== The Life of Thomas Story

I think it proper in this place to recount some of the
gracious dealings of the Lord with me from my early days.
I was not naturally addicted to much vice or evil; and yet,
through the conduct of rude boys at school, I had acquired, by imitation,
some things which tended that way.
However, as I came to put these things in practice, by word or by action,
I found something in me at such times suddenly surprising me with a sense of the evil,
and making me ashamed when alone,
even though what I had said or done was not evil in the
common opinion of those with whom I conversed,
or among men in general.
And though I did not know or consider what this reprover was,
yet it had so much influence and power with me
that I was much reformed by it from those habits,
which, in time, might have been foundations for greater evils and grosser vices.

Nevertheless, as I grew up to maturity, I had many flowings and ebbings in my mind,
and the common temptations among youth were often and strongly presented to me.
And though I was preserved from guilt as in the sight of men,
yet it was not so before the Lord, who sees in secret,
and at all times beholds all the thoughts, desires, words,
and actions of the children of men, in every age and throughout the world.
The lust of the flesh, the lust of the eye, and the pride of life,
presented their objects before me.
The airs of youth were many and potent, and strength, activity,
and comeliness of person were not lacking.
I furthermore found that a natural capacity of
mind and its many acquirements were not afar off,
and so the glory, advancement,
and preferment of the world were spread as nets in my view,
and its friendship began to address me with flattering courtship.

I wore a sword, the use of which I well understood,
and had foiled several masters of that science in the north and at London.
I rode with firearms also, and knew the use of them, yet I was not naturally quarrelsome.
This rule I formed to myself--never to offend or affront anyone willfully or with design.
And if, inadvertently, I should happen to disoblige any,
I should rather acknowledge my wrong than maintain or vindicate a wrong thing;
and I should take ill behavior from others and not be
offended wherever no offense was willfully designed.
But I was also prepared to punish an affront, or a personal injury,
whenever it was done in contempt, or with design.
Yet I never met with any such occurrence, save once,
and then I kept to my own maxims with success, so as neither to wound or be wounded.
The good providence of the Almighty was ever over me,
and well knew my intent in all my conduct.

But, in process of time,
as these motions of corruption and sin became stronger and stronger in me, so the Lord,
in great goodness and mercy,
made manifest to my understanding the nature and end of them.
And then, having a view of them in the true light, and the danger attending them,
they became exceedingly heavy and oppressing to my mind.
Then was the necessity of that great work of regeneration deeply impressed upon me,
but I had no experience or evidence of it having been wrought in me.
This apprehension greatly surprised me with fear,
considering the great uncertainty of the continuance of natural life,
and it began to put a secret stain upon the world, all its glory,
and all that I had to glory in.
I kept these thoughts within my own breast,
not knowing of any soul to whom I could seriously and safely divulge them.
And indeed no one, for a considerable time,
discerned my inward concern by any outward appearance,
which I found afterwards was much to my advantage and safety.

It is admirable by what various steps the Lord is pleased to
lead the soul of man out of this world and its spirit,
home to Himself.
Yet I am apt to think, that in His divine and unlimited wisdom,
He does not take the same outward method and steps with everyone,
but varies the work of His providence as their
states and circumstances may best suit and bear.

By an accident that befell me, I was further alarmed to consider my ways,
the uncertainty of life, my present state, and latter end.
It was this: Intending to go to a country church with an acquaintance,
as we were riding gently along, my horse stumbled, fell, and broke his neck,
and then lay so heavy upon my leg that I could scarcely draw it from under him;
yet I received no hurt.
Then, as we stood by him I had this consideration--that my
own life might have been ended by that occasion,
and I did not find myself in a condition fit for heaven,
having yet no evidence of that necessary work of regeneration.
This brought a great heaviness over my mind, which did not totally depart until,
through the infinite mercy of God,
I was favored with further knowledge and a better state.

Up to this time,
I had known the grace of God in me only as a manifester of evil and of sin,
a word of reproof, and a law condemning and judging those thoughts, desires, words,
passions, affections, acts and omissions,
which are seated in the first nature and rooted in the carnal mind,
in which the suggestions, temptations, and influences of the evil one work and prevail.
By this divine grace I was, in some good degree, enlightened, reformed,
and enabled to shun and forbear all words and acts known to be evil,
and I knew moral righteousness restored in measure in my mind,
and thereby brought forth in me.
I then became weaned from all my former acquaintances and company.
Indeed their manners and conversation (though not vicious,
for such I never liked) became burdensome and disagreeable to me,
for I saw they did not have the knowledge of God, nor such conduct as I wanted.
Nevertheless, I did not yet know the divine grace in its own nature, as it is in Christ,
that is, as a Word of faith, sanctification, justification, consolation and redemption;
for I was yet alive in my own nature.
The Son of God was not yet revealed in me; nor was I, by the power of His holy cross,
mortified and slain; being still without the knowledge of the essential truth,
and in a state contrary to Him, and unreconciled.

But the Lord did not leave me here.
In His matchless mercy, He followed me still by His holy admonitions,
and more and more inclined my mind in an earnest
inquiry after Himself and His own truth and Word.
I did not know of any in all the earth who could teach me these things,
for the world (as I judged by the general ways and courses of men,
of all forms and ranks) seemed universally and altogether ignorant of the Lord,
knowing only some historical and traditional hints concerning Him,
and of His doctrine and ways.
Such knowledge appeared to have little or no effect or
influence upon the minds and lives of men,
but instead, was a kind of dead knowledge or image,
and so man (being dead while they yet lived) did
not really and savingly believe in the true God,
and Christ Jesus, though they made profession and talked much of them.
I did not then know that the Lord had a people in the world who were
owned by His presence among them as His own flock and family.

My mind being truly earnest with God,
thirsting unto death for the knowledge of the way of life,
He was pleased to hear the voice of my necessity; for I needed present salvation,
and the Lord knew my case could not admit of further delay.
Being moved by His own free mercy and goodness,
even in the same love in which He sent His beloved Son
into the world to seek and save the lost;
on the first day of the second month, in the evening, in the year 1689,
being alone in my chamber, the Lord broke in upon me unexpectedly,
as quick as lightning from the heavens, and as a righteous, all-powerful, all-knowing,
and sin-condemning Judge.
Before Him my soul, as in the deepest agony, trembled, was confounded and amazed,
and filled with such awful dread as no words can reach or declare.
My mind seemed plunged into utter darkness,
and eternal condemnation appeared to enclose me on every side,
as in the center of the horrible pit, never to see redemption from there,
nor the merciful face of Him whom I had sought with all my soul.
But in the midst of this confusion and amazement, where no thought could be formed,
or any idea retained besides eternal death possessing my whole man,
a voice was formed and uttered in me, "`Your will, O God, be done.
If this be Your act alone, and not my own, I yield my soul to You.`"
In conceiving these words from the Word of Life, I quickly found relief.
There was all-healing virtue in them, and the effect was so swift and powerful that,
even in a moment, all my fears vanished as if they had never been,
and my mind became as calm and still and simple as a little child.
The Day of the Lord dawned,
and the Son of Righteousness arose in me with divine
healing and restoring virtue in His countenance;
so He became the center of my mind.

 In this wonderful operation of the Lord's power, denouncing judgment in tender mercy,
and in the hour of my deepest concern and trial, I lost my old self,
and came to the beginning of the knowledge of Him, the just and the holy One,
whom my soul had longed for.
I now saw the whole body of sin condemned in my own flesh--not in particular acts,
as though only traveling in the way to a perfect moral state--but by
one stroke and sentence of the great Judge of the living and the dead.
By this stroke the whole carnal mind, with all that dwelt therein, was wounded,
and death began to self-love, pride, evil thoughts, and every evil desire,
with the whole corruption of the first state and natural life.
Here I had a taste and view of the agony of the Son of God,
and of His death and state upon the cross,
when the weight of the sins of all humankind were upon Him,
and when He "`trod the wine-press alone with none to assist Him.`"
(Isa. 63:3) Now all my past sins were pardoned and done away, and my own willings,
runnings, searchings, and strivings were at an end.
All my carnal reasonings and conceivings about the knowledge of God
and the mysteries of religion (which I saw to be but natural),
were over--though they had long exercised my mind both day and night,
and taken away my desire for food and natural rest.
Now my sorrows ended, and my anxious cares were done away; and a true fear arose,
which I found to be an initiation into wisdom,
where I discovered the true Sabbath--a holy, heavenly, divine, and free rest,
and most sweet repose.
This deep exercise being over, I slept till the next morning,
and had greater and better refreshment and
comfort than I had felt for some weeks before.

The next day I found my mind calm and free from anxiety,
in a state like that of a young child.
In this condition I remained until night,
and at about the same time in the evening when the previous visitation had come upon me,
my whole nature and being, both mind and body,
was filled with the divine presence in a manner I had never known before,
nor had ever thought could be.
Surely none can form the least idea of such a thing,
besides what the Holy thing itself does give.
Divine Truth was now self-evident; there lacked nothing else to prove it.
I needed not to reason about Him,
for all of that was superseded by a divine and truly wonderful
evidence and light which proceeded from Him alone,
leaving no place for doubt, or for any question at all.
For as the sun, in the open firmament of heaven,
is not discovered or seen except by its own light,
and so the mind of man determines things by sight,
and without any train of reasoning--even so, and more than so,
by the overshadowing influence and divine virtue of the Most High,
my soul was assured that it was the Lord.
I saw Him in His own light,
by that blessed and holy medium which of old He promised to make known to
all nations--by that eye which He Himself had formed and opened,
and also enlightened by the emanation of His own eternal glory.
Thus I was filled with perfect consolation,
which none but the Word of Life can declare or give.
It was then, and not till then, I knew that God is love,
even a perfect love which casts out all fear.
It was then I knew that God is eternal light, and that in Him is no darkness at all.

I was highly favored also with a view of the manner of
the operation of the Almighty in assuming human nature,
and clothing His inaccessible divine light and glory therewith, even with an innocent,
holy, and divine soul and mind, comparable to the children of men.
This was like a veil, whereby the Most High condescended to the low condition of man,
and in whom also man, being refined as the tried gold,
and thereby fitted for the holy One, can approach Him, as by a proper medium,
and therein dwell with the Lord, and enjoy Him forever.

From that time forth, I desired to know nothing but the Lord,
and to feed on that bread of life which He alone can give,
and which He does not fail to minister daily.
Of His own free will and goodness,
He was pleased to open my understanding by degrees into
all the needful mysteries of His kingdom,
and the truths of His gospel, exercising my mind in dreams, in visions, in revelations,
in prophecies, in divine openings and demonstrations.
And by His eternal and divine light, grace, spirit, power and wisdom or word,
He instructed and informed my mind, yet allowing Satan to minister temptations also,
and deep provings, that I might see my own weakness and danger,
and prove to the utmost the force and efficacy
of that divine love and truth by which the Lord,
in His boundless goodness and mercy, had thus visited my soul.

All things I saw and heard in His wonderful works of
creation testified of Him--my own mind and body,
the animals, reptiles, and vegetables of the earth and sea,
their ranks and subserviencies one to another,
and all of them subservient to the children of men.
The sun, moon, and stars, the innumerable host of heaven,
and that boundless space in which they move without interfering,
or any way annoying one another, all depending one upon another.
I saw all of this was connected without division,
and was governed by the steady laws which the almighty Word and Decree,
who gave them being and formed them, placed them under, and settled them in.
But, as the crown of all, and the only true and certain way,
it pleased the Most High (by the effusion of His own
goodness) to reveal in me the Son of His love,
even His wisdom and power by whom He designed and effected all things.
Then I was taught to fear Him; then I was taught to love Him; then,
and not rightly till then, was my soul instructed and informed indeed.

But these secret operations were confined to my own breast,
so that no one knew anything of them.
An alteration was observed in me, but the cause of it was not seen.
I put off my usual pretension, my jovial actions and address,
and laid aside my sword (which I had worn, not through design of injury or fear of man,
but as a modish and manly ornament).
I burnt also my instruments of music,
and divested myself of the superfluous parts of my apparel,
retaining only that which was necessary, or deemed decent.
I ceased to attend the public worship,
though not with a design to join myself to any other sect, for I was apt to conclude,
from what I had observed, that these manifestations were peculiar to me,
and that there was not any people with whom I might properly associate.
I was also induced to believe that one day I would be
obliged to oppose the world in matters of religion,
but when or how that should be brought to pass, I did not foresee.

I remained in a still and retired state, and as the Book of Life was opened in my mind,
I read what the Lord Himself, by the finger of His power, had written,
and what the Lion of the tribe of Judah opened there.
The Scriptures of truth, written by Moses and the prophets,
the evangelists and apostles of Christ, were brought to my remembrance daily,
even when I did not read them.
These were made clear and plain to my understanding and experience,
so far as they related to my own state,
and also in a general way--though I lusted not to know any
mystery or thing contained in them besides what the Lord,
in His own free will and wisdom, thought fit to manifest.
As the nature and virtue of divine truth increased in my mind,
it wrought in me daily a greater conformity to itself by its own power,
and reduced my mind to a solid quietude and silence.
This was a state more fit for attending to the divine Word,
and distinguishing it from all other powers,
and discerning its divine influences from all imaginations and other motions.
And being daily fed with the fruit of the Tree of Life,
I desired no other knowledge than that which was thus given to me.

On the afternoon of the 21st day of the eleventh month, 1689,
silence was commanded in me (though not by me),
in which I was made to remain till the evening.
Then the scripture John 3:10 was brought to my remembrance.
I began to write in the following manner as things opened in my mind:

Jesus said to him, 'He who is bathed needs only to wash his feet,
but is completely clean'`" The washing of the feet signifies the cleansing of the ways,
and those who are washed in the laver of regeneration will walk in clean paths,
and bring forth fruit according to the nature of the Tree of Life.
Such will walk in faith, love, obedience, peace, holiness, righteousness, judgment,
mercy, and truth.
And whosoever says he is of the Father, and has not love, he is a liar,
and the living Word does not rule in him.
For whosoever has known the Word, and abides therein, has the Father,
because the Word of Truth bears witness of the Father;
and whosoever is born of God will keep His commandments.

Hear, O you mountains, and give ear, O you cedars of Lebanon--the Lord,
the light of Jerusalem, the life of saints, has put a song of praise in my mouth,
and caused me to rejoice in the valley of Jehoshaphat.
I was in the desert, and He led me forth by the power of His right hand.
I was fallen, and He stretched out His arm, and set me upright.
Yes, I was dead, and behold, He raised me from the grave!
I was also hungry, and He has fed me with the bread of His everlasting covenant.
I weakly fainted in the way,
but the King of the holy mountain revived me by the word of His promise.
He has laid my foundations with beauty, with precious stones of diverse colors,
and the architecture is all glory.
Fear not, you of low degree, for with our God there is no respect of persons.
Fear not, you little ones, for He showed you His lovingkindness of old,
and with Him there is no shadow of turning.
Awake, awake, you who sleep in trespasses and in sins,
for the trumpet sounds aloud in the city of our King.
Be raised, you dead, and stand upright before Him,
for He is true and faithful who sent forth His Word.
Conquer, O conquer, you holy love of God, all those who in ignorance oppose Your mercy.
Smite Your people with great thirst, O Lord God of mercy,
that they may drink abundantly of the waters of Your salvation.
Make them hungry, O Life of the just,
that they may eat abundantly and be refreshed by the bread of life everlasting.
Call them from the husks of outward shadows,
and feed them with Your hidden manna and Tree of Life.
Take from them the wine of the earth, which they have abused to abomination,
and give them the fruit of the living Vine at the Father's table.
Wash them in the laver of regeneration by Your Holy Spirit,
and cleanse them by Your righteous judgments, that they may retain Your love.
Consider their weakness, O Father of mercies; for they are flesh and blood,
and cannot see through the veil into Your holy habitation.
Rend the veil of carnal wisdom in the earthly mind, You wonderful Counselor,
and display Your glory in its full perfection.
Dissolve the great world of pride, covetousness, drunkenness, lying, cursing,
oppressions, filthy communications, and whoredoms,
and establish righteousness and peace forevermore.

I was silent before the Lord, as a child not yet weaned.
He put words in my mouth, and I sang forth His praise with an audible voice.
I called unto my God out of the great deep,
and He put on bowels of mercy and had compassion on me, because His love was infinite,
and His power was without measure.
He called for my life, and I offered it at His footstool; but He gave it me as a prey,
with unspeakable addition.
He called for my will, and I resigned it at His call;
but He returned me His own in token of His love.
He called for the world, and I laid it at His feet, with the crowns thereof;
I withheld them not at the beckoning of His hand.
But mark the benefit of the exchange!
For He gave me, instead of earth, a kingdom of eternal peace;
and instead of the crowns of vanity, He gave a crown of glory.
They gazed upon me; they said I was mad, distracted, and had become a fool.
They lamented because my freedom came.
They whispered against me in the vanity of their imaginations,
but I inclined my ear unto the whisperings of the Spirit of Truth.
I said, "`What am I, that I should receive such honor?`"
But He removed the mountains out of my way,
and by His secret workings pressed me forward.

+++[+++At another time he penned the following prayer:]


O Almighty, incomprehensible, and infinitely merciful Lord God,
forasmuch as none can enter into Your rest, unless he be regenerated and renewed,
I humbly beg, in the name and for the sake of Your Son Christ,
that You will be pleased to wash me in the water of life,
and purify my polluted soul with the holy fire of Your infinite love.
O that I may live in You, and walk in the living way of truth, love, peace, joy,
righteousness, holiness, temperance, and patience,
so long as You are pleased to continue me in this garden of labor.
Be my strength and my righteousness,
that I go not astray from Your paths through the frailty of this earthly tabernacle.
Give me daily the bread of life,
which You freely hold forth to the hungry all the day long.
And inasmuch as none can eat of this bread but
those who hunger and thirst after righteousness,
give me (O You who are my salvation) a fervent desire, and a saving faith,
a living faith, to lay hold on Your most certain promise,
that I may be made a partaker of the glory that is laid
up for Your servants in Your everlasting habitations.

Finding that the conversation of mankind was generally upon trifles,
not worthy of the thought of rational creatures,
and tending much more to vice than to virtue--and since my mind had
been a little renewed by the influence of the divine truth,
I remained much in silence and alone.
At times I had thoughts upon other objects,
which I wrote (without any search or labor) as
they were from time to time presented in my mind.
+++[+++The following written prayer shows that he also experienced an ebbing of
the divine life after seasons of enjoyment of which he has spoken.]


O Lord, take pity on a perishing soul, borne down under a multitude of vile affections,
trodden under foot by the insolence of the wicked one!
I faint under the yoke, O most faithful and true, and have no hope but in You.
My heart is weary with sighing under troubles, and my pains increase.
When shall my day come?
When shall I see the seal of my salvation?
O work in me the law of everlasting love, and fix my boundaries there forever and ever.
You who said to the worlds, "`Be finished!`" and it was so--say now unto my soul,
"`Be perfect!`" and it shall be done.
Purify me, O God, by the judgments of Your right hand,
and let Your mercies be ever before me.
Raise me, that I may praise You in the firmament of Your power.
Humble me, that I may exalt Your name in the midst of the nations.

A deep consideration entered into my mind con­cerning the
states of many persons in the national way of worship,
as also among the various dissenters from it.
I had occasionally heard some of their preachers,
particularly Dr. Richard Gilpin of Scaleb Castle, an able physician and an ancient,
celebrated preacher among the Presbyterians,
and I had observed many others who seemed to have sincerity
and good intentions in their respective modes of worship.
Therefore a question arose in me whether it might not be through my own fault,
for lack of the true knowledge of God in myself prior to this time,
that I had been kept from enjoying His presence among them as I now did,
ever since I had been visited by the Lord and drawn
into retirement by the comfort of His secret presence.
Upon this consideration,
I determined to go again and see whether the good
presence of the Lord would be manifested in me there,
as it was alone in my retirement.

The place I went to was called St. Cuthbert's, in the city of Carlisle,
where there were usually prayers and a sermon in the afternoon on first-days,
but not with that pomp, noise, and show, that attended the service at the cathedral.
Being seated there with my mind retired inward to wait
upon the Lord (as He Himself had taught me to do),
I found that the Lord would not own their worship by His sensible presence,
nor me in that place, though He Himself is omnipresent.
Instead,
my mind became filled with darkness and overwhelmed with trouble to
so great a degree that I could hardly stay till the time was over.
But lest I should do something which might be looked upon as indecent,
I continued to the end, and then, returning to my chamber in trouble,
I went among them no more.

However, though I declined all outward worship (or that which was called so),
determining to follow the Lord wheresoever it might please Him to lead me,
yet I found universal love, good will, and compassion in my mind, to all sorts of people,
whether Protestants of different denominations, Romans, Jews, Turks, or heathens.
But I observed their several religions to be mostly the effect of education, tradition,
or chance.
For he who is born and educated among the Protestants of any sect respectively, is such.
He who is born and educated among the Romans, is a Roman.
And so it is with all the rest,
until by circumstance or interest they change from form to form;
or sometimes (though more rarely) through the
inward convictions of the Holy Spirit of God,
they obtain a right understanding and come to worship Him in truth.
Therefore I stood still, and waited for the further leadings of the Lord,
and the evidence of His presence as to what to do, or where to abide,
though the Protestants, in general, and especially the national church,
were still nearer to me than any other sect.

Thus, the world, in general,
appeared to be dead (like walking statues) with respect to the true knowledge of God,
notwithstanding the truth of some notions they held in
relation to matters of fact and literal interpretation.
I did not then see that the Lord God had any collective body of people in
that day who truly worshipped Him according to His own institution;
nor did I know of anyone on earth who had learned of God by His own free grace,
and who could communicate to me that which I could neither ask nor think.
However, I found in due time I was mistaken in these things, even as the prophet of old,
who thought he had been alone while all Israel departed from the Lord.

As the life of the Son of God prevailed in me, I became more and more innocent, humble,
loving, and charitable to the poor, to whom I gave money according to my ability,
and without ostentation, or expectation of reward.
One instance of this I think might be proper to relate,
as it was attended with some particular circumstances.
At the time King William III was subduing Ireland,
some persons and families fled from the inconveniences
and hardships of the war and came into England.
Among others,
an Independent minister and his young son came to my
father's house in Carlisle where I then lived,
and being in need, requested charity.
I gave him half a crown, which, being more than he expected or had received elsewhere,
gave occasion for him to enter into discourse concerning some points of religion.
He civilly asked of me what form of worship I attended.
I replied I had formerly frequented the national worship, according to my education,
but that for some time I had declined it, as also all other outward forms,
keeping retired in my chamber on the usual days appointed for that purpose.
When he heard this,
he asked if his company might be acceptable the next Lord's day (as he called it),
for the national worship was not agreeable to him.
I gave liberty, and he and his son came accordingly to my chamber,
where I was sitting alone in silence, waiting upon the Lord.
After a civil reception and short pause of silence,
he began to magnify the great providence of God in re-
establishing and advancing the Independents and Presbyterians,
who had been so much hated, persecuted, and suppressed,
but were now to be made the chief instruments of deliverance, restoration,
and reformation to the right way of the Lord, and to His own glory.
As he spoke, I observed that he himself was not upon the true foundation,
nor acquainted with the mind of the Lord on that account,
but rather spoke from his own imagination and partiality to his own sect,
according as he and they desired it should have been.
His mind was natural and carnal,
and his views were outward and directed toward the power and dominion of this world,
even as the Jews were at the time of Christ's appearance among them.

As soon as he came to a period,
I found my mind filled with the sweetness and meekness of divine truth, and replied,
"`The divine providence is indeed great over the children of men,
and apparently over this nation and her dependents at this day.
And indeed, the necessity of a right and thorough reformation is very great,
and in the proper time and way of the Almighty it will surely be brought to pass.
But it will be neither by the means nor the instruments which are now in your view.
For all the contenders, one against another, by destructive force,
are of one spirit divided against itself, under different forms and views,
and the strongest will advance themselves and their own way.
But these cannot, by such means, reform either themselves or others,
as they ought to do in the sight of God, for He does not approve or countenance violence,
bloodshed, and unrighteousness in one sect, and then condemn the same things in another.
The Lord will therefore bring about the right
reformation by instruments of a different kind,
and by another means and way, as it is written, 'Not by might, nor by power;
but by My Spirit, says the Lord.'`" Upon this the stranger was much broken in spirit,
and as he sat by me the tears ran down his beard and dropped upon his knee.
Then, being filled with love (the same which had reached him from my spirit),
he embraced me in his arms, rejoicing that he had met with me,
but said no more on any religious subject.
Soon after he departed, and I saw him no more.

I now proceed with the account of my further pro­gress.
In writing the last paragraph of a piece, the people called Quakers were suddenly,
and with some surprise, brought to my mind.
So strongly were they impressed upon my remembrance that, from that time forward,
I had a secret inclination to inquire further concerning them, their way and principles.
It was sometime in the fifth month, in the year 1691, when an opportunity was presented.
The occasion took place in the west part of Cumberland,
when lodging at an inn kept by one of that profession.
As I inquired of the innkeeper concerning some points of their religion,
I perceived no material difference between his sentiments and mine;
and he also perceived I was nearer to acknowledging them than he, or perhaps any other,
had thought; for I had formerly opposed the same man in some things.
This gave him occasion to inform me of a meeting to be held the next day,
at a country village called Broughton.

As I had been desirous to be rightly informed concerning that people,
and to see them as in truth they really were, I was pleased with the opportunity.
So the next morning the Friend and I set forward toward the meeting.
He being zealous to have me further informed and convinced of the truth of their way,
spoke of many things as we rode along, and no doubt had good intent.
But my mind was composed,
and its attention directed towards God (who knew I wanted only to see the truth,
and not to be deceived), so I could not take any distinct notice of what the Friend said.
Perceiving this, after some time he desisted and said no more,
and we rode some miles together in profound silence,
in which my mind enjoyed a gentle rest and
consolation from the divine and holy presence.

We arrived at the meeting a little late, when it was already fully gathered,
and I went in among the throng of people on the benches and sat still
among them in an inward condition of mental retirement.
One of their ministers, a stranger, began to speak to some points held by them,
and to declaim against some things held by others--particularly predestination,
as it is asserted by the Presbyterians.
I took little notice of what was said, not doubting that, like all other sects,
these might have something to say both for their own principles,
and against the opinions of others.
My only concern at that time was to know whether they were a people gathered
under a sense of the enjoyment of the presence of God in their meetings--or,
in other words,
whether they worshipped the true and living God in the life and nature of Christ,
the Son of God, the true and only Savior.
The Lord answered my desire according to the integrity of my heart;
for not long after I had sat down among them,
that heavenly and watery cloud overshadowed my mind and
broke into a sweet shower of celestial rain.
Then, the greatest part of the assembly were broken together,
dissolved and comforted in the divine presence of the true, heavenly Lord,
which repeated several times before the meeting ended.
In this same way, and by the same divine power,
I had often been favored by the Lord when alone,
when no eye but that of heaven beheld me.
And now,
even as many small springs and streams descend
into one place and form a deep and weighty river,
so I felt an increase of the joy of the salvation of God while
meeting together with a people who were gathered by the living
God into a sense of His divine and living presence,
through Jesus Christ, the Son of God and Savior of the world.
And my joy was the more full,
perceiving I had been under the like mistake as the prophet of old,
but now was otherwise informed by a sure evidence, by the witness of the divine truth,
in which no living soul can err or be deceived--being self-
evident and undeniable in all those who truly know Him.

Our joy was mutual and full, though in many tears,
as in cases of the deepest and most unfeigned love.
Friends there were sensible I was affected and tendered with them by the
influence of the divine truth that they knew and made profession of,
and they concluded it had been at that time, and not before,
that I was convinced and had come to the knowledge of the way of truth.
Their joy was like the joy of heaven at the return of a penitent;
and mine was like the joy of salvation,
seeing the work of the Lord so far carried on in the earth,
when I had not long before thought there had scarcely been any true and living faith,
or knowledge of God in the world.

When the meeting had ended,
the peace of God which passes all the understanding of natural men,
and is inexpressible by any language but itself alone,
remained as a holy canopy over my mind, in a silence out of the reach of all words,
and where no idea but the Word Himself can be conceived.
I was invited, together with the ministering Friend,
to the house of the ancient widow Hall, and so went willingly with them.
However, there remained a sweet silence commanded within me,
and so I had nothing to say to any of them until the Lord was
pleased to draw the curtain and veil His presence.
Then I found my mind pure,
and in a well-bounded liberty of innocent conversation with them.
Having stayed there a short time, I was invited to dinner at the house of Richard Ribton,
an ancient and honorable Friend in the village, where I was made kindly welcome,
and where I had great freedom of conversation.

I was now satisfied beyond my expectation concerning the true people of God,
in whom the Lord had begun, and in a good measure carried on,
a great work and reformation in the earth.
I then determined to lay aside every business and thing which might hinder
or veil in me the enjoyment of the presence of the Lord (whether among His
people or alone) or obstruct any service whereunto I might be called by Him.
I cast off all things of an entangling or confining nature,
not regarding what the world might say, or what name they might impose upon me.

When I had finished with the business which had brought me into that part of the country,
I returned to Carlisle.
After this I attended some other meetings of Friends,
but little notice was taken of it by any of my relations or
acquaintances until the time of the court sessions at Carlisle,
where some Friends were prisoners in the county jail for non-payment of tithes.
Various other Friends attended these sessions (as was their
custom) to help prevent trouble or hurt to any of the Society,
and to minister counsel or other help as need might be.
These Friends gathered for a meeting at Scotby, about two miles from the city,
and there I went also.
During the time of the meeting I found an unusual load upon my spirit,
and a hardness in my heart to such a degree that
I could hardly breathe under the oppression.
I had no sense of the comforts of the divine presence there,
but the heavens were as thick brass, and their bars as strong iron.
But though I had no enjoyment in myself,
yet I was sensible that the presence and goodness of the Lord were there,
and many were greatly comforted thereby.
I therefore con­cluded that my condition of mind was from some other cause,
and not related to the state of the meeting in general.

After the meeting had ended, one of them asked me how I was.
I answered indifferently, so that he and some others perceived my spirit was oppressed,
and sympathized with me therein.
I could not, all this time, perceive the particular matter which thus affected me,
for I knew of nothing I had done or said to bring it upon myself.
But that evening, being returned to my father's house very solitary, silent, and inward,
there came in one Thomas Tod who desired to speak with me.
He told me that he had a trial coming on the next day
concerning certain houses of his in the town of Penrith,
which were the greatest part of all he had in the world.
One of the witnesses to his deed of conveyance was dead, another had gone into Ireland,
but he hoped that I, being the third, and having had prepared the documents,
would help him against his unfair adversary.
He desired me to be in readiness in the morning,
for the trial was likely to come on very early.

As soon as he began this relation,
the Word of life began likewise to work in me in a very powerful manner.
I sensibly felt the hammer of the Lord,
and saw it to be lifted up against that hardness
of heart which had for some time been my state.
My heart began to be broken, softened, and dissolved,
and the sense of the love of God was then in some degree renewed.
Then I saw plainly that this was the hard thing I had to go through,
and that now was the time of trial wherein I must take up the cross of Christ,
acknowledge His doctrine in this point fully and openly,
according to the understanding given me.
I saw I must despise the shame, reproach,
and whatever sufferings (which I well knew would ensue quickly),
or I must forsake the Lord forever.
For if I denied His doctrine, having been given such a clear and plain sense of it,
this would be a denying of Him before men.
And if I denied Him,
I could expect no less (according to His word) than to
have been immediately and forever denied by Him,
and left under that hardness of heart and lack of enjoyment of
His divine presence with which I had been favored before.
But, by reason of the advances of His Word and work in me at that time,
my heart inclined to Him.
And by the time my acquaintance was done speaking,
I was furnished with a full resolution to give him a plain and direct answer,
which was according to this manner:
"`I am truly concerned and will appear and testify what I know in the matter,
and do whatever I can for you in that way; but I cannot swear.`"
This was so great a surprise to him,
both from the nature of his case and the confidence he had of
my ready compliance--he having had no suspicion of my present
condition till that moment--that he broke into a passion,
and with a curse, said, "`What, you are surely not a Quaker!`"
Though the divine presence had sensibly returned in me,
yet upon this question I was again silent until I felt clear
in my understanding what to answer in sincerity and truth.
For since nobody before that time had called me a Quaker, I had not yet assumed the name.
Nor did I then know whether I had complete unity with
all their tenets as might justify me in owning the name,
for I had known them only in the unity of divine love and life,
and not as yet heard all of their doctrines.
But the power of the Life who forbids all oaths and swearing,
arose yet clearer and fuller in me.
The Lord opened my understanding, cleared my way, and enabled me to reply,
"`I must confess the truth: I am a Quaker.`"

As this confession brought me still nearer to the Son of God,
so that I felt His love yet increasing in me,
so it likewise heightened the perplexity and disturbance of my friend,
whose case thereby became the more desperate in his own view.
Upon this, in an increase of heat and expressions that suited his obvious disappointment,
he then threatened to have me fined by the court and
proceeded against with the utmost rigor of the law.
"`What!`" he said, "`Must I lose my estate because of your groundless notions and whims?`"
But the higher my enemy arose and raged in this well-meaning but mistaken man (who,
without design, had became the instrument of my trial),
the fuller and more powerful was the love of God in me,
whose cause I had now upheld through His own aid and
the power of an endless life made manifest in me.
I replied in that calm resignation to the will of God which
the life of the Son of God teaches and enables to perform,
"`You may do what you think proper that way,
but I cannot comply with your request in this matter, whatever be the outcome.`"
He then departed under great dissatisfaction,
with all the threats and reproaches that his enraged
passions could suggest under a view of so great a loss.

Immediately I retired into my chamber,
for I perceived my grand enemy to be yet at work to introduce a slavish fear,
and by that means to subject my mind and bring me again into captivity and bondage.
I desired to be alone and free from all the interruptions of company,
that I might more fully experience the arm of the Lord and His
divine instructions and counsel in this great exercise.
The enemy, being a crafty and subtle spirit,
wrought upon those passions which were not fully subjected,
and artfully applied himself to my natural reason and understanding,
which were not fully illuminated.
He urged the fine and imprisonment, and the hardships accompanying that condition,
and how little help I could expect from my father or friends,
who would be highly displeased with me for so foolish and unaccountable a resolution,
as they would think it.
He also suggested the scoffing, mocking, derision, scorn, contempt,
loss of friends and friendships in the world, with other similar inconveniences,
hardships, and ill consequences.
During all this time, from about eight in the evening till midnight,
the eye of my mind was fixed upon the love of God, which still remained sensibly in me,
and my soul cleaved to it in great simplicity, humility, and trust,
without yielding to Satan and his reasonings on those subjects,
where flesh and blood in its own strength is easily overcome by him.
But about twelve at night, the Lord put him to utter silence, with all his temptations,
and the life of the Son of God alone remained in my soul.
Then, from a sense of His wonderful work and redeeming arm,
the saying of the apostle arose in me with power,
"`The law of the Spirit of life in Christ Jesus
has made me free from the law of sin and death.`"
Then the teachings of the Lord were plentiful and glorious,
and my understanding was further cleared.
His holy law of love and life settled in me,
and I was admitted into sweet rest with the Lord my Savior,
and given up in perfect resignation to His holy will,
in whatsoever might relate to this great trial of my faith and obedience to the Lord.

In the morning I went up toward the hall where the judges sat,
expecting to be called as a witness in the case before mentioned.
But before I reached the place, I saw my said acquaintance approaching me,
with an air in his countenance denoting friendship and affection.
When we met, he said, "`I can tell you good news!
My adversary has yielded the cause, and we are agreed to my satisfaction.`"
Upon hearing this, I stood still in the street,
and as I reviewed in my mind the work of the
Lord in me the night before (as already related),
this Scripture came fresh and livingly into my remembrance,
"`It is God who works in you both to will and to do of His good pleasure.`"
I was sensible it was the Lord's doing, and accounted it a great mercy and deliverance.

Nevertheless, by this means I was exposed to the view and observation of all,
the pity of many, and the scoffs and censures of the baser and more ignorant sort.
This event happening at the time of the court sessions,
and people from all quarters being there,
I quickly became the common subject of discourse and debate.
Few could believe the report that I was now a Quaker,
and many came to see and talk and wonder.
When they happened to see me afar off in the streets, they would come in crowds to gaze.
Some would take off their hats, and pretend to show more than ordinary complaisance,
saluting me as at other times; but as I did not make any return of that kind,
some would smirk, and giggle, and scoff, and grin, and run away in loud laughter,
saying I was mad.
Some others were struck with another passion--they turned pale, looked sorrowful,
and returned weeping.
And one who had been educated at a university, to show at once his temper, manners,
and learning, after he had gazed upon me a while with many of the baser sort, cried out,
"`He knows not a genus from a species!`" when there was
not anything previous leading to such an expression.
Yet he was mistaken in that; for I knew very well that dog is a genus,
and that bull-dog and blood-hound are distinct species of that genus.
And at that time,
I saw the nature and way of these brute animals too much appearing in that giddy mob,
though I said very little to any of them,
but instead gave them my face to their fill of gazing.

Some, who but a day or two before dared not have given me a disobliging look,
now insulted and triumphed.
This put me in mind of a saying of Job, "`But now they mock at me, men younger than I,
whose fathers I disdained to put with the dogs of my flock.`"
Yet the fool's pretended pity and instruction,
who could not see and pity his own miserable case, was the hardest to bear.
But all these things did not provoke or move me;
for the grace and presence of the Lord were with me,
and these were my strength and preservation.
Indeed, my heart was surrounded with a rampart of invincible patience,
and my soul was filled with divine love.
This treatment gave me a much clearer view of the low, mean, miserable,
brutish state of many men than I ever had before, or could have imagined.

When the business of the court sessions was over,
some of my acquaintances (gentlemen both of town and country,
who wished me well in their own way) thinking I had been deluded by the Quakers,
consulted how to restore and reclaim me (though I do not think any of
them knew what the true Quakers or their principles were).
Several ways were proposed to help me,
especially by a meeting and consultation with some of the clergy, who, they imagined,
might solve any doubts I might be under,
supposing my sentiments to be but lately embraced, and I not yet settled in them.
The clergy generally shunned me,
and I quickly observed a particular enmity in them against me,
though I had no more aversion to them as men than to others.
But some of the above-mentioned well-wishers,
having seen my former levity and cheerfulness turned to silence and gravity,
supposed me to be melancholy.
These got together in a tavern, along with my father,
and intended to have me drink a hearty glass,
seeking to raise my spirits into a more sociable temper,
and bring me off from such thoughts.

While they were contriving this scheme, I was retired alone in my chamber,
and favored with a sense of the good and soul-nourishing presence of the Lord.
But after some time, a concern came upon me,
which gave me to expect something was in agitation concerning me.
Soon after, an acquaintance who was an attorney at law,
came to me from the company and mentioned a certain
gentlemen who desired to see me at the tavern.
I was not hasty to go, nor did I refuse,
but looked for the countenance of the Lord in the matter.
After a short while, my father and some others grew impatient to have me among them,
and likewise came to see me.
I arose from my seat when they came in,
but did not remove my hat to them as they did to me,
upon which my father fell to weeping and said I did not use to behave so to him.
I entreated him not to resent it as a fault,
for though I now thought fit to decline that ceremony,
it was not in disobedience or disrespect to him or them,
for I honored him as much as ever, and desired he would be pleased to think so.
Through grace, I became aware of their intentions,
but soon found freedom in my mind to go among them.

When we came to the tavern, they placed me so that I was in the midst of them,
and then began to put the glass around; and in order to relish it the more,
they proposed to drink to the health of King William.
The glass went forward till it came to me, and then I told them,
"`I wish both the king and them well, and if I could drink to the health of any,
I should more especially drink to the king's,
but I shall do such things no more,`" and so refused it.
The glass never went around, for several of them fell to weeping and were much broken,
and all of them were silenced for a time.
When this was over, some of them said they believed I intended well in what I did,
and that every man must be left to proceed in
the way he thinks right in the sight of God.
So we parted in solid friendship.

It was the secret grace of God which wrought this; and to Him, the Lord alone,
I did impute it.
Many disputes have I had with many people since, in various parts of the world,
but I never began any controversy, being always on the defensive side.
And I rarely entered upon any point in question, with any man or sect,
until I felt the divine truth risen over all in my own mind, and my will subjected by it.
And my next care was generally not to provoke my opponent; for, by keeping him calm,
I had his own understanding, and the measure of grace at work in him,
to work against the error for which he contended.
For when a man gets into a passion, he may be confounded, but not convinced.
Passion is like a scorching fire without light.
It suspends the understanding and obstructs the way to it,
so that it cannot be gained upon or informed.
So my chief aim in disputes in matters of religion has been to
gain upon people's understandings for their own good,
or else all will end in vain and unprofitable jangling, which displeases the Holy One.
In two or three times in the course of my life,
in too hasty of engagements in my own strength, my mind has been ruffled,
and though I have gained the point by force of
argument (from the principle of reason only,
and not from the principle of divine Truth),
yet I have not had that peace and satisfaction of mind
which is to be found in the virtue of truth alone.
And this has also taught me to be totally silent,
and sometimes even insulted by ignorant people, as if I had nothing to say,
until the power and virtue of truth has arisen in my mind.
But when it arises, it has never failed, by its own light and evidence,
to support its own cause.

I had not, all this while, conversed with any Friend about their principles,
or read any of their books, nor did any of them come near me for some time,
for my father would not then allow them to come to his house.
Some of them not long after sent me three small books, which I took kindly,
knowing it was well intended.
But I was favored of the Lord with something more excellent than books,
which gave me both understanding and support in time of need.
Indeed, that book, which had been sealed as with seven seals, was now, in measure,
opened by the powerful voice of the Lion of the royal tribe,
the Holy Lamb of God--even the book of the eternal law of God,
the law of the Spirit of life from the Father, by Christ the Son,
the Redeemer of the world, and it was my delight to read day and night therein.
By this I profited more in a short time in the
knowledge of God and the things of His holy kingdom,
than if I could have read and understood all the written and printed books in the world.
I therefore declined reading the Friend's books till a more proper season,
and then I looked into one of the books concerning prayer.
For surely, the reading of good books (especially the holy Scriptures,
the chief of all) is highly profitable and commendable.

I went constantly to the meetings of Friends, where, in a state of silence,
my heart was frequently tendered and broken by the divine influence of truth,
to my unspeakable satisfaction.
I found there a holy pleasure and enjoyment which neither the world,
nor anything therein, could afford.
Our meetings in the north in those days were
frequently broken and melted when in silence,
as well as when under a powerful, living ministry by the Word.
My delight was continually in the truth, and I desired no company but that of Friends.
I frequented meetings on all occasions,
where my heart was often made so tender by the truth
that it reached and affected others through me.
In this way I became very dear to Friends, and they to me.
And as this tenderness was something of an involuntary ministry,
being an operation of the Spirit of God without words,
I found for some time great satisfaction and safety in it.

Desiring to see Friends in some other places, I took a short journey with Andrew Taylor,
a powerful and able minister in his day of an affable and cheerful temper,
and one of my particular friends.
On the 20th day of the twelfth month, 1691, we went from Heatherside, in Cumberland,
and that night lodged two miles beyond Alston.
The next day we journeyed to Welgill; on the 22nd to Thomas Williamson's;
on the 23rd to Walkmill; on the 24th to Steel,
and on the 25th to Benfieldside-- having meetings at several of these places.
From there we went on the 27th to Newcastle, and lodged at Jeremiah Hunter's,
being at their meeting the next day.
On the 29th we went to Caleb Tenent's at Shields, and had a meeting there.
On the 1st day of the first month a meeting was appointed at Sunderland.
We intended to cross the River Tyne at Shields in order to attend,
but the wind being very strong,
the horses were frightened with the fluttering of the sails as we put off from the key,
so that Caleb's mare, being strong and sprightly,
jumped overboard and carried him along with her as he strove to stop her by the bridle.
They both went under the water, for it was very deep,
but as good Providence would have it, the mare came up with her head towards the shore,
and Caleb came up behind her at so little distance, and with such presence of mind,
that he laid hold on her tail,
and got on shore without any other hurt than the surprise and the wet clothes.

The meeting at Sunderland proved a very comfortable
time in the enjoyment of the good presence of the Lord,
with which my heart was plentifully furnished.
In the time of silence,
I was greatly tendered and soon bathed in a flood of tears from divine, melting love;
and the like effect was seen over the entire meeting.
After this, Robert Wardell, a ministering Friend at whose house we lodged,
spoke some sentences,
by which I perceived he thought I should have uttered
some words by way of public ministry at that time.
But I did not apprehend my time was then come for that service, and besides,
the ministration of the Word, by a more immediate operation, had had the same effect,
or perhaps greater, than the utterance of many words.

After the meeting many Friends came to me and expressed so much love and
respect as gave me occasion to consider what could be the reason of it,
for they were all strangers to me, and I to them.
Being but a child in the knowledge of the invisible operation
of the Word of truth and its effects by instruments,
even in a way of silence and sympathy, I had looked at its effects only in myself,
for my own strength and consolation.
I did not yet know that when truth broke in upon one in an eminent manner,
it often affected the living part of the meeting the same way, at the same time.
It has since become clear to my understanding, by experience,
that there is an unspeakable communication of divine love
through the one Spirit among the sanctified in Christ,
as the members of Christ sit together in a state
of holy silence in their heavenly places in Him.

*   *   *

Thomas Story went on to become an extremely gifted and
serviceable minister in the Society of Friends,
traveling all over England, Ireland, Scotland, Holland, Jamaica, Barbados,
and the American colonies.
He was known for both his spiritual depth and his intellectual genius,
and his writings became very influential among Quakers.

In 1695 Thomas Story befriended William Penn,
and in 1698 sailed to Pennsylvania (at Penn's request) where
he held several public offices in the developing province.
He remained there for sixteen years,
always putting ministerial duties in the Lord's body above his business in the world,
and even declining positions and advancements
that might encumber his service to the church.
He married in America, but lost his wife after only six years,
and then returned to England where he continued a minister until his death in 1741.