== Salvation by Christ

An Excerpt from the Journal of Thomas Story

I begin then with the purpose of God to make man; when he was perfected as man,
God breathed into him the breath of life from Himself;
whereby man became spiritually minded; alive in God who is a spirit;
like unto God in his mind or inner man;
the image of Him who created him in righteousness and true holiness.
In this state God gave man a positive commandment, not of action,
but rather of abstinence, connecting death and disobedience together.

Man, in the beginning, by the voice of God, knew the command of God,
and his duty to Him thereby,
and believed the Word of God for a time (which Word is the divine, eternal,
essential Truth).
As long as man continued in the faith of the Word,
he lived in the divine light and life of it;
and stood and remained in the moral image of God--righteous, holy,
uncorrupted and undefiled.

But when the mind of man, through temptation, disbelieved the Word of God,
in which he at first believed, and adhered unto another voice, which was false and a lie,
the mind of man thereby became corrupted and incapacitated to enjoy the life
and light of the divine Word any longer--according to the promise of God,
which says, "`In the day you eat thereof you shall surely die.`"
Thus the fall of man was his departure from the
divine life and light of the eternal Word of God,
His wisdom and power,
and the redemption of man is his restoration (and more
than restoration) to the knowledge of it,
and being re-united with it.

And as the love, mercy, and compassion of God was still towards man,
He gave him a promise by the same Word,
"`That the Seed of the woman should bruise the serpent`'s head,`"--
that subtle spirit which had betrayed her--so that in the fulness of
time the woman should be instrumental in the restoration;
which accordingly is mercifully fulfilled.
For when the angel of God was sent to Mary, the holy Virgin, he said, "`Hail,
you that are highly favored, the Lord is with you; blessed are you among women.
And behold, you shall conceive in your womb, and bring forth a Son,
and shall call His name Jesus.
He shall be great, and shall be called the Son of the Highest;
and the Lord God shall give unto Him the throne of His father David:
and He shall reign over the house of Jacob forever,
and of His kingdom there shall be no end.`"

But Mary did not at first believe the angel.
"`And the angel answered and said unto her, "`The Holy Ghost shall come upon you,
and the power of the Highest shall overshadow you:
therefore also that holy thing which shall be born of you, shall be called the Son God.`"
And Mary said, Behold the handmaid of the Lord, be it unto me according to your word.
And the angel departed from her.`"

And that it might be certainly known, in the fulness of time, unto all mankind,
who this sacred Person is, and what is the manner of His coming and appearance,
both to Jew and Gentile, He was to be made manifest unto the Jews first,
under the name and character of Jesus, a Savior, and being anointed of God,
with all the divine in-dwelling fulness, is thereby called Christ; and under both titles,
He is called Jesus Christ,
"`the anointed Savior,`" proposed as the object of faith unto all nations:
First unto the Jews in the flesh, as born of the Virgin; and secondly, unto the Gentiles,
as "`the true Light, who enlightens every man who comes into the world.`"

Now consider: 1st--The testimony of good old Simeon concerning Him,
through the Holy Ghost,
that "`He is a Light to bring revelation to the Gentiles,`" and in that respect,
their light and salvation, according to the promise of the covenant of God aforegoing.

2ndly--The evidence of John, where he is full and express, saying,
"`In the beginning was the Word, and the Word was with God, and the Word was God.
In Him was life, and the life was the light of men.
That was the true light which enlightens every man who comes into the world.
And the Word was made (or assumed) flesh, and dwelt among us, (and we beheld His glory,
the glory as of the only begotten of the Father) full of grace and truth.
And of His fulness have all we received, and grace for grace.`"

3rdly; The witness of Christ himself, where He says, "`I am the light of the world;
he that follows Me, shall not walk in darkness, but shall have the light of life.`"
Again, "`Jesus said unto them, Yet a little while is the light with you; walk,
while you have the light, lest darkness come upon you:
for he that walks in darkness knows not where he goes.`"
"`While you have light, believe in the light,
that you may be the children of the light.`"

And as the Father has promised and offered His Son, and as He is that Light,
as well as the new and everlasting covenant with mankind for
their restoration and establishment (not of works,
but of life); so now, whoever will enter into this covenant with God,
must first believe in Him whom God has sent,
and in the way and manner in which He has sent Him, according to His promises.

Now a covenant is not on one side only, but on two sides at least.
Therefore God, who is divine eternal love, infinite in goodness and mercy,
is pleased of His own nature and love to mankind thus to send His Son,
the Lord Jesus Christ, into the world, who,
by a voluntary death upon the tree of the cross,
according to the fore-determined council and purpose of the Father,
declared His mercy and free pardon of the sins of the whole world,
upon terms that were suitable to the state, reason, and understanding of mankind:
that is to say, upon faith in God the Father of all and in Jesus Christ the Son of God,
and repentance from dead works.
These are the reasonable and necessary terms
required of mankind on our side of this covenant,
in order that we may be restored to the true knowledge of God,
and made capable of being united to God,
through Christ the Mediator between God and man in this covenant;
for it is by and through Him that we are brought into,
and stand steadfast and immoveable in this covenant forever.

We must then receive the Savior in the way in which He is sent and offered unto us;
not only as He is offered upon the cross for the expiation of the sins that are past,
but also as He is the divine Light, enlightening our hearts and understandings,
as directed by Christ himself, where He says, "`While you have light,
believe in the light, that you may be the children of light`"--that is, children of God,
who is that light.
So then, even as Adam fell from the true knowledge of God,
and a sense of His divine love, presence, goodness, and other attributes,
through unbelief; so we, his posterity after the flesh,
may all arise and be restored by faith in Christ, the second Adam, the Lord from heaven,
the life-giving Spirit.
This restoration is not unto the animal life,
which by nature we already have, and in which we are enmity to God and all His ways,
but unto eternal life, that we may all know what that Word means, "`As in Adam all die,
even so in Christ shall all be made alive.`"
And, "`as by the offense of one, judgment came upon all men to condemnation: even so,
by the righteousness of One,
the free gift came upon all men unto justification of life.`"

Again,
as to the plain indication and character which the Holy
Scripture has put upon this divine light,
whereby we may know it (even as natural men) by its effects,
the evangelist says that the Comforter, which is the Holy Ghost, the Spirit of Christ,
who is that light, "`when He is come,
(or made manifest) He will convince the world of sin, and of righteousness,
and of judgment.`"
And says the apostle, "`All things which are reproved, are made manifest by the light:
for whatsoever does make manifest is light.`"
Again, "`This is the condemnation,
(of the world) that light (even this Light) has come into the world,
and men loved darkness rather than light, because their deeds were evil.`"

This is He, that divine eternal Light,
to whom John the Baptist and the apostles of Christ bore testimony;
and in a special manner the apostle Paul, who was sent by Christ to the Gentiles,
"`to open their eyes, and turn them from darkness to light,
(even unto He who is that Light) and from the
power of Satan unto God;`" that being so turned,
"`they might receive forgiveness of sins,
and an inheritance among them who are sanctified by faith in Him, the Lord.`"
