== Letter to a Doubter

[.chapter-subtitle--blurb]
An Excerpt from the Journal of Thomas Story

Soon after we arrived at London, I received a letter from an unknown hand,
upon subjects of great importance; my answer to which,
including the material part of the said letter, was as follows:

[.salutation]
My unknown friend, K. P.

Since I came to London, about a week ago, I received a letter from you,
by my friend E. F., dated the 5th of December last,
occasioned by one of mine to that friend, of which I was glad.
I am persuaded of your sincerity, and that your intent thereby is good;
and not as a busy-body, to be meddling in other men`'s matters,
but to be satisfied in things doubtful to you: and under that consideration,
I find freedom to answer your request; which I could not well do sooner,
by reason of several interposing concerns.
And though this may be lengthened, as well by my transcribing the several parts,
or genuine purport of yours, as also by the extensiveness of the subjects treated on;
yet, if thereby I can assist you with better information,
I shall think my pains well bestowed, having no end in what I shall write,
but the promotion of God`'s everlasting truth,
and the better being of your never-dying soul.

[.numbered-group]
====

[.numbered]
1+++.+++ You say in your letter, that you, providentially, (for so to be sure it was,
since a hair of our head falls not to the ground without a
providence) met with a letter of mine to my Friend E. F.,
and was not a little surprised at the reading of it,
to find so great a sense of the love of God from one of my persuasion.
A people you always thought to be led away by a spirit of delusion and vain glory;
but that you are now fully convinced,
that whatever the authors of these suggestions were,
there are many people called by the name of Quakers, really fearing God;
and that the person I wrote to, you really takes to be such a one,
and my being so you will not question,
my letter being so full of pithy expressions of love to God, and to his Son Jesus Christ.

[.numbered]
2+++.+++ That Christ so loved mankind, as to die for us, and wash us in his own precious blood.

[.numbered]
3+++.+++ That he took upon him our nature, that he might know how to pity our infirmities;
and from there knew what need we had of strengthening ordinances,
and in love commanded us to commemorate his death till he came, etc.

[.numbered]
4+++.+++ That Christ was baptized of John, and sent forth his disciples to preach to,
and baptize all nations.

[.numbered]
5+++.+++ That they are accursed that take from, or add to the Scriptures.

[.numbered]
6+++.+++ That whosoever breaks any of the least of these commandments, namely: the sacraments,
the subjects there intended, shall not enter the kingdom of heaven.

[.numbered]
7+++.+++ That such as tell of God`'s love, and of rejoicing in it, and obey not his commands,
these pretended sacraments, must be accounted of as confessing him with their lips,
but denying him in their actions.

[.numbered]
8+++.+++ That these sacraments are better means of grace than we will make use of.

[.numbered]
9+++.+++ That God has set me upon seeking the way to heaven.

[.numbered]
10+++.+++ You advise me to make use of my reason in searching the Scriptures;
and then to tell you why I neglect those two great ordinances,
of baptism and the Lord`'s supper.

[.numbered]
11+++.+++ Of a sinless perfection in this life,
and what Scriptures I have to induce me to believe I shall arrive at it;
with your Scriptures cited against such perfection, and your reasoning therefrom.

[.numbered]
12+++.+++ That if we had no corruptions to struggle with,
we should be for building tabernacles, and abiding here.

[.numbered]
13+++.+++ That you love all those that love the Lord Jesus Christ,
and rely upon him for salvation, by the working of his holy Spirit in their hearts.

[.numbered]
14+++.+++ That the garb, manners, and conduct of our people, you greatly like.

[.numbered]
15+++.+++ But would gladly know what induces us to the above mentioned errors.

====

[.offset]
To all which I answer in order:

[.numbered-group]
====

[.numbered]
To the 1st; It reminds me of that saying of Nathaniel, concerning the Lord Jesus Christ,
"`Can any good thing come out of Nazareth?`"
a mean despised place it seems; and also of the answer, "`Come and see.`"
And likewise of what the Lord said to Nathaniel; "`Because I said unto you,
I saw you under the fig-tree, you believe?
You shall see greater things than these.`"
So even I, in the name of the Most High God, and Jesus Christ the eternal Son,
do write unto you, that you who have thus believed concerning the Lord,
and those who are now hated and contemned for his Name`'s sake,
if you are faithful to the manifestation of the life and light of Jesus in you,
shall see greater things than yet you see.
Your light shall then break forth as a morning without clouds,
and your peace shall shine as the sun at noon-day.

Then shall the substance take place in the midst of you,
and the shadows of the night shall fly before his glory.

[.numbered]
To the 2nd; That he trod the path of regeneration,
died a sacrifice for the sins of the whole world, ascended above all heavens,
and prepared the way for all that should believe and obey to the end of the world,
is true.
But that he actually washed us, almost seventeen hundred years before we were polluted,
or had any known being in the world, which your words seem to insinuate,
is a thing worth your further consideration.
For though they, who had been great sinners in that day, as we have been in this,
though not in the same things, and came to a sense and acknowledgment of them,
were washed and purified, he does not say with water,
but in the name of the Lord Jesus Christ, and by the Spirit of the living God;
and these things we believe;
yet unless we come to be actually washed and purified from our actual sins,
and the old root of them too,
by the two-fold operation of the same spirit of judgment and of burning, our belief,
though true, of their being washed and sanctified in their age,
will not save us now from the pollutions, power,
and reward of our own lusts and corruptions.
The Lord open your understanding by his divine power,
and shine therein by his pure light, that you may see all things as they are.

[.numbered]
To the 3rd; The plain sense of this is,
that the great end of Christ`'s taking upon him our nature is,
that he might thereby know how to pity our infirmities;
and from a knowledge thereof so obtained, was moved with so great compassion,
as to give us the sacraments, as the great fruits of his love and tenderness,
till he should come again at the end of the world.

This is a great perversion of the end of his coming,
and highly derogates from the glory of it;
insinuating that he was not sensible of our infirmities, nor could pity us therein,
till he acquired that knowledge by experience; reflecting upon his omniscience as God.
For he came that we might have life, not only shadows of if,
and that we might have it more abundantly: he came the second time in that generation,
according to his promise, to save his people from their sins, and not in them;
to save them from their pollutions and corruption, by the washing of regeneration,
and renewing of the Holy Ghost, the spirit of judgment and of burning,
that eternally burns, as an oven, against all corruption,
and can never be reconciled to sin; and not to establish a shadow only of cleansing.

He came to finish transgression, to put an end to sin,
and to bring everlasting righteousness into the soul of man, where it was needed;
and not some shadow of it only.

For this end likewise was the Son of God made manifest,
that he might destroy the works of the devil, which is sin in the hearts of mankind;
and not to give some signs of it only.
He came to give his life, the quickening spirit,
the true bread which comes down from heaven, to revive and preserve dead lost man;
and not only as you imagine, to give them these poor pretended ordinances,
in which there is no strength, to strengthen them.
The Lord himself, being with his people always, according to his promise, and will be,
in his own baptism of the Holy Ghost and fire, to the end of the world,
they need not any outward thing to put them in mind of him.
And sprinkling of children being an anti-christian forgery,
is not so much as a pertinent shadow of the one true baptism.

But if you will apply your heart to the Lord, in sincerity and truth,
and take up his cross daily, to your own will and natural desires,
and embrace those things he makes manifest to you, to be your duty to him and to mankind,
he will make you wiser than those who have thus taught and deceived you:
for great is his compassion and tender regard,
as I find by his grace made known in my heart, towards you at this time.

That the Lord Christ took a body of the same nature and kind as ours,
and was like us in all things, sin excepted, is true.
But whether he be come in us, is the question?
Whether that day be come in and unto us, wherein we have known,
"`that he is in the Father, and the Father in him, and he in us?`"
Or that we be yet so clouded, shadowed and benighted,
by the god and spirit of this world,
as not yet to have seen the Lord Jesus in and for ourselves?
If not, we are reprobates,
falsely covered with a vain profession of the holy name of Him we do not know.
For every spirit that confesses that Jesus Christ is come in the flesh,
the same is of God;
but every spirit that confesses not that Jesus Christ is come in the flesh,
the same is antichrist.

Now, every anti-christian spirit in the world, professing Christianity,
will confess in words, that Christ is come in that blessed, prepared body,
born of the Virgin Mary;
yet none can make this true confession of Christ`'s being come in the flesh,
but such only in whom the Spirit of Christ is revealed; who have put on Christ,
and are put on of him, and are become members of him, by his life that dwells in them,
as bone of his bone, and flesh of his flesh;
no more than any man can call Christ truly Lord but by the Holy Ghost;
though to call him our Lord Jesus Christ, and our Savior, in words,
is a thing very easily acquired, and common among most ungodly professors,
wallowing on still in all manner of sins and wickedness, and not saved by him.
Consider these things fully; and the Lord so shine in upon your heart in love,
and reveal himself in you,
that you may be able to confess him before all your acquaintance, and the world.

Again: as to those supposed ordinances of bread and wine,
and being sprinkled in the face with water in one`'s infancy,
if there was anything to boast of in these, I also might glory,
having formerly had the administration of both;
and the former with great preparation and fear, but know nothing of the latter,
but by tradition only, being too young then to know or remember anything of it; nor do,
or ever did, find any effect it had towards salvation.

In respect to the first, it is true there was something like a commandment;
for it being the passover of the Jews, and to be ended in Christ, the substance, he said,
"`This do, as often as you do it, in remembrance of me;`" not simply,
This do in remembrance of me, but, This "`do, as often as you do it,
in remembrance of me.
On which the apostle Paul, in his first Epistle to the Corinthians,
makes this observation, "`That as often as they ate that bread, and drank that cup,
they showed forth the Lord`'s death till he came.`"
This shows that it was determinable upon a certain contingency,
or within a certain limitation of time, namely: till he came.
And in that generation he came the second time, without sin unto salvation,
in those who believed and obeyed.

By which coming, this and all other types, shadows and figures of him,
were put to an end, as to any real obligation from that seeming commandment,
or any other, of a typical kind.

And yet, in condescension to some, who had believed in Christ, as to his outward coming,
that he is the Messiah and Sent of God, and were yet weak,
and not come to the experience of his presence in themselves,
being yet in an intermediate state, some eatings and drinkings,
I do not say any now in use, might be continued for a time, in some places;
though we read of none but Corinth, where they were then in a very carnal state.
But that practice did not make it necessary for ages then to come,
especially since antichrist has erected his kingdom of darkness under those shadows,
and forged idols under the cover of them, and thereby deceived the nations,
though not the elect, who cannot be deceived.
Yet that practice in those days, after the spiritual coming of the Lord Jesus Christ,
adds no more authority for the continuance or perpetuity of it,
than the practice of circumcision, vows, purifications,
and the like ceremonies and types under the law of Moses, made these necessary,
after his coming both in the flesh and spirit; some of which were not only continued,
for the reasons aforesaid, after the revelation of the Spirit of Christ, the Holy Ghost,
in them in that age; but some of them are continued,
especially in the church and kingdom of antichrist,
and among professors of Christianity unto this day, as still being needful,
in their judgment.

Breaking bread and drinking wine was a Jewish rite,
begun in the time of the captivity at Babylon, and continued till the coming of Christ,
and used at the passover and eating of the paschal lamb;
which was a type of Christ as the Lamb of God, the true vine and wine of the kingdom,
and the antitype of that figure; who made the application of it immediately to himself,
as being the real substance.

And though he was at that time come, and present with them as born of the Virgin Mary,
and the Messiah outwardly, according to the prophets, yet he was then shortly to come,
or be revealed, according to the prophecy of

Malachi, the last of the prophets, and of John the Baptist,
who prophesied of a divine coming and manifestation of the same Christ and Savior,
that is to say,
as the Mediator and Messenger of the new and second covenant of light and life;
and he is also that covenant, like a refiner`'s fire, and fuller`'s soap,
to sit in the hearts of mankind, as a refiner and purifier of silver; to make men pure,
and purer than fine gold, seven times tried in the fire;
to gather the weighty and solid wheat into the garner of God,
to be reserved there for his use, and of which is made the one bread;
but to burn up the chaff of pollutions with fire unquenchable, by him who is that fire,
the Word of God, who baptizes with the Holy Ghost, as John did with water,
and with that divine and holy fire.

"`As often as you eat this bread, and drink this cup,
you show forth the Lord`'s death till he come.`"
They therefore who are, at this day,
exercising themselves in the imitations of these things, with their own additions,
diminutions and alterations thereof, are only showing forth his death until now;
whereby they are bearing witness against themselves,
that they are not yet come to know him as the resurrection and life,
by his manifestation in them; that he is not yet revealed in them;
that they are yet dead unto the sense of the life of the Word of God,
and alienated therefrom, through the ignorance that is in them.

Christ is yet crucified in and unto them; being contented with a hear-say of him,
pretending to serve him in eating, drinking, touching, tasting and handling, in shows,
in imperfect imitations of some outward and typical shadows,
once in use in their proper dispensations of time, place, and people;
and yet deny or neglect the great everlasting command and ordinance of love.
"`Love one another; love your enemies; do good to them that hate you; be perfect:
by this shall all men know that you are my disciples, if you love one another.`"
Of these they are willingly ignorant.
And how little Christendom, falsely so called, has been in the practice of these things,
the heathen world has beheld, and has stumbled at.
How little she is in the practice of them still,
let her present circumstances demonstrate,
to all who have eyes to see the bloodshed and uncharity,
and ears to hear the cries of the poor and oppressed,
and hearts to lament the misery and judgments now on foot,
and swiftly advancing upon all false pretenders;
who are not only to be more and more vexed, by the destroying hands one of another,
but unless they speedily repent, and turn unto him,
the divine substance of all types and shadows,
even to that true light which enlightens every man that Comes into the world,
they must surely taste of the eternal judgment of the Son of God,
the great Judge of the living and of the dead;
who is now hastening upon all the kindreds of the earth.

"`I am the bread of life,`" said the Lord Jesus Christ,
"`the living bread which came down from heaven.
If any man eat of this bread, he shall live forever.
And the bread that I will give is my flesh, which I will give for the life of the world.
Except you eat the flesh of the Son of Man, and drink his blood, you have no life in you.
My flesh is meat indeed, and my blood is drink indeed.
He that eats my flesh, and drinks my blood, dwells in me, and I in him.`"
Then said the hearers,
"`How can this man give us his flesh to eat!`" Many therefore of his disciples,
when they had heard this, said, "`This is a hard saying, who can hear it?
And, to explain his sayings, he added, "`It is the Spirit that quickens,
the flesh profits nothing: the words that I speak unto you,
they are spirit and they are life.`"
"`Yet, from that time many of his disciples went back and walked no more with him.`"

Even the twelve apostles themselves seem to have been ready to stagger at his doctrine,
so far above the natural capacity of mankind, and of the hearers at that time,
as appears by his question to them in private; "`Will you also go away?
When Peter, recounting their experience, replied, "`Lord, to whom shall we go?
You have the words of eternal life.`"
As it is elsewhere written,
"`It is given unto you to know the mysteries of the kingdom of heaven;
but to them it is not given.`"
Even so it is at this day.
It is given unto those who are awakened out of sleep, to walk in the light,
and in the day of God, where there is no night or shadow,
and to be fed with this living bread and everlasting substance; but those who are asleep,
and dreaming, as in the night, that they are eating and drinking, and are satisfied,
when they awake in the morning, shall be hungry.
And then shall they know that they have been deluded with an empty dream,
and that real bread is lacking unto them,
and the true wine of the kingdom they have not tasted.

"`It is the Spirit that quickens, the flesh profits nothing.`"
And notwithstanding any use of any shadows or signs-visible, in the church of Christ,
after his descending upon them in spirit,
we find the true supper and divine substance explained,
and the way to obtain it directed to, by the Spirit of Christ,
after his glorification in heaven; and of which we are at this day made partakers,
through the infinite mercy of the Father in him; without the use of any ceremony, sign,
or shadow or of any other means than those of his own directing.
That is to say, "`As many as I love I rebuke and chasten; be zealous therefore and repent.
Behold I stand at the door and knock; if any man hear my voice, and open the door,
I will come in to him, and will sup with him, and he with me.`"
Here the love of God is the first moving cause,
and is seen in the rebukes and chastisements of his Holy Spirit,
in the hearts of mankind; and we ought to show our zeal and love to him,
by a free and hearty repentance, and forsaking of those things we are reproved for.
He will then stand at the door of such a heart,
and call more plainly and powerfully there, and knock by the hammer of his holy Word,
which breaks the rock in pieces; and whosoever shall hear, believe, and obey this voice,
and shall open his heart and door, and let in this divine guest,
shall sit with him at his heavenly table, and eat of his holy supper,
the true bread which comes down, day by day, from heaven,
and shall drink of the new wine of his kingdom, even now in this present world;
where their peace shall flow as a river, and their joy in him and the Father,
as a mighty stream.
They shall eat of the hidden manna, and fruit of the Tree of Life,
which is in the midst of the Paradise of God; and live with and in him, who was dead,
and died for them, and lives forevermore.

In all humility and honor to the sacred name of the Lord be it confessed,
I am often made partaker of this supper, with many brethren and sisters,
children of one Father, without the use of these means you talk of,
and without any self-conceited ness,
or blasphemous and vain apprehensions of our own wisdom, or being wiser than he;
for he is the wisdom of God, and the power of God, and is made unto us wisdom,
righteousness, sanctification and redemption; and by him, the heavenly substance,
we are led, directed and redeemed out of all shadows, types, and figures,
to serve God in newness of life, in love to God, and to all mankind.
Which love is the one great commandment, upon which depend all the rest, and which he,
the Lord Jesus, the great Dispenser of it in the hearts of his people,
is come to fulfill in us by his eternal power; and we are become,
and are more and more becoming, the workmanship of the Father in him, unto good works,
such as please him.

Without this new and living commandment, the observation of shadows, though once lawful,
or what men may invent to themselves, in imitation or addition thereto,
are as surely an abomination to the Lord at this day,
as the observation of things once commanded unto Israel, and in point of dispensation,
were then still in force, became as the cutting off a dog`'s neck,
and offering of swine`'s blood, because of their neglecting righteousness,
and greater matters of the law.

Every type or shadow once instituted, remained as an obligation, and in force,
until Christ, who is the antitype and substance of all types and shadows,
became that thing to man, which the type did typify or signify.
As when Christ was offered upon the cross, the Jewish offerings were ended;
when he became the High Priest of the soul,
the Jewish high priest`'s office was fully ended, etc.
Even so the Paschal lamb, and the breaking bread and drinking wine at that feast,
as part of it, were fully ended, when the true Paschal Lamb,
upon whom the saints and saved of the Lord were to feed, was fully come,
so as actually and spiritually to become meat and drink to their enlivened souls.
And in like manner also, so soon as the heavenly body of the Lord Jesus became,
experimentally, that bread of life which came down from heaven,
and his blood that new wine of the kingdom, unto the sanctified and redeemed in that day,
the breaking of bread outward, and drinking wine fully came to an end,
as to any obligation that was on any to retain the practice of it,
any more than washing the feet one of another, also a Jewish rite,
and a thing more positively commanded, and with great solemnity, and which, nevertheless,
has been little in use in the church of Christ.
And as said the apostle Paul,
"`I speak as to wise men; judge for yourselves what I say:
the cup of blessing which we bless,
is it not the communion of the blood of Christ?
The bread which we break, is it not the communion of the body of Christ?
For we being many, are one bread, and one body;
for we are all partakers of that one bread.`"
And blessed be the name of the Lord, so also is it now.

Great has been the apostasy of mankind from the heavenly substance,
and even from the shadow also; and all has become unto them as one shadow,
as the dark night and shadow of the earth:
and great idolatry has been committed by the professors of the name of the Lord Jesus,
therein and thereby.
And even at this day great is the apostasy from the true substance,
and superstition is committed and reigning in the imitation of this shadow,
while the living substance is still neglected and decried.

I sought the Lord in this ordinance, as you mistaking, calls it,
but found him not therein; but in a day of deep distress, and hour of bitter affliction,
when hell opened her mouth, and eternal death stood ready to devour,
when terrors unspeakable laid hold on my soul,
amazed and suddenly arrested for a debt I could not number or pay,
and despair encompassed me about;
then cried I unto the living Lord with exceeding lamentation,
from the depth of affliction, and in true resignation to his holy will,
and his mercy sprang in as the dawning of the morning.

The day dawning, the night retires, and the substance come, the shadow vanishes.
My dear, though unknown friend, when the beloved of your soul appears,
if the world and the things and friendship and glory of it, be not your beloved,
you will not then mind his picture, if it were his picture; nor mind his shadow,
though he had even said.
Look upon this till I come.
It is true, you will not then contemn his picture when he is with you: no more do I;
but have a due esteem for all he has commanded, in their times, dispensations, and ends.
Nor do I lightly esteem those who use that in
imitation with a good intent and sincere mind,
but pity them that they are come no nearer the kingdom; which,
though at hand seventeen hundred years ago,
is not yet come unto those who are set down contented under the shade of night,
and dreaming of things of which they have no knowledge or enjoyment.

Go into the sun-shine, and turn your face towards the sun,
and the shadow will be behind you; but turn your back on the sun,
and the shadow will be before you; and the more you follow it, the more it will fly you;
and the more you goest after it, the further from the sun.
And this is the state of apostatized Christendom at this day, and has been for many ages.

The kingdom of heaven is within, and stands not in eating and drinking,
nor comes with outward observation, but in righteousness and peace,
and joy in the Holy Ghost; to which the only true and living God,
through the inward revelation of his eternal Son, the Lord Jesus Christ,
bring your precious soul.
And that is the only thing that can truly satisfy,
where the soul is alive by the breath of life from God, and hungry and thirsty indeed;
though I am willing thus to take a little pains for your present information.

[.numbered]
4thly, And now as to baptism: to John the Baptist,
who was the immediate forerunner of Christ, came the word of God in the wilderness,
commanding him to preach repentance to the Jews, to whom alone he was sent,
to proclaim the kingdom of heaven to be then at hand; and to baptize the people in water,
directing them to believe in him who was to come after him, who was Christ the Lord,
then among them, though not known at that time to be the Messiah, either by John himself,
or any other.
But John declared that he baptized with water,
and that after him was to come one more worthy and powerful than he,
who should baptize them with the Holy Spirit and fire; and that John must decrease,
and Christ increase.

When the Lord Jesus Christ did appear, he likewise preached repentance;
as also did his disciples, who baptized with the same water baptism that John did,
and at the same time, but not in the name of one to come;
testifying that Jesus is the Messiah, sent of God unto Israel.
The disciples of Christ being thus in the practice of water baptism,
contemporary with John, and the Lord Christ present with them,
they continued in that practice till after his resurrection;
and then he declared and established his own proper baptism,
so foretold by John as aforesaid, saying,
"`Repentance and remission of sins must be preached in his name unto all nations,
beginning at Jerusalem.
And you shall be witnesses unto me,`" said he, "`in Jerusalem, in Samaria,
in all the countries round about, and to the uttermost parts of the earth.
All power in heaven and in earth is given unto me; go therefore, teach all nations,
baptizing them into the name of the Father, Son, and Holy Ghost;
teaching them all things whatsoever I have commanded you; and lo I am with you always,
even unto the end of the world.`"
And to explain what he had thus said, he further added, "`Go into all the earth,
and preach the gospel unto every creature.
He that believes, and is baptized shall be saved; but he that believes not,
shall be damned.
And, behold, I send the promise of my Father upon you;
but tarry you at Jerusalem till you are endued with power from on high:
but you shall receive power, after the Holy Ghost is come upon you;
for John truly baptized with water,
but you shall be baptized with the Holy Ghost not many days hence.`"
"`By all which Scriptures it is clear that John baptized with water only;
that the disciples of Christ, in his presence, baptized with the same,
and at the same time; that John had foretold them of the baptism of the Holy Spirit,
to be administered by Christ;
and that Christ declared and appointed the baptism of the Spirit,
and not any water baptism, where he commanded them to teach all nations, baptizing them, etc.
And as the terms of their mission were into the name of the Father, Son and Holy Ghost;
whenever any water was used,
of which we have few instances after the coming of the Holy Spirit,
it was not in the name of the Father, Son and Holy Ghost, as from that text,
but only in the name of the Lord Jesus; which demonstrates it was John`'s baptism,
and from no new command,
but only the continuance of the practice of
water baptism they had been in during his time,
before the commencement of the baptism of the Holy Spirit,
which initiates into the divine nature.

"`And when the churches became able to bear the
mystery and spirituality of the true baptism,
the apostle declared that, "`there is one Lord, one faith, and one baptism.
For by one Spirit are we all baptized into one body; the church, which is his body,
the fulness of him who fills all in all.`"
And as John said of his baptism, "`I must decrease;`" and of Christ`'s baptism.
"`He must increase;`" and that which decreases gradually comes to an end,
so water baptism came to an end many ages ago; when the church of Rome,
by her own wisdom and authority, which is from beneath,
without any institution of Christ, and being ignorant of the baptism of the Holy Spirit,
invented and imposed rantism, or sprinkling of infants, instead of the baptism of Christ,
from which they are departed, and between which there is no resemblance.

As the baptism of Christ must increase, without any determinate time of being full,
so that which increases indefinitely, never ends.

The baptism of Christ is an initiation into,
or beginning of the manifestation of his power and kingdom in the mind of man;
which kingdom is not of this world,
nor does it stand in any of the elements or powers of it,
but is his eternal power manifested in men; and as we began to know this baptism,
we began to die to the world, and to all the vainglory and evils of it,
and became hated and persecuted of those who are after the flesh,
and are not yet thus baptized or born of the Spirit,
but remain in the nature and spirit of this world.
Yet we are, by grace, made able to suffer all things,
for the sake of him who has loved us,
and into whose name and nature we were baptized by him.

And as to your notion, that as Christ was baptized with water by John,
so must we also be baptized with the same, by his example.

This is not a just consequence, but a common fallacy,
invented by the letter mongers and hirelings,
who pervert the holy Scriptures for worldly wealth, power and honor,
though to their own destruction, and the ruin also of many other souls.
For as Christ being born after the flesh among the Jews, submitted to the law of Moses,
and was circumcised, and had offerings offered for him as others had,
that he might fulfill all the righteousness of the law, and end it;
so he was likewise baptized of John,
to fulfill the righteousness of that dispensation also;
that all righteousness being fulfilled and concentered in him,
he might become righteousness, and the dispenser of it to them that believe,
through all generations.

As it is written, "`Unto us a child is born, unto lis a son is given,
and the government shall be upon his shoulder; and his name shall be called Wonderful,
Counsellor, the mighty God, the everlasting Father, +++[+++the Lord our righteousness]
the Prince of Peace.
Of the increase of his government and peace there shall be no end.
Who of God is made unto us wisdom, righteousness, sanctification and redemption;
for in him dwells all the fulness of the Godhead bodily.
And you are complete in him, which is the Head of all principality and power.
In whom also you are circumcised, with the circumcision made without hands,
in putting off the body of the sins of the flesh, by the circumcision of Christ:
buried with him in baptism, wherein also you are risen with him,
through the faith of the operation of God, who has raised him from the dead, etc.
Blotting out the hand-writing of ordinances that was against us, etc.
Let no man therefore judge you in meat or in drink, or in respect of a holy day,
or of the new moon, or of the sabbath days, which are a shadow of things to come;
but the body is of Christ, etc.
Wherefore, if you be dead with Christ from the rudiments of the world, why,
as though living in the world, are you subject to ordinances, etc.`"
"`Now, observe from this doctrine, that circumcision, baptism, with water,
and all religious ceremonies, respecting anything that may be eaten, or drunk,
or holy days, or new moons, or sabbath days, and all such like ordinances,
are here ended and fulfilled in the Lord Christ, the ever-living substance.
So that neither circumcision, nor uncircumcision, baptism with water, or no such baptism,
avails anything, but a new creature; born of him, the Word of Life, and complete in him,
who is the perfection of beauty, and head of all principality and power:
so that if we have Christ we have all,
and without him there is nothing at all in religion.

[.numbered]
To the 5th I answer.
That this is a misapplication of the Scripture suggested in the expression;
for the words are these,
"`I testify unto every man that hears the words of the prophecy of this book,
if any man shall add unto these things,
God shall add unto him the plagues that are written in this book.
And if any man shall take away from the words of the book of this prophecy,
God shall take away his part out of the book of life, and out of the holy city,`" etc.
Thus it is testified by the Holy Spirit; and the penalty here is great indeed,
and so is your accusation and charge,
but it is upon those who hear the words of the prophecy of that book, and shall add to,
or take away from the words of that book.
We are not guilty of this charge, of adding anything to that prophecy,
or taking anything from it, or of doing so to any other part of the holy Scriptures;
and so not liable to this curse or penalty.
But since actions, importing an addition of anything to the Christian religion,
as an ordinance of Christ, which is not so; or suppressing anything as an error,
which is no error, can be no less within the meaning of this Scripture,
in the nature of things, than adding or taking away of words; those are deeply guilty,
who have detained many typical things ended by the coming of Christ,
and invented and added to religion sprinkling of infants, with many impertinent,
superstitious, and idolatrous things, never commanded or ordained of Christ,
but forged in their own imaginations,
and imposed upon the professors of the faith of Christ as his ordinances,
by the violence of grievous anti-christian persecutions and murders by fire, sword,
and gallows, and all manner of cruel and inhuman tortures and torments.
And have detained and taken away the use of all the holy Scriptures from the people,
to whom, as Christians, they belong.
Then do you make haste from among them,
lest the curse you are bestowing so blindly upon the innocent,
fall upon your own head among those guilty sinners;
who are not citizens of the New Jerusalem, the holy city of God, but of Babel.

"`The Lord open their eyes to see, and give them hearts to understand,
and power to come out of all their inventions, to the great Baptizer and Feeder of souls;
that they may be saved from corruption, and enter those mansions, where there is no lack,
and where no unclean thing can come.
And the Lord bless you, my unknown friend, with the knowledge of his love,
and with a right understanding in all things.

[.numbered]
To the 6th and 7th;
This likewise is a manifest wresting and misapplication
of the holy Scripture alluded to in this place;
for the Lord Jesus was not then speaking of anything called sacraments,
as commandments of God, but of the moral commandments in the law of Moses.
And I know, that while we are breaking the commandments of God,
we cannot rejoice in his love; but in that state of disobedience,
are under his wrath and reproof.
But have you seen me break any of the commandments of God?
What I wrote in that letter of the love of God, was in truth and righteousness,
as it then was manifested in my soul by the Lord Jesus Christ;
and whatever it may be accounted of by such as know him not,
yet I know it is not accounted an offense before the Lord, to tell of his goodness,
but a duty in all them that are mercifully favored with the enjoyment of it,
when thereunto called by its own virtue.

Nor does the Lord, the great Judge of the world,
at any time charge me with the breach of any of his commands,
either for disusing the bread and wine of the priests, or their rantism,
which the Lord never sent them to administer; nor the pope`'s bread, or his rantism,
and other impertinences, which the Lord never commanded.

And who are they that are thus saying, but doing the contrary?
If you know of any that are breaking the moral commands of God,
or the new and living command of the Lord Jesus, the Son of God, daily;
and teaching men so, either by the example of a sinful conduct,
or by pleading and wrangling in words for a necessity of it for term of life;
loving God with lip-love only, and serving him only with tongue-service; you may,
if free yourself, reprove such as mockers of God, but accuse not the brethren,
in whom is revealed the eternal commandment, lest you offend the Father,
and the Judge reprove you in your own bosom: but believe in,
and follow and obey the light and life of the Son of God, in the way of regeneration,
if ever you yourself expects to enter his kingdom;
which you shall never see in any invention of the children of men.

[.numbered]
To the 8th; Where do you read,
or what experience have you that these pretended
sacraments are means to obtain the love or grace of God?
"`The grace of God, that brings salvation has appeared unto all men,
through the Lord Jesus Christ;`" and consequently to millions,
even the greatest part of all mankind, who never heard of those supposed ordinances.
"`Their sound is gone into all the earth, and their words unto the end of the world.`"
All have heard, but all have not believed or obeyed.
And he, by whom this universal grace is come upon all men,
in order to heal the universal disease, is the elect Seed of God,
and covenant with the nations; even that "`true light,
which enlightens every man that comes into the world;`"
and is "`ordained of God to be Judge of quick and dead.`"
By whom in no ways am I condemned for neglecting
these your ordinances as means of his love;
but by the mercy of the Father through him, do enjoy it, at times when it pleases him,
without any other means than his own free will and goodness.

[.numbered]
To the 9th; Time was when I was seeking the living among the dead,
and the way to God and his kingdom among the lo-heres and lo-theres of the times;
who were severally saying, Lo here, in our liturgy and ordinances; Lo there,
in our directory, and the like ordinances, as we administer them; Lo,
in the pools and ponds with us, as we perform with a nicer imitation;
and behold yonder in the mass, and glory, and pomp of the world,
in the great wilderness of anti-christian ordinances of human invention.
But within is the kingdom, and there I have found it,
through the voice of him who speaks from heaven; and there is made known the way,
and I desire to walk on in Him who is the way, truth, light, life, and love,
and leads to the God of love; to whom be renown, dominion, and glory, forever and ever.

[.numbered]
"`To the 10th: The Scripture says, "`The things of God knows no man,
but the Spirit of God, and God has revealed them by his Spirit;
for the Spirit (not the reason of man) searches all things, yes, the deep things of God.
By wisdom the world knows not God,
nor does the natural man receive the things of the Spirit of God:
for they are foolishness to him; neither can he know them,
because they are spiritually discerned.
But in the Lord Jesus, the Word of God,
"`are hid all the treasures of wisdom and knowledge;`" by whose breath of divine life,
not by reason, is understanding given, and the Scriptures opened.

"`None knows the Father but the Son, and he to whomsoever the Son will reveal him;
and none can come to the Son unless the Father draw him.`"
Men, by their reasoning about the things of God in a natural state, ignorant of God,
have made the gospel, to themselves, of no effect, as the Jews did the law,
by their tradition.

While I remained reasoning with flesh and blood, I had no true peace or knowledge of God;
but when it pleased him to reveal the life of his Son in me, then I denied myself,
and the world, with all the vain pleasures and glory of it, and likewise my own wisdom,
and became as a fool to the world,
that from then on I might be partaker of that wisdom and knowledge dispensed by him,
who is the Fountain and Dispenser of all true wisdom, knowledge and understanding;
by the opening and manifestation of whose Holy Spirit,
the Scriptures were given forth of old;
and the matters therein contained being things of God, are rightly to be understood,
and truly known,
only by the openings and in-shinings of the light of the same divine Word, by which,
at first, they were dictated, or the matters therein treated of made known.

And upon this Word have I ever depended since I was favored with the knowledge of God,
and not upon my own reason as a man only;
nor upon any supposed natural parts or acquirements, which, by themselves,
ought not to intermeddle with the things of God, how pregnant soever they may be.
"`And now dear friend, know that I am not a contemner of the holy Scriptures,
but do love them, and have searched them from my youth,
and have often been much comforted, and my heart has often glowed within me,
while the blessed and holy Spirit of Christ, which was in the prophets and apostles,
brought the Scriptures to my remembrance, and opened the mysteries thereof in me.
And therefore, to the Word of God,
which the noble Bereans received with all readiness of
mind before they searched the Scriptures,
do I refer you; even to the ingrafted Word, which is able to save your soul,
if you believe therein, that by the light and power of it, you may read and understand,
and have the Scriptures--as well the divine law of God written in your heart,
as the letter of the book--opened unto you:
and then shall you know the reason of my disuse of these supposed ordinances; till which,
all that can be said by man is not able to inform your understanding to the full.
But in a plain assertion of the innocent truth,
these shadows are not of God as they now stand and are used;
and being come to the immortal substance, I have no need of them,
but have the authority of the Lord and giver of life,
and the enjoyment of the divine and everlasting substance, for leaving them behind.

[.numbered]
11th; The enemy of man having deceived him, under pretense of a friend,
and wrought sin and iniquity in his heart, and thereby defiled him,
and obtained a place in his heart, the Son of God,
through the love and mercy of the Father, is made manifest there,
to discover unto man the works of the devil, and to destroy them;
and to create man anew in the image of God, in righteousness and holiness,
and to bring forth in him a new life.
And man, being thus the perfect workmanship of the Almighty,
created anew unto good works by Jesus Christ, his thoughts, words, actions,
and deportment are changed.
As it was natural, while in his first state in this life, to think, do, and speak evil;
so, in his new nature, being born of the Spirit,
it is natural to him to think righteously, speak truth without guile,
and do good unto all men, and no evil, in thought, word, or action.

And though the Lord Jesus closed his sermon upon the mount with these words,
"`Therefore be perfect, even as your Father which is in heaven is perfect;`"
yet it was not by the letter of the book only that I was first induced to
believe this doctrine of sinless perfection in this life,
but by the revelation of Jesus Christ, as he is the wisdom and power of God,
who condemns sin in mankind; and by the manifest operation of his power within,
condemns the man of sin, casts him out, and spoils his goods.
And though we have many temptations, from time to time, to strive against,
we find power in the Spirit of Christ whereby to resist and overcome them.
For it is not we alone that strive or resist the evil,
but first the Spirit of Christ in us is lifted
up as a standard and ensign against the enemy,
and then we, through him, become as co-workers in effecting our own salvation,
by continuing in faith, and obedience in well doing.

If you consider only your own weakness and infirmities,
as in the nature and properties of the first Adam in the fall, in whom all die,
you will hardly believe the liberty of the sons of God;
but coming to the revealed power of Christ, the second Adam, the quickening Spirit,
in whom all are made alive, you will not only believe,
but through faithfulness to his power, which works in you against all sin,
may come to attain that perfection of righteousness and holiness,
which you can not now conceive.

And though we are tempted as he was tempted, but sinned not, yet if we do not yield,
we are not charged: for it is no sin to be tempted; but to consent,
and enter into the temptation, is sin.
And how should we know the power of the grace of God,
or what degree of virtue we have thereby attained,
if we were not tempted I And how should we distinguish the voice of the tempter,
if we knew not the voice of the Word of Life?
But as God tempts no man, nor is himself tempted of evil;
so he allows not any of his children, son or daughter,
to be tried so as not to escape the evil, if they adhere to his grace.

By a sinless state in this life,
we do not mean such a degree wherein it is not possible for us to commit sin;
but such a stability in Christ, in whom there is no sin,
that we may resist all the temptations we meet with, after our old sins,
in time of ignorance, are pardoned by faith in the blood of Christ,
and our whole man sanctified, justified, and strengthened, by his power remaining in us,
against the old adversary; who still seeks to regain, by his subtlety,
his old place in us as before,
by means of any passion or affection unmortified or unsubdued.

Christ said to the Jews who did not believe, "`If you believe not that I am he,
you shall die in your sins.
Where I go, you cannot come.`"
And again, to those who did believe, "`If you continue in my word,
then are you my disciples indeed.
And you shall know the truth, and the truth shall make you free.
And if the truth make you free, then are you free indeed.`"
In this they did not understand him, as appears by their answer.
They thought he had meant some outward freedom; but he intended their freedom from sin,
which is a greater deliverance than out of Egyptian bondage.
By this it appears that if we die in our sins, we cannot enter the kingdom of heaven.
There is then great need that we come to Him in time, who alone is able to save us:
as it is written, "`He shall save his people from their sins;`" but not in them.

The more we obey the discoveries and leadings of the Spirit of truth,
the more he sets us free; and the more we are co-workers with Christ,
the more perfect we are.
Many things which have formerly been temptations to us,
being overcome by faith in his grace,
given by the word of faith working in our hearts by love, are now no temptations at all;
so that the work becomes easier by degrees.
I know the Lord is able to carry on his own work, when, and how,
and to what degree it pleases him.
And if the creature resists him not,
and quenches not the holy Spirit by willful or known sinning against him,
his work of perfection, as all his works are perfect, can never fail.

They who are God`'s workmanship in his Son, are perfect, so far as he has wrought;
and they who have given way, and been coworkers with Satan, so far are imperfect.
If then, Satan, who is a creature, was able,
through the subtle working of his power and cunning, which is finite,
to deprave innocent man, and betray him into sin and death; much more is God,
the Creator of all things,
by his infinite power and wisdom revealed in man through Jesus Christ,
able to restore mankind to his first innocence and image of God,
in righteousness and perfect holiness, to dissolve the chains of death,
and fix him forever in the bounds of eternal love, light, and glory; where no darkness,
temptation, or defilement, can approach, nor any fear of falling, can appear forevermore.

Oh, my unknown friend!
Great is the mystery of the redemption of poor lost man, who,
through his ignorance of the Almightiness of God`'s saving arm,
is ready to fix limits and bounds to the immense God; whose wisdom is past finding out,
and incomparably transcends all the imaginations of the thoughts of every creature,
men and angels.
I could tell you many things, but you are not in a condition to hear them;
and had much rather you should come to the knowledge of that power which makes perfect,
than write many things to you concerning it; which, in the state you are in,
might prove a stumbling block, instead of assistance, to you.

"`But though it was not the Holy Scriptures that
first induced me to believe this doctrine,
yet I have met with many passages therein since, which fully prove it,
some of which I have before pointed at herein.
The great end of the coming of the Son of God, is to save mankind from the power of sin,
the cause of eternal death, and separation from God; and that sin being removed,
with all its evil effects, which stood as a partition wall,
man might again have present fellowship, in measure, with the Lord,
and walk with him in newness of life, and finally be crowned with unspeakable glory.

"`God is light; sin is darkness; and between these two there can be no fellowship.
But sin being pardoned--as declared--by faith in the blood of Christ,
and the root thereof done away and destroyed, by the manifestation of his holy Spirit,
then men come to dwell in Christ, as he dwells in the Father;
and so they have true knowledge of, and fellowship with, the Father and the Son,
and with one another in him, who is light, in whom there is no sin, nor darkness,
nor shadow at all:
which knowledge and fellowship is greatly lacking among the professors of Christ,
in this confused age of the world.

"`As to that passage you allude to in an Epistle of John, where it is said,
"`If we say that we have no sin, we deceive ourselves, and the truth is not in us.`"
If we say that we have not sinned, we make him a liar, and his word is not in us.
The context proves the contrary to your intention: for in the seventh verse he says,
that "`if we walk in the light, as he is in the light,
we have fellowship one with another, and the blood of Jesus Christ his Son,
cleanses us from all sin.`"
And again, "`If we confess our sins, he is faithful and just to forgive us our sins,
and to cleanse us from all unrighteousness.`"

The Jews were a people who built much on the works of their law,
thinking themselves blameless in a strict performance of them;
as "`Paul was circumcised the eighth day,`" etc.,
"`touching the righteousness which is in the law, blameless.`"
And it seems, by the tenor of the apostle John`'s Epistle,
some such there were among the disciples at that time,
who were not come rightly to see that they were, or had been, sinners;
and so could not see the true reason of the coming of Christ,
to make them righteous and just, by his inward work;
which could not be till they came to a real
sight of their own sinful and degenerate state;
and that all the works of their law, which they could work in that natural state,
were but as an unclean thing.
And that apostle having labored to convince them, first, that they had sinned,
and were sinners, notwithstanding their legal performances,
how strictly or exactly soever observed, and though as to these they might be blameless;
he then proceeds to preach perfect redemption and salvation by Jesus Christ,
especially by his inward workings and teachings in their minds,
figuratively termed anointing; as it is written concerning himself,
simply considered as man, "`That God anointed Jesus of Nazareth with the Holy Ghost.`"

And what man ever more fully preached the doctrine of perfection in this life,
or spoke of higher attainments here, than this apostle does in that epistle;
where he says, "`Whosoever is born of God, does not commit sin: for his seed (that is,
the word of God) remains in him; and he cannot sin, because he is born of God?`"
Again, "`I have written unto you, young men, because you are strong,
and the word of God abides in you, and you have overcome the wicked one.`"
And their "`fellowship was with the Father and the Son,`" in the pure light,
where no sin can come: and the apostles were not only there themselves,
but were laboring in the spirit and power of Christ,
to bring those to whom they preached and wrote, to the same state and fellowship.

And though what I have already said to this 12th head, and to the former,
might be a sufficient answer to the extent of your meaning therein; yet,
being zealous for your convincement of the truth and conversion to God,
I shall proceed further, and add,
that I observe that the children of the flesh and of this world,
champions for sin and the kingdom and rule of Satan, both by word and practice,
commonly wrest several particular Scriptures to
support themselves and one another in sin,
to the end of their days, to their final destruction:
such as this expression of the apostle John, already noted,
that "`If we say we have no sin, we deceive ourselves,
and the truth is not in us;`" and where the apostle Paul says,
"`That which I do I allow not; for what I would that do I not, but what I hate,
that do I. O wretched man that I am,
who shall deliver me from the body of this death!`" From these
Scriptures some ungodly men perversely contend that those apostles,
and consequently all the primitive Christians,
were still sinners at the times of writing those Scriptures,
and continued in sin during life; upon a false supposition,
that all mankind are under an unavoidable necessity,
from the weakness of nature and constitution, so to continue to the end of this life.
This I oppose, and say, that as the apostles, as well as others, had been sinners,
before they believed in Christ and were converted;
so it was common with them to use that condescending way of expression,
in terms once applicable to themselves as well as to others:
as where the apostle James also says, "`The tongue can no man tame: it is an unruly evil,
full of deadly poison; therewith bless we God, even the Father;
and therewith curse we men.`"
Whereas, at that time, this apostle was not a curser of men, if ever he had so been.
No more were the apostles John and Paul then sinners; but had known,
not only forgiveness through faith in the blood of Christ,
but also a sanctification and cleansing from all unrighteousness and sin,
by "`the washing of regeneration and renewing of the Holy Ghost;`" and,
as you yourself have expressed the thing in the thirteenth paragraph, or head,
but without knowledge, namely: "`By the working of the holy Spirit in their hearts.`"

And you may see that John writes in that epistle,
to three different states in the church at that time,
and the same diversity continues still.
To little children in religion, though they might be men in nature,
that they should not sin: for he knew children in the faith were yet weak,
and might offend and fall; but if they should,
he instructed them how they might rise again, through the mercy of God in Jesus Christ,
declared unto all men, by the blood of his cross shed once for all.
To young men in the faith, that they should not sin: Why?
Because they were strong, and established in the faith and word of life,
and had already thereby overcome the wicked one, with all his temptations;
being begotten and born of God, and become his children,
though once merely the children of Adam and of this world: and to fathers in Christ,
and in the church of God,
who were come to a more full and mature knowledge of God and Christ,
revealed in them as a light, without the least darkness of any type, figure,
or shadow at all; and to a more ample perfection in Him,
through whom they were so far from sin at that time,
that they were become the light of the world,
by the light of Him whose glory shined in them.

Your other suggestion,
against the power and efficacy of the Christian faith and religion,
arises from the words of the apostle Paul,
before noted or some other Scriptures misapplied, which you do not understand.

How true is that saying, "`The letter kills, but the spirit gives life!`" Men,
falling to work upon the Scriptures in their sinful state,
with their own reason and wisdom from beneath--not knowing the Scriptures,
nor the power of God by the work thereof in their
hearts--have erred from the truth themselves,
and lead astray others also.

I shall therefore begin with the doctrine of the apostle Paul,
in the Epistle to the Romans,
and observe the manner of his proceeding in preaching the gospel:
he sets forward with mankind, both Jews and Gentiles,
as all once concluded under sin and unbelief; where he says, "`We have before proved,
both Jews and Gentiles, that they are all under sin.`"
And yet they were not to continue therein,
but were dead unto sin by the baptism of the Spirit of Christ:
and then proceeds to illustrate his doctrine by way of comparison;
"`that like as Christ was raised up from the dead by the glory (or power) of the Father,
even so we also should walk in newness of life:`" importing,
that as sure as Christ was raised from the dead; so, by the same spirit and power,
they who then believed, and had been baptized with the baptism of the spirit,
had attained a new life in him.
Again: "`For in that he died, he died unto sin once; but in that he lives,
he lives unto God.`"
So, by analogy, "`Likewise reckon you also yourselves to be dead indeed unto sin;
but alive unto God, through Jesus Christ, our Lord.`"
Who then can deny the death and resurrection of Christ,
but he that will deny any freedom from sin in this life,
through the power of Jesus Christ, our Lord?
And further, "`Shall we continue in sin, that grace may abound?
God forbid: and shall we sin, because we are not under the law,
but under grace? God forbid.`"
And since God has forever forbidden sin, under both the law and gospel,
and offered a free redemption therefrom, with all its dreadful effects,
through Jesus Christ, his Son, let us lay hold of it with all readiness.
Observing further the doctrine of this apostle in the same chapter,
"`Being then made free from sin, you became the servants of righteousness;
for when you were the servants of sin, you were free from righteousness: but now,
being made free from sin, and become the servants of God,
you have your fruit unto holiness, and the end everlasting life:
for the wages of sin is death, but the gift of God is eternal life, through Jesus Christ,
our Lord.`"
Read the whole chapter with attention.

"`But that which gives occasion to many, who are ignorant of the things of God,
and yet full of themselves and of their own dark conceivings,
and willing to favor and live in sin, to mistake or pervert this doctrine,
and imagine that the apostle contradicts all this in the seventh chapter, is this:
he having closed and finished his doctrine under the
similitude of Christ`'s death and resurrection,
in the latter end of the sixth chapter,
resumes the same doctrine in the beginning of the seventh,
under the similitude of marriage under the law;
which he directs in a more particular manner to them
who were acquainted with the rules and customs of it.
And in handling the same doctrine under that other similitude,
he impersonates several states, wherein men commonly were in a state of nature,
and under the law, before they came to the knowledge of the Lord Christ,
as if then his own; which to himself, and the saints contemporary with him,
were then really past and over,
and he and they arrived at another degree and dispensation.
He was endeavoring to excite them that were yet short,
to come further forward in the same way of life and salvation; from state to state;
from their initiation into the same, by the baptism of Christ,
till they should be perfect in him.
And, having spoken of these inferior states as in his own person, for illustration,
and to be more intelligible, in the same chapter he cries out, "`O wretched man that I am,
who shall deliver me from the body of this death!`" And,
in the next verse answers his own question, and says, "`I thank God, through Jesus Christ,
our Lord:`" and further adds,
"`There is therefore now no condemnation to them which are in Christ Jesus,
who walk not after the flesh, but after the spirit;
for the law of the spirit of life in Christ Jesus,
has made me free from the law of sin and death.`"

Now, neither the apostle, nor any other, could be both delivered and not delivered,
both in bondage and free, in the time of the writing these few verses;
which might all be done in half an hour.
I conclude, therefore,
with understanding that the apostle here impersonates two opposite states;
that of sin under the law, in a natural condition, and that of liberty from sin,
by grace through Christ; and that the latter was his own,
and of those also who had received and obeyed the gospel.
The gospel, and the effects of it, are the same throughout all generations unto this day,
in and unto all that believe, receive and obey the same; though they that do not,
remain as they were by nature, or degenerate more and more to perdition.

And seeing the same apostle labored to present every man perfect in Christ Jesus,
he himself was not excluded.
And can you think that the all-wise and all-powerful God, Lord of heaven and earth,
set this great apostle and the rest of them upon labor in vain;
which must needs have been, if they labored to present the believers perfect in Christ,
and it had not been attainable.

And that this blessed freedom and glorious liberty of
the sons of God is not attainable in this present world,
is only a dream in the night, which is yet over the nations in too general a way,
told and propagated by ignorant and inexperienced pretenders in this age,
who measure the attainments of the apostles and primitive saints,
as also of this present time,
by the very unequal measure and false standard of their own corruptions;
and the wisdom and power of God, by their weak and carnal knowledge:
for which the Most High will shortly rebuke them in judgment,
and call them to account for their great presumption.

[.numbered]
"`Now, to the 12th head: though what has been said to the 11th,
and some parts of the former, might be sufficient also to this; yet,
being desirous to do you all the help and service I may,
I proceed upon this likewise in a particular manner;
that we have corruptions to struggle with we are very sensible;
our own natural corruptions, and a subtle unwearied adversary,
lurking and working therein, seeking to entangle us again in the yoke of bondage.
But we are likewise sensible that it is one tiling to be tempted,
but another to remain in sin: for Christ was tempted, yet without sin;
tempted of Satan with the power, riches, and other glories of this world,
by which poor mortals are commonly enticed, yet he overcame the evil one;
tempted by weak and cunning men, children of the evil one, by ensnaring questions,
false accusations, lies and slanders;
by the rude and impudent contradictions of bold and ignorant sinners.
Yet he, being the wisdom of the Father, put them all to silence; and finally,
by patience and his cross, he overcame the world and all the power and enemies therein.
And the holy One, who thus overcame in his own person, prevails also in us,
by his own wisdom and power, against all our sins and corruptions;
and against the evil one and all his subtleties and power;
and over the principalities and powers of this world,
and the temptations arising therefrom;
and against spiritual wickedness exalted in the high places of the earth;
as our eyes are kept open and watchful towards the Lord,
and our confidence remains in him, and our faith in his power and love.

As to that Scripture hinted at, "`in building tabernacles here in this world,`" I observe,
that the transfiguration of Christ was a figure of his glorification,
and also a representation of the then present dispensation of
God and the condition of his church at that and future times:
there was Moses, representing the law by him, then not fully ended; Elias,
the dispensation of the doctrine and baptism of John, then likewise, in some degree,
remaining; with Christ, the only dispenser of the gospel and eternal substance,
and Mediator of the new covenant of light, life, and glory.
And after the glorification of Christ, neither Moses remained, nor Elias;
the law of ceremonies, nor John`'s baptism; but Christ alone upon the mount,
with his disciples; representing his church,
directed by the voice from the excellent glory, to hear him.
And the soul-quickening voice of the Son,
which brings forth the good pleasure of the Father therein, is his Holy Spirit;
as it is written,
"`He that has an ear let him hear what the Spirit says unto the churches.`"

It is this great and powerful voice out of heaven, by which the worlds were made,
which says, "`Behold, the tabernacle of God is with men, and he will dwell with them;
and they shall be his people, and God himself shall be with them, and be their God.`"
The tabernacle of God is his church and people, as say the apostles Peter and Paul:
"`For we know that if our earthly house of this tabernacle were dissolved,
we have a building of God, a house not made with hands, eternal in the heavens:
for we that are in this tabernacle do groan, being burdened;
not for that we would be unclothed, but clothed upon,
that mortality might be swallowed up of life.`"

We have no cause therefore to erect tabernacles here of our own inventing,
since a far more glorious degree is to be received here after,
by all those who hold out to the end of the race; which made not only some then,
but others also now, desire to be dissolved, that they might be with Christ alone,
in the fulness of that love, light, and glory,
which our souls have in measure been made partakers of;
to the praise of Him who lives forever and ever; and because he lives,
we live also in and by him.

Though the true God and his holy name, and this his tabernacle,
and those who dwell in heaven, may be blasphemed for a time by the beast and dragon,
and the worshippers of them; and by the synagogue of Satan, and of his tabernacle,
who live in sin and uncleanness, or rather are dead therein,
in the darkness of the earth and spirit and life of this world:
yet He who tabernacles in his saints, shall shortly wipe away all tears from their eyes;
and there shall be no more death unto them, neither sorrow, nor crying, nor pain.

[.numbered]
13th; I can assure you, if you can believe me,
that all true Quakers truly love the Lord Jesus Christ,
and rely upon him alone for the completion of that salvation which he has begun in us,
by the working of the Holy Spirit in our hearts; but say also,
that we must be co-workers with him in our salvation, with fear and trembling.
By reason of that trembling,
arising from a true dread of his awful presence while not fully reconciled,
we have received that name of contempt and scorn
by such as have seen the effect sometimes,
when the cause has been hid from their eyes.
And whatever may befall you for lack of obedience to your convictions in time to come,
I can sincerely wish the increase of that love in you,
and that you may testify it before the world in God`'s appointed season;
remembering that saying of our Lord Jesus Christ,
"`Whosoever therefore shall confess me before men,
him will I confess also before my Father which is in heaven.
But whosoever shall deny me before men,
him will I also deny before my Father which is in heaven.
He that receives you, receives me; and he that receives me, receives him that sent me.

[.numbered]
14th; The garb, manners, and conduct of our people you greatly like.
O my beloved friend, the Lord is come near you, and have you considered it?
In the love and fear of the Most High I write unto you,
that your sincerity shall be tried in this very thing;
for the Lord God of Sabaoth shall demand your garb, your manners, your conduct,
your crown and your glory, that he may give you a garb, manners, and conduct;
and upon your resignation and obedience shall depend your peace and your glory,
which the Lord God of never changing love shall crown you with, or not,
according to the integrity or deceit of your inmost soul.

The Lord God of life, truth, and peace, be merciful to you in the midst of judgment,
and bear up your mind in the approaching trial,
says the soul of him who is deeply concerned for you on that account,
in the universal love of the Father of mercies, manifested by our Lord Jesus Christ;
through whom, unto the invisible, just, merciful, and all-powerful God and Father,
be offered and ascribed eternal honor and immortal praise; for he is worthy of all love,
obedience and renown, forever and ever.
Amen.

[.numbered]
The 15th head is answered in the whole, and needs no further.

====

[.signed-section-closing]
Try all; hold the best. Farewell.

[.signed-section-signature]
Thomas Story

After this, I had an interview and conference with the same person,
who was convinced of the way of Truth; but being engaged in marriage,
could not decline that, or embrace the cross of Christ and despise the shame,
and so fell back, and never made any profession with us.
