== Chapter I

The following work is intended to record the tender mercies and judgments of the Lord;
to relate my own experience of his dealings with me through the course of my life;
and to write a faithful journal of my travels and labors in the service of the gospel:
which I design for my own review,
and likewise for the serious perusal of all those who
may incline to inquire into things of this nature.

I have solid evidence to believe, that the Lord, in his great mercy and kindness,
had an eye upon me for my good, even in my infancy,
inclining my heart to seek after him in my tender years.
From here, I may reasonably conclude, arose that early inclination I had to solitude;
where I sometimes had religious thoughts, and frequently read in the holy Scriptures;
which I ever loved, and still do, above all books, as most worthy and most profitable;
especially the New Testament, in which I chiefly delighted.

In this state, my mind suffered many flowings and ebbings;
and as I grew up towards a young man,
I found myself under great disadvantages in matters of religion,
as I was then circumstanced.
My father, intending me for the study of the law,
which was esteemed a genteel profession, first sent me to the fencing school,
as a fashionable and manly accomplishment.
Here I became a considerable proficient in a short time,
over all my contemporaries in that faculty; by which my mind was greatly drawn out,
and alienated from those beginnings of solidity which I had once known.
Having also acquired some skill in music,
the exercise of that occasioned an acquaintance and society not profitable to religion;
though I was hitherto preserved from such things
as are generally accounted evils among mankind.

After this I was put to the study of the law, under a counsellor in the country;
with a design to be entered, afterwards, into one of the inns of court,
and to finish there.
Being much in the country, and the family sober and religious in their way,
of the most moderate sort of Presbyterians,
I had again the advantage of solitude and little company, and that innocent;
so that my mind returned to its former state, and further search after the truth.
And though I had, at times, some youthful airs, yet, through secret grace,
I was preserved from gross evils, and gained respect from all the family.

During my abode with this counsellor, I was several times with him at London;
where by the fear of God, I was preserved from vice and evil company,
which much abound in that great city, though I was not without temptations;
and some not otherwise to be resisted than by the secret influence of grace,
which supersedes them;
though it may not always be immediately apprehended by such as are preserved by it.

Though I was educated in the way of the national church of England,
yet I had no aversion to any class professing the Christian name,
but occasionally heard several sorts;
and yet did not fully approve any sect in all things, as I came to consider them closely.
At Newcastle upon Tyne I once happened to hear a famous Presbyterian preacher.
It was in the reign of King Charles the Second,
when the national laws were against them and all
other dissenters from the national worship;
and they, being cowardly, had their meeting in the night, and in an upper room,
with a watch set below.
I did not go into the room, but stood at the head of the stairs,
expecting to hear something like doctrine from so noted a man among them;
but all that he entertained his auditory with,
was suggestions of jealousy and dislike against the government;
and this he delivered in such a way as appeared to me very disagreeable.

At another time I was at a Friends`' meeting, on a weekday, at Broughton,
in the county of Cumberland;
where I applied my mind with as much diligence as I
could to examine what I could discern in their way.
But, though I observed they were very grave, serious and solid,
in the time of their worship, I could gather but little,
either from their manner or doctrine; only I took them to be an honest, innocent,
and well-meaning sect.

Towards the latter end of the year 1687, we came out of the country,
and had chambers in the city of Carlisle.
King James the Second being then on the throne,
and the garrison and castle in the hands of popish officers and governors,
the Protestants were apprehensive of great danger,
and the people much divided in their sentiments and interests.
There was a loose and treacherous sort among the Protestants,
who approached daily nearer and nearer towards the Papists, and fell in, generally,
with all their measures; which grieved the steady part,
and justly heightened their apprehensions.

About this time I went diligently to the public worship,
especially to the cathedral at Carlisle; where, in time of public prayer,
as soon as that called the Apostle`'s Creed began,
we all used to turn our faces towards the east; and when the word Jesus was mentioned,
we all bowed and kneeled towards the altar-table, as they call it;
where stood a couple of Common Prayer books, in folio, one at each side of the table,
and over them, painted upon the wall, signifying, Jesus, the Savior of mankind.

I had read and heard many things of the popish religion; of their manifold ceremonies,
strange tenets and doctrines; their cruelty, murders,
and massacres of all who differed from them, wherever they had power:
which I thought denoted a degeneracy below even fallen nature;
that making men worse than this.
As I was concerned to inquire more and more after the truth of religion,
the manner of our worship in the cathedral often put me
in mind of the popish religion and ceremonies,
and made me conclude, that the way we were in, retained abundance of the old relics;
our prayers, postures, songs, organs, cringings and shows,
appearing to be little else than an abridgment of the popish mass,
and the pomp and show attending it; I began to be very uneasy with it;
and though I went there a little longer,
yet I could not comply with several of the ceremonies; which being taken notice of,
in a familiar conference with an acquaintance of the same way,
I asked a little pleasantly.
What is that we worship towards the east?
And why towards the altar, more than any other place, at the saying of the Creed?
The person replied, "`Sure you are not so ignorant as you would make yourself seem.
The Scripture says, '`At the name of Jesus every knee shall bow, of things in heaven,
and things in earth, and things under the earth.`'
And again, '`As the lightning comes out of the east, and shines even unto the west;
so shall also the coming of the Son of Man be.`'`"

To the first I returned,
That our pagan ancestors were worshippers of the sun and all the host of heaven;
and this looked very like that; and could not certainly be grounded on that Scripture;
which I cannot understand to signify any other,
than the gradual manifestation of the power and glory of Christ to the world.
But if he should literally come from the east, in an outward sense; which,
considering the state of the earth,
its revolutions and relation to the sun and other planets,
cannot be in the nature of things, that being west to one place which is east to another;
yet that coming would not excuse our superstition, if not idolatry, before he so come;
though I grant, if he should so come, and we see him, then, and not till then,
may we lawfully and reasonably worship towards the place, or imaginary place,
of his coming.

As to bowing at the name of Jesus, I understand it to be in the nature of a prediction,
that in the fulness of time all powers in heaven and earth
shall be subjected and brought under the power of Christ,
as the next verse imports, which is explanatory of the former, namely:
that "`every tongue shall confess, that Jesus Christ is Lord,
to the glory of God the Father.`"
Agreeing also with what the Lord Jesus himself says,--"`All
power is given unto me in heaven and in earth.`"
And therefore, this bowing towards a cipher of the words, Jesus the Savior,
painted upon a wall,
while the heart and spirit of a man is not subjected to the power of his grace,
is but a mocking of Christ, a relic of popery, and has some show of idolatry in it,
from which I thought all Protestants had been thoroughly reformed.

This a little surprised my acquaintance at first,
coming from one in whom so little of the work of religion appeared outwardly;
but as I remained in the diversions of fencing, dancing, music,
and other recreations of the like sort, little notice was taken for a while.

After this I happened to be at a christening, as we called it, of a relation`'s child;
on which occasion I found my mind agitated in an unusual manner,
and a secret aversion to that ceremony;
which I perceived was not according to the holy Scripture,
for we have neither precept nor example there for that practice.
And when the priest came to say the prayer,
which is a part of the service on that occasion,
a great fear and surprise came over my mind, as I gave a more close attention than usual,
so that I could not pay that regard to it as formerly.
By way of introduction to the work,
the priest reads part of the tenth chapter of Mark`'s history of the gospel,
where it is related, that the people "`brought young children to Christ,
that he should touch them;`" that his disciples rebuked those that brought them.
But when Jesus saw it, he was much displeased; and said unto them,
"`Permit the little children to come unto me, and forbid them not;
for of such is the kingdom of God.
Verily I say unto you, whosoever shall not receive the kingdom of God as a little child,
shall not enter therein.
And he took them up in his arms, put his hands upon them, and blessed them.`"
After this they prayed that God would give his holy Spirit to that infant; that she,
being born again, and made an heir of everlasting salvation,
through our Lord Jesus Christ, might continue the servant of God, and obtain his promise, etc.
And after some more ceremony, the priest said,
"`We receive this child into the congregation of Christ`'s flock,
and do sign her with the sign of the cross,`" etc.
Then the priest, pretending to the company that the infant is, by that rantism,
regenerated and grafted into the body of Christ`'s church, exhorts them to prayer;
the substance whereof was this:
they thanked God that it had pleased him to regenerate that infant, with his holy Spirit,
to receive her for his own child by adoption,
and to incorporate her into his holy church, etc.

Upon this I note, that the Scripture there has no relation at all to baptism;
much less to sprinkling, which is no baptism.
For the people brought their children to the Lord Christ, not to be baptized,
but that he might touch them; and he answered the faith of the people accordingly;
he blessed them, and declared their innocence and aptitude for the kingdom of God,
without such baptism; and did not baptize them.
So that this Scripture is inapplicable, and all the consequences drawn from it,
in this sense, are null and chimerical.
But they, first praying that God, in their own invented way,
would give his holy Spirit to that child; and that being taken for granted,
as already done by that ceremony and prayer,
they then receive the child into the congregation of Christ`'s flock; as they say,
acknowledging, that, by that baptism, that child is regenerated,
and grafted into the body of Christ`'s church;
and accordingly they make their address of thanks to God for doing it.
After this ceremony was over, I privately asked the priest,
whether he did believe that that ceremony,
for which there is not any foundation in Scripture,
either for making little children the subjects of baptism,
signing them with the sign of the cross, promising and vowing in their names,
believing and confessing in their stead, or sprinkling them only with water, etc.,
did really then, or at any time to come, regenerate those children?
At which he smiled, and said no; but it being an established order in the church,
the practice could not be omitted.
Why then, said I, you do but mock God,
in giving him thanks for that which you do not seriously believe he has effected.`"
And the sequel proves there is no such thing done by those means;
for true baptism is justification and sanctification,
effected by the holy Spirit of Christ in the mind;
and not by the application of any outward element,
or external performance of any person whatsoever, under any qualification.

I continued in the national way of worship, though by the divine grace,
my understanding was still more and more cleared.
About this time the power of king James the Second was at the height,
and all sects were indulged with great liberty; when John Scansfield, a noted Quaker,
having, by leave, a meeting on a first-day in the town-hall, several young men,
among whom I was one, went there to hear what those Quakers had to say.
There was a mixed multitude, and some of our sort and company rude enough; but others,
and myself, were resolved to (five the best attention we could,
in order to form a right judgment.
Two Cumberland preachers spoke before John Scansfield, whom several of us knew;
but their preaching had no other effect upon me,
than to confirm an opinion which I had conceived when I was a boy;
that as a sort of people I had heard of, called Baptists, imitated John the Baptist,
in washing or plunging their followers in water, who, I believed,
had not any authority from God for that practice;
so the Quakers only imitated the apostles, in going about preaching, as they did,
but without that power which the apostles were accompanied with and travelled in;
and I thought it was a great pity they were not so endued,
since I heard they took pains as if they were.
One of these preachers, to me, had only a little dry, empty talk,
and the other was more lively; but straining his voice to be heard over the multitude,
he quickly grew hoarse, lost his voice, and so sat down.
And then Scansfield, the stranger, from whom we had greater expectations, stood up,
and made a more manly appearance than either of the former.
The first thing he did was to reprove the rudeness of some of the company; and,
in his preaching, falling upon baptism, among other things,
and alleging there was no foundation for the practice of the church of England,
in all the Scripture: concerning that, he advanced this query: "`Suppose,`" said he,
"`I were a Turk or a Jew, and should ask you,
What is the rule of your practice in that point?
and you should say the Scripture; and if I should desire to see that Scripture,
you not being able to produce any,
what could I conclude other than that you had no
foundation for your religion but your own imagination,
and so go away offended and prejudiced against the Christian religion?`"
This agreed with my own former sentiments, and gave me occasion to give further attention.
In the rest of his speech, he first run down the national church at a great rate,
and then likewise the church of Rome: and there being many Irish, popish,
military officers present, and a couple of musketeers placed at the door,
and the officers behaving so tamely, as no show of dislike appeared in any of them,
many suspected Scansfield to be a Jesuit,
and that his aim was to expose and run down the church;
and what he said against the church of Rome, was only the better to cloak his design:
for the king and his friends could support their religion by the power of the sword,
and other cruel and forcible means; that being their usual method and practice:
but there was nothing then to support the church
of England but the truth of her own principles,
and the fortitude and stability of her members,
in the time of an impending danger and trial.

Many of us left them when they went to prayer;
yet I was apprehensive of the secret influence of a divine power and presence,
being in some degree, among that people: but that impression did not remain long with me,
till renewed upon another occasion; which will be related hereafter.

This was in the year 1688; and when the news came of the birth of a prince,
the Papists made a great bonfire in the market place; where they drank wine, till,
with that, and the transport of the news, they were exceedingly distracted.
The whole Protestant part of the king`'s subjects, except the temporizers,
were in great consternation, and apprehensive of a popish government,
and consequent oppression and persecution to destruction.
Nevertheless, whether out of fear, or other cause,
as well the bishops as inferior clergy,
and the generality of the people throughout the king`'s dominions,
presented addresses to him on this occasion,
replete with the utmost expression of loyalty and duty that
words were capable of The pulpits generally resounded
throughout the nation with their king-pleasing doctrine,
of passive obedience and non-resistance; but with their own mental reservations,
as in the sequel proved,
insomuch that he who could not compose a discourse on that modish subject, would beg,
borrow, buy, and steal from the more able, rather than not be fashionable;
which occasioned jealousy in many,
lest the clergy should revert and embrace the old errors; from which they,
with the people, seemed to have been reformed.
Yet seven of the bishops stood obstinately to their principles,
when the king commanded them to read, or cause to be read,
his proclamation for liberty of conscience in their respective dioceses; which,
though highly reasonable and Christian, they refused.
This could not be on any foundation of religion,
but because it was contrary to those national laws
which persecuted and suppressed all but themselves,
and those of their own sect.

The face of affairs thus flattering the Roman interest,
they became zenith-high in their expectations and assurance; imperious, insolent,
swaggering, and insulting everywhere;
and the Protestants more and more filled with rational
apprehensions of impending danger and destruction.
Notwithstanding, there were many,
both among the priests and people professing the Protestant religion,
as brisk and forward as the Papists themselves, to fall into the present measures,
interests and politics; which gave others just occasion to think they would, in the end,
prove themselves false brethren.

A solid consideration of the state of affairs, and the doubtfulness of the issue,
put me upon a more inward and close observation of persons and things than ever.
And one day, at the assizes at Carlisle, dining at an inn with a mixed company,
where happened to be two of our ministers of the church of England,
a popish gentleman moved a debate concerning transubstantiation; pretending to prove,
by Scripture, that,
by virtue of certain words which their priests say over a piece of bread, or wafer,
there is a substantial conversion of it into the real body of Christ;
the very same that was born of the Virgin Mary, crucified at Jerusalem,
and now glorified in heaven.

The text of Scripture he advanced to support this position, was,
"`And as they were eating, Jesus took bread, and blessed it, and broke it,
and gave it to the disciples, and said, Take, eat, this is my body.`"
And his argument was this.
That Christ, being the Word of God, and the truth,
whatever he said must be positively and literally true;
and therefore there is a real change of the bread into the true and real body of Christ:
and this being an ordinance of God to his ministers,
the same power is annexed to that ordinance; since, at the same time,
he commanded them to do the same, saying, "`This do in remembrance of me.`"

During this uninterrupted discourse, my zeal was kindled,
so that I could scarcely contain it.
But being young, and diffident of my own abilities,
and paying regard and preference to our two ministers present,
and expecting their appearance against so great an error,
and so opposite to the Protestant religion,
I delayed till it became almost unseasonable to engage him.
But they minding their plates, and hanging down their heads,
with their countenances veiled by their hats;
and I seeing no sign of any answer from them to the papist,
I took him up upon the subject, thus;

You of the church of Rome take these words literally;
but we take the whole form of his speech at that time on that subject, to be figurative;
and that these words, "`This is my body,`" intended no more than, This bread is a symbol,
or figure, or representation of my body, which shall shortly hereafter be broken for you:
for we ought not to divide the sentence or speech of Christ,
and take one part literally and another figuratively.
And you may remember that, at the same time, he also took the cup, saying,
"`This cup is the New Testament, in my blood, which is shed for you.`"
Do you think that that cup, whether of gold, silver, glass, or wood,
was the New Testament?
Or can`'t you see, that in this latter part of his speech there is a double figure?
First, the thing containing for the thing contained; and secondly, the wine in the cup,
exhibited under the word cup, as a figure or representation of his blood;
which was not then actually, or literally shed, or his body broken.
And seeing he said, in the present tense,
"`This is my body which is broken (not to be broken) for you;
and this cup is the Now Testament in my blood,
which is (not which shall hereafter be) shed for you;`" you
must either own that Christ advanced a false proposition,
which you will not; or that he spoke figuratively in both sentences;
which you cannot reasonably avoid.
Besides, the words uttered by Christ himself, did not work that effect you imagine;
for no man can call a thing by any name, denoting its existence,
before it is that thing which it is called: +++[+++then taking up a plate]
no man, for instance, can truly and literally say, this is a plate,
if it were not a plate before.
Then, by a parity of reason and truth, Christ could not say, this bread is my body,
if it were not his body before.
Therefore these words made no alteration, for it was so before;
these words were only declarative of what was before, and not initiatory,
or commencive of a new being, which was not there before.
Again, if ever these words had effected a transubstantiation,
they would when Christ himself uttered them.
Consider then, pray, that as soon as Christ began to speak these words,
"`This is my body,`" the body of Christ, born of the Virgin Mary,
began to cease to be his body, and the bread began to convert into it; and that,
as soon as the words were finished, the body born of the Virgin,
altogether ceased to be what it was before; and,
by a new way of corporeal transmigration, insinuated itself into the bread; which,
by the same degrees that the body of Christ ceased to be his body, commenced, proceeded,
grew, and became his body;
or else he had two bodies present with his disciples at the same time;
and if they eat his body that evening,
what body was that which was crucified the next day?
And what blood was then shed, if, the night before,
the disciples had drank the blood of Jesus in a proper and literal sense,
and without a figure?
And where now is that same cup?
If you have lost that, you have, in your own sense, lost the New Testament,
and all your share therein.
Now, if you can persuade me and this company out of our senses and understandings,
so that we may be able to believe against both,
that a piece of bread is the body of Christ, and a cup of wine is his blood,
then you may bid fair for our conversion, or rather perversion, to your religion.
But, till you can do that,
you cannot reasonably expect we should embrace so great absurdities.
Upon this, several of the company laughed;
and the Papist said these were great mysteries, and the subject copious and intricate,
and could not, at that time, be fully prosecuted,
but might be more largely discussed at some other convenient opportunity.
I replied, then why did you move it?
Could you think we would all sit silent, to hear you propagate such notions,
and make no opposition?
And so the matter dropped.
But though I had thus opposed him,
he showed more respect to me afterwards than to any other of the company.

Dinner being over, our ministers retired into another room, and I went to them; where,
with much seeming respect, they addressed themselves to me after this manner,
"`We are very glad to hear you have so much to say in defense of our religion,
and that you managed the debate so that he got no advantage,
nor could maintain his point.`"
But I, being still under the grief and shame, as well as resentment,
of their temporizing cowardice and negligence, quickly returned thus: "`And I, gentlemen,
am very much grieved and ashamed to find that
you had nothing at all to say in defense of it,
which I very much wondered at;
for I so long expected one of you would have engaged the gentleman,
that it was almost unseasonable to make any answer.`"

To this they replied, that I might do it a great deal better and safer than they;
for it would have been more taken notice of, and worse resented in them;
and might have been greatly to their future prejudice.

This reply, from men of their profession, at such a crisis,
when our religion was apparently in the most imminent danger,
bore such an aspect of temporizing,
and was so suspicious of a secret inclination to apostatize
from their own avowed principles and to conform to Popery,
then ready to force its way into fashion, that it very much offended me,
increasing my former disgust;
and occasioned such a crowd of thoughts in my mind about the
clergy and the religion they pretended to propagate,
that I said no more to them about it.

This was towards the end of August, in the year 1688; and not long after,
arrived the Prince of Orange; at whose appearance,
that party which had but a little before, been so very high, despotic, and rampant,
were at once universally dispirited and dejected to such a degree,
that they stole away from some places in the night, particularly Carlisle.
There was a strong castle here, and other fortified holds,
and the city surrounded with a high and strong wall, and well stored with ammunition;
which made many judge that their guilt,
and the consciousness of their own evil designs against the Protestants,
were the main ground of the panic which seized them at
the news of the arrival of that Protestant prince;
with whom they had good ground to believe the Protestants had a secret understanding;
and with whom, most likely, they would quickly join;
which accordingly happened at the erecting of his standard and displaying his banners.

Being at Carlisle when this surprising departure of the Popish party happened,
and with them our great fears, I wrote to my brother,
chaplain to the Countess Dowager of Carlisle, and then with her at Howard castle,
in Yorkshire, a full and particular account of all the circumstances of it;
which being intercepted, with other letters, and sent to the Lord Delamere, then in arms,
in favor of the Prince, it gave him great satisfaction.
But the noise of passive obedience and nonresistance being still fresh in my ears; and,
thinking the clergy would oppose their late doctrine by a contrary practice,
I inserted this sentence in the close of my letter: "`However,
I could now wish that those who have so lately
been preaching passive obedience to others,
may not be found in actual rebellion themselves.`"
I was not aware into whose hands it might fall; nor had I penetration enough to discern,
or apprehend the subtle distinctions contrived by the learned
clergy to reconcile their practice to their doctrine;
distinguishing and explaining it so as to make it, at last,
passive obedience and no passive obedience.
But the sentence above being then unfashionable,
my brother was directed to admonish me to forbear meddling any more with that subject.

These things gave me still more occasion to reflect,
and closely to consider the foundation of our own
religion and of those who pretended to propagate it.
For though that doctrine, rightly stated, is a Christian doctrine and duty,
yet the failure in practice renders that testimony, as to them, void,
how nicely and subtly soever they may interpret themselves out
of the practice of what the people understood,
and the priests intended they should understand by it at that time.
But though I was well pleased with the revolution of affairs at that time,
the circumstances thereof being attended with sufficient
evidence of a very particular providence of the Almighty,
yet I took offense at the clergy`'s appearing so much in it as they did,
who had lately so vehemently preached up contrary principles.

This great and sudden revolution in the government seemed to unhinge things for a time;
and few, if any, knew where they would at last fix.
The church was divided in judgment, if not in interest;
some few keeping to the practice of their former doctrine,
but the generality receding from it.
So that, for my own part, being young, and only a private person,
I could not see any certainty in anything we called religion, state, or politics;
all being interpreted as served the times;
or as if none of them had any certain or steady bottom, or longer continued the same,
than the humor or interest of Pretenders run that way.
Christianity, heaven, and eternal life, and the way there,
were the general pretenses of so many insincere and empty professors of Christ,
wholly strangers to his holy and divine nature;
that under deep humiliation in a view of these things,
and of my own lack of an experimental knowledge of God, in true contrition,
and bent of both mind and body before him in secret,
I often implored his divine wisdom and direction in a concern of the last importance;
in which, above all things, we ought to be most certain and clear,
both as to the object of faith, in things to be believed, done and suffered;
about which there are so many great and
unchristian-like contests in the pretended Christian world,
and so little of the wise, innocent,
and holy nature of that divine and heavenly thing we all talk and make profession of.

I think proper in this place,
to recount some of the gracious dealings of the Lord with me from my early days.
I was not naturally addicted to much vice or evil; and yet,
through the conduct of rude boys at school, I had acquired some things by imitation,
tending that way.
But as I came to put them in practice, by word or action,
I found something in myself at such times,
suddenly surprising me with a sense of the evil, and making me ashamed when alone;
though what I had said or done was not evil in
the common account of such as I conversed with,
or among men, in a common acceptation.
And though I did not know, or consider what this reprover was,
yet it had so much influence and power with me that I
was much reformed thereby from those habits,
which, in time, might have been foundations for greater evils;
or as stocks whereon to have engrafted a worse nature,
to the bringing forth of a more plentiful crop of grosser vices.

Nevertheless, as I grew up to maturity I had many flowings and ebbings in my mind;
the common temptations among youth being often and strongly presented:
and though I was preserved from guilt, as in the sight of men,
yet not so before the Lord, who sees in secret,
and at all times beholds all the thoughts, desires, words,
and actions of the children of men, in every age and throughout the world.

The lust of the flesh, of the eye, and the pride of life,
had their objects and subjects presented.
The airs of youth were many and potent; strength, activity,
and comeliness of person were not lacking, and had their share;
nor were natural endowments of mind or competent acquirements afar off; and the glory,
advancements and preferments of the world, spread as nets in my view,
and the friendship thereof beginning to address me with flattering courtship.
I wore a sword, the use of which I well understood,
and had foiled several masters of that science in the north and at London;
and rode with fire-arms also, of which I knew the use; and yet I was not quarrelsome;
for though I emulated, I was not envious.
This rule, as a man, I formed to myself, never to offend or affront any willfully,
or with design; and if, inadvertently, I should happen to disoblige any,
rather to acknowledge, than maintain or vindicate a wrong thing;
and rather to take ill behavior from others by the best handle, than to be offended,
where no offense was willfully designed.
But then I was determined to resent and punish an affront, or personal injury,
when it was done in contempt, or with design.
Yet I never met with any, save once; and then I kept to my own maxims with success;
and yet so as neither to wound, nor be wounded;
the good providence of the Almighty being ever over me and on my side,
as well knowing my meaning in all my conduct.
But, in process of time,
as these motions of corruption and sin became stronger and stronger in me, so the Lord,
in great goodness and mercy,
made manifest to my understanding the nature and end of them;
and having a view of them in the true light, and the danger attending them,
they became exceedingly heavy and oppressing to my mind.
And then the necessity of that great work of regeneration was deeply impressed upon me;
but I had no experience or evidence of it wrought in me hitherto.
This apprehension greatly surprised me with fear,
considering the great uncertainty of the continuance of the natural life;
and it began to put a secret stain upon the world and all its glory,
and all that I had to glory in; though I kept these thoughts within my own breast,
not knowing of any soul to whom I could seriously and safely divulge them.
And indeed none, for a considerable time,
discerned my inward concern by any outward appearance; which I found afterwards,
had been much to my advantage and safety.

It is admirable by what various steps the Lord is pleased to
lead the soul of man out of this world and the spirit of it,
home to himself; and yet I am apt to think, that, in his divine and unlimited wisdom,
he does not take the same outward method and steps with every one,
but varies the work of his providence as their
states and circumstances may best suit and bear.
By an accident that befell me, I was further alarmed to consider my ways,
the uncertainty of life, my present state, and latter end.

It was this: Intending to go to a country church with an acquaintance,
as we were riding gently along, my horse stumbling, fell and broke his neck,
and lay so heavy upon my leg that I could scarcely draw it from under him;
yet I received no hurt.
But as we stood by him I had this consideration,
that my own life might have been ended by that occasion,
and I did not find myself in a condition fit for heaven,
having yet no evidence of that necessary work of regeneration.
This brought great heaviness over my mind, which did not totally depart till,
through the infinite mercy of God,
I was favored with further knowledge and a better state.

Hitherto I had known the grace of God in me only as a manifester of evil and of sin,
a word of reproof, and a law condemning and judging those thoughts, desires, words,
passions, affections, acts and omissions, which are seated in the first nature,
and rooted in the carnal mind; in which the suggestions, temptations,
and influences of the evil one work and prevail.
By this divine grace I was, in some good degree, enlightened, reformed,
and enabled to shun and forbear all words and acts known to be evil,
and moral righteousness restored in my mind, and thereby brought forth in me.
I became then weaned from all my former acquaintance and company;
their manners and conduct, though not vicious, for such I never liked,
became burdensome and disagreeable; for they had not the knowledge of God,
nor such a conduct as I wanted.
Yet I did not know the divine grace in its own nature, as it is in Christ;
not as a word of faith, sanctification, justification, consolation and redemption;
being yet alive in my own nature.
The Son of God was not yet revealed in me; nor I, by the power of his holy cross,
mortified and slain; being without the knowledge of the essential truth,
and in a state contrary to him, and unreconciled.
But the Lord did not leave me here, but, in his matchless mercy,
followed me still by his holy admonitions,
and more and more inclined my mind in an earnest inquiry after himself,
and his own truth and Word; concerning whom,
I did not know of any in all the earth who could teach me, the world being universally,
as I judged by the general ways and courses of men, of all forms and ranks,
altogether ignorant of the Lord,
knowing only some historical and traditional hints concerning him,
and of his doctrine and ways;
which having little or no effect or influence upon the minds and conversations of men,
it seemed but a dead knowledge or image, and they being dead while they yet lived,
did not really and savingly believe in the true God, and Christ Jesus,
of whom they made profession and talked.
I did not then know that the Lord had any people in the world,
owned by his presence with them, as his flock and family;
which reminds me of that saying of the Lord, "`Nevertheless, when the Son of Man comes,
shall he find faith on the earth?`"

My mind being truly earnest with God,
thirsting unto death for the knowledge of the Way of Life,
he was pleased to hear the voice of my necessity; for I lacked present salvation,
and the Lord knew my case could not admit of further delay.
Being moved by his own free mercy and goodness,
even in the same love in which he sent his Son, the beloved, into the world,
to seek and save the lost; on the 1st day of the second month, in the evening,
in the year, according to the common account, 1689, being alone in my chamber,
the Lord broke in upon me unexpectedly; quick as lightning from the heavens,
and as a righteous, all-powerful, all-knowing, and sin-condemning Judge:
before whom my soul, as in the deepest agony, trembled, was confounded and amazed,
and filled with such awful dread as no words can reach or declare.

My mind seemed plunged into utter darkness,
and eternal condemnation appeared to enclose me on every side,
as in the centre of the horrible pit; never to see redemption from there,
or the face of him in mercy, whom I had sought with all my soul.
But in the midst of this confusion and amazement, where no thought could be formed,
or any idea retained, save eternal death possessing my whole man,
a voice was formed and uttered in me, "`Your will, O God, be done;
if this be your act alone, and not my own, I yield my soul to you.`"
In conceiving these words, from the Word of Life, I quickly found relief:
there was all-healing virtue in them; and the effect was so swift and powerful, that,
even in a moment, all my fears vanished, as if they had never been,
and my mind became calm and still, and simple as a little child;
the day of the Lord dawned and the Son of Righteousness arose in me,
with divine healing and restoring virtue in his countenance;
and he became the centre of my mind.

In this wonderful operation of the Lord`'s power, denouncing judgment in tender mercy,
and in the hour of my deepest concern and trial, I lost my old self,
and came to the beginning of the knowledge of Him, the just and the Holy One,
whom my soul had longed for.
I now saw the whole body of sin condemned in my own flesh; not by particular acts,
as while traveling in the way to a perfect moral state only,
but by one stroke and sentence of the great Judge of all the world,
of the living and of the dead, the whole carnal mind, with all that dwelt therein,
was wounded, and death begun; as self-love, pride, evil thoughts, and every evil desire,
with the whole corruption of the first state and natural life.

Here I had a taste and view of the agony of the Son of God,
and of his death and state upon the cross,
when the weight of the sins of all human kind were upon him,
and when he trod the wine-press alone, with none to assist him.
Now all my past sins were pardoned and done away; my own willings, runnings,
searchings and strivings, were at an end;
and all my carnal reasonings and conceivings about the knowledge of God,
and the mysteries of religion, were over; which had long exercised my mind,
being then natural, both day and night,
and taken away my desire of food and natural repose.
But now my sorrows ended, and my anxious cares were done away; and this true fear being,
to me, the initiation into wisdom, I now found the true sabbath, a holy, heavenly,
divine, and free rest, and most sweet repose.
This deep exercise being over, I slept till the next morning,
and h:id greater and better refreshment and
comfort than I had felt for some weeks before.

The next day I found my mind calm and free from anxiety,
in a state like that of a young child.
In this condition I remained till night:
and about the same time in the evening that the visitation, before related, came upon me,
my whole nature and being, both mind and body, was filled with the divine presence,
in a manner I had never known before, nor had ever thought that such a thing could be;
and of which none can form any idea, but what the Holy thing itself does give.

Divine Truth was now self-evident; there lacked nothing else to prove it.
I needed not to reason about him;
all that was superseded by that divine and truly wonderful evidence and light,
which proceeded from Himself alone, leaving no place for doubt, or any question at all.
For as the sun, in the open firmament of heaven, is not discovered or seen,
but by his own light, and the mind of man determines thereby, at sight,
and without any train of reasoning, what he is; even so, and more than so,
by the overshadowing influence and divine virtue of the Highest, was my soul assured,
that it was the Lord.
I saw him in his own light, by that blessed and holy medium,
which of old he promised to make known to all nations;
by that eye which he himself had formed and opened,
and also enlightened by the emanation of his own eternal glory.

Thus I was filled with perfect consolation,
which none but the Word of Life can declare or give.
It was then, and not till then, I knew that God is love,
and that perfect love which casts out all fear.
It was then I knew that God is eternal light, and that in him is no darkness at all.

I was highly favored also with a view of the manner of the operation of the Almighty,
in assuming human nature, and clothing therewith his inaccessible divine light and glory,
even with an innocent, holy, and divine soul and mind, homogeneal to the children of men;
as with a veil, whereby the Most High condescended to the low condition of man,
and in whom also man, being refined as the tried gold,
and thereby fitted for the holy One, can approach to him, as by a proper medium,
and therein dwell with the Lord, and enjoy him forever.

From henceforth I desired to know nothing but the Lord,
and to feed on that bread of life which he alone can give,
and did not fail to minister daily, and oftener than the morning: and yet,
of his own free will and goodness, he was pleased to open my understanding, by degrees,
into all the needful mysteries of his kingdom, and the truths of his gospel;
in the process whereof he exercised my mind in dreams, in visions, in revelations,
in prophecies, in divine openings and demonstrations.
Also, by his eternal and divine light, grace, spirit, power and wisdom or word,
he instructed and informed my mind; and by temptations also, and provings,
which he allowed Satan to minister; that I might see my own weakness and danger,
and prove, to the utmost, the force and efficacy of that divine love and truth,
by which the Lord, in his boundless goodness and mercy, had thus visited my soul.
By all things I saw and heard in his wonderful works of creation,
by my own mind and body, by the animals, reptiles, and vegetables of the earth and sea,
their ranks and subserviencies one to another, and all of them to the children of men;
by the sun, moon and stars, the innumerable host of heaven,
and that boundless space which they move in, without interfering,
or any way annoying one another, all depending one upon another,
all connected without a chasm, and all governed by the steady laws,
which the Almighty Word and Fiat who gave them being, and formed them, placed them under,
and settled them in.

But, as the diadem of all, and the only true and certain way,
when it pleased the Most High, by the effusion of his own goodness,
to reveal in me the Son of his love, even his wisdom and power,
by whom he designed and effected all things, then I was taught to fear him;
then I was taught to love him; then, and not aright till then,
was my soul instructed and informed indeed.

But these secret operations were confined to my own breast,
so that no one knew anything of them; an alteration was observed in me,
but the cause of it was not seen.
I put off my usual airs, my jovial actions and address, and laid aside my sword,
which I had worn, not through design of injury, or fear of any,
but as a modish and manly ornament.
I burnt also my instruments of music,
and divested myself of the superfluous parts of my apparel,
retaining only that which was necessary, or deemed decent.
I declined the public worship, not with a design to join myself to any other sect;
for I was rather apt to conclude, from what I had observed,
that these manifestations were peculiar to me,
and that there was not any people I might properly associate with; and also,
I was induced to believe,
that one day I should be obliged to appose the world in matters of religion,
but when or how that should be brought to pass, I did not foresee.

Remaining in a still and retired state, and the Book of Life being opened in my mind,
I read what the Lord himself, by the finger of his power, had written,
and the Lion of the tribe of Judah opened there; and the Scriptures of truth,
written by Moses and the prophets, the evangelists and apostles of Christ,
were brought to my remembrance daily, when I did not read them,
and made clear and plain to my understanding and experience,
so far as they related to my own state, and also in a general way;
though I lusted not to know any mystery or thing contained therein, other than the Lord,
in his own free will and wisdom, thought fit to manifest.

As the nature and virtue of divine truth increased in my mind,
it wrought in me daily a greater conformity to itself, by its own power;
reducing my mind to a solid quietude and silence,
as a state more fit for attending to the divine Word,
and distinguishing it from all other powers,
and its divine influences from all imaginations and other motions:
and being daily fed with the fruit of the Tree of Life,
I desired no other knowledge than that which was thus given me.

On the afternoon of the 21st day of the eleventh month, 1689,
silence was commanded in me, though not by me,
in which it was given me to remain till the evening; and then that Scripture,
John 13:10, was brought to my remembrance; which I began to write, and proceeded,
as things opened in my mind, and in manner following:

[.embedded-content-document.paper]
--

Jesus says to him, he that is washed needs not, save to wash his feet,
but is clean every whit.`"
The washing of the feet signifies the cleansing of the ways;
and those who are washed in the laver of regeneration, will walk in clean paths,
and bring forth fruit according to the nature of the Tree of Life.
Such will walk in faith, love, obedience, peace, holiness, righteousness, judgment,
mercy, and truth.
And whosoever says he is of the Father, and has not charity, he is a liar,
and the living Word rules not in him; for whosoever has known the Word,
and abides therein, has the Father,
because the word of Truth bears witness of the Father;
and whosoever is born of God will keep his commandments.

Hear, O you mountains, and give ear, O you cedars of Lebanon, the Lord,
the light of Jerusalem, the life of saints, has put a song of praise in my mouth,
and caused me to rejoice in the valley of Jehoshaphat.
I was in the desert, and he led me forth by the power of his right hand; I was fallen,
and he stretched out his arm, and set me upright; yes, I was dead, and, behold,
he raised me from the grave.
I was also hungry, and he has led me with the bread of his everlasting covenant.
I weakly fainted in the way;
but the King of the holy mountain revived me by the word of his promise.
He has laid my foundations with beauty, with precious stones of various colors;
and the superstructure is all glory.

Fear not, you of low degree; for with our God there is no respect of persons: fear not,
you little ones; for he showed you his lovingkindness of old;
and with him there is no shadow of turning.
Awake, awake, you who sleep in trespasses and in sins;
for the trumpet sounds aloud in the city of our King: be raised, you dead,
and stand upright before him; for he is true and faithful who sent forth his Word.
Conquer, O conquer, you holy love of God, those who in ignorance oppose your mercy.
Smite your people with great thirst, O Lord God of mercy,
that they may drink abundantly of the waters of your salvation.
Make them hungry, O Life of the just, that they may eat abundantly,
and be refreshed by the bread of life everlasting.
Call them from the husks of outward shadows,
and feed them with your hidden manna and Tree of Life.
Take from them the wine of the earth, which they have abused to abomination,
and give them the fruit of the living Vine at the Father`'s table.
Wash them in the laver of regeneration, by your holy Spirit;
and cleanse them by your righteous judgments, that they may retain your love.
Consider their weakness, O Father of mercies; for they are flesh and blood,
and cannot see through the veil into your holy habitation.
Rend the veil of carnal wisdom in the earthly mind, you wonderful Counsellor,
and display your glory in its full perfection.
Dissolve the great world of pride, covetousness, drunkenness, lying, cursing,
oppressions, filthy communications, and whoredoms;
and establish righteousness and peace forevermore.

I was silent before the Lord, as a child not yet weaned; he put words in my mouth,
and I sang forth his praise with an audible voice.
I called unto my God out of the great deep; he put on bowels of mercy,
and had compassion on me, because his love was infinite, and his power without measure.
He called for my life, and I offered it at his footstool; but he gave it me as a prey,
with unspeakable addition.
He called for my will, and I resigned it at his call;
but he returned me his own in token of his love.
He called for the world, and I laid it at his feet, with the crowns thereof;
I withheld them not at the beckoning of his hand.
But mark the benefit of exchange!
For he gave me, instead of earth, a kingdom of eternal peace;
and in lieu of the crowns of vanity, a crown of glory.

They gazed upon me; they said I was mad, distracted, and become a fool;
they lamented because my freedom came.
They whispered against me in the vanity of their imaginations;
but I inclined mine ear unto the whisperings of the Spirit of Truth.
I said, what am I, that I should receive such honor?
But he removed the mountains out of my way,
and by his secret workings pressed me forward.

--

[.offset]
+++[+++At another time he penned the following prayer:]

[.embedded-content-document.paper]
--

O Almighty, incomprehensible, and infinitely merciful Lord God,
forasmuch as none can enter into your rest, unless he be regenerated and renewed,
I humbly beg, in the name and for the sake of your Son Christ,
that you will be pleased to wash me in the water of life,
and purify my polluted soul with the holy fire of your infinite love;
that I may live in you, and walk in the living way of truth, love, peace, joy,
righteousness, holiness, temperance, and patience,
so long as you are pleased to continue me in this garden of labor.
And be my strength, O my righteousness! that I go not astray from your paths,
through the frailty of this earthly tabernacle; but give me daily the bread of life,
which you freely boldest forth to the hungry all the day long.
And inasmuch as none can eat of this bread,
but those who hunger and thirst after righteousness, give me a fervent desire,
my salvation! and a saving faith, a living faith,
to lay hold on your most certain promise;
that I may be made partaker of the glory that is laid
up for your servants in your everlasting habitations.

--

The conversation of mankind being generally upon trifles,
not worthy of the thought of rational creatures,
tending much more to vice than to virtue;
and my mind being a little renewed by the influence of the divine truth,
I was much in silence and alone:
and what thoughts I had being upon other objects than those I
had been conversant with before I knew the truth,
I wrote also some other things, as they were from time to time presented in my mind,
without any search or labor.

[.offset]
+++[+++The following aspirations show that he experienced the ebbing of the
divine life after seasons of enjoyment of which he has spoken.]

[.embedded-content-document.paper]
--

O Lord, take pity on a perishing soul, borne down under a multitude of vile affections,
trodden under foot by the insolence of the wicked one.
I faint under the yoke, O you most faithful and true! and have no hope but in you.
My heart is weary with sighing under troubles, and my pains increase.
When shall my day come, O redemption of the just?
and when shall I see the seal of my salvation?
O work in me the law of everlasting love, and fix my boundaries there forever and ever.
O you, who said unto the worlds, Be you finished, and it was so; say unto my soul,
Be you perfect, and it shall be done.
Purify me, O God, by the judgments of your right hand,
and let your mercies ever be before me: raise me,
that I may praise you in the firmament of your power: humble me,
that I may exalt your name in the midst of the nations.

--

A deep consideration entered into my mind,
concerning the states of many persons in the national way of worship,
as also among the dissenters from it; some of whose preachers I had occasionally heard,
particularly Dr. Richard Gilpin of Scaleb-castle,
an able physician and an ancient celebrated preacher among the Presbyterians;
and I had observed many others who seemed to have sincerity
and good intentions in their respective modes of worship.
From here a question arose, whether it might not he through my own fault,
for lack of the true knowledge of God in myself heretofore,
that I did not enjoy his presence among them, as I had done, through his grace,
since I had been visited by the Lord,
and drawn into retirement by the comforts of his secret presence?
Upon which I determined to go again and see,
whether the good presence of the Lord would be manifested in me there,
as alone in my retirements.
The place I went to was that called St. Cuthbert`'s, in the city of Carlisle;
there being usually prayers and a sermon there in the afternoon of the first-days;
but not with that pomp, noise, and show, as at the cathedral,
and therefore I rather chose it.
Being seated there, as I had been often, and my mind retired inward,
to wait upon the Lord, as he himself had taught me,
the Lord would not own that worship by his sensible presence,
though in himself omnipresent, nor me in that place;
but my mind became filled with darkness, and overwhelmed with trouble,
to so great a degree, that I could hardly stay till the time was over.
But lest I should do a thing which might be looked upon as indecent,
I continued to the end, and returning to my chamber in trouble,
and I went not among any of them any more.
Though I thus declined all outward worship, or that which was called so,
determining to follow the Lord wheresoever it might please him to lead me;
yet I found universal love, good will, and compassion in my mind, to all sorts of people,
whether Protestants of different denominations, Romans, Jews, Turks, or heathens.
But I observed their several religions, or what they accounted so, every man for himself,
to be mostly the effect of education, tradition, or chance.
For he who is born and educated among the Protestants of any sect respectively, is such:
he who is born and educated among the Romans, is a Roman; and so of all the rest,
till by accident, or interest, they change from form to form; or sometimes,
though more rarely, through the inward convictions of the Holy Spirit of God,
they obtain a right understanding and worship him in truth.
Therefore I stood still, and waited for the further leadings of the Lord,
and the evidence of his presence, what to do, or where to abide; though the Protestants,
in general, especially the national church, were still nearer to me than any other sect.

Thus, the world, in general,
appearing to me dead with respect to the true knowledge of God,
notwithstanding the truth of some notions they held in
relation to matters of fact and literal interpretation,
and as walking statues,
I did not then see that the Lord God had any collective body of people at that day,
who truly worshipped him, according to his own institution;
or that anyone on earth knew some things, which the true and living God had been pleased,
of his own free grace, and which I could neither ask or think of, to communicate unto me;
though I found, in due time, I had been in this point mistaken, as the prophet of old,
who thought he had been alone, and all Israel departed from the Lord.

As the life of the Son of God prevailed in me, I became more and more innocent, humble,
loving, and charitable to the poor; to whom I gave money according to my ability,
and without ostentation, or expectation of reward:
one instance of which I think proper to relate,
it being attended with some particular circumstances.

At the time king William the Third was subduing Ireland, some persons and families,
retiring from the inconveniences and hardships of the war, came into England,
and among others an Independent teacher, and with him a youth, his son;
who being in need, requested charity; and coming to my father`'s house in Carlisle,
where I then was, I gave him half a crown; which being more than he expected,
or had received, as he said, from any other person in town,
he took occasion from there to enter into discourse concerning some points of religion,
and civilly asked of me, what form of worship I attended?
I replied, I had formerly frequented the national worship, according to my education;
but then, and for some time before, had declined it, as also all other outward forms,
keeping retired in my chamber, on the usual days appointed for that purpose.
And when he heard this, he asked if his company the next Lord`'s day, as he called it,
might be acceptable, for the national worship was not agreeable to him; I gave liberty,
and he and his son came accordingly to my chamber, where I was sitting alone in silence,
waiting upon the Lord.

After a civil reception, and short pause of silence,
he began to magnify the great providence of God,
in reestablishing and advancing that people, meaning the Independents and Presbyterians,
who had been so much hated, persecuted and suppressed,
now to be made the chief instruments of deliverance, restoration,
and reformation to the right way of the Lord, and to his own glory.

As he spoke, I observed he himself was not upon the true foundation,
nor acquainted with the mind of the Lord on that account;
but spoke from his own imagination and partiality to his own sect,
as he and they desired it should have been; his mind natural and carnal,
and his views outward, toward the power and dominion of this world,
as the Jews were at the time of the appearance of Christ among them;
and as soon as he came to a period,
finding my mind filled with the sweetness and meekness of divine truth, I replied:
"`The divine providence is indeed great over the children of men,
and apparently over this nation and her dependents at this day;
and the necessity of a right and thorough reformation is very great,
and in the proper time and way of the Almighty, will be brought to pass.
But it will be neither by the means nor instruments now in your view;
for all the contenders, one against another, by destructive force,
are of one spirit divided against itself, under different forms and views,
in which the strongest will advance themselves and their own way;
but cannot by such means, reform either themselves or others,
as they ought to do in the sight of God, who does not approve or countenance violence,
bloodshed, and unrighteousness in one sect, and condemn the same things in another;
and will therefore bring about that right reformation,
by instruments of a different kind, and by another means and way: as it is written,
'`Not by might, nor by power; but by my Spirit, says the Lord.`'`"

Upon this the stranger was much broken in spirit, and the tears ran down his beard,
and dropped upon his knee, as he sat by me; and after that being filled with love,
the same which had reached him from my spirit, he embraced me in his arms,
rejoicing that he had met with me, but said no more on any religious subject.
Soon after he departed, and I saw him no more.

I now proceed with the account of my further progress.
In writing the last paragraph of a piece, the people called Quakers were suddenly,
and with some surprise, brought to my mind; and so strongly impressed on my remembrance,
that from that time forward I had a secret
inclination to inquire further concerning them,
their way and principles.

It was sometime in the fifth month, in the year 1691, when an opportunity was presented.
The occasion of it was some concerns that I had in the west parts of Cumberland,
when lodging at an inn kept by one of that profession, on a seventh-day night,
and inquiring of him concerning some points of their religion,
I perceived no material difference between his sentiments and mine,
in the particulars then asked after;
and he also perceived I was nearer them than he or perhaps any other had thought,
for I had formerly Opposed the same man in some things,
which gave him occasion to inform me of their meeting, to be held the next day,
at a country village called Broughton.

As I had been desirous to be rightly informed concerning that people,
and to see them as in truth they were, I was pleased with the opportunity;
and the next morning the Friend and I set forward toward the meeting.
He being zealous to have me further informed and convinced of the truth of their way,
spoke of many things as we rode along, and with a good intent:
but my mind being composed, and its attention directed towards God,
who knew I wanted only to see the truth, and not to be deceived,
I could not take any distinct notice of what the Friend said; which he perceiving,
after some time desisted, and said no more.
And then we rode some miles together in profound silence;
in which my mind enjoyed a gentle rest and consolation,
from the divine and holy presence.

When we came to the meeting, being a little late, it was full gathered;
and I went among the throng of the people on the forms,
and sat still among them in that inward condition and mental retirement.
And though one of their ministers, a stranger,
began to speak to some points held by them,
and declaim against some things held by others, and denied by them;
particularly predestination as asserted by the Presbyterians;
yet I took not much notice of it.
I did not doubt but like all other sects, they might have something to say,
both for their own and against the opinions of others;
yet my concern was much rather to know whether they were a people gathered
under a sense of the enjoyment of the presence of God in their meetings;
or, in other words, whether they worshiped the true and living God,
in the life and nature of Christ, the Son of God, the true and only Savior:
and the Lord answered my desire according to the integrity of my heart.

For, not long after I had sat down among them,
that heavenly and watery cloud overshadowing my mind,
broke into a sweet abounding shower of celestial rain,
and the greatest part of the meeting was broken together,
dissolved and comforted in the divine presence of the true, heavenly Lord;
which was several times repeated before the meeting ended.
In the same way, by the same divine power, I had been often favored before when alone,
and when no eye but that of heaven beheld, or any knew, but the Lord himself; who,
in infinite mercy, had been pleased to bestow so great a favor.

And, as many small springs and streams, descending into a proper place,
and forming a river, become more deep and weighty; even so,
thus meeting with a people gathered of the living God,
into a sense of the enjoyment of his divine and living presence, through Jesus Christ,
the Son of God and Savior of the world,
I felt an increase of the joy of the salvation of God; and the more,
by how much I now perceived I had been under the
like mistake as the prophet of God of old;
but now was otherwise informed, by a sure evidence and token;
by the witness of the divine truth, in which no living soul can err, or be deceived;
being self-evident and undeniable in all those who truly know him.

Our joy was mutual and full, though in many tears,
as in cases of the deepest and most unfeigned love;
for the Friends there being generally sensible I was affected and tendered with them,
by the influence of the divine truth they knew and made profession of,
did conclude I had been at that time, and not before,
convinced and come to the knowledge of the way of truth among them;
and their joy was as of heaven, at the return of a penitent;
and mine as the joy of salvation from God,
in view of the work of the Lord so far carried on in the earth; when I had thought,
not long before, there had scarcely been any true and living faith,
or knowledge of God in the world.

The meeting being ended,
the peace of God which passes all the understanding of natural men,
and is inexpressible by any language but itself alone,
remained as a holy canopy over my mind, in a silence out of the reach of all words;
and where no idea but the Word himself can be conceived.
But being invited, together with the ministering Friend,
to the house of the ancient widow Hall, I went willingly with them:
but the sweet silence commanded in me still remaining,
I had nothing to say to any of them till He was pleased
to draw the curtain and veil his presence;
and then I found my mind pure,
and in a well bounded liberty of innocent conversation with them.

Having stayed there a short time, I was invited to dinner at the house of Richard Ribton,
an ancient and honorable Friend in the village, where I was made kindly welcome,
and where I had great freedom of conversation.

Being now satisfied, beyond my expectation, concerning the people of God,
in whom the Lord had begun,
and in a good measure carried on a great work and reformation in the earth,
I determined to lay aside every business and thing which might
hinder or veil in me the enjoyment of the presence of the Lord,
whether among his people or alone;
or obstruct any service whereunto I was or might be called by him;
especially things of an entangling or confining nature;
not regarding what the world might say, or what name they might impose upon me.
