== Chapter II

The business being over which had brought me into that part of the country,
I returned to Carlisle,
where I had been but about two weeks till the Friend of the inn before mentioned,
coming to town, informed me of their meeting for business and affairs of their Society,
and invited me to it, being about four miles distant.

At first I was a little surprised that he should invite me to such a meeting,
and hardly thought him prudent in it;
for I had not yet made any outward profession with them,
or declared myself of their communion.
But though I found some aversion, rather than inclination, towards it,
yet I yielded to go,
that I might see in what spirit and wisdom they managed the
discipline and business of their Society in matters of religion,
that I might view them a little more clearly in all circumstances,
before I should openly declare for their way in all things--some doubts yet
remaining as to some points--and see whether they thoroughly agreed with the
idea I had conceived in my mind of the state of the church of Christ,
namely: that they believed in God and Christ;
were settled in the practice of Christian morality;
that they were able to suffer any persecution, or opposition, for true religion,
when thereunto called, in the course of divine providence; that the characteristic,
mark of the disciples of Christ should be fairly upon them,
"`to love one another,`" not in word and in tongue only, but in deed and in truth;
and that they should be preserved by that love, in uniformity and unity among themselves;
and also be loving and kind to all men, as occasion might offer; and evince the same,
by doing them good, and never any harm.
These qualifications I had deemed sufficient to
demonstrate such to be the children of God,
brought forth in his image, righteousness and true holiness, in the inner man.

The meeting being set, they had first a time of silence, waiting upon God,
as I did believe and practice, for the renewing and strengthening of their minds;
and after that they proceeded upon the business of the day.
It happened at that time that a matter of great importance among them was debated,
and not without some warmth on both sides;
but the zeal of both did not arise from the same root.
It was concerning the manner and essence of their discipline,
which a sect among them had opposed,
from the time of the first proposal of any discipline in the Society.
The debates arising pretty high, and they observing me to be there, and most of them,
I doubt not, having heard I seemed to favor their way;
and being cautious lest I should take offense at their debates,
not knowing the state of the case, or, perhaps,
not qualified to judge in matters so foreign to me,
some of them prudently put the Friend who had introduced me,
upon an inoffensive way to procure my absence;
and accordingly he called me into an outer room,
offering to discourse on some foreign subject.
But as my mind, in time of silence in the meeting,
had been comforted in the life of truth, I remained under the sense of it;
having taken little other notice of what had passed in point of argument,
than in what spirit they managed and contended on each side.

Though I observed the Friend`'s good intent in calling me out,
I could take no cognizance of what he said; for a deep thought now entered my mind,
whether these could be the people of God?
since they seemed to be divided among themselves,
and treat one another with an acrimony of language, which, I thought,
could not arise from love, neither altogether suited to the humility of Jesus,
the true Christ.
The Friend observing my silence, and that I was under a deep inward concern,
became silent likewise, and a trouble also seized him, but of another kind;
for I was concerned to know the truth, and on what side, if on either, it might lie;
and he was afraid I had taken, or might take offense,
and depart from the beginning I had made among them.

Thus we remained silent for some time;
during which I plainly observed a struggle between two distinct powers working in myself,
which exhibited two different conclusions in my mind concerning the matter then in hand,
and the spirits and persons concerned therein, namely: the first was Truth,
establishing himself in his own nature,
a law-giver and ruler in every member of his church and body,
as alone needful unto them who were truly so.
But as He who knows all things, did foresee that many would, in time,
come into that profession, as of old, without any knowledge of divine truth,
or the work of it in themselves, but, as thieves and robbers, climbing up some other way;
by education, tradition, imitation, or sinister interests and worldly views; who,
not being under the rule and law of grace in the second birth,
would act and say of themselves,
contrary to the way of truth and the church of the living God; and therefore,
in his wisdom and power, working in the minds of the just, he had early established,
and was yet more firmly establishing, a duo order among his people;
for preserving the right,
and passing judgment and condemnation on the wrong and evil doers;
that such as should profess the truth of God, and yet walk contrary to the same,
bringing forth fruits of another kind,
might be bounded and confined by outward moral rules,
adapted to human reason and understanding.

Secondly, that the spirit of this world had been,
and still was working in the other sort, to oppose all order and discipline,
and to live loose as they wish, without any rule or account to the Society,
though professing the same truth with them; wanting to be judged only by their own light,
or what they called so, and accountable only to the spirit in themselves;
though several among that party were only against some branches of
the discipline already established by the body of the Society,
and not against the whole.

During this time of silence I clearly beheld the
contrary natures and ends of these differing spirits;
the one truth, the other error; the one light, the other darkness;
the one for moral virtue and a holy pure mind,
and the other for a loose unbounded liberty; and yet, that these last, as creatures,
did not see the sophistry of the evil one, to whom themselves were instruments,
nor the snare; but intended well, in their own view and way of conceiving things.

As these distinctions were gradually made clear in my understanding at that time,
the load and trouble I was under abated;
and at last my mind settled down again to its own centre in peace, and became serene,
as before; which, being fully sensible of, I was cheerful, and said to the Friend,
we may now return into the house, for the danger is entirely over.
I knew your meaning before we came out of the other room;
and commend your care and caution.
With this he was greatly pleased; and so were the rest, when they came to know it.

After this I was at some other meetings;
but little notice was taken of it by any of my relations or acquaintance,
till the time of the assizes at Carlisle,
where some Friends being prisoners in the county jail, for non-payment of tithes,
others attended the assizes, as their custom was,
the better to obviate the occasion of troubles or hurt to any of the Society,
and to minister counsel or other help, as need might be;
and these went to a meeting at Scotby, about two miles from the city;
and there I went also.

During the time of the meeting I found an unusual load on my spirit,
and hardness in my heart; insomuch that I could hardly breathe under the oppression;
nor could I say I had any sense of the comforts of the divine presence there,
but that the heavens were as thick brass, and the bars thereof as strong iron.
But though I had no enjoyment in myself,
yet I was sensible the presence and goodness of the Lord were there,
and many therein greatly comforted;
and therefore did conclude my condition of mind was from some other cause,
and not relating to the state of the meeting in general.
After the meeting was over, one of them asked me how I did; I answered, indifferently.
Then he and some others perceived my spirit was oppressed,
and sympathized with me therein.
I could not, all this time,
perceive the particular matter which thus affected me,--for I knew not of
anything I had done or said to bring it upon myself--till that evening,
being returned to my father`'s house, very solitary, silent, and inward,
there came in one Thomas Tod, an acquaintance of mine; who,
after some compliments of civility--for at that time I had not quite
declined the common modes of salutation-- desired to speak with me apart;
and then told me that he had a trial to come on next day,
concerning certain houses of his in the town of Penrith,
being the greatest part of all he had in the world;
that one of the witnesses to his deeds of conveyance was dead;
another of them gone into Ireland, and could not be had; but I, being the third,
and having made the writings, he hoped, through my evidence and credit,
to gain his just point against his unfair adversary;
and desired me to be in readiness in the morning;
for the trial was likely to come on very early.

As soon as he began this relation,
the word of life began likewise to work in me in a very powerful manner;
and the hammer of the Lord I sensibly felt,
and saw to be lifted up upon that hardness of heart,
which for some time had been my state; and it began to be broken, softened,
and dissolved; and the sense of the love of God in some degree to be renewed.
Then I saw plainly that this was the hard thing I had to go through,
and that now was the time of trial, wherein I must take up the cross of Christ,
acknowledge his doctrine in that point fully and openly,
according to the understanding given me; and to despise the shame and reproach,
and other sufferings, which I well knew would ensue quickly;
or I must forsake the Lord forever.
For, denying his doctrine, in the sense I had now plainly seen it,
would be denying himself before men; and if I had then denied him,
I could expect no less, but according to his word, to have been immediately,
and forever denied of him,
and left under that hardness of heart and lack of the enjoyment of his divine presence,
wherewith I had been favored before,
and all the dreadful consequences of a beginning so woful.

But according to the advances of the word and work of the Lord in me at that time,
my heart inclined to him: as my acquaintance was speaking, and by the time he had done,
I was furnished with a full resolution to give him a plain and direct answer;
which was on this manner:
"`I am concerned it should fall out so;--for I had a real respect for him,
and saw his case to be very hard--I will appear if it please God,
and testify what I know in the matter, and do what I can for you that way;
but I cannot swear.`"

This was so great a surprise to him,
both from the nature of his case and confidence he had of my ready compliance,
he having had no suspicion of my present condition till that moment,
that he broke into a passion, and with an oath, or curse, said, "`What,
you are not a Quaker sure!`"

Though I had made confession to the truth so far, in that point,
and the divine presence sensibly returned in me, yet, upon this I was again silent,
till clear in my understanding what to answer in sincerity and truth.
For as nobody before that time had called me a Quaker,
so I had not assumed the appellation; which being given in reproach, was not grateful;
though the thing, in its proper sense, most delightful.
Nor did I then see whether I had so much unity with all their tenets as might
justify me in owning the name,--for in the unity of divine love and life only I had
known them--till the power of that life of Him who forbids all oaths and swearing,
arising yet clearer and fuller in me, opened my understanding, cleared my way,
and enabled me thereto; and then I said, "`I must confess the truth, I am a Quaker.`"

As this confession brought me still nearer to the Son of God,
his love increasing yet more sensibly in me,
so likewise it heightened the perplexity and disturbance of my friend,
whose case thereby became more desperate, in his own opinion.
Upon which, in an increase of heat,
and expressions therefrom suiting so obvious a disappointment,
as it then appeared to him,
he threatened to have me fined by the court and
proceeded against with the utmost rigor of the law;
saying, "`What! must I lose my estate by your groundless notions and whims`'?`"

But the higher my enemy arose and raged in this well-meaning, but mistaken man, who thus,
without design, became the instrument of my trial,
the fuller and more powerful still was the love of God;
whose cause I had now espoused through his own aid and the
power of an endless life from him made manifest in me.
I replied, in that calm of mind and resignation to the will of God,
that the life of the Son of God enables to and teaches,
"`You may do what you think proper that way,
but I cannot comply with your request in this matter, whatever be the consequence of it.`"
And then he departed under great dissatisfaction,
with all the threats and reproaches his enraged passions could suggest,
under a view of so great loss.

Immediately I retired into my chamber;
for perceiving my grand enemy to be yet at work to introduce a slavish fear,
and by that means subject my mind and bring me again into captivity and bondage,
I was willing to be alone and free from all the interruptions of company,
that I might more fully experience the arm of the Lord and his
divine instructions and counsel in this great exercise.

The enemy being a crafty and subtle spirit, wrought upon my passions,
not fully subjected, and artfully applied to my natural reason,
my understanding not being fully illuminated, as his most suitable instrument.
He urged the fine and imprisonment, and the hardships accompanying that condition,
and how little help I could expect from my father or friends,
who would be highly displeased with me, for so foolish and unaccountable a resolution,
as they would think it; and also the scoffings, mockings, derision, scorn, contempt,
loss of friends and friendships in the world, with such other inconveniences, hardships,
and ill consequences, as the enemy could invent and suggest.

During all this time, from about eight in the evening till midnight,
the eye of my mind was fixed on the love of God, which still remained sensibly in me,
and my soul cleaved thereto in great simplicity, humility, and trust therein,
without any yielding to Satan and his reasonings on those subjects,
where flesh and blood in its own strength is easily overcome by him.
But about twelve at night the Lord put him to utter silence, with all his temptations,
for that season, and the life of the Son of God alone remained in my soul; and then,
from a sense of his wonderful work and redeeming arm,
this saying of the apostle arose in me with power,
"`The law of the spirit of life in Christ Jesus,
has made me free from the law of sin and death.`"

Then the teachings of the Lord were plentiful and glorious;
my understanding was further cleared, and his holy law of love and life settled in me;
and I admitted into sweet rest with the Lord my Savior,
and given up in perfect resignation to his holy will,
in whatsoever might relate to this great trial of my faith and obedience to the Lord.
In the morning I went up toward the hall where the judges sat,
expecting to be called as a witness in the case before mentioned;
but before I reached the place, I saw my said acquaintance approaching me,
with an air in his countenance denoting friendship and affection; and when met, he said,
"`I can tell you good news; my adversary has yielded the cause;
we are agreed to my satisfaction.`"

Upon this I stood still in the street,
and reviewing in my mind the work of the Lord in me the night before, as already related,
this Scripture came fresh into my remembrance, in the life of it,
"`It is God who works in you, both to will and to do of his good pleasure.`"
I was sensible it was the Lord`'s doing, and accounted it a great mercy and deliverance;
though I was by this means exposed to the view and observation of all, the pity of many,
as they judged of my case,
and the scoffs and censures of the baser and more ignorant sort,
which was for Christ`'s sake only; for none had any immorality to charge me with.

This happening at the time of the assizes, and people from all quarters being there,
I quickly became the common subject of discourse and debate.
Few could believe the report, and many came to see;
and during the assizes would get together, talking and wondering;
and when they happened to see me afar off in the streets, would come in crowds to gaze.
Some would take off their hats, and pretend to show more than ordinary complaisance,
saluting me as at other times; but I not making any returns of that kind,
some would fleer, and giggle, and scoff, and grin, and run away in loud laughter,
saying I was mad.
Yet some others were struck with another passion; they turned pale, looked sorrowful,
and returned weeping.
And one who had been educated at a university, to show at once his temper, manners,
and learning, after he had gazed upon me a while among the baser sort, cried out,
as if he had then been surprised with the discovery of some new system,
"`He knows not a genus from a species!`" when there was
not anything previous leading to such an expression.
Yet he was mistaken in that; for I knew very well that dog is a genus, and cur, bull-dog,
and blood-hound, are distinct species of that genus; and at that time,
saw the nature and way of these brute animals too much resembled in that giddy mob;
though I said very little to any of them, but gave them my face to their fill of gazing.
Some who, but a day or two before, dared not have discovered a disobliging look upon me,
now insulted and triumphed; which put me in mind of a saying of Job, "`But now they,
who are younger than I, have me in derision;
whose fathers I would have disdained to set with the dogs of my flock;`" and
likewise of some expressions in that little piece before inserted;
which I did not think, at the time of writing it, would be so soon, if ever,
fulfilled upon myself, namely: "`They gazed upon me; they said I was mad, distracted,
and become a fool; they lamented because my freedom came.`"

The fool`'s pretended pity and instructions,
who could not see and pity his own miserable case, or knew what himself said,
was hardest to bear: yet all these things did not provoke or move me;
for the grace and presence of the Lord was with me,
and were my strength and preservation.
My heart was surrounded with a rampart of invincible patience,
and my soul filled with divine love.
This usage gave me a much clearer view of the low, mean, miserable,
brutish state of many men, and of the greatest part of that mob, than ever I had before,
or could have imagined.
But I was more civilly used by some counsellors who came the circuit from London,
among whom I had some business; especially Dormer, who was afterwards a judge:
they were kind, familiar, and without a scoff or taunting grin.

The business of the assizes being over, some of my acquaintance,
gentlemen both of town and country, who wished me well, in their own sense,
thinking I had been deluded, as they usually called it, by the Quakers,
consulted how to restore and reclaim me.
Several ways were proposed,
especially by a meeting and consultation of some of the clergy; who, they imagined,
might solve those doubts I might be under, and but yet wavering;
supposing those sentiments to be but lately embraced by me,
and I not yet settled in them;
though I do not think any of them knew what the true Quakers or their principles were.

The clergy generally shunned me,
and I quickly observed a particular enmity in them against me;
though I had no more aversion to them as men than to others.
But some of these others, my well-wishers above said, supposing me melancholy,
because reduced from my former airs and cheerfulness to silence and gravity,
got together in a tavern, and my father with them, intending to have me among them,
to drink a hearty glass; and try in their way,
whether they could raise my spirits into a more sociable temper,
and bring me off from such thoughts.

While they were contriving this scheme, I was retired alone into my chamber,
and favored with a sense of the good and soul-nourishing presence of the Lord;
but after some time, a concern came upon me,
which gave me to expect something was in agitation concerning me;
and soon after an attorney at law, of my acquaintance, came from the company to me,
and mentioned certain gentlemen who desired to see me at the tavern.

I was not hasty to go, looking for the countenance of the Lord therein,
neither did I refuse;
but my father and some others being impatient to have me among them, came likewise to me.
I arose from my seat when they came in, but did remove my hat to them as they did to me;
upon which my father fell a weeping, and said I did not use to behave so to him.
I entreated him not to resent it as a fault;
for though I now thought fit to decline that ceremony,
it was not in disobedience or disrespect to him or them,
for I honored him as much as ever, and desired he would please to think so,
notwithstanding the exterior alteration.

Most of the rest kept up another air, hoping to bring me into the same at the tavern;
but I, through grace, saw their intents, and was aware;
and I had now freedom in my mind to go among them.
When we came there, the company all arose from their seats, and seeming generally glad,
put on airs of pleasantness.
In seating themselves again they placed me so that I was in the midst of them,
and then they put the glass round; and to relish it the more,
they began a health to king William.
But the secret presence of the Lord being with me, though hid from them,
it affected them all in a way they did not expect; for scarcely had two of them drank,
till their countenances changed, and all were silenced.
The glass, nevertheless, went forward, till it came to me, and then I told them,
I wished both the king and them well, and if I could drink to the health of any,
I should more especially to the king`'s, but should drink no health any more,
and so refused it.
The glass never went round; for several of them fell to weeping, and were much broken,
and all of them were silenced for a time.
When this was over, some of them said they believed I intended well in what I did,
and that every man must be left to proceed in the way
which he thinks right in the sight of God;
and so we parted in solid friendship.
It was the secret grace of God which wrought this; and to him, the Lord alone,
did I impute it.
The company dispersing,
I returned to my chamber in divine peace and true tranquillity of mind;
with which I was favored for many days.

I had not, all this while, conversed with any Friend about their principles,
or read any of their books; nor did any of them come near me for some time;
for my father would not then allow them to come to his house;
yet some of them not long after sent me three small books; which I took kindly,
as well intended.
But I was favored of the Lord with something to give me
understanding and support in time of need,
more excellent than books; for that book, which had been sealed as with seven seals,
was now, in measure, opened by the powerful voice of the Lion of the royal tribe,
the Holy Lamb of God; even the book of the eternal law of God;
the law of the Spirit of life from the Father, by Christ the Son,
the Redeemer of the world, and my delight was to read day and night therein.
By this I profited more, in a short time,
in the knowledge of God and the things of his holy kingdom,
than if I could have read and understood all the written and printed books in the world.
I therefore declined reading these till a more proper season;
and then I looked into one of the aforesaid books, a small tract, concerning prayer:
for it must be allowed, that the reading of good books, especially the holy Scriptures,
the chief of all, and upon which the truth of the rest depends,
is highly profitable and commendable.

Sometime after this Dr. Gilpin, before mentioned, sent his son, a counsellor,
under whom I had been initiated into the study of the law,
and who was one of those at the tavern aforesaid,
and still retained a great affection for me, to invite me to his house at Scaleby castle,
and desired to see some of the Quakers`' books,
supposing I had been imposed upon by reading them; and I sent him, as I remember,
all that I had.

Soon after I had parted with these books, I observed a cloud came over my mind,
and an unusual concern; and therein the two sacraments, commonly so termed,
came afresh into my remembrance, and various Scriptures and arguments, pro and con;
and then I was apprehensive the doctor was preparing
something of that sort to discourse me upon.
I began to search out some Scriptures in defense of my own sentiments on those subjects;
but as I proceeded a little in that work, I became more uneasy and clouded;
upon which I laid aside the Scriptures and sat still,
looking towards the Lord for counsel.
I considered the doctor as a man of great learning, religious in his way,
an ancient preacher and writer too, famous in Oliver`'s time,
and a throne among his brethren;
and that he might advance such subtleties as I could not readily confute,
nor would concede to, as knowing them erroneous,
though I might not be suddenly furnished with arguments to demonstrate their fallacy;
and so might receive hurt.
Then it was clear in my understanding, that as he was in his own will and strength,
though with a good intent, searching the letter,
and depending upon that and his own wisdom, acquirements, and subtly,
leaning to his own spirit and understanding, I must decline that way,
and trust in the Spirit of Christ, the divine Author of the holy Scriptures.
This caution was presented in the life and virtue of truth,
and I rested satisfied therein, and searched no further on that occasion.
When I went to his house, he entered into a discourse on those subjects;
and had such passages of Scripture folded down as he purposed to use: when I observed it,
I was confirmed that my sight of him, in my own chamber at Carlisle, and of his work,
some days before, was right; and my mind was strengthened thereby.
But, before he began to move upon the subject,
he dismissed every other person out of the room; so that himself and I remained alone.

The first thing he said, was in a calm manner,
to admonish me to be very cautious how I espoused the errors of the Quakers;
for he had heard of late, and with concern, that I had been among them,
or seemed to incline that wav.
I answered, that I had not been much among them;
nor seen any of their books but those I had sent him;
and knew not of any errors they held.
"`Yes,`" said he, "`they deny the ordinances of Christ, the two sacraments,
baptism and the Lord`'s supper;`" and then opened
his book at one of his down-folded leaves,
where he read thus:

"`Unto the church of God which is at Corinth,
to them that are sanctified in Christ Jesus, called to be saints;`" 1 Cor. 1:2. And,
at another folded down part, he read thus:
"`For I have received of the Lord that which also I delivered unto you,
that the Lord Jesus, the same night in which he was betrayed, took bread:
and when he had given thanks, he broke it, and said.
Take, eat; this is my body, which is broken for you: this do in remembrance of me.
After the same manner also he took the cup, when he had supped, saying.
This cup is the New Testament in my blood; this do you, as often as you drink it,
in remembrance of me: for as often as you eat this bread, and drink this cup,
you do show the Lord`'s death till he come.`"

Upon these Scriptures he raised this argument.
That though the Corinthians, at that time, were sanctified in Christ,
and called to be saints, yet they still needed this ordinance,
and were to continue in it, according to the apostle`'s doctrine,
till the coming of Christ, at the end of the world:
and he did not think the Quakers more holy or perfect Christians,
than the Corinthians at that time; and consequently,
that no state in this life can render that ordinance needless to them, or overgrow it.

To this I replied.
That though some of those Corinthians had obeyed the call of God,
and were at that time sanctified by faith in Christ;
yet others of them had not obeyed the call,
but were remaining in gross sins and pollutions.
But as they had been heathens, and convinced by the ministry of that apostle,
as appears by the beginning of the second and fifteenth chapters of that epistle,
he had first of all preached to them Christ`'s coming in the flesh among the Jews;
his life, miracles, doctrine, death for our sins, and resurrection from the dead,
as saving truths; but does not so much as mention this supposed ordinance among them.

But, considering their weak and carnal state,
and incapacity then to reach the knowledge of divine mysteries, the apostle had,
in their initiation into the Christian religion,
related to them the sayings of Christ on that subject; and they had been in the practice,
or rather abuse of it, till the time of the writing of that epistle.
Yet, if the words of that epistle in that place, be carefully and impartially observed,
without prepossession or prejudice, and compared with other Scriptures,
it will appear that there is not any positive command for it at all,
much less is it made a standing ordinance;
but left to the option and discretion of his disciples;
to whom it was first mentioned how often they should do it, and consequently also,
how long they should continue it; as appears by the same text now adduced, namely:
"`This do, as often as you do it, in remembrance of me.`"

But to set this matter in a clearer light, it is well known,
that at the time of the redemption of the Jews from their Egyptian slavery, the passover,
with the paschal Lamb, was instituted as a standing ordinance in commemoration of it,
until Christ the Lamb of God, and antitype of that figure, should come.
But as Israel, offending the Lord,
was afterwards sent into captivity under the Babylonians, they could not in that state,
and under that government, celebrate it in form;
and therefore they invented another way to keep that great deliverance in memory,
which was this:

The father or chief of the family, at the proper time of the paschal supper,
took bread and blessed it, saying, "`Blessed are you, O Lord our God,
who gives us the fruit of the earth,`" then dividing it among the company;
in like manner also he took the cup, and blessing it, said, "`Blessed are you, O Lord,
who gives us the fruit of the vine.`"
This they did in a solemn manner, remembering their Egyptian slavery and deliverance,
lamenting their present state, acknowledging their sins,
and the justice of God in their punishment, and hopes of his mercy,
from his former kind dealings and gracious promises.

The Jews being thus initiated into this practice,
upon so solemn an occasion as the Lord`'s being pleased
to remember them with redemption a second time,
the succeeding generations continued it, as incident to the passover,
until the Lord Christ, the antitype, as well of the paschal Lamb,
as of the bread and wine, did come; who, when he appeared,
was declared by John the Baptist,
to be "`the Lamb of God which takes away the sin of the world;`" and
he declared himself to be "`the bread of life,
the living bread which came down from heaven:`" proclaiming also,
and that very emphatically, that his "`flesh is meat indeed,
and his blood is drink indeed;`" that "`except they ate his flesh, and drank his blood,
they had no life in them.`"
And all this was meant of the Spirit of Christ, and not of his flesh;
"`it is the Spirit that quickens, the flesh profits nothing.`"

The time drawing near when the Lamb of God was to be slain, and offered as a sacrifice,
declaring the mercy of God the Father, who sent him in love to the whole world,
he then said to his disciples,
"`With desire I have desired to eat this passover with you before I suffer.`"
And at the time of it, as father and chief of his flock and family,
he celebrated the passover in form, with this difference only, that whereas the Jews,
until that time, in the celebration of it,
had looked back to the type and the outward deliverance from Egypt,
the Lord now directs them to himself, as the antitype of all figures; and tells them,
he would not any more eat thereof,
(the passover) until it should be fulfilled in the kingdom of God;
nor drink of the fruit of the vine,
until that day "`when he should drink it new with them in his Father`'s kingdom.`"

Which eating and drinking in the kingdom of God,
cannot relate to material bread and wine;
which can only be exhibited as symbols of the outward body of Christ,
and the blood of that holy body; which to be eaten and drank in a natural sense,
profits nothing: but to the all-quickening virtue and power of his Holy Spirit;
which is all in all, and the true feeding to the commonwealth of the whole Israel of God.
Therefore this passover, or any part or relative to it, whether bread, wine,
or any other matter in it,
could be of no further use or obligation to the disciples of Christ,
than till they should experience in themselves his
divine and spiritual appearance and coming in them;
and Him to be the same to their souls or minds,
which natural food and drink is to the body`'s support, strength,
nourishment and means of duration.
This coming of Christ, as such,
can mean no other than his being made manifest in a spiritual administration: for,
as he is that eternal Spirit of Truth and Word, wisdom and power of God,
it is not strictly proper to say of him, in that sense,
that he shall come or go any where, but to be made manifest; for, as such, he ever was,
is, and will be, omnipresent, and never absent from any place or time.

His coming then must intend his powerful manifestation where he already is,
and not a loco-motive coming from where he is,
to any other place where he was not before:
"`For the heaven of heavens cannot contain him.`" 2 Chron. 2:6.

Seeing then this was only the passover,
and the terms of the application of it to himself not
institutive of any new command or ordinance,
but a liberty to do or not to do it, at discretion, "`this do you,
as oft as you drink it,
in remembrance of me,`" laid no obligation upon them to do it any more at all;
it being ended by the manifestation of its antitype; and in the nature of the thing,
could be of no further obligation or reasonable use,
when Christ himself was witnessed in them, to be that eternal, never-failing,
divine substance.

But the apostle Paul, whose concern for the Jews,
and zeal for the conversion of the Gentiles, to whom in an especial manner he was sent,
engaged him to "`become all things to all men,
that by all means he might gain some,`" recommended to
the Corinthians the practice of the passover,
with the new application of it to Christ,
at the time of their first believing in him by that apostle`'s ministry;
that being yet carnally minded, they might have an outward communion,
till the true communion should be made known; which their state, at that time,
could not bear: as, in point of prudence only, he practiced some other legal rites,
at some times; which, in his doctrine, he condemned at other times,
where the state of the people was able to bear it.

It is much more likely, considering the nature and end of the gospel,
and its excellency above the law, and all legal and typical rites,
as substances excel shadows, that the apostle,
observing how much some of the Corinthians had abused the passover in practice,
and their very carnal state under it, was rather, by that epistle,
endeavoring to supersede it, and bring them off to the living substance;
where he says to such among them as were already sanctified,
and to whom he inscribed his epistle,
"`I speak as to wise men, judge for yourselves what I say:
the cup of blessing which we bless, is it not the communion of the blood of Christ?
The bread which we break, is it not the communion of the body of Christ?
For we, being many, are one bread and one body;
for we are all partakers of that one bread.`"

It is plain therefore, that the communion of the sanctified and wise in Corinth,
stood not in the bread which perishes, nor in the wine of the grape,
which some of the Corinthians were carnally abusing,
but in the quickening Spirit and power of Christ, the true, living, life-giving,
and life-preserving bread; which daily comes from heaven,
into all the sanctified and saved of the Lord.

This is that Spirit that quickens and preserves to life eternal;
the flesh profits nothing: and since it is so,
much less does any symbol of the flesh profit; but the divine substance only.
This is that substance of which the apostle draws the comparison; "`we, being many,
are one bread "`For, as wheat consists of many particular grains,
each containing a distinct principle of life after its kind, and all of the same nature;
which, being broken and rightly prepared and ordered by the good husbandman,
become one bread: even so is the church, of Christ.
Every member, in his natural state, being alienated from the life of God,
through the ignorance and darkness that was in him, and separated also one from another,
as without a proper medium and condition of union;
but being ordered and prepared by the Father of mercies, through Christ his eternal Word,
they become one body, and one spirit, the church; which is his body;
the fulness of him who fills all in all.

The substance of this was what I observed to the doctor,
though I have in this place expatiated somewhat further upon the subject,
and generally applied the Scriptures; to which he made little other reply,
than by telling me in a very calm and familiar manner,
that as he had always believed it to be an ordinance of Christ,
he had solemnly used it as such, and found comfort in it.

To which I returned.
That I did not doubt but that he might have some satisfaction in it,
since he believed it a remaining ordinance, and did it under that apprehension.
Whosoever in his heart believes anything to be a standing duty in the church of Christ,
which ever had any countenance in it by practice, and performs it faithfully,
according to his belief and understanding, may find a satisfaction in it.
But since God, in mercy, is pleased to afford the living substance,
without the use of those means which are supposed to lead to an end already attained,
they can be no more a duty to such; and that is the real case among the true Quakers,
who love and fear the Lord sincerely.

As to the other point, namely: baptism, he said but little about it;
for he knew very well, that in strictness,
they were not so much as in the form of water baptism.
And I only asked him this question.
Whether he did believe it necessary to salvation?
He answered,
That he did not think it absolutely necessary.
Then, said I, we shall not need to say any more about it; and so the whole matter ended,
as to these points.

Then he said something concerning the books I had sent him, speaking slightly of them;
but thought that about prayer, written, I think, by George Keith, the best: and said,
that seeing the Quakers pretended, that they did not know before they went to meetings,
whether they should preach or pray, or what way in either,
and yet travelled in strange places, how could they speak to the states of the people,
or be joined with in prayer?

To this I answered: That such as went to a meeting empty of all things,
and waited upon God, were filled with his Holy Spirit, who knows all states,
at all times and places: and if the preacher attend to him as he ought,
and delivers those matters opened to him at the time, the Lord both gives the word,
and makes the application to every state, in every particular person;
which no preacher or instrument, of himself, is able to do.

And as to joining in prayer, all right prayer is by the aid of the Spirit of Christ,
the Mediator between God and man; which, in that respect,
is called the spirit of prayer and of supplications; and as such,
is promised of the Father to the church, and received by her.
Her unity in prayer stands not so much in the form of words, though sound and pertinent,
as in the nature, virtue, and influence of the Holy Spirit of Christ, her holy Head,
Life, Law-giver, and Comforter.

The doctor did not oppose this;
but only said I had given him better satisfaction in that point,
than he had found in the book;
and afterwards he was much more free and familiar with me than before,
or than I expected: and so we parted in friendship,
and I returned in peace and gladness.

From henceforth I was easy as to everything any of that sort could say.
And many disputes I have had with many of them since, in other parts of the world;
but never began any controversy, being always on the defensive side;
and rarely entered upon any point in question, with any sect,
till I knew the divine truth over all in my own mind, and my will subjected by it.
And my next care usually was, not to provoke my opponent; for, by keeping him calm,
I had his own understanding, and the measure of grace in him, for truth and my point,
against the error he contended for; and my chief aim generally has been,
to gain upon people`'s understandings for their own good.
But when a man is put into a passion, he may be confounded, but not convinced.
For passion is as scorching fire without light; suspends the understanding,
and obstructs the way to it, so that it cannot be gained upon or informed:
which ought to be the true aim, in all conferences and reasoning in matters of religion;
else all will end in vain and unprofitable jangling,
contrary to the nature of the thing they reason about, and displease the Holy One.
In two or three times, at most, in the course of my life, in some low cases,
and in too hasty engagements in my own strength, my mind has been ruffled:
and though I have gained the point, by force of argument,
from the principle of reason only, and not from the principle of divine Truth;
yet I have not had that peace and satisfaction of mind
which is to be found in the virtue of truth alone.
And this has also taught me to be totally silent,
and sometimes even insulted by ignorants, as if I had nothing to say;
till the power and virtue of truth has arisen in my mind, and then it has never failed,
by its own light and evidence, to support its own cause, and justify me.

After this I had divine peace and consolation in my mind for some time,
and was mercifully favored with the living bread from above daily.
I went constantly to the meetings of Friends, where, in a state of silence,
my heart was frequently tendered and broken, by the divine influence of the truth,
to my unspeakable satisfaction: a holy pleasure and enjoyment, which the world,
or anything therein, can never afford.

Our meetings in the north in those days were frequently broken and melted in silence,
as well as under a powerful, living ministry, by the Word;
which gave me occasion sometimes to remember another saying in a piece which I wrote;
"`He gave me joy which no tongue can express, and peace which passes understanding.`"
In the mean time my father began a little to relent,
and admit some Friends to come to my chamber to see me; and he was brought by degrees,
into a pretty low state of mind.
One day, as I was sitting by him, he read in a book entitled, Clerk`'s Lives, etc.,
as I remember, when I observed his tears drop upon the book;
but he did not know that I perceived it.
After he had wiped his face, he turned towards me and said,
"`I see there have been in former times, as great fools as you,
to leave their friends and preferments in the world for their opinions in religion.`"

But he did not remain long in this condition;
for the spirit of the world began to work another way.
Some of his acquaintance discoursing with him concerning me,
as I was for a time frequently the subject of common conversation, one day told him,
"`We know your son very well; though young, he is no fool.
You know the Quakers are an opulent people,
and their principles lead them to refuse the payment of tithes to the clergy; which,
together with other oppositions they meet with from one or other,
occasions many law-suits and much business: and as they favor one another in all things,
particularly in trade and the like,
you will see he will have as much business soon as any man in England;
and will be well paid without question.`"

This temptation being skillfully adapted, took immediately with him,
and entered very deep, the ill effects whereof quickly appeared.
He soon got from under that humble state of mind
and tenderness he had in some degree experienced;
and though his countenance seemed very open and cheerful towards me,
yet it was from that wrong ground and worldly view;
which greatly loaded and oppressed my mind.
I clearly perceived the practice of the law,
and to be frequently in the suits and contests of the world,
would be inconsistent with divine peace in my own mind, expose me to many temptations,
and confine me so that I could not follow the Lord in
that way wherein I understood he was leading me,
and purposed to bring me forward; that is, not only in sanctification and justification,
for my own salvation,
but also in a public ministry of that holy and powerful Word of life, by which the Lord,
of his own free will and grace, had called me; and to that end, I knew,
was working in me qualifications suiting his own purpose thereby.
Therefore my secret concern was, how to get rid of that great and dangerous obstruction;
well knowing it would very much oppose my father`'s views, heightened as aforesaid,
and I was reluctant to offend him; but had no concern, prospect, or doubt then,
as to a way of living in the world.
On the other hand, to offend the Lord by neglect or disobedience,
was justly to forfeit his mercy and favor, and cancel the seal of the covenant of life;
depending, on my part, upon perseverance in moral righteousness,
and a faithful future obedience to his holy calling.
Where the word of God is given, and become a law of life and an immediate director,
disobedience is of a higher nature and more immediately attended with
the sensible and dreadful condemnation of this immortal law,
thus ministered, than for the neglect of any moral command,
mediately administered to mankind, while yet in a natural and rational state only.

Duty to the Almighty, and the will and views of my natural parent, becoming opposite,
I remained not long in suspense what to do.
For as, through grace, I had been enabled to take up the cross of Christ,
in confessing his holy Name, in the dispensation of God to his people at that time; so,
by the same grace, I was likewise enabled to undergo the displeasure of my father,
to close my eyes from all worldly views,
and to stop my ears forever from hearkening to any preferments there.
Being furnished with a full resolution in my mind to decline the practice of the law,
though the only thing designed as a means of life,
the next persons who came to employ me in business of that kind,
I refused in my father`'s presence; and told them in his hearing,
that I should not undertake business of that kind any more.

Upon this the load went off my mind;
but from that time my father`'s countenance was changed towards me,
and his behavior quite another thing; often asking me with a supercilious brow,
how I expected to live in the world?
as if he feared I should become a dead charge upon him.

This temptation being overcome, another quickly followed:
the world had formed a false notion in those days, that our ministers,
like their priests, were well paid by the Society for preaching,
and generally grew rich by that means;
they not knowing of any reasonable motive to such an undertaking, but lucre only.
Some having told my father, that such and such ministering Friends whom he knew,
went often abroad preaching, and as often brought home good sums of money;
and that his son, being ingenious, would soon learn to preach among them, get money,
and become rich too; this seemed to take some hold,
and he would now and then pass a joke upon me about it;
but I being silent for some years after,
it afforded him no great hopes of my living by it.
This I think proper to remember here,
that though I had no more dislike to priests than to others, as men, yet,
when any of them and I happened to come into the same company or place,
they usually fell into some visible disorder and uneasiness,
though I said nothing to occasion it; which I took, therefore,
to arise from a prepossession and general prejudice and enmity against Friends,
supposing them enemies to their persons, as to their errors.
And particularly one of them coming into a place where I was, all of a sudden,
and in a confused manner, without any occasion given to lead to it, cried out,
"`You deny the resurrection.`"
I replied, that he had not heard me say anything on that subject.
Then said he, "`The people you have joined yourself to deny it.`"
I replied, I did not understand they denied the resurrection; and that Christ,
to prove the resurrection, adduced that Scripture, where it is written,
"`But as touching the resurrection of the dead,
have you not read that which was spoken unto you by God, saying, I am the God of Abraham,
and the God of Isaac, and the God of Jacob.
God is not the God of the dead, but of the living.`"
If then Abraham, Isaac, and Jacob, had attained the resurrection from the dead,
in Christ`'s sense of the resurrection,
and yet the bodies of those saints then remained in the earth,
something else must be meant by the resurrection of the dead than earthly bodies.

Then said the priest, "`I believe that Abraham, etc., did arise,
not only to a state of righteousness in this life,
but also to a state of glory in heaven after his death.`"
Then said I, "`Since he attained a first and second resurrection,
he completed that state, without the resurrection of this earthly body;
for of a third resurrection we read not, and of a second, by implication only.`"
And so the matter ended:
and from that time we became acquainted and
intimate so long as I remained in the country.

Another time there came a priest into the company where I was, and I being silent,
and the rest cheerful in their way, he being a wanton, airy man, and a little in drink,
observing me, cried out in a scoffing manner, "`What have we got here,
one of the holy brethren?`"
I returned upon him, "`What! are you a teacher of the people, and scoff at holiness?
What can you teach,
since you are void of a qualification indispensably necessary to that work?`"
Upon which he became so uneasy and downcast, that he could no longer stay in the room,
but went off troubled.
And that night, being from home, I lodged with another priest at his house,
with whom I was acquainted, a sober, religious man; where I was kindly entertained,
and had no occasion of offense, either by himself or any of his family.

Again, having been concerned in writing a settlement for a gentleman,
upon the marriage of his daughter, and at his house in the country on that occasion;
after the ceremony was over, and dinner upon the table,
the priest said what they called the grace; wherein he gave thanks for their creation,
redemption, sanctification, etc., to which I paid no respect,
keeping on my hat all the time, because it was a dead form;
and that neither the priest himself,
nor any of his company seemed to have any real sense of what he said.

As soon as dinner was over, a fiddler began to play; and up started the priest,
and taking one of the young women by the hand, fell to dancing very merrily.
I being in the room, and under heaviness,
some others of the company could not take all the
liberty the occasion called for in their way;
and expecting I would not stay long, forbore.
Nor could the priest make much of his dance;
for the load upon my mind was to be left among them before I departed,
and I only waited a proper occasion, which was soon offered;
for the priest`'s dance going on heavily, he left it, and came to me,
where I was sitting quietly, and would have had me dance with one of the young women.
Then I took the opportunity to tell him, that I had observed his grace,
and what he had said before the Almighty and the company so very lately,
giving thanks for his creation, redemption, sanctification, etc.,
and so very quickly after to fall into such behavior as
did not consist with sanctification and redemption,
denoted his very great insensibility of the import of his own words.
Then he clapped himself down on a seat,
and began to defend the use and innocence of music,
which at that time was not the most offensive part, and said that king David used music,
yet was a prophet greatly beloved of God, and wrote the Psalms,
owned by Christ as of divine authority.

I replied, that David employed his music in holy hymns and spiritual songs to the Lord,
according to the dispensation then in being; but that afterward, some airy persons,
such as the priest himself,
had invented unto themselves instruments of music like unto David`'s,
and used them in their profane revellings, as he and his company were then doing;
and therefore a prophet of God, by divine authority and direction, cried out,
"`Woe to them that chant to the sound of the violin,
and invent to themselves instruments of music
like David;`" and you being in that practice,
the woe is upon you also.
Upon this I was very easy, and left him sitting silent, and the company in some surprise;
and wishing them all well, I departed in peace and great tranquillity of mind.

My eldest brother being priest of the parish, and likewise dean of Connor,
afterward of Limerick, in Ireland, had one of the Scots Episcopal priests for his curate,
or journeyman,
who had been turned out at the establishment of
Presbytery as the national way in Scotland.
This priest being poor, my father took him into his house for his better accommodation;
which proved some exercise to me,
we being so very different in our sentiments in some things relating to religion.
One day, there being a goose on the table at dinner,
he intending to disappoint me of a part,
whispered to me so loud as that all about the table heard him,
"`This is a tithe goose;`" and then sneered.
I replied, "`Let him look to the evil of that to whom it is tithe;
but to me it is no tithe, but a goose only; and with my father`'s leave,
I will take a share.`"
After this we had much dispute about the maintenance of the ministers of Christ.
I alleged, that when Christ sent out his disciples to preach to the people, he said,
"`Freely you have received, freely give;`" and did not allow them either gold, silver,
or brass in their purses, nor scrip, nor two coals, nor shoes, nor staves,
but to depend on Divine Providence only for their subsistence;
"`eating such things as should be set before them;
for the workman is worthy of his meat.`"

To this he answered, that Christ and his apostles received money for preaching,
otherwise where did they get the money they had in the bag; for they were poor men,
and had nothing to give, or any other way to procure money.
Upon this I asked him from where that money came that
Christ sent Peter to take out of the mouth of the fish?
Had he not command over all things to have what he pleased?
But you priests, to justify yourselves in your anti-christian practices,
dare accuse Christ himself, and his apostles, of your own crimes,
he and they preached not for hire, nor for filthy lucre and maintenance,
but for the help and salvation of men.
As there is nothing needful to the laborer in that work,
but the present subsistence of food and raiment, with that they were to be content:
and as to what money they had,
it arose from the superabounding love of those who heard him and them, and believed;
which they did not hoard up, and detain to their own use only; but also gave to the poor,
as they had occasion: so far were they from sitting down in corners,
and forcing a maintenance, even to luxury, from those who did not receive them,
as you priests do at this day.
By which it appears you are none of his, but rather like Judas the traitor,
who carried the bag, loved money better than him, and was a thief.
At this he became a little ashamed, and in an abject manner said,
"`What I have for my preaching is but a small matter:`" as if
the diminutive pay and poverty should excuse the error;
and so it ended.

At another time my father had a mind to discourse me on that subject;
and after he had moved it,
I desired leave to ask him a question before I entered the dispute with him.
He granted it; and then I asked him, if it were not for his reputation among men,
and the law of the land, would he himself pay any tithe?
Upon this he was silent a little, and then replied with an oath,
that if it were not for the laws`" he would pay no more tithe than myself.
Then said I, "`There is no need of any further dispute:`" and it ended thus;
for he never offered any argument about it.

My delight was continually in the truth, and I desired no company but of Friends,
and frequented meetings on all occasions;
where my heart was frequently tendered by the truth,
and it often reached and affected others by me, and sometimes very much:
so that I became very dear to Friends, and they to me.
And as that tenderness was an involuntary ministry,
being an operation of the Spirit without words, I found for some time,
great satisfaction and safety in it.

Desiring to see Friends in some other places, I went a short journey with Andrew Taylor,
a powerful and able minister in his day, of an affable and cheerful temper,
and one of my particular friends.
On the 20th day of the twelfth month, 1691, we went from Heatherside, in Kirklinton,
in Cumberland, and that night lodged two miles beyond Alston;
and from there next day to Welgill; on the 22nd to Thomas Williamson`'s;
on the 23rd to Walkmill; on the 24th to Steel, and on the 25th to Benfieldside;
having meetings at several of these places.

From there we went, on the 27th, to Newcastle, and lodged at Jeremiah Hunter`'s,
being at their meeting next day; and on the 29th we went to Caleb Tenent`'s,
at Shields and had a meeting there.
On the 1st day of the first month, a meeting being appointed at Sunderland,
we intended to cross the river Tyne at Shields, in order to be there;
but Caleb Tenent and we entering the ferry boat with our horses,
and the wind being very high, they were frightened with the fluttering of the sails,
at our putting off from the key; so that Caleb`'s mare, being strong and sprightly,
jumped overboard; and carried him along with her as he strove to stop her by the bridle,
and they both went under the water, for it was deep;
but as good Providence would have it, the mare came up with her head towards the shore,
and near it, and he came up behind her at so little distance,
and with such presence of mind, that he laid hold on her tail,
and got on shore without any other hurt than the surprise and wetting his clothes.

The meeting was appointed at Sunderland, to begin about the middle of the day,
and we being obliged, by reason of the high wind, to go round by Newcastle,
it was put off till the evening;
which proved a very comfortable time of the enjoyment of the good presence of the Lord;
with which my heart being plentifully furnished,
it greatly tendered me and bathed me in a flood of tears, from divine melting love,
and had the like effect over the meeting; and this happened in time of silence.
After this Robert Wardell, a ministering Friend, at whose house we lodged,
spoke some sentences;
by which I perceived he thought I should have uttered
some words by way of public ministry at that time.
But I did not apprehend my time was then come for that service;
and it had the same effect, and peradventure, more than if I had uttered words:
for it was a ministration of the Word, by a more immediate operation,
and a great mystery.

After the meeting many Friends came to me,
and expressed so much love and respect as gave me
occasion to consider what could be the reason of it;
for they were all strangers to me, and I to them;
and being but a child in the knowledge of the invisible
operation of the Word of truth and its effects by instruments,
in a way of silence and sympathy,
I had looked at its effects only in myself for my own strength and consolation;
and yet could not but observe, that when truth broke in upon me in an eminent manner,
with which, in other places, I had been often favored before,
it affected the living part of the meeting the same way, at the same time:
and it is clear to my understanding, by experience,
that there is a communication of divine love through the one Spirit,
and that unspeakable, among the sanctified in Christ, at this day,
as well as in time past; and that in a state of holy silence,
as the members of Christ sit together in their heavenly places in him.

The next day we were at a meeting at Shotton, from which we went to Anthony Robinson`'s,
at Hawthorn, and next day had a meeting at Durham; from there to Auckland,
and so on to Robert Corney`'s, at Stockton; from there to Yarm, and back to Stockton;
in all which places we had meetings: from there to Darlington,
and on the 10th of same month, to Raby; from there to Cutherston and Bowes;
at all which places we also had meetings, and the Lord was with us.
And yet, for some days after that meeting at Sunderland, my mind was very low,
and not sensible of the same degree of the divine presence as some time before;
and a question possessed my mind,
whether I ought not to have uttered some words in that meeting.
But by degrees I attained my former tranquillity.

On the 12th went to the Height of Winder by Sedberg; then to Side; next day to Dent;
next day to Dent meeting at Anthony Mason`'s. On the 16th we went to John Dickinson`'s,
at Beckhouses, and to the meeting at Grayrig; next day to Girsgarth, at Thomas Wilson`'s;
and so to Crook, at John Thompson`'s; and on the 18th to Thomas Lower`'s, at Marshgrange;
and the next day to Broughton Tower;
and the next day to Swarthmore and on the 23nd to Hawkside meeting;
having likewise had several other meetings in the way:
and on the 23rd we went to John Banks`' at Rogersgill;
and the next day to the meeting at Pardshaw.
After this we went to the house of Margaret Fawcet, an ancient widow,
having an estate of six or seven pounds per annum,
out of which she entertained all traveling Friends coming that way,
besides her own family, and had always plenty; and so desirous was she to entertain all,
that she was commonly called the covetous widow of Cumberland;
and was a woman truly honorable in the truth during her time.

On the 25th we went to Eaglesfield; and then to Jonathan Bell`'s at Hundwath-hill;
and so to Cockermouth and Broughton; and from there to Alanby;
and on the 27th to Holm-Cultram; and so to Longnewton and Bowstcad;
having meetings all along.
But I had no other public ministry in this journey,
than being frequently much tendered in the several meetings, to my great satisfaction,
and the comfort of many who wished me well for the Truth`'s sake,
and desired my prosperity therein.
This journey being finished, I went home to my father`'s house in the evening;
and having taken much cold, so that I was hoarse.
I spoke with difficulty when I went into the house; yet,
through a very sensible operation of the divine truth, and the healing virtue thereof,
under which I sat in silence for about half an hour, I was perfectly healed;
by which I was forever confirmed in the belief of the
miracles of Christ recorded in holy Scripture.
