== Chapter V

One first-day about this time, Thomas Kent,
preacher to the separate meeting at Harp Lane, London, and Arthur Ismay,
another separate preacher out of the country, came to our meeting in Whitehart Court,
in Grace-church Street, and many of the Separates of Harp Lane meeting came with them,
with intent, as appeared by their management,
to impose themselves and their preachment upon our meeting, which was very large.
Ismay being of a large body, and a bold man, with n loud strong voice, began early,
before the meeting was half gathered; and went on with abundance of ranting matter,
such as he used to vent, and held it till near the time to break up the meeting.
Then Thomas Kent snatched an opportunity to pray;
in which he made many protestations to the Almighty of his innocence in things,
of which several persons there present knew him to be guilty.
His own disciples, and several other weak and inadvertent persons,
together with some strangers not of our communion,
moved their hats m posture of prayer at the time;
though Friends generally kept their hats on,
and some reproved Thomas Kent in the mean time, for his imposition on the meeting.
Being under a very great concern by reason of this attempt and usurpation,
as soon as the meeting was broken up over his head,
I called to the people to stay and hear me a few words; which generally they did:
and then I said,
"`That considering the disturbance and confusion which had then happened, where,
when one pretended to pray to the Almighty,
as if he were the mouth of the assembly in that exercise, some seemed to join with him,
some reproved and forbade him, and the greater part rejected him and his performance,
as not having any unity with him therein; which might perplex many,
and be offensive to several sober persons present,
who could not know the reason of such conduct;
I therefore put them in mind of the direction of our Lord Jesus Christ, where he says,
'`If you bring your gift to the altar,
and there remember that your brother has aught against you,
leave there your gift before the altar and go your way,
first be reconciled to your brother, and then come and offer your gift.`'

"`By this we may observe, that though the gift may in itself be proper to be offered,
yet there is a qualification necessary in him that offers, before he ought to offer;
and that is, reconciliation to a brother justly offended by him.
You are therefore to know,
that this person and his accomplices have given just cause of offense,
not only to one brother, but to the community,
by setting up and continuing a separate meeting,
in opposition and contempt of his brethren; and have thus imposed themselves,
and insulted this meeting, where they ought not to have come in this manner.
Since then he that offers an offering unto God, as he who prays does, or pretends to do,
is not acceptable until he be reconciled, even to a single brother, if justly offended,
such a one must needs also be unacceptable to the Almighty,
while he stands in opposition to the whole community and body of his brethren,
throughout this nation and elsewhere; contrary to the order of Christ,
in whose name alone he ought to pray.
And this is the reason of the behavior of them who have thus publicly denied him,
and testified against him and his performance, lest by joining with him, as now stated,
they should make themselves parties to his sin before the Most High.`"

This plunged them into a rage, and they began, many at the same time,
to bawl out aloud some pretenses to a justification of their conduct herein;
but the multitude immediately dispersed, and would not hear them,
and they were then like madmen.
I said no more to any of them,
but went immediately into the passage that leads out of the court,
in order to face them as they came out of the meeting-house;
where Thomas Kent coming towards me in a great rage,
said I had charged him with more than I could prove.
I looked upon him, and said, "`I both could and would prove all that,
and much more to his disadvantage, if, by contending,
he would make it needful:`" then he shrunk, and went off grumbling.

I went to Theodore Eccleslone`'s, where I was invited to dine,
and in great peace in my mind; but soon after that peace withdrew,
and a very great uneasiness appeared.
This remained but a very short time till my peace returned,
and in that my mind settled with great consolation.
I observed that the uneasiness and dissatisfaction was the state of those opposers;
and my peace confirmed me that I had done my duty;
and that it was my present reward for that work
the Lord had required and enabled me to perform,
for his glory, and the justification of his people.

This had such effect upon Thomas Kent, that he came the next day to the morning meeting,
and seeming in a very low and humble mind, desiring to be reconciled to Friends,
offered to bring back most of his said meeting.
But one of the Friends of the morning meeting asked him
if he expected to return as a preacher among us?
And he owning that he did, the same Friend then said,
that he could not be received as such,
till he had given ample satisfaction for his outgoings and what he had done,
in testimony of his sincere repentance: which he did not comply with at that time,
but never troubled our meetings any more, as I remember.

Continuing in London, my elder brother, who was dean of Limerick, in Ireland,
desired my company in a visit to Robert Constable,
a justice of peace in Goodman`'s-Fields, and our near relation;
and when we came to his house we met with his brother George, who was likewise a priest,
and with him another priest, a stranger to me, and some other company.
This strange priest not knowing the relation among us,
and looking upon me as a bird of a different feather,
began to peck at me by several sour hints, which showed his dislike of my company;
which for conversation`'s sake, I passed by.
But my forbearance and silence encouraging him to be a little bolder,
at length he moved a plain accusation, and said, "`You deny the ordinances of Christ,
water baptism and the Lord`'s supper.`"

I replied, "`You have not heard me say anything on these subjects;
how do you therefore know what I deny or affirm!`"
Then said he, "`I perceive you are one of a sect that does deny them.`"
"`What authority have you,`" said I, "`for water baptism?`"
He was ready with that much mistaken text, "`Go you therefore and teach all nations,
baptizing, etc.`"
"`This,`" said I, "`was a commandment given by Christ to his apostles;
but do you think this is a command to you, for you seem to be a teacher of the people;
have you any authority by this text?`"
Upon this he hesitated a little, and the justice began to smile: the pause being over,
the priest answered yes.
Then said I, "`How many nations have you travelled through in this work?
how many taught and baptized?`"
His countenance began a little to alter, and then he replied,
"`I have never been out of England.`"
My next question was,
"`In how many counties of England have you travelled in this service?`"
He answered, he had not travelled in any on that account.
Then said I, "`You wicked and unfaithful servant,
out of your own mouth shall you be judged: you have here affirmed before these witnesses,
that the Lord Jesus Christ has commanded and sent you to teach and baptize all nations,
and you are set down in a corner, and have not baptized anyone: for you must understand,
friend, that sprinkling an infant is no baptism, either in mode or subject.`"
Upon this the counsellor laughed outright, for so he was as well as a justice,
and the other priests smiled.
Then said the justice, "`Sir, this gentleman is my near relation, a cousin-german,
you will get nothing by meddling with him on these subjects.`"
So the matter dropped.

At this time Peter the Great, Czar of Muscovy, being in London, and Gilbert Molleson,
Robert Barclay`'s wife`'s brother,
having heard that a kinsman of his was in the Czar`'s service,
and being desirous to spread the knowledge of the truth,
requested me to go with him to the Czar`'s residence,
a large house at the bottom of York Buildings,
in order to present his kinsman with some of Robert Barclay`'s Apologies in Latin;
hoping by that means, they might fall under the Czar`'s notice,
and be subservient to the end proposed.
When we came to the place, Gilbert inquired after his cousin;
but could not hear anything of him in the lower apartments,
but was desired to stay till further inquiry was made in the house;
and a servant went up stairs to that end, and when returned, invited us up.
The head of the stair-case on the first floor
brought us to the entrance of a long passage,
and there stood a single man at a large window,
to whom we were directed for intelligence.
As we passed along, we observed two men walking in a room on the right-hand;
and supposing one of them to be the Czar,
of whom I had heard that he was not willing to be looked upon;
we went directly to the person standing at the window,
of whom Gilbert Molleson inquired after his kinsman, and he told us,
that such a person had been in the Czar`'s service, but was dead.

In the mean time came the Czar and the other to us;
the other I suppose was Prince Menzikoff, his general.
Our backs were towards them, and our hats on; and when they approached,
the person with whom we had conversed looked down upon
the floor with profound respect and silence;
but we stood in our first posture, with our faces towards the window,
as if we had not taken any notice of them.
The person we had conversed with was an Englishman, a Muscovy merchant,
known to the Czar in his own country, understood his language, and was his interpreter.
Then the Czar spoke something to him, which we did not understand.
Upon which he asked us,
"`Why do you not pay respect to great persons when you are in their presence?`"
I answered, "`We do when we are sensible of it, especially to kings and princes:
for though we have laid aside and decline all vain and empty shows of respect and duty,
and flattering titles,
whereby they are generally deceived by insincere and designing men,
who seem to admire them for their own ends;
yet we yield all due and sincere respect and duty to such,
and all in authority under them, by giving ready obedience to all their lawful commands.
But when any of them, either through tyranny or ignorance, or ill counsel,
command anything contrary to our duty to the Almighty, and his Son Christ our Lord,
then we offer our prayers and tears to God, and humble addresses to such rulers,
that their understandings may be opened, and their minds changed towards us.`"

The Czar gave no reply to this, but talked with his interpreter again, who then asked,
"`Of what use can you be in any kingdom or government,
seeing you will not bear arms and fight?`"

To this I replied, "`That many of us had borne arms in times past,
and been in many battles, and fought with courage and magnanimity, and thought it lawful,
and a duty then, in days of ignorance.
I myself have worn a sword and other arms, and knew how to use them.
But when it pleased God to reveal in our hearts the life and power of Jesus Christ,
his Son, our Lord, who is the Prince of righteousness and peace,
whose commandment is love, we were then reconciled unto God, one unto another,
to our enemies, and to all men.
He that commands that we should love our enemies,
has left us no right to fight and destroy, but to convert them.
And yet we are of use and helpful in any kingdom or government.
For the principle of our religion prohibits idleness, and excites to industry;
as it is written, '`They shall beat their swords into plough-shares,
and their spears into pruning-hooks:`' and we being husbandmen,
concerned in all manner of husbandry and improvements,
as likewise in manufactories and merchandizing,
with the blessing of heaven upon our labors, do not lack, but rather abound.
And though we are prohibited arms and fighting as inconsistent with the gospel of Christ,
yet we can and do, by his example,
readily and cheerfully pay to every government where we happen to be subjects,
such sums and assessments as are required of us
by the respective laws under which we live.
For when a general tax was laid by the Roman Emperor upon his extensive empire,
and the time of payment came, the Lord Jesus Christ, whose kingdom is not of this world,
demanded of Peter, '`Of whom do the kings of the earth take custom or tribute?
Of their own children, or of strangers?
Peter says unto him, Of strangers.
Jesus says unto him, Then are the children free.
Notwithstanding, lest we should offend them, go you to the sea and cast a hook,
and take up the fish that first comes up.
And when you have opened his mouth, you shall find a piece of money; that take,
and give unto them, (the tribute gatherers) for me and you.`'
Thus working a miracle to pay a lax, where yet it was not strictly due; we,
by so great an example, do freely pay our taxes.`"

Upon this the Czar took several turns in the gallery or passage,
and then came and looked steadfastly upon us, though we did not seem to mind him,
or know that it was he.
Then I said to the interpreter,
"`That we understood there was a person of great dignity and distinction in that place,
a stranger, inspecting into the state of affairs and things in general; and no doubt,
he might be also inquisitive into the state of religion;
and we being a people differing in some points from all others,
and so much misunderstood and misrepresented in our own country,
that even our neighbors themselves did not know us;
lest that great prince should be misinformed and
imposed upon concerning us and our religion,
we had brought him some books dedicated to the sovereign of our native country,
by which he might please to see a full account of our
principles.`"--We then produced two of the Apologies in Latin.

Then the Czar talked again with the interpreter, who asked us,
"`Were not these books written by a Jesuit?
It is said there are Jesuits among you.`"
To which Gilbert Molleson replied, "`That is a calumny,
and proves the necessity of our endeavors in that respect, at this time.
We have no Jesuits among us.
Our religion and theirs differ very widely.
This book was written by a near relation of mine, who was not a Jesuit,
but sincerely of those principles assorted and maintained in the book,
as our whole community is.`"
The Czar and interpreter talked together again;
after which the latter took some gold out of his pocket and offered us for the books.
But I told them, "`We did not lack anything for the books.
They were a present to that great prince and given freely; and all that we desired was,
that they might be acceptable,
and that in case any of our friends should come into his country,
and preach those principles contained in the books, if they should meet with opposition,
and be persecuted by any officers or persons in power under him, for the same,
he would please to afford them protection and relief.`"
Then they talked together again, and the interpreter kept the books;
and the Czar and Prince Menzikoff retired into the room from which they came.

They being gone, we asked the interpreter if that was the Czar?
He said he was.
Then we asked him if he had told the Czar the substance of what we had said?
And he said he had.
We desired that if he asked him any more questions about us and our religion,
not to mention to him any of those rude calumnies
thrown upon us by ignorant and malicious persons,
but the truth, to the best of his observation and information; and he promised he would.
He told us, that the Czar did not understand the Latin tongue;
but only his own language and High Dutch.
Gilbert Molleson gave one of the Apologies to the interpreter,
and so we departed in peace and satisfaction.

This was about the beginning of the week, and the next first-day the Czar, the prince,
and a great company of his attendants,
came in the morning to our meeting in Grace-church street,
and the same interpreter with him.
I happened to be there, and the first I knew was Menzikoff.
Robert Haddock had begun to preach a little before they came in,
upon the subject of Naaman, the captain general of the host of the Assyrians,
going to the prophet for cure of his leprosy; who,
directing him to dip himself seven times in the river Jordan, the general,
despising the means, as loo low a thing,
expecting some ceremony or action from the prophet, was about to return without a cure,
till, being persuaded by his own servant to make a trial of the means prescribed,
he found the end accomplished by happy experience.

From which Robert drew this observation,
as from a type of a more excellent and general nature and consequence, saying,
"`The nations of this world being defiled and distempered,
as with a leprosy of sin and uncleanness, no cure or help could be found,
until the Almighty, in his infinite goodness, sent his Son Jesus Christ into the world,
to die for man, as a propitiation for sin;
through whom also he has sent forth his divine light, spirit, and grace upon all mankind,
in order for the completing of that cure; which nothing less can do,
and to which all mankind are directed by the servants of Christ;
and as many as have believed and made trial of this excellent means,
have found the blessed effects thereof; they have been cured and cleansed.

"`Now,`" said he, "`if you were the greatest king, emperor, or potentate upon earth,
you are not too great to make use of the means offered
by the Almighty for your healing and restoration,
if ever you expect to enter his kingdom, into which no unclean thing can come.`"

The Czar and his interpreter were often whispering together in the time,
though Robert Haddock knew nothing of his being in the meeting;
and thus he stayed till observing the people crowd up before him to gaze,
which he could not endure, he retired on a sudden, with his company,
before the meeting was quite over:
for some people in the streets had seen him as he came, and had discovered who he was,
and crowded after him to see him more perfectly.

After this he went to Deptford, to improve himself in the art of ship-building,
and there wrought at it with his own hands.
And Gilbert Molleson and I acquainting some Friends how we happened to see him,
and had given him some books, and that he understood the High Dutch, William Penn,
George Whitehead, and some other Friends went to Deptford and waited on him privately,
and presented him with more of the same books in that language; which he accepted,
and afterwards was sometimes at our meeting there, behaving as a private person,
and very social; changing seats, standing or sitting as occasion might be,
to accommodate others as well as himself.

When this great prince had in a good degree furnished himself
with the useful knowledge in things necessary for civilizing
and improving the barbarous people of his kingdom,
he returned there, accomplished with experience in many particulars,
to the great advancement thereof in general.

During my continuance in London, I employed myself in conveyancing,
and having more business than I could manage alone,
I had several clerks or apprentices offered, both in London and from the north,
and considerable sums of money with them; but could not accept of any,
lest it should prove too great a confinement from my calling in the Truth.
For though I was willing to take pains for my necessary support,
and the charges of my travels, yet I suffered much in my mind, by reason of confinement,
since the calling of God cannot be rightly and fully
answered by anyone much entangled in other concerns,
though lawful and gainful, and to the view of reason, needful.
I stayed, attending the city meetings,
and sometimes visiting those of the neighborhood in the country, until the year 1698;
when, having a letter from William Penn, then at Bristol,
desiring me to meet him and John Everot at Holy Head, in Wales, at a day certain,
in order to go for Ireland, I set forward from London on the 28th of the second month,
and reaching Conway, I there met with my friends aforesaid, to our mutual satisfaction.
From there we went to Holy Head, in the Isle of Anglesea; and next day,
about two in the afternoon,
we set sail and arrived in Dublin Bay in about twenty-four hours,
for which we were thankful.

At the time of our landing there was a ship in the bay,
with a great many friars going for France,
being sent out of Ireland by virtue of a law lately made there.
John Everot having something to say in some meetings after we landed,
against several tenets and practices of the Papists, a report was raised,
that William Penn had preached among those monks and friars at our landing,
and had converted some of them; one of whom, being more zealous than the rest,
was now with William Penn, preaching mightily against the Papists, meaning John Everot.

On the 6th of the third month we went to Dublin, and on the 8th,
being the first of the week, was the half-year`'s meeting there;
where we were greatly comforted,
not only in the enjoyment of the blessed presence of the Lord,
but also in observing the unity, mildness,
and order which appeared among Friends in the management of the affairs of the church.

Great was the resort of people of all ranks, qualities, and professions, to our meetings,
chiefly on account of our friend William Penn;
who was ever furnished by the Truth with matter fully to answer their expectations.
Many of the clergy were there, and the people with one voice,
spoke well of what they heard.
Of the clergy, the dean of Derry was one; who, being there several times,
was asked by his bishop, whether he had heard anything but blasphemy and nonsense;
and whether he took off his hat in time of prayer, to join with us?
He answered, that he heard no blasphemy or nonsense, but the everlasting truth;
and did not only take off his hat at prayer, but his heart said amen to what he heard.
Yet he proved like the stony ground, and brought forth no fruit.
He said, though`' he could die for the principles of religion the Quakers professed;
yet to lose his living and character for some incidents they are tenacious of,
as plain language, plain habits, and other distinguishing particularities,
he did not think these of sufficient weight, or reasonable,
and so came no further in the way of truth,
put proved unfaithful in the day of small things.

In the intervals of meetings William Penn visited the lords justices of Ireland,
and chief ministers of government there;
in which he was very serviceable to truth and Friends.

But the envy of Satan soon began to work against the truth and us,
in such tools as he then had; for one John Plympton, a journeyman woolcomber,
and teacher among a few General Baptists, soon after we came there,
published an abusive paper against Friends in general, and William Penn in particular;
wherein he treated him with language much below common civility,
calling him a willful and desperate liar, etc.

Upon this several of us went to the chief elders of that people,
and afterwards to their meeting, and inquired whether this work was by their consent;
and they, in a very modest manner, and with concern, answered,
that it was altogether his own work, in which they had no hand, but disowned him therein.
Finding him an impertinent wrangler, of little consequence,
we took no further notice of him at that time,
but afterwards published a sheet called Gospel Truths; drawn up chiefly by William Penn,
and signed by himself and several others, of whom I was one.
Plympton also published a paper, which he called, A Quaker no Christian;
which William Penn answered by another, entitled, The Quaker a Christian.
He also reprinted the 8th and 9th chapters of his Primitive Christianity Revived;
which gave the people general satisfaction that Plympton`'s charges were groundless.
As William Penn`'s travels through the nation at that time,
made the envy of the priests to boil against the truth and us,
the bishop of Cork wrote a book against the above sheet entitled Gospel Truths;
which gave occasion for much controversy, and many other book`'s to be written.

We had several very crowded meetings at Dublin, and the Lord was with us; and many,
I believe, were touched by the virtue of truth;
especially through the ministry of William Penn,
upon whom were the eyes of the people in a more particular manner;
and John Everot had also good service: but justly preferring them before myself,
my spirit was weakened by bearing too much, and I became very uneasy;
but they taking a turn into the country about Wicklow for some days,
I had opportunity at Dublin to clear my mind to Friends and others in several meetings.

William Penn returning to Dublin,
we went from there on the 27th of the third month towards the county of Wexford,
and next day got to our friend John Watson`'s, where we stayed some hours;
and from there to Lambstown, to our friend Thomas Cubage`'s;
and in the mean time John Everot visited some meetings alone in those parts.
William Penn and I had a large and good meeting at Lambstown on the 29th,
the divine presence being with us, to the praise of His holy name.

On the 1st of the fourth month, +++[+++1698]
we had a meeting at Wexford, which was very large and open;
after which a justice of peace for the county and his wife dined with us,
being very near the truth, and loving; and that evening we returned to Lambstown.
Next day we wrote the following epistle to the yearly meeting at London:

[.embedded-content-document.letter]
--

[.salutation]
Dear friends and brethren,

It is not the least of our exercises that we are thus far outwardly
separated from you at this time of your holy and blessed solemnity;
but because we have great reason to believe it is the will of God,
we humbly submit to his ordering hand;
and with open arms of deep and tender love embrace you, our living and loving brethren;
who are given up to serve the Lord in your generation,
and that have long preferred Jerusalem and the peace
and prosperity of her borders above your chiefest joy.
The salutation of our endeared brotherly love in Christ Jesus is unto you,
desiring that he may richly appear among you in power, wisdom, and love,
to guide your judgments and influence your spirits in this weighty anniversary assembly;
that so nothing may appear or have place among you,
but what singly seeks the honor of the Lord, the exaltation of his truth,
and the peace and edification of his heritage.
This, brethren, you and we know has been the aim, end,
and practice of those whom the Lord has made willing to
forsake and give up all for his name`'s sake;
and through various exercises and tribulations, yes, in the way of the daily cross,
and through the fight and baptism of manifold afflictions,
to have their conduct and sojourning here below in fear and love;
looking for their reward in the heavens, that shall never pass away.
These have not been lifted up by good report, or cast down by evil report,
from their love to the Lord and his precious truth; but held on their way;
whose hands being clean of evil things towards all men,
have waxed stronger and stronger in the Lord.
Wherefore, dear brethren,
let us also be found in the same steps and walking the same way; not being high-minded,
but fearing the Lord, that we may serve him through our generation,
in diligence and faithfulness,
and so enter into the rest that God has reserved for
his true travelers and laborers in his vineyard.

And now, dear brethren,
know that the Lord has brought us well into this kingdom of Ireland,
and given us many large and blessed opportunities in several parts;
meetings being crowded by people of all ranks and persuasions, especially at Dublin; who,
for anything we have heard, have given the truth a good report.
Indeed the Lord has mightily appeared for his own name,
and owned us with a more than ordinary presence, suitable to the occasions,
and made very heavy and hard things easy to us, because of the glory of his power,
with which he assisted us in our needful times; for which our souls bow before him,
and bless, reverence, and praise his holy and worthy name.
So that, dear brethren, we have good tidings to give you of truth`'s prosperity at large;
and more especially in the church,
having had the comfort of the general meeting of this nation,
consisting of many weighty brethren and sisters from all parts thereof,
which was held in the city of Dublin, in much love, peace, and unity, for several days;
wherein we had occasion to observe their commendable care for the prosperity
of the blessed truth in all the branches of its holy testimony,
both in the general and in the particular;
improving the good order that is practiced among the churches of Christ in our nation.

Their simplicity, gravity and coolness, in managing their church affairs;
their diligence in meetings, both for worship and business;
their despatch in ending differences, and expedients to prevent them;
but especially their zeal against covetousness and indifference in truth`'s service,
and an exemplary care to discourage an immoderate
concern in the pursuit of the things of this life,
and to excite Friends to do good with what they are possessed of, while they have it,
and time to do good withal; have very greatly comforted us.
In the sweet and blessed power of Christ Jesus, the meetings ended and Friends departed.
The Lord grant that you may also make the same purpose the travail of your souls,
and end of your labor and service of love, as not seeking your own things,
but the things of Jesus Christ, in this your solemn general meeting.
And, dear brethren, we must tell you,
here is room enough for true laborers in God`'s vineyard;
and cannot well forbear to recommend the service of
truth in this nation to your serious consideration,
if happily the Lord may put it into the hearts of any faithful
and weighty brethren to visit it in the word of eternal life;
for we cannot but say, the harvest appears to us to be great, and the laborers,
in comparison, but few.

So, in that love which many waters cannot quench,
nor distance wear out of our remembrance,
and in which we desire to be remembered of you to the Lord of our household,
we dearly and tenderly salute and embrace you,
and remain,

[.signed-section-closing]
Your loving and faithful brethren,

[.signed-section-signature]
William Penn, John Everot, Thomas Story

[.postscript]
P+++.+++ S. Friends here have been very zealous and liberal in printing and re-printing,
and freely distributing to very good purpose,
great quantities of several books and papers, written in defense of the Truth,
and for information of the simple and misinformed; which, we hope,
will also fall under your consideration.

--

Before we departed from Lambstown, I found my mind deeply engaged in some heavy work,
and much laden; but as I did not know the cause, I concealed my concern from every one.
On the 3rd of the fourth month, being the sixth of the week, we set out for Waterford,
where was a meeting appointed to begin at the fifth hour in the afternoon of that day,
and my concern continued till we came to Ross, where we dined.
After dinner we took a boat to cross the river, in order for Waterford;
but as we were about to enter the boat,
about half a dozen dragoons stepped in before us and forced off the boat from the shore;
which William Penn observing,
wont to some of their officers and gentlemen standing on the key,
reasonably expecting they should so resent the abuse,
as at least to reprove the soldiers; which, when they neglected,
we perceived it was done by their direction, to prevent our passage.
William Penn said to them, with a suitable freedom and resentment.
What!
Are you gentlemen and officers,
and will stand here and suffer such insolence in your open view?
Then the load went off my mind, and my spirit was at liberty and over them.

The case was thus: in order to discourage the evil purposes of Papists,
the Parliament of Ireland had made a law,
that no Papist should be allowed to keep a horse
of the value of five pounds five shillings,
or upwards; and to make the same take effect,
the horse of any Papist being deemed worth so much, any person being a Protestant,
might discover, or make information of it upon oath, before two justices of the peace,
the mayor, or chief magistrate of any city, or town corporate.
The horse was to be brought before such magistrate, and the informer to pay,
or tender to the owner or possessor, the sum of five pounds five shillings,
and the property of the horse after such tender of the money,
was to be vested in the informer, etc.
All were to be deemed Papists who refused to take the oaths
and subscribe the declarations upon tender thereof, etc.
Though this law was not intended against Friends, yet it was put in practice against us.

The chief informers, we then perceived,
had seized several of our horses in town by this law, while we were at dinner;
and these dragoons seized our boat,
to detain us there till they could have opportunity to tender the money.

As some of our friends returned from the Key into town,
they met the informers in possession of four of our horses, namely: William Penn`'s,
and his son`'s, and two more.
The two last they returned by entreaty,
being worth little more than five pounds five shillings each;
but the two first they detained, being of much greater value.

William Penn and John Everot in the mean time had got over the river,
and several other Friends with them,
and took the horses that had been got over before the seizure,
and went on to Waterford to answer the meeting; and our friends Joseph Pike, of Cork,
and Thomas Cubage, of Lambstown, and some other Friends,
stayed to settle the matter about the horses which were in custody.
They going to the sufferan of the town, who granted the warrant, took out a replevin,
whereby they gained possession of the horses;
which so disappointed and enraged these covetous and unreasonable officers,
that they were upon the point of forcing them again from the Friends by their soldiers;
but not adventuring on that method, they stormed,
and boasted what they would expend in law to regain them.
They were so precipitate and inconsiderate in their seizure,
that they had omitted several material points directed by the
statute which gave us great advantage against them.
The replevin being taken out and bond given by Thomas Cubage to proceed therein,
we left them and went to Waleford that afternoon to the rest of our friends;
but the meeting was over before we arrived,
which was all the further hurl they could do us.

These rude disingenuous persons had not their ends of us;
for William Penn wrote to the lords justices of Ireland, complaining of the abuse;
and they issued an order, whereby they confined these officers to their chambers,
and commanded them to decline the suit.
They were detained several weeks,
till they made application to the governor of Waterford to make way
for them by some of our friends at Cork to William Penn,
and to entreat him to write again to the lords justices for their release,
and that they might not be broken.
The first they did not expect, until it should be effected by his means,
and the latter they much feared would happen, unless he signified his satisfaction;
which they had endeavored to obtain by paying
all charges and discharging the suit at Ross.
William Penn, who was not a man of revenge, but of justice and mercy,
so soon as he found their request was made in a due sense of their error,
delayed not to solicit for them accordingly; upon which they were released and forgiven,
for which they appeared very thankful and much humbled.

The meeting at Waterford was very large and well;
and it was said the bishop of the place and several of his clergy were in his garden,
where they might hear; but we heard of no objection,
William Penn having had the whole service of the meeting upon him.

On the 4th of the fourth month we went from Waterford to Clonmell,
and the next day being the first of the week, were at the province meeting there,
which was very large; and had another next day, on the afternoon of which,
the men`'s and women`'s meetings were held.

On the 7th we went for Youghall, though not without some danger,
of which we were not then aware.
For we were told afterwards that the Rapparees usually
haunted some waste places we had passed over;
and that there had been about fourteen of them in ambush under a hedge,
on the side of a mountain in our way, to have set upon us:
for they said if they could seize Mr. Penn, they should have a hatful of guineas.
But it being a heavy rain, and some of us staying behind,
our company was divided into several parties;
and several of the Rapparees knowing some of our company belonging to Youghall,
they did not attack us, or appear.
But whether for fear that some who knew them
might escape and make discovery who they were,
or that our number, though unarmed, over-awed them, or, which is most likely,
the Lord by his power restrained them, I shall not determine;
but through his good providence we went all safe to Youghall in the evening.
The Lord is good to them that love him,
and near to preserve those that trust in him and mean no hurt;
and all these can praise his never-failing power.

At Youghall we stayed one night, and had a small meeting with Friends there:
on the 7th we went into the barony of Imokilley,
where lies great part of William Penn`'s estate in that kingdom, some of which he viewed,
and we stayed thereabout till the 10th; and being at the castle of Shannigary,
belonging to him, a gentlewoman of good sense and character,
related to me the following passage:

"`That she being in the city of Cork when it was invested by King William`'s army,
and having a little daughter of hers with her, they were sitting together on a squab;
and being much concerned in mind about the danger and circumstances they were under,
she was seized with a sudden fear and strong impulse to arise from that seat,
which she did in a precipitant manner, and hastened to another part of the room;
and then was in the like concern for her child,
to whom she called with uncommon earnestness to come to her, which she did;
immediately after which came a cannon-ball and struck the seat all in pieces,
and drove the parts of it about the room, without any hurt to either of them.`"

From this relation I took occasion to reason with her thus:
"`That Intelligencer which gave her notice of the danger they were in,
must be a spiritual being,
having access to her mind--which is likewise of a
spiritual nature--when in that state of humiliation;
and must also be a good and beneficent Intelligencer, willing to preserve them,
and furnished also with knowledge and foresight more than human.
He must have known that such a piece would be fired at that time,
and that the ball would hit that seat and infallibly destroy you both,
if not prevented in due time by a suitable admonition;
which he suggested by the passion of fear, the passions being useful when duly subjected,
and by that means saved your lives.
And seeing that the passions of the mind can be wrought upon for our good,
by an invisible, beneficent Intelligencer, in a state of humiliation and stillness,
without any exterior medium,
is it not reasonable to conclude that an evil
intelligencer may have access likewise to the mind,
in a state of unwatchfulness,
when the passions are moving and the imagination
at liberty to form ideas destructive to the mind,
being thereby depraved and wounded?
And when so, is it not likewise reasonable to think that the Almighty himself,
who is the most pure, merciful, and beneficent Spirit, knowing all events and things,
does sometimes, at his pleasure, visit the minds of mankind through Christ,
so as to communicate of his goodness and virtue to a humble and silent mind,
to heal and instruct him in things pleasing to himself,
and proper for the conduct of man in his pilgrimage through this present world,
and lead him to the next in safety?`"

This coming immediately upon the instance she had given, took with her and the company;
who readily granted it might be so, and some of them knew it;
and this conversation seemed agreeable to us all.

On the 10th, in the evening, we went to Cork; and on the 12th,
being the first of the week, we had a large meeting there,
both of Friends from several parts, and others in great numbers;
and the divine truth was over all.

On the 16th, leaving John Everot at Cork, we went to Bandon; and from there next morning,
accompanied by several Friends, into the barony of Ibaune and Barryroe,
to view the rest of William Penn`'s estate in those parts, and spent two days there;
and on the 18th came back to Bandon,
where next day John Everot came to us with many Friends from Cork,
and being the first of the week, we were favored with a large good meeting,
which was much crowded with persons of all ranks, religions, and qualities.

Here we stayed that night, and the next day John Everot went west to Skibbereen,
and William Penn and I, with several Friends, returned towards Cork,
though William Penn turned off to Shannon Park, to visit the lord Shannon.

But while we were thus in the service of Truth,
according to the several degrees of the dispensation thereof unto every one of us,
Satan was busy in his evil work at London: for we had letters about this time from there,
importing that some persons professing truth,
and setting themselves up in the Society as no small dictators,
and some of them in the ministry, being filled with envy,
and unwisely emulating that glory and dignity the Lord was pleased to
put upon William Penn for the exaltation of his own holy name,
had made very unworthy and unchristian attempts against his character in his absence,
and even in the yearly meeting, to the great grief of all the right-minded among them:
but this was done by a shameless and implacable party.
The same week, on the third and sixth days, we had full and edifying meetings at Cork,
John Everot being also returned.

On the first-day following we had another very large and much crowded meeting there;
and the Lord was mightily with William Penn that day, clothing him with majesty,
holy zeal, and divine wisdom, to the great satisfaction of Friends there,
and admiration and applause of the people;
even increasing that unsought praise which some did much grudge him,
whose years and pretenses to truth might have shown
forth a better state of Christianity and wisdom;
and who, by attempting his character unjustly, greatly lost their own.

On the 28th I was at a meeting at Skibbereen,
accompanied by our friend George Kooke from Dublin, he having come to us at Cork.
The meeting was small, by reason of a fair that happened the same day at that village;
yet the promise of the Lord was made good unto us,
being met in the virtue of his holy name and presence,
which he was pleased to afford us together.

Next day were at Bandon, and were favored with a good meeting;
that evening we returned to Cork, where we had another meeting.

On the 3rd of the fifth month William Penn and John
Everot had a large and good meeting at Charleville,
which might have been much larger,
but the priest there began his sermon sooner than usual,
and our meetings there commonly not beginning till others have done,
he continued his discourse till our meeting was nearly over; in which he used,
as we heard, many invectives against Friends and our principles in general,
and against William Penn in particular.
Though such was the report which they that heard carried of the meeting,
that it soon wiped off all the priest`'s lies and reproaches;
and those of his hearers who had been so imposed upon by his long preachment,
when they heard of our good meeting, spoke contemptibly of him;
and one who had been at the meeting went to the priest and told him,
to his mortification, that Mr. Penn preached much better than he.
That evening they had another meeting near that place,
where came several persons who had been tendered in the other meeting,
and were again well satisfied.

The same day George Rooke and I stayed at Cork,
where the Lord likewise favored us with his good
presence in a large meeting of Friends and others;
and the next day, accompanied by several Friends, we went to Limerick,
where we were glad to see William Penn, John Everot, and many other Friends,
some of whom had accompanied them from Cork.

On the 5th, being the third-day of the week,
we had a great meeting at Limerick of a mixed multitude,
over whom was thick darkness that might be felt.
It was a hard meeting; and I came away with a heavy load,
not having had any time therein; yet it cleared up towards the end,
and some service was done as I believe.

That afternoon we viewed some of the effects of the late siege there,
and observed the walls of some houses, as well as of the city,
had been much shattered with many large cannon shot,
and that great breaches had been made at the late siege by King William`'s army.
We viewed also the ruins of the besieged`'s out-works and bastions,
and many unrepaired desolations and ruins,
as so many characters of the indignation of Him who justly
gives men up to the destruction one of another in furious wars,
when they like not to retain God in their thoughts, nor really to embrace his Son,
the Prince of love, peace, and concord; though in words they confess him.
Yet we had occasion here to observe the kind and protecting hand of
divine Providence over those who love and fear the Lord:
for we had a certain account from our friend Thomas Pearce, an apothecary in that city,
that in the time of the siege a bomb fell into his yard close by the window,
when many Friends were with him in the house; which, if it had broken,
might have destroyed them: but falling into a cistern full of water,
the fuse was quenched, and it did not break at all.

The next day we went to Birr, where we stayed that night,
and next day had a good meeting in the town-hall, which the chief magistrate,
at the instance of William Penn, let us have for that purpose.
To this meeting came the priest of the parish and several persons of quality thereabout,
and were all civil.
In the evening came the priest to see William Penn, with whom he had some conversation,
praising his good sermon and soundness of doctrine;
to whom William Penn gave a little book concerning our principles,
which he thankfully received and took a very respectful leave.

Next morning we set forward for Roseanallis,
to see our ancient and honorable friend William Edmundson,
where we arrived about the second hour in the afternoon,
and William Penn and John Everot stayed there;
and some Friends went on with me to Mount-mellick,
and that evening we visited some Friends in town and near it.

On the 10th, being the first of the week, William Penn and his company came to us,
and we had a very large meeting at Mountmellick, and the Lord was with us in general.
But as I had greater regard to the services of William Penn and John Everot than my own,
and at Limerick,
under that consideration had neglected my own gift till
the proper time for the exercise thereof was over,
and so had come from there greatly laden in my mind; fearing to do the like here,
and add to my burden,--too heavy already to bear-- I stood up to speak too soon;
and that I might not be in the way of those I preferred, I spoke too fast,
and thereby went before my right guide; so that my burden remained on that account,
though not so heavy as before: for the Lord, who is merciful, knew it was not willful,
but out of weakness.

By this conduct I obtained further, though expensive, experience;
that there ought to be neither too much regard nor disregard to any person,
neither short nor over, staying behind our true guide nor going before;
but in and with the divine and living truth, and the motion and operation of it,
in God`'s time; and then only can men preach the gospel.
W`'hen he moves his time is to be observed; and that and no other should be our time;
though some disappointments there are, not properly our own fault,
but occasioned by the unskillfulness and haste of others, taking a wrong time,
and intruding where they ought not; in which there is evil,
and the gospel of Christ thereby greatly hindered,
often out of the view of the unskillful instruments acting or omitting to act therein.

The same afternoon was their meeting for business,
where things were managed with a just severity against every appearance of evil,
to the great comfort of the upright and discouragement of evil doers.
A great instrument of exact discipline was that ancient
and worthy friend of truth William Edmundson,
who lived within the precincts of that meeting; for whom not they only,
but also all Ireland, may give thanks to the Lord,
for the due observation of order in the churches of Christ in that kingdom.

Next day we went to Edenderry,
where we met our friends Samuel Waldenfield and John Vaughton from London,
of whom we had an ample account of the concern moved
against William Penn in the yearly meeting at London,
in his absence; and by whom, and to what purposes,
and on what foundation it was chiefly begun and prosecuted;
being only the fruits of emulation and envy in some who
lacked that honor the Lord was pleased to put upon him,
and could not have it.

Here also we were favored with a large and full meeting of Friends and others,
several persons of quality being there, and two Episcopal priests; one of whom,
an ancient man, was tendered in the meeting by the testimony of truth,
to which he confessed.
The Lord was good to us that day;
and when the meeting was ended we had comfortable society together in his love,
who never fails to be with all those, from age to age,
and will be to the end of the world with them, that love one another in him,
according to his new and blessed commandment.

In the evening we went along with the London Friends and some others, to John Barcroft`'s,
where we stayed that night; and next morning the London Friends went towards Carlow,
and we, about thirty-one in company, set forward towards Lurgan in the north;
but the greatest part being Dublin Friends, went there, and William Penn, John Everot,
Samuel Randal, Thomas Pearce, Thomas Winsloe, myself,
and some young men from about Edenderry, went that night to Ardee, and lodged at an inn.

Our way to Lurgan was through a very wild, mountainous country;
but being met by several Friends about eight miles from there,
and well received while there, we were fresh and easy next morning,
when we had a very large meeting, about two parts Friends,
and of others some were persons of quality.
The Lord glorified his own arm that day, to the lasting honor of his name.
I had a short concern in the beginning of the meeting, then John Everot much larger;
and though slow a considerable time, and of no great appearance, for he made no flourish,
yet in the end of his labor truth was over all, in the virtue and power of it,
and so remained.
By the time he had done William Penn was full, as a new bottle with new wine;
and He who filled him therewith,
by him dispensed the same liberally to all that were athirst.

Many professors among the sectaries were there,
who now understood Friends had been much wronged
by false reports concerning our principles,
doctrines, and manners.
The Lord was good to us, and the meeting ended under a solid sense of his holy presence;
and that afternoon we rested, and had the society of Friends.
The next morning, about seven, had a select meeting, in great sweetness, among Friends,
and then departed towards Dublin.

We lodged that night at Dundalk,
where we had opportunity to see the place of the late miserable camps,
where such numbers died in great distress.
Here we saw many proofs of the misery many souls had endured in time of sickness,
in a cold and wet winter season;
but that which most of all gave occasion for
reflection on the miseries and calamities of war,
by men professing, on all hands, the peaceable Savior,
was the sculls and other bones of human bodies, of the same flesh and blood with us,
for God made of one blood all nations, who never had received burial;
but their flesh had been, no doubt, rent from their bones by the wild beasts and dogs,
and fowls of the air.

In the evening of seventh-day we arrived at Dublin;
next day had two large and living meetings, many strangers being there.
We rested as privately as could be till the 20th, and then had another meeting there;
and that afternoon we went to Kilcock, about twelve miles from Dublin,
and next day to Carlow, where, on the 22nd, we had a large meeting.

Thus we travelled through the country, visiting Friends and meetings as we went,
till we came towards the south parts, where I left the company and went to Clonmell,
in order to see my brother George, then dean of Limerick,
and met with him at Thomas Osborn`'s, who had been sent into France for education,
and there had embraced the Romish religion.

I found him of a frank and familiar temper,
and he desired me to take a turn with him in the garden.
Walking there together, he asked me some questions concerning our principles,
and more particularly of our silent meetings, and of what advantage they were to us;
for he did suppose they were of some use,
else we would not continue in the practice of them.

I answered, that we had been as other men,
subject to common infirmities and ignorant of God,
as to any experience of his presence and divine working in us, till it pleased him,
in his own goodness and mercy, to visit us by the Spirit of his Son Christ;
through which we had known a time of condemnation and humiliation for sins past,
and true repentance and forgiveness; and believing in him,
through the work of his Spirit and power in our minds, he,
with the light and life of his Son, became the object of our faith;
by which also he sanctified our hearts, and reconciled us unto himself.
Thus the enmity being slain, and we made temples of the Holy Ghost,
we now worshipped the Father through the Spirit of his Son,
in a state of faith and obedience; whereby we draw near unto him,
even through that blessed Mediator whom he has appointed, partaking of the nature of man;
not of flesh and blood only as the Son of man,
but also being clothed with a holy human mind.
By him we are made partakers of the divine nature as the sons of God; as it is written,
"`He shall take of mine, and show it unto you.`"
And the Father being made manifest in him, we have instructions in wisdom,
and enjoyments in the divine and blessed presence, of which the world,
in a state of nature, is not aware, and never more so than in a state of true silence;
where all the passions, affections, and natural desires of the heart are silenced,
by the all-commanding voice and power of the divine Word; who said, "`Let the worlds be,
and it was so.`"

He heard me with attention, and replied, that he firmly believed what I had said;
that we were such a people, and consequently the happiest in the world;
over whom the Almighty has a particular care.
Then he told me a passage concerning himself, saying,
that he and some other gentlemen being at Clonmell some time ago,
they heard that one of our meetings was appointed there that day,
by one of our preachers from the west of England, and they agreed to go to it.
After they had been there about half an hour, the rest all tired,
and would have had him away with them;
but he was so much satisfied with what he fell there, that he could not go with them,
but stayed the meeting to the end;
having never met with the like satisfaction any where else.

By the time this relation was finished,
he began to be apprehensive that his priest might miss us out of the company,
and be in quest of him, for he kept a Popish priest in his house,
under the appearance of a gentleman, and so it proved,
for we were but got back into the garden till he came to us.
The priest beginning to ask me some questions about religion, he withdrew;
for the priests will seldom permit, if they can avoid it,
that their people shall hear any debates between them and Protestants,
lest they should be infected with what they call heresy;
unless where they think they shall have manifestly the
advantage in the argument upon the subject.

The first question he asked me was, whether we believed predestination?
I answered "`No, but that the grace of God, through our Lord Jesus Christ, is universal,
and free to all mankind.`"
He said, they were of different opinions on that subject; some one way, and some another:
and then asked me what we thought of excommunication, and its effect in the church?

I answered, that it ought to be applied to such as deny the faith in express words;
or if not in words, yet by actions,
by committing and persisting in any immoral or sinful acts,
or declining the common and slated rules of the community,
or terms of Christian communion among them:
but that excommunication ought not to affect life, liberty, property,
or the person of anyone, but only to deny him Christian communion till reformed.

This, he said, was not of sufficient force to awe offenders, or to induce their return,
where the motives to their offenses were strong and cogent.

I replied, that to be denied communion by any real Christian congregation,
of which one is a member, is a matter of great weight and consequence.
For certainly God is with and in his own appointments;
and whosoever is denied by the church of Christ, is denied by himself.
For as she acts in and by his Spirit, which is ever in her, and present with her,
it is his act by her; and in that respect, she is called the ground and pillar of truth.
Offenders so denied, undergo, even in this life,
a burden more sinking than the loss of all they have in the world;
whereby life itself becomes a load and tedious.
But where any form of excommunication is invented only by the wisdom or policy of men,
from secular views, with punishments of their own contriving annexed,
the Lord does not cooperate there, nor own that ordinance;
so that the punishments awarded, which are often inadequate, cruel, and unjust,
are all that the excommunicated sustain; not for the salvation of the soul,
but satisfying the ends of power, pride, covetousness, and envy,
to the destruction of the character, estate, body, and family, if not ruin of the soul,
by complying, under such grievous temptations, with heterodox errors in opinion,
and practices immoral, idolatrous, and anti-christian;
fruits of the inventions of apostate and fallen spirits,
by whom the children of men are deceived.

Being then near the house, we were called to supper; and that being over,
he began to introduce other matter of controversy.

He saluted me with some encomiums,
that he might cast his net with greater certainty and success.
"`Sir,`" said he, "`I have heard a very good character of you,
both as to your understanding and other qualifications and accomplishments;
from which I conclude, it must have been something extraordinary, or very particular,
which induced you to embrace a religion and opinions so
generally exploded by men of sense and penetration;
and as sufficient reasons, to yourself at least, for what you have done on that account,
cannot be lacking to a man of your repute, I beg leave to ask you some questions,
that I may be better informed than yet I have
been concerning the religion you now profess.

"`Do you believe there ever was such a man in the world as Jesus Christ?`"
This question looked scurrilous and smiling; yet,
perceiving he meant to lay a foundation for some further superstructure, I answered,
"`Yes,
we believe all that is written in the holy Scriptures
concerning our Lord and Savior Jesus Christ,
and upon as good a foundation and evidence, if not better,
than any who have pretended to suspect us on that account.`"
Then he went on; "`Do you believe that Jesus Christ made choice of twelve persons,
called his apostles?`"
I answered yes.
Again said he,
"`Do you believe that Christ commanded his apostles to go teach all nations,
baptizing them in the name of the Father, Son, and Holy Ghost?`"
I answered, "`Yes, with some restrictions and observations now to be noted, we do.`"
He continued to interrogate;
"`Do you believe that the apostles of Christ did go and preach and baptize,
according to this command?`"
I answered, as before, yes.
"`Then,`" said he, "`how can you be Christians, or disciples of Christ,
who deny this baptism, and do not at all practice it?`"

Then I asked him if he did believe, and those of his communion, that the Lord Jesus,
at that time, thereby instituted water baptism?
He answered, they did believe that Christ by these words, at that time,
instituted water baptism.
Then I answered,
"`That if those were not Christians who declined the use of water baptism,
I would prove that neither himself, nor the pope, nor any of his communion,
are Christians,
not being baptized at all in the practice of what
Christ commanded or instituted at that time,
as follows:

"`John the Baptist being commanded by the Word of God to baptize the Jews in water,
foretold them of another Baptizer much preferable to himself,
and of a baptism excelling his, being of another nature,
and more powerful and efficacious, even with the Holy Ghost and fire.
This baptizer is Christ; who, having been circumcised,
in obedience to the ordinance of the law of Moses, under which, as man,
he was born into this world, and fulfilled, in his own person,
all the righteousness thereof, according to the prophets,
he was also baptized of John with wafer;
thereby not only submitting to that dispensation,
as an ordinance of God for the time being,
but also fulfilling all righteousness in his own person;
that being declared from heaven to be the Son of God, he might, from then forward,
through the divine anointing poured upon him above all his brethren, and without measure,
be the Dispenser of all righteousness and truth unto all generations.
From that time onward he preached repentance to the Jews, as John did,
and by his disciples, but not in his own person, baptized likewise with water,
as an intermediate dispensation between the law and the gospel.
But with this difference,
John baptized for a time without directing the subjects of his baptism to any
certain object of faith saying they must believe in one that was to come after him,
for he did not then know that Jesus was the Christ.
But the disciples of Christ, as also John, from the time of the baptism of Jesus,
having believed in him as he is the Messiah, preached not only repentance,
but also that Jesus is the Christ and Savior promised of God unto Israel;
and consequently directed them unto him as the true object of their faith,
and baptized in his name, and by his authority while yet present with them.
Yet water baptism is but water baptism, whether administered by Christ himself,
or by any other he may command; nor did John, or the disciples of Christ,
administer water baptism in that day to any but the Jews, or the proselytes among them.

"`But after Christ had been crucified and arisen from the dead,
a little before he ascended into heaven, he said unto the eleven,
'`All power is given unto me in heaven and in earth.
Go you therefore and teach all nations, baptizing them into the name of the Father, Son,
and Holy Ghost, etc.
Go you into all the world, and preach the gospel to every creature.
He that believes and is baptized, shall be saved; but he that believes not,
shall be damned.
And being assembled together with them,
he commanded them that they should not depart from Jerusalem;
but wait for the promise of the Father, which you have heard of me.
For John truly baptized with water; but you shall be baptized with the Holy Ghost,
not many days hence.
But you shall receive power after the Holy Ghost is come upon you;
and you shall be witnesses unto me, both in Jerusalem, and in all Judea, and in Samaria,
and to the uttermost parts of the earth.
And teaching
them all things whatsoever I have commanded you.
And lo I am with you always, even unto the end of the world.`'

"`1st; The Lord Jesus declares his own power,
and sufficient authority to institute this baptism; '`All power in heaven and in earth.`'
2ndly; The extent of it, '`To all nations; to preach the gospel to all the world,
thereby discipling or initiating all that believe and obey,
into the divine nature of the Father, Son, and Holy Ghost.
The act of baptizing is chiefly by preaching in
the power and wisdom of the Spirit of Christ,
and sometimes by laying on of the hands of his ministers,
as moved thereunto by the same Spirit.
3rdly; The advantage to be reaped by believing their message,
and being baptized with this baptism,
'`they shall be saved;`' which salvation cannot be imputed to water baptism.
4thly;
The judgment denounced against such as would not
believe the message of his ministers and witnesses,
thus qualified and sent; '`They shall be damned.`'
5thly; The apostles themselves were not to enter upon that work,
nor could they perform it, notwithstanding this verbal command from his own mouth,
but under the immediate influence of the Holy Ghost, and by his power only;
being no other than the Spirit of Christ promised to them before he was crucified.
6thly; It was not water baptism;
for that he here contradistinguishes from the baptism of the Holy Ghost,
and ascribes it to John, saying,
'`John truly baptized with water,`' as a thing already over,
at least in point of obligation;
and then the baptism of the Holy Ghost alone is here appointed;
'`but you shall be baptized with the Holy Ghost not many days hence.`'
Here water baptism was already over, or near an end,
and the Spirit`'s baptism not yet actually commenced, but only promised;
and very soon after took place accordingly.
7thly;
This baptism is such as cannot be performed
without the immediate power of the Holy Ghost;
and accordingly he is here mentioned to that end.
It cannot be water baptism,
because any man can baptize with water without the Holy Ghost;
and all mankind who now use it do so, without any influence at all of the Holy Ghost,
or any command from him to that purpose, if at all they have any real knowledge of him.
8thly; And since no power on earth can give this qualification but Christ alone;
and no man can be a true witness unto him, be his minister, or preach him and his gospel,
but by the power and influence of the Spirit of Christ,
immediately upon him in the time of preaching;
and that they only who are so qualified by him, have right or power to preach the gospel,
and that in all parts of the world,
they ought not to be hindered or molested by any earthly power.
And such as do obstruct them, are opposers of the work of him who has all power,
and shall surely suffer by that power, in this or another world, or in both,
if they do not, in due time repent ill this.
9thly; The matter and substance of their teachings,
after having borne witness to himself and his sufferings,
'`All things whatsoever he had before commanded them.`'
First, the old commandment, which they had heard from the beginning, that is,
the righteousness of the moral law, briefly expressed in these words,
'`You shall love the Lord your God with all your soul, and with all your strength,
and your neighbor as yourself.`'
And secondly, the new and gospel commandment, that they should love one another,
as the true and certain characteristic of their discipleship.
10thly; In this gospel, and this practice,
he promised to be with them and all those who
should succeed them in this faith and practice,
to the end of the world.
So that as his true ministers can do nothing without him, vet, as he is always with them,
they are, by him enabled to do all things,
whatsoever it pleases him to work in or by them, or require of them.
And whosoever set themselves at work, pretending to exercise any ordinance of Christ,
without his Spirit and power sensibly with them, they are antichrists and impostors;
and therefore they have not, nor can they profit the people, but mislead them.

"`As to those instances from which you seems to collect that the apostles
baptized with water after the effusion of the Holy Ghost upon them;
that was only a continuance of the same water baptism
they had been in the practice of in John`'s time,
and not from that command and mission, Matt. 28:19.
And as to the continuance of water baptism in the church unto this day,
that is a great mistake: for first, I observe what water baptism is in the act of it;
that is, a going into water, and being washed and dipped therein,
and not rantised or sprinkled only.
And secondly, note also, that the water baptism administered in the apostles`' days,
was always only in the name of the Lord Jesus, and not in the name of the Father, Son,
and Holy Ghost; which shows it was not from that command, Matt. 28:19,
for then they would have pursued these terms of institution; which they never did,
by anything I can find in all the Scriptures.

"`I say again,
that if those are not Christians who are not under the administration of water baptism,
then you yourselves are no Christians, having been out of the practice,
even of that water baptism, for many generations;
inventing to yourselves sprinkling of infants, never commanded by Christ,
nor practiced by his apostles, which is no baptism at all, but rantism;
and is an error from both the mode and subjects of baptism.
And therefore you only profane and take in vain that holy name,
in which you exercise this your own invention.`"

Upon this the priest was totally silent; and knowing him bound,
I challenged him three times before the company,
to answer me on that subject if he could; and yet he did not,
nor said anything at all on any other subject that night.

This being on the seventh-day night, and now very late, I took leave,
and proposing to go to rest,
the gentleman of the house would not sutler a servant to attend me to my chamber,
but went himself; and when there, he told me,
that he had never heard those things so explained before;
that he was very glad of the occasion; and that he was of the same mind with me therein;
that he would gladly go with me in the morning to hear Mr. Penn,
but that my brother and sister had not been at his house before, since their marriage,
and it would look as if he neglected them if he should go with me.
"`Besides,`" said he, "`this person with whom you discoursed, is a priest,
whom I keep in my house, and I know he would take it ill if I should go to your meeting,
and leave our own devotion.

A relation of mine happening to be there, and knowing the way,
we set forward early next morning for Cashel;
where we arrived before the meeting was gathered,
to which came a great multitude of people of all notions and ranks.
The meeting being set, the mayor of the town, with constables, etc., came,
by direction of the bishop of the place, and in the king`'s name,
commanded us to disperse,
though he could not get into the body of the meeting for the throng.

John Vaughton having been preaching in the meeting, turned to the mayor and said,
that he, with some others of our Friends,
had been admitted into the king`'s presence on a certain occasion,
before he came from England;
and the king was pleased to ask if we had full liberty
in all his dominions to exercise our religion,
without molestation?
And we, not knowing anything to the contrary, answered,
that through the good providence of the Almighty, who had placed the king on the throne,
and the king`'s kind indulgence, we had now more liberty than before;
for which we were thankful to God and the king.
To which the king was pleased to reply.
That if any did disturb us in the exercise of our religious liberties,
make it known to him, and he would provide for us therein, and protect us.
And here you disturbs our meeting, and commands us in the king`'s name, to disperse,
as if we were transgressors.
But whether we should obey you without law, or believe the king`'s word,
and accept of his royal protection according to law, let all that hear judge.

The people did not seem to be concerned at the mayor`'s appearance in this manner,
but kept their places.
Then I stood up and spoke among them such things as I believed my duty at that time;
and in the mean time, the mayor reached over the half space from an entry or passage,
where he stood in his accoutrements, with cap and sword, to take me by the arm,
to pull me down, or haul me out of the place; but he missed his catch, and I went on.
Near the conclusion of what I said, I remarked to the people, that the high priests,
scribes and pharisees of old,
were the greatest enemies of Christ and his apostles and disciples; and that generally,
where mischief appeared in any nation professing religion, that set of men,
in every form, were at the bottom of it; and so it is still to this day.
They would ever ride mankind, and rule over them as property to themselves,
and of them serve their own lusts of self-love, pride, envy, and domination,
covetousness, wealth, and power, under a false pretense of serving God; and as if,
by divine authority from the Lord,
they were appointed to take the care and cure of the souls of other men,
while they are in the high-way to ruin and lose their own; but were now made manifest,
and would yet be more so, and the people redeemed from under their heavy yoke.

The mayor did not relish this, but could not come at me for the crowd; and William Penn,
who was not yet come into the meeting, sending to speak with him in a chamber near by,
he went immediately; for I believe he was weary of that office,
which had been imposed upon him by the bishop of Cashel against his own inclination.

William Penn treated him with the respect due to his office, but desired him to retire,
and let the bishop know that he would see him at
his own house after the meeting was over,
desiring the bishop`'s patience till then; and the mayor did so accordingly,
Then William Penn came into the meeting,
for he had been writing letters of importance while the meeting was not fully gathered;
which was so large at last that the greatest part could not get in.
The Lord favored us that day with his good presence,
fitting every instrument for the work required;
and the people were generally satisfied with what they heard and felt,
to the honor of God, and the comfort of his people.

The meeting being ended,
William Penn took two or three ancient Friends of that country with him,
and went to the bishop; and after an interchange of some tokens of civil respect,
each in his own mode, he expostulated with him concerning that transaction,
in sending the mayor to the meeting in that manner, as above; and told him,
it looked a little extraordinary, as the king`'s dominions and the laws were then stated,
and a general liberty granted to all his subjects, and nothing new there that day,
being the usual time and place of our meeting, unless it were that he himself was there,
which might excite the curiosity of the people to see what sort of a creature he was,
since, one way or another, he had been represented as some monster, or uncommon thing,
to be gazed at.

The bishop could not maintain what he had done, but treated William Penn friendly,
and told him, "`That he went that morning to church to perform his office of preaching,
as usual, and when there, he had no body to preach to but the mayor, church-wardens,
some of the constables, and the walls, the people being all gone to your meeting; which,
I confess,`" said the bishop, "`made me a little angry,
and I sent the mayor and constables with that message, in hope, by that means,
to have a greater auditory; though I have no ill will to you,
or those of your profession.`"
After some tokens of mutual respect they parted in seeming friendship;
but the bishop had another design.
The Friends present with them at this interview,
related to us this passage when they returned to our company.

The bishop recollecting, when the hot tit was over,
what noise such an action might make in the nation,
that such a meeting should be so disturbed by his command,
and which could not be justified,
unless the meeting had been attended with some extraordinary and unlawful circumstances,
wrote to the earl of Galloway and the other lord justices of Ireland, and informed them,
though unduly, "`That Mr. Penn and the Quakers had gathered together in that place,
that day, such a vast multitude of people, and so many armed Papists,
that it struck a terror into him and the town;
and not knowing what might be the consequence of such an appearance,
he had sent the mayor and other magistrates to disperse them;
but seeing they had taken no notice of him, or the civil powers there,
he thought it his duty to lay the matter before their lordships,
that such remedy might be applied, as in their wisdom they might think proper,
to obviate the danger and ill consequences of such assemblies.`"

From Cashel, William Penn, John Everot, and i, went towards Cork,
taking meetings in our way,
the other Friends pursuing their visit in other parts of the nation,
as it laid before them.
When we came there, William Penn went to see the lords justices,
who had a very great friendship for him, and were got there before us;
and after mutual salutations were interchanged,
the earl of Galloway gave the bishop of Cashel`'s letter to William Penn to read; which,
when done, he related all the particulars to them; telling them,
that he did not see any armed persons there,
unless here and there a gentleman might have a sword, as usual;
but knew nothing of what religion they were.
And then the earl said of the bishop,
"`Old dotard! why should he make all this to do on such a common occasion?`"
And that was all this forward man got for his misrepresentation of us.

We stayed at Cork and those parts, having meetings there and in the country,
till the 19th day of the sixth month; and then set sail in the Jane of London,
and landed at Minehead on the 21st day of the same, in good health, and in peace;
for which we were thankful to the Lord and giver of all our mercies.
That night we lodged at Thomas Holway`'s, having had a meeting there that evening,
and we had another next day; and from there we went to Bristol,
where I lodged at William Penn`'s, and stayed some weeks,
till he had finished his answer to the bishop of Cork`'s book.
I assisted in transcribing his sheets, searching the Scriptures, etc.,
which being finished, I returned to London on the 5th of the eighth month,
preserved through all dangers, and in peace;
to the sole praise of Him who lives and reigns,
and is worthy of all adoration and glory forever and ever.
Amen.
