== Chapter VII

We went to Stratford, and next day by Milford to New Haven; where,
alighting for refreshment, I had a concern to pray before we ate;
which several persons in the house took notice of, to the advantage of our profession,
they, as many others, having been misinformed, that we never prayed,
or gave thanks on such occasions.
Being desirous to have a meeting there,
I made request to our landlord for the liberty of his house for that purpose;
to which he replied, that without leave of the magistrates he could not.
Then we went to speak with the next justice of peace about it, but he was not at home;
and neither we, nor the innkeeper himself,
could have the liberty of his house for a meeting.

As we were going away, at the other end of the town, we called at the mayor`'s house,
and told him the innkeeper would let us have a meeting in his house,
provided we had the assent of a magistrate.
And though he was very smooth at first, he soon after told us,
he would not give way to any such thing, since they had already a ministry`' of their own,
and did not lack anything of us; for they understood we denied Christ,
and were heretical; with some other opprobrious language, and false accusations.

I replied, "`That we own Christ, and believe him to be the Savior of the world;
and would gladly have an opportunity to undeceive people concerning Christ,
and those things wherein they are in error about the
Lord and us;`" but by no means would he consent.
Such is the great bondage and slavery that people are in to their hired preachers;
who had got a law made, destructive of the liberty of their consciences and civil rights:
so that neither magistrates nor people dared do anything,
but according to the will of the priest.

From New Haven we went to Killingsworth, about twenty-eight miles,
and that night at the inn had some dispute with our landlord, and others,
concerning freedom from sin in this life; which we maintained against them,
by the sixth and eighth chapters to the Romans, and first Epistle of John,
where it is written, "`What shall we say then?
Shall we continue in sin, that grace may abound?
God forbid: how shall we, that are dead to sin, live any longer therein?`"
"`For in that he (Christ) died, he died unto sin once: but in that he lives,
he lives unto God.
Likewise reckon you also yourselves to be dead indeed unto sin,
but alive unto God through Jesus Christ our Lord.`"
"`Being then made free from sin, you became the servants of righteousness.`"
"`For when you were the servants of sin, you were free from righteousness.`"
"`But now being made free from sin, and become servants to God,
you have your fruit unto holiness; and the end, everlasting life.`"
"`For the law of the Spirit of life, in Christ Jesus,
has made me free from the law of sin and death.`"
"`If we say that we have no sin, we deceive ourselves, and the truth is not in us.`"
"`If we say we have not sinned, we make him a liar, and his word is not in us.`"
"`If we confess our sins, (that is,
unto the Lord who convinces us of them) he is faithful and just to forgive us our sins,
and to cleanse us from all unrighteousness.`"
"`But if we walk in the light, as he is in the light,
we have fellowship one with another, and the blood of Jesus Christ his Son,
(that is the Son of God) cleanses us from all sin.`"
"`I have written unto you, young men, because you are strong,
and the word of God abides in you, and you have overcome the wicked one.`"
"`And every man that has this hope, (that is, to be like him,
and see him as he is) purifies himself, even as he is pure.`"
"`Whosoever abides in him, sins not: whosoever sins, has not seen him,
neither known him.`"
"`He that commits sin, is of the devil; for the devil sins from the beginning.
For this purpose the Son of God was manifested,
that he might destroy the works of the devil.
Whosoever is born of God, does not commit sin; for his seed (that is,
the word Christ) remains in him: and he cannot sin, because he is born of God.`"

Having thus, and with other arguments deduced from these and other Scriptures,
maintained the doctrine of truth against their false
and pernicious doctrine of sin for term of life;
we then sent the priest of the town word, that if he would summon his people,
(for they had boasted that their minister could have said great things,
and answered all if he had been there) by such a time in the morning, and give us notice,
we would meet him and them in conference, about this and other controversial points;
but no answer came.

We departed next morning, and rode about forty miles;
and on the following day set forward for Rhode Island,
and in our way called at a little ordinary, where there was an Indian woman spinning;
and after a while I found a concern for her in my mind, and made her slop her wheel,
and spoke to her of the witness of God in her, which discovered to her good and evil,
that dictates the former, and reproves the latter.
To which she confessed, and said, with tears in her eyes,
that she knew better than she practiced, and was very humble.
We went forward to the house of Rowland Robinson in Narraganset,
where we were kindly received, and then to Joseph Mory`'s in Conanicut,
from which we sent notice that evening to Newport on Rhode Island, of our coming.
Next day, being the first of the week, were at their meeting, which was not very large,
because of a new monthly meeting for worship that day begun in Narraganset,
to which many Friends in those parts were gone.
We staid till third-day, and I had a meeting at Conanicut island,
and returned that evening to Rhode Island; and next day had a large meeting at Newport,
and the day after another some miles off.
Next morning we set forward for Boston, and that night lodged at a poor inn in Braintree.

Near Boston, on a green, we observed a gallows;
and being told that was the place where several
of our friends had suffered death for the Truth,
and had been there thrown into a hole, we rode a little out of the way to see it;
which was a kind of pit near the gallows, and full of water, but two posts at each end,
which had been set there by means of Edward Shippen of Philadelphia, a reputable Friend,
formerly of Boston; who would have erected some more lasting monument there,
but the magistrates were not willing,
since it would too frequently bring to remembrance that great error of their ancestors,
which could not now be repaired.

While we sat on horseback by the pit, we were drawn into right silence, by the awful,
yet life-giving presence of the Lord,
which there graciously and unexpectedly visited us together, and tendered us;
and so raised our minds, though in deep humility before the Lord,
over that evil spirit which murdered our friends,
that for my own part the inhabitants were no more than
as the dust in the streets as we rode among them.

But though I rode into the town in this holy triumph, yet,
in a short time I was so inwardly weak and cast down,
that I was as the dirt under the feet of all;
so that I could not look even their children in the face.
But being raised again by the Truth into my former condition,
I perceived that the state of triumph I had been in,
represented to me the state of glory, which the Lord Jesus and his saints,
with those our friends, and others, are now in;
and that low state represented the condition of the
Seed of life in that people still suffering under all.
We lodged with our friend Daniel Zachary, and had a small meeting next day,
the first of the week, there being few Friends in the town, or near it;
but in the evening we had one much larger, the house being crowded,
and the Lord favored us with his good presence, and things were well and comfortable.
The meetinghouse being in a narrow thoroughfare-lane,
many of the people came as if passing that way occasionally,
and seeing some persons in the meeting, slopped,
as if it had been to look upon us but at a distance; yet standing a while,
they at length came in, and were very sober.

On second-day we went to Lynn, where,
hearing of a meeting appointed by our friend Jedediah Allan, about two miles from there,
we went to it, and lodged that night with our friend Richard Eslis, at Lynn,
and had a meeting the next day at Salem: proceeded next day to Hampton, forty miles,
and had a meeting there on the 13th, being the fifth of the week,
among a considerable number of young convinced Friends, who had embraced the Truth,
for the most part, by the gospel ministry of Jonathan Taylor,
who had been in those parts some time before us;
and the Lord gave us a comfortable season among them.

On the 14th we went to Dover, and next day had a small meeting at Cachecha,
about three miles further, at the house of our friend Thomas Hanson.
This was the furthest we went in that country;
for we were informed that the country for above one hundred miles further north-east,
formerly inhabited by the English, was at this time laid waste by the Indians;
one of whom, in these last wars, was able to chase several English; whereas, formerly,
it was much the contrary.
Many houses had been laid waste and ruined,
and the owners were at this time beginning to return,
but many were not yet bold enough to lodge out of some garrison.

I did not hear of any of our friends who carried arms when abroad, or in their business,
but two, and these the Indians killed;
but most went into garrisons to lodge in the nights, and some did not,
but trusted in the Lord; and we kept clear of all garrisons,
always lodging without their bounds.
The people in those parts were willing to hear us; then, if ever,
are they apt to receive the Lord and his truth,
when their minds are humbled by his judgments.

On the 16th, being the first of the week, we had a large open meeting at Dover,
and things were well; and next day returned to Hampton,
and on the 18th had a meeting at Joseph Chase`'s,
where we had the company of many of the people.
My companion comparing their priests to the serpent, who, by some things true,
and some false, beguiled Eve; for these men preach to the people, sin term of life,
and heaven in the end; not regarding the holy Scripture, where it is said,
"`He that commits sin is the servant of sin; and his servants you are to whom you obey,
whether of sin unto death, or of obedience unto righteousness.`"
He was opposed by a rude person, who called him a liar; but my companion being over him,
bid him be silent till he had done, and he would answer any objection;
but before the time was half over, he slipped away, and the meeting ended well,
and in peace.

On the 19th we had a meeting at Salisbury;
and there having been a report that the minister of the place, one Major Pike,
and Joseph Ring, all great opposers, intended to be there, it was very large;
yet none of them came but Ring, who did not oppose, but slunk off towards the conclusion;
and the meeting was held and concluded in peace, and the blessed Truth was over all.

That night we returned to Hampton, and next day to Salem, about forty miles,
and got to their week-day meeting; and the day after to Lynn,
where we likewise had a meeting, and from there to Boston,
where we had two meetings the next day, the latter whereof being in the evening,
and the first of the week, was large.

Having an inclination to return towards Hampton and Dover,
and to have some meetings where we had not yet had any; I went back from Boston,
and my companion intending to go to a yearly meeting at Providence,
went towards Scituate.
That day I went to Lynn, and the next day had a meeting with Friends at Salem,
where part of my testimony was against a sleepy state in some,
and a wandering spirit in others; which I perceived infested and hurt that meeting,
and hindered the growth of several.
It was a tender, comfortable meeting,
and I was told afterwards there was great need of such a testimony:
one ancient Friend confessed, with tears,
that he had received great hurt in meetings by a wandering spirit,
which draws away the mind from a true and sincere waiting upon God,
and hinders its progress in the truth, and in the true worship.

On the 26th I went towards Hampton, accompanied by my kind friend Samuel Collins,
of Lynn, and as we were near Ipswich, one of his acquaintance, not a Friend,
overtook and invited us to his house.
Meal being set before us, I was concerned in prayer before we ate,
and they were well affected with it;
and before we parted I had much discourse with them concerning the things of God,
and opened many things to them, as the Lord revealed them in me;
in which they were well satisfied, and very loving.

On the 27th had a pretty large meeting at Hampton; the sum of my testimony being,
as in the meeting at Salem, against a drowsy, lukewarm,
indifferent spirit which had overtaken some; with an exhortation to the old convinced,
not to rest in that condition, lest they might lose their crowns,
and become stumbling blocks in the way of the weak then under convincement.
And to the young, that they should mind the Lord alone,
and that if they should see anything amiss in anyone who professed the Truth,
either in conversation, or in meetings, whether in the vanity of the one,
or indifference of the other, or in not coming to meetings, or negligence when in them,
they should not look at the failings of others, but to the Lord for help;
to whom we must all stand or fall, and answer for ourselves, and not for another.
Though at first my concern was a little hard, we had a tender time in the melting Truth,
several, both old and young, being broken, and I went away well and easy:
blessed be the Lord forever.

Next day we went to Cachecah, to Thomas Hanson`'s, where I remained till the 30th,
which being the first of the week, I went to the meeting at Dover;
and among other things,
exhorted Friends to re-establish and continue their week-day meetings,
in which they had been deficient; and to be watchful against an indifferent, easy,
and lukewarm spirit and state: several, both Friends and others,
were tendered in the divine presence; which was mercifully with us that day,
to his own praise.

The 1st of the sixth month I had a large good meeting at Aimsbury,
in the house of one Samuel Weed, a friendly man, and many things were opened,
through the grace of God, to the satisfaction of the people in general;
but some were not pleased,
because the testimony of Truth was against their ways and sentiments;
the priest`'s son and other opposers being there.

But that which occasioned the meeting to be so large, was this:
there was one Joseph Ring, formerly mentioned, a bold, confident adversary, who,
from time to time, had challenged Friends, not only in those parts,
but also traveling Friends, to dispute with him; but being of no good fame,
they had generally declined it; upon which he had boasted greatly,
and had done much hurt to some weak persons, who had been at our meetings,
and under convincement, by perverting the Scriptures, and by unlearned questions; which,
in their weak state, they could not answer.

When I was at Hampton, as before, the Friends told me, that this man had greatly boasted,
that we dared not give him a meeting, lest our errors should appear to the people;
and so was going on in his former course,
when he thought we were gone out of the country: therefore they desired me if I was free,
to give him a meeting, for they thought it might be of service; to which,
after some consideration, I yielded,
and had sent him word of this meeting to be at Aimsbury,
so that he had full time to prepare; and into the meeting he came accordingly.
After it was ended, and before I sat down,
I inquired if there was one Joseph Ring in the place?
He started up, seeming to be surprised, and said,
"`Here am I.`" Then I called him in to the place where I stood,
and he came with his hat off, and his hands trembling.
I looked steadily upon him, but he could not look upon me.
Then I asked him, "`Are you he that wrote to one of our friends,
purporting your dissatisfaction about some things we hold in religion?`"
He answered, "`I am.`"
"`What are your objections?`"
Upon which he pulled out a paper, and read them: "`1st; Your preachers, as you say,
have an infallible spirit.
2ndly; That Christ does dwell in them: and of these things I want to be satisfied.`"
"`What satisfaction would you have?`"
"`I would have you demonstrate to me, and prove these things to be true, if you can;
for I deny them.`"
"`What demonstration or proof would you have?`"
"`From plain Scripture;`" said he, "`which I think you cannot do.`"

Seeing I had to deal with one who was not a conscientious inquirer, but a bitter,
opposer of the Truth, I further asked him,
"`Are you a member of any society of people professing Christ?
Are you a Papist, or an Episcopalian, or Presbyterian, Independent, or Baptist;
or do you represent any of these in what you do?`"
"`No; but I can hear all these, and the Quakers too,
and object against anything I like not in any of them.`"

"`But I suspect you are put upon this by some others,
who would not be seen in it themselves; be plain, tell me the truth, is it so?`"
"`No; it is only of myself, to be satisfied.`"

Then I proceeded thus:
"`I now perceive I have one to deal with who is ignorant of Christianity,
though as a seeming inquirer; I therefore begin with that point of infallibility.
People, it is necessary, in this case,
that you should clearly understand what is intended by an infallible spirit.
We do not mean a spirit, whereby to know what weather it will be tomorrow,
or the good or ill fortunes of mankind in this world, or the like;
but mean only the Spirit of Truth; that is, the Spirit of Christ, who is the Truth,
and infallibly discovers sin in men, good and evil, right and wrong,
in matters of religion; and infallibly leads into all truth, and out of all error,
in all things respecting our own salvation, as the same is received, believed in,
and obeyed.

Those who are made ministers of this spirit, by its powerful working in them,
may thereby, but not otherwise, infallibly declare the mind of God to the people,
being themselves perfectly assured by the Spirit, of the truth of what they deliver;
and yet do not pretend to impose their own sense, though infallible to themselves,
upon any others, but as they also are satisfied of the same truths by the same Spirit.
And as sure as men can distinguish and be certain of outward objects,
by the eye and light of the sun in the firmament of heaven,
so sure men may be in matters of a spiritual nature,
by the in-shining of the light of the Spirit of Christ into the understanding.
But if mankind will not fully believe and obey,
and attentively wait upon the Spirit in their hearts, they may, and do err,
both in doctrine and practice;
and this is the cause why so many and great errors are in the world.`"
And then I turned to my opponent, and queried,
"`Do you believe that the Spirit of Christ is an infallible spirit?`"

He answered, yes.
"`Well then,
since you have agreed to be determined in these points by the Holy Scriptures,
I prove the Spirit of Christ is in all Christians: and first, in his ministers;
'`At that day you shall know that I am in my Father, and you in me, and I in you.`'
And secondly, in all others; '`Now if any man have not the Spirit of Christ,
he is none of his: and if Christ be in you, the body is dead because of sin.`'
These words, '`tiny man,`' in the text, are indefinite terms, signifying every man,
male and female; I, you, he, she, they, (pointing to the people all around) all people.
And since you have confessed this is an infallible Spirit,
and the Scriptures say every man has it, as it is written,
'`The manifestation of the Spirit is given to every man to
profit withal,`' then you and I both have the Spirit of Christ,
or once had it; and if we are not infallibly led by it in the way of Truth,
we have not profiled, and it is our own fault and loss.`"

This much weakened him as to that point, for he could not get over these Scriptures,
yet would have been at another argument, which he could not form,
for the disorder and confusion he was in.
It was this: "`None who deny the ordinances of Christ can be led by the Spirit of Christ:
but the Quakers deny the ordinances of Christ; that is, they do not baptize with water,
therefore are not guided by his Spirit.`"
This not being fairly stated by him, but by myself,
in order to an answer before the people, I presently followed it with this:
"`That what he meant by baptism was sprinkling of infants, which Christ never instituted;
therefore we may omit it, and yet be led by the Spirit of Christ into that omission,
as a testimony for him against it.
And that he would unchristian all the people there, and himself too,
and likewise nearly all who profess Christ at this day throughout the world;
for none are in the practice of water baptism but a few called Baptists;
who only imitate John`'s baptism as nearly as they can,
and that by their own assumption and authority,
without any mission by Christ on that account.

The sprinkling of infants I maintained to be only a Popish innovation and institution,
and no ordinance of Christ, as I had before more fully opened it in the meeting;
and added, that we do not deny,
but believe that water baptism was commanded of God to John the Baptist,
and practiced upon the Jews only, as an ordinance of God, in its dispensation of time,
place, and subjects; but that it is superceded, and in point of obligation, ended,
by the institution and introduction of Christ`'s spiritual baptism with the Holy Ghost:
and there is now remaining in the church of Christ only '`one Lord, one faith,
and one baptism;`' for by one Spirit are we all baptized into one body,
and have all been made to drink into one spirit.
For the body is not one member but many.
The church, which is his body; the fulness of him that fills all in all.
And therefore his imagination, that we could not be led by the Spirit of Christ,
for omitting the sprinkling of infants, is unreasonable, and not a just consequence.`"

By this time he was weary of his undertaking,
and silent as to any further argument on the first point;
and so we proceeded to the other, namely: That Christ dwells in his people.

To prove the absurdity, as he thought, of this,
he brought that Scripture where Thomas and the apostles doubting of
the bodily appearance of Christ after his resurrection,
the Lord said to them, "`A spirit has not flesh and bones as you see me have.`"
"`Now,`" said he, "`since Christ has flesh and bones, as we have,
how can he be in every one of you?

Upon this I desired the people to be still, and told them, "`This man`'s imagination,
concerning Christ`'s being in his people is very gross, carnal, and foolish,
and not at all as we understand it;
for we speak of the light and spirit of Christ
in the sense mentioned in the other argument,
and not of his human body.
But as the body of the sun is at a great distance, in the open firmament,
yet his light and influence shines over and affects all the earth,
and into many thousands of houses and places at the same time;
and in what proportion the light shines into any house,
by the same proportion is the virtue, influence, and power of the sun there dispensed;
so, and infinitely more, it is with Christ; whose holy body, though far remote from us,
yet his Spirit is every where, in all hearts;
and he is the "`Word of God,`" and "`true light,
that enlightens every man that comes into the world.`"
The mystery which has been hid from awes and generations,
but now is made manifest to his saints:
to whom God would make known what is the riches
of the glory of this mystery among the Gentiles,
(whose offspring we are) which is, "`Christ in you, the hope of glory.`"

"`But I have something more to say of Christ`'s being in men.
It is no new thing for perverse men to oppose the Truth;
and no wonder it falls thus to our lot now,
since the like objection was moved to the apostle Paul, and by such too as had sinned,
seeking a proof of Christ`'s speaking in him;
and all the proof he thought fit to give them was,
to bid them examine themselves whether they were in the faith; prove your ownselves:
know you not your ownselves, how that Jesus Christ is in you,
except you be reprobates.`"

My adversary quickly turned to the place, and I bid him read it to the people,
and then said to him, "`You are the man seeking a proof of Christ being in us.
Have you examined yourself on that account?`"
"`Yes.
Have you proved yourself?
Yes. What have you found?`"
Then he, perceiving what the conclusion was like to be, would have evaded and shuffled.
"`No, but,`" said I, "`give me a plain and positive answer;
have you found Christ in you?`"
But he would not answer.
Then I observed to the people, "`He confesses, you see,
that he has examined and proved himself, but dares not say he has found Christ in him,
therefore the text is conclusive upon him, he is a reprobate; and as such,
I set him aside, as not worthy to be talked with any more in matters of Christianity.`"
He said no more, but soon after slunk away out of the company.
This struck an awe upon the people; for the Lord was with me, and was my director,
to his own glory; and presently came to me a young man, in a consternation, and said,
"`Ah, sir I would not have been before you today, as that man was,
for the whole world.`"

Immediately upon this came another sober young man to me, and said,
"`I have heard what you said this day in the meeting; and many things I liked,
which you explained beyond what I ever heard from any of your persuasion;
but one thing I am not satisfied in; that which you call spiritual, I call natural.`"
"`What is that?`"
said I. "`You said, that which reproves sin in mankind is sufficient for salvation,
provided it be believed in and obeyed; which I cannot receive.
For that Scripture which you mentioned will be against you; where you said,
'`When the Gentiles, which have not a law, do, by nature, the things contained in the law;
these, having not the law, are a law unto themselves;
which show the work of the law written in their hearts.`'
Now,`" said he, "`that which reproves sin, the Gentiles had before Christ came,
even from the beginning: how then can that be the Spirit of Christ, but only the law,
the same that reproves men now?
It is the remains of that righteousness that was in Adam, in his state of creation,
before he fell.`"

I answered,
"`That if he rightly considered that righteousness which was in Adam before he fell,
it is the same that the saints and people of God now have,
after they are restored out of the fall.
The better to understand this,
let us observe what John the Evangelist says concerning Christ the Word of God:
'`In the beginning was the Word, and the Word was with God, and the Word was God.
In him was life, and the life was the light of men.
And the light shines in darkness, and the darkness comprehended it not.
That was the true light, which enlightens every man that comes into the world.
And the Word was made flesh and dwelt among us, and we beheld his glory,
the glory as of the only begotten of the Father, full of grace and truth.
And of his fulness have we all received, and grace for grace.
For the law was given by Moses, but grace and truth came by Jesus Christ.`"

The Word, Wisdom and Power of God therefore,
clothed and veiled with a reasonable soul and human flesh, is Jesus Christ,
born into this world by the blessed Virgin Mary.
This Word is the righteousness of God, which was light and wisdom in Adam before he fell;
and by whom God judged and condemned Adam for sin,
in disobeying and departing from this Word, light and life,
through unbelief and actual transgression.
It was by the light and life of this Word, that God, the Father of all,
strove with the old world to reclaim them, as by a law written in them,
and against which they likewise rebelled;
whereby the Almighty was provoked at length to destroy them by the flood,
save righteous Noah, who had not offended, and his family.

"`And after the flood the same law of light and life was still
with and in the posterity of Noah and his family,
by which they had the knowledge of God, of the creation, and of moral righteousness;
and being obedient, they were ruled and governed thereby for a time.
It was by this divine nature in their hearts,
and not by their own fallen and corrupt nature,
that they did the things contained in the moral law;
but by degrees they likewise degenerated, as the old world did,
and departed from the law of light which gave them that knowledge; '`Because,
that when they knew God, they glorified him not as God; neither were thankful,
but became vain in their imaginations,
and (departing from that light) their foolish
hearts were darkened;`' and they became darkness.

"`Departing from the wisdom of this divine Word, they became fools and vile idolators;
and therefore God departed from them, and '`gave them up to their own hearts`' lusts,
and to believe and follow lies, and vile affections.
And even as they did not like to retain God in their knowledge,
God gave them up to a reprobate mind, to do those things which are not convenient;
being filled with all unrighteousness, fornication, wickedness, covetousness,
maliciousness, full of envy, murder, debate, deceit, malignity, whisperers, backbiters,
haters of God, despiteful, proud, boasters, inventors of evil things,
disobedient to parents, without understanding, covenant breakers,
without natural affection, implacable, unmerciful.`'
And though they knew at the same time, by that law of light,
that the judgment of God was against them for these things; yet they did them,
and took pleasure one in another therein.
And therefore God left them under the power of their own sins, in this miserable state,
for many ages.

"`In the mean time, God made choice of Abraham and his posterity,
in whom to restore this law of light and life.
For the children of Israel being in bondage, and a state of slavery in Egypt,
were also degenerated and become transgressors;
and therefore God added the law of moral righteousness, by the mediation of Moses,
his servant, written on tables of stone by the finger of God; which,
for the transgressions of the people, were broken by the mediator of that law,
on the side of the mountain before which they were.
But the mercy of God returned unto them,
and he commanded Moses to prepare other tables of stone, on which to write the same law:
which thing, though matter of fact, is also an allegory.
For the law of light and life being written in the hearts of men from the beginning,
was broken and blotted out by their sins; but the Most High,
in love and mercy to lost and degenerate mankind,
provided a more excellent mediator than Moses, and of a better and more powerful law,
which I may further speak of in the sequel.
Though this law was given by Moses, by the command of God,
and the people received it as reasonable and good, yet,
being inwardly departed from the light and life of the divine Word,
that outward law could not give them life, but condemnation;
for they could not keep it in the state they were in: and therefore the Almighty,
in justice and mercy, restored to them a manifestation of the same Word,
and light and life in him.
This is the eternal Word and commandment of God preached by
Moses in that day unto Israel in the wilderness,
of whom he says, '`This commandment which I command you this day,
it is not hidden from you; neither is it far off: it is not in heaven,
that you should say.
Who shall go up for us to heaven, and bring it unto us, that we may hear it and do it?
Neither is it beyond the sea, that you should say, Who shall go over the sea for us,
and bring it unto us, that we may hear it, and do it.`'
But the Word is very nigh unto you, in your mouth, and in your heart,
that you may do it.`'

"`In this manner was Christ preached by Moses many ages before he came in the flesh;
and after he did so come, was preached in the same way by the apostle Paul;
for the same that Moses preached as the Commandment, and the Word,
the apostle calls Christ, and the Word of faith, whom they preached,
and whom they knew no more after the flesh,
after they had thoroughly preached him come in the flesh; but consequently,
as he is the '`Word of God, Light of the world, divine Truth, and quickening Spirit.`'

"`And again, '`All Israel did eat the same spiritual meat,
and did all drink the same spiritual drink,
for they drank of that spiritual Rock that followed them, and that Rock was Christ.`'
And this is also the same of which he speaks, where he says,
'`Whosoever drinks of the water that I shall give him, shall never thirst;
but the water that I shall give him,
shall be in him a well of water springing up into everlasting life.`'

"`And to make this necessary point yet plainer, observe, '`In the last day,
that great day of the feast, Jesus stood and cried, saying, If any man thirst,
let him come unto me, and drink.
He that believes on me, as the Scripture has said,
out of his belly shall flow rivers of living water.
But this spoke he of the Spirit, which they that believe on him should receive:
for the Holy Ghost was not yet given; because that Jesus was not yet glorified.`'

"`But the Jews also rebelled against the Light, Spirit and Word of God,
so preached unto them by Moses aforesaid;
and therefore the law without could not save them:
yet the righteous and most merciful Creator did not forsake them forever,
but opened a door of hope, by his gracious promises aforehand,
that they might believe and obey when they came to pass; and therefore says,
'`Behold the days come, says the Lord,
that I will make a new covenant with the house of Israel, and with the house of Judah;
but this shall be the covenant, I will put my law in their inward parts,
and write it in their hearts, and will be their God, and they shall be my people.`'
Again; I will put my fear in their hearts, that they shall not depart from me.

"`The Almighty, of his abounding mercy and kindness,
remembered likewise the apostate and benighted Gentiles,
promising unto them also the same law and covenant of Light, by the same Mediator;
'`I the Lord have called you in righteousness, and will hold your hand, and will keep you,
and give you for a covenant of the people, for a light of the Gentiles.`'
And he said, '`It is a light thing that you should be my servant,
to raise up the tribes of Jacob, and to restore the preserved of Israel;
I will also give you for a light of the Gentiles,
that you may be my salvation unto the end of the earth.`'

"`This covenant, and the messenger thereof is the same,
whom the Most High describes aforehand; '`to the Jew first, and also to the Gentile.`'
To the Jew he says, '`Therefore the Lord himself shall give you a sign: behold,
a virgin shall conceive, and bear a son, and shall call his name Immanuel.`'
And to both Jews and Gentiles he says, '`Behold my servant whom I uphold, mine elect,
in whom my soul delights.
I have put my Spirit upon him, he shall bring forth judgment to the Gentiles.`'
This is he, of whom it was said, seven hundred and forty years before he came,
'`Unto us a child is born, unto us a son is given,
and the government shall be upon his shoulder.`'
This is he who spoke unto the Father in Spirit, saying,
'`Sacrifice and offering you wouldest not; but a body have you prepared me.`'
This is he who received that holy body of human flesh, with a reasonable soul,
the complete nature of man.
This is the Lord Jesus Christ, born of the Virgin Mary: who, by command of the Father,
wrought all those wonders attributed to him in the holy Scriptures.

"`This is he who offered himself upon the cross, at Jerusalem of old,
'`a propitiation for the sins of the whole world.`'
This is the Light of the Gentiles, in whom they are to believe and trust.
The Mediator of the new covenant, not of works, but of light and life from God;
not that which is natural, but eternal.
This is the true witness of God; the finger and power of God,
by which he writes and restores the law of righteousness; the law of the Spirit of life,
which makes free from the law of sin and death, and which the law without,
given by Moses, could not do.
This is the Law and Word of Life that was in Adam before he fell.

"`This is the divine, immortal, and unchangeable truth of God,
which '`reproves the world of sin, of righteousness,
and of judgment;`' that reproves and manifests sin in all mankind: and for lack of faith,
love, and obedience to this divine Law, Light, and Word of God,
the faithless and disobedient world remains in condemnation by that Word.
For, till they do so, both Jews and Gentiles remain and are concluded under sin:
as says the Son of God, '`He that believes on him is not condemned;
but he that believes not is condemned already,
because he has not believed in the name of the only begotten Son of God.
And this is the condemnation, that light is come into the world,
and men loved darkness rather than light, because their deeds were evil.
He that believes on the Son has everlasting life; and he that believes not the Son,
shall not see life; but the wrath of God abides on him.`'

"`As the mystery of iniquity began to work in the days of the apostles,
so there were many antichrists, even then, in the world,
who were neither Jews nor heathens, but professors of the name of the true God,
and of Jesus Christ the Son of God, and Savior of the world;
and they went out from the apostles and their doctrine,
and from the teaching of the grace and Spirit of God;
the holy anointing which teaches all things.
They turned their ears from the Truth, and gave ear to fables;
heaping to themselves teachers after their hearts`' lusts, having itching ears:
they went back under the law of types, which was ended by the law of liberty,
through Christ Jesus our Lord.

"`And as great is the mystery of iniquity, it has so wrought in the Christian world,
that the same that is so called, is degenerated as the old world,
and as the old Gentiles, the heathen and apostate Jews, and become anti-christian,
and in utter darkness and confusion.
They once, in the days of old, spoke one language from the one Word and voice of God,
speaking divine wisdom, and the knowledge of the one true God,
and of Jesus Christ the Son of God, in every living soul.
But, by their apostasy from the divine light and Spirit of God, and from his wisdom,
grace, and power, they followed their own spirit and wisdom, which is darkness,
into many evil inventions; and multiplied their superstitions,
and became miserable idolators, worshipping a piece of bread for their God,
and wallowing in all the sins of the Gentiles and heathens of old.
So that their language, as at Babel, is confounded, and they are no more one,
but scattered, and shall unite no more,
till they return by him from whom they are fallen; to the covenant of God,
even that true light of his Son,
'`which enlightens every man that comes into the world;`' of whose fullness,
all those who now believe in him, and behold his glory,
as of the only and first begotten Son of God, have now received, as they did of old,
and grace for grace.
'`This grace brings salvation, and has appeared to all men; teaching us,
that denying ungodliness and worldly lusts, we should live soberly,
righteously and godly in this present world.
By this grace we are saved, through faith, and that not of ourselves,
it is the gift of God.`'
From all which proofs it is plain,
that the same that reproves sin in man is the Spirit of Christ, the Word of God,
which in the beginning was the light of men; and it is not natural, but spiritual,
and the mystery that lay hid in the Gentiles from the foundation of the world,
though they were darkness, and this light had not been comprehended by them.`"

During the time that passed on these subjects, the people were very sober,
and the young man, being deeply under the effects of a wrong education and tradition,
replied, "`faith in this light cannot be sufficient; '`for, except a man be born again,
he cannot see the kingdom of heaven.`'`"

"`That is true; but seeing we must be born again, we cannot do that of ourselves;
there is none can do it for us but God.
And he does that great work by the word of his wisdom and power, which is Christ,
the light of the intellectual world; the Sun of righteousness,
and glorious luminary of the mind.

And we are to believe in him, that we may be corn again of him, who is the second Adam,
the Lord from heaven, the quickening Spirit; as it is written, '`While you have light,
believe in the light, that you may be children of the light.`'
"`'`And if children, then heirs, heirs of God, and joint heirs with Christ.`'
But it reasonably follows, that if no faith in this divine light,
then no children of God through him who is that light, and elect seed of God;
and if not children, then not heirs of God, nor of his promises,
which are all unto this divine Seed, and all true in him.
And if we do not believe in the Word of God, we cannot please him,
or be created anew unto good works by him; which are indispensable to every child of God,
as the evidence of that faith, and work of regeneration in the mind;
'`and to be carnally minded is death, but to be spiritually minded is life and peace,
through Jesus Christ our Lord.`'

"`Christ testifies of himself,
that he is '`the light of the world;`' and the apostles of Christ were sent by him,
to testify that God is light, and to turn mankind '`from darkness to that light;
from the power of satan unto God;`' from that darkness
and ignorance which had covered the earth,
and from that gross darkness which had covered the people, unto the Son of God,
and unto the Father by him.

"`So then, in order to our being born from above, there must first be faith in Christ,
as he is the divine Light, and second covenant of God:
and the first work of this light in man toward that faith, is the manifestation, reproof,
and condemnation of sin in the heart, mind, and understanding of man:
'`For all things that are reproved are made manifest by the light;
for (after the manner of men) whatsoever does make manifest is light.`'

"`Thus the testimony of the holy Scriptures concur
clearly to the proof of this most needful doctrine,
That the reprover of sin in the mind and understanding of man, is not man himself;
neither is it the evil one, who tempts man to sin.
For then he would be both tempter and reprover, and divided against himself;
and even that way, his kingdom and power could not stand.
But it is the divine light and spirit of Christ, that sin may be manifested, reproved,
become exceeding sinful and be condemned,
and through faith in the Manifester and Reprover, be forsaken, pardoned, remitted,
and by the work of the Holy Spirit of Christ, fully removed,
and the minds of mankind purified, and made lucid as the day,
and formed into light in the Lord.`"

In the conclusion of this I felt the weight removed from off my spirit,
and the love and goodness of Truth to arise towards the young man,
and he took me kindly by the hand, and said, he had other points to discourse,
but would now leave them.
But I believe the main objection was removed, and the mark hit, for he departed cheerful;
and some others also who seemed to have had something to say,
when they had heard these things, were silent, and all ended in peace,
to the glory of the Lord, whose service and honor, and common good of mankind,
through the grace of God, we only aim at in all these things.

The meeting being over, there came a woman, being introduced by some women Friends,
and told me she was much troubled with a spirit of blasphemy,
which often uttered in her blasphemies against God; and that she was vexed with it,
and abhorred herself because thereof; though she no way, in her desires,
assented thereto.
I replied, that the Lord often allowed such to be tempted,
in whom he purposed to make known his power; but it is no sin to be tempted,
for Christ was tempted, and yet without sin; but satan`'s end in these great blasphemies,
which were of his own uttering in her imagination, was this,
that when he had wearied and weakened her,
he would try to make her believe she had sinned against God, and so bring her to despair.
But I exhorted her to be still, resist him in faith towards Christ,
and not join with him, and he would vanish; and she went away easy.

It being late before all these things were ended,
I went only one mile from the place that evening,
and next day had a meeting at the house of Joseph Paisley, in Haverhill.
It was not large, by reason of the throng of harvest;
but a very good time the Lord afforded us, and we were comforted together in him,
several of the young convinced, and some of the elder Friends from Salisbury being there;
and next day, being the fifth of the week, I went to Lynn,
and lodged with Samuel Collins, where I was kindly entertained.

I heard in this country,
that one part of the scheme of religion invented by the
preachers among the Presbyterians and Independents,
is.
That a preacher, unprovided with a living, or wanting a better,
goes and preaches a sermon, or more,
to the people he would beget into a good opinion of himself; and if they like him,
he must first have a call from that people to whom he has preached,
before he can be their settled minister.
The meaning of which is,
that he may have an opportunity to bargain for so much a year as they can agree upon,
before he will obey their call, so as to be their settled preacher;
and when the price is fixed, the leading elders give him security for payment,
and they raise it by subscription.

But the preachers in that country being dry and formal,
and the people cold in their love, many townships were silent,
and no voice of calling was heard from them; so that the preachers multiplying,
and many of them wanting employment and maintenance,
they and their friends influenced the Legislature to make a law,
"`That the inhabitants of each town within that
province should be provided with at least one able,
learned, orthodox minister, to dispense the word of God to them;
which minister shall be suitably encouraged,
and sufficiently supported and maintained by the inhabitants of such town;
with provision for levying proportionable rates upon such as should refuse to pay,`" etc.

Pursuant to this law, the towns which had no ministers,
made choice of some by votes of the inhabitants;
yet others looking upon it as an imposition on them, contrary to their religious liberty,
in calling or not calling any minister, eluded the force of it,
by nominating several of our ministering Friends,
and returning their names as the choice of the people.
They were answered, "`These were not ministers in the intent of the law.`"
It was replied, "`'`they were the people`'s choice, and such as the law required;
they were able, learned, and orthodox ministers of the gospel,
and would appear to be so upon proper examination; and they could not return any other.`"
The Friends thus chosen by the people, did some times visit them,
and had meetings among them, as they found liberty in the Truth,
and were very acceptable in that service; which they did freely,
without any view to maintenance or filthy lucre.
By this law.
Friends fell under sufferings,
their goods being distrained and forced from them to
maintain a false ministry they could not own;
the testimony of God bearing witness against them in their enlightened understandings.
And several Friends being under sufferings at this time on that account,
Samuel Collins went with me to Boston, where we made application to Lord Belmont,
then governor of the country, for relief, and were very favorably received,
and our request granted; so far as it was in his power we had relief,
by discouraging that practice.

I had a pretty large meeting at Lynn, and the next day went to Boston, where,
notice being given, I had two meetings on the first of the week;
the former of which was small, but the latter, being in the evening, was very large,
and the truths of the gospel opened clearly, the Lord`'s power being with me.
Some were tendered, though but a few Friends inhabited there at that time.
On the 7th I went to Scituate, and on the 10th had a pretty large meeting;
the day following I rode thirty miles, near to Sandwich,
and hearing that my companion was to have a meeting next day at Dartmouth,
about thirty-five miles off, after some concern and consideration,
I resolved to go there.
Accordingly, in the morning, about the break of day we set forward,
and arrived at John Tucker`'s, three miles from the meeting-house,
about half an hour after the ninth hour.
Here we rested a little, and then went to the meeting,
and were there before my companion; who, when he came, was glad to see me,
for the meeting was large, and he had almost lost his voice by a great cold.
The beginning of the meeting fell to my lot, and my companion afterwards had a good time;
though at first his voice could scarcely be heard over the meeting,
yet mended by exercise, and the Lord favored us with a good season.

On the 10th we went to Gideon Freeborn`'s, on Rhode Island,
where we met with Samuel Jennings, and there lodged that night.
The next day being the first of the week, I went to the meeting at Portsmouth,
in that island, and they went to Second,
to a meeting they had appointed some days before.
The meeting I was at was large; but during the forepart thereof,
I was much burdened by the unconcernedness of many.
The generality of people in those parts come to meetings, there being no others near,
and being persuaded notionally of the truth of our doctrines,
and yet not living in the life of Truth,
are rather worse to meet among than such as never heard the testimony of Truth;
but having these two points, baptism and the supper, given me to speak to,
I had a good meeting, though it was some time before I got through that idle, drowsy,
lukewarm spirit, by exposing and reproving it in the forepart of the meeting.
But things ended well.

On the 12th went to Newport, and had a large and good meeting there,
and tarried in town till the next morning, and then took boat for Conanicut island.
But the wind being high, the waves were great in the channel;
so that the vessel pitching against them, some of them broke over us,
and one of our horses was thrown down, and the rest much disordered;
and the water coming over the side of the vessel,
the man at the helm bore away to the leeward, and presently we were in a safer condition,
taking another landing than at first we aimed at.

Being on the shore we took horse, and went to our friend John Hull`'s;
and the wind continuing high, and the sea raging,
we went to see what we could do to get over the water to a meeting,
which had been appointed for us at Greenwich, in Narraganset,
about five miles on the other side.
I came to a conclusion to go, and my companion and Samuel Jennings staid behind,
and though the waves ran high,
which gave us great difficulty to get our horses into the boat;
yet we had a good passage about four miles over, and went to the meeting,
the public service of which falling to my lot,
the Lord opened many things in me for the information of the people,
about the fall of man in the first Adam,
and rising again by faith and obedience to Christ, the second Adam, and about baptism,
church fellowship, etc., and I heard of nothing but a general satisfaction.

On the 14th my companion and Samuel Jennings coming to us,
we had a large meeting at William Gardner`'s, at Kingston;
from which we went on our way to Narraganset,
and next morning set forward on a long journey, through the colony ofConnecticut,
in which there was not one Friend.
That evening we reached New London, and lodged at an inn:
and soon after we alighted we asked the landlord whether he
would let us have a room for a meeting the next day;
which he readily granted in words;
and told us that he and his servant should
assist us in anything that might facilitate it,
but he proved deceitful.

The governor of the colony having his residence there, and hearing of us,
sent for one of us in the morning to speak with him, and we all went to wait upon him;
and after he had saluted us in his way, with much civility, he began and told us,
he had been at our meetings in the city of London,
and observed how peaceably they were held, and that none molested them;
and that he thought it was not well for any one sort of
people to disturb another in their worship, etc.
By which we perceived he, and the preacher of the place and inhabitants,
suspected that we purposed to be at their meeting the first-day following, having,
we conjectured, heard what we had done before at Fairfield; but in this he mistook.
When I perceived what he aimed at, I said,
"`It might seem strange and unreasonable to such as could see
no otherwise than by the common and natural faculties of men,
for any to come into the assemblies of others,
and interrupt them in the act of their worship, or what they called so;
and we were always cautious to give as little offense that way as might be.
But to go to hear any, and be still till they have done,
and then make reasonable and Christian objections, if any arise, cannot be hurtful,
if the objectors are conscientious in what they do, and do not oppose out of humor,
or for opposition`'s sake, but for the information of mankind,
in anything wherein they have been in an error.
The apostles, in their day, though charged as turners of the world upside down,
usually went to the synagogues of the Jews, and some public places of others,
and both disputed and taught, contrary to both Jews and heathens;
and the Lord is the same still, and may influence his servants now to the like practice,
when and where it may please him.`"

Then Samuel Jennings gave him a hint that we purposed
to stay in town till after the first-day,
in order to clear the truth of those false
suggestions which had been cast upon it and us,
as well here as in other places.
But though we had no intention to go to their meeting,
yet not knowing how we might afterwards be engaged, we did not resolve him in that point,
or lay ourselves under any restriction; but departed with civil respect on all sides,
according to our different ways of expressing it.

Our deceitful landlord tarried behind with the governor, and we saw him no more that day;
and notwithstanding his promises,
we could not have so much favor from him as a boy to
give notice in the town of a meeting at our quarters,
but sent our friend, Rowland Robinson, who came with us from Narraganset.

About the fourth hour in the evening came John Rogers and his disciples,
and some other people; but the meeting was small,
the people being extremely in bondage in those parts to
the ministers of their own calling and maintaining;
and yet pretty many came to the windows and doors in the dusk of the evening,
and the blessed power of the Lord was with us;
and John Rogers and his friends were well satisfied, and parted friendly with us,
declaring their sense of the divine presence among us;
some of them having been tendered in the meeting.
After all was over, our landlord came fawning again,
having as many fair and deceitful words as before; but we took little notice of him.

The next day we went on to Killingsworth;
where I and my companion had had discourse with some persons as we went into New England;
and were scarcely now alighted till our landlord began to tell us,
"`That he had reported to their minister what had then been discoursed;
and that he inclined to confer with us on the same things,
if we should happen to return that way;
and asked if we were willing to go speak with him on that account?`"

We gave our landlord this answer, "`That we were then weary;
but if their minister would call his people
together in the morning to their meeting-house,
we would there meet him at the ninth hour:`" which, when he heard, he began to flag,
and said,
"`He would not send him that word unless we would write
it:`" and accordingly I wrote to their minister thus:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Killingsworth, 21st Sixth month, 1699.

[.salutation]
Friend Abraham Pearson,

Forasmuch as some of us, the people called in scorn, Quakers,
passing this way some time ago, and lodging at the sign of the Hart,
here in Killingsworth, the landlord, with other persons, perceiving what we were,
moved some discourse concerning certain points respecting the Christian religion, namely:
freedom from sin in this life, and baptism; and they not being able, as we thought,
to resist the Scriptures and arguments we urged against them,
in defense of what we hold therein, I think our landlord, if not also some of the rest,
told us, that though they could not,
yet their minister--meaning yourself--was able to confute the errors,
as they called them, which we hold therein.
Whereupon we, or one of us replied, that if their minister would convene his people,
or a competent number of the more discreet of them, we would meet him,
to hear and answer his arguments against us in
those points wherein we differ from him and them.
And we returning this way this evening, lodge at the same inn,
and are willing to defend the principles and doctrines we hold,
and to meet you tomorrow morning, about the ninth hour, at your meeting-house,
provided your sober neighbors and people be there convened.
In the mean time, desiring your speedy answer, we remain your loving friends.

[.signed-section-closing]
Signed on behalf of myself and the other two, by

[.signed-section-signature]
Thomas Story.

--

This being sent him, he returned this verbal answer:
"`That we should be welcome to his house, or he would come to our inn;
but thought the meeting-house not convenient.`"
In the morning, about the eighth hour, he came to our quarters;
and being seated in a chair when we were absent, I coming in before my companion,
sat down by him; and after an interchange of some civilities,
in our different ways of expression, and a pause of silence,
he took out the letter and began to move about the contents of it, namely:
freedom from sin in this life, and baptism; the points proposed to be conferred upon.

In the first place I asked him a previous question, namely:
"`Whether he appeared there as a minister of Christ,
or only as a minister to a particular people there?`"
Perceiving I would put him upon his proof if he came as a minister of Christ,
he evaded that and moved the other, about a sinless state in this life;
and in the mean time came in Samuel Jennings and my companion Roger Gill,
the Presbyterian minister having several of his hearers with him;
and all the people in those parts were generally of that sect.
Then I moved for a statement of the first question in writing; which was settled thus:

"`Whether it be an error from the doctrine of Christ and his apostles,
to believe that mankind may be free from sin while living in this world,
or on this side the grave?

"`Abraham Pearson assumes to prove it is an error,
from the doctrine of Christ and his apostles,
to believe that men may be free from sin while living in this world,
or on this side the grave.`"

The first question thus stated and agreed upon, he began his proof after this manner:
"`That which God has not, at any time, promised unto man,
we have no ground to believe is attainable by man; but God has not, at any time,
promised that men shall be free from sin in this life;
therefore we ought not to look for it.`"

I replied, "`The question is not what God has promised, or not promised;
but whether it be an error, from the doctrine of Christ and his apostles,
to believe that mankind can be free from sin in this life, or on this side the grave?
And you have assumed upon yourself to prove that it is such an error so to believe;
which your assertion, namely: that God has not so promised, etc.,
does not at all prove.`"

"`No, said he, but you shall not draw me from my argument, and run away to other things,
as your manner is; I will hold to my point,
till you prove that ever God promised to make men free from sin in this life.`"

I returned, "`I am not going from any point in question;
nor have I said that God never promised so.
But you have assumed, in the first place,
to prove it is an error to believe as is slated in the question; and now,
in the second place, asserted negatively, that God never promised such a freedom.
I insist therefore upon your proof of your assumption in the question,
and of your assertion that God never so promised:
for your asserting the same thing twice over in different terms is no proof;
so that you are still to be held to your first point.`"

Then he brought forth his Scriptures for sin term of life:
"`For there is not a just man upon the earth that does good and sins not.`"

I answered, "`This was written in the time of the law, and must intend a legal justice,
as by the '`Works of the law shall no flesh be justified.`'
But to be evangelically just is another thing;
they are sanctified through faith in Christ Jesus,
and by him also they are justified and saved from their sins,
'`by the washing of regeneration, and renewing of the Holy Ghost.`'`"

Then he advanced their common plea for sin term of life,
as being written in the time of the gospel, namely: "`If we say we have no sin,
we deceive ourselves, and the truth is not in us;`" and there he slopped.

I replied, "`That the apostle began there with men in their natural state,
as children of the first Adam, and says, '`If we say we have no sin, we deceive ourselves,
and the truth is not in us.
If we say we have not sinned, we make him a liar, and his word is not in us.`'
But though we have sinned, must we continue therein?
No; for '`if we confess our sins,`' to Him who convinces us of them in our own hearts,
'`he is faithful and just to forgive us our sins,
and to cleanse us from all unrighteousness.`' '`And if we walk in the light, as he is in the light, (that is, in God, verse 5.
) we have fellowship one with another,
and the blood of Jesus Christ the Son of God cleanses us from all sin.
And he that says he abides in him, ought himself also so to walk,
even as he walked;`' which cannot be in sin: for he never sinned,
nor was ever any sin in him; and he is separate from sinners.
The sins of the little children are forgiven for his name`'s sake.
The fathers have known him who is from the beginning: And the young men are strong,
and the word of God abides in them, and they have overcome the wicked one.
'`Whosoever abides in him sins not; whosoever sins, has not seen him, neither known him.
He that commits sin is of the devil; for the devil sins from the beginning.
For this purpose the Son of God was manifested,
that he might destroy the works of the devil.`'

"`'`Except a man be born again he cannot see the kingdom of God:
and whosoever is born of God, does not commit sin;
for his seed (the word of God) remains in him, and he cannot sin,
because he is born of God.`'
And as he is, so are we in this world; and if so, then not in sin.

"`Again, the apostle Paul in his Epistle to the Romans, preaches the same doctrine:
he first proves both Jews and Gentiles all under sin once, and if they had not sinned,
there had not been any need of a Savior to save them from their sins;
and then preaches salvation both to Jews and Gentiles by Christ,
and freedom from sin by him, even in this life; where he says, '`What shall we say then?
Shall we continue in sin, that grace may abound?
God forbid: How shall we that are dead to sin, live any longer therein?
Being then made free from sin, you became the servants of righteousness;
for when you were servants of sin you were free from righteousness,
but now being made free from sin and become servants of God,
you have your fruit unto holiness, and the end everlasting life.`'
'`But if we go on in sin, we shall die in our sins; and if we die in our sins,
where he is gone we cannot come.`'
'`But the law of the Spirit of life in Christ Jesus,`' says the apostle,
personating every true member of the church of Christ,
'`has made me free from the law of sin and death.`'
A glorious liberty indeed!`"

Then said the priest, "`Yes, that is true, we are to be made free from sin,
but not in this life.`"
Then Samuel Jennings asked the priest, since he had acknowledged a freedom from sin,
but not in this life, "`When, where, and how must it be effected,
since '`no unclean thing can enter the kingdom?`'
"`To which he replied, "`We are driven to a necessity to confess,
it is not done in heaven, and in this life it cannot be;
therefore it must be at the very point of death, as the soul departs from the body.`"

"`Well then,`" said I, "`let us see you split a hair,
and show what distance there is between the utmost
point of time and the beginning of eternity.
For if done in the last point of time, it is in this life;
and if not till its entrance into eternity, then the unclean thing enters the kingdom,
which is already granted cannot be.
Where then is this freedom?`"
Which question Samuel Jennings pressing upon him, he then affirmed,
"`The soul is cleansed from sin in its way between earth and heaven;
for there is,`" said he, "`a considerable space between.`"
Then said Samuel Jennings, "`This is such a purgatory as I never heard of before.`"
And though the preacher had hitherto seemed to have command of his passion,
yet upon this he grew very angry; for we then exposed him to his own people.

If the soul is freed from sin after it departs from the body,
in its ascending from earth to heaven,
speaking in an outward sense according to his apprehension, it is still in time.
Being reduced to this condition before his people, he then began to accuse us falsely;
and having his members now pretty well fitted to his evil purpose, to laugh,
setting his rustics to mock us,
and said he would tell us a story of a merchant in London,
intending thereby to raise levity, and so take off all sense of what had been said,
for there were several of the people very sober and attentive all the time.
But I sharply reproved him, and said, that he manifested himself, to all that had eyes,
in a thing ill becoming his grey hairs, and much worse his profession,
and least of all the matter in hand, touching the everlasting life or death of mankind.
This utterly suppressed his jest; and then I summed up the whole matter in short,
and noted to the people, "`That touching this point he had undertaken to prove, namely:
that freedom from sin in this life is inconsistent with
the doctrine of Christ and his apostles,
but could not; and we had adduced several plain, applicable,
and unanswerable texts of Scripture, proving that freedom from sin in this life,
is the doctrine of Christ and his apostles, and had left the truth over his head.`"

By this time it was about mid-day, and we were willing to depart,
and our antagonist as desirous we should, for he sweated much, and often sighed deeply;
which gave me occasion to think he argued against his own understanding.
Yet we had a short touch on baptism, or rather rantism,
for I held him to sprinkling infants; which, though no baptism,
yet being their practice instead of baptism, they must be determined by it.

The next day we went on to Milford, Stratford, and Fairfield,
and there we alighted at an inn, the house of one Burr; where, after some refreshment,
we requested the liberty of his house for a meeting-place, but could not obtain it,
he being an old, zealous, or cowardly Independent or Presbyterian; for in those parts,
though many could be willing to hear Friends,
yet such is the bondage they are in to their ministers, elders, magistrates,
and one to another, that they dare not attempt it in the day-time.

We took horse on that evening, and went again to Norwalk and lodged.
As we went to this place, we fell in with a neighboring man,
who told us that many of the people were much
dissatisfied with the measure we met with at Fairfield,
in being hindered to speak to them, seeing we had not interrupted their minister,
nor offered to speak till their service was over: that the priest of Fairfield,
next sabbath day, as he called it, took his text in 2 Tim. 3:5, From such turn away;
upon which some of the people said among themselves,
their minister could now talk much against the Quakers behind their backs,
but face to face, had very little to say.
And some of them told him,
that the Quakers made seven of them together say and own what they pleased;
and that some of the people had been wishing our return.

In the morning we went on to Horseneck, where we arrived about noon,
when it began to rain heavily, and continued till near night; so that we lodged there,
and some of the inhabitants came to see us.

The next day we went forward, and in our way,
heard of a quarterly meeting to be the day after, at Westbury, in Long Island,
and therefore we went that evening, over the sound, to Samuel Bownes,
and had a comfortable lodging after so long a journey,
where our accommodations had not been extraordinary.

On the 26th we went to Westbury and had a good meeting with Friends, and next day,
being the first of the week, had another very large meeting there.

On the 28th we had a meeting on occasion of a marriage, about nine miles from there.
To this meeting came some of the Ranters of Oyster Bay;
and during the greatest part of the time, were pretty still, save only an old man,
who sometimes hooted like an owl, and made a ridiculous noise, as their manner is.
The marriage being solemnized, he stood up, and bare his testimony, as he called it,
against our set forms, and cried for liberty to the oppressed seed; "`Which,`" said he,
"`is oppressed with your forms,`" meaning the manner of the celebration of our marriages,
generally approved by mankind as the most decent.

Those Ranters would have liberty to all who profess Truth to do what they wish,
without being reproved, or accountable to any person or people.
For they say, to be accountable to man is bondage; and for man to judge is vain,
since those actions he may censure may be done in the
motion of the holy Seed and Spirit of Christ;
under which pretense they would cover many vile practices,
by reason whereof we had sometimes been upbraided and reproached in Connecticut,
where some of them, in times past, had appeared, in their extravagant ravings,
under the name of Quakers.
We said not much to them, Truth being over them, and the meeting ended well.
That evening we went to Jericho, eight miles, and lodged at the widow Mary Willis`'.

We went from Jericho to Jerusalem, and had a pretty good meeting at Benjamin Seaman`'s;
and next day had a meeting at Hempstead, where came a priest, or teacher of a sect,
and some people with him, and he began to write after my companion; who, in a short time,
fell so exposingly and heavily upon the sort he was of,
that the teacher ceased from writing, and departed the place,
without offering to defend his profession.

But one among ourselves, who had professed the Truth about twenty years,
took exception against something Roger said concerning the resurrection of the body;
for in his testimony he said, "`He had once believed,
that if the body of a man were burnt to ashes,
and those ashes sifted through a sieve over all the earth, sea and air, yet,
at the last day, the same dust should come together again,
and the same body should then arise; but,`" said he,
"`I now believe otherwise:`" and then cited the words
of the apostle to the too curious and captious inquirer,
"`You fool, you sow not that body that shall be, but bare grain,`" etc.
And this man coming into the friend`'s house after the meeting, made objections in public,
saying, "`He believed in the resurrection of the very same body; for, said he,
the apostle says, '`It is sown a natural body, it is raised a spiritual body,`' etc.`"
And Roger discoursed with him on the subject,
and adduced arguments sufficient to have satisfied any sober inquirer,
and yet he continued to cavil.
Then for the sake of the people and others that might be weak among us,
I called for the Bible and read that part to them: "`That which you sow,
you sow not that body which shall be, but bare grain, it may chance of wheat,`" etc.
"`Therefore the same body does not arise;
but as the grain of wheat dies to its present form of being, by sending forth a blade,
being no other than the one grain expanded, and that blade a stalk, and often many;
and that stalk, or stalks, an ear, or many, with other grains,
but not the same individual grain, of the same nature, shape, and kind;
so argues the apostle for the resurrection of the body,
that that which is sown arises no more, but God gives it a body as it pleases him;
though no comparison will hold in every circumstance.`"
Upon this he was silent; and so the matter ended.
But upon our inquiry what this man was,
he appeared to be one of those the people call wet Quakers:
no wonder then he remained so carnally minded, though so long a professor of the truth;
for it is not profession only, nor confession alone, that the Almighty regards,
but faith, which works by love, to the conversion of the mind to the will of God,
through the sanctification of the Spirit.

Now, though we fully believe the resurrection of the dead, both of the just and unjust,
yet we take not upon us to determine the mode of existence in that state,
or with what bodies they shall come;
but leave it with the Almighty to give unto us bodies as may best please him.
But there is a wonderful mystery in this thing, far out of the sight of the natural man;
but "`blessed and holy is he that has part in the first resurrection;
on such the second death has no power.`"
And the Son of God has said, "`I am the resurrection and the life;
he that believes in me, though he were dead, yet shall he live;
and whosoever lives and believes in me, shall never die.`"
So then they who are truly in him, and he in them, are arisen with him,
and live in and with him, to the praise of his own arm;
who reigns in glory forever and ever.

After this we went with Samuel Bowne and his wife to Flushing,
where we had a glorious meeting next day;
and the day after had a pretty large meeting at Jamaica, about four miles from there;
and that evening we returned to Flushing.
The next day I went over the Sound, accompanied by several Friends, to West Chester;
and the day following, being the first of the week, had a large open meeting there,
many Friends coming from Long Island, and abundance of people from all quarters round,
and some as far as Horseneck: the people were very still,
and many affected with the testimony of truth.
After the meeting we returned over the Sound in a canoe,
and lodged that night at Thomas Stevenson`'s.

The next day we had a meeting at Newtown, three miles off,
to which came John Rodman and my companion from York: the meeting was not large,
but much affected with trouble at the account Roger Gill published in his testimony,
of many being taken away at Philadelphia, by a pestilential fever then greatly prevalent,
ten being buried in one day, and four died on the same;
several of them being good Friends.
His testimony was by way of warning to Friends in that meeting,
to be prepared to meet the Lord,
if peradventure the stroke of his hand might reach those parts.
Then Samuel Jennings reminded the meeting,
that it was no new or strange thing for the people of God to suffer in common calamities;
but the love and favor of God being assured to them, whether life or death ensued,
as it might best please the Lord, there was no occasion of fear,
or to be dismayed at such things, especially to those who were prepared, as the apostle,
when he said, "`For to me to live is Christ, and to die is gain.`"
And since a translation through death to life is the exceeding great gain of the saints,
we have no ground to repine at the loss of their society here, though most grateful,
but rather patiently and diligently wait upon the Lord, till it may become our lot.

From this time my companion could never fully settle
his mind to stay any longer in those parts;
but said if he had wings he could fly to Philadelphia to the distressed Friends:
but I kept to our settled purpose,
stipulated before we heard of their condition and exercise.

That night Samuel Jennings and I lodged with Robert Field,
and Roger Gill and John Rodman returned to New York; where, next day we had a meeting,
and each of us a good opportunity therein among the people;
who seemed to have good understandings generally as men; and Friends were well satisfied,
there being pretty many from the island.

My spirit was heavy and sorrowful all night; and the next morning we took boat,
and in the evening came to anchor in the entrance of
the river that goes up to Elizabethtown,
and went to an inn at Elizabeth Point about one in the morning,
where all the beds were taken up; so that we had little rest that night.
As soon as it was light we set forward, got to Woodbridge,
and had a meeting there that afternoon; in which, though small, I was refreshed;
to the praise of Him whose presence is life,
and at whose right hand is fulness of joy forevermore.

That evening we set forward, but when we came to the inn all was full,
and no attendance could be had but a superannuated negro, who could do but little for us;
so that we were obliged to take care of our own horses,
and fetch them hay a considerable way off.
That night I lay with my clothes on in the entry, and slept very well:
for where the Lord subjects the mind and makes it content, all things are easy.
Next day we went about thirty-five miles to Crosswicks,
and had very good accommodations with our friend Francis Davenport.

The day following we went to Burlington, being met in the way by some Friends from there,
and lodged with Samuel Jennings;
where we heard more of the sad effects of the
pestilential distemper still prevailing at Philadelphia;
and the next day being the first of the week,
in the morning my companion fell under a great concern
to go to the meeting that day at Philadelphia,
and asked my thoughts upon it: I answered,
that it was a case too difficult for me to advise in, as things were then circumstanced;
but for my own part,
I did not see any cause to recede from the plan of proceeding formerly settled,
but left him to the concern and liberty of his own mind;
and that since notice had gone abroad of our intention of being that day at Burlington,
I thought it my place to stay there; which I did accordingly,
and he hastened to Philadelphia; where he arrived, as he said,
before the morning meeting was ended, though twenty miles off,
and he had the great river Delaware to cross by a ferry.

The meeting at Burlington was very large, but not so open as in some other places,
for which I knew no particular reason.
Next day I rested there, and on the 12th went over the river into Pennsylvania,
to a meeting appointed at the Falls, and the presence of the Lord was tenderly with us;
and that night I lodged with our honorable friend in the truth, Phineas Pemberton,
and rested there next day.

On the 14th of seventh month +++[+++1699]
we had a pretty large meeting at Neshaminy, and very tender, the Lord being good to us.
The next day I had a good meeting at Poquessink, but not very broken:
I came away in peace, and rode very hard, being late, to Philadelphia that evening;
where my soul for some time had desired to be, and where I found my companion well,
but many Friends on their sick and dying pillows;
and yet the settled presence of the Lord was with them at that time:
such is the goodness of God to his own people, that in their bodily,
or any other afflictions,
his holy presence greatly abates the exercises of nature by its divine consolation.
O the love that flowed in my soul to several in the times of my
visits to them! in which I was lifted over all fear of the contagion,
and yet not without an awful regard toward the Lord therein.

The first I visited was Aaron Atkinson, then at Edward Shippen`'s;
of whoso recovery I was glad,
both from personal respect and for the sake likewise of his services in the churches;
and Edward and his wife were also well recovered.
In this distemper had died six, seven, and sometimes eight a day,
for several weeks together; and the yearly meeting being to begin there next day,
we had some exercise and consultation about it,
arising from the prevalence of the distemper in the city at that time,
and yet not much in the country.

Some Friends had written from Burlington to Friends at Philadelphia,
proposals to adjourn the meeting till a cooler time; to which it was answered,
that till the meeting was come together, they had no power to adjourn;
but thought it might do well to discourage, in all places,
the great numbers of young people and servants
that usually come to town on those occasions;
and such only to come as were necessarily concerned in the service of the meetings,
because of the great infection, and incapacity of Friends and inns in town,
at such a juncture, to lodge and entertain them, there being few, if any,
houses free of the sickness.

In the morning meeting of ministers and elders,
on the seventh-day of the week at Philadelphia,
we were under great concern about holding the meeting in the usual time,
or whether it were better to suspend it; and as we waited on the Lord for counsel,
the testimony of truth went generally against the adjournment, or suspension;
and the Lord`'s presence was greatly with us to the end,
though some opposition we met with from the prudentially wise men present,
who consulted their own reason, but not the Truth; who has all power,
and can do and prevent what He pleases.

Accordingly the next day, being the first of the week, the meeting was held,
and was large, all circumstances considered; and the Lord so evidently appeared with us,
that there was no room left for doubt,
but that it was his will we should hold our meeting and serve God therein,
as well in times of adversity and affliction, as in prosperity and less seeming danger.
Friends were generally comforted in the divine truth,
and the fear of the contagion was much taken away,
and the testimony of truth was exceedingly glorious in several instruments,
and over the meeting in general, and so continued to the end; which was the first,
second, and third days for worship, and the fourth for business;
which was managed in wisdom and unanimity, and ended in sweetness and concord;
as becomes all meetings of the people of God everywhere.

But that which was very remarkable, was,
that though the distemper was very raging and prevalent all the week before,
yet there was not one taken ill during the whole time of the meeting,
either of those who came there on that account, or of the people of the town,
that could be remembered by such Friends as made the observation;
and yet presently after there were many taken ill thereof in town, and several died,
but few in comparison to what had died before;
and a little after that it was finally stopped by the good hand of divine Providence.

My companion and I both remained in town till the 23rd of the seventh month,
visiting the sick Friends from time to time, as we found necessary or expedient.
Great was the presence of the love of God with his people,
in the midst of this trying visitation; which gave us occasion to say, Good is the Lord,
and greatly to be feared, loved and obeyed;
for though he allows afflictions to come upon his own chosen people,
in common with other men, yet that which otherwise would be intolerable,
is made as nothing, by how much the sense thereof is swallowed up in his divine love.
O the melting love!
O the sweetness I enjoyed with several, as they lay under the disease,
being unspeakably comforted in the Lord: let my soul remember it,
and wait low before the Lord to the end of my days!
Great was the majesty and hand of the Lord!
Great was the fear that fell upon all flesh!
I saw no lofty or airy countenance, nor heard any vain jesting to move men to laughter;
nor witty repartee, to raise mirth; nor extravagant feasting,
to excite the lusts and desires of the flesh above measure;
but every face gathered paleness, and many hearts were humbled,
and countenances fallen and sunk,
as those who waited every moment to be summoned to the bar and numbered to the grave.

But the just appeared with open face, and walked upright in the streets,
and rejoiced in secret, in that perfect love that casts out all fear;
and sang praises to Him who lives and reigns, and is worthy forever,
being resigned to do his holy will in all things; saying, Let it be as you will, in time,
and in eternity, now and forevermore.
No love of the world, nor fear of death, hindered their resignation,
abridged their confidence, or clouded their enjoyments in the Lord.

On the 23rd my companion went to Burlington, to be at the meeting there next day,
having passed it as we went to Philadelphia; where notice was given,
and some meetings appointed for me the same week on that side the river.
He returned on the 25th to Philadelphia;
and the same evening he appeared to be under symptoms of the common distemper.
We discoursed together concerning our further proceedings in our service,
but he told me he did not see his way any further to any meeting at all.

That night we lodged together, and he sweated very much, and next morning arose,
but soon took bed again; and then, at his request,
I took an account of some small things he had in America;
upon which he asked me how his effects there, and in England,
would be distributed among his wife and children, if he should die intestate?
in which I resolved him.
The meetings being appointed, I could not stay with him; and when I look leave of him,
he told me he was pretty easy and not very ill:
yet I departed under a very great load upon my spirit, and suspected the worst;
for he had prayed in the yearly meeting, with great zeal and earnestness,
that the Lord would be pleased to accept of his life as a sacrifice for his people,
that a stop might be put to the contagion;
and I had thought in the mean time he would be taken at his word,
though no such sacrifices in such cases are required;
only therein appeared his great love and concern for Friends,
whom he had come so far to see.

That evening I went to Burlington,
and next day had a pretty large and good meeting at John Shinn`'s;
where was a new meeting-house, about six miles from Burlington, in the woods;
and next day had another meeting at John Adams`',
about seven miles further down the river, where many people were gathered.
In the beginning of this meeting my mind was greatly
concerned about going to the yearly meeting,
to be in the eighth month, at Choptank, in Maryland; which being yielded to in secret,
I then had a pretty open time, and the meeting ended well.
But Samuel Jennings having used some expressions in his
testimony concerning evil surmising and false censuring,
I inquired of him after the meeting, whether I had missed in any expression,
that might be justly censured?
To which he answered, he was well pleased with the meeting, and what had passed in it;
for sooner or later all was clear:
and he had also given a general caution in the meeting,
that all should be careful to know in what spirit and
to what end they judged or censured others,
lest they judged others in the same spirit in which they themselves
had committed greater evils than those they judged in others;
and so incur greater condemnation.

But when I came to the bottom of the matter,
I understood that as I had been concerned in some other meetings,
to expose some of the false doctrines of the apostate George Keith,
which had obtained a place among many in those parts,
some of that sort had invited a very critical Keithian to this meeting,
in hope to get some advantage, or matter for dispute and contention;
in which he and they more delighted,
than in the practice of any Christian duty toward God or man.
And the rather they had this hope, because I had in some former meetings in those parts,
been concerned about the sufferings of Christ in the flesh among the Jews,
and his powerful and effectual baptism by the Spirit;
but in this meeting I had little on those subjects,
save a short introduction as to the coming of Christ in the flesh,
but rather the blessed effects and consequences thereof;
his divine and spiritual manifestation,
as he is the Word of God and light of the Gentiles, in whom, as such,
we ought to believe; and by which faith in his divine light and obedience thereto,
we have remission of sins and the full benefit of his death and sufferings.
So that those contentious apostate spirits were not gratified; who usually,
and falsely charged us with neglecting,
and even disbelieving Christ`'s outward appearance, and too much preaching the light;
which they hated, and at which they stumbled, and were offended;
and of whom it may justly be said, When they knew God, they did not glorify him as God,
but turned aside into envy and vain jangling; in which there is no honor to Christ,
nor life to the soul.
But none of them made any objection to anything
that was delivered in the meeting that day.

The same evening I set forward for Philadelphia, where I arrived about the ninth hour,
and found my companion very ill, and several dead,
and others taken ill in the few days I had been absent.

On the 29th was a monthly meeting at Philadelphia, which was small,
yet the Lord was gloriously with us; Aaron Atkinson was likewise there.
In that meeting I acquainted Friends that I intended to leave them for some time,
and that there were some there I should never see more in that meeting.
Before the meeting was ended, John Busby, a Friend there, was taken very ill,
and violently handled; and when at home he sent for Aaron Atkinson, and I went with him.
The Friend was in a tender condition of mind,
and used some lively expressions of the goodness of God, and afterwards in prayer;
and we were comforted in him.
I was concerned in prayer also; and we were much refreshed together in the Lord.
Aaron and I visited several other Friends, who were in the like condition.

My companion remaining ill, and my concern for the yearly meeting in Maryland increasing,
it came very near to me to leave him under these circumstances.
But having duly considered every part, and finding I could not be of much service to him,
and that he was among friends who could do more than I in that case,
on the 30th of this month, being the seventh of the week, in the morning,
I took leave of him.
But my departing proved to be an occasion of greater tenderness than I expected;
for I had not been so much affected since I came from England, weeping exceedingly,
and irresistibly, so that my tears ran down upon the floor.
He then desired me to leave him, for he had not been fully willing before,
and that the Lord might be with me; "`For,`" said he, "`you break my heart;
I cannot bear it any longer.`"
And in a short time after, I left him, uneasy and restless in body,
but otherwise well and comfortable.

About the eleventh hour, Aaron Atkinson and I, Edward Shippen and his wife,
Samuel Carpenter, Isaac Norris, Griffith Owen,
and some other Friends set forward for Maryland,
and that evening went to Bartholomew Coppuck`'s, where most of us lodged that night.

The next day we went to Chester, where we had a large meeting;
after which we went to Caleb Pusey`'s and lodged,
and next day went forward about forty-six miles and lodged at an inn.

On the 3rd day of the eighth month we went to George Warner`'s, a Friend,
who lived on the bay of Chesapeake, eight miles below Turkey Point,
where we were kindly entertained,
and the Lord`'s comfortable presence was with us in that family.
We went next to Chester river, to our friend Henry Hosier`'s, and had meetings;
and the good presence of the Lord was with us, to the praise of his own holy name,
who lives, and is worthy to reign forever.

On the 6th we set forward for Great Choptank, and at the ferry,
I had the afflicting news of the death of my companion, Roger Gill, at Philadelphia;
at which my soul was greatly bowed, and my heart tendered,
and the ground whereon I sat was watered with my tears.
I was fully satisfied he had obtained a crown of everlasting peace with the Lord,
and that his memory should not rot,
nor his living testimony fall in those American parts, wherein we had labored together,
from Carolina to New England; where many hearts had been tendered by him,
and souls comforted, and several convinced;
and all through that divine power by which he is now raised to glory,
to sing praises to him who sits on the throne, and rules and reigns, and is alone worthy,
forever and ever.
Amen.

This afforded me matter of deep humiliation,
considering how long and often the Lord had spared me, and to what end,
since I have no interest in the world, nor anything,
for the enjoyment whereof I could desire to live;
but that it may please the Lord and Giver of life to spare mine,
till I may be more fit to appear with my accounts before him.

Having rode about thirty miles, we arrived at John Pitt`'s in the evening,
and next day went to the yearly meeting at Choptank, which was not large that day,
being the seventh of the week, and the people not gathered;
but next day it was large and well, and ended peaceably.

In the morning we returned to the meeting place with a heavy load upon our spirits,
but did not know the cause till the meeting was assembled,
and then came an Episcopal priest, and with him several justices of the peace, a colonel,
and a great company of gentry of both sexes;
and a mighty great crowd of people there was.

While Aaron Atkinson was engaged the priest came not into the house,
nor did I know anything of his being there till a little before Aaron had finished.
As soon as I stood up they came in,
and then I saw from where came the load of darkness in the morning, which, by that time,
the Truth had, in a good degree, overcome, and driven as smoke before the wind.

Many things opened in my mind, which I delivered: Of the fall of man through temptation,
unbelief, and disobedience: of the love and mercy of God still towards him:
of the various dispensations of God for the restoration of man, namely:
the manifestation and strivings of the Spirit of God with the old world;
the law of Moses; the ceremonial, moral, and judicial or civil parts of it: of Christ,
the antitype of all the figures, and fulfiller of them,
and of the whole law first in himself, and then in all who believe in him, and obey:
of the life, sufferings, death, resurrection, ascension, glorification,
and intercession of Christ:
of his dying as a propitiation for the sins of the whole world:
of universal saving grace by him: of the faith of the Gentiles in him,
the Word that took flesh,
and is the "`true light that enlightens every man that comes into the world;`" that
makes a discovery of sin in the understandings of mankind,
and reproves them for it in secret, when no man can accuse: of the baptism of John,
and of Christ`'s baptism; the former with water unto repentance, proposing Christ,
not then made manifest, as the object of faith, when come or manifested;
and the latter with the Holy Spirit:
how the apostles of Christ fell in with John in the administration of water baptism;
not in the name of one to come, or unknown, but in the name of Jesus,
whom they declared to be the Messiah, for the remission of sins;
with many other things for the clearing of that subject.
During all which the priest and his company were very still and attentive,
and the meeting ended in peace without interruption.

When the meeting was over,
Richard Jones told me the priest desired to have some conference with me;
and that he had asked him if he had anything to object against what he had heard?
and he said no.
I asked him the same question, but there being many of the people about us,
he then insinuated that he had something to object, but was unwilling to expose me,
but would discourse me in private, with two or three of my friends, and as many,
or fewer, of his.

To which I answered,
that if to what I had said in that great auditory he had anything to object,
I was ready to answer in the face of the same;
and desired him to go into the meeting-house as the most proper place,
and that was the most proper auditory, which had heard so lately what I had delivered;
but he refused, and began to abuse me, saying, I was a cunning sophister,
and had deluded the people; which I challenged him to prove before them if he could;
but he went on railing, and alleged,
that I had asserted none of the apostles ever baptized
with water after the coming of the Holy Ghost:
and calling a young man as a witness, he confessed,
that I had challenged the priests to prove by Scripture,
that any of the apostles ever baptized with water, in the name of the Father, Son,
and Holy Ghost; and if they could not,
then any baptism they used with water after the coming of the Holy Ghost,
was only the same they administered in John`'s time, before that in Matt. 28:19,
was instituted; where it is said, "`Go you therefore, and teach all nations,
baptizing them in the name of the Father, and of the Son, and of the Holy Ghost,`" etc.,
for if any of the apostles had baptized with water from that text,
they would have pursued the terms of it in that action; which they never did.
And therefore, since no water is mentioned in the text, nor any instance can be given,
where the terms of it were used by any of apostles, it follows,
that the baptism intended there was not with water, but the Spirit,
as alone proper to the dispensation of Christ, the Son of God, and not to the servant.

His witness thus witnessing against him, he raged,
but would not engage any further in the dispute.
Then I sent for a form out of the meeting-house, on which I stood up,
and informed the people of the priest`'s mistake; upon which he rode off,
almost without hearing, and placing himself at some distance, with a rude company,
stood gazing, blustering, and calling us names, and then departed.
Many were offended at his management; some saying they had come twenty miles,
and were disappointed.

The priest and his company being gone, we were told by some who observed it,
that the justices and he, before they parted,
held a consultation to have drawn up a warrant against
me for speaking against the common prayer,
but could not find how to make it bear;
for I had said something against the sprinkling of infants as no ordinance of Christ,
as they pretended: but the Lord defeated their mischievous design.

The meeting for business being there the next day, it held late in the afternoon,
so that several of the people who had come far
in expectation of another meeting for worship,
went away before we had done; but business being ended,
we were favored with a tender season together,
and our meeting ended in the pure holy love of our Lord Jesus Christ, our holy Head,
Life, and Comforter, who is ever near, to the end of the world,
to strengthen and support his own in the needful season, and to bind up his holy body,
the church, with the joints and sinews of divine love, that cannot be broken;
against which the gates of hell never can prevail.

According to appointment, we held a meeting next day at Tuckahoe, which was pretty large,
the whip of small cords being well employed,
to scourge the buyers and sellers out of the temple;
and there was likewise clean water to wash the tables and cleanse the steps.
It ended well, and we went that evening, about nine miles, to William Troth`'s,
who had been greatly indisposed, but was much refreshed by our visit to him.

On the 13th we went to Choptank river meeting, where the Lord gave us a comfortable time.
On the 15th, being the first of the week, we went to a meeting at Little Choptank,
and in the way, I found my mind much laden,
not knowing the cause till we came to the place.
There we received a message from an Episcopal priest,
that he intended to be at our meeting, and desired us to stay for him,
that he might hear us.
This message increased my concern to see what the Lord would be pleased to direct;
and being favored with a sense of the gentle operation of his power,
and my heart much comforted in his divine presence,
I did not doubt but we should have understanding and power sufficient for the day.

We were not hasty to go into the meeting, nor found we freedom to delay,
but began it near the usual time; and the good presence of the Lord was tenderly with us,
and I felt my spirit thereby over that spirit that was coming to oppose us.

Aaron Atkinson spoke first in the meeting,
and the priest delaying longer than the time he had appointed,
Aaron had done before he appeared; and a concern being upon me likewise before he came,
I had gone through several things concerning the fall of man,
and the promises of God for his restoration; and that Christ has come accordingly,
and has died for all men;
and that the grace of God is come upon all men for their salvation,
upon condition of their faith in him, repentance, amendment, and obedience;
and this grace is that spiritual power that reproves mankind for sin in their own hearts, etc.

In the mean time came the priest, his wife, several justices of the peace, two lawyers,
and many people; who rushing in, occasioned some unsettledness in the meeting,
and altered the state of it, so that the people were not, for some time,
in a condition to hear with attention; and therefore I stood a little while silent,
finding the operation of the word of Truth to abate, as to that matter.
After which I exhorted them to be still, not only as to their bodies,
but also their minds, that haply they might reap some advantage by what they might hear;
and then I began '`to recount, in short, what points I had gone through before they came,
to the end they might perceive the entire scope of my testimony.
Then the power of Truth began again to work,
and therein I quickly came over both priest and people,
who were generally sober and attentive, which made the priest very uneasy.
And at length, as I came to treat of baptism, he fell into a passion, and interrupted me;
but I kept my authority and matter, and went on.
That which seemed to touch him most, was about sprinkling of infants;
when I told the people it is an anti-christian and Popish innovation,
he then fired upon me with an objection; but I bid him be silent,
for our meeting was not ended; and he forbore till I had done:
and then Aaron Atkinson concluded the meeting in prayer;
upon which the priest and justices went out.

The meeting being ended, they came in again, and the priest was big with his objection,
which he had conceived from a mistake of a text of Scripture.
It was thus: "`You,`" said he, "`have spoken much against water baptism,
as if it were not obligatory at this day; but the Scripture says,
'`Unless a man be baptized with water and the Holy Ghost he cannot see the kingdom
of God.`'`" I passed by his mistake for the present in misrendering that Scripture,
and said, "`There is no necessity to believe,
that the Lord Jesus spoke then of elementary water;
but as there is a twofold operation of the Holy Spirit, the one compared to water,
which is for the washing away of the pollution of sins past before conviction,
and the other to fire, for destroying the root of it in us;
as it is prophesied of Christ, "`He is like a refiner`'s fire, and fuller`'s soap;
and he shall sit as a refiner and purifier of silver,
and he shall purify the sons of Levi, and purge them as gold and silver.`'
Again, the baptism of Christ makes thorough work; for '`his fan is in his hand,
and he will thoroughly purge his floor, and gather the wheat into the garner;
but he will burn up the chaff with unquenchable fire.`'
In another place it is written, that Christ said, '`He that believes on me,
as the Scripture has said, out of his belly shall flow rivers of living water:
but this spoke he of the Spirit, which they that believe on him should receive.`'

"`The Spirit of Christ is thus compared both to water and fire,
and their different effects and operations, to express the baptism of Christ,
and work of regeneration, as begun, carried on, and perfected by him:
and it is also written, '`By one spirit are we all baptized into one body,
and have been all made to drink into one spirit.`'`"

Then I asked the priest, "`That since the Spirit of Christ is thus compared to fire,
as well as water,
why he did not think elementary fire was to be used in baptism as well as water?`"
To which he was silent.

Having entered thus far into the argument for the sake of the people,
Aaron Atkinson told them, there was no such Scripture as their priest had alleged;
for it is, "`Except a man be born of water,
and of the Spirit;`" and not baptized with water and the Spirit;
which the priest could not deny, and then the people saw him wrong.

The priest being foiled in this, he recurred to the text in iMatthew,
"`Go you therefore and teach all nations, baptizing them in the name of the Father,
and of the Son, and of the Holy Ghost;`" and alleging from here, "`That these words,
'`Go teach all nations, baptizing them, etc.,`' show,
that teaching and baptizing is one act.`"
"`You say well, said I; we have all along maintained that against our adversaries,
why then do you oppose us?
For if teaching and baptizing be the same act in the sense of that text, water baptism,
as to any command from there, is excluded.`"
He then saw his mistake, and was ashamed; and many of his people were so too,
and went out of the room.

At length he pulled a book out of his bosom,
and would have shown us what his author had said about baptism:
he was not willing to show the title, or the author`'s name,
but I perceived it was the Snake in the Grass;
and then I exposed it as a very false piece, and Charles Lesly, the author, as a forger;
and that his book had been fully answered, and his arguments repelled,
by one of our friends, Joseph Wyeth.
And then I advised the priest to be baptized himself,
if he thought water baptism was necessary, or else he had no right to dispute about it;
for sprinkling is not baptism.

To this he replied, "`That though they did not use washing in water, but sprinkling,
that ought not to be alleged as a ground for us to reject the whole.`"

I answered, "`We have sufficient authority, without that, to decline all water baptism,
as no ordinance of Christ;
but it must needs be very perverse in any to contend
with others for a necessity of anything in religion,
which themselves will not practice.`"
I then exhorted the priest to give way to the
manifestation of Truth in his own conscience,
and it would lead him out of all error and evil things;
and so we parted in a friendly manner.

A justice of peace and a lawyer staid longer,
and we had discourse with them on some other points.
We informed them further concerning our principles,
and particularly of our sentiments respecting human government.
Of our loyalty and inoffensive demeanor under all governments, in any form,
giving always either active or passive obedience;
and that where the former could not be yielded,
when anything contrary to our religion and consciences, and duty to God,
was commanded or required by any law, then the latter was never lacking, or refused,
though to the loss of all.

Upon this an attorney at law asserted,
"`That all men were bound in conscience to give active obedience to
all laws made by the legislature of any government where they lived;`"
but offered no reason for his opinion.

I answered, "`That, according to this, all the faithful primitives were wrong,
who never complied with the laws of the heathens, made against them and their religion;
but suffered cruel deaths in confessing the true God, and the Lord Jesus,
especially under the two emperors, in the tenth general persecution.
Thereby he condemned all the Protestants, and others,
as worthy of those punishments inflicted upon them by Papists,
on account of their religious sentiments,
being contrary to their national and ecclesiastical laws;
to which those sufferers could not, because of their known duty to God and Christ,
give any active, but only passive obedience and non-resistance,
though inflicted by force of the statute de heretico comburendo;
whereby many of the people of the nation,
who were then of the same religion of the present national church, were destroyed.
If they ought to have given active obedience to that, and such other persecuting laws,
then their blood was upon their own heads, being justly shed for their disobedience;
which would be a very severe and unchristian opinion, and therefore to be rejected;
and being attended with such consequences, you would do well to lay it aside,
and entertain it no more.`"

That night we lodged at the Widow Kennerly`'s,
and the good presence of the Lord was comfortably with us,
and great was our reward of peace in him after that day`'s work.
As I never have observed anyone to undertake with so much confidence,
and come so meanly off as this priest did,
so I believe he made himself work for repentance.

The next day we went to Chickinacomoco,
and on the following morning went forward to a meeting appointed at Nanticoke river,
at Edward Fisher`'s, which was small, but comfortable.

In the morning we made haste to get over the river, the tide being upon the ebb,
and then rode to another ferry, where we had a good passage,
and that evening arrived at Leven Denwood`'s, where we lodged.
There we met with one they called the king`'s attorney, an ill-spirited man;
and after some time a discourse arose between him and Aaron Atkinson,
and he soon discovered a bad disposition towards us as a people.

The matter they were upon was Christ`'s satisfaction
made upon the cross for the sins of mankind,
which he pretended to magnify; but with a view, as it might seem,
to the exemption of men thereby from the necessity of a holy and righteous life;
and Aaron Atkinson endeavored to inform him,
that men`'s belief only of the things which Christ did and suffered in this world,
without a conformity to his life, is not sufficient for salvation.

In the mean time the attorney, as he spoke of these things,
behaved himself in such a manner,
that I perceived he had no regard to the dignity of the matter,
nor sense of the things he talked of; and therefore I told him,
if men would take upon them to speak of such things,
it ought to be done in a spirit of meekness and humility,
and with an understanding of the things they treated of.
This a little cooled him (or a time;
and then I took occasion to mention to him the
promise of God concerning the new covenant,
which is inward, in the heart; a covenant of light, life, and power,
of which Christ is the Mediator, and the great effect of his coming in the flesh;
the fruits whereof are peace, love, and good-will unto all men:
under which dispensation men are to "`beat their swords into plough-shares,
and their spears into pruning-hooks; nation is not to lift up sword against nation,
nor to learn war any more.`"
Many of the prophecies being already come to pass,
we look for the fulfilling of this also,
by the inward revelation of the Spirit of Christ, who is the Prince of peace,
of the increase of whose government there is no end.

"`But,`" said he, "`that is not likely to be in our time.`"
"`Why,`" said I, "`if it be fulfilled in you and me, we shall have the advantage of it,
as to us, though it be not general in our time.
It is evident it is not yet come to pass among those nations professing Christ,
who have been so lately in wars one against another;
and yet it is come to pass in a people at this day,
in whom the Lord has begun this great and good work.
For we have not used the carnal weapon since we were a people; nor can we,
because the life of Christ in us is against and contrary to it.
And to the same principle of divine light, life, and love, will God, who is the same,
bring all nations in his own appointed time.`"

He replied, "`You say it is fulfilled in you; but how does that appear,
since you have not yet been tried as a people in any government where you had full power?
I have heard, that in Pennsylvania, where you have a government only under another,
you have used the carnal weapon,
in rescuing a sloop which some piratical persons had stolen from a wharf at Philadelphia;
by which it may be suspected you would use it further in other cases,
which might touch you if you had an independent government;
though I cannot charge them in Pennsylvania with
anything of that kind but what I have heard.`"

I then asked him if he had heard the defense of the persons
charged with the retaking of that vessel`'! He said he had,
but did not know whether it was true.
"`It seems you can not charge but upon hearsay.
Does it not then discover a partial inclination in you, to think us guilty,
since you cannot receive a defense upon hearsay as well as a charge?

I informed him,
that we had been greatly abused by the false reports and misrepresentations
of some envious apostates and their abettors on that account,
with an evil design, not only to destroy our characters,
as if we had acted as hypocrites, contrary to our religion,
but to lessen and decry the efficacy of that principle of divine light, life,
and truth we make profession of.
But if the report had been true as stated, as it was false,
yet the weakness or presumption of some persons professing the same religion, is not,
by any justice, to be charged upon the whole people,
and much less upon their principles of religion.
For it was not the government, but some particular persons,
who took upon themselves privately to bring back that sloop,
which they effected by surprising the thieves,
and without any bloodshed or act of violence.

It is still more unjust to suggest against us as a people,
that if we had power we would take up arms and fight upon occasion,
contrary to the religion we now profess; yet this is no other, in effect,
than what I have heard suggested by men of your principles,
against the apostles of Christ and the holy primitives.

The next day we had a meeting there, which was pretty large and comfortable,
and on the 20th, being the sixth of the week,
we set forward and passed a ferry on the Pocomoke river,
about twenty miles from our lodging,
and Aaron Atkinson`'s horse being sick and likely to fail, it laid us under some concern,
having about twenty-five miles more to ride that day, and no lodging by the way,
and the nights then beginning to be cold.
But the Lord was near to bear up our minds;
and after our horses had grazed a little in the wood,
the sick horse began to grow better,
and before it was quite dark we arrived at the widow Mary Johnston`'s, at Muddy creek,
where we were entertained to the best of her ability, and were refreshed,
and rested well that night.
Next morning her son and George Drewett, who had been our guide,
went to give notice of a meeting to be at the meetinghouse on the first-day following,
and we rested there that day.

The meeting was large, the house being full, and many more than it could admit,
but hard in the beginning.
The people are apt, in those parts,
to keep out of the meeting houses till they hear some begin to speak,
and then they frequently rush in rudely, and so disturb the meetings;
though they do not intend any molestation by it.
Many things were opened that day, in the wisdom of Truth;
and the meeting proved better in the end, several persons were tender,
and the people generally humbled under the authority of Truth.
The necessity of the work of the Holy Spirit in the heart, regeneration,
faith in Christ the Word of God, and good works, being greatly pressed upon the audience,
and holiness, without which there is no entering the kingdom, or seeing the glory of God.

That night we went home with Thomas Fooks to Anancock, about twelve miles,
where we rested well and easy,
and Aaron Atkinson was twice concerned in prayer for his children being twelve in number.

Next morning we set forward for Thomas Brown`'s, at Naswadock`'s creek,
about twenty-five miles off; where we arrived about three in the afternoon,
and staid that night, and the day following had a large meeting at the meeting house.
Things being much out of order in those parts,
Friends intermarrying and intermixing with the world, we were laden in our minds,
and uneasy, and therefore appointed another meeting,
to be on the 26th. In the mean time we were concerned
to preach Truth in the family where we lodged,
by which we were greatly eased and comforted in our spirits,
and the glorious reward remained upon us all night,
and the next day we were favored with a better meeting than before.
Truth being over all; and we came away clear, and in much satisfaction.

On the 27th we had another meeting at Thomas Fooks`', wherein we were well satisfied.
Truth being over all; the people were sober, and went away low and humbled.

On the 29th, being the first of the week,
we had a large meeting in the meeting-house at Muddy creek,
and that evening returned to Mary Johnston`'s; and next morning,
after a very tender season at table, rode about forty-five miles to George Truet`'s,
where we staid, being very weary, till the 1st of the ninth month,
and then had a meeting there.

The day following we had a meeting at the house of Walter Lane, about fifteen miles off,
whose wife was a Friend.
The meeting was small, by reason of a court held near the place at the same time;
but the countenance of the Lord being with us, all was well;
and after this we rode to our friend Thomas Evernden`'s, at Anomessicks,
where we staid nearly two days, and had some service in the family.

On the 4th we went to Richard Waters`', and next day, being the first of the week,
had a meeting there, which was hard and dry in the main, though we were easy after it,
and had some good times in the friend`'s house;
he and his wife not having been long convinced, were tender and innocent.

On the 5th Aaron Atkinson went on board a sloop in order for the Western shore;
I went with him to the vessel, and there we took leave of each other.
I went to George Truet`'s, about thirty miles, where I lodged that night,
and next day rode about thirty-five miles to Cedar-Neck;
and calling at the house of one William Atkinson, not a Friend by profession,
he informed us that the tide was high, and no passing the inlet,
but invited us kindly to stay with him that night; which we consented to do.
The house was small, and several children, yet they made a shift to get us beds,
and sufficient eatables, and good milk and water to drink.
At supper I was concerned to call upon the name of the Lord,
and both the man of the house and his wife were touched
with a sense of the divine virtue of Truth,
and praised God that I came under their roof,
as having been made instrumental for their good.
The woman being devout in the way of the church of England,
I opened to her many things about baptism and the supper; which she gladly received,
and asked me many questions about other points, which I resolved to her satisfaction;
and her husband was likewise well pleased.

In the morning we ate and drank again, and then asked what we had to pay;
but they would not receive anything, either for ourselves or for our horses; and besides,
the man went with us over the inlet about seven miles,
and put us in the way to Lewistown, in the county of Sussex,
in the territories of Pennsylvania, where we arrived in the evening late.
Alighting at our friend William Clark`'s,
he sent out that night to give notice of a meeting to be there next day;
which accordingly we had.
It was not large, there being no settled meeting there, but comfortable,
the Lord mercifully owning us with his good presence.

I found a concern upon my mind for another meeting there,
and staid till the first-day following.
This was larger than the former, and I was well satisfied in it;
for Truth and its testimony were over all,
and many things were opened to the satisfaction of Friends and people.

The next morning, accompanied by Samuel Preston of Philadelphia, I went on to Mispillion,
to Joseph Booth`'s, where we had a meeting the day after.
He did not profess with us, but was friendly;
and he asked me many questions concerning baptism, the supper, perfection, etc.,
all which I answered to his satisfaction;
and next day after the meeting he expressed his full convincement of what he had heard.
But I found he stuck at the cross;
he could not submit to the plain language of thee and thou to a single person,
nor become unmodish in keeping on the hat, and declining the customary ways of address,
nor break off that heathenish custom of calling the
days and months by the names of their imaginary gods,
which he thought too low for matters of religion;
concerning all which we discoursed next morning, as he set us on our way;
and in some of these points he was better satisfied before we parted.
Yet the cross was hard for him to bear in these small things; and why?
Because submitting to the practice of them,
immediately subjects a man to the scoffing and contempt
with which we are treated by the world at this day,
no way agreeable to the natural and carnal mind.
And that which rendered things harder to him was,
the station and character he supported in the world; for he was a justice of the peace,
and the most sober and knowing person in those parts.

After that meeting many expressed their satisfaction,
especially with what was said concerning baptism,
though it was more difficult to make that point
clear to the understandings of the people,
especially the weaker sort, at that time, than it might have been at some other.
For there was then a romantic paper handed about, falsely relating,
"`That in Holland had lately been observed by some travelers,
a certain great stone by the wayside, with this inscription,
'`Blessed is he that turns me over;`' upon which the travelers essayed to do it,
but could not; and many people being about it trying, but in vain,
there came one unknown, in the form of a little boy of about four years of age,
and making the crowd give way, turned the stone with ease;
under which was found a letter, pretending to be written by the Lord Jesus Christ,
intimating, That he purposed to come shortly to judgment;
and strictly commanded the keeping of the sabbath,
and that they should baptize their children.`"

Copies of this forged letter were industriously spread about in Maryland,
and in those lower counties and territories of Pennsylvania,
not without some suspicion of priestcraft; for about that time some of them went about,
in their trade, asking the people if they had any children to christen?
And those who would pay for it, might have them made as good members of Christ,
children of God, and inheritors of the kingdom of heaven, as the priest was able,
for so much money, tobacco, or other reward or barter as they could agree for.
But the work going on slowly and heavily,
there lacked something to quicken the zeal of the people;
and to that end this miraculous event was reported beforehand,
as a messenger to prepare the way of the priests before them:
and that which was to have made the people`'s neglect in the case the more to be dreaded,
such as should be negligent herein were not to thrive in the world;
for neither their cattle, hogs, corn, nor anything else, were to prosper.

The priests of Maryland, from whom this report and paper came,
had it read in their churches, in which also they had another end, namely:
to overawe the inconsiderate people into the practice of sprinkling their children,
the invalidity whereof had, all over those parts, been so lately before exposed,
as no ordinance of Christ, but a popish remain.

The wife of Joseph Booth, before mentioned,
was fully in the belief of this new coined miracle,
and what I had both argued before and preached in this meeting against sprinkling,
and water baptism in general, was extremely hard for her to bear;
so that she went out of the meeting into another room,
and I had not her countenance any more while I staid in the house.
But her husband being resolved to confess the truth, so far as he was convinced,
reasoned with her, and said,
that seeing he was so fully satisfied of the truth of our principles,
if she found him grow any worse for owning them,
she might then have cause to be troubled; but till then, she would do well not to murmur.

On the fourth-day, being the 15th of the month, we went forward,
and on the 18th got to Salem, in West Jersey, and next day, being the first of the week,
were at the meeting there; but the testimony of Truth running, for the most part,
toward the world, and against apostates,
I had not so much comfort therein as in some others, yet things were well.

On the 20th I went to Cohansey, and next day had a small meeting there;
but the promise of the Lord was fulfilled in us,
for several were melted and comforted in his presence, and I returned in great peace.
That night proving very rainy, I went home with Josiah White, near Alloway`'s creek,
and there lodged.

Next day I had a meeting about two miles over the creek, wherein I had service,
and afterwards was comforted in the Truth; and that evening came to Elsinborough,
and the next morning we sailed cross the river Delaware in a small boat,
and up George`'s creek to Robert Ashton`'s.

On the 24th we had a meeting at Edward Gibbs`', which was very small, but comfortable,
and I staid till the first-day following, and had another meeting, which was larger,
and greatly tendered, and I was much comforted in the presence and power of the Lord.

On the 28th I had a small meeting at New-Castle upon Delaware,
which would have been less,
had it not been for the expectation several were in of seeing William Penn,
proprietor and governor of Pennsylvania, then in the river, in his voyage from England,
in order to exercise his government in person, having been absent many years:
but he did not land there.

Next day had a comfortable meeting at Valentine Hollingsworth`'s, which, though not large,
was very comfortable, and Friends, for the most part, much tendered;
then was at Chichester meeting, which was large and comfortable,
the power of the blessed Truth being over all.
Being informed that the governor was under sail,
and desired me to meet him that evening near Chester, I took horse after supper,
and went to our friend Lydia Wade`'s, by Chester,
and there wailed till he came up in his barge;
and as we had parted in England in much tenderness,
my satisfaction was also great to meet him so well and safe in his own province;
and that night we lodged together, and discoursed on various subjects,
especially on matters of government.

The next day, being the 1st of the tenth month, +++[+++1699]
we went over Chester creek in a boat, to the town; and as the governor landed,
some young men, officiously,
and contrary to the express command of some of the magistrates,
fired two small sea-pieces of cannon, and being ambitious to make three out of two,
by firing one twice,
one of the young men darting in a cartridge of powder before the piece was spunged,
had his left hand and arm shot in pieces.
A surgeon being sent for from on board a ship,
an amputation was quickly resolved upon by Dr. Griffith Owen, a Friend, the surgeon,
and some other skillful persons present; which accordingly was done without delay.
But as the arm was cut off, some spirits in a basin happened to take fire,
and being spilt upon the surgeon`'s apron, set his clothes on fire,
and there being a great crowd of spectators,
some of them were in danger of being scalded,
as the surgeon himself was upon his hands and face; but running into the street,
the fire was quenched; and so quick was he, that the patient lost not very much blood.

Such is the unreasonableness of envy, and of those that are exercised therein,
that some such would gladly have blamed the governor,
because the matter happened on that occasion,
though he could not be any way accessory thereto, the action being without his knowledge,
and contrary to the command of the magistrates.
But as he was above the reach of his enemies, their envy and calumnies could not hurt him.

The governor and his attendants going on board, in order for Philadelphia,
the next morning I went to our friend Robert Pyle`'s, about eight miles; and on the 3rd,
being the first of the week, I went to Concord meeting.
It was large and well; but being kept out of my exercise beyond my proper time,
by one who ought not to have spoken at that time, I had not full satisfaction.

On the 5th I had a meeting at John Bowater`'s, which was very good and tender;
for the Lord was with us, and we parted in much love.
The next day we had a meeting at Thomas Minshall`'s, which was large,
and several were tendered by the virtue of Truth;
but I had not so much satisfaction therein, as in that before, yet it was well.
On the 7th I had a meeting at Bartholomew Coppuck`'s, which was pretty large,
and very tender; after which I was very easy, and much comforted in the divine Truth.
On the 8th I went to Philadelphia, visited the governor, and some friends in town,
and staid there till the 13th, when I went with the governor to Chester,
to their Quarter Sessions of the peace.
The next day we had a meeting at the town, which was large and open,
and on the 15th we returned to Philadelphia, where I staid till the 20th,
and then went to a fourth-day`'s meeting, which fell in course at Haverford-West,
among the Welsh Friends, and Griffith Owen was with me.
The meeting was small, but comfortable.

The next day Radnor meeting falling of course, we went to it.
It was small for lack of notice of our coming, and because of the badness of the weather;
for it rained and froze at the same time, and the fields were as cakes of ice,
and the trees of the woods as if candied.

The day following we took Merion meeting also in course.
It was large and heavenly; for Friends had heard from the former meetings,
that we were going that way, and several from there met us there;
but our chief rejoicing was, that we met with the Lord.
Many important truths of the gospel were opened,
and we were comforted in the blessed Truth, and mutually one in another therein.
After the meeting we went with John Roberts, and lodged at his house that night;
and the next morning returned to Philadelphia,
and were at the meetings there the first-day following.

On the 25th I went to a monthly meeting at Frankford, and being late by an accident,
a Welsh Friend was speaking when I went in,
and before he concluded I was under a great concern to
appear in testimony as soon as he had done.
But immediately after there started up one of the same meeting, and when he had done,
another, and after him another, and then one of them prayed;
and the meeting concluded in this kind of hurry, to my great oppression and exercise.
The weight of the service of the day was laid upon me,
but I could not have any time to discharge it for those who
had no authority in the Truth to meddle at that time.

On the 27th I was at a general meeting not far from there,
where I was much refreshed in the Truth,
and eased of my burden received in the meeting before,
and next day I returned to Philadelphia,
where I remained till the 2nd of the eleventh month,
and then went in company of the governor and
other Friends to a general meeting at Haverford,
among the Welsh;
wherein we met with great refreshment and comfort in the good presence of the Lord;
and next morning to a meeting appointed at Germantown, which was large and comfortable.
On the 4th went to a meeting at Neshaminy, about ten miles off,
where the Lord favored us with a comfortable time in his good presence.
The next day we were favored with a good meeting at the falls; and the day following,
being the seventh of the week, we returned for Philadelphia.

The next day I went to the meeting at Frankford, which was small,
no notice having been given, but satisfactory,
and that evening I returned to Philadelphia.
Here I remained until the 10th of the month,
and then went to the week-day meeting at Darby, which was pretty full.
All that I said by way of testimony was, "`The Lord fills the hungry with good things,
but the rich and full he sends empty away.`"
For that was the case in that meeting; but I had a satisfactory time in prayer,
and that night lodged with our ancient and honorable friend John Blunston, of that place.

On the 13th the governor set forward for Burlington, in West New Jersey,
and I went with him, where we were favored with a satisfactory meeting.
On the 15th we rested at Burlington, at our friend Samuel Jennings`', and on the 16th,
being the marriage day of two of his daughters, we had a large and good meeting,
and on the 18th we went down to the ferry, in order for Philadelphia;
but the river proving impassable,
by reason of the ice and floods by the mighty rains upon a great snow,
we returned to Burlington, and the day after went down again,
and the frost being set in extremely hard the second time, we cut a way through the ice,
and with much labor and difficulty got over,
and went about sixteen miles to Philadelphia.

I staid at Phdadelphia till the 23rd, and then returned to Burlington,
in order for New York, Long Island, Shrewsbury in East Jersey, and parts thereaway,
and landed in Long Island on the 27th, and on first-day we went to Flushing,
where the Lord gave us a good and comfortable meeting.
On the 31st we had a meeting at Hempstead,
and the 1st of the twelfth month I was at the monthly meeting at Flushing,
where several marriages were presented,
and the countenance of the Lord was over us for good;
and the next day I was at a marriage at Newtown,
where we were favored with another good meeting.
I went to New York, and the day following was at the meeting there,
which was pretty large,
though the testimony of Truth has seldom any great prevalence in that place.
At the conclusion of the meeting I appointed another, to be held next evening,
at the house of Thomas Roberts,
where I had been disappointed of my proper time when last there,
and my concern remained till now.
This meeting being large, I had a full and open time therein,
and then was fully clear and easy.

We staid till the 9th, and then went to the Narrows on Long Island, about ten miles,
in order for Stalen Island, but the, passage was full of ice.
The next day we got over with difficulty,
and were often in danger of being interlocked among the huge cakes of ice,
and carried to sea, but by good Providence, landed safe.

Next day we got over in canoes to Amboy, in East Jersey,
and that evening we had a meeting there, and the company of several of the people,
and things were comfortable and well.
The 12th we had another good meeting at Woodbridge, on the 13th another at Piscataway,
and on the 14th we went over the Raritan river on the ice,
and then through the untrodden wilderness, about thirty miles, to Shrewsbury;
where we were favored with a large and comfortable meeting next day.
On the 16th went to Crosswicks, and on the 18th, being the first of the week,
were favored with a large and comfortable meeting there,
where the good presence of the Lord was with us, as at many other times and places,
to his own praise.

On the 19th I went to Burlington, where we met with William Penn,
to our mutual satisfaction,
and on the 21st to a three-weeks`' meeting at Joshua Humphreys`', on Northampton river,
about six miles off, and returned that evening to Burlington.
Here I remained till the 25th, and being the first of the week, was at the meeting there;
and on the 26th I went to a quarterly meeting at Mount-Hope.
It was large, and the Lord was pleased to own us with his good presence.
At this meeting, a woman who had been deceived by George Keith,
and followed him in his apostasy from the Truth,
acknowledged her outgoing with many tears,
and her great loss of the consolation she had formerly enjoyed
In the good presence of the Lord among his people,
and in great humility, tenderness, and true repentance,
desired to be restored and accepted again into unity with Friends;
and she was accepted accordingly, and restored in the spirit of meekness and love,
to her great satisfaction, and that of Friends.
That evening I returned to Burlington, where was a youths`' meeting next day,
which was large and comfortable; and William Penn being likewise there,
we tarried till the 29th, and then went to a quarterly meeting at Neshaminy,
in Pennsylvania, which, though not large, was well;
and that evening we went to Philadelphia,
where I remained till the 5th of the first month, +++[+++1700,]
and then went to a monthly meeting among the Welsh Friends at Haverford,
which was very large, open, comfortable, and edifying.

On the 10th, being the first of the week, I went to the meeting at Germantown;
on the 17th had an appointed meeting at Newtown, in Jersey, which was large and open,
the Lord being with us,
and next day was at the youths`' quarterly meeting at Philadelphia,
which was very large and well.

Having, through the grace of God, finished the visit to Friends and others in America,
which had been incumbent upon me for some years before I came from Europe,
and being ready to return to England, my true and honorable friend William Penn,
finding the affairs of his province very much embarrassed,
became very importunate with me to remain here for some time,
to make him what assistance I could.
I had letters to the like purpose from several judicious Friends of my acquaintance,
both in England and Ireland, who were concerned for the honor of truth,
with regard to the just and reputable settlement of affairs in Pennsylvania;
which had been in much disorder a long time, by reason of the absence of the proprietor;
occasioned by the many and great persecutions and
troubles he had been under on various accounts,
for many years, not only in England, but likewise in his own province,
by false brethren and an apostate company, who deserted the truth of God and equity,
with that anti-christian and willful transgressor, George Keith.
