== Chapter IX

And now, to return to my further progress in my journey and travels:
Next day I went to Scituate, and their meeting being on the 26th at Nantasket,
I was there; where some strangers came in and were sober,
and the Lord gave us a comfortable meeting.

On the 27th of the second month I had a meeting appointed at Scituate;
where came a young man from Connecticut,
who look some exceptions against what I said in the meeting, about infants,
and their salvation by Christ, and about baptism; and,
as we rode towards Edward Wanton`'s, one told me of it;
and I desired the same person to tell the young man,
(being a Presbyterian or Independent) "`that if he
pleased to go to the house of our friend with us,
I would endeavor to satisfy him;`" and he did so.
There I told him,
"`I understood he was not satisfied with something I
had said in the meeting concerning infants;
and therefore asked him what he believed concerning them?`"

He said, "`he believed they were all damned who died unbaptized.`"
Then I asked him, "`if he believed all of them were saved that were baptized,
as he called it?`"
He answered.
No. "`What then,`" said I, "`makes the difference!`"
Then after a pause of silence, he replied, "`that they were all damned.`"
I asked him why he thought so?
He answered, "`because they cannot believe in Christ.`"
I replied, "`neither can they commit sin;
nor can they believe who are baptized and saved, as your first answer implies,
though you have receded from it since.`"
Then said he, "`they sinned in Adam.`"
I answered, "`That as in Adam all die, even so in Christ shall +++[+++the same]
all be made alive.`"
But, said he again, "`they cannot believe in Christ.`"
Then said I, "`do you not believe,
that many ages and nations of people fell under some disadvantages by Adam`'s sin,
who never heard of him outwardly?`"
He said.
Yes. Then said I, "`Why may not they, through the boundless mercy and goodness of God,
manifested by Christ, have the advantage by the death and works of Christ,
who never heard of him outwardly?`"
To this he was silent.

I went on and preached to the auditory,
(some others being present) "`that '`where there is no law,
there is no transgression;`' and little children,
being incapable of any law but that of nature, which they cannot break,
consequently they cannot sin.
And that though, for some time under the law and first covenant with the Jews,
the sins of the fathers were to be visited upon the children, not forever,
but only unto the third and fourth generation; not such as loved God,
but such as hated him; upon which a proverb arose among the people,
that the fathers have eaten a sour grape,
and the children`'s teeth are set on edge;`' but this proverb was to cease,
and was annulled of God, as by the testimony of two of his great prophets,
by whom it is written, in the name of the Lord: first, by Jeremiah,
+++[+++606 years before Christ]
who says '`In those days they shall say no more.
The fathers have eaten a sour grape, and the children`'s teeth are set on edge;
but every one shall die for his own iniquity; every man that eats the sour grape,
his teeth shall be set on edge.`'
And this was to be under the new covenant, come by the Lord Jesus Christ, now in force.
Secondly, by Ezekiel, +++[+++about 112 years after]
who has it much more at large, thus, "`What mean you,
that you use this proverb concerning the land of Israel, saying.
The fathers have eaten sour grapes, and the children`'s teeth are set on edge?
As I live, says the Lord God,
you shall not have occasion any more to use this proverb in Israel.
Behold, all souls are mine, as the soul of the father,
so also the soul of the son is mine; the soul that sins, it shall die.`'
And there are many conditions in this eighteenth chapter of Ezekiel,
respecting the life and death of the righteous and wicked,
and the changes which may happen to both, from state to state, by their own acts,
or omission of known duties, from which little children are exempted;
and the Lord Jesus Christ, the Mediator of the new covenant, has suffered for them,
with all mankind, and declared them innocent, by taking them in his arms, blessing them,
and saying, that '`of such is the kingdom of heaven.`'
And the apostle says, That sin was in the world before the law, but it was not imputed;
so that, though there be a seed of sin in children, which in time may spring up,
unto which, if they join by any sinful act, as mankind commonly and universally do,
they are thereby brought under the law, or power of sin;
not by the transgression of Adam, the common father of all after the flesh,
but by their own, as Adam was.
Yet, until children be capable of the knowledge of good and evil,
by the law of the new covenant of light and grace, sin is not imputed;
and there being nothing to condemn them until they have sinned,
consequently they are all saved; and therefore sprinkling them under the bare words,
'`Father, Son, and Holy Ghost,`' without the power, is a profanation of that Holy Name,
though under pretense to take away original sin, and save them:
which is an act of great ignorance, or willful supererogation; to no purpose,
but to bring honor and gain to proud, covetous, imposing priests;
and is no ordinance of Christ, but an anti-christian forgery, and Popish relic.`"
After this the young man was silent on the subject;
but confessed he now believed there could not be any little children in hell,
but that all of them are saved; and he parted with us in a very friendly manner.

Next day I went to Boston, and the day following, being the first-day of the week,
had a small meeting there; and, on the 29th, arrived a sloop from Bristol,
near Rhode-Island, with John Smith and Thomas Macomber, before mentioned:
and they had leave of the governor to come to us to Daniel Zachary`'s;
where they remained as long as I was there.

On the first of the third month, being the third of the week, Daniel Zachary,
Samuel Collins of Lynn, and I went to the governor,
Colonel Dudley, and requested him to release our friend.
He received us respectfully,
and seemed to lament that we should expose ourselves to such sufferings.
I answered, "`that it was not in our own wills,
but in obedience to the doctrine of Christ, who said unto his disciples,
'`Except your righteousness shall exceed the righteousness of the Scribes and Pharisees,
you shall in no case enter into the kingdom of heaven:`' '`You have heard,
that it was said by them of old time, You shall not kill; and whosoever shall kill,
shall be in danger of the judgment: But I say unto you,
that whosoever is angry with his brother without a cause,
shall be in danger of the judgment.`'
Again; '`You have heard that it has been said.
You shall love your neighbor, and hate your enemy; but I say unto you, love your enemies.`'
Now, seeing anger without a cause, and haired to enemies, is the cause of killing,
and both condemned; and love, which is contrary thereto, recommended and commanded,
then they, who believe and obey this doctrine, cannot kill any; not even enemies.
It is not therefore lawful to us, who believe in the Lord Jesus Christ,
and obey his doctrine, in hopes of eternal life in his kingdom,
which is not of this world, to go to war, lest we should forfeit our portion in him,
and become unworthy of life in him,
by disobedience to his manifest will under the dispensation of his gospel.`"

The governor answered, "`That he was no disputant about religion;
but to tell you the truth,`" said he, "`seeing the judges have given such a judgment,
I cannot tell how to dispense with it; especially now in the time of war,
when every body thinks there is so much need of help, and just cause of war.`"

I urged again the prophecy, "`They shall beat their swords into plough-shares,`" etc.
"`That day,`" said he, "`is not come; for you see many nations are at war at this time.`"
I replied, "`That proves, that though the dispensation of peace is come in point of time,
yet those who are in wars are not in the life or doctrine of Christ,
but in the first and fallen nature; but this dispensation is effectually begun in some,
and will go on, and over all in time,
and whatever it may be to you who have not embraced it, though offered unto you,
it is not lawful for us to whom it is come, to fight.
We desire, therefore, we may not be required to fight, but left to our Christian liberty,
to do, or forbear, as we are persuaded in our consciences is best,
and most suitable to the doctrine and practice of our great Lord, Master and Example,
the Captain of our salvation, who came into the world,
not to destroy the lives of mankind, but to save them.`"

Then said the governor, "`It would be better if all were so;
but if I should release your friends, I should be much blamed by the country,
who have formerly been very hard upon me as well as upon you:
but I endeavor to forget it, and so would I have you.`"

I answered, "`We have no enmity against that people for anything they have formerly,
done or now do to us;
but rather desire they might be brought into a condition of forgiveness by amendment.`"
And added, that since the judges had given judgment otherwise than the law directs,
and execution was already performed further than their own law reaches,
or can support them in, it was in the governor`'s power, as I apprehended,
to release the young men.

Then said he, "`You may have remedy by law, if you are wronged.`"
"`But,`" said i, "`we sue for favor and justice at the fountain-head in this country,
and not to be at the trouble, delay, and expense to send to England about it;
and the justices were told at the same time, and Colonel Byfield, chief justice,
in particular, before sentence, that this was more than the law could justify them in,
he having told us what he intended; and these being poor men,
had not wherewithal to appeal from court to court, in a legal procedure,
which would be very chargeable; and besides, what remedy could be expected from men,
who had acted arbitrarily and contrary to their own laws already.
We therefore desire their release.`"

The governor replied to the like effect as before,
"`That the country would be about his ears if he should do that; but,`" said he,
"`it is a harmless thing to work at the castle; they need not fight there.`"

"`But,`" said I, "`that is an erection for war,
and we cannot be active in such works as may be thought necessary there.`"
And so, finding nothing could be done at that time,
we fell into some discourse on other subjects, and he invited me to dinner with him,
which I excused, and so we parted; and we returned to Daniel Zachary`'s house,
and there I wrote to the governor, inclosing a copy of the judgment of the court,
with some remarks thereon.

To this letter we had no answer while I stayed,
but we heard that the governor had given an order the day before,
that the young men should be taken to the castle,
though himself had told us he had not given any
order at all for bringing them from Bristol;
but the captain who brought them from there would not
have any hand in taking them to the castle,
nor anything more to do with them.
So that they were at Boston when I went from there, on the fifth-day following,
and at liberty, on their own words to be ready upon call.

This afternoon we had a meeting at Boston, where came several of the town`'s people,
and many boys, who were exceedingly rude, but reprehended by some of the older.
The meeting was indifferently well, things being intelligibly cleared on several subjects.
On the 2nd of the third month we had another meeting there,
which was very full of sober people, both from Boston and Charlestown:
the blessed Truth was over all, and many doctrines were opened to general satisfaction.
Infant rantism was discovered to be upon a false foundation:
that the ancestors of that people in New England were once a religious people,
according to the degree of manifestation and reformation that then was:
that they left their native country and its advantages,
for the liberty of their consciences in matters of religion and worship of God;
but that some among them quickly degenerated, though others, I believed,
being faithful to what they knew, held their integrity, and were entered into rest.
But that many in this generation have only the image
and outside of the religion of their ancestors,
without the virtue and life which many of them were in possession of, and enjoyed.
I then exhorted them to turn to the Lord Jesus Christ,
in the dispensation of divine light and life, which is clear from all types, shadows,
and symbols, for as their ancestors lived in the dawning of the day,
they did not see plainly, but as it were men as trees;
and therefore had retained a Popish invention
and relic instead of an ordinance of Christ,
that is, the sprinkling of infants; which is as much Popery,
and as much without Scripture foundation as god-fathers and the sign of the cross.
After which I observed a distinction between the
dispensations of God to the Jews and Gentiles,
though by the same Savior.
Under all which they were exceedingly patient and attentive,
many of them looking surprised and amazed at the opening of things;
Truth having great authority over the people at that time.
It was by much the best meeting I ever was at there, or in all New England before.

On the 3rd we had a meeting at Charlestown, over the Sound;
to which came several people from Boston, who had been at the meeting there.
This meeting was not so large as the other, being a much smaller town,
but very open and well, and several people of both sexes took us kindly by the hands,
and departed in a very solid manner.

That afternoon we went to Lynn with Samuel Collins,
where we stayed that night and next day, and on the seventh of the week,
the fishermen being usually more at home on that day, we had a meeting at Marblehead,
where there is not a Friend; the meeting was pretty large, and the people sober.
The creation of man, his first state of innocence, his fall, present state of nature,
and restoration by Christ the second Adam, were subjects of the testimony;
and the divine Truth had good dominion over the people, who, after the meeting,
were loving, and behaved rather with respect than light cheerfulness or familiarity.
That evening we returned to Lynn.

On the 5th we had a meeting there,
where things opened to the state of a convinced professing people,
and the danger of sitting down in any form of religion and worship,
without the life and power, as well in our meetings as others;
for there is either life or death, truth or error,
in every form or outward appearance of religion:
and where Christ appears in the midst of an assembly, there is life;
and where he does not appear in any degree, death reigns and God is not worshipped.

On the 7th of the month, being the third of the week, we were at a marriage at Salem,
which had been delayed sometime on purpose; but the day proving very rainy and stormy,
the meeting was not so large as otherwise it might have been;
but several of the people of both sexes being there, were generally sober,
and some broken in heart.

At Salem I remained until the 9th, and being the day of their monthly meeting,
it was large; several of the people being there,
were well satisfied with the testimony of Truth therein.
The next day we had a meeting at Ipswich, where there are no Friends; it was large,
several of the people tendered, and generally satisfied,
some of them giving particular demonstrations of it.
The meeting being ended, I stood up and said to the people,
that perhaps some things might not have been well understood, and doubts might remain;
but if any were dissatisfied with anything which had been said, or doubtful in any point,
I would do my best to explain matters to them.
But none appearing we departed in peace, and went to Newbury, and night coming on,
I would have tarried there till the morning,
but there was no provender to be had for my horse,
so that I went with some Salisbury Friends to Henry Dow`'s, and lodged.

Several persons having been killed a little before by the Indians,
I found the people in those parts under great fear and danger,
and the weight of their condition came heavy upon me.

Henry Dow gave notice in the neighborhood of my being come,
and of the meeting to be next day at the house of Thomas Nichols,
in the upper part of the town.
It was a tender meeting, the minds of the people being low for fear of the Indians,
their cruel enemies,
and by reason of the great distress many were in otherwise on that occasion.
It was a dismal time indeed in those parts; for no man knew, when the sun set,
that ever it would arise upon him any more; or, lying down to sleep,
but his first waking might be in eternity, by a salutation in the face with a hatchet,
or a bullet from the gun of a merciless savage; who, from wrongs received,
as they too justly say, from the professors of Christ in New England,
are to this day enraged, sparing neither age nor sex.

The people in those parts, at this time, were generally in garrisons in the night-time;
and some professing Truth also went into the same with their guns, and some without them.
But the faithful and true, trusting in the Lord, used neither gun nor garrison, sword,
buckler, or spear;
the Lord alone being their strong tower and place of refuge and defense,
and great was their peace, safety, and comfort in him.
That evening I had as great peace as at any time in my travels before;
many things were opened suiting the states of the meetings and people.

On the 13th we had a meeting at Salisbury,
where there was a garrison in part of the town,
but I had not liberty in myself to lodge near it; but after some dispute with a townsman,
brother-in-law to a priest, returned late in the evening to Henry Dow`'s,
a place of as much seeming danger as any,
being within pistol-shot of a great swamp and thicket, where Indians formerly inhabited,
and there I lodged, where there was neither gun nor sword, nor any weapon of war,
but truth, faith, the fear of God, and love in a humble and resigned mind;
and there I rested with consolation.

The mother of Henry Dow`'s wife being a Friend of a blameless life,
and living in this same house with them,
let in reasonings against their continuing in a place of so much apparent danger,
and frequently urged them to remove into the town where the garrison was,
that they might lodge there in the night for more safety, as many others,
and some Friends, did.
This her daughter could never be free to do,
believing that if they should let in any slavish fear,
or distrust the protection of the Lord, some very hard thing would befall them.
At length her mother said to her,
that if she could say she had the mind of the Lord against it, being a minister,
though young, she would rest satisfied;
but nothing less than that could balance rational fears in so obvious danger.
But the young woman being modest and prudent,
dared not assume positively to place her aversion to their removal so high;
but at length she and her husband complied with the mother, and they removed to the town,
to a house near the garrison,
where the young woman was constantly troubled with fears of the Indians, though,
while at the house by the swamp, she was free from it, and quiet.

But the mother, having left some small things in the house by the swamp,
and going early in the morning to fetch them,
was killed by some Indians in ambush near the town in this way.
The same morning a young man, a Friend, and tanner by trade,
going from the town to his work, with a gun in his hand,
and another with him without any, the Indians shot him who had the gun,
but hurt not the other; and when they knew the young man they had killed was a Friend,
they seemed to be sorry for it, but blamed him for carrying a gun:
for they knew the Quakers would not fight, nor do them any harm; and by carrying a gun,
they took him for an enemy.

When the town was alarmed, the young woman concluded her mother was slain:
it was not by shot, but a blow on the head.
She did not go into the garrison, but took one of her children in each hand,
and went with them into a swamp or thicket full of reeds, near the place,
where all her tormenting fear left her,
and she was then greatly comforted and strengthened in the presence of the Lord,
and confirmed in her thoughts, that they should not have left their house;
after which she returned to her house by the garrison with her children.
The loss of the mother was much lamented by the son and daughter, and others; but,
as soon as her body was interred,
they went back with their little children to the same place by the swamp,
where I lodged with them when they gave me this relation.

On the 14th of the third month we had a meeting at an inn in Newbury.
There are not many Friends there, but the meeting was very large,
and several persons much broken under the testimony of Truth.
On the 15th we had a meeting at Hampton, at the house of Joseph Chase,
where we had the company of several of the people,
and the truths of the gospel were largely opened; but some of them were very senseless,
scoffing and foolish, and yet several others were sober, still, and attentive,
and the Lord gave us a good time.

Next day we were at their monthly meeting,
where many were tendered in the time of worship, which being over,
we went upon the business of the meeting, which was very small; for it was but of late,
when Thomas Thomson was there, that they had any meeting of discipline,
the elder people being of an old separate sort, and against it;
but the discipline and order being now settled,
the younger and more living are generally zealous for it.
I had many things to say touching the necessity of order in the church,
and the great advantage and safety of it to Christian society;
so that some opposite spirits were fretted,
but the generality of the meeting received it with pleasure, and some of them,
after the meeting was over, expressed their great satisfaction with what had passed,
and all ended in great consolation.

Three Friends from Dover were at this meeting, who went with me the next day,
about sixteen miles, through dismal swamps and thickets.
But the good providence of the Almighty preserved us, and we arrived at Dover,
and that night lodged with Thomas Whitehouse, from under the protection of the garrison,
which was my choice everywhere.

On the 18th, being the seventh of the week, was the monthly meeting at Dover,
where we were comforted together in the Truth.
The meeting there on first-day was pretty large,
considering the great danger the people thought themselves in by coming;
the high-ways and paths being often ambuscaded by the Indian enemy,
who would creep under hedges and fences to get a shot at a man;
many truths were opened there to general satisfaction, and it was a good meeting.

On the 20th, accompanied by some of the most steady and concerned Friends of the place,
we went to visit several others at their houses, and among the rest, Peter Varney,
a substantial Friend, at a house he had a little way in the woods,
and much in danger of the enemy.
We were all under the weight of things, and especially myself,
under the consideration that if I should appoint meetings at places in the woods,
and any person happened to be killed or hurt in coming to, or going from, them,
great blame might be cast upon me as accessory to it, if not the cause,
and the way of Truth likewise be reflected upon by my means.
We had very few words, and none needless, among us;
and I could not see my way concerning any meetings.
In this state of mind, this saying presented itself before me,
"`He that walks in darkness knows not where he goes; but to him who walks in the light,
there is no occasion of stumbling.`"
And when this entered, every doubt and fear vanished, my mind was clear,
my countenance cheered, and the same invisible Power reached the company likewise,
so that they were all cheered up, and we were in one mind.
Then I saw my way clear to appoint meetings for the week, with their concurrence,
at several places where formerly they had been;
all reasonings from the apparent danger of the times being fully silenced in my mind,
and I had no further doubt about it.
On going to dinner,
we were favored of the Lord with a very full and open season of his divine goodness,
to the glory of his great name.
And the meetings were appointed accordingly, namely: On the 21st at Dover;
on the 22nd at Oyster river; on the 23rd at Dover again; on the 24th at Kittery;
on the 25th at Cachecha, to which I walked on foot about two miles through the woods,
with several other Friends; where the Lord was with us, and gave us a precious meeting;
his blessed Truth being over all.
On the 26th, being the first of the week, we had a large meeting at Dover, and very open,
many things being cleared to most capacities, about the supper and baptism,
and several other points.

The Indians having committed several murders, and done other mischiefs in those parts,
many were struck with great fear of them;
and several professing Truth fell under that temptation so far as to take up arms,
and go into forts and garrisons,
and also to take their guns with them when they went about their occasions,
to the dishonor of Truth.
A few standing faithful in the simplicity of it,
keeping their habitations herein day and night, trusting in the Lord,
and willing rather to lose their natural lives for the Lord`'s sake, than offend him,
or give occasion to the enemies of the blessed Truth to triumph,
there happened debates among them;
the unfaithful not being content in their unfaithfulness,
or satisfied in their forts and guns,
sought to justify themselves in that unworthy practice,
condemning the faithful as willful and presumptuous.

I had much to say in every meeting on that subject, to convince them of their weakness,
bring them forward and fortify them in their testimony; and especially to charge them,
that seeing they had not full faith in the arm of the Lord,
they should acknowledge it to be their own weakness, and be humble,
and not seek to justify themselves therein,
lest the Lord should blast them as to his Truth,
and they find themselves also disappointed of the arm of flesh, in which they trusted.
It is commonly the way of such as are unfaithful in any part of the testimony of Truth,
under the influence and conduct of the adversary of souls,
not only to strive to justify themselves in their errors and apostasy,
as if they were true and in the right, but with an air of domination and inveteracy,
to contradict, oppose, condemn, reproach, vilify, and contemn the just and true;
who sacrifice their all for the sacred testimony of Jesus,
and follow the Lamb wheresoever he leads; through life, through death,
over principalities, and powers in the earth, and of hell and the grave,
to the throne of his dominion and glory.

The next morning I had a meeting at Dover with the Friends of the ministry in that place,
which was the most comfortable of all;
and many profitable things were opened in the love of Truth, to our mutual comfort,
edification, and establishment;
and that afternoon I went with Jabez Jenkins through the woods, and the Lord,
to his sole praise, preserved us safe to Hampton.
Alighting at Joseph Chase`'s by the way, his wife, not a Friend, told me their minister,
a Presbyterian, having heard of me, had a great desire to see me,
and she persuaded me to call at his house as I went, being near the high-way,
which accordingly I did.

He was very civil, and we had about two hours conference concerning several points,
especially baptism and the supper; the observance whereof, in their own way and mode,
seemed to be the sum of their religion.
I believe his understanding was reached as to several points of doctrine;
but he seemed unwilling to own it.

I exhorted him, "`Not to sit down under those inadequate and dark shadows,
short of the divine substance, nor to persuade the people to rest there;
for you have no baptism instituted by the Lord Christ;
for the only baptism remaining in his church, is that by his Holy Spirit.
As to the true supper, it is the flesh and blood of Christ,
the soul-quickening Spirit and life from God;
which whosoever eats and drinks dwells in Christ, and Christ in him;
the ministration whereof is in the words of Christ, the Word of God,
by whom mankind are quickened, raised from death unto life,
and live in him and by him forever;
which cannot be effected by any other minister or ministration.
And if mankind could, by any means, eat the flesh and drink the blood of Christ,
in a literal or symbolical sense, that would not profit them; for it is the Spirit only,
by the working of his Almighty power in the soul, which quickens it,
'`the flesh profits nothing;`' for Christ himself places
the sum of that whole divine matter upon the Spirit.`"
He was a mild and temperate spirited man, and we parted in friendship.

On the 28th we had a meeting in the meeting-house at Hampton, which was not large,
and I was kept out of the public service, though under the weight of it,
great part of the time, by a self-conceited, dead, and confused preacher of that place,
and an enemy to the discipline of the church; whom, after I stood up, I reproved,
so that at last the divine life of Truth came over all,
and we had a good and comfortable meeting, all the living being well satisfied.

The adversary does great disservice and mischief
in the church by such dry and dead preachers,
who, being full of themselves only, can and will speak in their own time,
without any regard to the life of Truth, or to any minister of Truth,
though a stranger in the place, their time being always, and what and when they will,
and the true ministers waiting only upon the Lord,
as having no ministry at any time but immediately from him; when the Lord`'s time is,
and the real concern comes from him upon the true minister, the false one is in the way,
hindering the true work and service of the ministry and meetings many times,
loading and grieving the true ministry,
and the living and sensible members in an assembly.
Such oppressing persons and things are permitted, to prevent confusion,
which might ensue from openly reproving them;
and I have never yet seen anyone so much out of the way of Truth,
or anything so unworthy in itself,
but would have a party and supporters to vindicate them.
That night I lodged at Henry Low`'s,
and on the 29th was at another appointed meeting at Salisbury, which was not large,
but good and comfortable.

On the 30th I was at their week-day meeting at Jamaica, which was pretty large,
and very open and satisfactory, both to Friends and people;
for the divine Truth was over all, to the glory and praise of his own Arm,
which gives victory to the weak, humble, and needy, and salvation and redemption to all,
who in sincerity and need call upon his holy Name.

On the 1st of the fourth month we had a meeting at Henry Dow`'s,
which was comfortable and edifying, and several of the people much tendered.
But this meeting also was hurt in the beginning of it by a forward person,
who prayed a long sermon to the Almighty,
with many accusations in it against the people and their ways.

During a great part of this time I had lodged with Henry Dow,
in a place of the most apparent danger in those parts, yet the Lord,
in his great goodness, preserved us from time to time,
overcame our rational doubts and fears, and settled our assurance,
by the working of his Holy Spirit.
All which, his most gracious and tender dealings with us,
I heartily desire may not be forgotten.

On the 2nd, being the seventh of the week, we went up to Haverhill,
and the next day had a meeting there, which being near the Presbyterian meeting-house,
several of them came to us in the time between their forenoon and afternoon meetings,
and some of them were affected and tendered,
and others very sober and attentive to what was delivered.
Though desired by some of the ruder sort of their own profession to leave us,
they would not; and then the others endeavored to haul them away by force.
But the Lord gave us a good meeting, notwithstanding this treatment;
for his powerful Truth reigned over all, to his own glory,
and our satisfaction and comfort.

After this meeting Jacob Morrel of Salisbury informed me,
that he had been with several persons in that town,
in order to have a meeting among them, but they generally refused,
the old stock of persecutors, still ruling there, being much against it;
but the younger people were, for the most part, for it;
and that at last he had gone to one major Pike,
and desired his consent that we might have a meeting in their meeting-house,
to which he assented, and said also, that if we could not have their meeting-house,
we should have his house.
And accordingly Jacob Morrel had given notice of a meeting to be there the next day.

Both Friends and others went to the place about the tenth hour next morning,
and the major seemed very open and free; and seats being arranged,
and many people set down, all of a sudden, and without any provocation,
the major began to be very turbulent and abusive, saying, "`Friends,
if I may call you so, what is your business here?
What means all this concourse of people?`"
To which Jacob Morrel answered, "`We are come here to have a meeting,
according to the liberty you have given us.`"
Then said he, "`You told me of a man that had a message from heaven to the people; which,
if he has, let him say on; but for my part, I did not expect such a multitude,
neither did I intend any such leave to such a people as you are.`"
Then he gave us much ill and abusive language, saying,
we were led by the spirit of the devil.
At length I stood up and told him, that I was the person intended in what had been said;
but as for a message from heaven, in his sense, I had not pretended to it,
but in the love of God, though a stranger,
desired to have a meeting among such of the people as were free to come;
and had been credibly informed we had obtained the liberty of his house for that purpose,
or else we should not have given him that trouble.

Then Jacob Morrel cleared the matter, affirming in the audience of the people,
that he never said anything of a message from heaven, but only that a traveling Friend,
in the love of God, had a mind to see them in a meeting,
which the major had given leave should be there in his house.

The major persisted in his abuses, alleging that Scripture against us,
and applying it unduly, "`Try the spirits, believe not every spirit,`" etc.
I asked him, "`By what means are spirits known?`"
He replied, "`By the Word of God, the Rule,`" meaning the Scriptures.
I replied, "`That the Scripture itself could not be the rule in that case;
for it could not be rightly understood or applied without the Spirit of God,
by which it was given forth; and that by which the letter of the book came and was given,
must, in common sense, be more excellent than the letter, and a superior rule.
Yet we highly esteem the holy Scriptures, and ever have done,
as the best secondary rule in the world, as subordinate to the Holy Spirit,
and as opened and applied by him.
But seeing the Scriptures tell us of some who confess Christ with their mouths,
or in words, but in their works deny him, and that the tree is known by its fruit;
you yourself looks like one of those evil spirits,
who are to be discerned and tried by their evil, reproachful,
and contentious words and works; even by your false accusations, abuses,
and unworthy treatment of us at this time, who are come, not in our own names,
but in the name and grace of the Lord Jesus Christ, to visit this people,
and more especially by your denying and blaspheming against the Spirit of Christ;
by which we are led into all Truth, and not by the evil one,
as you have falsely accused us.
The Scripture which you have hinted at, and misapplied, is this; '`Beloved,
believe not every spirit, but try the spirits whether they are of God;
because many false prophets are gone out in the world.
Hereby know you the Spirit of God:
every spirit which confesses that Jesus Christ is come in the flesh, is of God;
and every spirit which does not confess that Jesus Christ is come in the flesh,
is not of God: and this is that spirit of antichrist,
whereof you have heard that it should come, and even now already it is in the world.`'`"

Now, you have not heard any of us deny that Jesus Christ is come in the flesh;
and I do not doubt but every one here believes and confesses it,
unless you yourself be the exception.
And yet a verbal acknowledgment only,
of the coming of Christ in his body of flesh in that day, is not intended in this place;
for the devils also believe that and tremble, and yet remain devils still.
But this confession must arise from experience of the working, revelation,
or manifestation of the Spirit of Christ,
in the heart and mind of him who thereby believes in Christ, to present salvation,
according to the same apostle, a little below, where he says,
'`Hereby know we that we dwell in him, and he in us,
because he has given us of his Spirit.`'
Again, says the apostle Paul, '`The Spirit itself bears witness with our spirit,
that we are the children of God.`'
And again, '`If any man have not the Spirit of Christ, he is none of his.`'
Whose then are you?`"

This made the old persecutor rage for a time, and he began to ask me from where I came?
and threatened to order me into custody: but finding Truth over his spirit,
and I above him therein, I replied,
that if he had thought fit at first to have refused us his house to meet in,
we could not have blamed him; but since he had once granted it, and now used us ill,
it was unbecoming a man of honor, his office, and a Christian.

The invisible power of divine Truth bound his unruly spirit,
and he began to grow more calm, and offered us his orchard to meet in: but I replied,
"`That seeing he had so spitefully reproached the Spirit of Christ,
in whose name and grace we had come there, by his own concession, to worship God,
visit the people, and in his love, to inform and instruct them;
and had broken his word so evidently, and abused us so very much, though strangers,
and that too in his own house, without any provocation, we should not accept it,
but testify against that spirit which ruled so lately in him,
and against his unchristian practice and behavior.`"
Adding, that he should remember, that he had that day rejected the Truth,
and those who dwell therein.

I went then immediately into the street, where,
seeing a parcel of logs of wood near the side of a house,
I went in and asked the woman of the house, the goodman being absent,
leave to set the logs in order, and sit upon them, and she was very willing;
besides these, we procured some deal boards and other things for seats,
and sat down in the open street by the house-side;
which proved a far more convenient place than the major`'s house,
for a multitude of people came there, and though some were very light, airy, and rude,
most of them were sober, and several tender.
I had a large time in testimony among them,
and several other Friends of both sexes also appeared in public: while I was at prayer,
as I was informed, several of the people were more broken than at any time before.
The Truth was over all, and many things were opened, in the wisdom and authority of it,
to the glory of God, and information and edification of the people,
as well as the comfort of Friends, and to general satisfaction.
It being ended, I stood upon a form, and informed the auditory,
"`That I had travelled in this service, through several nations of the British dominions,
and many of the American plantations,
and had seen several sorts of people of other countries, both rude and civil,
and also both blacks and Indians at our meetings;
and though the generality of the people there
that day had behaved themselves very commendably,
and like people professing the Christian name;
yet some among them had behaved themselves much below all others,
both negroes and Indians, that I had ever seen on such occasions.`"

This proved a sore reproof upon the persons concerned,
the application being plain to many of the auditory;
but though several muttered in private, being ashamed,
they appeared not openly to excuse themselves.
And I further added, that if anyone had anything to object,
it might be most proper to do it before we parted.

Then there appeared one who made his objection at large against womens`' preaching,
saying, that the apostle Paul said to the Corinthians,
"`I will that women keep silence in the church.`"
I answered, that the apostle said, "`Your women,`" only, and not women indefinitely,
without exception; which he denied.
Then one offered him a Bible to look into the place; which he refused, and went off,
pretending to go into a house to fetch one; but never returned.
Then I opened that point more fully to the people, saying,
that no interpretation of Scripture ought to be advanced, or admitted,
which makes it contradict itself, or one part of it another;
or one apostle oppose another, or contradict himself or any of the prophets,
or the matters of fact recorded in Holy Writ,
relating to the public ministry of holy women in the church of Christ, or otherwise.

[.numbered-group]
====

[.numbered]
"`1st Then, you may observe what Joel the prophet said,
many ages before the days of the apostles,
relating to the dispensation of the gospel in this point, and the publishers of it,
'`And it shall come to pass afterward, that I will pour out my Spirit upon all flesh,
and your sons and your daughters shall prophesy, your old men shall dream dreams,
your young men shall see visions:
and also upon the servants and upon the handmaids in
those days will I pour out my Spirit.`'
"`The apostle Peter, being filled with the Holy Ghost,
declares this prophecy to relate to the dispensation of the gospel,
and to begin at the time of the great and glorious
effusion of the holy Spirit of Christ at Jerusalem,
saying, "`This is that which was spoken of by the prophet Joel,
and it shall come to pass in the last days, says God,
I will pour out of my Spirit upon all flesh;`" and so repeats the prophecy at large.

"`Now it is morally certain, by a just and undeniable consequence,
that the Spirit of Christ came at that time upon the holy women present;
and that the women, or some of them, preached Christ to the multitude,
as well as the men, having been his witnesses as well as they;
or otherwise the application Peter made of that prophecy to that instance,
could not have been without exception or a reasonable objection.
For if no women had spoken or preached Christ at that time,
it might have been said that the prophet mentions women as well as men,
daughters equally with sons, but only sons appear in this dispensation and occasion;
and therefore that prophecy cannot relate to it.
But no objection of this nature appearing, it strongly follows,
that some women preached there as well as the men at that time.

[.numbered]
"`2ndly; If daughters were not to preach as well as sons,
handmaids as well as other servants, this prophecy could never be fulfilled,
and consequently must be false; which, to say or think, would be profane and blasphemous,
and cannot be admitted in any wise.

[.numbered]
"`3rdly; The apostle Paul says in that place,
'`Let your women keep silence in the churches, (that is,
in the meetings or congregations) for it is not permitted unto them to speak;
but they are commanded to be under obedience, as also says the law.
And if they will learn anything, let them ask their husbands at home:
for it is a shame for women to speak in the church`' (or congregation.)

[.numbered]
"`4thly; The same apostle says elsewhere, on another occasion,
'`Let the women learn in silence with all subjection.
But I permit not a woman to teach, nor to usurp authority over the man,
but to be in silence.`'

"`By all which it appears, that the apostle was not prohibiting women in general,
when inspired by Christ, and thereby qualified for such services,
to preach or pray publicly in the congregation; but such only as were imperious,
ignorant, and unlearned in the way of Christ and religion; and also talkative,
asking bold and impertinent questions in the congregations, occasioning debates, heats,
contentions, and confusion.
Such were not to be permitted in such evil work, but to be obedient to their husbands,
and learn of them at home in modest and decent silence;
it being a shame both to the women themselves, and the congregations of the faithful,
that such women should be permitted to speak in that manner in a public way,
to disturb them, and hinder their devotion,
and the public service and ministry of such of either sex as were
duly qualified and sent in the wisdom and power of the Holy Spirit.
We, as a people, are of the same mind,
that neither such women nor men ought to be permitted in such destructive work;
but to be silent, and learn there, behaving therein with modesty becoming their sex,
and the nature and end of what they undertake.

[.numbered]
5thly; And as to matters of fact,
proving that women preached publicly in the Christian
congregations in the days of the apostles,
Paul recommended Phebe, a sister in Christ, to the congregation then at Rome,
as a minister, servant, and deaconess of the church at Cenchrea;
and in the same place mentions Priscilla with great respect,
as his helper in Christ Jesus,
which help can refer to nothing else but the work of the ministry,
in which they were jointly and severally engaged.

[.numbered]
6thly; And though Apollos was a man of eloquence, and mighty in the Scriptures,
and had been instructed in the way of the Lord in some measure,
and had taught the things of the Lord zealously and diligently,
knowing only the baptism of John--Priscilla, as well as Aquila,
expounded unto him the way of God more perfectly.

[.numbered]
"`7thly; These instances wherein that great apostle so much approves
the public ministry of these holy and inspired women,
plainly demonstrate that he was not against women`'s preaching;
for then he must have written contradictions in the name of the Lord,
which would have destroyed the authority of his own ministry,
since no man speaking or writing by the Holy Ghost, the Spirit of Truth,
speaks or writes contrary things; and they cannot both be true,
but the one or the other must needs be false,
and suggests a reasonable suspicion that both are so;
which cannot be thought of any apostle of Christ, or his ministry.

====

"`Again, Paul directs how women ought to be attired, as well as men,
in the time of the public exercise of their ministry or preaching;
and if he had been against all women`'s preaching,
and yet given directions how they should demean therein,
he would not have been consistent with himself,
nor one part of his ministry with another; for he says,
'`Every man praying or prophesying, having his head covered, dishonors his head;
but every woman that prays or prophesies with her head uncovered,
dishonors her head;`' and more in the same place to that purpose:
which still further proves that the apostle was not
against womens`' preaching in the congregations,
but fully allowed it.

"`And also Philip, an evangelist, one of the seven deacons,
and an able minister of Christ, had four daughters, virgins, who did prophesy; that is,
they preached the gospel.
And seeing they were daughters of so eminent a minister of Christ as Philip was,
without all reasonable contradiction, not only Philip himself,
but the churches of Christ approved them therein.
Then, if Paul had been against women`'s preaching and praying publicly in the church,
and Philip for it, they would, in that case, have contradicted and opposed each other,
to the confounding of the people, by a contradictory uncertain ministry;
which cannot be admitted by men of truth, and sincere lovers of Christ.
Upon the whole, we must needs conclude, that women as well as men, may,
and ought to prophesy, preach, and pray publicly in the church and churches of Christ,
when thereunto called and qualified by Christ,
under the immediate direction and influence of his holy Spirit and power,
as those holy women were; without which neither male nor female,
under any other qualification or pretense whatsoever, ought to intrude themselves,
or meddle, lest that question, under the displeasure of the Almighty, be asked of such,
'`Who has required this at your hand?`'
and they incur a just punishment in the end.`"

During all this time the people were generally attentive, and seemingly pleased;
but just in the close of the matter, I was attacked, all of a sudden,
by a person who broke into the crowd behind me on horseback,
and by his garb looked like a pastor of the people, and upon inquiry afterwards,
I found he was so.
His first salutation was after this manner:
"`Are you not ashamed thus to delude the people,
imposing upon them false glosses on the Scripture?
I am a stranger on the road, and drawing near this multitude to know the occasion of it,
cannot but appear in defense of truth against your perversions.
`'Tis true, you have a smooth way, a gaining countenance, and advantageous deportment;
but, sir, you look, in all this, the more like an emissary.`"

This being sudden, was a little surprising at first; but Truth being uppermost,
I quickly challenged him to instance any particular wherein I had imposed upon them.

He instanced only in this, where I had said Phebe was a minister of the church; he said,
"`She was not a minister, but a servant, as appears by the text itself in that place;
and it will not bear to be translated minister, as you say.`"

I replied, "`Servant and minister are synonymous terms,
and the word there used may be better translated minister: and if she was a servant,
in what other respect to the church, if not in a public ministry, as a preacher?
For Theodore Beza, in his Latin translation from the Greek,
from which our English translations are made, has it minister, and not servant,
_ministra ecclesiep cencrcensis_; and in the Greek Testament it is _arakoton_; that is,
minister or servant.`"
I asked him before the people, if he would say, upon his reputation as a minister,
as he professed himself to be, that it might not be properly rendered minister,
which he refused; and then, in abundance of assurance, said openly, that I was no Quaker,
but in a flattering way, added, I had more sense than to be a Quaker;
for I had an ingenious countenance, and a deportment importing a better education.
I rejected his flattery, and replied, that he might have had better education,
and ought to have had more justice, than falsely to accuse one whom he never saw before,
and put him upon his proof in that and several other things,
in which he had overshot himself,
in the apprehension of most of the people who heard him.

I observed to the people,
who did not generally understand the meaning of the word emissary,
that it was unduly applied by him; it imported a very high, as well as false charge,
and as such I returned it upon him.
Then he began to charge Jonathan Taylor, then in England, with being a Jesuit,
he having been in that country seven years before,
and instrumental to convince many in those parts,
and thereby had greatly enraged the priests and their envious company against him,
which they had not forgot.
There stood up likewise another man, and said the charge was true.
But I opposed them, telling the people, I very well knew Jonathan Taylor,
and that he was no Jesuit, nor anything like one in any respect;
putting the priest in mind of what dangerous
consequence it might be to himself to charge me,
or any other innocent person, in that manner, since, by law,
it touched the life of the accused, and was highly punishable in the accuser,
if not legally proved.
Then wheeling his horse about, he said he could not stay any longer,
but rode hastily out of the crowd and went off.

The opposition this priest and the others made being for the
most part notoriously false assertions and charges,
without any proof, exposed him and themselves to the just censure of the people,
and rather confirmed them in the truth of what we had delivered,
than hurt the cause of Truth; which we, in some measure of the wisdom and power of it,
had defended against them.

It was now near night, and began to rain, and I took horse and rode to Henry Dow`'s,
being well satisfied that there had not happened any further contest,
which might have unsettled the minds of the people from the effect of those truths,
so largely and plainly delivered among them;
and from that sense of the divine power of the Word of life, of which some of them had,
in measure, tasted.

On the 5th, in the morning, we had a meeting of ministering Friends at Henry Dow`'s,
at which most of the ministers in those parts were present;
and the presence and power of the Lord was eminently with us,
to the glory of his own name; and many things were brought to remembrance,
and opened to our mutual edification and consolation;
for they being for the most part young in that exercise,
things opened in me to my own admiration,
so that it was one of the best meetings I had been at in those parts.
That evening I went again to Haverhill, and on the 6th had a meeting there,
where some of the people came in, and pretty many Friends from Salisbury,
Jamaica and Amesbury, and the Lord was with us.
Many things were opened, and Truth came over all;
yet several of us had felt a hard inward trouble and exercise:
and as soon as I sat down I observed a man in the entrance of the door, who,
looking at me, said, "`You have spoken several true things,
but by what authority did you speak?`"
I answered, "`By the authority of Truth, and then told him our meeting was not ended,
and bid him be silent till it was; and then if he had anything to say, he might be heard.
Upon which he was silent, and soon after Lydia Norton stood up,
and several of the people went out in contempt of her sex,
though she had a ministry as affecting and satisfactory as most women or men either;
and when she had done I concluded the meeting in prayer,
and Truth was over all contrary spirits,
though I felt some further exercise and opposition hatching;
but saw likewise that the end would be to the honor of God and his all-conquering Truth.

The meeting being ended,
a man began to cavil against several things I had said
concerning the Scriptures and the light of Christ;
but the Lord being with me, I came over him, and it settled in my mind,
that he had been convinced of the Truth in his heart, and had rebelled against it.
I went to him where he sat upon a form, many people being in the room,
and looking in his face, said to him in that boldness which truth gave me,
That he had been convinced of the Truth of God in his heart,
and had resisted and rejected it,
and therefore was now become an open enemy and opposer of the Truth in others also,
and that therefore God would reject him forever
if he did not cease from his wicked practice,
and turn to the Lord by speedy humiliation and repentance unfeigned.

This sunk in him as the stone in the face of Goliath, and silenced him at once,
and he remained as a man amazed all the time he stayed in the room after that,
which was above an hour, while I was answering other adversaries, and opening things,
as the Lord assisted me, to several sober inquirers;
and when he went away I renewed the matter openly to him in the audience of all;
but he made no answer, but went off as one deeply smitten in his conscience.

The next day proving rainy, and several of us staying there till the evening,
we were divinely comforted in the love of God;
in which we had many tender seasons together, as at other times and places,
to the praise of his great name, who is God worthy forever.

I went, at the request of John Keeser, a young man who had not been long convinced,
to the priest of that town, a most embittered enemy to the way of Truth,
and all that walk therein in this dispensation,
who had desired to speak with him about his dissenting
from him and the common Presbyterian way.

At our first entrance into the house this priest looked very haughty and ill natured,
and bid us sit down, which we did.
John Keeser told him, he had heard he desired to speak with him,
and was now come to know the matter.
Then he began and said, "`John, I have had a mind to speak with you a long time,
to know your reasons for neglecting the public worship,
and deserting me who have charge over you, to follow the errors of the Quakers,
who deny salvation by Jesus Christ, and follow their light within:
but I could not meet you, though I came to your house on purpose.`"

John Keeser replied, "`I heard of it, and am now come to hear what you have to say.`"
Then said the priest, "`You are a perverse fellow; I wanted to speak with you alone,
in order to reclaim you from the pernicious errors of the Quakers,
who deny justification by Christ; affirming,
that to expect to be justified by the works of Christ without us,
is a doctrine of devils.`"

Then said I, "`Friend,
if you have anything to say to the young man relating to anything he has done or said,
I am here, at his request, to hear it; but if you goest on thus to reflect against,
and falsely accuse that people, I am one of them, and shall oppose you.
I return upon you your false accusations already uttered,
in which you have shown your great injustice, unworthiness and ill nature.
For we do not expect salvation by any other than the Lord Jesus Christ and the Father;
and I challenge you to produce any author approved by us,
that denies the work of the Lord Jesus Christ, done without us, and its efficacy,
for its proper end and purpose, in the redemption and salvation of mankind.`"

Then the priest said, "`William Penn, in one of his books,
called the doctrine of justification, by the coming of Christ without, in the flesh,
the doctrine of devils.`"
I asked him if he had ever seen that book?
and he confessed he had not.
Then I asked him how he could charge William Penn with such a position?
He replied, he had seen it quoted out of the book by Mr. Bugg and Mr. Keith.
"`Francis Bugg and George Keith,`" said I, "`once knew the Truth in some degree,
and made profession of it with us, but took offenses,
first against some particular persons, and then against the whole body,
and became apostates, open enemies, filled with envy implacable.
It is neither safe nor wise in you to take anything upon trust from them against us,
they having been, and still are notorious false accusers, perverters,
and misrepresenters of us, our books, doctrines, and principles.
But I know William Penn, and his sentiments on that subject,
and have read the passage aimed at; which, to the best of my remembrance,
not having the book here, is to this effect: '`To teach that men are justified before God,
by the righteousness of Christ, as wholly without us, while sin is yet reigning in us,
is a doctrine of devils.`'`"

This the priest did not deny, but asked me how we hold it?
I said, "`I shall first premise some things by way of introduction,
before I proceed to a direct answer to the question,
intending thereby to make it more plain in the conclusion.
I begin then with the purpose of God to make man; when he was perfected as man,
God breathed into him the breath of life from himself;
whereby man became spiritually minded; alive in God who is a spirit;
like unto God in his mind or inner man;
the image of him who created him in righteousness and true holiness.
In which state God gave him a positive commandment, not of action, but abstinence,
annexing death and disobedience together.

"`Man, in the beginning, by the voice of God, knew the command of God,
and his duty to him thereby, and believed the Word of God for a time,
which is the divine, eternal, essential Truth;
and as long as man continued in the faith of the Word,
he lived in the divine light and life of it;
stood and remained in the moral image of God, righteous, holy, uncorrupted and undefiled.

"`But when the mind of man, through temptation, disbelieved the Word of God,
in which he at first believed, and adhered unto another voice, which was false and a lie,
the mind of man thereby became corrupted and incapacitated to
enjoy the life and light of the divine Word any longer,
according to the word of God, which says,
'`In the day you eat thereof you shall surely die.`'
"`Thus the fall of man being his departure from the
divine life and light of the eternal Word of God,
his wisdom and power, the redemption of man is his restoration,
and more than restoration, to the knowledge of it, and being re-united with it.

"`And as the love, mercy, and compassion of God was still towards man,
he gave him a promise by the same Word,
'`That the seed of the woman should bruise the serpent`'s
head,`' or that subtle spirit which had betrayed her,
so that in the fulness of time the woman should be instrumental in the restoration;
which accordingly is mercifully fulfilled.
For when the angel of God was sent to Mary, the holy Virgin, he said, '`Hail,
you that are highly favored, the Lord is with you; blessed are you among women.
And behold, you shall conceive in your womb, and bring forth a son,
and shall call his name Jesus.
He shall be great, and shall be called the Son of the Highest;
and the Lord God shall give unto him the throne of his father David:
and he shall reign over the house of Jacob forever,
and of his kingdom there shall be no end.`'

"`But Mary did not at first believe the angel '`And the angel answered and said unto her,
The Holy Ghost shall come upon you, and the power of the Highest shall overshadow you:
therefore also that holy thing which shall be born of you, shall be called the Son God.
And Mary said, Behold the handmaid of the Lord, be it unto me according to your word.
And the angel departed from her.`'

"`And that it might be certainly known, in the fulness of time, unto all mankind,
who this sacred person is, and what is the manner of his coming and appearance,
both to Jew and Gentile, he was to be made manifest unto the Jews first,
under the name and character of Jesus, a Savior, and being anointed of God,
with all the divine in-dwelling fulness, is thereby called Christ; and under both,
is called Jesus Christ, the anointed Savior,
proposed as the object of faith unto all nations.
First unto the Jews in the flesh, as born of the Virgin; and secondly, unto the Gentiles,
as '`the true Light, who enlightens every man who comes into the world.`'`"

[.numbered-group]
====

[.numbered]
1st; The testimony of good old Simeon concerning him, through the Holy Ghost, is,
that he is a Light to lighten the Gentiles, and in that respect,
their light and salvation, according to the promise of the covenant of God aforegoing.

[.numbered]
"`2ndly; The evidence of John, where he is full and express, saying,
'`In the beginning was the Word, and the Word was with God, and the Word was God.
In him was life, and the life was the light of men.
That was the true light which enlightens every man who comes into the world.
And the Word was made (or assumed) flesh, and dwelt among us, (and we beheld his glory,
the glory as of the only begotten of the Father) full of grace and truth.
And of his fulness have all we received, and grace for grace.`'

[.numbered]
"`3rdly; The witness of Christ himself, where he says, '`I am the light of the world;
he that follows me, shall not walk in darkness, but shall have the light of life.`'
Again, '`Jesus said unto them, Yet a little while is the light with you; walk,
while you have the light, lest darkness come upon you:
for he that walks in darkness knows not where he goes.`'
'`While you have light, believe in the light, that you may be the children of the light.`'

====

"`And as the Father has promised and offered his Son as he is that Light,
and as his new and everlasting covenant with mankind,
in order to their restoration and establishment, not of works, but of life; so,
whoever will enter into this covenant with God,
must first believe in him whom God has sent,
and in the way and manner in which he has sent him, according to his promises.

"`Now a covenant is not on one side only, but two at the least; and therefore God,
who is divine eternal love, infinite in goodness and mercy,
is pleased of his own nature and love to mankind thus to send his Son,
the Lord Jesus Christ, into the world, who,
by a voluntary death upon the tree of the cross,
according to the fore-determined council and purpose of the Father,
declared his mercy and free pardon of the sins of the whole world,
upon terms suiting the state, reason, and understanding of mankind: that is to say,
upon faith in God the Father of all, and in Jesus Christ the Son of God,
and repentance from dead works,
as the reasonable and necessary terms required of mankind,
on our side or part of this covenant, that we may be restored to the knowledge of God,
and the Lord Jesus Christ his Son, and made capable of being united unto God,
through Christ the Mediator between God and man in this covenant,
by and through whom we are brought into it,
and stand therein steadfast and immoveable forever.

"`We must then receive the Savior in the way in which he is sent and proposed unto us;
not only as he is offered upon the cross, for the expiation of the sins that are past,
but also as he is the divine Light, enlightening our minds and understandings,
as directed by Christ himself, where he says, '`While you have light,
believe in the light, that you may be the children of light;`' that is, children of God,
who is that light.
So that as Adam fell from the true knowledge of God, and sense of his divine love,
presence, goodness, and other attributes, through unbelief; we,
his posterity after the flesh, may all arise and be restored by faith in Christ,
the second Adam, the Lord from heaven, that quickening Spirit; not into the animal life,
which by nature we already have, and in which we are averse to God and all his ways,
but unto life eternal, that we may all know what that Word means, '`As in Adam all die,
even so in Christ shall all be made alive.`'
And, '`as by the offense of one, judgment came upon all men to condemnation: even so,
by the righteousness of one,
the free gift came upon all men unto justification of life.`'

"`Again,
as to the plain indication and character which the Holy
Scripture has put upon this divine light,
whereby we may know it, even as natural men, by its effects, the evangelist says,
that the Comforter, which is the Holy Ghost, the Spirit of Christ, who is that light,
'`when he is come, (or made manifest) he will reprove, or convince, the world of sin,
and of righteousness, and of judgment.`'
And says the apostle, '`All things which are reproved, are made manifest by the light:
for whatsoever does make manifest is light.`'
Again, '`This is the condemnation,
(of the world) that light (even this light) is come into the world,
and men loved darkness rather than light, because their deeds were evil.`'

"`This is he, that divine eternal Light,
to whom John the Baptist and the apostles of Christ bore testimony;
and in an especial manner the apostle Paul, who was sent by Christ to the Gentiles,
'`to open their eyes, and turn them from darkness to light,
(even unto himself who is that Light) and from the
power of Satan unto God;`' that being so turned,
'`they might receive forgiveness of sins,
and an inheritance among them who are sanctified by faith in him, the Lord.`'`"

During all this time the priest gave me many interruptions,
so that I perceived he was not worthy to know these things, neither could he,
being deeply prepossessed against the Truth, and the light of it.
What I said therefore was principally for the sake of the young man with me,
who had not been long convinced of Truth, and to leave the priest without excuse.
But I having mentioned this Light according to the evangelist,
as the true manifester of sin in mankind, he opposed that as a great error, and said,
"`That light which is in every man gives no knowledge of divine things,
but only of natural, as to distinguish between one plant and another,
and that five is more than three, and the like; and that there is no knowledge of sin,
or of God, or of Christ, or of any divine things, but by the Bible.`"

I replied, "`The Bible itself says otherwise, and that is,
'`No man knows the Son but the Father, neither knows any man the Father save the Son,
and he to whomsoever the Son will reveal him.`'
But read some verses of this first chapter of John the evangelist,
so as to put the Bible in the place of the Father and Son, as you do,
and see how it will read; thus, '`In the beginning was the Bible,
and the Bible was with God, and the Bible was God.
The same (Bible) was in the beginning with God.
All things were made by the Bible,
and without the Bible was not anything made that was made.
In the Bible was life, and the life of the Bible was the light of men.
The Bible was the true light which enlightens every man who comes into the world.
The Bible was in the world and the world was made by the Bible,
and the world knew not the Bible.
And the Bible was made (or assumed) flesh, and dwelt among them, full of grace and truth.
The law was given by Moses,
but grace and truth came by the Bible,`' according to your doctrine.

"`But to return to the true doctrine in the Scripture, seeing that God is the Word,
and the Word is God, and the same is the '`true Light,
which enlightens every man who comes into the world,`' and assumed flesh,
it follows that God, who is omnipresent, is in all mankind, and Christ,
the light of the Father, as inseparable from him in that respect, is in all men.`"

About this time rushed in several of the priest`'s rude company,
who we thought had been sent for by his wife;
and at the sight of this company the priest fell into a sudden transport of rage,
and starting up, said, "`That is blasphemy, O horrid blasphemy!`" appealing,
by his mock gestures of admiration, to his dark ignorant crew.

I being a little moved at this sudden charge before such witnesses,
who might swear anything against me which their enraged teacher might dictate, I replied,
"`What do you call blasphemy?`"
"`What you said is blasphemy.`"
"`What did I say?`"
"`You said, that the light which is in all the heathens, is God.`"

I replied, "`I despise your wicked attempt, and witnesses too,
and retort your false charge justly upon your own head.`"
Then I repeated some of my own words, "`That the Word is God;
that the same enlightens every man that comes into the world;
and that all heathens being men, have in them the same light;
but though this light shines in that darkness, it is not comprehended thereby:
and the saints and faithful in Christ had once been darkness,
and yet became light in the Lord, and walked in that light as children of it,
though some of them had been heathens before this light was revealed in them;
and they were called out of darkness into this marvelous light,
and thereby became the light of the world.
Now, you denying this, must needs hold the contrary, that this Light and Word is not God;
which is directly against the Scripture, and plain blasphemy.`"

Upon this the priest grew a little more calm, and his company seeming surprised,
stood silent, looking seriously upon him and me; and then he replied,
that the light wherewith every man is enlightened is a creature,
as much as a house or a tree is a creature: and added,
that the illumination wherewith every man is illuminated is a creature.

I replied, "`I am not speaking of the illumination, which is an act of the Illuminator,
but of the Illuminator himself.
For there is the Illuminator, who is God; and there is his light,
wherewith he enlightens; and there is his illumination,
which is his act of enlightening in man, who is a creature, and is thereby enlightened.
I do not say the act of God in enlightening of man is God,
but that the Light which enlightens man is God.`"
Then he said again,
"`That the light which enlightens man is a creature as much as a house or a tree.`"
I replied, that he did not rightly distinguish,
for though a tree be a creature of God as well as himself,
yet a house as such is no creature, but an effect of human wisdom and art;
and his distinction between God and his light was blind and heterodox: adding,
"`That seeing God is light, and in him is no darkness at all,
and he enlightens mankind by his own light,
how do you distinguish between God and the light of God?`"

Then he told me, "`I had before asserted the light to be Christ,
as the doctrine of the Quakers;
and to call that light Christ is to deny the true Christ.`"
Then I repeated the words of the text,
insisting that I had all along spoken of God the Word as that true Light;
that the same assumed a body of flesh, and was Christ,
as plain and full as any man could speak from the text;
and that light he had denied to be God or Christ, which is a denying of the true God,
and Jesus Christ the Son of God, who is light.

It was now about the tenth hour at night,
and when we went out several of the priest`'s company came after us,
having none with me except John Keeser, on whose account I went there,
and we were as two sheep among many wolves; for they looked angry, and he told me,
as soon as we came out of the house,
that one of these men being a member of that priest`'s congregation, had said to the rest,
while I and the priest were discoursing together, "`This a cunning fellow;
he is no Quaker; he was a merchant in London, and through ill living spent all,
and was broken, and ran away in great debt; and coming into those parts,
has cheated the Quakers, falsely pretending to be one of them,
to get money from them to make up his deficiencies, and then he will desert them.`"
Upon this, John Keeser showing me the man, I went and reproved him for his falsehood,
and so ready invention of it; and his folly therein,
considering how publicly I am known in several parts of the world,
and even in that country.
But he did not stand to justify himself, but sheered off muttering.

This envious teacher, and blind leader of the blind,
had some time before this appointed a fast and prayer for his
congregation against three great plagues or evils.
First, Because of the cold and backward spring season,
which threatened the withholding of the fruits of the earth, and famine.
Secondly, Against the Indians, that they might not prevail against them,
as they had done;
several of the inhabitants of that town having been some time before killed, and others,
about nineteen in all, taken captives by those savages.
Thirdly, and above all,
for the prevention of the coming abroad and prevailing of the Quakers,
several of his hearers having been convinced of Truth, and left him not long before,
which he had said was a far worse plague or judgment than either of the other;
for they only affected the body, which, though destroyed, the soul might be saved,
but the latter affected the eternal well-being of the soul,
which is of infinitely more value than the body.

But mark the end of this ignorant and envious man; for, as I have been assured since,
there came a party of Indians to that town, and before the dawning of the day,
placing themselves two at least at each door of every house,
and knocking softly as if they had been neighbors,
as soon as any opened the doors the Indians rushed in
and killed the first they met with their hatchets,
and then the rest, and many of them in their beds;
and this teacher happening to be one who opened his door at this time,
an Indian killed him with a hatchet;
at which I did not rejoice when I was informed of it,
though I could not but remember his fast and prayers.

Our day`'s work above mentioned being over, to the glory of the victorious Truth,
and our peace in him, I rested there that night, and the next morning went to Salem,
about twenty-two miles, and there bad a good and peaceable meeting,
several strangers being present, and generally satisfied.
On the 9th I had a meeting at Marblehead,
where several hearts were broken and tendered by the Truth and testimony of it,
and no objections made.

On the 11th, at a meeting at a Friend`'s house in Salem,
we had the company of many of the priest`'s people, who were generally sober:
but I heard the priest of that place had been
railing against Truth and us in his preachment,
whereby he had offended several of the more sober sort of his hearers.

On the 12th I went to Lynn, and was at their week-day`'s meeting the day after,
where came some Friends from Salem and those parts; and we had an indifferent good time.

On the 14th in the evening we had another meeting at Lynn,
to which came a good number of people, who behaved well, being very silent and quiet;
and the next day I returned to Boston,
and the day following I went to Castle Island to see the two young men,
John Smith and Thomas Macomber, before mentioned, still kept there as prisoners;
where they were very cheerful, having been well used beyond expectation;
for though they refused to work at the castle,
none offered to force or threaten them about it.

We went to see the captain of the fort, to acknowledge his civility to our Friends;
and he was very respectful to us.
But in the mean time came several merchants from Boston,
and some members of the assembly, and the chaplain of the castle,
by profession a Baptist; who soon began to bring false accusations against the Quakers,
and to rail against the light;
pretending to give a description of the faith of the Quakers, and prove it erroneous,
allowing us to be moral men, but no Christians.
Upon which I took him up sharply, and said, that a false accuser of men,
and railer against the light of Christ, could not be either a moral man, or a Christian;
and that it was immodest and rude in him,
to pretend to give an account of other men`'s faith, and falsely too,
in contradiction to themselves.

This surprised him a little;
and then I cited out of the first chapter of John the evangelist, a text,
that the Word is God; that he is Light, the true Light,
which enlightens every man who comes into the world; and that the same Word was made,
or assumed, flesh, and was in that manifestation, called Jesus Christ,
the anointed Savior.
This Light is that true Light in whom the Quakers believe;
and therefore you are false and injurious to affirm--as he had then
done --that we believe in the false light of our own fallen nature.
But it growing late, and we having about a league by water to Boston,
and not time to proceed upon that subject, there the mailer ended,
and we landed at Boston after sunset.

On the 17th, being the first of the week, I was at our meeting there,
which was but small at first, by reason of the short notice;
but towards the latter part of it there came in many out of a
meeting-house of the Presbyterians after they had done with their worship;
and things then opened suited to their conditions.
My concern soon turned upon their way of making ministers,
and their bargaining with the people beforehand about their maintenance, being contrary,
both to Christ`'s way of making ministers, and to their maintenance,
and the way of the ancient Puritans, their ancestors in religion;
whose ministers were often called among themselves, gifted brethren,
professing to preach by a gift, or manifestation of the spirit of Christ.
Upon this some of them went out of the meeting;
but the greatest number remained in a solid settled condition, and very attentive.
I understood afterwards,
that those who went out did not go in dislike to what they had heard.

On the 20th day of this month we had a meeting at Cambridge,
where they have a college for the education of youth,
and where many of them are fitted for an artificial and mercenary ministry in their way.
Many Friends and others came at the time appointed.
But the priest of the town, and one that had been sheriff, or some officer in Boston,
did what they could to disappoint us.

The priest sending for the innkeeper, laid before him the great evil, as he called it,
of such a meeting; and at the same time he was made apprehensive of the danger,
as himself told me, of losing his license for that employment,
by which he had his livelihood.
This sheriff likewise went about the town,
discouraging the people from coming to our meeting.
When I came to the house there were pretty many people, but several gone away,
seeing the stir which had been made, and no likelihood of a meeting;
but some Friends sitting together in a room, the sheriff came there,
and having intimidated the innkeeper, he discharged us of his house, as to, a meeting.

Then I asked the sheriff, "`Have you any public office?
for if you have, we will take notice of you accordingly; but if not,
we shall look upon you as a busy-body, and a tool worthy of reprehension.`"
He confessed he did not come there as a public officer.
Then I said unto him, "`Meddle yourself with your own affairs;
you have no business with us, and we shall not regard you.`"
And to the innkeeper I said, "`Since we are thus disappointed of your house,
once granted, yet we shall not altogether impute it to you,
but to the envy of some others,
and must now take our next course;`" which was to search out a place in the street,
where we might sit together without disturbance,
that being as free for us as for any others.

Accordingly we went into the street, not knowing where to pitch; but proceeding along,
we came to a fair dry green, before the buildings of the college,
where was a large spreading oak; and under the shade of that we sat down upon the ground,
and abundance of people came and sat down with us.

Samuel Gaskin, of Salem, stood up first,
and some of the meaner sort of the people were a little rude in their behavior,
but much more moderate and calm before he had done.
I stood up next, and being a stranger, they seemed still more attentive.
Many of the students of the college being there, they were sent for by the president,
and some of them went to him; but others remained in the meeting,
and several of those who went out returned before it was ended.

Various matters were opened concerning the state of man in the fall;
the necessity of freedom from sin in this life,
by the manifestation of the Lord Jesus Christ,
who appears in us the offspring of the Gentiles,
according to the promises and covenant of God, by his divine light, grace,
and holy Spirit in our hearts; and that Christ is that "`true light,
which enlightens every man that comes into the world,`" as well as he
is the "`propitiation for the sins of the whole world.`"

And as to the way that God raises, qualifies, and sends his ministers in his church,
and unto mankind in this dispensation,
it is the same as in the days of the prophets and apostles, and ever will be;
for God changes not, neither does his way change.
It is not by human learning, or in the wit and wisdom of man,
but in and by the word and wisdom of God.
Some of the prophets of old were learned among men, as Isaiah, but generally unlearned,
as Amos, Elisha, Joel, and the rest.
And some of the apostles likewise were learned, as Paul; but generally unlearned,
as Peter, James, John, and most of the rest.
The Word of God, which was in the beginning with God, came unto the prophets,
by which they declared the mind of God unto his people,
and his judgments against the school prophets, who were liars,
and spoke false things from their own imaginations, and not from the Lord;
and sometimes stole the words of the Lord spoken by the true prophets,
and spoke as if the Lord had sent them, and by their false doctrine and lies,
made the people err; but the Lord denied these prophets,
and reproved them by his true prophets.

The apostles of Christ were not appointed or ordained of men, but by Christ himself,
by whose holy Spirit they were filled, being the wisdom of God, and the power of God,
by and from which they preached and reproved the rabbles of the age,
and exposed their evil ways and errors to the people.
Yet human learning, where the mind is fully subjected to the Spirit of Truth,
and subservient to it, may be useful, as in Paul,
but not to be preferred as the chief qualification in that service; unto which,
through the pride and vain-glory of the carnal unmortified minds of self-exalting men,
it has frequently done much more harm than ever it did good.
And, as says the apostle to the Gentiles, "`For you see your calling, brethren,
how that not many wise men after the flesh, not many mighty, not many noble, are called;
but God has chosen the foolish things of the world to confound the wise,
and God has chosen the weak things of the world, to confound the things which are mighty;
and base things of the world, and things which are despised, has God chosen, yes,
and things which are not, to bring to nought things which are,
that no flesh should glory in his presence.`"

And as no fountain can send forth sweet and bitter waters at the same time and place,
I exhorted the students not to sin against God,
by depending upon their qualifications and acquirements in human learning,
and run when God does not send them; and so embitter the minds of the people,
by sowing tares, a false and evil seed, prepossessing them against the truth;
pointing to them some passages in Jeremiah the prophet, where it is said,
"`Thus says the Lord of hosts,
hearken not unto the words of the prophets that prophecy unto you; they make you vain;
they speak a vision of their own heart, and not out of the mouth of the Lord:
they say still unto them who despise me, the Lord has said you shall have peace;
and they said unto every one that walks after the imagination of his own heart,
no evil shall come upon you;`" with great and
terrible threatening against the false prophets,
and then adds,
"`In the latter days you shall consider it perfectly:`" desiring that
they might be so seasoned with the salt of the covenant of life,
that they might escape all those evils;
and that they might come to drink of that living fountain,
which as a river of living water issues out of
those who rightly believe in the Lord Jesus.

I observed also to them, that their ancestors who first came into this country,
and the ancient Puritans of whom they came, were a religious people,
according to the degree of manifestation they then had,
depending upon the gift of God in their ministry, and not upon human literature.
For though some of them had learning, many of their ministers had not,
but were called gifted brethren;
and that those were the men who gathered the congregations in those days,
the bees who gathered the honey,
on the dregs and decays whereof the present drones are now feeding;
and that the glory is departed from their Israel,
which shall never be restored in the form and image left of their ancestors,
but in the life of the Lamb, whom this age have much rejected.
But since their ancestors did it ignorantly,
it should not be imputed to them their offspring,
but only as they rejected the same life.
And if they would receive the truth in the present dispensation of it, that is,
of divine light and grace revealed in the heart,
the story should yet return to New England, and shine brighter than ever,
and more and more unto the perfect day.
I concluded the meeting in prayer to God for them all, both magistrates, ministers,
the college and people; and all ended in solidity and peace, to general satisfaction;
for I did not observe a light or dissatisfied countenance.
I must say for these young students, that they did behave themselves better,
and much more like a moral education at least, no, more like Christians too,
than those at Cambridge or Oxford, in Old England, or at Edinburgh, Glasgow, or Aberdeen,
in Scotland; some of them being very solid, and generally very attentive.
I hope this meeting was of some service among them, and that was all we desired.

The next day I was at an appointed meeting at Boston, which was large and comfortable;
and on the 23rd we had another meeting between Lynn and Boston,
which was small and heavy.

On the 25th, being the first of the week, I was again at the meeting at Boston;
which was large, and the truths of the gospel opened well and clear;
several of the students from Cambridge were there, and were very sober and attentive.

During the forepart of the next day, I had a great load upon my spirit,
but did not then see the cause of it, till after dinner a Friend told me,
the Lieutenant-Governor at the castle in the island,
had been informed that I had spoken against the government,
and against him in particular, in our meeting the day before at Boston,
because of their imprisoning those young men at the castle for refusing to bear arms;
and he had told the Friends there of it, and they sent me word,
that I might set the matter in its proper light.
I perceived this to be the cause of my trouble,
and quickly took a boat and went to the castle,
accompanied by Daniel Zachary and some other Friends.
When we arrived, the Lieutenant-Governor of the castle,
was in company with some other officers; and at our entrance into the room,
ordered us seats with them.
I told him, my last visit had been to my friends, but this was to him;
and mentioning the occasion, said I was come to clear it, and remove the prejudice,
if any had taken place;
desiring him to relate before that company what he had been informed on the subject.
The captain answered, he had been told, that I had in our open meeting,
uttered several hard things against the government, of their cruelty to our Friends;
and particularly of their hard usage by him.

Before I had time to reply, one of the company, a stranger to me, and I think,
an officer, answered, "`There could not be anything in it;
for I did not look like a man that could be guilty of
so mean a thing:`" the captain himself likewise saying,
he did not believe it, but was willing I should know it.
I assured them "`It was all false;
for I understood the nature and end of government better than to vilify it:
and that when at any time we suffered for religion under any government,
either through the tyranny or misunderstanding of the rulers,
we took better methods than that to make them sensible of it;
using our best endeavors to convince their understandings of their mistakes,
and our innocence; but did not rail or rebel against them.
And as to the captain, he had been kind and civil to our Friends, and to myself also;
so that not any disrespectful thought of him had entered me:
but the tenor of what I had said in the meeting,
was something by way of apology for our not giving personal assistance in arms,
now in the time of war; when, in common reason, it might look hard,
that other men should spend their time, blood, and estates, in defense of us and ours,
as they call it, and we do nothing, either for them or ourselves,
on such important occasions; but yet it was not any stubborn humor in us,
as some might be apt to think, or from cowardice, that we refused to bear arms,
but because we take war to be contrary to the doctrine of Christ and the new covenant,
and the tenor, nature, and true end of the gospel;
and dare not fight or learn war for that reason.`"
The whole company being satisfied of the falsehood of that report, and civil to us,
after some further touches upon the subject of war,
and the ill effects of it in the world, especially among Christians, we took leave,
and I went away very easy.

That evening there came to me a young man who had been at the meeting at Cambridge,
and never at one before: he seemed to have been satisfied in general,
but could not understand the doctrine of the light;
but things opening pretty clearly in our discourse, he seemed satisfied both in that,
and also about the sacraments, concerning which he asked me several questions.
He was tender and humble in discoursing, not opposing, but inquiring;
and departed very loving.

On the 28th we sailed down the bay to Nantasket, to a half-year meeting.
We were late, the wind being contrary, and a fog; but were favored with a good meeting:
and parting with Friends of Boston there, I went that evening to Scituate.
On the 29th we had a meeting at Robert Barker`'s, which in the beginning was heavy,
but ended well.
On the 30th we had a meeting at Arthur Howland`'s, at Marshfield;
and Thomas Chalkley was also there,
and persuaded us to go to Robert Barker`'s after that meeting was over;
and we had a good time.

Next day, being the first of the week, we had a large good meeting at Sandwich;
some of the priest`'s hearers being there;
and the day after we had a meeting at Mary Perrie`'s, she being ancient and sick,
and not able to go to the meeting-house.
It was the best meeting I ever had at Sandwich, the love, life,
and wisdom of truth being over all; to the glory of His great power,
who is worthy forever.

On the 5th I was at their week-day meeting at Dartmouth, which was open and well.
On the 7th had an appointed meeting at the house of one Thomas Hadaway,
at a village called Cushnet, north of Dartmouth: he was ensign to a company of militia;
but both he and his wife were ready to admit of a meeting, as at some other times before:
there were many people at the meeting, and generally sober, and some also tender.

On the 11th I had an appointed meeting near that place,
being between Dartmouth and Second; which was large, and indifferent well;
only a zealous Baptist woman was offended at my saying,
"`We had no Scripture expressly for dipping, nor any which necessarily implied it,
but only for going into the water, or washing;`" and for my saying,
"`I knew of none now who washed the feet one of another, as a religious duty;
only the Pope, who, I had been credibly informed,
did once a year wash the feet of some persons, out of a vain show of voluntary humility,
or pretense of compliance with that saying of Christ,
'`If I then your Lord and Master have washed your feet,
you also ought to wash one anothers`' feet.`'
"`The woman muttering about this after the meeting,
I went to her and discoursed with her on the subject.
She had been very angry, as they too frequently are, but went away more calm and friendly.
We had some discourse about bread and wine also.

The next day I was again at the meeting at Dartmouth, which was large and well,
many hearts being melted and tendered; and that evening I returned to Peleg Slocumb`'s.
