== Chapter X

Before I proceed,
I think proper first to give a general relation of the
state of the people in the island of Nantucket,
where I went next after this, with respect to religion at this time.
This small island lies about twenty leagues from the main land of New England,
inhabited by a mixed people of various notions,
and some among them called Christian Indians, but no settled teachers of any kind:
and as poor hirelings search all corners for settled maintenance, several such,
from time to time, had made their attempts upon this people on that account,
but were disappointed; for there was in this island one Nathaniel Starbuck,
whose wife was a wise discreet woman, well read in the Scriptures,
and not attached to any sect,
but in great reputation throughout the island for her knowledge in matters of religion,
and an oracle among them on that account,
insomuch that they would not do any tiling without her advice and consent therein.
When such hirelings came to preach among them,
and attempted to have a settled maintenance, she always opposed it with solid arguments,
as being contrary to the practice of the apostles and primitives,
and the nature of the maintenance of a gospel ministry; but would consent so far,
as that when any preachers came among them that they liked, and stayed some time,
and took pains among them, every family might give to such what they pleased,
for the help of themselves and their families, if they had any, as Indian corn,
or such other provisions as they happened to have at the time to spare; and wool, etc.,
for clothing, but nothing certain or settled.

Finding a concern at this time +++[+++to visit Nantucket,]
on the 13th day of the fifth month, about the tenth hour in the morning,
we set sail for the said island in a shallop belonging to our friend Peleg Slocumb,
and landed there the next morning about six.
At our landing, we went to the house of the widow Mary Gardner; where,
after some refreshment, came to us Nathaniel Starbuck, husband of Mary Starbuck,
before mentioned, and his son of the same name;
and we proposed to them to have a meeting that day;
but there being a court to sit then by special commission,
we found it improper at that time.

On the 15th we had a meeting at the house of Nathaniel Starbuck, the elder;
which was pretty large and open, several of the people being tendered,
and generally satisfied with what they heard and felt of the goodness and mercy of God.

On the 16th, being the first of the week, we had another meeting there;
which was not so large as was expected, by reason of two priests,
an elderly man and a young one; the first from the isle of Shoals,
and the other from Martha`'s Vineyard, who had a meeting near us;
the former being come to try if he could obtain a settled maintenance among that people:
and several being curious to hear this new preacher in the Presbyterian way,
it made our meeting something less than otherwise it might have been;
yet it was considerably large, very open and encouraging;
for the good presence of the Lord was with us.

Many of the inhabitants of this island are convinced of
some points of the doctrine of Truth,
and some of them have been reached by the divine virtue and power of it;
but some other things they do not yet see; and if there were no cross, would,
in all appearance, come generally under our profession.
Some few are for a priest, and to allow him some certain maintenance,
for they walk not by faith but sight, but the majority is against it:
so that one of these, not being able to effect his purpose, went home in a few days,
but the other stayed a little longer.

That afternoon we went about visiting several people at their houses,
and they were generally very well pleased, kind, and respectful; but one justice Gardner,
an ancient man, who had much sway in the affairs of the government of the island,
soon after we went into his house,
uttered some invectives and reproaches against Solomon Eccles, George Fox,
and others of our friends.

He also told us, that thirty or forty years since,
a Quaker at Salem denied that the body of Jesus Christ ever rose from the dead.
I replied, "`That is nothing to us, seeing we hold no such error, nor ever did,
as a people, but deny all such holders and their tenets.`"
Then Susannah Freeborn, one of our company,
informed us what gave occasion to this report,
and that it was one who had been denied by Friends before that time;
so that we were not accountable for his error.
I said to the justice, "`I perceive you have long been convinced of Truth;
but not liking the cross,
you have laid hold on such trifling occasions and pretenses as these,
as excuses for your disobedience,
which will not cover you in that day which is hastening upon you,
when no such fig-leaves will hide you from the face of an all-seeing,
all-knowing Judge;`" and advising him to repent and return to the Truth,
if not already too late, I left him.

On the 18th we had a large good meeting there among the people;
and on the 19th another large good meeting at Nathaniel Starbuck`'s, the elder,
his wife Mary, as before hinted,
being the first in that island who had any regard to the way of Truth as among us;
but now her three sons and daughters, and sons`' wives,
are all in a hopeful way to the knowledge of T`'ruth, and liberty of the sons of God,
with several other tender people at this time in that small island.

To this meeting came Thomas West, the elder of the priests aforesaid,
and stayed till I had done,
though many things had been opened concerning the hireling priests,
the merchants of Babylon, their doctrine and maintenance; yet I heard after the meeting,
that he said, there was a good life and power in that meeting;
but I having spoken of the universal grace of God, through Christ, unto mankind,
he could not receive that part, being prepossessed by false principles against it.

On the 21st we had a meeting at Stephen Hussey`'s, which,
in the beginning of it was a little hard;
but the Lord favoring us with his good presence,
several were melted and tendered under the influence of
the power of Truth before it was over,
and it was a good meeting.
That night I lodged there,
and observed the woman of the house full of questions and fault-finding.
The first thing she began with,
was an expression she said I uttered in some former meeting, namely:
To say that man may be saved in his sins by a bare
belief of Christ`'s outward coming in the flesh,
is a doctrine of devils.
I did not remember the expression, but owned the thing to be true;
and proved to her before the company,
that without the inward work of the Spirit of Christ,
nothing else can complete our salvation.
The next morning she had folded down many leaves
and places of Scripture about predestination,
and I confuted the sense that sect commonly put upon them;
showing her how she misunderstood and misapplied them;
that she was seeking a false rest in her sins, and Christ without his cross,
and knowledge without life; and answered all her questions,
contrary to her desires or expectations;
removing those perversions she had received upon various Scriptures,
both of the Old Testament and the New.
At length, finding herself hedged round, and her way blocked up on every hand,
she burst out into weeping, and endeavoring to hide it, went away a while,
but came again, and we had some more discourse; but she could not say much then,
being in tears again; and still reluctant to submit to the cross of Christ;
she went and came several times, still striving against the Truth in herself and me,
and at last was silent, and sighed deeply, till being quite still for a time,
and new life springing in her soul, she became very gentle, loving, and sweet spi riled,
and would have had us stay longer.
But being otherwise engaged, we returned to Nathaniel Starbuck`'s, the elder.

On this 23rd of the fifth month, being the first of the week,
we had another large open meeting at Nathaniel Starbuck`'s, senior,
where several were tendered and comforted;
but it was a little exercising and painful to my body, for having a sore throat,
and not willing to spare myself, I spit much blood in the time of my ministry.
Esther Palmer and Susannah Freeborn being there, had good service.
They were living ministers, and their testimonies reaching and affecting the people,
all objections were removed against women`'s preaching
without the labor of dispute or contention,
or jar about it.
One night before we returned from this island my sleep was taken from
me under a concern of mind for the settlement of a meeting there.
And though there were two men under the profession of Truth among them,
they had not been faithful, or of good report,
but as stumbling blocks in the way of the weak,
for they could not agree between themselves;
and one of them was at odds with many of his neighbors; so that they were set aside.
The chief instrument pointed to in my thoughts by the Truth for this service,
when we should be gone, was Mary Starbuck, before mentioned, to whom I made it known;
and in the opening and mind of Truth,
laid a charge upon her to endeavor to have a meeting
established in their family once a week at least,
to wait upon the Lord, with all who were convinced of Truth in the neighborhood,
and in the island, as they had conveniency.

This she received with Christian gravity, and it affected her much,
and became her concern.
Having first mentioned it to the Friends who were with me,
I proposed it likewise to her children, who were all discreet young men and women,
most of them married and hopeful; being all convinced of Truth,
they were ready to embrace the proposal.
Then I advised them to wait sincerely upon the Lord in such meetings,
for they had no instrumental teachers,
and assured them that I had a firm confidence in the Lord,
that he would visit them by his Holy Spirit in them in his own time,
if they were faithful, and did not faint or look back.
Accordingly, some time after we departed the island, they did meet,
and the Lord did visit then), and gathered many there unto himself;
and they became a large and living meeting in him,
and several living and able ministers were raised by the Lord in that family,
and of others, to the honor of his own arm, who is worthy forever.

On the 24th of the fifth month we went on board a vessel in order to return,
accompanied by several of our new and tender Friends,
who provided plentifully for our voyage, and parted with us, and we with them,
with great reluctance and tenderness.
Being under sail, there came on a great fog, and the wind abating,
it was almost dark before we arrived in the channel near Old Town, in Martha`'s Vineyard,
an island between Nantucket and the Main, and we anchored there that night.

In the morning we went up to the town,
and after some refreshment had a meeting in the afternoon.
It was small but pretty open; we had another meeting next day:
the truths of the gospel opened well in the life and power of it in good degree,
and the people, though not Friends, seemed well satisfied;
only one man affirmed in the company, that I had said in the meeting,
that water was the only thing proper for baptism; but his neighbor,
who remembered the matter better than he, opposed him therein, for I had not said so;
and meeting with him, I informed him what I had said.
That water baptism is properly washing with water, or going into water;
but water baptism being ended by the beginning or
manifestation of the baptism of the Holy Spirit,
as the dispensation of Christ in his church;
that only remains in force to the end of the world: which none of them opposed.

After the meeting we set sail under a fair and fresh gale, and before it was dark,
arrived safe in Tarpauling cove, where we had a good harbor till next morning,
and then sailed for Dartmouth, where we arrived in the afternoon,
and lodged that night at Peleg Slocumb`'s.

On the 28th we went to Warwick to a yearly meeting,
which was to begin there the day following at the house of Benjamin Barton,
and continued by adjournment to the meeting-house at Providence the next day,
being the first of the week.

On the 31st I was at Greenwich at another meeting,
where I was concerned to speak against various enormities, and especially whispering,
backbiting, traducing and vilifying, as the works of the evil one, and of the flesh;
and after the meeting several persons went to Ebenezer Slocumb,
an honorable and able minister of Truth,
and made confession of things they had unjustly reported against him,
asking his forgiveness.
On the first of the sixth month I had a meeting at a new meeting-house in Narraganset.
It was not large,
but some persons were well satisfied and confirmed in their
understandings against the pernicious doctrine of predestination,
and for the sole Baptism of the Holy Spirit.

On the 2nd we had a meeting in Conanicut, which was small, but tender and comfortable,
and that evening I went over the Sound from this island to Newport on Rhode Island.

On the 3rd I was at their meeting, where likewise was Thomas Chalkley,
and the Lord gave us a comfortable time in his good presence.
I rested two days, and on the first-day of the week following we were both there again,
and the meeting was in the main well: but an inconsiderate busy-body living thereabout,
started up to preach when he ought not,
and thereby altered the whole course of the meeting,
and hurt the true and full service of it, to the grief of many,
and my great burden in particular.

On the 8th we had a meeting at Taunton at an inn,
a Friend having obtained leave of the innkeeper the day before;
and several Friends coming with me to the place, we found the justice of peace there,
as the tool of the priest, laboring with the innkeeper to refuse us his house.
But he proved to be a man of his word,
telling the justice he had promised us his house for a meeting place for that time,
and seeing he did not know of any law against it, he would not disappoint us.
The priest was very angry, and threatened the innkeeper;
and he and the justice did what they could to hinder us.
The priest having boasted some times before how he would
confute the Quakers if any of them should come there,
one Teasdale, a young man of the town, having a love for Friends,
invited the priest to the meeting, telling him, that if he could,
he had now a fair opportunity to confute us;
which he did on purpose to expose the priest in his cowardice.

The meeting being set,
there came a company of the baser sort of the
people into the porch and entry of the house,
and behaved themselves rudely by talking loud, and attempting to read some scurrilous,
false, and libelous matters in an almanac, written by one Daniel Leeds of New Jersey,
a rude, invidious apostate;
but at my request a lawyer went to them and invited them to come and hear with attention,
and if they had anything reasonably and soberly
to object after the meeting they might do it,
and be heard; but that it looked rude and unmannerly to stand cavilling there,
and opposing they knew not what, for they had not yet heard anything to object to.
The more sober sort came in and stayed the meeting,
and the landlord would not allow the rest to come in and read the almanac;
but told some of them who inveighed against him
for letting us have a meeting in his house,
that we had bespoke a dinner, and it was making ready,
and if we had a mind to exercise some devotion in the mean time,
we being a devout religious people, what was that to him or them?
The meeting being fully gathered, in came the ancient, grave and weak justice,
with a message from the priest, if not with words put into his mouth by him;
and being uncovered, addressed himself to me to this purpose, "`Sir,
I do not approve of this; we have a pastor of our own, we need not strangers to teach us;
neither ought any stranger to teach here without his leave among his flock.`"

Then said the lawyer, who was much our friend,
"`If they break any law you may prosecute them by the law;`"
but he knew they had no law then against our meeting.
Then said I to the justice, "`We know nothing of any pastor here,
and we force none to hear us.`"
He replied, "`We cannot help your ignorance.`"
I answered, "`A man may be ignorant of that,
and know more of the things of God than your pastor.
But as to the other point,
'`where there is no law there is no transgression;`' if we break any law,
you may use your authority in prosecuting us;
but if there is no law you ought not to be displeased with us, or disturb us;
for the law ought to be your pleasure in all your office,
so far as it is according to the will of God; nor shouldest you meddle without it.`"

Upon this the justice was willing to be going, saying, "`I cannot dispute.`"
Then I acknowledged his civility in retiring so peaceably,
which was only into a closet adjoining the room where we met,
where he stayed all the time of the meeting.
Many things were opened to the people,
and several of them were tenderly affected under the testimony of Truth.
But in the time of the meeting came in a very angry bigoted member of the priest,
and violently forced his son, being a youth, out of the meeting with a rude voice;
but the power of Truth being over all, so it continued to the end over all opposition,
and the Lord, being with us, gave us a comfortable time in his good presence;
the hireling pastor never appearing to save his flock.
The meeting being over, the lawyer gave me thanks, as their manner is,
for the good counsel given, as he called it, and went away very well satisfied.

Then came in an ancient man and asked me,
"`What Scriptures have you for women`'s preaching?`"
some of our preachers of that sex being there.
I asked him again, "`What is the reason of your question?
Do you ask it as presuming there is no authority for women`'s preaching,
or to be better informed about it?`"
Upon this he was a little down, but recovering his assurance he said,
"`Paul permitted not a woman to speak in the church.`"

I replied,
"`That we ought not to interpret the apostle`'s words in
that place so as to make him contradict them in another;
for that would destroy his authority, and render his testimony null.
But seeing he told the disciples in that day how women
as well as men ought to be qualified and circumstanced,
and how to behave themselves in the time of their public
exercises of preaching and praying in their congregations,
he could not be against all women`'s preaching in the church;
but only against such who themselves lacked instruction.
Besides, if women were not to appear so in the church,
the prophecy of Joel could not be true and fulfilled;
which consequence all Christians ought to guard against,
and be cautious how they oppose the ministry of women more than of men,
being alike included in this prophecy.`"
Upon this the man was silent, and sat down.

But two of his sons being present, one of them asked me,
"`How do you know that it is not a spirit of delusion which you are guided by,
seeing God sends such a spirit upon men as well as a good spirit?`" I answered,
"`That if he had known the Spirit of Truth, which leads into all truth,
he would have known him to be a most self-evidencing Spirit;
and when he appears in the heart, man cannot deny, but assent that he is Truth;
and that the things which he manifests and requires his servants to declare, are true.
But those who asked such questions knew him not, but were in darkness.`"
Then I asked him, "`By what medium does you discover the sun in the open heavens?`"
but he made me no answer.
Then I continued and said,
"`That as the sun is not to be seen or known but by his own light,
neither is the Spirit of Truth, which is divine, eternal light,
known or knowable but by himself; but is self-evident unto every eye which he has opened,
though the children of the darkness of this world do not know him.
He who believes has the witness in himself; and he who has not the Spirit of Christ,
who is that Truth, is none of his.
But as to God`'s sending a false spirit to deceive men, I know what you means,
as all such ignorants do, that none can be certain by what spirit they are led,
whether truth or error;
which is the same as to say that all mankind are in utter darkness,
and must ever so remain.`"
Then I demanded his proof.
He instanced in the false prophets, mentioned in the first book of the kings of Israel,
where it is said, "`Who shall persuade Ahab, that he may go up and fall at Ramoth Gilead?
And there came forth a spirit, and stood before the Lord, and said, I will persuade him:
and the Lord said unto him.
Wherewith?
And he said, I will go forth,
and I will be a lying spirit in the mouth of all his prophets.
And he said.
You shall persuade him, and prevail also: go forth and do so.
Now therefore behold,
the Lord has put a lying spirit in the mouth of all these your prophets;
and the Lord has spoken evil concerning you.`"
"`Here,`" said he,
"`is a plain instance where God sent a lying spirit
into the mouths of all the king`'s prophets,
to delude and deceive him; and what has been may be.
How then can you be certain whether you are deluded or not?
Whether led by a right or wrong spirit?`"

I answered, "`Ahab was a very wicked king,
and did evil in the sight of the Lord above all who went before him,
and yet the Lord allowed him to reign in his course.
For the punishment of Ahab for the neglect of his duty,
in not executing the will of the Lord upon Benhadad, a wicked, boasting blasphemer,
the man the Lord had appointed to utter destruction, for his pride, injustice,
and wickedness-- and Ahab killing Naboth, and continuing in idolatry,
filled up the measure of his wickedness; and then the Lord, by the prophet Elijah,
denounced his heavy and just judgments upon him--and
that the word of the Lord might be fulfilled upon Ahab,
who trusted in his four hundred lying state prophets,
he allowed a lying spirit to deceive them all, and himself also,
to his final destruction.

"`And as such false state prophets are always flatterers and
deceivers of kings and great men of the earth,
having their persons in seeming admiration, because of the interests, preferments,
and advantages to themselves; so here we have a notorious instance of it,
and in the behavior of Zedekiah, the most impudent and chief-like of all these impostors,
to Micaiah, the prophet of the Lord, smiting him on the cheek, with a lie in his mouth,
before two kings, without reproof from either of them,
especially not from Ahab his own prince;
which partial indulgence and approbation is common with such rebellious persecutors,
throughout all generations to this day.

"`But this being a particular case,
it no way follows that God sends a false spirit to
deceive such as sincerely seek unto him for help,
direction, and counsel, in the way of life and salvation; but on the contrary,
invites all mankind to look unto the Lord himself, as he is the only true God,
for salvation.

"`Again, the apostle Paul, speaking of the Gentiles,
and the means which God had afforded them for the knowledge of himself,
and by which also they had once known the Lord, has declared, '`That when they knew God,
they did not glorify him as God, neither were thankful;
but became vain in their imaginations, and their foolish heart was darkened,
and they degenerated into miserable idolatry:
wherefore the Lord gave them up to their own lusts and vile affections;
and even as they did not like to retain God in their knowledge,
God gave them over to a reprobate mind,
to do those things which are not convenient;`' and then
enumerates a large black catalogue of mortal sins,
as the consequences of their apostasy from God, and knowledge of the Lord,
which once they had.

"`It was not therefore, nor is it, by any act of God,
or sending a spirit of delusion into mankind, or any of them, that they are deluded,
deceived, or misguided;
but it is the natural consequence and fruit of their own neglects, acts, and doings.
For the Lord Jesus Christ gives encouragement unto all to come unto the Father for help;
for after he had reasoned tenderly with his hearers after the manner of men,
he draws this gracious conclusion, '`If you then being evil,
know how to give good gilts unto your children,
how much more shall your heavenly Father give the Holy Spirit to them that ask him.`'

"`By all which, duly considered,
it appears that the Lord does not send a spirit of delusion upon mankind, or any of them,
to deceive them, without a cause in themselves, especially those who believe in him,
and seek unto him for the help and guidance of his Holy Spirit;
but for the punishment of the ungodly,
leaving them to themselves and their own lusts for their punishment and destruction,
when they have forsaken the Lord,
and not that the Lord sends a lying spirit to deceive
any before they have grievously offended him,
as you have falsely suggested.
But as for such as seek the Lord in sincerity and truth, desire after and love him,
he hears their prayers, and grants them the greatest of all blessings,
the manifestation of his Holy Spirit,
to lead and direct them out of all evils and errors, into all righteousness,
truth and salvation.`"

And finally,
recommending this perverter to the consideration
of what the apostle wrote to the Corinthians,
"`Examine yourselves whether you be in the faith; prove your ownselves:
know you not your ownselves, how that Jesus Christ is in you,
except you be reprobates,`" the whole matter ended, to the honor of Truth,
and satisfaction of many present: and after refreshing ourselves at the inn,
we went back that evening to Wiccopinsit.

On the 9th we went to the island of Cananicut, and lodged at William Anthony`'s;
but cathng at Samuel Hicke`'s in our way, we were stayed there by a shower of rain,
and in the mean time came in a Baptist teacher,
who pleaded the necessity of the temporal sword in general,
and the continuance of it under the gospel, as well as before,
under the plea of the suppression of robbers, thieves, murderers, and other evil-doers;
and when any one nation would unjustly invade another, and her rights, property,
and privileges, and the like.
So that since the magistrate and the king as chief, bears not the sword in vain,
it is not wholly taken away by the gospel,
so long as magistracy and the cause and use of it remain.

To this I answered, "`That the sword there mentioned is not, as I apprehend,
the sword of destruction, nation against nation,
nor the necessity of the use of such a sword in the civil state;
but rather the sword of civil justice in execution of civil, temporal,
and righteous laws; whereby the civil magistrate is, or ought to be,
'`a terror to the evil-doer,`' and a safeguard '`and praise to them that do well.`'`"

He replied, "`That if force by arms were not to be used in apprehending thieves, robbers,
and the like, they would not submit to be apprehended and brought to justice,
but go on by force to do those mischiefs.`"

To this I replied, "`That magistracy being God`'s ordinance,
to that and other good and salutary ends,
the countenance of God is with the civil officer in his
just prosecution and execution of his office;
and the Almighty having power over all spirits,
for the most part strikes a terror into evil-doers, when they are discovered and accused;
so that it is very rare that any such resist the powers by force, but by stealth only;
however, force may be allowed in this case, in the hand of a proper officer,
whose business and duty it is to apprehend and bring to justice furious and
incorrigible transgressors of the righteous laws and ordinances of men,
for the just rule of countries and nations.
But here I must distinguish between the kingdom of Christ,
and the kingdoms of this world,
in order to bring this matter to a right understanding and period.
The Lord, by several of his prophets, has foretold,
that '`he shall judge among many people, and rebuke strong nations afar off;
and they shall beat their swords into plough-shares, and their spears into pruning-hooks;
nation shall not lift up sword against nation, neither shall they learn war any more.`'
This is to come to pass under the new covenant,
of which Christ the Son of God is Mediator; whose doctrine tends to the fulfilling of it,
in all who believe and obey the gospel.
For he says, '`You have heard that it has been said,
You shall love your neighbor and hate your enemy; but I say unto you, love your enemies,
bless them that curse you, and do good to them that hate you;
and pray for them who despitefully use you,
and persecute you;`' and that we should not be angry without a cause, nor lust.
He preached perfection, which being accomplished in the heart,
by the holy powerful spirit of him who preached this doctrine,
all lust is taken away and destroyed, whether it be the lust of the flesh,
the lust of the eye, of vain-glory, of power, domination, self-exaltation, covetousness,
the lust of envy, revenge, preeminence, and the like;
which are the ground and cause of wars and fightings among carnal men,
as says the apostle James, '`From which come wars and fightings among you?
Come they not from hence, even from your lusts that war in your members?
You lust and have not; you kill and desire to have, and cannot obtain; you fight and war,
yet you have not, because you ask not.
You ask and receive not, because you ask amiss, that you may consume it upon your lusts:
you adulterers and adulteresses,
know you not that the friendship of the world is enmity with God.`'
Now, though the kings and kingdoms of this world may be at war,
and do and will make war one against another for a time,
until the kingdom of Christ shall prevail over all,
yet the kingdom of Christ is not of this world, as he said unto Pilate,
'`If my kingdom were of this world, then would my servants fight,
that I should not be delivered to the Jews; but now is my kingdom not from hence.`'`"

To this he answered, "`It was only at that time that they would not fight;
for if they had fought he had not been delivered to the Jews to be crucified;
and so his death and all the advantages of it to mankind hindered;
but upon any other just occasion they might, and still may fight.`"

To this I replied, "`That this interpretation, or rather perversion,
of the Scripture would destroy the kingdom of Christ in the nature, infancy,
and end of it; denying Christ to have a kingdom on earth,
but only during his bodily presence with his disciples,
and would obstruct the way for accomplishing the
prophecies of the prophets before mentioned,
and oppose the whole tenor and end of the gospel.
For the proclamation of the celestial harbingers of the Prince of peace,
in notifying the birth of the First-born into the world, for the salvation,
not destruction of the lives of mankind, was after this manner,
'`Glory to God in the highest, and on earth, peace, good will towards men.`'
And as he was sent into the world in the love of the Father,
so the whole tenor of his doctrine and example of life, was for peace and love;
and in that love, and the power and divine virtue of it,
he yielded up his life and body on the cross,
an adequate propitiation for the sins of the whole world,
and to declare the mercy of God to all mankind.
And it is evident that the Jews crucified Christ in defense and support of this
same political principle and doctrine of self-defense by war and fighting,
for the preservation of their state against the Romans;
though their policy proved their utter ruin in the sequel.
For, said they, after Christ had raised Lazarus from the dead, '`What do we?
For this man does many miracles; if we let him thus alone, all men will believe on him,
and the Romans shall come, and take away both our place and nation.`'
This plainly demonstrates that the disciples and
followers of Christ were not of fighting principles,
but otherwise taught by him to love even their enemies;
and his whole doctrine tended to mercy, peace, truth, and love.
And the apostle says concerning the members and
subjects of the kingdom of Christ in this world,
'`For though we walk in the flesh, we do not war after the flesh;
for the weapons of our warfare are not carnal, but mighty through God,
to the pulling down of strong holds, casting down imaginations,
(or reasonings) and every high thing which exalts itself against the knowledge of God,
and bringing into captivity every thought to the obedience of Christ.`'

"`Again; '`Finally, my brethren be strong in the Lord, and in the power of his might:
put on the whole armour of God,
that you may be able to stand against the wiles of the
devil for we wrestle not against flesh and blood,
but against principalities, against powers,
against the rulers of the darkness of this world,
against spiritual wickedness in high places:
wherefore take unto you the whole armour of God,
that you may be able to withstand in the evil day; and having done (or overcome) all,
to stand.
Stand therefore, having your loins girt about with truth;
and having on the breast-plate of righteousness,
and your feet shod with the preparation of the gospel of peace: above all,
taking the shield of faith,
wherewith you shall be able to quench all the fiery darts of the wicked;
and take the helmet of salvation, and the sword of the Spirit, which is the Word of God;
praying always with all prayer and supplication in the spirit,
and watching thereunto with perseverance, and supplication for all saints.`'

"`As the kingdom of Christ is not of this world, he governs by his Holy Spirit,
in such as are not of this world, but are given him out of the world; over whom,
in all ages, he has ruled in righteousness, peace, and joy in the Holy Ghost;
and shall yet reign, till by degrees,
the '`kingdoms of this world shall all become the kingdoms of our God and his Christ.`'
Then shall be an end of all rule and dominion but that of God and the Lord Jesus,
who shall be all in all among the children of men.
But until this be finished by degrees, as it is now begun and proceeds,
the kingdom of Christ on earth is, and shall be, as at the first, a holy nation,
a royal priesthood, a peculiar people, zealous, not to fight and destroy,
or to meddle with the kingdoms or rule of the world, but of good works;
against whom there is no law founded upon righteousness and truth.
But until this be accomplished, nation will lift up sword against nation,
and they will learn and exercise war: but as to us, we,
through the mercy and goodness of God,
are of those in whom this prophecy is begun to be fulfilled,
and we can learn war no more.
For as a nation shall not he born in one day,
so this prophecy shall not be fulfilled in one generation, but in several;
but being fulfilled, shall not fail any more forever.
As for you, who are yet in wars and fightings, how are you his subjects,
or members of his holy nation, his royal priesthood, or peculiar people?
Or how can you be, until you obey his doctrine, to love God above all,
to love one another in him, to love your enemies, do good unto them who hate you,
and pray for them who despitefully use and persecute you?

"`We who do not fight with carnal weapons, meddle not with you who do,
otherwise than to persuade you to leave that off,
and be enlisted under the saving banner of the Prince of peace;
to believe in the divine light of the Son of God;
to come out of the spirit of this world, in which is all trouble,
into the Spirit and kingdom of Christ, in whom there is perfect peace.
If you will not do this, we must leave you to fight one with another,
until you are weary, and have the recompense of it, one by another,
in the natural consequences of that destructive evil;
with this caution of the apostle nevertheless, '`That if you bite and devour one another,
take heed lest you be destroyed one by another.`'
I desire you to leave us to the Lord, to serve him unto whom we belong,
and fight in his name, under his banner, against the enemy of our souls;
against whom we find warring sufficient, and fighting enough daily,
though we war not among you to destruction,
nor one with another to the breach of peace.`"

By this time the spirit of my opponent was overcome, and he was much under for a while;
but he began a discourse about water baptism, in which I found him subtle,
but not weighty.
We went through John`'s water baptism, and anti-christian rantism;
through dipping to sprinkling,
and from the whole to the one only permanent baptism of Christ by the Holy Ghost,
into one holy body the church; "`which is his body,
the fulness of him who fills all in all.`"
The particulars whereof I omit here, and closed the dispute on this manner:
"`That since the apostle Paul was the minister of the gospel to the Gentiles,
and completely furnished with every qualification
necessary to a gospel minister in so great an office,
and yet had no commission to baptize with water,
it is great vanity and presumption in anyone in this age to pretend to it.`"
This striking at the foundation of the image, he could not bear any longer,
but hasted away, and we parted friendly; which I ever endeavor to do with all men,
after every contest for the faith and doctrine of Christ;
my chief aim being to convince and open the understandings of the auditors.

On the 10th I was at a monthly meeting for worship, at Portsmouth.
It was an open and good meeting, wherein the honest-minded were comforted,
but the hypocrites rebuked.

On the 12th I had an appointed meeting at Joseph Wanton`'s, which was not large,
being a very rainy day, but a pretty good time, through divine goodness.

On the 13th, being the first of the week, I was again at the meeting at Newport,
which was large, and the best and most tender I was ever at there.
The doctrine of the gospel opening large and clear, and Truth in full dominion,
and reigning over all, many hearts were broken,
some of whom were bold and hardy commanders of privateers,
to the great honor and glory of the Lord;
which happened at this expression in the authority of Truth: "`Many there be,
who are so courageous as men,
that they dare go on undaunted in the face of great ordnance and cannon shot,
as contemning death,
and yet are subdued and laid prostrate by the soft and
melting reaches of that divine love in their hearts,
in which the Lord Jesus laid down his precious life for the redemption of their souls.`"

On the 14th I went over to Boston-Neck, where I met again with Thomas Chalkley,
who this last week had been visiting Narraganset;
and we having a meeting appointed in our way homeward, were there the day after.
It was an open, good meeting, wherein many were comforted and confirmed in the Truth;
and after this we went on our way, about ten miles, to Samuel Perry`'s, and there lodged.

On the 16th we went from there to an inn near Seabrook ferry, where we lodged;
and the day following proving very rainy and heavy riding, we put in at Killingsworth,
where, in my first journey I had a dispute with an old priest,
but had no discourse with any of the people at this time, they all being now silent.
We set forward, but the rain returning, we stopped in Guilford,
where being made sensible of the operation of Truth,
and the love of it springing in my heart, I waited to know the mind of the Lord therein,
and found a concern for a meeting in that place, with which I acquainted Thomas Chalkley,
who liking the proposal, I told the innkeeper,
we desired to see some of the more sober sort of the place, and have a meeting with them.
But he apprehending that the magistrates, by means of their minister, might blame him,
and do him some injury for letting us have a meeting in his house,
as Is common with them in such cases,
I desired him to put some he could trust upon giving notice among the neighborhood,
that there were some Quakers there, and that would draw them,
and so we might have an opportunity with them;
for though as to ourselves we feared not anything they could do,
yet we were cautious lest we should draw our landlord into blame,
or hazard of his license to keep an inn,
which they might have deprived him of on that account.
This took with him, for he was a frank-tempered man, and no enemy to us,
and accordingly there came pretty many young men in the evening,
and I put the landlord upon acquainting some of them
privately with our inclinations to have a meeting,
to which they were very ready;
and then I stood up and informed them openly what we desired, and they were all willing.
I told them our way is to sit in silence, to wait upon God,
until he might please to open something in our understandings for the auditory;
so we all sat still.
The Lord having prepared my heart, I was quickly ready,
and had a very open acceptable time among them; but not being long,
Thomas Chalkley concluded the meeting in prayer,
and some of the people declared openly their satisfaction with what had been said;
and we had great peace in the Lord.

We lodged there that night, and on the 18th went forward to Stratford, where, at the inn,
in the next room to us, was a very rude company of the professors.
Independents or Presbyterians of that place,
who kept almost in continual laughter and folly.
As we were at supper our landlady and a young woman came in,
and the young woman addressing herself very modestly to us, said,
"`I have often heard of your people and profession,
but have never seen any of you before,
and I would be heartily glad to have some discourse with you about your principles;
for I desire to know the Truth, and to follow it.`"
Then said I, '`Remember what the Lord Christ said, '`Woe unto them that laugh now,
for they shall mourn:`' and what the wise man said,
'`It is better to go to the house of mourning than to the house of mirth.`'`" Adding,
that God was about to turn the world upside down,
that that which is uppermost may be brought undermost,
and that which is lowest may be exalted above all;
and this put them both to deep and solid silence.
There are a sort of people in the world, who profess to believe in Christ the Son of God,
yet live jovial, airy, wanton, unconcerned, unmortified lives,
and know no cross to their own wills, but live and die in their sins;
and yet dream of salvation at last, though under woes from Christ,
the Savior of all who believe in, follow and obey him.
As man`'s own lusts reign in him, in his natural state,
and the evil one rules him therein, and is uppermost,
so the Lamb slain from the foundation of the world, and crucified in Sodom and Egypt,
the dark, ignorant,
and depraved hearts of wicked and ungodly mankind lies undermost in themselves;
but the Father of all, by his divine Light and Almighty power, is come,
and coming more and more, to destroy the kingdom of darkness and ignorance,
and the power of it,
and to advance and establish the kingdom and reign of
Christ the Lord in the hearts of mankind,
of the increase of whose kingdom, government, and peace, there shall be no end.
It growing lale, we soon after retired to our bed-chamber, recommending them to the Lord.

On the 19th we went on to Mamaroneck, where we arrived late in the evening,
and the next day, being the first of the week,
we came in time to the meeting at West-Chester, which was small but comfortable:
after which we went to visit John Forrest`'s family, his wife, son,
and daughter being ill, and that evening we went over the Sound into Long Island.

On the 21st we went to Flushing, where, being well received, and kindly entertained,
we stayed till the next day, and then had a meeting at Jamaica,
which was small but comfortable.
And here we went to visit our friend Samuel Bownas,
still a prisoner for the testimony of Truth,
by the lawless arbitrary imposition of that government
under the administration of Edward Hyde,
commonly called Lord Cornbury, an unreasonable and unjust persecutor.

On the 24th were at their week-day meeting at Flushing, which was large and well,
and on the 25th went to William Mott`'s, at Great Neck,
where the Lord favored us with a comfortable meeting.
On the 26th, being the seventh of the week, we were at the quarterly meeting at Weslbury,
which held two days, and was very large and well,
only some of the ranters in that island came and made a howling and hideous noise,
as is common with them, and thereby gave the meeting some uneasiness;
but all ended in great quietness and peace.

On the 28th I went to New York,
and the day after had a good and comfortable meeting there;
and though I had heard two months before I went from home,
that Lord Cornbury had threatened,
if ever I should come into his government he would confine me
for some words falsely alleged to have been spoken by me in my
testimony some time before in Maryland,
about the national church of England, her sacraments, order and catechism;
yet I did not go one step out of my way, nor at all shun him about it,
either in my going into New England, or now in my returning,
though the common talk in those parts was,
that a warrant was lodged in the sheriffs hand against me,
at whose house I was several times; yet the Lord preserved me free,
to the service and honor of the blessed Truth.

On the 30th we set forward for Philadelphia, and the same day got into East-Jersey,
and the next day we rode fifty miles, to Burlington.

On the 1st of the seventh month we reached Philadelphia, where, that evening,
and the next two days,
I felt more oppression of the Seed of life in my mind than in all my
travels among the blind professors and savages of New England;
the cause whereof may the Lord himself discover, reprove, judge, and amend,
as in his wisdom and goodness it may please him, to his own glory: to whom,
for his mighty aid, many preservations, and great love in this journey,
be immortal honor, says my soul.
Amen.

Having finished my journey to New York, Long Island, Rhode Island, and New England,
on the 1st of the seventh month, 1704,
I settled to the business of my offices at Philadelphia;
in the mean time visiting meetings in town and country, as occasion offered,
until the 14th day of the second month, 1706; and then I went from Philadelphia,
in order to visit Friends in Maryland, Virginia, and North Carolina,
and next day was at Concord meeting, where the Truth was over all, and things were well.

On the 17th we arrived at William Pecket`'s in the afternoon; who,
though not under the profession of Truth, yet was zealous for it.
He received us kindly;
and after some discourse with him about a meeting to be next day at his house,
he was very willing, and sent his servants several ways to give notice in the country.
In the mean time he told me of some discourses which had happened
among the people in those parts since I had been there before.
For in a great meeting on that side the bay,
I had reminded the members of the national church of England,
sincerely wishing the eternal salvation of all who bear that name,
of what they call their baptismal vow and promise,
made in so solemn a manner before God and man, when they are sprinkled,
which they think is their baptism.
For they promise and vow three great things by themselves or sureties; 1st,
To renounce the devil and all his works, the pomps and vanity of this wicked world,
and all the sinful lusts of the flesh.
2ndly, To believe all the articles of the Christian faith.
And 3rdly, To keep God`'s holy will and commandments,
and walk in the same all the days of their lives.
This they are taught by their priests to believe is their duty;
and as by their public confession, +++[+++in the service]
they had broken all those promises and vows, and from being made members of Christ,
children of God, and inheritors of the kingdom of heaven, in their baptism,
have so far renounced it, and are so far fallen and degenerated from that state,
as to have erred and strayed from the ways of the Lord like lost sheep;
followed too much the devices and desires of their own hearts;
offended against the holy laws of God;
left undone those things which they ought to have done,
and done those things which they ought not to have done;
so that there is no health in them, but are miserable sinners; and so, from time to time,
year to year, to the end of their days still go on in the same way,
and yet call Christ the Son of God, their Lord and Savior, and God their Father,
though they live and die in their sins,
and are not saved from them if this confession be true.
Therefore it might justly be charged upon them by the Almighty Creator,
and Judge of the world, as perjury in his sight; and for that cause,
and in zeal for their salvation,
and if possible to awaken them from this deep sleep of sin,
I had cried aloud in that meeting, "`O sinful nation!
O perjured people! how greatly do you provoke the Most High,
by so great apostasy and departure from the living God?
how can you answer the Lord in that day which is
hastening upon you as the wings of a glorious morning?`"
Exhorting them to repent, amend, return to the Lord, and perform their vows,
with all diligence and sincerity, that so their great sins might be pardoned,
blotted out, and remembered no more.
And William Pecket informed me that John Hall, a man of eminence in that country,
and a member of the national church at that time, and some others,
had been at that meeting, and were offended with what I had said,
and that he had invited him to this meeting, which was held at William Pecket`'s,
according to appointment, where all were still and attentive,
and we were favored with divine goodness.

After this meeting I inquired of John Hall,
what it was he and some others had taken offense at in that meeting some time before?
And it was chiefly what is before related, and that they thought I had said,
if a man was once in a good state, it was impossible to fall from it.
As to the first, I had said no more in effect than William Perkins,
a learned minister of the church of England had written,
William Pecket happening to have the book by him,
in his Exposition of Christ`'s sermon upon the mount, page 151,
which appears in these words: "`Having showed what perjury is, with the kinds thereof,
let us see whether we be free from it.
After examination it will appear that men`'s lives are full of perjury;
for where there is much swearing usually, there cannot but be much perjury;
because they who swear in their common talk do forget their oaths,
as they do their communication.
But say we are clear from perjury, yet are we in danger of God`'s heavy judgments,
for the breach of our vow in baptism; wherein we promise to believe in God, to serve him,
forsaking the world, the flesh and the devil.
Now, the breach of this vow is as ill as perjury;
for therefore may baptism be called a sacrament,
because of the oath and vow which a Christian makes to God therein:
for the word sacrament properly betokens the oath which
the soldier makes to the captain for his fidelity.
The breaking of Joshua`'s oath unto the Gibeonites, by Saul, caused three years dearth,
and was not satisfied but with the blood of seven of Saul`'s kindred.
And Zedekiah`'s perjury to the king of Babel,
was one cause of the Lord`'s fierce wrath against Jerusalem and the princes thereof Now,
shall one man`'s perjury cause such judgments, and shall we not think,
that among other sins, this our perjury unto God, in breaking our vow in baptism,
brings upon us God`'s heavy wrath, by plague, famine, and unseasonable weather?
Wherefore, let the consideration hereof persuade us to temperance,
and a more conscionable care of performing our vow unto God.`"

"`Thus this learned and religious author of the church of
England makes the breach of their baptismal vow plain perjury,
or full as bad, incurring the wrath and judgments of God; and if so,
then O perjured England!
In saying whereof, you may see I said nothing in that meeting, on that head,
but what a famous minister of your own church had said and written long before;
and you are not yet reformed, but still remain the same, or like miserable sinners.

"`And as to your alleging I said.
If a man were once in a good state, it was impossible to fall from it, I did not say so;
for that would have contradicted what went before;
and I have ever been of another judgment.
And besides, that would have been contrary to the known testimony of the Scriptures;
for Adam and Eve were once in a good state, yet fell from it:
and the author to the Hebrews teaches,
that '`it is impossible for those who were once enlightened,
and have tasted of the heavenly gift, and were made partakers of the Holy Ghost,
and have tasted the good Word of God, and the powers of the world to come,
if they shall fall away, to renew them again unto repentance;
seeing they crucify to themselves the Son of God afresh, and put him to an open shame.`'
And again, '`For if you sin willfully,
after that you have received the knowledge of the truth,
there remains no more sacrifice for sins,
but a certain fearful looking for of judgment and fiery indignation,
which shall devour the adversaries.`'
So that you have all mistaken what I delivered in that meeting,
and have not done well to lie under it so long, but should have told me of it then.`"

They owned that, and I added:

[.numbered]
"`1st;
That if mankind in their infancy were members of Christ, they were without sin;
for '`he is holy and separated from sinners;`' and is not head of a sinful unclean body,
but of a pure holy body, the church, '`which is his body, the fulness of him,
who fills all in all.`'

[.numbered]
"`2ndly; He who is a child of God, is born of God; '`and he who is born of God sins not,
nor can do so; for the Seed of God remains in him, and he cannot sin.`'

[.numbered]
"`3rdly; He who renounces the devil and all his works, at the eighth day of his age,
or sooner, according to your canon, renounces all sin, for all sin is of the devil.
And if he forsakes all sin at that age, he never sins at all if this be true.

[.numbered]
"`4thly; He who keeps God`'s holy will and law, and commandments,
and walks in the same all the days of his life, never sins.
And if all this be done, it is perfection indeed.

[.numbered]
"`5thly; He who believes all the articles of the Christian faith, cannot err in faith;
but seeing faith is not man`'s acquisition, but the gift of God,
no man can procure it for himself,
much less can he procure or falsely engage it for another.
But if it were true that all this were had upon your baptism, as you call it,
in your infancy, then see what a miserable and dreadful state you are fallen into;
for after all this, even in your old age,
instead of renouncing the devil and all his works,
you confess that you have erred from the way of God like lost sheep;
and it is the spirit of error, not of Christ, which leads mankind astray from God,
for the Spirit of Christ leads into all Truth.

[.numbered]
"`6thly; You say that you have offended against the holy laws of God,
and such offenses are not of Christ, but of antichrist:
you have left undone those things which you ought to have done,
and done those things which you ought not to have done;
and from members of Christ and children of God, you are become miserable sinners:
so that if that be true which you pretend to in your baptism, how great is your fall!
He who is an inheritor, is in possession of the inheritance, and enjoys it,
as he who is only an heir waits in expectancy, until the time of inheriting shall come.
If then you had been inheritors, that is, possessors,
of the kingdom of heaven in your infancy, with Christ and bis holy angels,
you must now needs be fallen from heaven, and from Christ,
and from the company of the holy angels of God, with the apostate angels,
and in communion with them, by your own assertion.
How then shall you be restored, being as the withered branches,
out of your own mouths condemned, cut off from the body of Christ,
from being members of him?
For the members of Christ, while such, are not miserable sinners,
but are redeemed from all iniquity by the life of Christ,
and purified as a peculiar people unto God, zealous of good works,
and not devoid of saving health; but healed by Him, who is the health of all nations,
to be testified in due time.
But the doctrine you are taught cannot be true;
you are not regenerated nor born again in your rantism, as you ignorantly imagine;
your dark and blind leaders have caused you thus to err, and lead you thus astray;
for if you had then been born again of the incorruptible Seed and Word of God,
so many gross sins would not now be reigning in you,
since he that is born of God sins not.`"

To this purpose was what I had said, and now repeated to them,
who did not contradict anything, but were very kind; and John Hall in particular told me,
that though he had been blamed for allowing a meeting in his house,
yet he had stood his ground over them who did so,
having a right to entertain in his own house,
such sober persons and neighbors as he thought fit.
I parted with the company in very good friendship after
some more conversation with other strangers,
who had also been in this meeting.

That evening we went forward and lodged at John Hay`'s, he and his wife being friendly,
and on the 19th had a meeting at Patapsco;
we were favored with a sensible degree of divine life with us,
but not in such aboundings as at some other times.
There had been several lately convinced in those parts,
and particularly Richard Cromwell, who had been a justice of the peace,
and having been convinced of Truth the last time I was that way, he stands nobly,
having divested himself of all those troubles attending that office,
and other encumbrances in the way of true religion.
On the 22nd, being the first of the week, we were at West-River meeting,
which was shut up and hard in the beginning of it; but at the pleasure of him who opens,
and none can shut, and when he shuts, none can open the way and fountain of life.
Truth broke through at last, and all was well and comfortable.
After the meeting we went up to Samuel Galloway`'s, his wife lying very ill; with whom,
and the family and some Friends, we had an open comfortable time in prayer,
the love of God and his good presence being plentifully with us;
and she was much refreshed, saying, That though the Lord had not been lacking to her,
yet she had not had such a season of his goodness for about six months before.

On the 26th I went to West-River meeting, which was very comfortable;
and on the 27th I had an appointed meeting at Herring creek,
which was likewise very open, and Friends generally satisfied.
On the 29th, being the first of the week, we had a meeting beyond the river Paluxent,
where no meeting is settled, nor had there been any in that place but once before,
it was indifferently large, being at an out-settlement, and was quiet and well.

On the 1st of the third month the quarterly meeting being at Samuel Chew`'s,
we were there: it was well and open, and on the 6th, being the first of the week,
we had a comfortable meeting at the meeting-house at the Cliffs,
the powerful and blessed Truth being over all.

On the 7th we went to Patuxent,
and the day following had a meeting at the meetinghouse there;
and on the 9th had a meeting at the Cliffs.
On the 10th had a meeting about three miles beyond the river Patuxent,
near Benedict-town, where there had not been any before, nor anywhere near it,
many of the people in those parts being Papists.
It was not large nor open, but rather dark and heavy, yet quiet;
and many truths of the gospel were delivered to them, as the Lord gave utterance,
and we left all friendly.

Henry Child having come with me as my companion from the Cliffs,
we set forward after this meeting, accompanied by several Friends,
about half an hour after three, in order for Virginia.
It rained fast all the way, with lightning and thunder,
and we got to a house near Cedar-Point, on Potomac river, about eight in the evening,
all thoroughly wet, and weary with our heavy clothes; but having very good quarters,
we were well refreshed by the morning, and though plentifully entertained,
our clothes dried, and horses taken care of,
yet the master and mistress of the family would
not receive any recompense from us for it.
And he added to this civility; for this hospitable person, by himself and servants,
set us over the river next day, about seven miles, and up a creek, in his own boat,
and all free,
only what we could persuade him to allow his servants
to receive as a gratuity for their extraordinary pains.

On the 13th, being the first of the week,
had a meeting about a mile and a half in our way, at the house of one Benjamin Berryman.
It was not large, but Truth was over all, and the people were very loving and respectful.
That night we lodged with a Friend,
who sent one with us next day to guide us to our friend Elizabeth Wilson`'s,
about forty miles.
Our guide not being perfect in the way, we missed it several times,
and were almost swamped twice;
but through good Providence we arrived safe there in the evening,
where we had good reception and accommodations.

The 15th proving very wet, we stayed till about the second hour afternoon,
and being then fair we set forward, with a guide to Matapony river, about four miles,
and on the other side we missed our way;
but about nine we arrived safely at Charles Fleming`'s, beyond Pamunliey river,
about twenty-six miles in all, where we were kindly received,
and the next morning he sent notice of a meeting
to be at the meeting-house called Black-Creek.

According to appointment the meeting was held on the 17th. It was not large nor open;
but appointing a meeting there the next day, it was larger, and a good meeting,
the truths of the gospel opening fully, to general satisfaction.

On the 19th went to a monthly meeting at William Porter`'s, and had some service there.
On the '`20th, being the first of the week, we were at Curies`' meeting,
which was large and well,
and that night and the next we rested at Jane Pleasant`'s.
On the 22nd we had a meeting at James Howard`'s,
which was pretty large, and things opened well, and the people were sober,
so that we had a comfortable time among them.

On the 23rd, in the morning, we set forward with a guide to James`'s river,
and got well over at Merchant`'s Hope; proceeding from there, we missed our way,
but growing uneasy, and observing the course of our way to alter,
we turned into a by-road, and coming to a plantation, found our error;
but being directed by a planter, we got well that evening to Benjamin Chapman`'s,
near fifty-six miles.
On the 24th we had a meeting there, which, for the time, was pretty large,
and very open and well.

On the 25th we had a meeting at Levy-Neck, but not large, nor very open; on the 27th,
being the first of the week, we went to the meeting at Chuckaluck,
which was indifferent large and open; but as I was speaking,
there came a very strong and sudden blast of wind upon the broadside of the house,
and the door being open, the house was thereby the more in danger,
and sensibly moved by the violence of the storm.
Many of the people were surprised, and some went out;
but the power of Truth being over all fear in me, I continued speaking,
advising the people to be still; and the meeting being quieted and settled,
the Truth came over the assembly.
The storm abating in a short time, many drew nearer, and were very attentive;
for the matter was weighty, it being concerning the coming of Christ in the flesh,
his office, and end of his coming, both outwardly and inwardly, as a sacrifice for sin,
and destroyer of the kingdom of Satan in all who believe;
and the meeting ended comfortably.
Several trees were broken by the violence of the storm, but no other hurt done there.

On the 29th we had a meeting at the Western branch of Nansemond,
which was pretty large and very open; and on the 30th at the Southern branch;
which was not large, but open.
There Henry Child, who had hitherto been with me from Maryland, returned homeward;
and I went that evening with Nathan Newby towards Carolina.
On the 3rd we had a meeting at his house, which was not large, but comfortable.

On the 1st of the fourth month I went to Carolina, about fifty computed miles,
to Gabriel Newby`'s; and on the 3rd day following, being the first of the week,
I was at the meeting at Perquimans, which was large and comfortable.
On the 5th had a meeting at our friend John Barrow`'s, at Yawpin, beyond the river;
and that evening returned with Francis Tomins.
On the 6th, being very rainy, and exceeding bad way, I went down to Little river,
and lodged that night with Thomas Simons.
On the 7th we had a monthly meeting at Caleb Bundle`'s, at New-begun-creek, in Pasquotank;
where the Lord gave us a very open and comfortable time in his good presence.

On the 8th we had another meeting, which was likewise comfortable.
On the 9th we went over the creek in the morning to Emanuel Low`'s,
and returned from there to Joseph Jordan`'s, in order to settle a meeting place;
which being done by the concurrence of several of the most competent Friends,
we returned to Emanuel Low`'s, where we met with the governor of North Carolina,
with whom I had much discourse about matters of government,
and informed him of the methods taken by some in other governments,
in favor of us against the severity of some laws;
and found him very inclinable to favor us so far as could be consistent with his office.

On the 10th, being the first of the week, we went over the river Pasquotank,
about four miles, to a meeting at the house of our friend William Ross, which was large,
many of the country people being there, who were generally sober;
and the Lord opened the truths of the gospel very clear, and with authority.
On the 11th the Lord favored us with a very open comfortable meeting, at Little river;
and on the 12th we were at Upper Perquimans;
which was the best and most powerful meeting I had in that country.

On the 14th I was at the monthly meeting at Chuckatuck, in Virginia,
which was very large, and the whole public exercise of it fell on me.
On the 15th we had another meeting there, which was also large;
and many things opening in my testimony concerning
government and the duty of magistrates,
according to the Holy Scriptures;
I understood afterwards there were three in that station present,
who came to me after the meeting was over, and were very respectful;
though the priests and people, who buy and sell,
and make merchandize concerning matters of religion, were sharply reprimanded.

On the 17th, being the first of the week, I went back to Nathan Newby`'s,
about twenty miles, to a meeting appointed there; which was large and open,
truth being over all, to its own glory.
After this meeting, in our return towards Robert Jordan`'s,
the company was overtaken with the greatest storm of lightning, thunder, and rain,
that ever I remember,
insomuch that the fire and water seemed to be commixed in their descending upon us,
and the thunder so sharp and sonorous, and so near,
as if it had been bombs splitting among us.
I being the second in the company,
looked back several times to see if any were slain behind;
and it was attended with a stifling smell of sulphur.
The storm abating a little, it was quickly renewed with equal show of terror;
so that we had it for the space of about eight miles in the first,
and three in the latter, in a very dreadful manner;
but the Lord preserved us from all harm.
And though I was a little concerned at the first approaches of
such terrible threatenings by an irresistible Power,
though from natural causes; yet feeling the Creator near, who ordains it,
and that his all-ruling authority was above and over it and all things,
I was much comforted in him, in the time of the most apparent danger:
for which I was greatly thankful to the Lord, and for our preservation;
for we observed that several great trees had been shattered to pieces by it.
We got safely to Robert Jordan`'s that evening; but another storm,
with much thunder and rain, coming on in the night, awakened the family,
and some of them were much terrified, the thunder breaking out near the house;
but upon my retiring inward, I had great peace in the good presence of the Lord,
and his holy love ejected all fears.

On the 19th had a meeting at Benjamin Small`'s, near that place, which was large and open,
several points of doctrine, especially baptism, and redemption from sin in this life,
being cleared to demonstration; and several magistrates being there,
all was quiet and satisfactory.

On the 20th I was at a meeting at Dirasconeck, which was pretty large,
but in the beginning of it something hard and dark,
till the divine and powerful truth arose as the sun,
and dispelled the thick clouds and fog.
In the time of silence my mind having been exercised about the
multitude of religions professed by mankind at this day,
and how remote they all are, save one, from the truth,
the first thing I had to say was this: "`What religion are you of, friend?`"
And my face being directed at the time towards a person of some distinction,
several thought I had spoken only to him; but upon this followed proper matter,
and a distinction between names and things;
that false names are often imposed upon true things, and good names given to bad things,
with respect to matters of religion.
And among other things I had occasion to speak
of a necessity of freedom from sin in this life,
in order to fit us for the kingdom of God.
As soon as I sat down,
the same man stood up and offered some opposition to some part of what I had said;
but I desired him to be silent at that time, for our meeting was not over;
and he sat down quietly.
Then another Friend stood up and preached truth;
and during that time I perceived this opposer was as a snake in fair colors,
lying as hid in the grass, to wait an opportunity to bite and vent his venom:
and the Friend having finished, I concluded the meeting in prayer.

Then this opposer stood up again, and directing to me, said, "`Sir,
I have heard you with much attention, and you have delivered many very good things:
do you mean by freedom from sin in this life, such a freedom,
as that a man never sins after he has embraced the Christian religion?`"

I answered, "`No; for as all are liable to be tempted after they have believed in Christ,
and known something of the work of conversion, a man may sin,
if he adheres to the temptation of the adversary;
but if he continues to follow the Spirit of Truth, which leads into all truth,
he sins not after he is converted; but through the grace of God, come by Christ the Lord,
may live a holy, righteous, and sinless life, to the end of his days in this world.`"

"`I ask you then,`" said he, "`did ever the apostle Paul sin after he was a minister,
and converted?`"
I answered, "`That is not a proper question to ask me concerning a person so eminent,
departed this life so many hundred years ago, and to whose secret failings,
if any he had, I was never privy; but if I may judge of him by his doctrine,
as I think I ought,
and that he was one in conduct and attainment with what he preached unto others,
I may justly conclude, he lived free from sin,
from the time of his conversion to his dying day.`"

He replied, and said, "`I prove out of the word of God,
(pulling out a Bible) and from the apostle`'s own words,
that he was a sinner after he was an apostle.`"
Then said I, "`Who are you?
Of what communion professing the Christian religion?`"
for I perceived by his accent he was a Frenchman by nation.
He replied, "`I am in communion with the church of England,
and am a minister of that church.`"
"`Do you then, said I, here in this auditory,
many of whom are of the same communion with yourself,
charge the apostles of Christ with sin?`"
"`Yes,`" said he, "`the apostles were sinners after they were converted,
and at the same time when they were ministers of Christ,
as I shall prove by the seventh chapter of Paul`'s epistle to the Romans,
and first chapter of the first epistle of John.`"
Then he read, "`For we know that the law is spiritual; but I am carnal, sold under sin:
tor that which I do, I allow not; for what I would, that do I not; but what I hate,
that do I.`" Again; "`If we say we have no sin, we deceive ourselves,
and the truth is not in us.`"

I answered, "`It is not to be admired that the people are so ignorant,
who have such blind guides:
but the saying of Christ is now again fulfilled in this generation,
as it was among the Jews who crucified him; '`If the blind lead the blind,
they shall both fall in the ditch.`'
I have told the auditory already, in the testimony I have borne among you,
that the apostle in that epistle to the Romans,
was not speaking of the state which himself or any of the
apostles were in at that time when he was writing it;
but personating and representing the state of the Jews under the law,
and of mankind in general under the fall of the first Adam,--in whom
all mankind were virtually included at the time of his transgression--
before they came to the belief and knowledge of the Lord Jesus Christ,
the second Adam, and Savior of all.
For in that epistle the apostle proves that both Jews and Gentiles were under sin;
the Gentiles by breaking the law written in their hearts,
and the Jews by transgressing the law of God by Moses:
so that the transgressing Jews and Gentiles were all alike sinners in the sight of God,
the Creator and Judge of the world: and more especially the Jews,
as having had the knowledge of the law of God, both inwardly and outwardly,
and had transgressed both dispensations, by which their sins were aggravated;
so that every mouth is stopped, and all the world become guilty before God:
for God has concluded them all in unbelief, that he might have mercy upon all.
Again; the Scripture has concluded all under sin,
that the promise by faith of Jesus Christ might be given to them who believe.

"`But are mankind still to remain in their sins to the end of their days,
and inherit tho kingdom of God at last?
No surely; for if we live and die in our sins, where Christ is gone we cannot come.
Though all have sinned, and come short of the glory of God,
yet being justified freely by his grace, through the redemption that is in Christ Jesus,
whom God has set forth to be a propitiation, through faith in his blood,
to declare his righteousness for the remission of sins that are past,
through the forbearance of God; this redemption is not, by any means,
consistent with sin, but contrary to it; for Christ came not to save us in our sins,
but from them; and sin being the cause both of defilement and condemnation,
until that is taken away there can be no redemption or salvation.

"`It was not the hearers only of the law who were just before God;
but the doers of the law should be justified; and by their fruits men are to be known.
And says Christ the Lord, '`Not every one that says unto me Lord, Lord,
shall enter into the kingdom of heaven,
but he that does the will of my Father who is in heaven`' The workers of iniquity,
though they have prophesied in his name, and cast out devils,
and done many wonderful works, will be disowned at last, and commanded to depart.
And it is the hearer and doer of the savings of Christ who
shall stand upon the rock when the time of trial shall come;
and every one who hears the sayings of Christ and does them not,
is on the sandy foundation, and all his building shall fall,
and be destroyed with great destruction in the end.

"`The advice and doctrine of the apostle James is, that we be doers of the word,
and not hearers only, deceiving our ownselves; and faith without works is dead.
The Son of God has said,
speaking of the law and of the prophets,`' Whosoever
therefore shall break one of these least commandments,
and shall teach men so, he shall be called the least in the kingdom of heaven;
but whosoever shall do and teach them,
the same shall be called great in the kingdom of heaven.`'
He closes that chapter of his excellent and most moral doctrine,
with this preceptory exhortation, '`Be you therefore perfect,
even as your Father who is in heaven is perfect.`'
Such therefore who are perfected, through the eternal Word who preached this doctrine,
shall be settled and established in Him, and with Him, forever in heaven;
when such as assume to teach others, and act contrary to the doctrines they preach,
or teach mankind to sin against God, and break the least of his commandments,
either by doctrine, disputation, or evil example, shall be condemned and excluded.`"

This enraged the priest to a great degree;
and then he repeated his charge against the apostle Paul with vehemence, saying,
"`He speaks in tho present tense, I am, I do, I do not: '`I am carnal, sold under sin;
for that which I do, I allow not; for what I would, that do I not; but what I hate,
that do I;`' and so on to the end of that chapter.
So it is clear that the apostle was in sin at that time.
'`So then,`' says he, '`with the mind, I myself serve the law of God; but with the flesh,
the law of sin.`'`"

To this I answered, "`That though the apostle, according to the holy Scriptures,
convinces all men of sin,
yet in great part of that epistle he preaches perfect
and absolute freedom from sin through Christ,
even in this present world.
In the beginning of the sixth chapter of that epistle, he says,
"`Shall we continue in sin that grace may abound?
God forbid.
How shall we, who are dead to sin, live any longer therein!`"
And then, alluding to the death and resurrection of Christ,
which was absolute and perfect, he draws this comparison,
'`that like as Christ was raised up from the dead by the glory of the Father,
even so we also should walk in newness of life.
Knowing this, that our old man is crucified with him,
that the body of sin might be destroyed, that henceforth we should not serve sin.
For he who is dead is freed from sin.`'
And still prosecuting the same doctrine throughout all that chapter, he adds,
'`For in that he (Christ) died, he died unto sin once; but in that he lives,
he lives unto God.
Likewise reckon you also yourselves to be dead indeed unto sin; but alive unto God,
through Jesus Christ our Lord.`'
Again, '`When you were the servants of sin, you were free from righteousness; but now,
being made free from sin, and become servants of God, you have your fruit unto holiness,
and the end everlasting life.`'
In all which he speaks in the present and preter-perfect tense,
as of a state already attained by many of the disciples of Christ,
through faith in his holy and powerful name.

"`The apostle still proceeding in the same doctrine,
in the beginning of the seventh chapter, but under another similitude,
alluding to marriage, says, '`Wherefore, my brethren,
you also are become dead to the law by the body of Christ,
that you should be married unto another, even unto him who is raised from the dead,
that we should bring forth fruit unto God: for when we were in the flesh,
the motions of sins which were by the law,
did work in our members to bring forth fruit unto death:
but now we are delivered from the law, that being dead wherein we were held;
that we should serve in newness of spirit, and not in the oldness of the letter.`'
And in the next chapter he further explains this, where he says,
'`The carnal mind is enmity against God; for it is not subject to the taw of God,
neither indeed can be: so then they that are in the flesh cannot please God;
but you are not in the flesh, but in the Spirit,
if so be that the Spirit of God dwell in you.
Now, if any man have not the Spirit of Christ, he is none of his.`'

"`The apostle having clearly finished the glorious and most
comfortable doctrine of present redemption from sin,
he resumes, in the seventh chapter, to speak of the state of the Jews, as has been said,
under the law only, and not of the condition, either of himself,
or of any other under the gospel.
In the first place, in the latter end of the seventh chapter,
he gives thanks unto God for his deliverance
from the wretched state of sin and body of death,
through Jesus Christ our Lord.
And secondly, confirms his doctrine in the eighth chapter, saying,
'`There is therefore now no condemnation to them who are in Christ Jesus,
who walk not after the flesh, but after the Spirit:
for the law of the Spirit of life in Christ Jesus has
made me free from the law of sin and death;
for what the law could not do, in that it was weak through the flesh,
God sending his own Son in the likeness of sinful flesh, and +++[+++as a sacrifice]
for sin, condemned sin in the flesh,
that the righteousness of the law might be fulfilled in us, who walk not after the flesh,
but after the Spirit: for to be carnally minded is death,
but to be spiritually minded is life and peace.`'
Now, whosoever contradicts himself in testimony, destroys his own credit,
and renders his evidence void.
If therefore the apostle should, in the seventh chapter,
contradict the doctrine he preaches in the sixth and in the eighth,
he would have rendered his doctrine null to all men of understanding,
distinguishing things that differ.
And to be sold under sin, and under captivity to the law of it,
and to be free from that law of sin at the same time,
is a contradiction in matter and terms,
and ought not to be admitted in favor of sin by any Christian,
against so great an apostle and minister of the Lord Jesus.
But such impostors and deceivers as plead, wrangle and dispute,
and contend for sin term of life, and salvation in the end,
cannot themselves be innocent, but even therein sin against God, and as far as they can,
propagate and advance the kingdom of Satan,
in opposition to the kingdom of Christ in mankind, not knowing the Scriptures,
nor the power of God; and wrest some places of this seventh chapter to the Romans,
and other Scriptures, not only to their own destruction, but of those also, who,
through the lusts of the flesh, eyes, and pride of life, believe and follow them.
For the apostle, in this chapter, is not preaching up the power of sin,
which has no power in itself without the law, but the weakness of the law against sin,
which it only discovers, but cannot destroy.`"

The priest was again in a rage, therein repealing his charge against the apostle John,
where he says, "`If we say that we have no sin, we deceive ourselves,
and the truth is not in us;`" but did not offer any comment or argument upon this text,
as supposing it sufficiently cogent of itself to prove his charge,
which he again and again insisted upon and repeated.

Then I replied, "`You have already brought your charge,
and we all understand it without repetition; it is to maintain sin term of life,
by a misapplied text of the first epistle of the apostle John;
and that no man ought to pretend to obtain freedom from sin while in this world.
You have brought in the apostles of Christ, the best and most perfect of men,
not only guilty of sin, but living in it, and preaching it,
that thereby you may fortify and establish yourself in your own sins,
against the plainest convictions of truth in full and
plain contradiction to your false charges.
But let this apostle be heard for himself and Truth.`"

Then I observed to the auditory, "`That this apostle, in his general epistle,
begins first with the testimony which himself and the
rest of the apostles had borne of God to the people,
when first sent unto them, that is, to the Word of Life, which is Christ in Spirit,
and to God, '`that he is Light, and in him is no darkness at all.`'
Secondly,
he proceeds to set forth the sinful and ignorant state mankind
were in when the apostles were first sent to them,
as in this doctrine, '`If we say we have no sin, we deceive ourselves,
and the truth is not in us;`' which is explained in the tenth verse thus,
'`If we say we have not sinned, we make him a liar, and his word is not in us.`'
That is, as we are men under the fall, in the first Adam,
before we know Christ the second Adam, and redemption from sin by him;
if in that state we say we have no sin, or have not sinned,
we deceive ourselves and lie against the truth, and give God the lie too,
who has declared he has sent his Son to redeem and save us from our sins,
if we had not sinned at all.
But the apostle proceeds, and says, '`If we confess our sins,
he is faithful and just to forgive us our sins,
and to cleanse us from all unrighteousness.`'
And to set forth the liberty of the sons of God, and freedom from all sin and evil,
both in this world and in that which is to come,
the apostle further adds in the sequel of this epistle, '`He that says he abides in him,
(Christ,) ought himself also so to walk, even as he walked.`'
And will you say that Christ walked in any sin?

"`Again, '`I have written unto you, fathers,
because you have known him that is from the beginning: I have written unto you,
young men; because you are strong, and the word of God abides in you,
and you have overcome the wicked one.`'
Fathers in Christ are not in sin as such;
for the keeping of the commandments of God is
their evidence and assurance that they know him.
Neither are young men in him overcome of sin, when they have overcome the wicked one,
the author of it, through the divine power of the Word of Life, which abides in them.
'`Let that therefore abide in you, which you have heard from the beginning.
If that which you have heard from the beginning shall remain in you,
you also shall continue in the Son, and in the Father.`'
And as there is no sin in the Son, nor have sinners, while such,
any communication with him, for he is separated from sinners,
so the Father is of purer eyes than to behold iniquity with approbation.
And if you know that he is righteous,
you know that every one who does righteousness is born of him.
And every man that has this hope in him, (to see God as he is) purifies himself,
even as he is pure;`' and you will not venture to say that God is not perfect in purity.
'`Be you holy, for I am holy,
says the Lord;`' and they could not be holy and sinners at the same time;
for these two states are opposite one to another.
The apostle carries this doctrine of freedom from sin in this life, yet further,
and says, '`Whosoever abides in him, sins not: whosoever sins has not seen him,
neither known him.
He that commits sin is of the devil; for the devil sins from the beginning:
for this purpose the Son of God was manifested,
that he might destroy the works of the devil.
Whosoever is born of God does not commit sin; for his Seed remains in him,
and he cannot sin, because he is born of God.`'
You therefore who are pleading and wrangling for sin term of life,
which is the work and kingdom of Satan, are proclaiming your own benighted state,
that you have not abode in Christ, if ever you have in any degree known him;
and that though he is the true Light,
which enlightens every man who comes into the world,
and the new and everlasting covenant of God, you have neither seen him, nor known him.
You may see by this doctrine of the apostle, which you are opposing, whose son you are,
and that the Son of God is not manifested in you, so as to destroy the work of the devil,
which you are supporting with all the might and subtlety he has given you;
and that you are not a child of God, but overcome of the world,
and of the evil one who rules therein.`"

The priest being very impatient to see the apostle justified
by his own doctrine from those false imputations,
vehemently repealed his charge,
that the apostles had sin at the same time when they were ministers of Christ,
and preaching salvation to the rest of mankind by him:
"`If we say we have no sin we deceive ourselves,`" etc.
Here he plainly includes himself and the rest of the apostles and primitives,
in the present tense.

I replied, "`That the apostle likewise speaks in the present tense,
and preter-perfect tense, in handling that doctrine;
'`Every one who does righteousness is born of him.
Every man who has this hope purifies himself:`' and so
of the rest of the texts I have mentioned before,
and many others in the same epistle of like import.
And the apostle being led into those truths of the gospel,
could not contradict one part of his epistle by another; only you do not understand him,
nor mind the context.
And besides, as the apostles had been born after the flesh,
and been sinners as well as others, and by nature, children of wrath,
and in that state not children of God more than others,
they sometimes condescended in the manner of their expression,
to the states and weakness of the people; as for instance, the apostle Paul says,
that he '`became all things to all men, that he might by all means save some;
unto the Jews he became as a Jew; to them who were under the law,
as under the law,`' as before in his epistle to the Romans; '`to them who were without law,
(in a religious sense) as without law:
to the weak he became as weak,`' that he might gain them also.
Timothy was circumcised under that consideration; and he baptized several with water,
though no part of his mission,
and preached the law of life and salvation unto the Gentiles, who, at that time,
were not under the power of the law of God, but without God in the world,
and subject to wild and unreasonable idolatry.
And yet the apostle did not condescend so far as to sin in any degree with sinners;
for that would have brought him under condemnation,
and rendered his testimony of none-effect,
and would not have tended to the salvation of his hearers, but to their destruction;
as does your false doctrine to such as hear, believe, and follow you.

"`Again, the apostle James condescends to the weak in the like manner of expression,
where he says, '`The tongue can no man tame; it is an unruly evil, full of deadly poison:
therewith bless we God, even the Father; and therewith curse we men,
who are made after the similitude of God.
Out of the same mouth proceeds blessing and cursing.
My brethren, these things ought not so to be:
does a fountain send forth at the same place sweet water and bitter '`! Can the fig-tree,
my brethren, bear olive berries?
either a vine figs?
So can no fountain yield both salt water and fresh.`'
Here this apostle, as the apostle Paul, speaks in the first person, and time present;
and who, unless yourself, in favor of sin, will say, that the apostle was at that time,
if at all in any time of his life,
a cursor of men`'! And so far was he from indulging mankind in sin, that he teaches,
'`That if you have respect to persons, you commit sin,
and are convinced of the law as transgressors: for whosoever shall keep the whole law,
and yet offend in one point, he is guilty of all.`'`"

Then he moved another charge against us; That we never pray for forgiveness of sins,
and consequently we never confess we have been sinners.

I answered, "`It is not to be admired that you charge us falsely,
seeing you have made so bold with the apostles of Christ and primitives;
for though we do not think it our duty to confess our sins to any priest,
who might be as sinful, or more so than ourselves, yet we confess them to God,
who knows us as we are, with all our infirmities, and who, we know, by happy experience,
is faithful and just to forgive us our sins, and to cleanse us from all sin;
which no priest, but the High Priest and Bishop of souls is able to do, who,
through infinite mercy and goodness,
has freely done so to many penitent and humble ones in this age,
as well as in times past, to his own glory.`"
I proved him false in this also, appealing to the people present, whether,
even in that meeting, I had not, in prayer,
given thanks unto God in behalf of our community, for his gracious pardon through Christ,
of our many sins and failings; and for his great love also since;
and for the flowings of it in the hearts of the sincere among us, even at that time.
But since we were favored with the evidence of the Spirit of the Son of God,
that the Father, through him, bad pardoned all our sins past, there was no need,
nor was it proper to pray for what, through grace, we had already obtained;
and yet I had prayed then also, that if the Lord, who sees in secret,
saw any sin or evil lurking in any of us, it might please him to discover it to us,
and do it away.
Thus his false charge in that point also was turned upon him.
Then I repeated his charge against the apostle Paul, and his reason for it, namely:
Because he spoke in the present tense,
and read the second verse of the eighth chapter to the Romans, where he says,
"`The law of the Spirit of life in Christ Jesus,
has made me free from the law of sin and death;`" which is not the law of Moses,
the mediator of the first covenant, which was of works, but of eternal life,
freely given us of God the Father, through Christ our Lord,
who is the only Mediator of this covenant.
And here the apostle, speaking in the preter-perfect tense,
as of a thing already accomplished, it was fully conclusive against him,
since it is impossible that the apostles could be in
these two repugnant states at one and the same time.

This contest detaining us late, we went, within night, to Matthew Jordan`'s,
and the 21st we had a large good meeting at Pagan Creek, where also came Joseph Glaister;
and that evening we went together, with several other Friends, to Benjamin Chapman`'s,
in Surry.
On the 22nd we had a meeting in his house, called Lyon`'s Creek meeting,
which was very open and well; and the next day, being the seventh-day of the week,
we crossed James river and went to the house of our friend Edward Thomas,
at Queen`'s creek, the first house I was in when we landed in this country from England.

On the 24th, being the first-day of the week, began the yearly meeting there,
and held the next day also.
It was open and comfortable;
but a wanton company of both sexes from Williamsburg and other adjacent places,
by their levity in the meeting, were troublesome,
and some exercise to Friends and other sober people,
and a hinderance to the right concern and end of the meeting, which was to worship God,
and propagate the gospel among them for their salvation.
But the meeting concluded well; the divine power, virtue, and goodness of God,
came over all before we parted.

On the 26th we set out in order to repass James`' river,
and in our way I called at Williamsburg to see Colonel Nicholson, then governor,
who was kind beyond expectation.
The governor and I discoursed for some time on various subjects; one point whereof was,
liberty of conscience in matters of religion, and that it is most reasonable,
that all people who are of opinion they ought to
pay their preachers should pay their own,
and not exact pay from others who do not employ them, nor hear them;
and concerning tithes, and the ill application of them at this day;
and about human government, and the nature and end of it as an ordinance of God,
and the great safety and many advantages accruing
thereby to mankind under a due administration of it;
and of the kingdom of Christ on earth, which is not of this world, though in the world;
and the difference between that and the kingdoms of men,
and their various services on earth;
that the kingdoms of men ought not to interfere with the kingdom of Christ.
Though the governor was attached to the national church and its interest,
he heard with candor, and took no offense.

We lodged that night with our friend Anne Acres, and had a meeting there on the 27th,
where we had the company of the most reputable people in those parts,
and the Lord gave us a comfortable time.

On the 28th we rested there, and in the evening made a visit to Miles Carey,
secretary of the county, who being absent, his wife, a Friend,
prevailed with us to stay to supper;
upon occasion whereof we had a comfortable time in the divine presence in prayer,
before we ate, to the tendering of the hearts of several of our company,
and especially the Friend of the house who invited us.
For which especially, and the provision before us,
we were humbly thankful to the great and gracious Giver of all good things.

On the 29th we went to Kicquotan,
where we had a meeting at our friend George Walker`'s house; to which came Colonel Brown,
one of the provincial council, and several commanders of ships, and others of note,
who were generally well satisfied with the meeting.

That night we lodged at George Walker`'s,
and had much discourse with his wife about matters of religion,
she being one of George Keith`'s daughters, and following him in his apostasy and enmity,
and naturally subtle like himself; but we kept the testimony of Truth over her,
so that she got no advantage in anything, but confessed after the meeting,
that we were orthodox, preaching undeniable doctrine;
but cavilled at some expressions in the books of some of our ancient Friends,
which we explained to her and the company,
so as to take off that odium cast upon our Society therefrom,
by our implacable adversaries.

About nine in the morning, being the seventh of the week,
we set forward from Kicquotan by water towards Nancemond,
and continuing rowing till there came up a gust of wind right ahead,
and the tide turning, the waves became high, and also against us.
We strove a while, but in vain, and then set sail towards the shore,
in order to row and drag along under it,
and by that means accomplished our voyage to Nancemond town about sunset;
and horses being provided, we rode about three miles to our friend Benjamin Small`'s,
and there lodged.

On the 1st of the fifth month we went to the meeting at Chuckatuck,
where came Colonel Bridges, one of the chief inhabitants of the country,
and some other strangers; and the Lord favored us with his good presence.
Here we had an account that James Burtell, the French priest,
had been at our friend the widow Jordan`'s,
the next day after he and I had discoursed as aforesaid,
to inquire when and where there would be another meeting,
he being desirous to come to it, and to dispute with me, or any of us,
as there might be occasion; having also boasted,
as if I had not answered his last challenge in the former meeting; which was not true.

This night we lodged at the widow Jordan`'s,
and on the 2nd Benjamin Jordan went from Joseph Glaister,
to acquaint the priest he was come to know what he meant by his conference?
The priest answered, that it was nothing from other men`'s books, but from himself;
and desired it might be at Colonel Bridges, next Thursday,
where they had disputed before, but would not send any account upon what subject:
yet Joseph Glaister assented under all these disadvantages.

In the mean time we had appointed a meeting at the Western Branch on the third-day,
of which I sent the French priest word, that he might be there if he thought fit,
where I should be ready to answer what he had to say against me.

On the 3rd we were at the meeting at Western Branch, which was large and peaceable,
many truths of the gospel being opened to good satisfaction,
both concerning the sacraments, so called,
and sinless perfection through Christ the Lord, in this life.

+++[+++On the 1st of the seventh month, 1705,]
we had a meeting at Chuckaluck, where several strangers were present,
and things were open, and a good meeting and very comfortable,
through the good presence of the Lord, which was with us;
after which we drew up some particular heads of matter to discourse the priests upon,
we having as much right to propose and insist upon matters for debate,
and the manner of proceeding, to them, as they had to do so to us.

On the 5th, being the time appointed for the conference, we went accordingly,
and met in Colonel Bridges`' great hall,
where we had a large auditory of all ranks of people in the country,
six justices of the peace, several colonels, majors, captains,
and other military officers, lawyers and others.
My friend Joseph Glaister and I were very low, inward, and humble in our minds,
the multitude being generally against us,
and the honor of Truth concerned in the management and
issue of this engagement on our part;
yet the Lord was on our side.
And on the other hand, Andrew Monro, the priest,
being the person more immediately engaged, as Joseph Glaister on our side,
he would not enter into any conference upon
these heads which we had drawn up and proposed,
but only in his own way; yet Joseph Glaister having the mind of Truth,
engaged him under some seeming disadvantages in the case.

+++[+++The two first questions argued between Joseph
Glaister and Andrew Monro were water baptism,
and the possibility of being made free from sin in this life.
When they were about to commence on the third, which was,
whether Christ did ever give command or power to any of
his apostles or ministers to force`' a maintenance,]
Andrew Monro would not enter upon it, but said, "`Mr. Glaister,
you are a much younger man than I am, and stronger, and can hold an argument longer.
I confess you have a close way of reasoning, though I think I have the truth on my side,
but can hold out no longer.`"
And being hot weather, and he an elderly man, grew so weary, weak and faint,
that he could scarcely be heard; but called for a pipe of tobacco and a tankard of ale,
for his refreshment; and so it ended on his part in drink and smoke.

Then one came and told me the French priest was going from there,
so that if I had anything to say to him, I must do it quickly.
Whereupon I went from the table, and found him with some people about him,
and spoke to him in their hearing, concerning our meeting upon his challenge.
This put him into a fresh rage, but he would not hear of any further dispute;
pretending he had appointed that day for it, and I did not go,
and therefore he was at liberty.
I replied, "`Neither did you go there; and you ought not to decline meeting me, since,
upon your own challenge, I came back from beyond James`' river with some difficulty,
charge and hazard, on purpose, and am ready to meet you at your own place tomorrow.`"
But he utterly refused it,
and yet by degrees we came upon the same point of sinless perfection in this life,
or sin to the end, and further debated it.

Being exceedingly reluctant to yield up this beloved doctrine of sin term of life,
and the kingdom of heaven at last, he struggled yet a little further: and,
upon my saying, that no man can serve two masters, nor God and sin at the same time;
he replied, as in our former dispute, "`that a man is never properly a servant,
unless he obey his master in all things: so a man cannot be a servant of sin,
unless he obey it in all things.`"

Then I urged, "`that if none can be the servants of sin, unless they obey in all things;
so, by a parity of reason, one may say, none can be the servants of God,
unless they obey in all things.
And then none of you priests, who plead for sin term of life,
pretending to serve God and sin at the same time, can be servants of God,
or ministers of Christ; since you do not, by your own confession, obey him in all things,
if in any one thing.`"

So many of the people as were present, being generally very quiet during the time;
were satisfied, for anything that appeared to the contrary; and, it growing late,
we at last parted friendly, my adversary taking me by the hand, called me brother.
Several of the people were very kind, Truth having dominion over all in the end;
to the praise of his own arm, to whom alone it is due, now and forevermore.
And many being now well satisfied concerning the way of Truth,
who had not been so before, we returned that evening to the widow Jordan`'s.

On the 6th we went over Nancemond river, to Benjamin Small`'s,
and rested there that night; but, in our way near the ferry,
we heard that James Burtell had left a note there,
advertising a new challenge for a further dispute with me.
And as we were conferring what could be the meaning of it,
we espied him just putting off from the shore in a boat a little before us,
and we made haste towards him; and, calling, he stayed till we came up,
and enquired what he meant by it; for I thought he had been satisfied before.

He replied, "`as for my own part I have no more to say,
but some gentlemen of my communion were very desirous
of some further satisfaction in some points;
so I desire we may meet upon it this day week.`"
I objected against the length of time;
that it was not reasonable I should be so long detained in those parts about it,
seeing I had, at his former request, returned over James`'s river to meet him, as before.

At last he agreed to the third-day following; but, though often urged,
he would not discover what were the points those persons desired further satisfaction in.

On the 8th, being the first of the week, we went to the meeting at Chuckatuck;
to which came several colonels, majors, justices of the peace, and many people,
for the country was much alarmed by our being among them,
and a good open meeting the Lord gave us in the main; yet, for my own part,
I came not fully easy from it, but rather under a secret burden from some unknown cause.

On the 10th we returned over the river to major Thomas Jordan`'s,
to dispute the French priest, where many people were assembled on that occasion.
The time appointed was nine in the morning, and he came not till twelve;
so that many of his party seemed to doubt his coming, and were troubled;
they having great dependence upon him as their only remaining champion in those parts.
But at length he came;
and the first salutation I gave him was a gentle reproof for
delaying so long after the time appointed by himself,
which he endeavored to excuse; though the real meaning of it was taken to be,
to shorten the time, so that night at least might end the controversy,
into which he had been so unwillingly brought.

My antagonist, being very volatile, made his assault instantly,
without a word of any preliminaries, or stating any question, and thus attacked me:
"`Why do not you, the people called quakers, use the Lord`'s prayer in your assemblies?
I prove that Christ taught his disciples this prayer, offering to read it,
and commanded them to pray so;
and I also prove that they who do not use it are no Christians; but you never use it;
because, if you did, you must then pray for forgiveness of your sins,
which your own supposed righteousness will not allow.
You are therefore none of his disciples.
You are no Christians.`"

I replied, "`the charge is founded upon a false suggestion;
for though we do not frequently use the very words of that prayer in our meetings,
as the manner of some is, yet we sometimes use it verbatim,
and often the sum of it in other terms; and we often likewise explain the nature,
end and substance of it in our meetings,
for the information and edification of the people; and how can we explain it,
and not refer to it?
And how can you say we never repeat it, having been at so very few of our meetings?`"
He replied, "`I never heard you; and who else here ever did?`"
Then arose a voice and cloud of witnesses, both of Friends and others, saying, "`I have;
I have; I have;`" and, among the rest, a lawyer said, "`I have heard Joseph Glaister,
now present, in particular, use it, and others also.`"
"`O then, said the priest, I have no more to say on that account.`"

Then I informed the auditory, "`That though we sometimes used that prayer in form,
and often the substance of it in other words, in our supplications to the Almighty;
yet it was not proper for the state of every man to use it,
nor to be done in men`'s own wills and times; when, and as often as we please;
for there is a qualification necessary to be
known in them who use it rightly with acceptance.
For though all men be the children and offspring of God by creation;
yet none can call God father truly, in an evangelical sense,
but such who have the evidence of the Spirit of God, that they are, at least,
begotten of him, by the influence of his divine Word and holy Spirit;
and must be come to a good degree of righteousness, and holiness also,
by the sensible operation of the holy Spirit, in their own hearts.

"`The introduction, or address of that prayer of prayers, is to the Almighty,
as he is the father of all; with acknowledgement that his habitation is in heaven,
above all.
And the first petition is, that his name,
or by what word soever the divine Being is meant, expressed, or designed,
may be mentioned with reverence and awe, as the most holy thing; and not blasphemed,
lightly used, profaned, or taken in vain.
And the second petition is, that his kingdom, rule, dominion and government, may come,
be made manifest, and established over all the earth and every soul therein,
throughout all generations, as explained by the next words therein; that is to say,
'`your will be done in earth as it is in heaven;`' which implies the highest
degree of perfection and exaltation human nature is capable of in this life.
For, if the will or law of God is to be done in earth as in heaven,
then there can be no more possibility of sin, unrighteousness, or evil,
among the children of men, to the end of the world; for the expression is unlimited,
including all persons, ages and times.
And all the holy angels of God in heaven, and the spirits of the just made perfect,
continually and forever do the will of God to all perfection,
in which also stands their life eternal.
And we are here taught to pray, that it may likewise be the same here on earth.
And the next petition in this divine and most perfect prayer, regards ourselves,
with respect to our present personal divine
nourishment and sustenance while here on earth,
and forever; and that is,
'`give us this day our daily bread;`' even the
true bread which the Father gives from heaven,
the bread of life, which gives life unto the world, of which mankind may eat and not die;
the living bread which comes down from heaven, of which whosoever shall eat,
he shall live forever;
which is likewise that flesh which Christ gives for the life of the world;
and unto him whosoever shall come shall not hunger or thirst any more.
This is that everliving and heavenly bread which gives life unto the world.
This is the hidden manna, more excellent than that in the wilderness.
The tree of life, which is in the midst of the paradise of God.
By the breaking of this bread is the Son of God made manifest unto him who eats thereof,
to be that meat which endures unto everlasting life.
This is the same heavenly bread which the apostles and primitives loved,
desired and prayed for, that they might be continual partakers of it;
and which we also have prayed for, do pray for,
and are mercifully and graciously heard of the holy One, unto whom we do pray.
By this bread we grow and increase from stature to stature,
and from strength to strength, unto eternal life,
and everlasting establishment and perfection in glory,
in and with him who lives and reigns over all, in all, and above all,
and is worthy forevermore.

"`The next petition is, '`forgive us our trespasses,
as we forgive them who trespass against us.`'
This petition also is suited to genera! or universal communion.
For as all have sinned, and come short of the glory of God, all, and every one ought,
being convinced of sin by the holy Spirit,
to confess their sins unto him who convinces them, and to desire forgiveness;
whether of God, for sins committed against him, or for trespasses done,
one against another.
In both cases, confession is to be made to the offended, and forgiveness requested,
before we can reasonably expect it, whether of God or man.
For as to our sins against God, it is said, '`if we confess our sins,
he is faithful and just to forgive us our sins,
and to cleanse us from all unrighteousness and sin.`'
And as to our trespasses one against another, it is said,
'`if your brother shall trespass against you,
go and tell him his fault between him and you alone; if he shall hear you,
you have gained your brother,`' etc.
Or, again, '`if your brother trespass against you, rebuke him; and if he repent,
forgive him.`'
And as God is merciful unto all, so he would have us all be merciful one to another;
and therefore Christ the Lord comments upon this petition in an especial manner, saying,
'`if you forgive men their trespasses, your heavenly Father will also forgive you;
but if you forgive not men their trespasses,
neither will your heavenly Father forgive your trespasses.`'
In all which the Lord teaches us to be like himself, full of goodness, mercy,
and social virtue, doing the will of the Father on earth as it is done in heaven,
in a state of restoration, redemption, righteousness and true holiness,
the end whereof is life eternal; which is opposite to a state of sin,
in the nature of things, and +++[+++is]
the end of the coming and manifestation of the Son of God.

"`The next petition is, '`lead us not into temptation, but deliver us from evil.`'
Jesus, when he was baptized, went up straightway out of the water; and lo,
the heavens were opened unto him, and he saw the Spirit of God descending, like a dove,
and lighting upon him: and lo, a voice from heaven, saying, this is my beloved Son,
in whom I am well pleased.
Then was Jesus led up of the Spirit into the wilderness, to be tempted of the devil.
Mankind, in general, being already in sin, and under condemnation in the first Adam,
and Jesus the Savior only Wee, being the Lamb of God, without spot or blemish;
it was necessary, in the counsel of the Father,
that he should be tempted of the evil one, the common enemy and tempter of mankind;
that thereby, even as man,
he might have a fellow feeling of our weakness and infirmities,
and be the supporter of such as should believe and trust in him, and be tempted of evil;
which petition is also obtained by those who are his through faith in his name.
For as God tempts no man, nor is he himself tempted of evil, those who are tempted,
+++[+++yield to temptation]
are led aside of their own lusts, and enticed;
so he permits none of his to be '`tempted above what they are able,
but will with the temptation also make a way to escape,
that they may be able to bear it;`' and it is no sin to be tempted unless we yield.
These temptations are allowed upon those who believe,
and are thereby become the children of God,
that they may have full trial of the manifold grace of God towards them, of their faith,
patience, and love toward God, and one toward another in him,
and experience his blessing upon them,
and come forth from under the weight and burden of temptations,
as from the furnace of affliction, as pure gold seven times tried therein;
and not as reprobate silver or dross, remaining as we are by nature, in a sinful,
sensual, polluted condition, ever learning,
and never able to come to the knowledge of the Truth, or salvation by him.

"`The last and concluding part is, a just and sincere acknowledgement unto the Father,
that we can do nothing without him, but by him; '`for his is the kingdom,
and the power`' to enter therein, by which alone we can do all these things,
and our whole duty unto his holy requirings, whether with respect unto the Lord himself,
or one toward another, as we ought.
And therefore, as we have no power or sufficiency of our own,
no glory or praise belongs unto us for the work required and wrought,
either during our conduct and abode in this world, or in the world to come.`"
And so this matter rested without reply.

"`Now,`" said I, "`It is my right to propose the next subject matter to discourse upon;
and therefore I ask you this question, "`Whether or no did Christ,
or any of his apostles, demand, force,
or receive any maintenance or thing from any person or people,
who did not receive or own them and their ministry?
And when did the Son of God give power unto any of the princes or powers of the earth,
to concern themselves, or intermeddle with the proper affairs of his kingdom;
which is not of this world?
Or to ordain ministers in his church?
Or appoint, direct, or assign them any support or maintenance?`"

James Burtell assumes the affirmative, and Thomas Story denies it:
and agreed that the matters shall be determined by express Scripture proof only,
or by fair, natural, and unforced consequences deduced from there.

James Burtell having assumed the affirmative, offered his proofs as follows.
"`The apostles and ministers of Christ being sent to preach the gospel,
were to live and be maintained by it;
as plainly appears by the doctrine of the apostle Paul on that subject, where he says,
'`Who goes a warfare any time at his own charges?
Who plants a vineyard, and eats not of the fruit thereof?
Or who feeds a flock, and eats not of the milk of the flock?
You shall not muzzle the mouth of the ox that treads out the corn.`'
Again, '`If we have sown unto you spiritual things,
is it a great thing if we shall reap your carnal things?
Do you not know, that they who minister about holy things,
live of the things of the temple; and they who wait at the altar,
are partakers with the altar.`'
And those Scriptures the apostle expressly applies to
the maintenance of the apostles and ministers of Christ,
in preaching the gospel, and exercising their ministry in the various branches thereof,
according to their several callings and gifts.
And this they claimed, not only as voluntary contributions or donations,
at the option of the people, but of right, by virtue of the power they had over them,
and as an ordinance of the Lord,
that they who preach the gospel should live of the gospel.`"

I answered, "`This is a sophistical way of reasoning,
and does not answer the first part of the question for which he adduces it,
nor proves his assumption therein: for that part of the question is,
whether Christ or his apostles did ever demand, force,
or receive any maintenance from any who did not receive or own them and their ministry?
which is the case between your ministers and us.
And not whether any support or maintenance at all be
due of right to the apostles and ministers of Christ,
from the people who receive them as such,
and believe in Christ as the Messiah and Savior of the world.
But he only attempts to prove that some support or maintenance, but says not what,
or how, is due to the apostles and ministers of Christ in preaching the gospel,
which we have never denied; by which he would elude that part of the question,
and impose upon us a fallacious and pretended proof of what is not therein.
For these texts of Scripture do not prove such a maintenance due,
even to the true ministers of Christ,
or to be had by such means as your ministers now demand, exact, and receive them,
not only from such as believe they are ministers of Christ,
but likewise from us and others, who do not believe it; being assured that no such wages,
hire, or maintenance as they demand, is due to any ministers of Christ,
and much less to them, by any command or ordinance of Christ,
or doctrine or example of his apostles.
For, when Christ first sent forth his twelve apostles,
it was in the power and wisdom of his own Spirit; in which they had power to preach,
to heal sicknesses, and cast out devils and unclean spirits.

"`And as to their protection and maintenance,
they were to depend immediately and absolutely upon the providence of God,
and travel in that work, under great natural disadvantages.
For they were not to provide beforehand, either gold, or silver, or brass,
in their purses, nor scrip, or two coats a piece, nor shoes, nor stalls, except one only,
nor bread.

"`And when the Lord appointed other seventy, and sent them likewise by two and two,
they also were prohibited to carry with them either purse, or scrip, or shoes.
And as to any reward from men, either for preaching, healing,
or any other part of their work, they were not to have any save their meat;
for as the power was, and is, of God only,
they were not to make an advantage or gain of it to themselves;
and therefore he said unto them, '`freely you have received,
freely give;`' yet the workman is worthy of his meat.
Neither were the seventy to have other wages from those
to whom they preached or whom they healed,
than the twelve had; that is,
to eat and drink such things as they to whom they preached gave or set before them.

"`Neither were they to have protection from any temporal power,
such powers being universally against them; but on the contrary,
were sent forth as sheep among wolves, and cautioned against the cruelties of men.
Neither were they to premeditate what to say,
when brought before governors and kings for the sake of Christ and his testimony;
but to depend upon the immediate assistance of the Spirit of God in themselves.
By all which it is evident that the apostles and ministers of Christ were not,
and are not, to demand, force, or receive any other maintenance or thing from any,
save only their meat, drink, and personal necessaries, during the time of their ministry;
which clearly explains the doctrine of the apostle Paul
in all those texts now adduced by your minister:
that is,
that no other way of maintenance is ordained or
allowed to the apostles and ministers of Christ,
or to live of the gospel, than their meat, drink,
and reasonable and necessary sustenance, in the exercise of their ministry,
and from them only who receive them as ministers of Christ, and give it freely.

"`But though this be a privilege given and due to the apostles and ministers of Christ,
what is that to you and yon?
Who has made you ministers of Christ?
Who sent you?
And to do what?
for they who run when God sends them not,
do not profit the people in the things of God at all.`"
James Burtell replied in short, "`Notwithstanding what has been said, this apostle,
and consequently the rest, must have had support from the believers in those days;
for he says, '`I robbed other churches, taking wages of them to do you service.`'`"

I answered, "`It is to be observed,
that the several churches or congregations in those
days had certain common public stocks or funds,
out of which the necessary charges of the ministry in preaching the gospel,
were defrayed, and the needs of the poor saints supplied; which arose from the love,
goodwill, and charity of the believers in Christ; every one giving,
without any other law or compulsion, according to his own free will and purpose,
which began in Christ and his twelve apostles,
by the love and gratitude of those who had been great sinners,
or under personal maladies, and been forgiven and healed by him.
For it is testified of Luke the evangelist,
that '`certain women who had been healed of evil spirits and infirmities,
Mary called Magdalene, out of whom went seven devils, and Joanna, the wife Chuza,
Herod`'s steward, and Susannah, and many others, ministered unto him of their substance.`'
And they had a common purse, or bag,
which was carried and managed by the most unworthy among them, by Judas,
the thief and traitor; out of which they sometimes, as they had occasion,
bought bread and necessaries for themselves, and likewise gave to the poor;
but nothing was particularly appropriated, either to Christ himself,
or any of his apostles, save what covetous and unfaithful Judas might rob them of.
And as the disciples increased and multiplied in number, so did this order and usage,
with respect both to giving and receiving, and to the same happy ends and purposes,
for the promulgation and propagation of the gospel of Christ,
and salvation unto mankind by him,
and the exercise`' of charity as a great fruit of his coming;
and not to appropriate any part to any particular person, like Judas,
greedy of filthy lucre, or Balaam,
'`who loved the wages of unrighteousness,`' to the enriching of
themselves and families at the expense of the church,
as happened among them, in process of time,
and remains among you by succession unto this day.

"`And as to the apostle`'s robbing other churches,
and taking wages of them to serve the Corinthians, it is only an elegancy of speech,
for he was learned, and an orator,
and no way imports that he appropriated to his own separate
use anything he received on account of his ministry;
but that when he first preached unto them of Corinth, he was not chargeable to any man,
but did it freely, as to them; his necessities and charges of his travels to them,
and his ministry,
being at the same time supplied and sustained at the charge of the church in Macedonia,
which had been settled before them; or by some brethren who came to him from there.
And as in all things he had kept himself from being burden some to them,
so he resolved to continue to keep himself;
intending thereby to cut off all occasion of reproach
by certain false apostles then among them,
who were deceitful workers, transforming themselves, as many do at this day,
into the likeness of the apostles of Christ, the ministers of righteousness.
And the apostle Paul was so far from receiving anything to himself,
or for his own private separate use, for, or in respect of his ministry,
or the exercise of it, that he commonly wrought with his hands to that end,
being a tent-maker; and towards his latter end,
taking his last and solemn leave of some elders,
who had the oversight of the flock of Christ at Ephesus,
and in appeal to their knowledge of him, and his conduct on that account,
and to excite them by his example to the like practice, he says,
'`I have coveted no man`'s silver, or gold, or apparel; yes,
you yourselves know that these hands have ministered unto my necessities,
and to them who were with me: I have showed you all things, how, that so laboring,
you ought to support the weak; and to remember the words of the Lord Jesus, how he said.
It is more blessed to give than to receive.`'
Which were the last, and as it were, the dying words of the apostle to them.`"

To this he offered no other reply than to repeat his assertion in like terms,
"`That the temporal powers have full authority and right in the case;
and upon them,`" said he, "`we will leave it.`"

During the discussion of this point, some of the people were uneasy,
and others interrupted; but the greatest number were silent and attentive;
which being ended, the priest immediately moved another subject of debate; which,
I suppose, was the main point that the people were most desirous to hear fully argued,
and was thus:
"`Our Lord and blessed Savior Jesus Christ
commands his disciples to '`go teach all nations,
baptizing them in the name of the Father, and of the Son,
and of the Holy Ghost;`' but you, the people called Quakers, do not obey him therein;
therefore you are none of his disciples; you are no Christians.`"

I answered,
"`What is it to you what Christ commanded his apostles in their ministerial character;
for you are no apostles?
And if the neglect or omission of the performance of
that be a proof that such are no disciples of Christ,
and no Christians, then you yourselves are no disciples, and no Christians;
for you do not practice anything here instituted or commanded, in any proper sense,
but an invention of your own, under pretense of it.`"
Then I signified to the auditory, "`That as that person had proposed a discourse,
and I had accordingly met him,
yet it did not follow that he ought to assume to state any question in his own method,
and draw from there his own arguments and conclusions, in favor of his own notions;
nor ought any question at all to be stated,
but what should relate to the known principles and practice of both parties.`"

Upon this Andrew Monro, the confuted priest aforementioned, started up,
pressing to be heard,
pretending to expose some gross errors out of our ancient Friends`' books;
and the Frenchman, my antagonist, was very ready to give him way:
but I utterly refused it; and with my friend Joseph Glaister, suppressed it.
Then stood up Major Jordan, and declared to the auditory,
that meddling with old books was contrary to the terms of that dispute,
as offered by the French minister to a Friend,
who had accepted his challenge on my behalf, in his hearing;
and that it ought not to be insisted upon, or allowed;
for it could not he reasonably expected that we, in itinerant circumstances,
and upon such a surprise, could be prepared for a proper defense.
That quieted them a little;
and then I offered a state of the question on the text mentioned,
which might include the principles and practice of both;
for we own baptism as well as they.

This he and his party would have evaded, and clamorously opposed;
but several of the justices said it was so reasonable, it could not be denied;
and yet the priest, and his raging party, for some few such there were,
rudely pressed for such a state of the question as
might bring it wholly relative to our principle,
of the baptism of the Spirit, of which they were no proper judges,
or only upon water baptism in its greatest latitude, which they do not practice;
and not to be confined to sprinkling, which is their only practice,
or to words necessarily including it.

Then I made a short harangue to the auditory,
and observed to them the evasions of their ministers, and the reason of them; that is,
lest their own practice should be detected, and made appear to be extra-scriptural.
And then urged him over and over,
to establish such a state of the question as might
comprehend both our principles and sentiments,
and his practice upon the subject; and the greatest part of the people also,
at last requiring it as very just, and more particularly one of the magistrates,
who said openly, that if they could not defend their baptism now in use,
it was high time to look for a better: at last he conceded, but with much reluctancy;
and then the question was stated thus:

"`What baptism is intended in these words, '`Go you therefore and teach all nations,
baptizing them in (or into) the name of the Father, and of the Son,
and of the Holy Ghost?
Is it water baptism only, or the baptism of the Holy Ghost?
And is sprinkling of infants on the face only, in those names, with water,
signing them on the foreheads with a sign of a cross, where no sign remains;
with godfathers and god-mothers, making them promise and vow,
as in the catechism of the national church of England,
commanded and warranted by that text?`"

"`James Burtell affirms and assumes, that water baptism only is commanded in that text;
and that the present practice of the church of England, as relative thereunto,
is included and supported by that command.
Signed, James Burtell.`"

"`Thomas Story denies that water baptism is commanded in that text;
but that the baptism of the Holy Ghost is there intended.
Signed, Thomas Story.`"

My opponent having thus assumed, that water baptism only is commanded in the text,
I put him upon the proof of it, which he essayed thus:
"`There is some baptism commanded here to the apostles,
and that baptism must be such as they were capable to perform;
they were not capable to perform the baptism of the Holy Ghost,
but with water they could baptize: therefore water baptism only is there commanded.`"

I answered, "`You may observe here,
that the force of your minister`'s argument lies in this,
that the apostles of Christ could not baptize with the Holy Ghost, but only with water;
and therefore it must be water baptism.
I grant that the apostles could not baptize with the Holy Ghost at their own pleasure,
when, and whom, and where they would, in their own wills, as your ministers can,
and do administer what they call,
and have taught you to believe and think is Christ`'s baptism;
but that the apostles could not instrumentally baptize with the Holy Ghost, I deny.
For that institution is introduced after this manner,
'`And Jesus came and spoke unto them, saying,
All power is given unto me in heaven and in earth:
go you therefore and teach all nations,
baptizing them in (or into) the name of the Father, and of the Son,
and of the Holy Ghost;
teaching them to observe all things whatsoever I have commanded you; and lo,
I am with you alway, even unto the end of the world.`'
'`And he said unto them, (at the same time) Go you into all the world,
and preach the gospel to every creature.`'
'`He that believes and is baptized shall be saved;
but he that believes not shall be damned.`'
And that this was not water baptism,
plainly appears by what the Lord further commanded his apostles at the same time,
that they should not depart from Jerusalem, but wait for the promise of the Father,
which he had told them of before he suffered; '`For John truly baptized with water,
but you shall be baptized with the holy Ghost not many days hence.`'

'`This baptism here commanded is not water baptism,
for the apostles were in the practice of water baptism in John`'s time,
before the institution of this baptism; and it is here contradistinguished,
as belonging to John`'s dispensation, and which some practiced,
though we have so few instances of it,
that it can hardly be called practice with propriety,
after the beginning of the ministration of the baptism of the Holy Ghost,
which none can administer without the immediate presence and power of the Holy Ghost,
the Spirit of Christ, given to that end.
But some apostles both could and did administer water baptism,
in the proper dispensation of it, without the power of the Holy Ghost,
which was not then given as a dispensation,
and which any bold and busy undertaker at this day, can, and some do, administer,
by the ordinary powers of nature,
without the assistance of the Holy Ghost on that account,
which they neither know nor believe in.
But the baptism here commanded, neither the apostles themselves could,
much less can anyone else administer, but by the immediate power of the Holy Ghost,
co-working in them, with them, and by them;
and therefore Christ promised that they should '`receive power
after that the Holy Ghost was come upon them and then,
and not till then, they were his proper witnesses,
but could not baptize with the Holy Ghost until they themselves were baptized therewith.
And as He who has all power in heaven and earth,
promised to be with them by that power alway,
in that and all other works of the gospel ministry, to the end of the world;
so they went forth and preached everywhere, '`the Lord working with them,
and confirming the word with signs following.`'
And this promise relates not only to them then present,
but to all the true ministers of Christ, according to their various gifts, degrees,
and services, from that point throughout all ages; yet,
as a just check and prohibition to all bold, forward, and presumptuous spirits,
it is also written concerning the Holy Ghost, that he shall not '`speak of himself,
but whatsoever he shall hear, that shall he speak; and he will show you things to come.`'

"`And as Christ himself is the Truth, and in the days of his flesh,
was always subject unto the Father, and under his direction,
and imputed all his words and works to him; by this text it appears to be so still,
and ever will be, in all the work of the redemption and salvation of mankind.
Then what and who are you, O dark, carnal, sinful, polluted man, of all your fallen kind,
who dares assume upon yourself to intermeddle with the things of God,
which you do not understand,
nor so much as believe that the Holy Ghost is now to be given, and waited for,
as the immediate guide, leader, and director in the things of God,
and work of the gospel?
You are an unbeliever, and therefore in a state of condemnation;
you are not saved yourself, and how then can you be a savior upon Mount Zion;
instrumentally to save others in the Spirit of Him who is the great Savior of all?

Then James Burtell questioned whether there is such a text in Scripture as,
that "`John truly baptized with water,
but you shall be baptized with the Holy Ghost not many
days hence;`" but my companion Joseph Glaister,
who was very ready that way, producing the place, the priest was silent as to that.

Then I insisted,
that since I had been interrupted before I had finished the point I was then upon,
it was but reasonable and fair that I might, without further interruption,
proceed to finish it; and so proceeded thus:

"`Having proved that the baptism of the Holy Ghost, and not water baptism, is instituted,
in the text and context in question;
and the full capacity of the apostles and ministers of
Christ to perform it in his Spirit and power,
I now proceed to prove, that they did baptize with the Holy Ghost accordingly.
But before I proceed any further,
that we may not beat the air through any misunderstanding,
or different applications of words to things,
favor me with your definition of the baptism of the Holy Ghost,
and what you understands by it, that I may know whether we, by the same terms,
mean the same things.`"

He answered rightly,
"`That the baptism of the Holy Ghost is the descending of the Holy
Spirit into the hearts of those who believe and wait tor his coming.`"
"`Very well,`" said I; "`but is this all?`"
And upon a short pause, he answered, "`No, he works in mankind the work of regeneration;
and this is his complete baptism.`"

I answered, "`Well, then I now prove,
that the apostles in the wisdom and power of the Spirit of Christ,
were instrumental ministers of this baptism.
First, when Peter preached to Cornelius and his household,
'`the Holy Ghost fell on all them which heard the word.`'
And in his relation of the passage, in his defense before the apostles and elders,
before whom he was accused, as if he had committed an error,
and broken the law or custom of the Jews, by preaching to the Gentiles,
and eating with them, though their mission was expressly to all nations,
he defines the falling of the Holy Ghost upon them to be the baptism
of the Holy Ghost mentioned by Christ in the text in question,
or context, in these words, '`And as I began to speak,
the Holy Ghost fell on them as on us at the beginning;
then remembered I the word of the Lord, how that he said,
John indeed baptized with water, but you shall be baptized with the Holy Ghost.`'

"`Here the apostle applies this event to the terms of the text, which says,
'`Go teach (or disciple) all nations,
baptizing them;`' which shows that this baptism is sometimes administered in
the time and act of teaching in the power and wisdom of the Holy Ghost,
whereof the tongue is chiefly instrumental;
as if teaching and baptizing were one and the same act,
emblematically signified by the likeness of cloven tongues of fire,
sitting upon the apostles,
at the time of the first descending of the Holy Ghost upon them;
which is more expressly illustrated where it is said,
that while Peter yet spoke these words (which he preached) the
Holy Ghost fell on all them which heard the word.`'
And according to the message of the angel to Cornelius,
in directing him to Peter as his minister, '`he should tell him words,
by which himself and all his household should be saved,`' and not by water baptism.
For though Peter himself, who, with the rest of the apostles and elders,
had but so lately understood the meaning of Christ in that institution,
and the rest of the apostles and elders not all hitherto, though about eight years after,
said to those believing Jews who came with him from Joppa, and for their sake,
the Jews being always pertinacious of all types and shadows, in neglect of the substance,
'`Can any man forbid water, that these (Gentiles) should not be baptized,
which have received the Holy Ghost as well as we?`'
for which there could be no other reason but to obviate any offense
those Jews might have taken at those believing Gentiles,
if they had wanted any circumstance which they imagined necessary, and John`'s baptism,
which the Jews had generally been baptized with,
being at that time remaining in reputation;
yet it does not appear by the text that they were so baptized,
nor could there be any real need of it, seeing they had received the words of salvation,
and gift of the Holy Ghost;
whereby alone the great work of regeneration and salvation is begun, carried on,
and perfected.

For, '`after that the kindness and love of God our Savior toward man appeared,
not by works of righteousness which we have done, but according to his mercy he saved us,
by the washing of regeneration, and renewing of the Holy Ghost,
which he shed on us abundantly through Jesus Christ our Savior;
that being justified by his grace,
we should be made heirs according to the hope of eternal life.`'
So that here it follows clearly, that the baptism of the Spirit is well defined,
and that the apostles were ministers of it, and Christ himself by them.
For this baptism is the promise of the Father to the Son, not of water, as John;
but by the Holy Ghost; and by the Son does he baptize his ministers by the same Spirit:
and when they have been baptized by the Holy Ghost, and received power in him,
then are and shall they be witnesses unto the Father and the Son, by the Holy Ghost,
unto the uttermost parts of the earth;
and then shall they '`go and teach (or disciple) all nations,
baptizing (or washing) them in the name or power of the Father, and of the (eternal) Son,
and of the Holy Ghost.
In him was life, and the life was the light of men.
That was the true light which enlightens every man that comes into the world.`'
And then also can they teach, or disciple,
to observe all things which Christ himself has commanded them, and to be with them alway,
not only in that age, but likewise in all ages in succession, in the same work,
and to the end of the world.

"`Again, for illustration, remember what is said by Christ,
'`I have manifested your name unto the men which you gave me out of the world:
yours they were, and you gave them me; and they have kept your word.`'
'`As you have sent me into the world, even so have I also sent them into the world.`'
And also, '`He that believes on me, as the Scripture has said,
out of his belly shall flow rivers of living water; but this he spoke of the Spirit,
which they that believe on him should receive: for the Holy Ghost was not yet given,
because that Jesus was not glorified.`'
Again, we are '`able ministers of the New Testament, not of the letter, but of the Spirit;
for the letter kills, but the Spirit gives life.`'
And the apostles frequently laid their hands on the disciples,
and they received the Holy Ghost.
'`And Paul laid his hands on certain disciples, and the Holy Ghost fell on them.`'`"

By all which it plainly appears,
that though the Lord Jesus is the only baptizer of souls by his own authority,
having all power in heaven and earth from the Father,
and in whom all fulness of the Godhead dwells substantially;
yet that the apostles and living ministers were,
and are instruments of the baptism of the Holy Ghost, no man who believes the Scriptures,
and understands them, can doubt,
nor support your reason for the continuation of water baptism in the church,
which I leave to the auditory to consider.`"

Then the Frenchman advanced a fresh argument for water baptism only, without the Spirit,
in the text, thus: "`As this commandment was to the apostles of Christ,
so they either understood it, or they did not understand it.
To say they did not understand it,
were to make the commandment of none effect by practicing another thing,
and omitting the thing intended.
But that they understood water baptism to he commanded,
is clear from their frequent practice of it, after the coming of the Holy Ghost;
as I prove by several instances.

'`1st; When Peter preached the gospel to the Jews, and they inquired what they should do,
he advised them to repentance, and baptism in the name of Jesus Christ,
'`tor the remission of their sins, and they should receive the gift of the Holy Ghost:
for the promise was to them, and to their children, and to all that were afar off,
even as many as the Lord our God should call;
then they that gladly received his word were baptized.`'

"`Again, 2ndly; The eunuch was baptized by Philip,
and here James Burtell read the passage, '`See, here is water,
what does hinder me to be baptized?
And Philip said, If you believe with all your heart, you may, etc., and he baptized him.`'
So that you may see two clear instances of water baptism by
the apostles after the coming of the Holy Ghost;
and that practice shows fully what baptism was intended in the text in question.`"

I answered, "`In the first place, I observe one thing from these two texts,
which I desire you to remember anon, upon the second part of the assumption; that is,
that those convinced by Peter, and also the eunuch, were first to believe and repent,
before they were baptized, which infants are not capable of.

"`2ndly; That the baptism was not in the name of the Father, Son, and Holy Ghost,
but in the name of Jesus Christ only;
and this shows it was no other but a continuance of John`'s water baptism,
of which they were in practice before Christ suffered,
and before the command in Matt. 28:19. That it has no reference to infants,
though the word children is there: for all Israel young and old,
are called the children of Israel, as one generation;
the aged as well as infants are the children of their ancestors.
And the promise there mentioned has no relation to water baptism,
but to the gift of the Holy Ghost, promised of God by the prophet Isaiah to Israel,
'`I will pour my spirit upon your seed, and my blessing upon your offspring,`' etc.
And I deny your conclusion barely from the practice;
for the apostles practiced circumcision, vows, shavings, etc.,
and were in the practice (as said) of water baptism, before this command was given.
The apostle to the '`weak became as weak; to all men all things,
that by all means he might gain some.
But his practice in all he did, is no warrant to others to follow him;
for he baptized with water, and yet confesses fairly he was not sent of Christ to do it:
so that neither his practice, nor that of the other apostles, is cogent.

"`And further there is not one instance in all
the New Testament where any apostle baptized,
or commanded any to be baptized with water in the name of the Father, Son,
and Holy Ghost; but where any water is used, it is only in the name of Jesus Christ,
and for the most part to the Jews.
For, as the Jews were to have remission of sins by faith m Christ, as born of the Virgin;
and the Spirit, upon that faith, is a gradual manifestation;
so the Gentiles were to have remission of sins by faith in him,
as he is the '`true light which enlightens every man who comes into the world.`'
So that baptism was no means to them of receiving the Spirit,
whatever it might be to the Jews, or Jewish proselytes.

"`Again, you may note, that the apostle Paul,
who was sent to the Gentiles in a particular manner,
denies that baptism with water was any part of his commission; for he says expressly,
'`Christ sent me not to baptize, but to preach the gospel.`'
Now, since this great and first minister of the
Gentiles had no commission to baptize with water,
we may justly conclude it was not necessary to that work; and if not to our forefathers,
then not to us.
And if he had no commission, then none could succeed him in a commission;
and then the pretenses of all to baptize the Gentiles is vain.`"

I added further, my adversary being almost on ground,
"`That though the apostles did baptize some, especially of the Jews,
and it may be some others, in the beginning of the gospel dispensation;
yet it does not follow that there was any necessity for its continuance.
For as Christ said, '`I have yet many things to say,
but you are not able to bear them;`' so also the apostle,
'`I could not write unto you as unto spiritual, but as unto carnal:
I have fed you with milk, and not with meat; for hitherto you were not able to bear it,
nor are you yet able.`'
And so soon as the church was able to bear this doctrine of baptism in its spirituality,
the two great apostles, Peter and Paul, both explained it unto them.
And as for a time, and under several administrations, there had been various baptisms,
yet at last all centered in one baptism; for John was to decrease,
and Christ to increase.
That which decreases comes to an end, but that which increases never ends.
John has decreased near seventeen hundred years, and is come to an end,
and Christ has increased as long to some,
though the beginning of his kingdom is not yet known unto many.
Paul, or the inspired author of the epistle to the Hebrews, speaks of baptisms;
but to the Ephesians he says, '`There is one Lord, one faith,
and one baptism;`' and what that one baptism is,
he also informs us in his epistle to the Corinthians,
'`We are all baptized by one Spirit into one body, the church; which is his body,
the fulness of him that fills all in all.`'
Again, Peter says, '``'Tis not the putting away the filth of the flesh,
but the answer of a good conscience towards God,
by the resurrection (i. e. revelation) of Jesus Christ.`'
Here it is both negatively and positively defined, what it is not, and what it is;
'`it is not the putting away the filth of the flesh,`' then not water,
which extends no further,
'`but the answer of a good conscience;`' which never can
be but by the work of the Holy Ghost descending unto us,
as my adversary has defined the Spirit`'s baptism, and sanctifying our hearts,
working the work of regeneration, and a holy conformity to the will of God,
even through that '`power that raised up Jesus from the dead, by the glory of the Father,
so also should we walk in newness of life.`'
And this is the inseparable effect of the one only
spiritual and permanent baptism of the Holy Ghost,
in which Christ is with his ministers, unto all that are qualified to receive it,
to the end of the world.`"
I had room enough by this time, and that made me more large;
but my antagonist to this made me this unexpected return:

"`It is true there is one baptism, but that baptism has two parts; the one is water,
the other Spirit: for as the body and soul make one man,
so water and spirit make one baptism.`"

To this I demanded his proof out of Scripture,
wherever the Spirit and water made up one baptism, or concurred in the act of baptizing,
as the Holy Ghost, and preaching the gospel in the power and wisdom of the Spirit,
had done.

He answered.
That wheresoever John`'s baptism was duly administered,
the Holy Ghost was given at the same time; which being so palpable an error,
I greatly admired at this answer, and returned,
"`I will prove the direct contrary by plain Scripture,
though it is your part to make good your assertion, if you can, namely: Acts xix.,
where the apostle asked certain disciples,
whether they had received the Holy Ghost since they believed?
And they said, '`We have not so much as heard whether there be any Holy Ghost.`'
And the apostle replied, '`Unto what then were you baptized?`'
They said only,
'`Unto John`'s baptism,`' (i.e. water baptism) and were so
far from receiving the Holy Ghost at the same time,
that they had not so much as heard whether there was such a thing in being.

"`Again, Simon Magus had water baptism duly administered,
and yet had neither part nor lot in the Holy Ghost.

"`And also, though it is not necessary to prove a contrary,
where no proof is offered for a position, I prove, by several instances,
where water was without the Spirit, and the Spirit without water;
the former in the case of the three thousand, and in the Samaritans;
and the latter in the case of Cornelius.`"

My adversary only repeated his assertion, That as the body and soul make up one man,
so the water and Spirit one baptism.
Thus, like a door on the hinges, he shifted to and again,
without proceeding forward one jot.

Upon which I said, "`Friend,
you are in utter confusion and self-contradiction;`" and noted to the auditory,
"`That his last position was against the state of the question, and his first assumption:
for the question is, Whether it is water baptism only, or the Spirit`'s baptism;
and the first he has assumed.`"

Then he twice denied that the question was so, or that he had so assumed,
not knowing what he said, till I produced it upon the table,
having kept it in my hand all the time; and further noted,
"`That the question was alternatively stated, whether water only, or Spirit;
and or being a disjunctive, it could not be both, but one or the other intended;
and therefore his last assertion was only a fruitless shift, and did not help him.`"

All the reply he made to this was.
That if I would not receive what he said upon it, he would proceed no further.

Then I noted to the people how short he was fallen as to water baptism at large,
and then put him upon his proof of the second part of his assumption, namely:
That the present practice of the church of England, sprinkling of infants,
sign of the cross, god-fathers, vows and promises in their name,
was supported by the text.

To this he offered little answer, but began to make away from the table,
through the crowd, only mentioning that text,
"`Permit the little children to come to me,`" etc.

To this I replied, "`That as in the text Mat.
xxviii.
the subjects of baptism are such as are capable of being taught,
and of observing whatever Christ had before commanded them; which children are not:
so in this latter text it is plain there is no reference at all to baptism of any kind;
for the people having faith in Christ, brought their children,
that he might lay his hands on them, which he accordingly did, and blessed them;
testifying to their innocence and purity, saying, '`Of such is the kingdom of heaven.`'
And if so, then they need riot anything to qualify them to enter,
or to take away original sin, as you suppose.
For though, under the law, the Lord said,
'`I will visit the sins of the fathers upon the children;
upon which arose a proverb in Israel, that '`the fathers have eaten sour grapes,
and the childrens`' teeth are set on edge:`' that is, the fathers have sinned,
and the children are punished for it; yet, under the gospel God gives more grace,
and says, '`As I live, says the Lord, this proverb shall cease;
he that eats the sour grape, his teeth shall be set on edge;
the soul that sins shall die.`'
Now the apostle says, that '`where there is no law, there is no transgression.`'
Sin was in the world before the law, but sin is not imputed where there is no law.
Little children, though they have a seed of sin in them, as descending from Adam,
the common father of all, yet that is not imputed;
because Christ is a '`Propitiation for the sins of the whole world.`'
And as many suffer under the effects of Adam`'s fall, who never heard of it,
so many receive benefit by Christ that never heard of him.
'`As in Adam all died, so in Christ all are made alive.`'
And children being incapable of any law are also of transgression,
and consequently of sin; so that there is nothing to condemn them;
'`for of such is the kingdom of heaven.`'`"

This passed off without any reply, and then the Frenchman slunk out of the company;
but forgetting his gloves, came back to see for them,
and then I asked him if he was going, and he said yes: so we parted friendly,
wishing one another`'s welfare, all the company being very grave and silent.

The whole dispute being ended, we kept the field; and having dined, or rather supped,
with Major Jordan, who kindly entertained us,
we returned that night over Nancemond river to Robert Jordan`'s,
where I stayed next day writing letters, and some part of the dispute.

On the 12th, being the fifth of the week, we were again at Chuckatuck meeting,
which was large and well; and the court-house being in our way, we called there,
and all the magistrates were kind to us,
as well those who had seemed rough and zealous for their priests at the disputes,
as those who had shown us favor and countenance.
Major Jordan and his son left the bench and walked with us half a mile,
till a shower of rain occasioned their return, parting with us in great respect.
As we walked along, he told me that he had heard since the last dispute,
that we had fifty to one on our side among the people,
and that it was thought most of them were turning Quakers.
I told him I was glad to hear it, but thought I had rather heard they were turned,
than turning; for the cross is too hard for many there, as elsewhere,
who are truly convinced, but not obedient,
because of the glory and friendship of the world.
That night we returned over Nancemond to Benjamin Small`'s, and lodged there.

On the 13th, in the morning, I set forward for Kicquotan, and went to Nancemond town;
and being upon the river, there came a gust, which brought up a storm right ahead,
and a great sea, so that we returned to Robert Jordan`'s that night.

On the 14th, in the morning, we set forward again, and the wind being still high,
and against us, we rowed over the river, and arrived about sunset.
It being then near low water,
we were forced all to get out of the boat about a quarter of a mile from the shore,
by reason of the shoals.
We made ourselves a tent with one of the sails and some pine tops,
and a fire at a distance on each side;
and there we lay (but I slept little) till about two in the morning.
Then the tide making, we took our boat and set forward over the river, about twelve miles.
The wind freshened as day broke, and the waves were high enough to think ourselves safe;
but the Lord preserved us, and we arrived at George Walker`'s, at Kicquotan,
about six in the morning.

It being the first-day of the week, and no notice being given of any meeting,
we could have none.
I set forward after three, and went about twenty-five miles that evening,
to our friend Anne Airey`'s, where I stayed several days.
But before I departed from George Walker`'s,
he told me that the people there were generally displeased with their priest, Wallace,
who had been very busy in his pulpit against us,
ever since Joseph Glaisler had disputed with him, calling us deceivers, devils, etc.,
insomuch that one of his hearers, one day after sermon, had taken him to task about it,
telling him that they went to church to worship God,
and hear something that might be for edification in matters of religion,
and not railery against honest people.

On the 16th I wrote letters for England,
and the day following had a meeting at Anne Airey`'s house, which was not large,
but a good meeting.

On the 18th I had a meeting at William Trotter`'s, about ten miles over the Neck,
which was not large, but open, and the people very still and quiet, and some lender.

On the 19th I went to Queen`'s creek, and on the 20th had a good meeting at James Bates`'s,
at Skimino;
and that night lodged at his brother John`'s. On the 21st I went about thirty-five miles,
to James Howard`'s; and the day following, being the first of the week,
had a meeting there.
There being but few Friends, and many people, and they very dark and hard,
the meeting was not very open, but ended well, and I was easy,
and that evening travelled about eleven miles,
to Jane Pleasants`'. Next day had a meeting there, which was large and well,
and I had great peace.

On the 25th I went to Charles Fleming`'s, and the next day had a meeting at Black creek.
On the 27th, the morning being rainy,
I set forward and arrived at Elizabeth Wilson`'s in the afternoon.
On the 29th I had a meeting there, being the first of the week, which was pretty large,
and a good meeting.

On the 30th, about the sixth hour in the morning, I set forward for Potomac,
and arrived at our friend Peter Skinner`'s, about three in the afternoon,
being about fifty miles,
and that evening sent notice about the neighborhood of a meeting to be there next day,
which was very large for the time, and very open,
though there are but a few Friends in those parts, and these but weak.

On the 1st of the sixth month I had an open meeting at Benjamin Berryman`'s,
to the honor of the Lord, who alone is worthy.

I was set over the great river of Potomac next morning by Major Thornton`'s servants,
and that night arrived at the widow Hutchins`',
where I was well refreshed after a tedious journey.
On the 3rd, in the morning, I went to Abraham Jones`',
and in the evening to see his father and mother, both ill.
On the 5th, being the first of the week, I was at their meeting about five miles off,
which was a good open time.

On the 6th I set forward to Samuel Chew`'s,
and on the 7th was at the quarterly meeting there, which held also the next day,
and were large and good meetings, through the goodness of the Lord,
who is not lacking to his people in all their assemblies.

On the 9th we had a meeting at Westriver meeting-house, which was not very open,
but ended well.

On the 13th, being the first of the week, I was at the meeting at Patuxent,
which was pretty large and open.
On the 14th we went to William Picket`'s through some difficulties,
the great rains having raised the rivers and brooks,
and the next day had a meeting there, where there are few Friends, but several friendly,
and generally sober and satisfied.

On the 17th I arrived safe and well at Philadelphia,
to the praise of the great name of the Lord, who was with me in all my exercises,
in his mercy and loving-kindness,
and by his holy Arm sustained me in things too hard for me; to whom be thanksgiving,
through Christ Jesus my Savior, forever and ever.
Amen.

[.offset]
+++[+++On the 10th of fifth month, 1706, Thomas Story was married to Ann Shippen,
the daughter of Edward Shippen, of whom he makes mention in his Journal:
see page 108 of this volume.
Their union, however, was not of long duration; for on the 19th of sixth month, 1710,
she departed this life.]
