== Chapter 13

[.chapter-subtitle--blurb]
A Journal from England to Holland, Friesland, and Germany, in the year 1715.

Through the goodness of the Lord we arrived well
at Rollerdam on the 19th of the fifth month,
and I took up my lodging with my friend and old acquaintance, Robert Gerard,
formerly of Aberdeen, in Scotland, who, for some years had lived there.

On the 20th, being the fourth of the week, I was at their meeting, which was very small,
there not being above four small families, and not all under a profession of Truth;
but the Lord, who is not confined to number,
but opened the law and the prophets to the two disciples going to Emmaus,
was pleased to visit us together, tender our hearts by the same word of his grace,
and make them burn within us, to our solid consolation.

On the 26th, being the third of the week, I set forward by Delft, Leyden, and Harlaem,
where I met with John Padley, from London.
We went that evening to Amsterdam, where the
meeting falling of course the next day, was small,
and in the forepart of it very heavy and dull, under the temptation of a sleepy spirit,
which prevailed on several,
there being rather a lukewarmness and declension in this city, than a going forward;
but the Lord was pleased to make way for us, through this veil of darkness,
and the meeting ended in some degree of life, and things were pretty well.
Here Jacob Claus interpreted for me, as Archibald Hope had done in Rotterdam;
which being a thing I had not been acquainted with, was a little strange at first,
but as I gained experience, it became more easy,
and my spirit more at liberty in that exercise.

The next day we returned to Harlaem, where we had an appointed meeting;
for though they formerly had a settled meeting there, most of them are become so cold,
that they have wholly dropped it,
and some of them so weak as to go among the Menists to hear them.
There having been good notice given, the meeting was pretty large, most of them Menists,
and some Presbyterians, and one minister, the public preacher in that town.
Things opened largely and clearly among them,
and Truth was in good dominion in the life and power of it.
They were generally very quiet,
and some of them being much reached by the power of Truth, and tendered,
were loving after the meeting, and departed very solidly.

On the 29th we went to the house of Simon Bevel, to make him a visit.
He had once known a pretty good condition, but marrying a Menist,
she had drawn him aside with her; and he coming to this meeting,
was reached and affected, which drew some notice from us.
When we got to his house he happened to be gone to Amsterdam; however,
his wife received us courteously, and invited us into an arbor in the garden,
and brought there some of her good things; but we having an eye upon the Lord,
and more towards her good than her entertainment,
the Lord was pleased to draw us into a sweet silence,
and gave me a few words to her in particular, which also reached all,
and then John Padley prayed, and we had a very tender and divine season;
after which we departed in great love and peace,
she inviting us there again in our return that way,
if it should please the Lord so to order it.

Having finished this satisfactory visit, we returned to Amsterdam,
and were at their first-day meeting, which, in the forenoon,
was pretty well filled with strangers, some supposed to be young princes, or nobles,
by their garb and retinue.
Things opened clearly concerning the way of Truth,
and I was interpreted by William Sewel; the people were very quiet,
and many of them seemed concerned, and in some measure reached by the Truth.
In the afternoon their meeting is usually more select,
which being known to the inhabitants, it was smaller, but more strangers than commonly.
In this country they make so little of the first-day,
that many buy and sell in the shops in the afternoons,
and are thereby detained from all worship, and others go a pleasuring in walks, gardens,
coaches, boats, and the like, so that all places of worship, I am told,
are very thin at such times.
Our meeting was open and comfortable, the Lord being with us,
to the praise of his holy name, who is worthy forever.

Here we remained till the 2nd of the sixth month, being the third of the week,
when we went from there, and that evening reached Twisk.
On the 3rd had two meetings there; the first was pretty well filled, and an open time,
but the second not so full, the people being about their cattle and business;
but several were tendered and comforted in the Truth, whose blessed power was over all.

On the 4th we went back to Horn, and had a meeting in the Menists`' meetinghouse,
which was not large but pretty open and well.
Several of their chief men were there, and were very sober, though I suppose,
not pleased; for there is a sect among them called Collegians,
who deny the divinity of Christ,
or that the Spirit of God is now to be expected as of old; and that men may,
if they will, keep all the doctrines and commandments of Christ, and in so doing,
are saved.
And the testimony of Truth that day went against them in all these points;
but we did not meet with any opposition, for the Truth was over them.

That afternoon we went by wagon to Enchuysen, where we went to see Martin Daniel,
a baker, who is convinced of Truth, but has not strength to profess it:
he and his wife were very kind.
I having something to say, they were reached, and their hearts still more opened;
and we exhorted them to be noble, and take up the cross freely, and despise the shame;
which now, as well as of old, attends the profession of the Lord Jesus,
according to the present dispensation.

On the 7th, being the first of the week, we had two meetings at Harlingen,
in a room which Friends have for that purpose, being but two or three small families,
and several of the collegian Menists came there;
but I believe our doctrine did not please some of them,
though others of the Menists were well satisfied, and several of them came to see us.
The Lord was with us, and all was well and comfortable,
several being touched with a sense of Truth.

There being only one poor old widow remaining in Embden under the profession of Truth,
we went to visit her, which she took well, and was rejoiced to see us.
After that we walked through the city, but were all of us greatly laden in our spirits,
in a sense of the power of darkness, which is great there.
Returning to our inn under this sense,
it pleased the Lord to visit us together in a time of holy silence,
and make us all sensible of his divine love to a people there,
in which our spirits were released from the other load,
and became concerned to visit some of them: accordingly,
next day we had a meeting at the widow`'s house, which being but small, was well filled,
so that several went up into an upper room, where they could hear,
and many in the street about the windows, and were generally sober,
and many well affected.
The Lord being with us, we had a comfortable time,
and the doctrine of Truth was clearly opened in a good degree of life and love,
and the people departed in solidity in a general way.
So that I have hopes of the place, that the inhabitants will receive Truth,
and entertain it better than heretofore; for there were several Friends there formerly,
but being greatly persecuted, some went from the place, and others died.
After this meeting we reigned over all in the Lord, who,
when and where he is pleased to arise in his great power,
subdues and puts all things under him: so that,
as in the evening before we had been greatly burdened,
we were now as much rejoiced in Him, to whom be rule and dominion forever.

We departed that city, the people in the streets showing no dislike, but rather civility,
as we passed along; and that night lodged at an inn.
On the 11th, early in the morning, we went to Oldenburg,
where we were stopped a little at the gate, and examined from where we came,
and what we were.
We refreshed ourselves at the inn, and soon departed,
being again examined as we passed out at the gate by the commander of the guard,
and our names again taken.
We arrived at an inn on the bank of the river before night,
going with horses and wagon into the house, where there were a coach and chariot before,
all on the same floor, and the people, and fire, and all their affairs in one view,
the horses being set on each side, all within the same walls,
though they have some chambers apart; which, though strange and odd to us,
yet is the common way in that part of the world throughout our journey.

On the 12th, early in the morning, we set forward in an open wagon,
and passed on to the city of Breme;
and there we heard that the plague was at the city of Altona, within a mile of Hamburg,
where we were going, and that it was shut up and guarded on all sides.
This gave us some exercise; for it looked, to human reason,
a little dangerous to proceed towards a place so circumstanced,
and by other towns and places too, where, being strangers,
we must expect strict examinations, besides our own personal danger of the sickness.
But after some inward retirement, our way was cleared up through all difficulties,
and we resolved to proceed on our journey and service.
Here we spoke with Sarah Schreders, a friendly woman, and loving the way of Truth.
She told us of some others there who also favored it;
that there was great division among the people about religion;
and that one of the public preachers having come near the doctrine of Truth,
telling them that outward baptism and bread and wine, without the substance would not do,
was silenced by a prevailing party, but had still many on his side;
and feeling some degree of openness in my mind to the inhabitants,
I kept the place in remembrance, intending that way in our return.
From here we departed about five in the evening,
and that night about eleven arrived at Otterberg, and lodged at an inn.

On the 14th we went early to Hamburg, and were strictly examined by the out-guards;
but having a certificate from our last inn,
testifying that we had come over the river there in the evening,
and we letting them know that we had come directly from Holland,
we had admittance into the city,
and were kindly received and entertained by our friend Jacob Hagen,
with whom we stayed that day, but could not have a meeting,
because the people were generally at their worship,
and none there under a profession of Truth but himself.

The next day, being the second of the week, we had a meeting at his house;
and he being acquainted with most merchants and persons of account,
and respected in the city,
and having given notice to such as he thought religiously inclined,
there came among others, the chancellor and counsellor of the king of Denmark,
a counsellor of the Duke of Ploen, near Lubeck, also a merchant from Riga,
and several other merchants of his acquaintance.
They were all men of appearance in their way,
and promised little towards the comfort of a meeting,
rather like persons of curiosity than religion,
and some of the merchants at first a little light, talkative,
and busy with their snuff-boxes among themselves.
My spirit was much down, and under heaviness, till about a quarter of an hour had past,
when Truth began to work, and soon arose in me over their spirits;
and then I had courage and strength,
and things opening much to the inward appearance of the divine Word,
they were brought under in some degree.
It was a good meeting,
and most of them took us kindly by the hand after the meeting was over,
and passed away very solidly.
The Friend told us afterwards that the above chancellor
of the king of Denmark was an enemy to all priestcraft,
and had written and published some very smart things against the Lutheran priests,
which had much galled them.

Remaining here till the next day afternoon, Jacob Hagen related the following passage:
"`In the year 1712 the Czar of Muscovy being in the city of Frederickstadt, in Holstein,
about two days journey from here,
with five thousand soldiers to assist the Danes against the Swedes,
after he had quartered his men, inquired of one of the burgomasters,
whether there were any of the people called Quakers there!
The said officer told him there were a few.
Then the Czar asked him if they had a meeting in that place!
The officer told him they had.
Then the Czar bid the officer let the Friends know,
that if they would appoint their meeting that forenoon, being the first-day,
he would be at it.
The officer replied, that there were thirty of his soldiers in the meeting-place,
so that there could not be any meeting in it.
When the Czar heard that, he was angry that they had put soldiers there,
and sent an order by one of his own captains, that they should all be put out forthwith,
and that notice should be given to the Friends by the captain,
that if they would appoint their meeting he would come to it.
Accordingly the officer gave notice thereof to the said Jacob Hagen, and Philip Defair,
a public Friend who lived there, and not only ordered the soldiers out of the room,
but made them take away all they had brought there.
The place being made ready, they had their meeting at the second hour after noon;
to which the Czar came, and brought with him Prince Menzikoff, of Muscovy,
the General Doigorucky, and several other of his dukes, generals, secretaries of state,
and other great men; and a great crowd following,
he ordered the door to be shut as soon as a competent number were in to sit comfortably,
and many more came to the windows.
After some time of silence, Philip Defair preached the doctrine of Truth among them,
and all sat very quietly, but especially the Czar,
who sat very gravely all the time of silence,
and all the others being awed by his example and presence, did so likewise.
But the Muscovite lords and generals not understanding the language,
and the Czar himself understanding it pretty well, interpreted to them what was declared,
with much gravity and seriousness, commending what he heard, saying.
That whoever could live according to that doctrine would be happy.
A Friend after this presenting him with Robert
Barclay`'s Chatechism and Apology in High Dutch,
he said he would have them translated and printed in his own language.`"

On the third-day after dinner I had a secret work of Truth in my mind,
and we were all drawn into silence, and after some time, to prayer,
and we were comforted together.
This being over, notice was given to Jacob Hagen,
that there was an order come from the king of Denmark to shut up the city of Hamburg,
as Altona was, he being informed that the plague was also among them.
Having no further concern there at that time,
and intending for Frederickstadt the next morning,
we were advised to depart that afternoon on our way, which we did accordingly,
though some of us could have been very free, and rather have stayed longer.
It was near five in the evening before we set forward,
and it began to rain as we departed the city; and being in an open wagon,
we were much wet.
We had an idle, ill-natured driver, who being hardy himself,
and able to endure the weather, would hardly go out of a foot-pace,
so that it was very late before we reached the inn; and when there,
had but mean accommodations, some of us lying on straw only,
and covered with wet clothes.

On the 17th, early in the morning, we again set forward, it still raining,
and went about the same pace as before till we came to another stage.
There we had the satisfaction to change our wagon
driver, and though it rained still, yet we were much better used,
and proceeded more cheerfully, for this one went a good pace,
and we shortened our journey a great deal that afternoon, but very wet still,
and all of us had taken cold.

The next morning being fair and clear, we set out early, and driving at a good rate,
our clothes dried as we rode along, and we were a little more cheerful,
and about eleven forenoon we arrived at Frederickstadt;
and coming to the house of our friend Gysmond Otterloo, we were joyfully received,
and kindly and plentifully entertained,
and being comforted together in the love of Truth,
we soon forgot the fatigue of our journey.

On the 19th, being the sixth of the week, we had a meeting in town,
where came many of the inhabitants, and some of the best rank.
They were generally satisfied, some tendered, and Friends much comforted,
and we were glad together of our visit.

On the first-day following we had two meetings there, which were both large and open,
and the people generally well affected.
The testimony of Truth was clear,
and some made in measure sensible of the power of Truth, and tendered.
After the meeting in the afternoon was over, I said to the people before they departed,
"`That there was so much difference between our English language and theirs,
that they might probably not well apprehend
everything according to the true intent of it;
and our testimony, by that means, might suffer loss,
and some might not have the full benefit of it.
And therefore if any scruples arose, we were ready, at any convenient time and place,
to remove any objection.`"
But we heard of none.

On the 23rd we went with several Friends to the city of Tuning,
to try if we could have a meeting, and several were spoken to,
but none would entertain a meeting in their houses, being afraid of their priests,
they being generally Lutherans.
Some of our company went to the priest and asked him if
he would let us have a meeting in his house.
He was pretty civil, and told them he could not consent to it;
being a preacher among a people of other principles,
it would look strange in him to admit such a meeting in his house.
But he sent for two of his brethren, one of whom was more warm and averse; however,
they parted pretty friendly on all hands.
After this we walked through the streets, and about the town,
but had nothing to say to the people there.
They took great notice of us, but offered no incivility.
Returning to our inn,
we gave notice in the town that we intended a meeting next day at Frederickstadt;
and there we returned that evening.

And here I think it not improper to relate what I had from several
Friends concerning a former visit to this place by Christopher Midel,
who some times had been preacher to the Danish chapel, at Well-Close, near Ratcliff,
London; but being convinced of Truth, and faithful, had received a part of this ministry;
it was after this manner:
"`About seven or eight years ago Christopher came to this city of Tuning,
then under the command of the Swedes, and preached the Truth in the open streets,
and some were affected with his innocency and doctrine.
But the magistrates sent soldiers to apprehend him, and take him out of the city,
and all the sentinels were ordered not to allow him to come in again,
so that he lay two nights without the gates, one in the fields,
and another in a farmer`'s house.
Though the soldiers could not allow him to go into the city,
yet they were very respectful to him, and he spoke much of the way of Truth among them,
which seemed to take place with several in some measure.
At length he sent to the governor of the city, who was also the chief military officer,
desiring to speak with him; and the governor came to him,
to whom Christopher made known his case,
desiring he might have liberty to clear his mind to the people.
The governor was respectful to him, and told him, that if he had applied to him first,
before he had been put out of the city by order of the magistrates,
he could have answered his request; but since they had done it,
if he should now protect him against them, it would raise a difference,
which he thought was not proper at that juncture of affairs there.
And after they had reasoned the case fully, the governor took out a handful of money,
which he would have presented to Christopher, supposing, being a stranger and traveler,
he might want to bear his charges.
But Christopher refused it, with acknowledgments of his kind offer;
and let him understand that he was not under any necessity that way,
and so departed from that city.`"
But we may observe how the Lord orders things in the course of his providence;
this city being besieged by the Czar and king of Denmark, in the year 1712,
fell into their hands; and the banks, ditches, gates, and bridges,
which had kept out this servant of the Lord from declaring Truth in the city,
are now so leveled, filled up and demolished,
that a stranger can scarcely discern where they have been,
but as shown by others that knew them before.
And yet the inhabitants, being guided by their priests,
as remote from the Truth in nature and spirit,
as those from whom they are a little reformed in notions,
do still continue their aversion to Truth,
the only way by which they can have true peace and safety.

I now return to Frederickstadt, where, on the 24th, we had a large meeting,
where the magistrates of Tuning, and some of the chief of the inhabitants,
made some amends for their remissness the day before;
for both the burgomasters came to the meeting, and also the secretary, or town clerk,
with many of the inhabitants, as also many from adjacent places,
with several priests and teachers of different sects, and were generally sober,
and several well affected.
The blessed Truth reigned in majesty over all, to his own glory;
and I believe many were touched with a sense of the virtue of it,
and their understandings in some degree opened.
The matter delivered, was mainly concerning the law written in the heart;
the light of the Gentiles, and the universality of it;
the necessity of faith in that light, and advantages arising thereby;
that though this law of the Spirit of life, come by Jesus Christ,
makes free from the law of sin and death, where it is truly opened and revealed,
yet "`there is none in heaven, or earth, or under the earth, can open it,
but the Lion of the tribe of Judah,`" which is the Lord Jesus Christ,
who came of that royal tribe.
Therefore it is in vain to depend upon the learned,
who cannot open it because it is sealed, or the unlearned, because they are so;
or upon the princes or potentates of this world; but upon the Lord alone.
"`For as none knows the things of a man, but the spirit of a man which is in him;
so no man knows the things of God, but by the Spirit of God;
and the Spirit searches all things, even the deep things of God.`"
That as the veil was and is still over the heart
of the Jew while the law was read unto him;
and he, in hearing of the letter, is still ignorant of the Spirit; even so the Gentiles,
though the law is written in them, "`it is even in their hearts,`" but yet sealed.
So that though they read the holy Scriptures, which testify of the true and living God,
and also of his Son Christ Jesus,
and also hear the things of God plainly and fully
declared by the hearing of the outward ear;
yet so long as the law is sealed up in the "`heart,
they neither understand the Scriptures, which are some of the things of God,
nor what is declared unto them,
though in the wisdom and demonstration of his Holy Spirit.

I exhorted them therefore to believe in the Son of God, the light of the Gentiles,
who once had appeared to the Jews in that holy body;
and fulfilling the will of the Father therein,
is also come in spirit according to his promise, and by whom all are taught that believe,
and have a divine understanding by him.
The wise and learned in this world, by all their wisdom, know not God;
but one giving one conjecture and opinion, and another giving another,
concerning the mysteries in the holy Scriptures,
they have led those that followed them into great confusion,
and being departed from the Spirit of the Lord Jesus,
the Prince of righteousness and peace, they are gone into wars and destruction,
making outward as well as inward desolation; in which they have proceeded to that degree,
that professed Christians have commixed the blood one of
another with the blood of horses and cattle in the open fields.
O great abomination before the Lord! with many more close things, which that day,
in the authority of the living Truth, were delivered among them;
so that some of them seemed to stand in admiration, and all were still and solid.
I heard of none but one priest that muttered,
who thought I bore too hard upon the learned,
and left them too little share in the knowledge of the things of God,
wherein he mistook me;
for though their learning without the Spirit
does not qualify them to teach the things of God,
they are not unqualified only by having it, but as subservient to Truth, it may be,
and is really useful.
But he only talked softly at a distance,
so that I had no opportunity to confer with him on that subject; and in the general,
things were very well, and well taken.

On the 25th we were at their monthly meeting at Frederickstadt,
which was altogether of Friends, to whom, though few in number, the Lord was near,
and we were tendered and comforted together in his holy love,
which alone edifies the whole body, which is one in all lands.

Being invited the day before by one of the burgomasters to dine with him,
we went accordingly after the meeting, where we were kindly and plentifully entertained.
His wife had been at the meeting the day before, and spoke well of it at table,
where I also had some words in prayer before we ate, which opened freshly.
He was very free and open with us, being a Menist.
After some hours spent in discourse, chiefly about religion,
wherein we had no difference, we departed,
and visited the widows and fatherless among Friends in town, there being seven widows,
and one with seven small children, their husbands having died in a great sickness,
like that at Altona, some time before.

That afternoon some Friends went to a neighboring
village to try if a meeting could be had,
and among others, spoke with a priest, who is a Lutheran,
who gave them a very civil answer, saying, "`My house should be open on that account;
but I being preacher myself in the place, and put in by the magistrates,
I do not know how they may resent it,
if I should admit strangers of other principles
to preach in my house;`" and so excused himself,
but said he would be glad of a visit from us.

On the 26th we had another meeting at Frederickstadt,
at which were several priests and ministers of different persuasions,
and one of the regents or professors of the college at Kiel,
the seat of the duke of Holstein, and several again from Tuning, etc.,
for it was their market-day, and after their business therein was much over.
The meeting was open, and many things cleared to them, and all very quiet.
Friends and I took particular notice of the still and innocent behavior and
countenance of the teacher of the Armenians in Frederickstadt,
then in the meeting, who seemed to be affected with Truth, and inwardly reached by it.
This also was a good and comfortable meeting.

The first-day following, being the 28th, we were again at Frederickstadt,
where the meeting was large and open, both forenoon and afternoon;
and there came many of the same people, and some others, who were generally still,
and the way of Truth and life was plainly opened to them,
and several affected with the power of it in some measure:
and Truth being overall in the majesty of it, had honor and praise, and is alone worthy.

There being a marriage intended between a couple of Friends,
notice was given thereof beforehand, and it being appointed the next day, that is,:
the 29th, there came a great crowd of all sorts;
so that many who came a little after the hour appointed,
not being able to come so near as either to hear or see, went away;
but as many as could crowd into the house, and about the doors and windows, and lane,
stayed; the novelty of the marriage inducing many that were not concerned about religion.
The Lord was pleased to favor us with his presence,
and open things suitable to the occasion; and I believe,
so as most of them had never heard before on the subject of marriage.
The marriage supper and ten virgins came up in the wisdom and authority of Truth,
setting forth the enjoyments of the five wise,
and misery and disappointment of the five foolish,
and the whole auditory were brought under the awe of it,
and became as still as the most sedate meeting of Friends,
and the Lord`'s power was over all magnified, and the buyers and sellers of oil,
or what they may so call, exposed.
There were many affected at this meeting with a solid sense of the virtue of Truth;
and I observed the above-said professor was there, as he had been, I think,
at every meeting, and also the Armenian preacher, very solid.
We went to dinner after meeting with the new married couple,
where came also some of the more sober of the neighborhood,
and all ended in a decent manner, and to satisfaction;
the Lord honoring his own name among his little family there,
and drawing several into a good liking of his holy and living way.

On the 30th in the afternoon, being the third of the week,
we had a select meeting with Friends at Frederickstadt,
and the Lord was pleased to visit us together,
and afford us a comfortable season and parting.
But though intended for Friends alone, and in our lodging at Gilbert Otterloo`'s,
yet some others found us out, and came there, not diminishing,
but adding to our satisfaction, being made sensible of the power of the blessed Truth,
then eminently among us to his own glory; and among the rest was Jacob Van-Maseick,
a wine merchant of that place, who had been at most of our meetings there, and I think,
fully convinced of Truth,
having owned himself satisfied on the point of
baptism at the second meeting we had there.

After meeting we went to take leave of Nicholas Ovens,
the burgomaster who had been friendly to us; but not being within,
his wife entertained us with friendship,
repeating her satisfaction with a meeting she had been at,
and also with what had passed at their own table when we were there.
Though we had not the opportunity of seeing him at his own house,
he came a little after to our lodging, and brought us a pass under his hand,
and the seal of the city, very necessary in those parts,
by reason of the great sickness at Altona, and the suspicion on Hamburg on that account;
and after some free and religious conversation, and good wishes on all sides,
he departed, showing us respect, and made the pass without any charge.

On the 31st, in the morning, we set forward,
accompanied to the river by most of the Friends there, and some others already named,
and parted with them near the river on the bank, leaving them in much love,
in which we had been drawn to visit them.
It was a solid, but not altogether sorrowful parting, though not without tears;
for we bare in our breasts, on all sides, I believe,
that which will make our mutual remembrance comfortable in distant places and times.
We had the company of our friends Gilbert Otterloo and John Van-Campen,
as far as the ferry-house on the Else, near Brunsbottle,
where we arrived in the evening about sunset.

I observed the people in the inn at Mildorp, as soon as the clock struck,
suddenly to change their several postures, and seem to be very serious and silent,
and everywhere enter upon some seeming devotion,
as when they say what they call their grace; some pulling off their hats,
and silting still, as if at prayer,
and others turning to the windows and walls in like seriousness,
which gave me occasion to inquire the meaning of it; and I was answered,
it was the custom of that place,
that as soon as the people heard the clock strike twelve, they all went to prayer.
But I observed the ceremony did not last long,
nor did any of them pray with an audible voice.

They seemed, nevertheless, a people ready for the reception of better things,
and I believe the Lord will, in his own way and time, visit them.
I asked our landlord why they had so many images of Christ in their churches and houses!
He answered, "`It is to put us in mind of Christ.`"
I replied, "`It seems you do not love Christ so well as you should,
since you lack so many outward mementos of his outward appearance.
But the primitives had the mind and Spirit of Christ;
they bore in their own bodies the dying of the Lord, and wore his cross in their hearts,
by which they were crucified to the world, and the world unto them,
with all its empty show and vain glory.
And this cross is that living virtue and life of Christ,
appearing in men`'s hearts now as well as in those days,
working the same effects in all who believe, follow, and obey it,
being the saving grace and light of Christ unto all people.`"
This seemed strange and surprising to him, as appeared by his countenance;
and I believe it answered his conscience, for he made no reply,
and I felt the love of Truth to him and the people there,
but nothing for a meeting at that time.

From there we proceeded in our journey,
and in the evening came to the ferry-house by the river,
but could not get over till after twelve in the night, the tide not serving before;
and about that time, or a little after,
parting with our friends at the river side in much tenderness, we embarked,
but not without some exercise, for the ferry-man had, in the night,
taken on board one hundred and sixteen hogs, and though there was a place apart to be in,
yet it was only a partition of boards, with wide and open chinks;
so that the smell of the hogs was very noisome,
the hatches being down for the conveniency of sailing the vessel.
To complain of this to these boorish people,
would only have raised their temper to give us further trouble;
so that we sat down with it in patience.
We came to the ferry-house about eleven, where, being provided with a wagon,
we set forward about twelve,
and that night about eight arrived at an inn twenty-four miles from there.

About one in the morning, being moon-light, we set forward in an open wagon,
and in the evening arrived at Breme, and lodged at an inn, where we had been before,
and were kindly received; but I having taken cold, an intermitting fever,
to which I had of late been subject, returned upon me,
which much impaired my health and strength.

In the morning we spoke again with Sarah Schreders,
with whom we had conversed as we went to Hamburg,
and we found things were at a low ebb among them relating to Truth,
hardly any of them having courage to entertain a meeting, she herself having no house,
but being with her brother, who, though he had passed under that name some years,
was still very weak and depressed.
And he and another, who was also friendly, but sometimes went to the public worship,
came to the inn, but could not give us any hopes of a meeting with them,
for they feared the magistrates and priests,
there being both Lutherans and Calvinists in their public churches,
and the people generally of these two sects.
I was under a burden in my spirit after they were gone from us,
and was ready to depart under it;
but John Padley was rather desirous to stay a little longer,
and go to some of their houses, which we did, and some more of them being together,
they took courage and consented to a meeting the next day;
and then we were a little easier.

On the 4th, being the first of the week, about nine in the morning,
we met In Hendrick Schreders`' house, in a back room, where came more than we expected,
and the Lord was pleased to be with us to our help and comfort;
but so cowardly were most of them,
that as my voice began to be raised so as to be heard further than the room or house,
they could hardly sit for fear,
which both hindered themselves much of what otherwise they might have received,
and also made my exercise the greater; and yet they stayed till I concluded.
As John Padley stood up to speak, several went into the other room in haste,
some knocking at the outer door frightened them;
but it proving only some that desired to come in, they came into the room again,
and stayed quietly the rest of the meeting, which, notwithstanding their weakness,
was pretty comfortable, and several of them were broken and tendered;
and they were generally very loving when we parted with them.

Before we went from the house, we had a message from a priest,
of whom we had heard something before, who desired to see us at his house,
which we also had desired, but had heard he was under exercise of mind,
and was so retired that he did not care to converse with any body.
When we went in, he received us at the entrance of the door very respectfully,
and took us into an inner room, where being placed, we were silent a while;
and some things opening in my mind suiting his condition, I spoke them,
wherewith he was well satisfied.
After I had done, he spoke a few words,
by which I perceived he was in a good degree illuminated by the divine Truth;
and in a sense of a fresh spring of love and life at that time in my soul,
I was much broken, which also reached him, and after some time in that condition,
we were bowed in prayer,
where I found my spirit much more at liberty than in the meeting,
and the Lord gave us a divine season of his love,
and a visitation thereof together at that time.
When this was over we fell into some conversation, wherein he was very open and free,
and gave us to understand, that he had in his first concerns in the world,
followed merchandising, wherein he had gained well;
but a desire entering his mind to be helpful to mankind in a better concern,
he went to the college, and studied about five years; when,
finding himself sufficiently qualified, as he thought, for the work he aimed at,
which was to be a teacher among the Calvinists, betook that function upon him,
and had been very acceptable among the people there.
But it pleasing God to open to him the emptiness of the priests,
and all outside shows and formalities in religion,
he had published his sentiments openly in his sermons,
especially the insufficiency of human learning, without the Spirit of Christ,
in the ministry; and that such a ministry could never profit the people,
but greatly hurt them, and much to this purpose.
He added, that he expected very quickly to be cast out from among them,
for this and other doctrines he had preached,
contrary both to their principles and practices; but being clear in his understanding,
and having peace with the Lord in what he had done,
and not needing their favor on account of a maintenance,
for the Lord had blessed him with a competency, he was resolved, by the grace of God,
to maintain his doctrines against them, and stand his ground,
let them do what they would.
This was very acceptable to us, and he was thankful to the Lord for our visit,
which he said was a strength and confirmation to him;
and those things I had said to him were agreeing to what was in his own mind.
He had that text ready before him, how that many believed in Christ,
but dared not own him for fear of the Jews, and being cast out of the synagogues;
which he knew at that time, he said, was the state of a great many in that city,
who were convinced of the way of Truth,
but were not yet able to confess it in an open manner,
but he was in hopes the Lord would give them strength in time to own him freely;
and this was also our apprehension of that people.
At our parting, he embraced us with much affection, wishing us a prosperous journey,
desiring we might remember one another in the Lord.

We were told by some of these friendly people, that this young man,
for he seemed not above thirty years of age,
being more fervent and spiritual in his doctrine than any of the rest in town,
was much admired and followed by the people,
which raised the emulation and envy of all the priests,
and they watched occasion against him; but being of a holy life,
and much pressing that in his ministry,
they could not find anything till he set forth the necessity
of inspiration and the Spirit of Christ in a gospel ministry,
and that all who were made ministers by men only, without the power of Christ,
which alone could make a minister, and that without any help, power,
or authority from man, were only intruders and pretenders, and not true ministers:
nor were the ministers of Christ to teach for hire, but freely.
This was what they had now against him, and had him at this time under dealing,
having admonished him twice, and the third time at hand,
in order to cast him off and silence him, which he seemed resolved to bear,
rather than recant his Christian doctrine.
For though he had gone to the college with that intent at first,
being now better informed, he leaned upon the Lord for strength and wisdom,
and not upon his learning, in which he was not inferior to any of them.
We heard also of some others, in other places, cast off for the same reasons:
so that the Lord is at work in many hearts against antichrist and his ministers,
in several parts of the world, and that day drawing near, wherein,
alas! alas! with wringing of hands,
must be the condition and cry of all the broken merchants of Babel;
for their old rotten ware will sell no longer, because there is wine and milk, yes,
all dainties and delicate things, to be had freely at the table of the Lord,
in his holy city, without money and without price.
"`For the Spirit and the bride say.
Come; and he that heareth says.
Come; and whosoever will come may come, and drink of the water of life freely.`"

We set forward from this city about three in the afternoon,
but were stopped about a quarter of an hour at the gate, till their divine service,
as they imagine it, was ended, that being their order to their soldiers.

At last the gates were opened, and we departed in peace,
though much gazed at as we sat in the wagon,
because they directed to us their formal salutations,
and had not the like formal returns, but did not abuse us.
That night we rode till about the tenth hour,
and then lay down on the straw on the floor, where also stood the wagon and horses,
and cattle, tied on each side.

On the 5th, early in the morning, we set forward in a great fog, and coming to Oldenburg,
were there stopped at their gates by the military formalities, for about half an hour,
while our pass was sent by a sentinel to the superior officer of the guard,
and from him to the chief, and so back to us; and entering the city,
after some refreshment we passed on to Leer, where we arrived about ten at night.
After some refreshment, going to bed, I had the fever all night,
as every night from that at Breme; and by much sweating and fatigue of the journey,
in their open and jostling wagons, was much weakened,
but not sensible of any pain or sickness.

In the morning there came to us one who had formerly
been a teacher in that place among the Baptists,
and very acceptable to them, being of a good conversation;
but through an inward conviction that he had taken upon
him what the Lord had not called him to,
he left it off, and lived retired, and not in communion with any,
but loving all that were honest and spiritually minded;
and we found him pretty near the Truth, both in notion and spirit.
Desiring to have a meeting there,
this man went with us to speak with the Baptist teacher in town, who being absent,
we went to the house of one of the elders,
by which we understood we could not have a meeting in their meetinghouse,
as some of our friends had had the year before:
they themselves having liberty only by connivance and payment of money,
the meeting our friends had there before had drawn their liberty into question;
and complaint being made against them, the matter was now depending before the court,
and they knew not how it would end,
or whether they should not all be banished the town on that account;
and therefore were not willing to commit the same crime to aggravate the magistrates:
for none have toleration there, by the emperor`'s orders, but Papists, Lutherans,
and Calvinists.
Upon this I told them, we were not come there to add to their sufferings,
but were sorry it should happen so on that occasion.
I took this opportunity to inform them, that we in Britain and elsewhere,
professing Truth, had been persecuted from the beginning.
Some of us had suffered banishment from our native country,
for our testimony to the Lord Jesus,
and his divine light and grace made manifest in our hearts;
and yet had experienced the goodness of God even in that:
for some had obtained greater riches in the world,
in those parts to which they were banished, than they had before.
Others had suffered long and hard imprisonments, even unto death,
in dirty and stinking dungeons; some, spoiling of goods and loss of lands,
with cruel whippings, scourgings, derision and mockings; and some had also been hanged,
and thrown into pits, denied burial for the testimony of Jesus,
which we were now preaching in these countries.
But the Lord was with us still in all this, and was our support and comforter,
or else we had not been able to endure what we had met with from false Christians,
and cruel persecutors, for his holy name`'s sake; but the Lord had now made way for us,
and we had as much liberty as any others.
I told them also, that the Lord had visited a people in France; but they being yet weak,
and flying the cross, left their native country,
and fell short of that testimony given them to bear;
but the Lord being still at work among them, they would at length stand as we had done.
I also observed, that there were many here in Germany, and the countries about,
convinced in their hearts of the same Truth and principle of divine light,
who being yet weak, and fearing persecution, were not willing openly to own It,
which might prove to their utter ruin; for Christ, who is the light of the world, said,
"`He that confesses me before men,
him will I also confess before my Father and the holy angels;
but he that denies me before men,
him will I also deny before my Father and the holy angels.`"
And so I proceeded, there being several of them present;
and the man having many children, grown up to young men and women,
his wife called some of them, and they were reached and solid,
and we had a comfortable time among them.
Taking leave of them with respect on all sides, we departed,
and that evening came to Emden.

Soon after we alighted from the wagon, we went to see our ancient friend, Esther Jans,
and to have a meeting appointed the next day.
She told us there was a widow, the mother of Simon Dock, in town,
who had a large granary in a convenient place there, which,
since we had the last meeting, she had of her own accord offered,
in case we should return that way.
Accordingly we ordered it to be made ready, and on the 7th, at three in the afternoon,
had a meeting there, which was pretty large, and many in the street,
and things were opened fully, but the work was something hard,
the people being greatly ignorant of spiritual things;
yet some of them were reached by the Truth, and were tender.
The meeting being ended, we retired to the inn,
and had some thoughts of departing in the morning for West Friesland;
but desiring to be further helpful to the seeking ones among them,
and hearing that several would be glad of another meeting,
we accordingly appointed one in the same place, at two in the afternoon next day.

This meeting was almost as large as the other, and pretty open,
and the way of Truth further set forth among them;
and we parted with them in peace and love.
After we returned to our inn, we went to see Hendrick Zwart,
the merchant who had invited us to his house as we passed that way to Frederickstadt.
He was very open and free with us, and inclinable to discourse on matters of religion,
which suited us best;
and we found him ready to own the Truth in all things we opened to him, which were many;
and we had a satisfactory time.

On the 9th we departed from the city, and arrived at Delfzel about two in the afternoon,
where, after a little refreshment, we look the next draw-boat for Groeningen,
where we arrived that evening.

We had now increased our company,
for Henry Johnson of Twisk had come to meet us as far as Emden,
and Jacob Nordyke from Harlingen, had tarried at Groeningen,
to try for a meeting when we should come there,
which was accordingly had the next morning about the ninth hour;
to which came pretty many Menists, and some others also;
and the Lord was pleased to be with us.
Many things concerning the light and Spirit of Christ, and the Word of God,
were plainly and fully opened to them, and I think, to general satisfaction,
though many things were directly opposed to that doctrine
which many Menists hold against the divinity of Christ,
which was fully proved.
This meeting being well ended, it was in my mind to propose another,
which they generally and readily agreed to,
and desired it might be at the third hour afternoon; which was held accordingly,
and was about as large as before, and very open.
I there set forth largely the one divine baptism of Christ, the Word of God;
and yet did not hear that any of them took offense, but some were well satisfied with it.

In the close of the meeting I proposed a third, to begin at nine in the morning,
which was also held: and being the first-day of the week,
some of our company thought the meeting would be very small,
because they would generally be at their own worship: but it proved otherwise;
for it was larger than any of the other,
and the Lord was pleased to favor us with his presence, and to open suitable things;
and we had a good time among them.
There was a Lutheran at all these meetings, a man of some account in the city,
and was more reached than many others, and tender in the last meeting,
taking leave of us with tears in his eyes, and had offered his house for a meeting,
but we had been provided before.

There was also an ancient apothecary in town who was at all the meetings,
and well satisfied,
confessing freely that water baptism could not be that commanded in Matt. 28:19,
but practiced for sometime, in some places,
in condescension to the weakness of the people,
as were circumcision and other legal rites.
His son and daughter were also at the meetings.

In the afternoon we departed the city in a draw-boat,
and about ten at night arrived at Dockum, where we had a meeting next morning about ten.
It was in the Baptist meetinghouse, and with them only; for they are not willing,
in some places, to let it be publicly known,
lest advantage should be taken against their own liberty.

That afternoon we went to Holfert, near the sea-coast,
where we prevailed with the Menists to have a meeting in their house, which was large,
and some of several sects at it, and some of the town officers.
This meeting was much more open than the other,
and several things of consequence cleared to them.
After the meeting was ended, one of them, as is usual in their own meetings,
read a verse of the seventy-fifth psalm,
as I was told by one of our company who understood the language,
and they fell to singing before we got out; but many of them did not sing,
and one of their teachers went out of the house.
I found myself easy to stay till they had done,
for there was something in my mind to say to them on that occasion;
and the other Friends stayed also.

The song ended, I desired to be heard a few words, which was granted;
and I spoke to this effect,
"`That I had once been among a people who used to sing psalms,
and it was a custom among many still.
But I desired them to consider the foundation of their singing,
whether it was any part of the worship of God, or that he required it of them as such;
and also whether they all sung their own conditions:
for things might be true in the psalmist, which were not so in them.
As for instance, a high-minded,
proud man singing that he behaves himself as a weaned child in silence and rest,
is not true, nor can any sing aright in that state;
though I did not accuse them of pride, but this for instance.`"
I proceeded further, and said, "`That the apostle Paul says,
'`I will pray with the spirit,
and with the understanding also,`' and sing also in like manner;
and speaks of '`making melody in the heart to the Lord in hymns and spiritual
songs;`' but nothing of singing other men`'s psalms without the spirit.
And that I had observed in those countries, among those who think themselves reformed,
a great deal of images, pictures, and outward show,
and also high and lofty instruments of music,
which had not been duly considered in their reformation.`"
This last some of them seemed not to relish so well as the former part,
but none made any answer; and in general,
we had the full countenance and approbation of some of their teachers,
and we parted with them in friendship.

This afternoon we rode across the country to Drachten, where we arrived in the evening;
and my fever being returned upon me some days before, and also a grievous sore boil,
what with these, and the exercise of meetings, I was very low in my body,
but my mind strong in the grace of God, which is a sure stay to all that trust therein.
This evening we sent to the Menists there, to desire a meeting with them,
which they readily granted; and about nine, on the 14th, in the morning, it began.
Several of their teachers were there, and a large gathering of several sorts,
but most Menists, having, we supposed, their whole meeting.
The Lord was kind to us,
and advanced his blessed Truth over all in the wisdom and power of it;
and many things were opened and cleared to general satisfaction,
and some were well affected with the power of Truth.
After the meeting was over, some of their preachers showed us kindness,
declaring their unity with our doctrine; and one of them said,
"`I hope we shall all one day meet in the kingdom of
heaven;`" and so we parted in peace and love.
This is as hopeful a meeting as any among them I have yet seen.

After dinner we set forward towards Goredyke, which was hard enough for me,
having sweat much in the night by the fever, and my strength being spent in the meeting,
together with the pain of the boil, and the trouble of it in the wagon;
but the Lord enabled me by his grace to bear it, for his blessed name and Truth`'s sake,
and for the spreading thereof among the people.

We arrived here about four, and had a meeting about six in the evening with the Menists,
in the meetinghouse, and some others were there.
In this meeting I had strength beyond expectation;
for though I could hardly walk to the place, through pain and weakness of body,
and my natural spirits much exhausted by the fever, travel and pain;
yet the Lord was good, and gave me full strength in a large exercise in that meeting,
and the truth was over all, and the people, both teachers and hearers,
were loving and pleased, and we parted with them in love.
After this was over and we returned to our inn, I found myself weaker than before;
and that night had the fever, but not as at other times, though I got no rest.
Some of the company, for some temporal ends, hastening beyond reason,
we were to set forward the next morning at six for Heerveen.
But as I was putting on my clothes, my weakness and pain were so great that I fainted,
which I perceiving before it fully came, attempted to call to the rest in the room;
but they did not hear me, my voice being cut off by the fainting.
One of them happening to speak to me, and having no answer, put by the curtain,
and found me in the fit; and they used what means they could on that occasion.
After a short time I recovered out of it, but found a great alteration;
the boil was broken, and I became very drowsy, and my spirits more at rest,
and less of the fever; and, after some refreshment, went into the wagon,
none offering to stay, or give me any rest or ease that way,
and the same person still driving home.
O the precipitant haste of this world,
and the hardness of the heart that is overcome thereby.
But that only which prevailed with me to concur in this cruelty against myself,
was the consideration of a meeting,
which we expected was appointed in the Menists`' meetinghouse,
at the place where we were going;
for one of the preachers of Goredyke going there as we arrived,
he said he would procure one for us; but when we came there, about the ninth hour,
there was no appointment, the people being generally at a fair at another town.
I was a little easier,
the motion of the wagon having forced much corruption and blood from my sore;
but lest I should take cold, and wrong my body too much,
and most of all to try for a meeting,
I stayed at that place the remaining part of that day and the night following.
That evening we had liberty of the Menists for a meeting in their house,
at nine in the morning; which was accordingly held.

This meeting was not large, but open and fresh;
and many things of great consequence were made plain beyond expectation,
which made me look a little at the people, they not seeming, by outward appearance,
like such as might have a capacity to take what they heard; but what opened was declared.
In the time of the meeting came in a person, who, by his garb and behavior,
looked like a gentleman, as such are usually called among themselves,
and he was very modest and serious.
After the meeting was done, and we retired to our inn, our host informed us,
that he was in an outer room, in the entrance of the meetinghouse;
where several persons of more than common note had placed themselves to hear us;
among whom was a considerable military officer,
often mentioned in the public news papers, and some with him.
Our host invited them in, but they declined it,
because they supposed it might be some surprise upon the poor people,
and make some disorder in the meeting, which was already settled and quiet.
This was civil, good natured, and genteel, if that was their true reason;
which I have no cause to doubt.

One point opened in the meeting was to this purpose, that "`When our blessed Lord,
in the days of his flesh, on a certain time was preaching to the Jews, he said,
'`Except you eat the flesh and drink the blood of the Son of man,
you have no life in you.`'
Again, '`He that eats my flesh, and drinks my blood, the same dwells in me, and I in him.`'
This doctrine greatly offending the multitude, they said, how can this be?
How can this man give us his flesh to eat, and his blood to drink?
This is a hard saying, who can receive (or bear) it!
And from that time they went back, and followed him no more.
And so great was the mystery of this saying, that the apostles themselves seemed,
at least some of them, to be staggered at it;
which gave the Lord occasion to say to them, Will you also go away?
But Peter, who often showed more forwardness than the rest to answer, said,
Where shall we go`'.`' You have the words of eternal life.
Signifying,
that he and the rest had tasted of the divine virtue
that accompanied his doctrine to such as believed.
Agreeably also to Christ`'s own words, where he said.
My words they are spirit, and they are life.
Now Christ here also told them,
that it was given unto them to understand the mysteries spoken to others in parables.
What then was the mystery of this saying, Except you eat the flesh,
and drink the blood of the Son of man,
you have no life in you '`! This is the meaning of it; it is the spirit that quickens,
the flesh profits nothing.
That is, as if he had said.
If you would eat my flesh and drink my blood in your carnal sense,
and as you literally take it,
that eating and drinking of my flesh and blood would profit you nothing;
but the substance is my spirit, which makes alive,
and also strengthens and nourishes all who partake of it.
Now, there are certain people, whom I desire not to name,
for I would not willingly offend any, who suppose and believe,
that as soon as their priests have uttered certain words of consecration,
as they call them, over a piece of bread, or wafer, or a cup of wine,
that this bread is transubstantiated into the very body of Christ,
even the same that was crucified without the gates of Jerusalem,
almost seventeen hundred years ago, and that cup into the same blood that was then shed.
Supposing this was really true, as it is plain to common sense it is not,
yet this eating and drinking this flesh and blood would profit them nothing;
therefore it is great pity that ever so much bloodshed, so much fire and faggot,
and cruel destruction, should have been made under pretense of that, which,
in comparison of his quickening spirit, profits nothing.
But this blood must yet be reckoned for, and the day hastens.`"
Though I was fully this plain at that time in the open meeting,
and it was interpreted to them, I heard of no dislike or objection in any.
And, I think, it is very hard to be answered,
striking at the very root of that strange and monstrous idolatry,
committed under that false notion,
and all the chain of hideous absurdities consequential to it.

One remarkable thing was here related to us, which I thought worth noting:
one Talken Corslen, a Menist, who lives at a certain town called Dokum, in Friesland,
told us, "`that some years ago, our friend Sarah Collier being in these parts,
desired a meeting with them in their meetinghouse, which they refused her;
but he himself had a secret desire of a meeting, having never been at one,
and accordingly gave her the liberty of his house; where a meeting was held accordingly,
and many were there, and well satisfied.
After the meeting, Sarah Collier having a mind to see his wife,
who then lay ill of a disease which had been upon her for about twelve or thirteen years,
was conducted into the chamber where she lay; and after some time,
Sarah was concerned to pray by his wife,
and for her help and deliverance from her malady, and to his great admiration,
and also his wife`'s, and all who had opportunity to observe it,
his wife recovered presently upon it, and has been well ever since.
He earnestly desired we would come to that town,
promising that he would let us have a meeting in his house, if the Menists would not;
and told us he had left them,
they having some way blamed him about the former meeting.`"

Having finished here, we went on the 16th, towards Jever,
and the Menists being apprized of our coming, they were ready and open for a meeting;
which began about five.
And there being several people in the town, besides the inhabitants,
the meeting was large and crowded,
and the Lord was pleased to manifest his truth and way in a good degree among them;
for the way of life was plainly set forth in doctrine,
and many were under some sense of the peace of it.
This being over, we had the thanks and approbation of their teachers,
which showed their good-will;
this is no small step towards gaining themselves and hearers;
and under that consideration, was very acceptable.

On the 17th, in the morning, being the seventh-day of the week,
we set forward for the town of Oudeboone by wagon,
having detained one with us all this week since the second-day morning;
and being a little recovered, I found myself now more able to bear the journey,
but our wagon beam breaking, I walked on foot about a mile;
in which I found myself very weak and feeble.
Having help from some neighboring houses, we repaired our loss,
and they overtook me in the way; Jacob Nordyke, a Menist, and friendly man,
having been with us all this time, went before on foot, when the wagon broke,
to prepare a meeting at that town.

Arriving there about eleven, we had a meeting in the Menists`' meetinghouse.
It was not large, but open and fresh, several being touched with the power of Truth;
and their teacher was also kind, wishing us a prosperous journey,
and success in our labors.

From there we departed, and came to Grow.
Soon after we arrived, we sent Jacob Nordyke to the Menists,
to see for a meeting next day, being the first-day of the week;
and they sent us word they were glad we were come,
and that we might have had their meeting in the forenoon,
but they expected one of their own ministers, for whom they had sent to another place;
but if he did not come, we might have the meeting still.
If he did come, we might have the meeting at one in the afternoon;
and if we were not then satisfied, we might have another in the evening at five,
which accordingly fell out.
That beginning at one was large, and many things were opened to them,
and several of them were reached by the power of Truth; though, before anything was said,
one of them raised a psalm, and they sung some few verses, and then had done;
but they did not all concur, some sitting silent, with their hats on, and pulled down,
as if they had not been pleased.
This we bore for Truth`'s sake, not joining with them; which they plainly saw.
The meeting being over, I desired another, as they had proposed;
and then their preacher came to us, and taking me by the hand, he embraced me:
he expressed much satisfaction before the people, and received us gladly,
inviting us to take a dish of tea with him; which we accepted.
We found his wife also in the same mind with him, openhearted and kind.
The meeting at five o`'clock was not so large as that before, but very open;
and some other sort of people also came among us, and all as still as a Friends`' meeting,
many things clearly and freshly opening among them.
It being ended, their teacher invited us again to his house,
and there treated us as if he had been a Friend; from which he is not far,
having been as tender as any in the meeting.
When we look leave of him, he embraced us freely,
and we had a great many good wishes from that honest sincere man;
which we also returned in true love,
leaving the door wide open for those who may come next:
and so we retired to our quarters.

On the 19th, we set forward by water, for Leuwarden, where we arrived about nine o`'clock;
and, sending out Jacob Nordyke among his acquaintances, the Menists,
to see if we could have a meeting, they readily consented to have one with us,
to begin at the first hour.
In the mean time we took a turn to view the city, and particularly the prince`'s gardens;
where we saw some foreign plants, rare and curious, and also many orange trees,
and several with ripe fruit, being forced with stoves;
but not comparable with the same sorts in their native soil.

The meeting was larger than we expected, and very still,
and many things were opened to them in the wisdom and power of Truth;
especially the fall of the first Adam, with his posterity;
the temptations and victory of the second Adam,
and the overcoming and salvation of all who believe and obey him,
but the final loss of all who disbelieve and disobey him.
For he is the same Word who was in the beginning, and in whom was life,
and that life the light of men; and by whom that prohibition came, you shall not eat,
for in the day you eat you shall surely die.
And eating, they died unto that life, and became blind also to that light,
and so fell from God who is that light;
and therefore the posterity of the fallen man must again believe in the same Word,
light and life, and also obey and follow him;
or else they remain in death and condemnation; and so departing this life,
having slighted the day of visitation by this light,
which is the true light which enlightens every man that comes into the world,
and that once was made flesh, and dwelt among them, +++[+++they]
are concluded under death and darkness forever.
For he said to the Jews, "`he that believes not is condemned already;`" that is,
whosoever has sinned, as the first Adam did, though not in the same thing,
is under condemnation and death;
but true faith coming by the word of life in him who has it,
and justifying the sinner from his sins, makes him holy, just and true;
for this faith purifies the heart, works by love, and overcomes the world.
Then such are free, and live to God, and no more to sin.
Then they keep that great saying of Christ, "`as I have kept my Father`'s commandments,
and abide in his love, even so do you keep my commandments,
that you may abide in my love.`"
And then he that has the Son has the Father also,
and he that has the Son he has life indeed, even life eternal,
etc. with much more of this kind, which I cannot now remember.

This meeting ending, the countenances of the people were open and free; but,
being in haste to take the boat, the last for the day being ready to put off,
we had no conversation with any of them, but only Wopke Clauses and his wife;
who kindly embraced us, and invited us to their house;
but giving them to understand our inclinations to depart in the boat,
they saw there was no time for it, and he went with us to the boat, and she also near it;
we coming a back way out of the meetinghouse, which he took us, being nearer the boat,
and out of the crowd.
He is a ruling elder of that congregation;
they expressed their satisfaction with the meeting, believing it was so to all;
and wishing us prosperity, and embracing us at the water-side, we parted.

That night about nine, we got well to Harlingen,
to the house of our friend Amilie Joestens; where we were kindly entertained by her.
Here also we found another friend, namely, Cornelius Jacobs, who came from Twisk,
in North Holland, to meet us.

Notice being given of our arrival that night, there was a meeting appointed next day,
the 20th, to begin at four in the afternoon; which was accordingly held.
It was small, being the market day, and not very open; as few meetings were,
where that sect called Collegians had any considerable sway.
Several of them were there, and some necessary truths were clearly opened;
especially the divinity of Christ, which they commonly deny;
and also his baptism with the Holy Spirit, of which they are ignorant.

At the close of this meeting another was appointed to begin at nine o`'clock the next day,
in the little room Friends have there; for they have a meeting,
though very few in number.
This was larger than the other, and more open; and a third was appointed,
to begin in the afternoon; which was rather the largest, and most open.
So that Truth seemed to gain upon them, and we heard of no objection made by any of them.
On the 2nd we came by wagon to a town on the coast, called Dokum;
and Jacob Nordyke being still with us, he went to the Menist teacher`'s,
and he let us have their house, in which a meeting was appointed at the tenth hour.
It was not large, but most of the heads of them there, and very sober,
hearing attentively several things of importance opened to them; one of which was,
that it is not our embracing true principles and notions doctrinally,
and so sitting down under these, in an imitation of good and godly men,
that will bring us to heaven,
unless we be also in the same life and virtue in which they were;
nor can any inherit the kingdom of heaven, unless they be in the nature of heaven;
which cannot be but by regeneration by the Word of God; the same that was made flesh,
and now appears a quickening spirit.
This they seemed to receive well, though the meeting was not very open as to life,
but laborious; yet solid, and ended well in free and open prayer.
After the meeting we visited the woman who was healed as before mentioned, +++[+++p. 238];
she and two or three more who came to the house, who are under a convincement,
are pretty tender; and after a short prayer with them, we exhorted them to meet together,
and wail upon the Lord by themselves in silence.
One of the friendly folks in this town going to the Calvinist teacher,
to invite him to the meeting, he said, "`if the meeting had been in a private house,
I would have come, for I desire to hear them; but, being in the Menists`' meetinghouse,
if I should go there, it would be taken notice of by my own people,
weaken me and my party, and strengthen the Menists;`" but he was very friendly.

This afternoon we passed along the coast to Henleven,
and procured a meeting with the Menists--that
sect called Collegians--in their meetinghouse;
which began about the sixth hour.
It was pretty large, and most of their chief people there, also one of their preachers.
This was the most open meeting we had on that coast,
and many things of great weight were made plain
and clear to the understandings of several,
and especially one of their teachers, who expressed his satisfaction.
The divinity of Christ was fully set forth, and proved according to scripture;
showing them, that the divine nature is not the human nature;
neither is the human nature, abstractly considered, the divine nature;
but the divine Word, assuming a reasonable soul,
and clothing that soul and Word with that holy body, born of the virgin Mary;
this is the true Christ, and so appeared to the Jews.
This meeting ended in much sweetness in prayer, and I had great peace after it,
and was very easy, as if I had done on that side the sea.

The next morning we went forward by water; and through the goodness of God,
our great Protector and Savior, we arrived safe at Enchuysen, in great peace with him,
about seven in the evening; and went to the house of Martin Daniel, a friendly man,
who with his wife received us freely.
But after supper, discoursing with him about a meeting,
he told us there was hardly any in all that great city who inclined to come to a meeting,
they being generally Calvinists, full and lacking nothing.
Next morning he had considered it further, and said,
"`if you will stay till the afternoon,
I will tell all whom I have any expectation will come, who are but two or three,
and let you have my house to meet in.`"
But we finding things so cold, and expecting better service elsewhere,
did not think proper to stay upon so uncertain a ground.
Before we departed, I exhorted them to be true and faithful to the Lord,
according to the degree of manifestation they had, and then they might expect more;
and after a time of prayer, whereby they were both much reached and tendered,
we parted in peace and love, he conducting us to the gate of the city.
We departed by wagon, and in our way, called to see Dirrick Mindersen.
He had been a Menist, but for some time, had withdrawn himself from their worship,
and remained alone; but his two daughters inclining to our meetings,
he had given them their freedom, and himself also had an inclination to Truth.
He received us very kindly; and after some time of silence after dinner,
John Padley had some words in prayer,
I also having had a secret concern during the time I had been there;
and when John had done, I then spoke to this effect,
"`That the Lord was at work in many hearts to draw men under his own blessed teachings;
and the voice of the angel of the covenant of life was
now calling to the people of God yet in Babylon,
to come out of her; not to be partakers with her in her sins,
lest also they should partake of her plagues:
and so exhorted him to be true and faithful unto the Lord in what he knew,
and the Lord would soon make him wiser than all his former teachers, etc.`"
I then kneeled down in prayer; in which we had a very tender and comfortable season.
He went with us about a quarter of a mile, and we parted with him in much tenderness,
he heartily embracing us.
That afternoon we went to Twisk, with our friend Henry Johnsen;
where we were kindly received by him and the rest of our friends.

The next day, the 25th, we were at their meeting, which was not large;
but there being several of the sober neighbors at it, the little place was full.
But here, where we might have expected more openness than in many other places,
being most of them such as make some profession of Truth,
I was very sensible of as great a power of darkness as
in any place we had been in all this journey;
and the meeting was dull and dry a long time in silence,
and hard to be wrought through in testimony; but the Lord being with us,
gave us victory and dominion in the end, and several were tendered and comforted.
The meeting being ended we went to Henry Johnsen`'s; and most of the Friends,
who may be so accounted, came to us,
expecting some further comfort and edification in our society.

But as in the days of Job, Satan came also to hinder; so there was one of that place,
a man of some account among them,
who had for some time met with them and professed Truth,
and yet was full of self-conceit and self-contrivance.

He at first, had opposed their weekday meetings, and then falling in with them,
would sleep great part of the time, and then stand up to preach; and sometimes,
in the end of a silent meeting,
would propose that all should kneel down together in the meeting in silent mental prayer,
before they parted; and this mental prayer he pretends to perform every night.
He is also for the continuance of water baptism, and the bread and wine.
By these whims he has been hurtful to Friends and others in this place,
they being yet but children in the way of Truth; and some he partly draws with him;
he and they keeping to meetings under all this,
and thereby laying a greater load upon the right-minded.
These things were largely spoken to in the meeting,
with a caution to Friends to keep close to the power and virtue of Truth,
which is the substance of all; and to beware of such as would draw them from that,
and back into the rudiments of the world;
which had not profited those who had been exercised therein, who now, as of old,
wanted something to glory in, in their flesh, and in an outward show;
being ignorant of the life of Christ; and where that took place, such were of no account:
but where they could continue in imitation of shadows, they magnified themselves,
and boasted.
This galled him much, and he seemed sullen after the meeting;
but said nothing till he came into the Friend`'s house, and brought another with him,
a stranger from Groeningen.

Soon after they came in,
the stranger began slyly and smoothly to move some conference about matters of religion,
and more especially drew on towards the subject of baptism; but being aware of them,
we were upon our guard; and the controversy falling to my share, it held not long.
For as his chief allegation was, that Christ instituted another water baptism,
distinct from John`'s baptism, urging Matthew 28:19, for proof, I repeated that,
and the other texts uttered by Christ at the same time, explaining that in Matthew,
which is but a small part of what the Lord then said;
in all which there is no water baptism mentioned, but only John`'s,
and that by way of distinction to the baptism of the Holy Ghost,
the true baptism of Christ there set forth.
This put him to the common reply, that is, to a conjecture that it was water baptism,
from common circumstances; which was balanced by other circumstances to the contrary,
and overruled by the apostle`'s doctrine, where he says,
"`There is one body and one spirit; one Lord, one faith, one baptism:
for by one spirit we are all baptized into one body, whether Jews or Greeks,
bond or free; for we have all been made to drink into one Spirit.`"
This is the Spirit of Truth, even of Jesus Christ,
who is that one Spirit of Truth and eternal life; into whom whosoever drinks,
and continues to drink, is a true and living member of that holy and living body,
in which that holy Spirit dwells as a living and holy temple, and of whom he is the life,
and only ruler and head; "`even the church, which is his body,
the fulness of him who fills all in all; the church of the first-born,
written in heaven;`" the true spouse; "`bone of his bone,
and flesh of his flesh;`" of one spirit, life and nature with him.
He was then at a pause, and so grew a little hot, which I reproved him for,
and cautioned him against it; telling him,
if he let that fire arise in him it would darken his understanding,
being from the root of evil.

Then his pretended friend showed himself,
and alleged some insignificant things in the same, or more heat than the other.
Then they owned that water baptism was not saving of itself; but only, being a command,
should be complied with, because commanded.
But this being only a begging of the question, I again insisted on proof.
Then he alleged Peter`'s question, "`Who can forbid water,`" etc.
I asked him who Peter spoke to in that question?
And it appeared he spoke to a few believing Jews then with him.
And as a question is no command,
so there were prudential reasons for what Peter thought best at that time,
as things were then circumstanced.
For these Jews, being always tenacious and bigoted to ceremonies and shadows,
even after they had believed, if Cornelius and his house had not been baptized,
or at least an offer made of it, for it does not appear that they were baptized,
these Jews, and others who might hear of it,
might think those Gentiles still wanted something they
should have had to make them complete,
and so deny them communion; which, when all was done, they were apt to do,
being always self-conceited of themselves, and a tincture of the old bitterness,
and contempt of the Gentiles still remaining after they had believed in the same Savior.
To this I added, that the apostle Peter, in his defense before the apostles and elders,
did not so much as mention this passage about water baptism; but on the contrary,
places the command and baptism of Christ, in Mat.
xxviii.
altogether upon the Holy Ghost.
I alleged also, in the proper part of this conference,
that it is not "`the putting away the filth of the flesh,
but the answer of a good conscience towards God;`" and therefore not
that baptism which extends only to an outward cleansing of the body,
as water can only do;
but that inward baptism and cleansing of the mind and conscience by the Holy Ghost,
and fire of the word of God and Spirit of Christ; for,
"`not by works of righteousness which we have done,
but according to his mercy he saved us.`"
But how?
"`by the washing of regeneration, and by the renewing of the Holy Ghost.`"
And this baptism is known by its effects; for, by this baptism,
"`we are buried with Christ into his death; who, in that he died, he died unto sin once,
but in that he lives, he lives unto God:`" so that they that are thus baptized,
and thus buried, "`are dead indeed unto sin, but alive unto God,
through Jesus Christ our Lord,`" the second Adam, the Lord from heaven,
the quickening Spirit.
"`That like as he himself was raised from the dead,
by the power and glory of the Father,`" which was a full and perfect resurrection,
even so also all those that then were, now are, and hereafter shall be, so baptized, are,
and shall be so raised, as they keep with that holy Word of life,
and divine power and nature, which effects this great and truly wonderful change;
which common observation and experience in all ages teach water baptism could never do,
or can do, by whomsoever administered, though even by Peter, Paul, Philip, or any other,
or all of the apostles.

I further urged, that since Paul was the apostle to the Gentiles,
and not one whit behind the chief of the apostles; and since that command in Mat.
xxviii.
was given long before his conversion and call to the ministry and apostleship,
if that had been a command for water baptism to all who
should have a part in the ministry and apostleship,
then it would have been a command to the apostle Paul.
But he did not think he had any power from that text, or in any other way,
to baptize with water; for long after this he says, "`Christ sent me not to baptize,
but to preach the gospel;`" which was to open the blind eye, to unstop the deaf ear,
"`to turn them from darkness to light, and from the power of Satan unto God.`"
That is, from the spirit and power of the prince of this world and of all the ungodly,
who is the prince of darkness, and blinds the eye of the ungodly;
and unto the Prince of peace, the true light,
"`who enlightens every man that comes into the world.`"

This almost silenced them, and then they fretted; and the stranger replied,
"`That since it had once been in use, what hurt could it do to any,
though such had already received the Holy Ghost,
having been once administered to such?`"

I returned, "`That so had circumcision, yet not fit at this day.
But this is not all: water baptism is imposed as a command of Christ from that text,
where there is no command for it, and is will-worship, made a part, and a great part too,
of the Christian religion, and not by Christ`'s authority, but by the errors of men;
not being of the true nature of the kingdom of Christ, which is spiritual, but a shadow,
in which antichrist has wrought in a mystery;
all shadows being of the nature of darkness, and continued beyond their due bounds,
become hurtful.
This having been as a garment or cover to the ungodly for many ages,
God hating the garment spotted by the flesh,
cannot approve of men in their unwarrantable imitation of any shadow,
at any time in use in the church; but has raised witnesses against them,
and for the ever-living substance: without which, all that man can do or imitate,
is but as Cain`'s sacrifice, of no acceptance.`"

Upon this they grew impatient, and wanted to be going,
and after a few soft words to them by John Padley,
in a testimony to the life and substance, telling them that we were surely come to it,
without the use of any shadows,
and therefore he exhorted them to wait for it in themselves;
they went away under a disappointment.
But though we, by their means, were also disappointed of
the comfort we expected with these few tender and living souls,
who in love came to visit us,
yet this afforded some satisfaction and confirmation to them.

The next morning they all went with us to Horn,
where we had a far more open and comfortable
season together in the Menist`'s meetinghouse,
which began at nine in the morning.

After the meeting we went into the Trackshute,
and that night about seven arrived safely at Amsterdam,
where our friends were glad of our return, and received us kindly.
Here we stayed till the 28th, being the fourth of the week, and their meeting-day.
The meeting was small and cloudy,
but Truth in some more dominion than in the meetings before in this place.
On the 29th was their quarterly meeting, which was small and dull.

On the 30th we went to Harlaem, and had a meeting there,
which was both larger and more open than that we had before in this place,
many things relating to Truth being clearly opened, and the Truth in good dominion,
and the people generally satisfied, and Friends comforted.

Next day, in the afternoon, we returned to Amsterdam, and on the 2nd of the eighth month,
being the first of the week, we were again at the meeting,
which was larger and more open than on any other day, both forenoon and afternoon.
For several persons coming in when they hear of strangers, there is, for the most part,
a fresh visitation to them, which makes things more lively and open,
though the meeting was not so large as some Friends expected,
by reason of the rain that fell that day.

On the 5th, being the fourth of the week, we were at their meeting, which was small,
dark, and hard in the forepart of it,
but Truth prevailed in some good degree before it ended.
That evening there came a dark and heavy load upon my spirit, from a cause then unknown,
as to anything which outwardly appeared, and so continued till the sixth-day; when,
after some discourse with an ancient Friend,
concerning certain offenses and misunderstandings
between some of them about little things,
I found myself much easier.

On the 8th we visited several families of Friends in town to our mutual satisfaction.
On the 9th, being the first of the week, we were there again, and being fair weather,
the meeting was large, and many strangers; and the Lord was pleased to condescend to us,
and give me a good time to the clearing of my mind fully among them,
and Truth was over all and exalted: in the afternoon the meeting was not so large,
but pretty fresh and open, especially towards the end of it.

On the 11th, taking leave of them in much love, and pretty easy in our minds,
we went to Harlnem, and that evening had a meeting there, about the sixth hour,
which was large and very open.
Several teachers of different sorts were at this meeting, and generally satisfied,
some of the Menists expressing it freely and openly.

On the 12th, about ten in the morning, accompanied by our ancient friend Jacob Claus,
an old servant of Truth, and of the ministry,
as an interpreter in above thirty long and laborious journeys,
we departed from here in the draw-boat, and arrived at Rotterdam that evening about eight,
and Robert Gerard meeting us in the way, took us with him to his house,
where we were well and openly entertained.

Notice being given of our coming, we appointed a meeting next day at five in the evening;
where we had the company of some people of different persuasions, as Presbyterians,
Baptists, Papists, and one Menist teacher,
though we knew not what they were till after the meeting.
Truth was declared plainly and fully to them; during which they were very still,
and seemed touched with some sense of the power of God, which reigned in the meeting;
though the same thing, opened as formerly, about transubstantiation, namely:
"`That if the bread,
after consecration (as they call it) were really transmuted into the very body of Christ,
retaining only the accidents of bread, and were really eaten in that sense,
which some people take it in;
yet even that eating of his flesh and drinking of his blood would profit nothing.
For we have the authority of Christ himself against all the world,
that his real flesh and blood profits nothing to
be eaten and drank in the sense of the people,
who carnally conceived such an eating and drinking from his words;
by which he intended a being quickened by his Spirit, and living unto God by him,
who is the resurrection and the life, the second Adam, a quickening Spirit.`"
This was a good meeting, and the Lord`'s name was honored by it.

On the 16th, being the first-day of the week, we were there again,
both forenoon and afternoon; and people of several notions were at the meeting,
and things opened largely and with good authority, concerning Christ as God and man,
and the object of the faith of the Gentiles, as he is light and life,
being so promised of the Father unto us.
The meeting being over, we had the comfort of the society of Friends at our lodgings,
where we had some discourse and conversation concerning Truth and divine things.

On the 19th, being the fourth of the week, and their meeting-day, we were there again;
and being a select meeting, altogether of Friends, it was small;
but the Lord was graciously pleased to visit us
together in his tender kindness and mercy,
and opened things fully to the states of all, and it was a good meeting.

On the 22nd John Padley embarking for London, and no opportunity offering for Yarmouth,
where I intended, I was there also the next day; and being the first of the week,
the meeting was full, both in the forenoon and afternoon,
and many things were fully and plainly opened, and they generally satisfied;
and the Lord`'s presence being with us, it was a good meeting.

The winds standing contrary, and generally stormy or foggy weather,
I continued here longer than otherwise I would have done,
but was from time to time with Friends at their meeting;
and the Lord was pleased to comfort us together, and condescended to be with us therein.
During this time I inquired more particularly
into the state of the Menists in those parts,
and found that all along their ministers had preached freely,
till of late some here and there had begun to receive hire, but were moderate therein;
and though they still keep up their old testimony against fighting and swearing,
yet they are not so lively in their worship,
or so near the Truth as they were in their first appearance;
and I was informed that their ministers are, for the most,
but weak and dry in their ministry,
and sometimes their hearers had rather some of them would be silent than preach,
though gratis.
If thus it be, it has fared with them as with many others, who,
having had a day of visitation from the Lord,
and obtained a reputation through his goodness among them,
and by that holy and innocent conduct they have had through his grace;
yet some becoming more loose, and not keeping in the grace of God,
and the virtue and power of it, have ended in mere formalists; and then,
in a generation or two, little has appeared but the outside and form of godliness,
which the power of grace brought forth in those who went before,
and so in a great measure it is with them; and yet, in the main,
they are preserved from the gross evils of the world,
and I hope the Lord has a visitation of life and power yet in store for them.
Among other things I obtained the form of words used by them instead of an oath,
which is thus: "`In the words of truth, instead of a solemn oath, I declare,`" etc.

The wind at length coming fair, and I inclining to take the first likely opportunity,
on the 13th of the ninth month, +++[+++1715]
about six in the evening, after two good meetings, being the first of the week,
I went to the Briel in a boat, and there we lay at anchor that night;
and the wind being high all next day, we stayed there till the 15th,
about eleven in the morning, when I embarked on board the John of Yarmouth,
Michael Bailey master, the wind being easterly, and a steady and fine gale,
but very cold, and through the good providence of God,
arrived safely in the harbor at Yarmouth on the 17th, about nine in the morning:
for which, and all the preservations of the Lord through so many dangers,
I desire to remain thankful unto him only.

I continued at Yarmouth till the 20th, and being the first of the week,
was at their meeting, which, though small, was open and well.
On the 21st we went on to Norwich, and the 23rd being their meeting-day,
we had a good and open time together; for the Lord was with us,
and was very gracious to me in this city.
Here I stayed till the 27th, being the first of the week,
and was at their meetings fore and afternoon.
They were large of Friends, and many strangers were there in the afternoon;
and things opened fully, particularly concerning war and lighting,
and the inconsistency thereof with the nature and end of the kingdom of Christ,
and we had a good meeting to general satisfaction.

On the 29th I had a meeting at Lammas, and the Lord was pleased to give us a good time.
On the 30th I had an appointed meeting at Holt, which was small but lively,
and on the 1st of "`the tenth month one at Wells, which was not large,
but very good and tender.

[.offset]
+++[+++He continued visiting the meetings of Friends in England,
but his health declining he went to London on the 23rd of eleventh month;
respecting which he says:]

Continuing weakly and indisposed, I stayed at London some time,
and the Lord was pleased to make my services
acceptable to his people there in a general way,
and many good times we had together in his blessed presence.
During my stay about this city I also visited some of the neighboring meetings;
as Ryegate, Winchmorehill, Plaistow, etc.
But the yearly meeting at Bristol approaching, and having some drawings there,
on the 14th of the second month, 1716, being the seventh of the week,
I set forward from Loudon, and that night lodged at Ruscomb,
with our friend William Penn, where my company was acceptable,
and we were mutually comforted one in another.

The 15th, being the half-year meeting at Reading, I was there.
It was large, and as open as could well be expected,
considering how long that old separation had continued among them,
and most of the separate party present; but the gospel being preached,
and nothing dropped like reflection, but rather for healing,
things were well and comfortable, the Lord being with his people.
The meeting held till the second-day afternoon, and in the evening I returned to Ruscomb,
and stayed there all third-day.

On the 23rd I went to Calne, accompanied with Daniel Smith,
and that evening had a pretty large and open meeting there among Friends.
The testimony of Truth ran sharply against such
as in an underhand manner colleague with priests,
and support them by payment of tithes, etc.
I heard afterwards some there were guilty; and the honest-minded were comforted,
in that the reproof was full and plain from the testimony of one who
was so great a stranger to any of their conditions in particular.

On the 28th I went to the city of Bristol, and lodged with Brice Webb,
where I stayed during my abode there, and was kindly entertained.

The 29th of second month was the beginning of the yearly meeting at Bristol,
and I had some public concern among them, which took some impression,
and my spirit was unladen in some degree; for I went there in great heaviness.

On the 30th, in the morning, was the meeting of ministering Friends,
which was not so large, they said, as sometimes formerly; but it was a very open,
comfortable meeting.
I was much eased, and we were mutually strengthened and refreshed in the Lord.
That afternoon was their meeting for inquiry into the affairs
and prosperity of Truth within the limits of that meeting,
and things were well and hopeful in the main.
The next day forenoon, being the 1st of the third month, was a time of public worship;
in which I was silent, but much comforted in the Truth and strengthened.
In the afternoon I went to the meeting for business, where I stayed a little while,
and then went to the women`'s meeting.
There I had some time in testimony, and being well satisfied, retired,
and left them to their own concerns in the church.

The next day in the forenoon, being the parting meeting, it was very large and full,
both of Friends and strangers; and after several brethren, I had a public concern,
in which the Lord was pleased to raise his Truth and wisdom over all to his own glory,
and the general satisfaction of his people and others.
For it is not man, but the Lord that works effectually, and the honor is due to God only,
though the weak are too apt to look to an instrument, which, in itself, is nothing.
An ancient Friend concluding the meeting in prayer, it ended in much love and comfort;
Friends being generally refreshed in the life of our dear Lord,
as much as at any meeting for some years there; as we had our enjoyment together therein,
so we also parted.

On the 3rd I went to Frenchay meeting, to which came many from the city;
and it was large, and through the goodness of the Lord, a good meeting.

On the 4th I went to Bath, where, about five in the evening, we had a meeting.
Many strangers being there, things were opened, first, concerning the Holy Scriptures,
their original, by the Spirit of Christ, the word of God; and their divine authority.
And secondly, concerning the divine Word, which, in time of old, came to the prophets,
saying so and so, as in the Scriptures of the prophets; and his being made flesh,
or assuming the whole human nature; and afterwards declared,
by the Scriptures of the New Testament,
to be the "`true light that enlightens every man that comes into the world;`" and
that all ought to believe in this light as manifested in their own hearts, etc.
And though this meeting was not attended with so much of the overflowings of life,
as some others, yet it was to me and several other Friends, a comfortable meeting.
Our friend Samuel Bownas, that able and experienced minister of the gospel, being there,
I was also comforted in his ministry, having some time after me,
as were many more both there and at Bristol; where we also had his help in the Lord.
This meeting ended well.

On the 8th I was at the quarterly meeting at Nailsworth,
which was large and well in the main, but a little hurt by an unskillful hand;
and not having so full a time with them as I desired, I let them know in the meeting,
that I intended to stay their week-day meeting,
which fell the fifth-day following of course, at the same place.
Wanting rest and recruit of strength, I stayed at the widow Elizabeth Smith`'s,
where I was respectfully entertained, as many others, on the like occasions,
had been by herself and late husband, and father; the father being, as Friends told me,
as honorable a Friend as any in those parts in his day.

The fifth-day`'s meeting was larger than usual, and though heavy in the beginning of it,
some being set down in an empty, drowsy dead form, yet after some time and labor of love,
the Lord was pleased to break in and give us a good season;
and the meeting was generally comforted,
though things were terrible against the unfaithful,
especially such as connive at paying tithes, and supporting the priests of antichrist.
After this meeting I was greatly comforted in the blessed Truth,
and Friends were under a weight of solid love and peace.

On the 13th, being the first of the week, I was at the forenoon meeting at Oxford,
and there being soldiers in town to overawe the Oxonians,
much prone to rebellion in that reign +++[+++of King George I.]
some of them, and also of the students of the university, came to the meeting;
but the former were civil, and the latter rude: for most of the few that came,
stood sneering, grinning, and scoffing all the time they stayed;
though so fluctuating that they could not reasonably
take under consideration any matter delivered,
so as to form a judgment; but like Ishmael their father,
mocked at what they could not prevent,
for several things were delivered against the very foundation
of their craft and end of their establishments,
which they did not otherwise oppose.
And yet there were some of them very sober and attentive, and seemed affected with Truth,
as were several sober people also.

In the afternoon the meeting was larger; but as there were more of the scholars,
there was more rudeness,
so that I thought if they could see their own folly and ill behavior,
as it was exposed to others, they could not but be ashamed:
but the greatest part seemed void of sight and sense,
though some were of better deportment, as well the collegians as others; and in the main,
over all that the enemy could do, the Lord gave us great refreshment,
and kept our minds above that evil spirit that moved in them,
and we were comforted together in the Lord.

On the 17th I went to London,
the Lord having made this journey in some good measure comfortable to me,
and also to Friends.

The yearly meeting coming on, I tarried there during the time;
and though we had some good times in our meetings for worship,
yet in our meetings for business, the affirmation, and what arose from there,
ministered great occasion of grief to many souls, especially such as love the Truth,
and the brethren therein.
It was chiefly owing to some rude and forward spirits,
who took boldness from the connivance and indulgence they had met with from such as
had all along strenuously contended to force the affirmation upon all,
and charged all the ill consequences of division upon such as could not comply with it:
but though the comfort of our meeting was greatly lessened and hindered by that means,
yet the imposing designs of these were frustrated,
and the body preserved together and entire, by establishing a just liberty;
which these persons, in their temper and practice have ever denied,
to the unspeakable exercise of the church throughout the world.

On the 8th of the fourth month, inclining to visit Friends in Ireland,
I set forward from London, and went next day to Ruscomb, to William Penn`'s,
whom I found in the same condition he had been in for some time, namely:
full of love and sweetness,
but not able to express himself as before that apoplectic fit,
which had so much impaired his memory.

On the 12th I was at Reading meeting, and the Lord gave us a very open time,
and I was much comforted, having never had so satisfactory a time there before.
Having had some thoughts before of endeavoring
to bring the remnant of those Friends back,
who formerly, by means of John Story and John Wilkinson, etc., had separated themselves;
and several of them having been at this meeting, I went to some of their houses,
where I was kindly received, and spoke to them about it,
answering their objections as things were with me; and I found them not averse to return,
but reluctant to make any acknowledgement of any fault in separating and keeping off,
unless the Friends there would take blame also, and so make a balance;
which I could not by any means yield to.
For they had gone off under a jealousy that Friends were apostates and innovators,
according to the accusations in William Rogers`'s book;
and had long continued in that error and schism;
and being now satisfied that they had been mistaken, and that Friends were not such,
as several of them owned, I thought they might well own their mistake,
and so be reconciled;
for they could not desire to be reconciled with apostates and innovators,
but with a Christian people.
I found one main obstruction was on account of their preacher William Saundy,
and therefore I spoke with him the next day, and laid things open and plain before him,
and found him condescending: but affairs could not then be brought to a conclusion,
he having a mind to consult the rest; but told me he had moved to them the day before,
that they should all come to our meeting, and he would go with them, and most went;
but some staying at their own meeting, he stayed with them.
After a full time with him we parted in peace,
and I was very easy and comforted in the Lord,
after a full and hearty endeavor for their reconciliation;
having nothing in view but the honor of Truth, and their own good in it.

On the 21st I was at the week-day meeting at Nailsworth, which was pretty large,
being one of the largest of itself in the county; and having heard by letter,
that those vessels were gone for Ireland from Bristol,
by which I intended to have gone over there, if I had reached them in time,
and that another would be ready in ten days;
I stayed their meeting at Nailsworth the first-day following,
and though it proved very rainy weather, the meeting was large;
both forenoon and afternoon,
and many things were opened to general information and edification,
and the people very solid and satisfied.

On the 29th, in the morning, I went to Bristol, to my former quarters,
and was at their meeting on the first-day following, which was large,
both forenoon and afternoon, and things very open and comfortable.
On the third and sixth-days following I was there also,
and had comfortable times with Friends, both in meetings and conversation;
for the Lord was with us, and love abounded.

The first-day following I was there again; and in the forenoon, at the Friers,
the meeting was large and open, and in the afternoon, over the river at the other house,
the meeting being crowded by reason of a funeral, things opened fully concerning death,
the kinds of it, and the resurrection from the dead etc.,
and after the meeting I had another time at the graveyard,
where there was a great multitude, and generally very sober.
On the 15th of the fifth month, being the first of the week, I was at Bath,
forenoon and afternoon, where the meeting was large and open,
and Friends and strangers generally satisfied.
The next day I returned to Bristol, where I heard by letters from London and other parts,
that the separate Friends at Reading had laid down their meeting and returned to Friends,
which gave me great satisfaction.

On the 17th I was at their meeting, which was very open and comfortable;
and therein I took leave of them, being bound for Ireland,
and the vessel intending to sail that evening; but the wind coming against us,
we sailed not till the 20th, about seven in the evening, from King`'s-Road,
with an easterly wind, which came up just as we fell down there with the tide.

It being very wet hazy weather, and a fresh gale ahead, we returned back to Minehead,
where we anchored about four afternoon, and went on shore with John Davis,
the commander of the vessel, where I stayed till the 24th,
and then had a meeting at that place.

The wind continuing westerly, I remained till the 26th,
and set sail about the turning of the tide,
and on the 29th came within seven English miles of the city of Cork,
and there being no boat fit to carry my mare on shore, I walked,
willing to get to the afternoon meeting at Cork, which I accomplished,
but found myself much fatigued with the heat and dust, besides the walk,
which proved hard enough, having been sick at sea, and but weak otherwise.
But going to the house of my good friend Joseph Pike,
he gave me a kind and open reception; and I went to their afternoon meeting,
which being pretty open and well, I found my strength return a little.

On the 31st I was at their week-day meeting, which was larger, I suppose,
by reason of the notice going about of my being the dean of Limerick`'s brother,
who was well known in this nation, as having written the history of the late wars there,
and lived long among them in that station; and though it made my work the harder,
their minds being outward, and their expectations high and off from the true object;
yet my mind being only to the Lord, he was pleased to answer,
and things were pretty well.

The 5th of the sixth month, being first-day, was their province meeting:
I was at their morning meeting of ministering Friends, which was small and heavy,
the load of the approaching meeting being upon us;
but the Lord owned us with his good presence in some degree.
The meetings that day, both forenoon and afternoon, being very large,
the Lord was with us in his power and wisdom,
and many things were opened to general satisfaction,
and a good time it was to Friends and others.

On the 6th, in the morning, we had also a good time, and in the afternoon,
being for the inspection of the affairs of Truth, things were well and peaceably managed,
and ended in comfort.

On the 7th was a meeting more select for the young people,
in which i had a very open and full time in the love of Truth,
and many of them were much reached.
The Lord gave us a good season of his love together, to his own praise,
and our mutual consolation, help and edification.

It being the time of the assizes, many of the higher rank were in town,
and one day came to my friend John Pike`'s, the young countess of Kildare,
and her maiden sister and three more of the gentry.
We had some free and open conversation together, in which this lady, and the rest,
commended the plain dress of our women, as the most decent and comely,
wishing it were in fashion among them.
I told her, "`That she, and the rest of her quality, standing in places of eminence,
were the fittest to begin it, especially since they saw a beauty in it;
and they would be sooner followed than those of lower degree.`"
To this she replied, "`If we should dress ourselves plain, people would gaze at us,
call us Quakers, and make us the subject of their discourse and town talk;
and we cannot bear to be made so particular.`"
I answered, "`The cause is so good, being that of truth and virtue,
if you will espouse it heartily upon its just foundation,
a few of`" you would put out of countenance, with a steady and fixed gravity,
abundance of the other side, who have no bottom but the vain customs of the times;
and you will find a satisfaction in it, an overbalance to all you can lose,
since the works of virtue and modesty carry in them an
immediate and perpetual reward to the worker.`"
This seemed not unpleasant, being said in an open freedom.
But then, alas! all was quenched at last by this; they all of them alleged,
"`That our own young women of any note, about London and Bristol, went as fine as they,
with the finest of silks and laced shoes; and when they went to Bath,
made as great a show as any.`"
Not knowing but some particulars might give too much occasion for this allegation,
it was a little quenching; but with some presence of mind, I replied,
"`I have been lately at London and Bristol, and also at the Bath,
and have not observed any such;
but at all these three places generally indifferent plain, and many of them,
even of the younger sort, very well on that account.
But those among us who take such liberties, go beside their profession,
and are no examples of virtue, but a dishonor and reproach to our profession,
and a daily exercise to us.
I hope you will not look at the worst, since, among us everywhere,
you may find better and more general examples of virtue and plainness.`"
This they did not deny, and so that part ended;
though we had much more free and pleasing conversation in the garden,
to which we adjourned from table,
and spent part of that afternoon together on like agreeable subjects;
there being the family, and but one friend more in the company.

On the 9th I went to Kinsale,
setting out in as great a shower of rain as most I have seen.
The meeting was considerably large, and mostly strangers;
for there is no settled meeting, only Friends have built a house,
on purpose to accommodate meetings when any stranger
inclines to have one for the sake of the people;
who often come on notice given.
Things opened beyond expectation, and Truth was over them, and a good time we had;
I being as easy, and as much satisfied after this meeting, as any I had yet been at.
That evening we returned to Cork.

On the 15th, being the fourth of the week, we went to Charleville,
and had a meeting there the next day;
which consisted mostly of strangers and Friends from Cork.
And though I had a fever, all was made very easy, and the Lord gave us a good meeting;
Truth, to his own praise, being over us and the people.
That afternoon, I went forward to Limerick, where we arrived in the evening;
but I found myself much spent, and very weary.
But one of my biles breaking, and my friend Thomas Pearce, where I lodged,
being an apothecary, providing suitable things, I was better in the morning,
and went to the meeting; which was large, the people expecting my coming,
and wanting to gaze at the dean`'s brother, it being a rarity to see such a one a Quaker;
and many fancies they had about me; but curiosity, not Truth, drawing them there,
I had not much comfort among them; though things were well, and without exception.

On the 19th, being the first-day of the week, both forenoon and afternoon,
the meeting was crowded, and Truth was over them.
But the greatest part having no want of Truth, but drawn by curiosity,
I had not so much satisfaction in them as in some other places,
where their coming had not the same inducement.

On the 24th, being the sixth of the week, I was at the meeting again;
which being mostly of Friends, and few strangers, was more comfortable than before;
and a good time the Lord gave us together; some of the strangers were also tendered.

I continued here till the next first-day, when the meeting was again crowded,
both forenoon and afternoon, and things opened fully on several points;
especially concerning freedom from sin in this life, and the necessity of it;
in which I urged the catechism of the Church of England,
and the great vows and promises therein mentioned.
That the composers thereof either believed the possibility of the attainment,
or they did not; if they did, then they taught a perfection higher than ever we had done,
that is, that men may live from the eighth day of their age,
their canon requiring baptism to be then administered, to the eightieth year,
if so long they live, and never sin.
For he that renounces the devil and all his works, the pomps and vanities of this world,
and all the sinful lusts of the flesh; keeps God`'s holy will, or law, and commandments,
and walks in the same all the days of his life; and, finally,
believes all the articles of the Christian faith; +++[+++such a one]
never sins, or errs, in faith or practice.
But if they did not believe the attainment, and yet enjoined and promised the thing,
then they committed great sin in so doing; for what is not of faith is sin.
But, alas! though despising the covenant of grace,
and have thus invented to themselves a covenant of works, they have not kept it, being,
by their own confession, miserable sinners,
leaving undone those things they ought to have done,
and doing those things they`" ought not;
and so are in the state of the fallen angels who were once in heaven,
but kept not their first station, but fell by transgression.
I directed them therefore to God`'s covenant of light,
and the grace which came by Jesus Christ; (for,
though they mention it in their catechism, yet they regard it not in practice,
but commonly assert that no man can be free from sin in this life,)
as the only means to attain that freedom and perform those vows;
which, though they made so very light of them, would be exacted to the utmost farthing,
in a day that was hastening over all nations,
when all must give an account before the great Judge of all the world,
and every one be rewarded according to his works.
All which they seemed to bear with patience.
But when I rejected purgatory as a satanic invention,
to elude the end of the coming of Christ, which was to destroy the works of the devil,
to finish sin, put an end to transgression, and bring in everlasting righteousness,
and render poor weak mortals secure in their sins,
in vain hopes of purification after death; some of the Papists went out of the meeting;
being obstinately bent on the slavery of sin and priestcraft to the end of the world;
which God will disappoint and destroy by the brightness of his coming and glory,
now advancing as the rising sun through the thick darkness;
and none shall be able to hinder or delay him.

On the 28th, being the third-day, I was there again; and the crowd being now well over,
and the meeting more select, it was very open to Friends,
and the Lord gave us a baptizing season of his love together;
and things ended to general satisfaction.

On the 29th,
having had a kind invitation by my brother and sister to their house at Bilboa,
I went there, accompanied by Joseph Phelps, George Pease and my cousin Charles Story,
one of the Prebends of Limerick.
This was an uncommon mixture, but no occasion of offense given or taken on any hand,
but all free and friendly.
My sister being a person of excellent natural temper, and very discreet,
and my brother also well pleased with our company, we were fully and kindly entertained.

The next day, after he had showed us his deerpark, and some of his fields,
with some other entertainments, the two Friends went back to Limerick,
but I stayed till the 1st of the seventh month, +++[+++1716]; and,
being the seventh-day morning, my brother and cousin went with me, about five miles,
where some Friends from Limerick met me.
That evening we went to John Ashton`'s, within five miles of Birr,
and had a large meeting next day, but not very open.
In the evening I went to Birr, and on the 3rd we had a meeting there;
where came many people, and some officers and soldiers.
They behaved civilly, and Truth was over all, and it was a good meeting.

On the 4th we set forwards, and that night lodged with Joshua Clibborn,
at the Mont of Greenogue; where we had a large meeting next day, but not very open.
There were many young people in it, not yet arrived at a sufficient sense of Truth;
and though under a profession of it, many of them have little desire after it,
but consider themselves safe; having had their education in the form,
they think all is well, and lack nothing; and so it is in many other places.

On the 7th, we had a small, but open and tender meeting at Oldcastle; and on the 9th,
being the first of the week, two large meetings at Coot-hill, which were filled,
especially in the afternoon, with many strangers,
there being great openness among the people thereaway; and things were very well.

On the 10th, in the morning, we went forward to Monaghan;
where there were three or four Friends; and got a meeting at the Bull inn,
in a large upper room.
To this meeting came a crowd of Papists, Episcopalians and some Presbyterians;
and some of the younger sort, especially Papists, were a little wanton and airy at first;
but Truth arising, they were generally tamed by the power and wisdom of it,
though they did not know what did it; and the meeting continued sober to the end,
though some two or three papists withdrew,
when I exposed the insignificancy of their doctrine of transubstantiation.
The meeting ended well, to the honor of our great Lord; of whom is the power and wisdom.

On the 12th, attended the meeting at Charlemount; but, though large,
it was not very open,
there being some contention among them about a marriage too near of blood;
where some sided one way, and some another;
there being scarcely anything so bad but that one or other will espouse it,
to their own hurt and exercise, and the hurt of others also; but in the main,
things were well.

On the 13th, I went to the meeting at Ballyhagen, which was pretty open; and on the 16th,
being the first of the week, I was at the meeting at Toberhead,
which was pretty large and tender, and Friends and others generally satisfied.
On the 18th, the great rains having raised the waters,
we had but a small meeting at Dunclaudy; but a very broken tender time it was,
and we were generally comforted.

On the 19th I had a meeting near James Moor`'s, the elder, which was small, being harvest,
and wet weather, and not so open as the last, and yet a good meeting.

On the 21st I had a meeting at the Ship inn, near the bridge over the Bund,
at Portlanone; where came many people and Friends from several places.
Many things were opened in the word of life to
general satisfaction and it was a good meeting.

On the 22nd I was at their six-weeks meeting at Grange;
where some strangers came and among others, one Moses Cleck,
who had received his education at Glasgow, in Scotland, was a good scholar,
and had commenced minister among the Presbyterians, to whom he had often preached,
and was in good repute among them.
But having fallen in with one of our meetings providentially, some years before,
he was reached by Truth, under the ministry of Hugh Hamilton,
and afterwards by John Salkeld,
though he still continued in his old way till the week before this, when he had,
before their presbytery, disclaimed his ministry and left them;
though they had taken great pains to reclaim him,
and offered him his choice of several parishes, or places, but in vain.
He owned himself convinced of Truth as professed by us in many things;
though not in all at that time.
We had a good meeting; but he took exceptions at some things I delivered,
there being some of the old imbibed notions still,
as a veil of darkness over his understanding.
After the meeting he discoursed with me upon them; and I satisfied him,
by explaining them fully, so that all ended well;
and he stayed with me there till the third-day following.

The 23rd, being the first of the week, I was at their meeting again; which was large,
and a good time, though some were disappointed,
having heard that this young man was come among us,
and was to preach in our meeting that day; but though they missed of that,
they were generally satisfied with what they heard.

On the 25th, I set forward to Antrim;
and the same expectations being among the people there also, many came to the meeting;
but some of the Presbyterian sect, being disappointed, went out before it ended,
though most stayed; and the Truth shining bright that day over them,
they were generally satisfied; and it was a good meeting to Friends also.

On the 26th I was at their mens`' meeting at Ballinderry, which was large and good;
and on the 27th, I had a meeting at Lisburn;
several towns people came in and were orderly,
and some affected with the testimony of Truth, which was large and free that day,
and a good time we had.
On the 28th I was at the meeting at Hillsborough, which was pretty large, and open.
On the 30th, being the first of the week, I was at the meeting at Lurgan,
which was very large in the forenoon, and also in the afternoon;
and it was a good meeting, Truth being over all, and many things largely opened,
to the glory of him who has the key of David; "`who opens and no man shuts,
and shuts and no man opens.`"

Being wearied and worn out with my journey and service,
and willing to take a little rest, especially where I found the most service,
I stayed here till the 3rd of the eighth month, and was at the meeting again,
which was an open and comfortable season, and several strangers were there, and affected.
