== Chapter 15

[.offset]
+++[+++After attending meetings at Nottingham, Mansfield, and Chesterfield, he says:]

On the 18th, being the first of the week, I went to a meeting at Sheffield,
which was large; but consisting for the most part of young people,
brought up in a form of Truth, and many of them unacquainted with the power of it,
and my concern therein being doctrinal, and out of their reach,
having been rather used to some musical noises affecting the passions,
than to any rational doctrine reaching the understanding,
it did not seem to have much effect upon several.
But there being a more grown people among them, they were well satisfied;
and it was in the main a good meeting, the Lord`'s good presence being over the same.

On the 20th I was at an appointed meeting at Highflats, which was large and pretty open,
there being several people of the neighborhood of various notions present,
who were generally satisfied.
On the 25th, being the first of the week, I was at the meeting at Leeds,
forenoon and afternoon, where I had a comfortable time with Friends;
and in the afternoon some people of the town coming in,
things were fully opened both to Friends and them.
On the 31st I went to Newcastle,
and on the 1st of the seventh month was at their meeting forenoon and afternoon;
it was pretty large and open, and the Lord refreshed us together in his goodness.
On the 5th was at the meeting at Emelton, which consisted of about eight persons;
and yet the Lord`'s ancient promise was, in some degree, made good in us,
"`That where two or three are gathered together in my`' name,
there am I in the midst of them;`" for we had a comfortable time in his good presence.

On the 8th, being the first-day of the week,
I was at Kelso meeting forenoon and afternoon.
There were a few pretty honest Friends,
and some persons of the better sort of the people in the forenoon,
and in the afternoon a larger number; and several things of importance opened,
and a good day the Lord gave us.
The Presbyterian church government, and the management of their priests, or ministers,
not sitting so easy on the shoulders of some of the people as they desired,
some of them about this time were looking out a better way,
and several were affected in the meeting.

The next day, accompanied by my old friend Samuel Robinson, I proceeded to Edinburgh,
and the day following had a meeting there with
about half a dozen Friends still remaining,
and some more sober persons that came in.
It was in the house of William Miller, junior, and was comfortable, though small,
the Lord being with us in some measure, to his own praise, who is only worthy.

But though that city has often been visited, and warned from the Lord by his servants,
yet there appears not any inclination in them towards Truth, or the way of it;
but the contrary, so far as I can see, or learn from those Friends conversant among them;
though some few sober people there are, who in due time may come forward.

On the 11th I crossed the Firth of Forth, and went that night to Kenway,
and the next day to the ferry at Montrose, but the winds being high,
could not pass over that night; and in the morning following I went to Tayck,
and next day to Ury, to my friend Robert Barclay`'s, where I stayed but that night,
though weary and feverish by the fatigue of my journey.
For the course of the meetings fell out so as that
Aberdeen was most convenient the day following;
and being the first of the week.
Robert Barclay and I went there, and though too late for the forenoon meeting,
were with them in the afternoon.
There was a large congregation of people,
and having travelled far in the good-will and love of God to see them,
a little after I entered the place I was much broken in
that love which reaches over sea and land,
and engages in the greatest fatigues and labors
for the good of souls for whom Christ died,
through a never-fading love, not of man, but of God also.
I had a good season in the meeting, and several were reached, and Truth was over all.

On the 17th I lodged at the widow Hall`'s, my old lodging when formerly in this country,
where I was very easy, and comfortably entertained;
and the effects of my journey remaining a little upon me,
she was very careful and helpful to me, being an honest Friend,
of an excellent natural temper, and prone to do good.
On the 18th I went to Kingswells, and had a meeting at Alexander Jaffery`'s,
where I lodged that night,
and the next day returned to Aberdeen to their weekday meeting, which was small,
but open; and the day following being their meeting for the affairs of the church,
I was there also, and a good open time the Lord was pleased to afford us together.

On the 22nd, being the first of the week, I was, in the forenoon,
at the meeting at Kilmuck, which was large,
and the truths of the gospel and kingdom of our dear Lord, were fully opened,
and we comforted together in his presence.
In the afternoon I was at a meeting at Inverary, where came people of several sorts,
and things were open and well; the next day returned to Aberdeen,
and the day following back to Ury with Robert Barclay,
who had given me his very acceptable company all this time.

Here I stayed till the 25th, and had a meeting with Friends there and of Stonehaven,
and so spent the week in the family, his mother being still living,
where I had all necessary refreshments and help, being then under a great cold,
which affected both my head and lungs.
But above all, the help of the Lord was near, and made all things easy and well.

On the 29th, being the first-day following,
I was at a six weeks meeting at Ury in the forenoon, which was large,
and the Lord was with us to our comfort and help; and in the afternoon, the same day,
I was at the meeting at Stonehaven, which was also a pretty large open meeting,
and in the evening returned to Ury.

On the 31st,
having some remaining inclination to see the Friends and people once more at Aberdeen,
I returned with Alexander Jaffrey to Kingswells,
and there I stayed till the fifth-day morning following,
being at two meetings in the mean time.

On the 3rd of the eighth month I went to the monthly meeting at Aberdeen,
where we had a comfortable time in the Lord`'s goodness;
and on the seventh-day following was at a meeting at the Old Town of Aberdeen,
and that afternoon returned to the widow Hall`'s at New Town with Andrew Jaffrey.

On the 6th I was again at the meeting at Aberdeen, forenoon and afternoon.
It was large,
and many things were opened of great importance concerning the law of the spirit,
and its strivings with the old world, and also with Israel;
as likewise with the Gentiles, and now with the nominal Christians; and all guilty,
by neglect and opposition to this spirit, and all means and additions proposed;
but such justified as believe and obey, to whom the same becomes a "`law of life,
and makes free from the law of sin and death.`"
This is that book and law written in the heart, sealed with seven seals,
which none in heaven, or in earth, or under the earth, can open or explain;
but the Lion of the tribe of Judah, the Lord Jesus Christ,
the mediator of the new covenant, and writer and giver of this law; whose law is light,
and his commandment as a lamp that burns,
and whose glowing warmth comforts all who read therein,
and are instructed of him who opens the seals.
The meeting was solid and large.
From the time of the rebellion,
in which some of the Episcopal priests had concerned themselves,
till the Act of Pardon by the king,
the Episcopal people there had generally come to our meetings,
rather than go to the Presbyterians, whom they looked upon as their enemies;
but since the said Act, had gone back again to their own preachers.
However,
some of the people had conceived such a liking to the way of Truth in the mean time,
that they continue to come at times, and may at length come further.
And their being at our meetings has had this good effect generally, that it removed,
in great measure, the old prejudices the people lay under,
by reason of the many lies and calumnies the
priests of all sorts had cast upon Truth and us.

On the 7th I went again to Kingswells, and stayed that night, Robert Barclay,
his wife and sister, being also there, and next day we went all to Ury,
where I stayed with them till the 12th, and was at their week-day meeting.

On the 14th I set forward towards England,
Robert Barclay and his son and servant being with me, and that night we lodged at Dundee.
The next day we passed through the Carse of Gowry, a very rich and pleasant country,
and lodged at the Bridge of Airn.
Next day, in our road, called to see sir Thomas Bruce Hope, at his house at Kinross,
near Loch-Leven.
He was religiously inclined, and entertained us very courteously.
His house is of wrought white free-stone, large, and well contrived; and near it,
in a little island in the Loch,
is yet standing the old square tower wherein Mary Queen of Scots,
afterwards beheaded by Elizabeth Queen of England, was some time prisoner.
That evening after sunset, we passed over the Firth of Forth at the Queen`'s Ferry,
where we lodged that night.

On the 17th we went all together to the house of Archibald Shaw,
a Friend near Hopeton House, belonging to the Earl of Hopeton,
where we stayed together that day; and our friend being gardener there,
we had the opportunity to see the gardens and house, which were very neat and convenient.

On the 18th we parted there with considerable reluctancy;
but as men are variously stated in this world by Providence,
who separates the nearest friends, our differing concerns obliging to it,
we were made easier to part by the same who first made
us acquainted in the time of our youth.
That night I went on to Falkirk.

On the 20th, being the first of the week, I was at their meeting.
In the forenoon it was smaller, they said, than for some time before, but quiet and open;
but in the afternoon a little larger,
and several important truths were set forth in a
good measure of the power and wisdom of Truth.
In the evening we had another meeting at George Swan`'s house,
which was as large as any of the other, and open, and the people generally satisfied.
I observed, that though the Presbyterians have the government there,
the people seem more moderate than formerly,
whether arising from the many divisions now on foot amongst themselves,
or considerations of the lenity of the government in England,
or that there is a secret work of God towards their redemption, or a general reformation,
I shall not determine, but had rather the latter were the Truth of the case.

On the 24th I went to Hamilton,
where there is now remaining but a very small number of Friends, poor and honest,
and but one or two of the old stock.
The next day was their monthly meeting, which was very small, but open and comfortable,
the Lord owning us together.

On the 26th I went to Cumberhead, to the house of my cousin Andrew Latimer,
a lonely place among the desolate mountains; and the next day,
being the first of the week, I was at the meeting,
and though there were but two or three persons besides the family,
yet the blessed promise was in some measure afresh fulfilled,
"`That where two or three are gathered together in my name,
there am I in the midst of them.`"

On the 28th I went forward for Cumberland, accompanied by my cousin Latimer.
He took me to the house of one John Williamson, his kinsman by marriage,
and a great Presbyterian; with whom falling into discourse, he, with all his might,
maintained sin term of life, as that sect commonly does,
in opposition to the plainest Scripture, and the end of the coming of Christ;
perversely alleging, that the apostle Paul,
at the time of writing his epistle to the Romans,
was in that miserable state of sin he speaks of in the seventh chapter.
I took much pains to inform him, that the apostle had, in the beginning of that epistle,
set forth the general state, both of Jew and Gentile; that all had sinned;
that Christ is the Savior of all; that he saves all who believe and obey, from sin,
not in it;
that the apostle brings his doctrine of freedom from sin in this life to a result,
or period, in the latter end of the sixth chapter,
and resumes the same doctrine in the beginning of the seventh, under another similitude,
that is, of a woman bound by the law to her husband so long as he lives,
but he being dead she is free to take another, etc.,
and then brings the same doctrine to a like conclusion in a few verses;
and the third time, in the same chapter, prosecuting still the same doctrine,
in the forepart of the eighth chapter, establishes this great point in these words,
"`The law of the Spirit of life in Christ Jesus
has`' made me free from the law of sin and death.`
Here it is evident,
that as a man cannot be in these two opposite states at the same time,
so the state of liberty from sin was not only the condition of the apostle himself,
who preached the doctrine, but of many of the saints at that time in the church,
to whom he preached it.
But after all this, and much more to the same effect,
this person still persisted in defense of sin,
as being most suitable to a depraved state, and the prejudice of his education.
However, his good nature and civility of temper,
so over-balanced the rancor commonly attending that principle,
which usually rather depraves than improves nature,
that he was conversant on other subjects,
and entertained us kindly in his house that night.

On the 29th we went to Wanlockhead, and that evening,
had a very comfortable time in the family of a widow,
the Lord`'s good presence being freely with us.
Next morning I went on my journey,
and the day following arrived at my father`'s house in Cumberland,
where I found him alive and well, being about eighty-seven years of age;
and there I stayed some days.

On the 3rd of the ninth month I went from my father`'s house at Justice-Town,
to the Border meeting, which was pretty large and open,
several of the ancient Friends being still alive.
That evening I was again at their meeting,
and lodged at Righead with my old friend and kinsman, Christopher Story,
and the next day returned to Justice-Town.

On the 6th I went again to their week-day meeting.
Calling to see justice Appleby and his wife, the daughter of counsellor Gilpin,
they both went to meeting,
he running the hazard of the Act of Parliament then in force against it.
We had a good meeting, and things opened well; and they pressing me earnestly,
I went with them to dinner,
and the justice went with me to Scaleby castle to see Richard Gilpin,
the counsellor`'s eldest son, a sober, goodnatured young man.
We went that night to Carlisle, and stayed their meeting on the first-day.
We had a good and comfortable time in the forenoon, but in the afternoon, Satan,
who ever envies the people of God,
gave us some disturbance by his unhappy instruments and servants,
Job Pearson and Isaac his brother; who, slipping out of the jail,
which was kept by one not well affected to us, came into the meeting,
and in the time of silence, used many unsavory, scurrilous, and provoking expressions;
but none gave them a word again, till after some time,
Dr. Isaac Huntington giving the governor of the city a private hint of their behavior,
he sent and look them away.
Some time after, I had an opportunity to speak to the people,
and to lay open the kingdom of Christ, the kingdoms of men,
and the kingdom of antichrist; their different natures, jurisdictions, and ends;
the divine and spiritual nature of the first,
with the subjection of the members thereof in
this life in temporal affairs to the second;
how far they ought, and where they ought not, to obey:
the great and good ends of the second, for the suppression of evil,
support and protection of the just and innocent,
against the violence and oppression of the unruly and ungodly;
and the wicked and unrighteous power of the last,
gained by the subtlety of Satan in ungodly men, under pretense of the Christian religion,
destroying it in all ages; having deceived the temporal powers,
and made them the instruments of the greatest cruelty against
the innocent children and subjects of the kingdom of Christ;
till the Lord, in mercy, is in these latter days beginning to arise,
discovering antichrist, undeceiving the powers of the earth,
and directing them to a more just and equal application of their authority,
for the encouragement of the well-doer, and correction of the ungodly.

On the 12th I went to John Newton`'s, in Alston-Moor, and on the 14th had a meeting there,
which was very open and broken, there being several new-convinced Friends there,
among whom was Thomas Erskine, lately a Baptist teacher, a very hopeful young man,
and of good repute among the people.
On the 15th, in the evening, we had a meeting at Jacob Moor`'s at Welgill,
about two miles further up the Dale, and it was far larger than the former,
many strangers being there, and very sedate and sober,
and things were well and satisfactory.
On the 17th, being the first of the week, I was again at John Newton`'s,
where the meeting was very open and broken,
the Lord`'s good presence being with us to our general comfort and satisfaction.

On the 18th I had a meeting at East-Allandale;
and the same evening had another about three miles off, at Sparkes,
where came a considerable number both of Friends and others.
We had good meetings there also;
for at that time there was considerable openness in the people towards Truth.

On the 19th we went back to Askerton,
and the day following I fell in with Solport meeting, which, though small,
having had no notice, was comfortable, the blessed Truth being over all.
But my distemper returning, through cold and hard riding to reach the meeting,
I was much pained at times in it, and though carefully provided for,
was very ill most of that night;
but towards morning the Lord encouraged me with a little help,
which proved very effectual; it was by the operation of his power in my heart,
by which all the pains for that time were overcome and quieted,
and then I had ease and rest all that day.
I having also a great cold, and my lungs a little affected,
I stayed there till the second-day following,
and was at the same meeting again on the 24th, being the first of the week,
which was much larger, and very open;
and some strangers being touched with the virtue of Truth,
spoke well of the meeting afterwards.

On the 25th, going down to my father`'s house again, I stayed there till the 28th,
and that evening went to Carlisle, and was at a six weeks meeting there,
which was pretty large, and very open,
being composed of the members of all the particular meetings of the monthly meeting.
The same afternoon I was also at a select meeting of ministers and elders,
for inquiry after the prosperity of Truth in those precincts.

On the 1st of the tenth month I was again at the meeting at Carlisle,
which was fresh and open, both forenoon and afternoon;
and being a little out of order in my health, I stayed the fourth-day meeting following,
which was a tender good meeting.
In the mean time I visited several of my old acquaintance and fellow citizens,
among whom was the mayor and some of the aldermen, and old counsellor Aglionby,
the recorder, who had often showed kindness to Friends on occasion;
especially in that very abusive case of the Pearsons.

On the fifth-day following I was at the meeting at Moorhouse, which was the larger,
by reason of a marriage, and a pretty open time the Lord gave us;
for many were well satisfied, amongst whom were some strangers.
That evening I returned to Carlisle, and the day following I went to their meeting,
and though pretty early, yet John Robinson was got there,
and before the meeting was a quarter part gathered,
as soon as he perceived that Truth began to move in the meeting,
he began to show his malice against it and Friends, and against me in particular,
supposing, that I as a stranger, might have something to say;
and so directed abundance of rude, false, railing and impertinent accusations to me,
both against myself and Friends.
But I answered not a word; nor did this at all provoke me, though it was very abusive,
Truth being over my spirit.
I stood up and spoke to the meeting, taking no notice at all of him,
and things opening suitably and well, in the wisdom and authority of Truth,
we had a good and open meeting, the Lord being with us, to John Robinson`'s great torment;
for in time of prayer his envy raged so,
that he read some passage out of Robert Barclay`'s Apology all the time,
which he imagined was for him and his few accomplices against Friends and Truth.
But none regarded him; and soon after prayer the meeting ended in comfort,
over the head of this opposing apostate.

The day following I had a meeting appointed at Bolton, where this Robinson came again,
and after some time stood up to preach to us, beginning with the royal law,
"`That all should do as they would be done by.`"
But before he proceeded any further, a Friend who knew his circumstances in the world,
bid him sit down, for we could not receive that doctrine, or any other from him,
who was not in the thing, having defrauded many in the country,
and detained from them what was their own,
whereas himself would not lack what was his from such as owed him;
and so stopped his preaching.
Then he fell to railing, reproaching, reviling, and falsely accusing Friends.
I desired him to sit down and be quiet, he railing at me first,
and pressing by the other Friend to come towards me,
as if he would have offered violence, being in a rage.
I said some more words to him, and he was still worse.
Then I told him, "`You are distracted,
and fitter for a house of correction than any civil, much less Christian society.`"
He still raged more and more; so I said nothing further to him,
knowing that spirit is fed by answering, and destroyed by neglect and silence.
After a little silence, I stood up and spoke to the meeting over him,
he railing in the mean time, and making all the noise he could to hinder;
but he often running himself out of breath, and my voice being raised over him,
many things opened to the states of persons and things: and Truth was over all,
to our general satisfaction, and his grief.

On the 10th I went to Holm, and next day was at their meeting,
which was indifferently large and very open; for, as the Lord ordered it,
none of the troublers were there, this meeting being frequently, above many others,
the stage of their strange and brutish behavior.
The meeting was much tendered, and many things opened concerning the principle of Truth,
and that evil spirit which had opposed it from the days of the apostles,
both in the old heathen emperors and people, and most and worst of all,
by such as both professed and preached it in words--of
which sort were these Pearsons and Robinsons,
and their unhappy accomplices.
The meeting ended under a sense of the love and goodness of God.
That night I stayed at Thomas Wilkinson`'s,
where some marks of the violence of these men were still remaining on the house;
for as this Friend had much opposed them from the beginning,
so their envy and rage were the greater and more particular against him; neither himself,
family, nor house escaping the effects of their rage.

On the 12th he went with me to Allanby,
where the Lord gave us a tender season with Friends, being their meeting-day.
Many things were opened confirming the weak among them,
and the meeting ended in peace and comfort in our dear Lord Jesus,
whose blessed power was over all.

On the 13th being their meeting-day at Great Broughton, I was with them,
and the Lord exalted his own holy name in the midst of us, to his own praise,
who alone is worthy.
Not having been at this meeting on a first-day for many years,
and considering it was the place where I first knew Friends to be the people of God,
I stayed till the 15th; which being the first of the week,
I was at the meeting in the forenoon.
It was open and well, but not many strangers present.
Desiring to see as many of the people as I could,
an evening meeting was appointed at Mary Bowman`'s, where I lodged,
which was the largest they had seen there, and things opened to general satisfaction.

On the 16th I went to Whitehaven, and desiring to have a meeting in town next day,
we could not procure a convenient place,
and so appointed one at our friend John Nicholson`'s, about a mile off,
to which came justice Gilpin`'s wife, eldest son, and another, and two daughters,
John Gilpin his brother, and many others of the town.
James Dickinson met me there, and we had a very good opportunity among them;
the power and presence of the Lord was with us, and the people were generally satisfied,
and several tendered.

Next day I went to West-side, or Crossfield meeting, which was a very good open meeting,
and many were tendered.
That evening I went back to John Nicholson`'s,
inclining to see and converse with my old friends and
acquaintance at Whitehaven a little more;
and accordingly went there next morning,
and that day dined with my old and hearty friend John Gilpin and his family.
I lodged there also that night, and tarried all the day following in town.

On the 22nd, being the first of the week, I was at Pardsay-Crag meeting,
which was very large and open, and the Lord gave us a good season together,
being mostly Friends.
That night I went to Meser-Gate,
where we had an evening meeting at the widow Fawcet`'s house, which was heavy at first,
but ended pretty well.

The 24th was their monthly meeting at Pardsay-Crag, and we went there,
where was also a select meeting of ministers and elders,
for inspecting and promoting the affairs and concerns of truth;
and the Lord being with us,
gave us a good and open season of his love and counsel together,
to his own glory and our help.
That evening, after the meeting, I went to Cockermouth,
and on the 25th had a meeting there, being that they call Christmas day,
and the Lord was with us to our comfort, being for the most part Friends.

On the 25th, in the evening, I returned to Cockermouth,
and the next day in the forenoon was at their meeting, which was very large,
mostly of Friends from various parts of the country; and an open time we had.
But not many of the town`'s people being there,
we appointed another meeting to begin at five in the evening,
which was much crowded by the town`'s people; and things opened largely,
and the Lord`'s power and Truth were over all,
to the glory of him who alone is able and worthy forever.
That night I stayed at Cockermouth.

On the 31st I was at Isell meeting, which was a small but comfortable meeting;
and that evening had another appointed at John Scot`'s house, for the sake of the people,
which was pretty open and well,
the people sitting still long after the meeting was ended.

On the 1st of the eleventh month I went to Keswick,
and called together the few Friends in town, who, with those that went with me,
made up a little meeting, which was pretty comfortable.
That evening going forward to Mossdale, where a meeting was appointed next day,
and the frost very hard, add snow blown in deep wreaths in many places,
we were in great danger, and much fatigued before we got through,
and often almost out of breath with wrestling through the snow.
For our horses could not keep their feet, but often stumbled in it;
so that we went mostly on foot, which, with our boots and heavy riding clothes,
made it very exhausting.
But God`'s good providence carried us through these dangers,
as through many more I have met with on such occasions in times past; and that evening,
a little within night, we arrived at George Mark`'s house.

On the 2nd of eleventh month the meeting at Mossdale was held according to appointment,
and being mostly of Friends,
the Lord gave us a comfortable season of his goodness together.
On the 5th went to the meeting at Coldbeck,
and being the first-day of the week it was large and open, and Truth over all.
On the 6th I went to Penrith, and the day following, in the evening, had a meeting there,
which was large, and a good open time.

On the 9th I went towards Newcastle, accompanied by John Benson and his son James;
but could not pass over the mountains for the snow, but by the common road from Brampton;
and on the 12th, being the first of the week,
I was at their meeting both forenoon and afternoon.
It was large and open, several strangers being there,
and things passed to general satisfaction.
On the 16th I was there again, the meeting being mostly of Friends;
and the Lord was with us in his love and divine virtue;
by which many were tendered and comforted, to his own praise,
and our mutual help and edification.

On the 18th I went to North-Shields, and the next day was at their meeting,
which was pretty large both forenoon and afternoon, and things opened well.
But though the doctrines of Truth appeared pretty clear in wisdom,
yet not so much life accompanied us as at Newcastle, but rather laid more under,
as in some way suffering more there from some hidden cause;
but in the main things were to general satisfaction.

On the 20th I went to Sunderland, and the day after had a meeting there,
which was pretty large, and very open and comfortable.
But I found myself under great inconvenience, by reason of cold I had taken before;
in which I had good help from my kind friends Lancelot Wardale and his wife,
where I lodged, who were very courteous, as were also other Friends there.

On the 22nd, James Dickinson coming up, there was a meeting appointed there for him,
where I was also; and having no public concern therein,
I was much renewed in my strength both of body and mind.
For though I had been ill all night, and had little rest,
by reason both of a great cough and pain,
and so much indisposed in the morning after I arose that I
could not go to meeting till about half an hour after the time;
yet within a few minutes after I was there,
I found my heart bound up with the girdle of Truth,
so that the healing virtue thereof overpowered every other power in me,
both of body and mind; and I had no present sense at all of any ailing.

On the 23 rd we went together to Shotton meeting, which was pretty large,
and indifferently well; but my exercise therein was a little heavy,
yet a good meeting in the main.
That night we went together about three miles further towards Durham,
and the next day had a meeting there, and a good open time the Lord gave us together.

On the 26th, being the first-day of the week, I was at the meeting at Bishop-Auckland,
which was pretty large and open as to doctrine,
and some reaches of Truth now and then stirring among us,
but some secret suffering of the seed still there, though in the main a good meeting.
That evening I went home with John Walton, an honest Friend,
well skilled in spiritual and natural things.
His wife, whose maiden name was Helen Fairlow, served the Countess of Carlisle,
as her gentlewoman, at the time of her convincement; in which, by the grace of God,
I also had been in some degree instrumental before I went to America.

On the 28th I went to an appointed meeting at Raby, which was large, and very open,
and some strangers well affected therein; and on the 29th to Cockerton,
and the day following had a large open meeting at Darlington.
There being pretty many strangers, things opened clear and free,
and the power and wisdom of Truth was over all,
to the praise of the great Master Workman, the Lord himself, who works all,
in all of his people and servants;
many of whom were much broken and comforted in that meeting.

On the 31st I went to Stockton, about nine miles, and had an appointed meeting,
which was pretty large, and very open; and many being broken and tendered,
were also edified and comforted together in the love of our heavenly Father,
which plentifully flowed among us, to his glory.
Amen.

On the 2nd of the 12th month I went to Yarm meeting, which was not large,
but open and living,
the life-giving presence of the Lord being graciously afforded to us.

On the 4th of the twelfth month I was at their meeting at Ayton,
which was open and comfortable, and that evening called to see old Maurice Lisle,
then priest of Kildale, to which I had several inducements.
1st; His eldest son, of the same name, having come over into Pennsylvania,
been my clerk for about four years, had been convinced in the time,
and was now among Friends there.
2ndly; This Maurice, the father,
had all along been civil and tender to Friends in his way;
not suing or imprisoning any for his parish wages,
as has been too common in others of his profession, and still is, in this nation.
He and his family kindly received my visit, and we parted in pretty open friendship.

On the 5th I was at Gisborough, where the meeting was not large,
but Truth was exalted over all, and we were comforted together;
and several of the town`'s people coming in, were quiet, and some of them pretty tender.

Next day I was at the meeting at Moorsham, which was small and heavy;
yet the Lord owned us in some measure by his life and presence,
which were not afar off several there; and it ended well.
That night I lodged near the place, at the house of John Stonehouse,
who went with me next day to Roxby meeting, which was small and heavy in the beginning;
but the Lord in mercy visited us together, and we had a very comfortable time.
That night I stayed there, at the widow Anne Furbank`'s.

On the 8th I went to Whitby, and the day following was at their meeting in the forenoon,
which is large, there being a fine body of Friends in that place,
and was open and comfortable, and I had several good openings among them,
and the testimony of Truth had a free passage.
The meeting was also very comfortable in the afternoon.

They have two week-day meetings, the one on the fourth, the other on the sixth;
and being also at them, I found them open and comfortable;
and staying till the first-day following, being the 16th of the month,
the meeting in the forenoon was large and open, but not many strangers.
Being desirous to see the people,
the afternoon meeting was put off till five in the evening, and notice given,
which fully answered the intent;
for there was such a crowd as Friends had never seen in that place,
and many things opened to them in the wisdom and authority of Truth,
to general satisfaction.
I do not see but at this day,
in all places where Friends are diligent to draw people to meetings,
the Truth appears most freely, and things are most lively;
but where Friends themselves are set down contented, without any such concern,
things are cold and heavy to themselves also,
and little appearance of Truth but in reproof and dislike.

On the 18th, being the third of the week, I went forward to a meeting at Staintondale,
which was of itself a small meeting, but augmented by Friends who went from Whitby,
and was open and comfortable; and that evening I went to Scarborough,
and lodged with Peter Garbut, an ancient Friend there.
They have also at Scarborough two week-day meetings, namely: on the fourth and sixth.
I was at them both; but the first was a little shut up, especially in the beginning,
and the second more open.
On the first-day forenoon the meeting consisted for the most part of Friends,
and generally young people, and was indifferently open;
but that in the evening was very large, and crowded with people of several sorts.
Truth came over them with good authority,
many things suitable being clearly opened among them,
and the meeting ended in a very solid manner, to general comfort and edification.

On the 24th I went to Burlington, and the next day had a meeting there,
which was very large; for the Friends having taken care to invite the people,
they came fully, and the Lord was with us, and honored his own name among them,
for his blessed Truth was over, all, and Friends were generally satisfied.
The next day I was at a meeting at Hornsey, which is very small;
but some from Burlington and other places made it up pretty well,
and it was open and comfortable.

On the 27th I was at a meeting at Oustwick,
where came some Friends from several places about;
but Utile notice being given to the people, the meeting was not large, or very open;
and I was also heavy in my spirit some time after this meeting,
but knew no reason for it.

I lodged that night at Isaac Storr`'s, and on the 26th he went with me to Hull,
and that evening we had a meeting there.
They are but few of themselves, but notice being given to some of the people,
the meeting was pretty full, and things opened largely,
both for the encouragement of the faithful, and rebuke of the backsliders;
especially the unfaithful concerning tithes, as a main branch of the testimony of Truth,
in our day, against antichrist and his ministers; for which, I heard afterward,
there was too much reason in these parts.
On the 2nd day of the first month, 1717, being the first of the week, I went to Beverly,
where we had a large meeting of Friends and others, and very open,
many being reached in it by the power of Truth.

On the 4th day I went to an appointed meeting at North-Cave,
where came people of several sects, as Papists, Episcopalians, Presbyterians, etc.,
and there being a burial at the same place, things opened largely,
and to general satisfaction, and the Lord gave us a good and comfortable time.
After the meeting I went that evening home with Nathaniel Wells, to Cotness, where,
on the 6th, I had a meeting, not large, nor much in the flowing of life,
but some things of great importance were moving:
as the first establishment of the worship of God in spirit,
before there was any church in Asia, or the gospel at all preached at Rome;
the rise of antichrist in the apostles`' days, his progress in the same sort of ministers,
his height in the papacy, and approaching downfall in the same,
and in all others the like, in all lands, and in all forms; the Truth,
and its testimony and followers, persecuted in this land from the beginning;
the great reward and triumph of its faithful witnesses,
and the mean and base spirits of those who were visited, and were unfaithful;
and their reward of infamy and death: and in the main it was a good meeting.

The first of the week I went to Rawcliff, where the meeting was large and open,
there being Friends from several meetings about, and some strangers;
and the Lord gave us an open and free time.
That evening we had another meeting there, which is usual;
but no notice being given to the people of the town, we had but a heavy time;
as I ever observe in my travels,
where the professors of Truth are set down by themselves,
without a due concern for others, things are but heavy and dead: and yet,
after a considerable time in silence, the Lord condescended to comfort us together,
and the little meeting ended well.

On the 11th I was at an appointed meeting at Selby,
where came some few of the town`'s people, and Friends from some other parts,
and we had a pretty open time and good meeting.
On the 12th I went to Pontefract, where we had a small meeting, but indifferently open,
there being few but Friends, and some of them young,
and not much acquainted with the work of Truth, as is the case in most other places.
But being preserved pretty generally from the grosser evils of the world,
and keeping orderly,
there is good ground of hope the Lord will effectually reach them in his own time; as,
blessed be his name,
he has already blessed many of them with the knowledge of his way and Truth,
to the comfort of their own souls, and all that are concerned with them.
I stayed after the meeting at Robert Clarkson`'s, an ancient Friend of the old stock,
and faithful.

On the 13th I was at an appointed meeting at Wakefield, which was but small;
but there came in some sober people of the town, and things were very open to them.
But a parcel of giggling, rude persons coming also,
we had some disturbance by their unchristian and uncivil behavior; and yet,
for the sake of the sober and well-inclined, things opened clear and full,
and Truth being in dominion over all,
the rude company could not live under the cutting reproofs of it, but retired,
and then we had a good season.
I found they were a parcel of scholars belonging to a school in town,
with some their like abettors, which gives me occasion to observe,
that we have but a melancholy prospect, to see the youth of the age so corrupted,
especially at the colleges and schools in the three kingdoms, generally speaking,
where young men have the rudiments of that learning and education which
should qualify them for the services of their own families and country.
From here arise great mischiefs in church, in state, in the offices and officers, civil,
military and ecclesiastical; in pride, in covetousness, in emulation, strife and envy;
in lust of dominion, preeminence and rule, to the great danger of utter ruin;
which surely will come, if they continue to neglect so great salvation as the Lord,
in infinite mercy, yet offers to them;
in sending forth his light and truth so freely and plentifully among them;
in which he will be clear in that day,
when their sins will make their deep humiliation so necessary to them.

The 14th was the week-day meeting at Leeds, which was pretty open and well.
On the 18th I went to York to the quarterly meeting, which was large,
and a very open time the Lord gave us,
and things opened clearly to the state of Friends and people.
On the 27th I went to Gildersham to a meeting, where came several of the neighborhood,
some Antinomians, Presbyterians, Episcopalians, etc.;
and after a considerable time in silence, the Lord gave us a good season,
and opened many things to the state and understanding of the people.

On the 30th, being the first of the week, I was at the meeting at Kendal in the forenoon,
where there were few but Friends, and pretty open,
but not so full as I could have desired.
But the afternoon meeting, at my request, being put off till the fourth hour,
and notice given to the people, there came a great company,
and the Lord opened many things for their convincement,
in the demonstration of his wisdom and power; and many were tendered,
and generally very sober.
It was a large and good meeting, to the honor of the Lord, who alone can make it so.

On the 31st, in the afternoon, began the yearly meeting;
the first meeting being for ministering Friends, several being there from Cumberland,
Westmoreland, Northumberland, Durham, Lancashire, Yorkshire, and Cheshire.
Many things were opened among the brethren to general edification and comfort.
In the mean time was a meeting of elders apart,
to confer about such affairs of Truth as came under their proper cognizance:
and before the meeting of ministers ended,
the elders desiring admittance to sit with them, as is usual,
they were readily received accordingly; and then we had some time together,
and all concluded to satisfaction.
The next morning about eight, being the 1st of the second month,
we had the public meeting for worship, which was very large and open,
consisting mostly of young and middle-aged Friends, but not of many other people,
considering the occasion.

On the 2nd, in the forenoon, we had a meeting of conference,
by ministers and elders from all parts, to confer about the affairs of Truth in general,
and how it prospered, and what was yet to be done for the honor of God,
and spreading of the blessed Truth still more and more on earth,
which is the whole end of these meetings;
in which also we had peace and comfort in the Lord, and one in another in him.
That afternoon we had a parting meeting, which was large and comfortable.
So all ended to our mutual satisfaction,
and the meeting was then adjourned to the 14th of the second month, the year following,
to be held then at Liverpool in Lancashire.

On the 5th there happening to be a marriage in that town,
the woman a grand-daughter of Robert Barrow, who, with others,
suffered so much at Florida, etc., I had an inclination to be at it,
as I was also requested to be by several Friends;
and a marriage among the Quakers being a novelty there,
and the public meetings having stirred up the people,
more of them came than to the other meetings:
and the Lord was pleased to look upon us in his goodness;
for his blessed Truth was over all to his own glory, and the comfort of many.
The public exercise falling to my share,
the Lord opened matters of importance relating to marriage, and some other things,
and the meeting ended well, Benjamin Bangs concluding it in prayer.

On the 4th I was at the quarterly meeting at Lancaster,
where also the Lord appeared in love, and we had a good season thereof together.

On the 6th, being the first of the week, I was at Penketh,
where also came Benjamin Bangs, and we had a large open meeting.
Dining at Gilbert Thompson`'s, we went afterwards to Warrington,
where we had a large evening meeting, mostly of the town`'s people of several persuasions,
who were generally sober and pleased; for the Lord was with us, and did us good together.

On the 8th we had a pretty large meeting at Frenchay, which,
though a little heavy for a time, the sun at last broke through and dispersed the clouds;
and we had a growing season in the end,
to the praise of the great Director of all our
seasons of divine love and heavenly enjoyment.
On the 9th had a meeting at Newton, which was also large and clouded at the beginning,
but ended well, and to general satisfaction, there being pretty many people;
and on the 10th Benjamin Bangs returned home, and I went to Namptwich,
where a meeting had been appointed.
The sheriff of the county living there, let us have an empty house to meet in;
for we have no meeting-house there, being but few Friends in those parts.
It was a large meeting, and Friends came from several places, and many people,
so that all the rooms were crowded;
and though many of them came in with light and fleering countenances,
yet before the meeting was ended the visitation of the Lord being to them,
several were tendered, and generally sober and grave, and the solid Truth was over them:
it was a good open meeting.

On the 11th I went to Shrewsbury,
where meeting with Thomas Harvey and Charles Lloyd from Wales,
met to consult about a place for the yearly meeting,
their company made some amends for the fatigue of that day.
That evening I went home with Thomas Harvey, where I stayed till the first-day morning,
and then went to the meeting at Shrewsbury, which was not large in the forenoon,
nor very open, though some other strangers were there.

The afternoon meeting was as large as the house could well hold, and a pretty good time;
but there being no ministering Friend belonging to the meeting except one,
who has but few words, things looked a little strange to some.
Having a kind invitation after the meeting by my friend John Fowler, to lodge with him,
I accepted of it,
and was kindly entertained at his house all the time of the yearly meeting,
which was held once or twice a day till the sixth-day following.

There were several ministering Friends present; as Aaron Atkinson, from Leeds,
John Fallowfield, from Hertford, Daniel Bell, from London, Gilbert Thompson,
from Penketh, etc.
And such meetings being new there, a multitude of people of all ranks flocked there;
and the Lord was evidently with us,
and opened many excellent truths of the gospel to general satisfaction,
and Truth was over all; the meeting being preserved in good decorum from first to last.
But having occasion to speak of the necessity of freedom from sin in this life,
I cited the catechism of the church of England among other things, to prove it,
for it is held there that people may live all the days of their lives, and never sin,
and some one had misrepresented what I said to a priest; who, after the meeting,
sent to speak with John Fallowfield and Daniel Bell about it, not knowing my name;
and they had some discourse about it,
his chief objection lying against our naming their catechism, and said,
we ought to confine ourselves within our own communion,
and say nothing that might have any tendency to draw any of another communion to our way:
but finding him unreasonable, they soon came over him, and he was running away in a rage,
but they stayed him till that was over.
This priest had met with a young man and woman, who were under convincement,
and had been much reached in some of the meetings,
and told them the Quakers were in the way of damnation,
and therefore cautioned them in private, to fly from us as from a serpent or the plague;
which they discovering to John and Daniel, they treated him accordingly, and exposed him.

On the 18th, being the last day of the meeting, and our parting time,
the Lord being still with us, in the forenoon I had a large open time;
and though I was very weak, and ill of a great cold I had taken a week before,
yet the Lord gave me strength and utterance,
so that many things were opened to general satisfaction.
One thing happened somewhat remarkable in it:
for as I was concerned to speak of the crucifixion of Christ,
and mentioning the large incision in his side by the spear,
from which issued blood and water, which clearly evinced he was wounded to the heart,
through the pericardium which held that water; and that this being for the sins of men,
without which that would not have been put upon him,
I myself was so much affected with it, as also the auditory, that I could not go on;
but being much broken,
stopped and stood still till my spirit was a
little unburdened by an efflux of many tears,
and the whole auditory was bowed, and generally broken and melted,
so that many confessed the Truth, and that they had never known the like.
After some time, I went on further with the matter, which opened so fully as, I believe,
nothing stood in the way.
before all was ended.
As this was the Lord`'s work, and his hand plainly in it,
for at first I was very weak to the sight of all, by reason of the cold and hoarseness,
but my voice grew stronger than common, and clear,
so to him only be the glory and thanks now and forever.
Amen.
The meeting ended in prayer, and to general comfort;
and I have not know`'n many meetings hold so many days, and so well throughout,
which was also the observation of many more.
And so Friends returned to their various places with great satisfaction,
and the people were generally humbled, and spoke well of the Truth;
but some were angry that there was no power to suppress us, though they were very few,
partly of High Church, and partly Presbyterians, who would soon be at their old work,
if they had but power.

On the 24th, being the fifth of the week, I was at the meeting at Wolverhampton,
which was small, because I was not free, as circumstanced,
that any notice should be given on my account.

On the 26th I went to Birmingham, and lodged at Richard Park`'s,
and the next day was at their meeting forenoon and afternoon.
The first was not large, but indifferently open, but the latter was larger and more open.

On the 29th I went to Stourbridge, where we had a large open meeting,
many of the chief of the town being there;
and the Lord favored us with his wisdom and pow-er,
which was apparent there to the reaching of several.

On the 30th I went from there to Bromsgrove,
and on the 1st of the third month to Worcester,
and next day was at their week-day meeting, which consisted mostly of Friends:
and the Lord gave us an open time together, affording to us his comfortable presence.
Tarrying here till the first-day, I was again at their meeting, which, in the forenoon,
was well filled with Friends, pretty open, and a good time;
but in the afternoon was much larger, and a great many people there,
and things were very open and clear, and Friends and the people generally satisfied;
but I found my natural strength much spent, and my spirits exhausted.

On the 5th I went to Tewksbury, and the day after had a meeting there,
which was pretty large, and many reached by the power of Truth, both Friends and others,
and well satisfied; the blessed presence of the Lord being over all in the meeting.
There were also present several scholars of one
who taught academical learning in the place,
who were very sober and solid in their behavior.

On the 7th I went to the city of Gloucester, where there is a small meeting,
and not many strangers came in; it was heavy and drowsy,
but after a considerable time in silence,
the Truth working through the cloud and power of darkness,
I had a pretty open time among them, and afterwards learned the reason of the hardness;
for there were several unruly and shattered persons among them.

On the 10th I reached Bristol, and was at the yearly meeting, which was large and open;
and among many others, for there was a large appearance of ministering Friends,
I had some concern in the meeting, regarding the sins of the old world,
and God`'s long suffering towards them for so many hundred years,
and their destruction for sin at last; the re-peopling of the world,
and their degeneracy also; the dispensation of God to the Jews, their apostasy,
and many sins and provocations for many ages, and their destruction also.
Lastly, the visitation of God, his offers of salvation "`by Christ,
and his light and grace unto all nations; the rise of antichrist in the apostles`' days,
not among the Jews or Gentiles, but among the Christians; who they were; their progress,
height and insults over mankind, subjecting all other powers to themselves,
perverting the good ends of civil power,
and turning the edge of justice backward against the innocent, and indulging the ungodly;
the approach of the final downfall and ruin of that power in all nations,
under a profession of the Christian religion,
longer than either in the old world or the Jews; and cannot escape condign punishment,
for the ocean of blood she has shed,
having the same righteous and Almighty Judge to answer before,
and the word of his mouth already gone forth against her,
in many prophecies of her final desolation:
and the tranquillity of the nations and people after that, to the end of time,
under the reign of the Lord Jesus, by his Holy Spirit.

On the 18th I went out of the city to a place about five miles off, called Parsbury,
where the priest of the place had been preaching against the king and government,
and taken to task about it.
The sober people were weary of him; and having notice of it, I found freedom to go there,
where also came many Friends from Bristol, and places adjacent.
We were about five hundred together, in a large barn;
and the Lord appeared in his love and wisdom, and opened many things instrumentally,
to general satisfaction; and that evening we returned to Bristol.

On the 19th I went to Nailsworth again,
and was at the quarterly meeting for Gloucester county, held there.
Being a little wearied and spent, I stayed the fifth-day`'s meeting,
and on the 25th was at the meeting at Reading.
In the forenoon it was not large, nor very open, but rather heavy;
nor found I anything to say amongst them, only a little in prayer; but in the afternoon,
on occasion of a burial, the meeting was large, and much more open,
where I had some concern to expose the kingdom of antichrist, in some degree,
and say something also about the resurrection of the dead;
and things were pretty well in the main.
That evening I went with Hannah Penn and family to Ruscomb,
where I found her husband still weak, but very open to receive me,
which he expressed several ways.
There I stayed till third-day, and returned to Reading to their monthly meeting,
which being select and quiet, we had a tender time together in waiting upon the Lord;
where I also had something in testimony, and afterwards we proceeded to the business:
and so all ended in peace.
That evening I returned to Ruscomb, where I stayed till the 29th,
and then went to a monthly meeting at Winkheld, held at John Finch`'s, which,
though small, was very open.

On the 30th we had a small meeting at Stains,
and the day following being the seventh of the week,
I went to London to the yearly meeting, which was large;
but some debate happening therein concerning the manner
of dealing with persons accused of public slander,
occasioned by some satirical libels printed the year before,
the meeting was somewhat disturbed on that occasion; but yet the Lord was near,
and things ended pretty well and comfortable.

On the 14th of the fifth month I went to Chelmsford, and next day to Colchester;
and being the first of the week, and the day before the yearly meeting of that place,
we had a large appearance of Friends and others, and an open time.
The yearly meeting which ensued was large, and the Lord`'s good presence was there,
and many weighty things were, through his grace,
opened in the meeting to general edification and comfort.

On the 19th I returned to Coggeshall, being their meeting-day,
where the Lord`'s presence was with us, and a good time we had.
That night I lodged with John Osgood, a mile from there,
and the day following had a meeting appointed at Braintree,
where came Friends from several parts adjacent, and things were well.

On the 21st I went back to Chelmsford, aVid was at their meeting the day following,
which was large, and pretty open in the main.
Friends from various parts being there.
In the evening, about the sixth hour, I had another meeting,
more particularly for the people; but for lack of due notice it was not large;
yet those who came in being quiet and orderly, many things of great weight opened,
and we had, through the goodness of the Lord, a good meeting.

Having visited meetings in town for some time,
I left the city again upon the 24th day of the fifth month, in order for Bristol,
and that night went to Ruscomb, where I stayed till the first-day of the week following.
On the 27th I went to the meeting at Reading,
which was pretty open both forenoon and afternoon.

On the 28th I went to Marlborough, and next day went to Bristol,
where staying till the 31st, I received a letter from Hannah Penn,
of the decease of her husband, our ancient and honorable friend William Penn,
who departed this life on the 30th, between two and three in the morning,
of a short sickness,
of which he had no symptoms at my departure I was much
broken in my spirit on reading the letter,
considering how nearly we had been acquainted and united in the Truth;
and a concern taking hold of my mind to be at the interment of his corpse,
I set out that afternoon about three, from Bristol, accompanied by his son John Penn,
and on the 1st of the sixth month arrived at Ruscomb late in the evening,
where we found the widow and most of the family together.
Our coming occasioned a fresh remembrance of the deceased,
and also a renewed flood of many tears from all eyes.
A solid time we had, but few words among us for some time;
for it was a deep baptizing season, and the Lord was near.

Here I stayed till the 5th, and that day accompanied the corpse to the grave,
at Jordan`'s meeting-place in the county of Bucks,
where we had a large meeting of Friends and others, from many places.
And as the Lord had made choice of him in the days of his youth,
for great and good services,
and had been with him in many dangers and difficulties of various kinds,
so he did not leave him in his last moments,
but honored the occasion with his blessed presence,
and gave us a happy season of his goodness, to the general satisfaction of all;
the meeting being well spoken of by strangers afterwards.
That night I returned to Ruscomb with the family, where I stayed till the 10th;
and being present at the opening of his last Will,
had occasion to advise the family touching their various interests therein,
as I thought most conducing to equity, and their general peace and good,
as became their relation to, and honor of, the deceased.

On the 10th I went to the meeting at Reading, and that evening returned to Ruscomb,
being solicited thereto by the family,
in order to some further advice concerning their affairs, being of great importance,
and accompanied with many and considerable difficulties.

On the 12th I returned to Reading to their meeting,
and on the 13th was at the meeting at Newbury,
where the Friends who formerly separated themselves, were now,
after the example of Reading, returned, and become one with Friends again;
and though for some time a spirit of heaviness was over several,
yet the Lord condescended to arise for our help,
and things opened to the state of the meeting,
which concluded in a more living condition.
That evening I went to Marlborough.

On the 14th I appointed a meeting there, which, though small, was open and comfortable;
and that afternoon I went forward to Monks,
where I was kindly received by my friends Caleb Dickinson and his wife,
and there I stayed till the 16th,
being much fatigued in these late long journeys in the heat of the weather,
which had been extreme at times this summer.

On the 17th, being the first of the week, I was at Bath,
where many people being come to drink the waters,
the meeting was full both forenoon and afternoon, and things were open and well.
Finding some remains of the effects of my late journeys,
I had freedom to stay a little to try the bath, and drink the water;
and yet not without an eye to the good of the people who resorted there,
and frequented our meetings there, rather than in their respective counties,
as being less under the observation of their neighbors.

On the 19th we had an appointed meeting there, which was of some service,
people of several notions in religion being present, who were generally satisfied.
On the 21st was the meeting-day of course; but having had a meeting as before,
and no notice given the people, they were not apprized of it,
so that we had less company of them than before;
but it proved a good season to those who were present;
for the Lord was with us in his love and goodness.

On the 24th, being the first of the week, I was at this meeting again,
where came Friends from Bristol and some other places, and some strangers in town,
so that the place was filled both forenoon and afternoon; and the Lord was near,
both to comfort his own, and also to invite others, opening many things to that end,
which seemed to be satisfactory in general, by the sober deportment of the people.

On the 28th went to a marriage near Bedford, where came many strangers, with Friends,
and the Lord gave us a tender and open season of his love.
The doctrine of the kingdom of Christ dropped as the dew, to the refreshing of many,
and to general satisfaction;
especially in the repetition of things relating to our dear Lord Jesus,
and his sufferings upon the cross for the sins of the whole world,
and his appearance as the covenant of light and life to all mankind.
That evening I returned to Bath, and was at their meeting the day following,
which had been put off till then,
several Friends being out of town at the marriage aforesaid; but this meeting was small,
being out of course, and due notice not given to the people,
yet a comfortable time we had before it ended.

I continued here till the 2nd of the seventh month,
being partly induced by the concern I had for the Countess of Ranelagh,
a goodnatured and affable person, and at that time religiously inclined;
who having lodgings at my friend Thomas Gingell`'s, on account of the Bath,
and I lodging there also, she had heard some report of me; and being desirous to see me,
invited the Friend, his wife, and me, one evening not long after she came to town,
to an entertainment she had provided for us.
This began an acquaintance,
which was followed with some other interviews on like occasions,
which she was pleased to repeat f and gave me opportunity,
on her mentioning some matters of religion, to discourse upon several things,
which I found not ungrateful to her;
particularly upon the subjects of baptism and the supper.
The former she readily owned themselves to be wrong in,
as practicing a thing not instituted; and to confirm her therein,
I produced her two old canons made in the time of the apostasy;
the first in the Milevetan Council in Africa, Anno.
402, in these words: "`It is our will,
that all who affirm young children have everlasting life, which are not baptized,
to the taking away original sin, that they be anathematized.`"
As by Danvers, page 105. The second, in the fifth Carthagenian Council, runs thus:
"`We will,
that whosoever denies that little children by baptism are not freed from perdition,
and eternally saved, that they be accursed.`"
This was first confirmed by Pope Innocentius and Augustine, with seventy bishops.
These ignorant and presumptuous men,
upon an imagination that little children are guilty of original sin,
so as to be damned for it, invented these curses; wherein their language is,
"`It is our will,`" and "`We will,`" and not a word of the will of God;
as to be sure the divine Wisdom was never the author of it.

As to sprinkling, instead of baptizing, I observed it was introduced by one Cyprian,
sometime bishop of Carthage, by the suffrage of the people; who,
from the danger and inconvenience, as he thought, of baptizing the sick,
reasoned for their being sprinkled with water, instead of being baptized;
and for sprinkling prisoners, converted in prison,
for lack of conveniency of water to baptize them; and by degrees,
they brought it in for sick children, and then for all children.
So that here is the proper and true ground of sprinkling and baptizing children,
introduced in the time of apostasy and blindness,
and continued among the Papists till the time of the Protestant reformation;
and they finding with it a great mixture of other things, as salt, spittle, cream,
the sign of the cross, godfathers, vows, etc.,
they saw some of these things to be superstitious innovations,
but could not reform the whole at once.
They reformed as to salt, spittle, etc., but either could not or would not see,
that infants are not subjects of baptism, nor sprinkling the mode of it;
and that the sign of the cross therein, with godfathers and vows,
are not an institution of Christ, or practice of the apostles, etc.,
with all which she seemed fully to acquiesce, owning freely,
that sprinkling is not the mode, nor infants the subjects of baptism.
But as to the supper, she was not so clear, and consequently more tenacious,
and yet with much modesty and condescension;
but being too late then to go fully into that subject, it was declined by consent,
for that time.
But before I departed from Bath,
I had more conversation with her on these and other religious subjects;
and found her of a very good understanding,
and no way tenacious of what seemed amiss in notion or practice.

I came from Bath on the 2nd of the seventh month to Bristol,
and next day went to the meeting at Chew, which was not large, but pretty open.

On the 10th I was at Frenchay, on the 11th at Olson, and on the 12th at Thornbury.
The last was a large open meeting, as also were most of the rest.

On the 17th I went to the meeting at Clareham, where I met with George Bowles,
who had come down that way to visit Friends;
and he being an able minister of the gospel of Christ, and the Lord with us,
we had a large and good meeting; for the doors were opened by the key of David,
both of utterance and entrance, and it was a happy day to several.

On the 18th I was at an appointed meeting at Sidcot,
where we sat a long time before the Lord was pleased to open himself;
but he condescended at last, and his reward came with him, for we had an open time;
and William Jenkins, a schoolmaster and Friend there, bringing with him all his scholars,
many of them gentlemen`'s sons about the country, I had something to them in particular.

On the 19th I had an appointed meeting at Posset,
and the first of the week I was at a meeting at Portbury,
which had been appointed in the same barn in which we had one before;
but the landlord being one of the high sort,
threatened the tenant who possessed the same; so we had the grant of another near,
which proving too little for the concourse of people,
we held the meeting in an orchard ad joining.
It was large, and many truths were declared in divine power and wisdom,
and some of the people touched, and generally satisfied.

That evening I returned to Posset, and Samuel Bownas with me,
who had come to accompany me to some meetings in those parts,
having full knowledge of the most advantageous places for Truth`'s service.
On the 22nd we went to Glastonbury, and had a meeting there next evening;
and a burying happening about the same time, the meeting was large,
and very open and well.

The 25th was the quarterly meeting for the county of Somerset, which was large and open.
Here we reconciled a difference that had been long
depending between a Friend and a monthly meeting,
which had done much hurt among them, and all ended in peace and satisfaction.

On the 26th I had another meeting, which was very open, after some time of hardness.
That night I went home with Samuel Bownas to his house,
accompanied also by John Andrews of Bristol, and Alexander Arscot of the same place,
who had been at the quarterly meeting with us.

On the 27th, being the first of the week, was at their monthly meeting for worship,
which was large, and held silent a long time;
but at length I had an open time among them, and Samuel Bownas some good time after:
I concluded the meeting with prayer, and all ended well and comfortable.
That night we went together to Chard, and lodged with our ancient friend Elias Osborne,
who was very glad to see us, with his whole family.

On the 30th we went on to Kingsbridge, to the quarterly meeting of Devonshire,
which was small, by reason of the weather,
and the remoteness of the members constituting it;
but we were well rewarded for all our travel and pains, for the Lord was with us,
and gave us a good season of his comfortable presence together.
The next day we had also a good time before we entered upon the business of the meeting.
This being over, I went to Plymouth meeting, which, by reason of the weather,
was small and long silent; but in the end I had something to say to them,
to stir up the careless to their duty, and the meeting ended well.

On the 5th of eighth month, being the first of the week,
I was again there both forenoon and afternoon.
The meetings were large and pretty open.
We had also a little evening meeting in Henry Cane`'s house with a few Friends.
We set out from Plymouth on the 6th, in order for the quarterly meeting at Falmouth;
and the wind being very high, and rain with it, we could not pass at the lower ferry;
and when we came to the upper, we were twice repulsed by the storm,
but at the third essay, got over, and that night got to St. Austle,
and lodged at Samuel Hopwood`'s. On the 7th I arrived at
Falmouth before the meeting was half over,
and was opened into some things of importance, and had a good time among Friends there.
Next day being their meeting for worship,
we had a good season of the blessed presence of the Lord, and an open time,
some of the town`'s people also coming in.

On the 12th I went to Key meeting, which it was supposed would be large,
being a monthly meeting, composed of several meetings for worship.
It was a heavy time for the most part, and yet ended well.

The next day I went to Austle, and on the 14th had a meeting there;
and though it was the most stormy and rainy day I had observed since I came into Europe,
yet we had a large meeting, most of them being of the town`'s people, and generally sober.
A good time we had together, and the people were generally satisfied.
On the 15th we had a meeting at Liskeard, which was very open,
and Truth overall in dominion, and many tendered.
On the 17th were at Sticklepath meeting, which was very small, but comfortable;
on the 19th, being the first of the week, was at Exeter meeting,
which was large in the morning, by reason of a marriage, that drew many,
who were curious to observe it; and a good open time we had.
The report of this meeting in town made the afternoon meeting large: it was more open,
and to general satisfaction.

On the 22nd I was at the meeting at Topsham, to which, upon notice,
came some Presbyterians; and we had an open time,
many things in my testimony being very suitable,
though I did not know what sect they were of till after the meeting.

+++[+++After attending meetings at Exeter, Covington, Spiceland, Wellington, and Taunton,]
on the 31st went to Bridgewater, where we arrived about half an hour after twelve,
being very wet with rain; and there being but two or three families of Friends in town,
they had no meeting-house; and expecting more company than usual,
they applied to a Baptist teacher and some of his elders for their meeting house,
which was readily granted.
We met at two in the afternoon, and considering the time,
we had a pretty large gathering, most of them Baptists, and their teacher was there,
and behaved very civilly.
We had a good open time, and things were well.

On the 1st of the ninth month I returned to John Govet`'s, and the day following,
being the first of the week, I was again at Wellington;
and it being a monthly meeting for worship,
many Friends and others came from the country round, and it was a very large gathering:
Samuel Bownas being also there, we had an open satisfactory time.
On the 4th we had a very large meeting at Chard,
being the largest that any had seen there, and very open.
There was present a Baptist teacher, and some said an Episcopal priest also.
On the 5th went to Malmsbury, where the meeting was long in gathering, and not large,
and heavy and flat most of the time, but ended pretty fresh.

On the 6th had a meeting at Lyme, to which came a few of the meaner sort of the people,
some others, and a few Friends.
The people were low in understanding, so that it was hard to minister to their states,
there being Mule to lay hold of in them; yet in the main it was a good meeting.
On the 7th we had a meeting at Bridport, which was pretty full and open.
I had many things to say to them in the openings of Truth,
which had a good reach upon several.
On the 9th I went to the meeting at Thorncomb, and being the first of the week,
it was large; and the Lord gave us an open and comfortable time,
many strangers being there, and some much broken.
On the 11th I was at an appointed meeting at Crewkern, which was not large,
there being but few Friends belonging to it; but some sober people coming in,
we had a good time, several being touched by the power of Truth.

On the 13th I was at their week-day meeting at Lymington,
held in Samuel Bownas`'s malt-house, which was well filled, and a pretty good meeting.

On the 21st we had an appointed meeting in the evening at Sherburn, which was very large,
and though consisting mostly of other people, they were generally very sober.
On the 23rd, being the first of the week,
we had an appointed meeting in the town hall of Ivelchester,
which was very large from all the parishes round,
and the Lord was not lacking to us in his goodness, but gave us an open time,
to general satisfaction.
On the 24th, in the evening, we had a meeting at Summerton, which was large,
and many things opened to information, edification, and comfort.
On the 25th I went to the funeral of a Friend at Hambridge, where many people appeared,
and the Lord was pleased to make it a comfortable time to us;
and the people were generally sober and well satisfied.
On the 26th, at evening, I returned to Longsutton,
and the day after was at their monthly meeting.
That evening I had a very large meeting there, where things opened freely,
and the Truth was much over the people,
to the praise of him without whom we can do nothing.

On the 27th we had a meeting at Langport, in the Presbyterian meeting-house,
where Samuel Bownas and I sat in the pulpit, as the most convenient place to be heard.
Many of that people came to the meeting, and among others,
the elder who granted us the house; they were generally satisfied,
things opening clearly and fully to several weighty points.
This elder was so well pleased, that after the meeting,
he assured Friends that we should have their house for
that service as often as we had occasion;
which we looked the more at from him,
because some of that sect have formerly behaved in a quite
differing manner towards our friends in some other places:
but we were glad of this condescension, both for their sakes,
and the prevailing of Truth in some measure among the people.

On the 28th we had a meeting at Bridgewater,
in a ware-house of Thomas Holwell and Joseph Ball, two Friends, young men,
who had lately gone there to live.
For a certain high man among the Baptists had been much disgusted against
their preacher for letting us have their meeting-house the time before,
threatening to withdraw his contribution; but the young man bearing it with patience,
another of his hearers, who had been satisfied with the meeting, said,
if the other detained what he used to contribute, he would make it up.
We did not put him upon it the second time,
hoping he will not lose his reward for what he did for Truth`'s service,
though he may lose the favor of some of the angry sort.
The meeting was very large and open, and the people generally reached, being,
after some time, sober and attentive.
The Lord gave us a good time among them, Samuel Bownas being also there.
I have some hopes that the Lord will raise a people yet in that place, and thereaway,
to his own glory.

On the 3rd I went to Bristol, where I stayed till the 4th of the twelfth month following.
Here I had many good opportunities among Friends, and often among others,
who usually came to our meetings on first-days.
I was also, during my stay here, at the meeting at Kingsweston,
and at a funeral at Frenchay;
and Samuel Bownas and I took much pains to
reconcile these Friends to the body at Bristol,
they having set up a separate meeting by themselves, under pretense that Friends there,
especially the men`'s meeting, were gone from Truth into the grossest evils;
and yet would not accuse any particular of any one crime.
They said, they and Friends of Bristol were of two different spirits,
and till they came to be of one, there could be no reconciliation;
and to be sure they meant the better to themselves.
We could make but little impression upon them,
the women who governed them being very high, and very conceited of themselves,
and laid all upon God, as his requirings;
putting themselves in the place of the righteous in former ages, the prophets,
apostles and martyrs; and Friends of Bristol in the place of Cain, Nimrod,
Nebuchadnezzar, heathen persecutors, Papists, and Queen Mary;
and themselves as suffering all those cruelties:
and all this because the men`'s meeting could not
see any reason for their separate meeting,
desiring them to let it alone as a thing unprofitable,
as things were stated at that time in that city.
I also tried a second time before I came away;
but they seemed still more and more averse, under the pretenses above-said.
During this stay I was at times under great heaviness from the effects of the separation,
and other sufferings of the seed of life in that city.

On the 4th of the twelfth month, accompanied by my old friend and long acquaintance,
Waller Newbury, of Boston, in New England, I went from there to Kainsham.
On the 7th we went to Bradford, and the day following, being the first of the week,
we had three meetings there; that in the morning was not large, but indifferently open,
consisting for the most part of Friends.
In the afternoon it was large and more open to the people; and in the evening,
greatest part of the more reputable people of the town being there,
it was very large and very open, and the Lord gave us a good time, and opened,
through our ministry, many things of importance; and Truth was over all.
Many went away who could not get in, the throng was so great in that large house.

+++[+++After attending several meetings he says:]
on the 22nd I was at Henley upon Thames,
where we had two as open meetings as I had known for a long time.
That in the evening was very large, a number of the town`'s people coming in,
and great openness among them; went next day to London, where I found great openness,
both among Friends and others, many coming to our meetings on first-days.

During my stay at London, which was from the 23rd of the twelfth month,
to the 16th of the seventh month, 1719, I visited meetings there,
and some meetings adjacent, and was at the yearly meeting,
which was more peaceable than at some other times;
and in the main we had a good and comfortable time.

In this meeting John Gurnev, jun., of Norwich,
though satisfied with the affirmation as it then stood,
moved for a further solicitation to the government,
for ease also to the dissatisfied Friends in that case,
which was seconded by John Eccleslon, and followed by Richard Ashby,
and some others on that side.
And while things run in that channel, there was a considerable glory over the meeting,
and the peaceable and divine Truth comforted many;
and his peaceable wisdom prevailed with most of the meeting to assent and acquiesce.
But as there were some particular persons there, who,
having more regard to party than unity,
and to themselves and what they had procured and set up,
than the peace of the church--designing to set the affirmation as it then was, over all,
and not at all in any other terms--in their usual subtlety raised several objections,
and a palpable cloud of darkness over the meeting,
and a great uneasiness in the minds of many, which, after some time, being dispelled,
and that spirit made manifest and repulsed,
the meeting concluded for a fresh solicitation to the next session of Parliament,
if things should continue as they were till the said session.

One particular passage which happened while I was at London,
I think proper to insert here, since it fell out so much to my own satisfaction.
When the present earl of Carlisle was a boy, he was at that city with his grandfather,
then governor of the castle there, and I was at the same time at school in that city,
which occasioned my being admitted into the
acquaintance and favor of this young nobleman.
As I had then a strong affection for him, it did not wear out all this time,
notwithstanding the several changes both in him and me, and our differing circumstances;
so that I had an inclination to see him, and speak with him,
which I had not done in many years.
Accordingly, taking Dr. Gilbert Heathcote in my company, partly to introduce me,
he being physician to some of the family, and known to the earl,
I went one morning to his lodgings.

The earl received us respectfully, though I was become a stranger to him;
for he did not at all know me, nor did I presently make myself known.
He ordered a couple of chairs to be placed for us, and bid us sit down by him;
and some occasional expressions having passed between him and the doctor, I being silent,
and my mind inwardly exercised at the same time,
and waiting an opportunity for matters of some other consequence,
the earl and I fell into discourse after this manner.

"`Mr. Story,`" said he, "`are you anything related to the Story`'s in Cumberland?`"
"`Yes,`" said I, "`Thomas Story of Justice-Town is my father.`"
"`Did you know Mr. James Appleby, a friend of yours,
who lived on a farm of mine at Askerton "`Yes, very well.`"
"`I have the bad news to tell you, that he is lately dead.
He was a good, industrious man,
and improved that estate much since he had the management of it;
and I think your people are generally sober and industrious, and few of you poor.`"
"`We ought to be so,`" said I,
"`for our principles lead us both to sobriety and industry.`"

"`The great end of the Christian religion,`" said he,
"`being to mortify and subdue the passions, irregular desires and appetites of men,
I see no people in the world come up to that as you do;
but cannot apprehend by what means you arrive at these attainments.
It cannot be anything preached among you that works such effects;
for I have been at some of your meetings, and heard some of you preach,
but could not make anything at all of it; and have also read some of your books,
but could not make much more sense of them than of your preaching;
so that I am still at a loss what to think of you in matters of religion.
I knew a young man in the north of England, whom, perhaps you might also know,
a brother of Mr. Appleby`'s, as wild a young fellow as was in England;
but by some means or other, turning Quaker,
he was no sooner under that profession than he became a very sober good man.`"

"`No doubt,`" said I, "`but you have read the Scriptures,
and may remember what Christ said to his disciples a little before he suffered;
'`It is expedient for you that I go away;
for if I go not away the Comforter will not come: but if I go away,
I will pray the Father, and he shall send you another comforter,
even the Spirit of Truth, which the Father will send in my name;
he shall lead you into all truth, and bring all things into your remembrance,
whatsoever I have said unto you.`'
Again, '`I will not leave you comfortless; I will come again unto you.`'
Here is the Spirit of Truth promised, which is no other than the Spirit of Christ;
and is the same which was promised of God by his prophet, where he says,
'`I will give him for a light to the Gentiles,
and a covenant to the people:`' and as the holy Scriptures elsewhere testify,
'`he is that true light which enlightens every man that
comes into the world:`' and of whom the apostle says,
'`Believe in the light, that you may be children of the light; and if children,
then heirs.`'
Now, though we, in and of ourselves, have been like other men,
incident and subject to many failings and weaknesses,
yet it being given us to believe in the Lord Jesus,
not only as he came in the flesh in that day, but also as he is the light of the world,
we do not only find that his Spirit, as he said, reproved us for our sins,
but is also become our comforter and supporter, as we have repented and left them off.
And according to his promise, by degrees,
he leads into all the necessary truths of the gospel, and out of evil into righteousness;
giving us also to experience the end of his manifestation,
the destruction of the works of the devil, the mortification of our lusts, appetites,
and passions, and to be created anew to good works, through him,
our Lord and Savior Jesus Christ.
And what difference there is between us and other men,
and in our present from our former state, it is the Lord that has done it,
and not ourselves; for we have nothing to boast of but the mercies of God in him.`"

Then said the earl, "`If the Spirit of Christ and his light be all one,
and that light be in all men, why does it not work the same effect in all men?
Why have not I power over my inclinations, as well as you over yours?`"

Then said Dr. Heathcote, "`I was once in my time wild enough; but when it pleased God,
by the manifestation of his divine light, to convince me of the vanity of these things,
and the error of my course of life, through faith in this light,
and obedience to its discoveries,
I am now reformed and got over those lusts and appetites of many kinds,
which once were over me; and as I keep to that light, and not otherwise,
I am daily preserved.
And the true reason of men`'s being overcome by evil is,
because they believe not in that divine manifestation, which manifests it to be evil,
but go on to act the same things after they see them to be wrong.
But as men leave off evil when they see it,
through the power and virtue of the discoverer,
they have further manifestations of that light that discovers it,
and greater power over their corruptions, till all be discovered, and all subdued.
Then there is a liberty and enjoyment in the Truth,
which far exceeds all the enjoyments of this world,
and a satisfaction which nothing else can give.
Therefore, if you would be rid of anything you finds amiss in yourself,
you must not act again the same thing you have once seen to be evil,
or else there never can be any reformation.`"

Then said the earl, of his own accord,
and without anything particularly introductory thereto by either of us,
"`You are a very useful people in the nation, and I think,
deserve encouragement as well as any in it.
I know your people are not generally satisfied with the affirmation;
because I have been often applied to for relief by such as have suffered that way,
and have always done what I could to relieve them, and have helped many.
But as the king and government look upon you favorably,
it were better you were relieved by law;
and if you will move the Parliament for further relief,
you shall not lack any help I can make you;
and I know many are inclined to favor you on that account.
And what do you need besides this?`"

Then I said,
"`We are very sensible of the good intentions of the
government in what they have already done on that account;
but as you have been pleased to observe--though we are
not come at this time to make any complaint about it,
we were not generally easy in it.
And as the king and nobility, in some other cases,
have been as fathers and supports to us,
so we were glad to see their good inclinations still,
and hoped we should not desire any unreasonable thing,
there being one wherein we yet want your further aid; and that is,
to be further relieved against the tyranny and oppression of your priests;
and I hope,`" said I, (by the way) "`the legislature of Great Britain will, in due time,
take care that it shall never more be in the power of the clergy to jostle the throne.`"

Then said the earl, "`You would not have us, I hope, break in upon the laws,
and deprive the ministers of the maintenance the law
provides them! at least till we can see as you see.`"

"`No,`" said I,
"`we are very far from desiring anything that may bring the least reflection,
or any just imputation of blame, upon any of you;
but are as careful of your true honor as you yourselves can be.
Nor do we desire to lead you into any inconvenience, or blame-worthy thing,
if it were in our power; and so far are we from setting up any new craft,
under any new umbrage, that we would have all men to see with their own eyes,
and not to undertake anything but upon sure and certain grounds.
But as the legislature, with very good intent,
have made laws for the more easy recovery of what you call their dues,
these laws prove very oppressive to many poor, honest, industrious families;
for so mean-spirited are some of your country justices in various parts of the nation,
and under the influence of the worse-natured sort of your clergy,
that where the demand may happen to be but a groat, sixpence, or a shilling,
some of them will award the highest fees the law allows, which is ten shillings; which,
though a small sum among you great men,
is much to those who must earn it with the sweat of their brows, at two-pence, fourpence,
six-pence, or twelve-pence a day.
And besides this,
the former destructive ways of proceeding in the exchequer for
tithes being still left in the power of your priests,
many of them decline the more gentle way which the law provides, and make choice of this,
if, peradventure, they may at least ruin and destroy some of us,
which we hope may not be unworthy of the further consideration of our superiors,
so inclinable to equity in our favor.`"

"`Now,`" said he, "`you say something which may bear further consideration:
and I know some of your people have suffered by exorbitant fees;
for as complaint has been made to me, I have relieved several on that account.
But pray, on this occasion, upon what ground do you refuse to pay tithes;
were they not commanded of God?`"

"`We do not deny that they were commanded of God;
but they were made payable to the tribe of Levi, and located in the land of Canaan only;
but by the coming of Christ, there is an end of that law by which tithes were given,
and an end of that tribe, though your clergy still pray for themselves under that name,
the better to insinuate their pretended right,
and the land itself where they were payable, now in the hands of the Turks;
so that the reason of the thing failing, the thing itself also fails.
And since God, by the death of his Son, the great High Priest and Bishop of the soul,
has rejected that tribe, and that service, and established a new one,
to whom he has said, '`Freely you have received,
freely give;`' we do not find he has empowered any of the princes of
the Gentiles to assign any maintenance for his ministers.
But as they have been deceived by the subtlety of the
craft to impose upon mankind by laws on that account,
so by that wisdom, which, in due time, will arise among them,
they will yet be instrumental to undo what they have done,
and leave religion and the gospel upon its own bottom;
which needs no other helper than its own author, or maintenance for its ministers,
but what itself commands;
and they are really such as labor with all their might
to make the gospel they preach without charge.
So far are they from destroying the people for the maintenance of their bodies,
that they have no other reason or inducement for what they do,
but obedience to the calling of God, and the good of souls; whereas the end of hirelings,
though supported by law, is their own bellies.`"

"`Well,`" said he, "`you do not like our ministers; but after all,
I think you lack but one thing to make you a very complete people; that is, to bear arms.
Pray what would have become of this whole nation the
other day when the Spaniards were coming to invade us,
if we had all, or the greatest part, been of your religion?
No doubt we should all have been destroyed or enslaved.`"

To this I answered, "`It was upon this very consideration that the Jews crucified Christ;
for as he had raised Lazarus from the dead,
it greatly awakened the people concerning him, and many believed in him;
in so much that the rulers began to fear,
that if he continued to preach his doctrines among the people, and work miracles,
the body of the people would follow him; and the consequence of that would be,
the state would not have soldiers or people enough to defend them against their enemies.
For as it was prophesied that, under the new covenant,
'`they shall beat their swords into plough-shares, and their spears into pruning hooks;
and that nation shall not lift up sword against nation,
neither shall they learn war any more,`' so Christ being the mediator of that covenant,
preached doctrines conducing to that end; '`Love your enemies;
do good to them that hate you;
pray for them that despitefully use you and persecute you.`'
And to take away all suspicion of any disloyalty to Caesar,
or danger of the state from his kingdom, which was their pretense against him,
he said to Pontius Pilate, '`My kingdom is not of this world:
for if my kingdom were of this world, then would my servants fight,
that I should not be delivered to the Jews; but my kingdom is not of this world.`'
Here he declares his kingdom not to be of this world, being divine and spiritual,
and that his servants will not fight.
For if they love their enemies, they cannot fight with them, much less their friends;
and if they do good to them that hate them, they cannot tight with them neither;
and if they pray for them that despitefully use them and persecute them,
neither can they fight with them; and if they do not as Christ teaches,
they cannot be his disciples.
'`For then are you my friends,`' or disciples '`indeed,`' said the Lord,
'`if you do whatsoever I command you.`'
Now, Christ laying the foundation of such a kingdom, which is not of the world,
though in the world, and declaring his subjects will not fight, it is in this kingdom,
which is a kingdom of righteousness, truth and peace,
in which the prophecy before mentioned is begun to be fulfilled;
and of this kingdom Christ himself, the Prince of righteousness and peace, is only king,
ruler, and lawgiver.
This no way interferes with the kingdoms of this world.
For as Christ himself, being born a Jew, and they,
at that time being subject in some sort, to the Romans, paid tribute to Caesar,
thereby giving an example to all his disciples, in all countries and states,
and in all future ages, as well as that time; so the disciples of Christ,
though they may not fight, pay taxes and tribute to civil states,
as well by the example of their Lord and Master, as the doctrine of the apostle,
in the 13th chapter to the Romans; where he sets forth clearly,
that civil states and powers are of God, and that their end is,
to be '`a terror to evil-doers, and a praise to them that do well.`'
Since then the kingdom of Christ is not of this world; neither is it national,
but spiritual.
It cannot be supposed that any one nation will ever be the church of Christ,
which is not national, and so subjected to the violence of any other nation.
But God, '`by whom kings reign,
and princes decree justice,`' having ordained government and rule,
entrusts it with whom he pleases; and they must apply and administer it accordingly,
till by degrees, the kingdom of Christ, the Prince of divine peace,
has the ascendant over all kingdoms: not by violence, for his servants can offer none:
'`Not by might nor by power, but by my Spirit,`' says the Lord.
It will not be by human force or policy, but by conviction; not by violence, but consent,
that '`the kingdoms of this world will become the kingdoms of God, and of his Christ.`'
Nor will the kingdoms and powers in this world ever cease,
being God`'s ordinance in natural and civil affairs, till the reason of them cease;
that is, till all violence and injustice cease, and evil-doing come to an end,
by the advancement of Truth, righteousness, love and peace, over all nations,
which is the true end of the coming of the Lord Jesus,
and nature of his kingdom here on earth.
So that as the kingdom of Christ can offer no other force to
the kingdoms or states of men than that of love and truth,
and his subjects may not fight, but pay taxes, customs, tribute, fear,
and honor to all kings, powers and states,
in all nations where they are chosen of God out of the world to serve him,
and bear testimony to his name, neither Jew nor Greek, barbarian, Scythian, Mahometan,
Infidel, nor nominal Christian, can have any reasonable jealousy of the true Christian,
whose practice is according to the doctrine and
commandments of his Lord and Master Christ Jesus:
and whosoever falls short of that ceases to be his disciple, and reverts to the world.
But to his disciples he says, '`You are not of the world;
but God has chosen you out of the world.
If you were of the world, the world would love you; for the world loves its own:
but you are not of the world, therefore the world hates you.
But marvel not that the world hates you; for it hated me before it hated you.`'
So that upon the whole, this nation is not in danger of the Spaniard,
or of any other nation, by reason of our principle, or for lack of our help in fighting,
which we have declined, because we dared not, or could not use the weapons of war.
For many of us have been fighters; and I myself have worn a sword,
and knew very well how to use it; but being convinced of the evil,
by the Spirit of the Lord Jesus, working in us a conformity to the will of God,
and subjecting us to himself, as subjects of his peaceable kingdom,
it is neither cowardice in ourselves, nor rebellion, nor disloyally to kings or rulers,
whom God, in the course of his providence, advances in nations,
but conscience towards God, and obedience to his dear Son, the Prince of peace,
our Lord and Savior Christ Jesus, which make us decline fighting.`"

To this effect, and much in the same words, was my answer to the earl,
who heard me with great patience and candor, and then replied, "`It is true,`" said he,
"`so long as you behave peaceably, are loyal to the government, and pay your taxes,
as you do, I think, when all is done,
there is not an absolute necessity for your personal service in war,
since his majesty may always have soldiers enough for money, as he may have occasion.`"
Some time being spent in what I have here related,
and things seeming to sit well on this great man`'s mind, I was willing to withdraw;
and then rising upon my feet, I said further unto him,
"`Considering your station and resort, we may trespass, though undesigned, on your time,
which may be necessarily employed on public services;
but if I might have liberty to wait on you at leisure times,
I do not doubt but to make all these points we have gone upon,
and all others wherein we differ from other professors of Christianity,
as clear as the sun at noon-day, in favor of our profession,
and that the same thing which now goes under the reproachful name of Quakerism and error,
is no other than primitive Christianity.`"

To which he replied, "`I shall be glad to see you at any convenient time.
My hour is about nine or ten in the morning; and if I should happen to be indisposed,
or otherwise engaged, I will let you know it,
and expect you another time;`" which accepting as a favor, I proceeded thus:

"`I took notice of what you said in this discourse concerning our preaching and writings,
that they seemed both awkward and unintelligible.
I suppose you may remember something of one James Wilson,
who has waited on you some times to solicit your
assistance for relief of several of our friends.`"

"`This is,`" said he, "`Wilson of Westmoreland, an honest good man.`"
"`It is the same,`" said I. "`You was pleased to admit him to
some discourse with you on some points of religion,
on some of those occasions; and he then promised to send you a book,
which would clear up some of those matters more than could then be done by him;
and he has accordingly requested me to present you with it:`" and so I gave it him,
being Robert Barclay`'s Apology, and said,
"`If you pleases to read this book over with attention,
I hope it will give you some more satisfaction,
both concerning the principles we believe and suffer for, ourselves, and our writings.`"
He readily received the book, and said, "`I will peruse it.`"
I said further, "`It is below the earl of Carlisle to be flattered,
and inconsistent with me to do it; but this I can say with much freedom,
I have often remembered you and yours, with many good wishes, when far remote,
in another part of the world; and since I returned to Europe have, from time to time,
desired to see you, but the circumstances of my concerns would not allow me till now.
I am glad of this opportunity, and your condescension herein,
and may make use of the liberty given me, in some other convenient time;
and in the mean time wish your happiness and prosperity.`"
And so we departed with great satisfaction.
