== Chapter 17

At this time I stayed in Cumberland about two years, sometimes visiting Friends thereaway,
and having some meetings in new places about in the country;
and was twice at the yearly meeting for the north, once at Carlisle and once at Kendal,
and some meetings also in Westmoreland, and the north parts of Lancashire;
and among others, was at the first meeting in the new meeting-house at Whitehaven,
on the day called Easter-day, in the year 1725.
It was a large and open meeting, many, both Friends and others being there;
and I heard not of any objection.

On the 6th of the eighth month I went from Carlisle to Alston-moor,
and the quarterly meeting for Northumberland falling the next day at East-Allandale,
I went to it; where the Lord was good to us, and I had a very open time among them.
On the 8th I went to Newcastle,
and on the 10th was at their meeting forenoon and afternoon; which were large and open.
Joseph Jordan, son of Robert Jordan of Virginia, was also there.
He is a young man, of a clean life, and solid testimony,
calm and deliberate in his ministry, which is reaching and edifying;
and I was glad to see and hear him.
When I was last at his father`'s house, after that dispute with the French priest Burtell,
at his uncle Thomas Jordan`'s, he was but a boy;
and I did not know him when I saw him here.

The next day we went together to Shields to a monthly meeting; which was pretty large,
and very open, several Friends from Sunderland being also there.

From here Joseph Jordan went, on the third-day, westward, in order for Cumberland;
and I stayed at Newcastle till the fifth; which being the day of their weekly meeting,
I was there, and an open time the Lord gave us, to our mutual comfort.
On the 15th I went to Sunderland; and on the 17th, being the first of the week,
was at their meeting forenoon and afternoon.
The first was more select, for the most part Friends;
but in the afternoon there came in many others, and among the rest,
three attorneys at law; who,
hearing that I had formerly been initialed into that faculty,
came of curiosity to make their observations; and as I heard afterwards,
were well satisfied; especially one of them, who said,
he would not have missed that meeting.
It was an open time, and to general satisfaction.

On the 22nd I went to Bishop-Auckland;
where Friends of that place and of Raby met together: and though we sat long in silence,
it was a profitable meeting; and I had a good time among them,
both in testimony and prayer;
and in the evening went home with my old friend the widow Walton.
She had been formerly wailing-woman to the countess Carlisle; and convinced,
in her service, while in Cumberland, by William Armstrong,
and helped forward and confirmed by me at London;
our old and early acquaintance in the Truth still remaining fresh and living.

On the 24th, being the first of the week, I was at Darlington meeting,
forenoon and afternoon.
It is a pretty gathering of Friends.
We had a tender open time in the morning; and in the afternoon several strangers came in,
of various persuasions: and an opening, convincing time it was to several,
and a solid meeting.

On the 30th I went to Whitby, and next day, being the first of the week,
was at their meeting forenoon and afternoon.
The meeting is considerable, as to the number of Friends;
and at this time open and clear; and several of the neighborhood there in the afternoon,
very solid.
On the fourth of the week was at Scarborough meeting,
a good number of Friends belonging it, and we had a seasoning time together in the Truth;
and on the fifth-day following, they put off the time of their meeting till the evening;
and then came many of the people; and we had a good open time, all being sober and solid.

On first-day following, in the forenoon,
the meeting was well filled with Friends and some others, and a good meeting;
but for the sake of the people, the afternoon meeting being put off till the evening,
the house, though large, was extremely crowded,
and many in the street who could not get in, and some went away for that reason.
Some truths of the gospel were clearly preached among them, in the authority of it;
but the press was so great, especially towards the door,
that they of necessity made themselves uneasy; which hurt the meeting in some degree,
yet in the main it was an open, informing, and confirming time to Friends and others.
Many of the reputable inhabitants were there.

Third-day went to a meeting at Pickering; which was small, and for some time, heavy;
but the Lord quickened us together, and gave us comfort in the end.
On the 9th of the ninth month the waters were very high, overflowing the banks;
so that with difficulty and some danger, I got to the fourth-day meeting at Malton;
which was small, but very open and comfortable.
On the 11th I made a visit to the earl of Carlisle at Castle Howard,
about three miles from Malton.
He was confined to his chamber in a fit of the gout; but sending up my name,
he readily admitted me, and expressed satisfaction to see me.
Being set down, after a little pause of silence, he moved a discourse to this purpose:
that mankind are incident to many troubles and temptations in life,
and he observed a great difference between the trouble of mind which
arises from losses and disappointments in the things of the world,
and that which proceeds from a sense of misconduct,
in a course inconsistent with duty to God and his known laws; and in the first instanced,
a man`'s hazarding his all, in one bottom, at sea, and suffering shipwreck.

This great truth I confirmed in the words of Solomon,
"`' The spirit of a man may bear his infirmity; but a wounded spirit who can bear?`'
Magnanimous persons may sustain, for a long time, the shocks of bodily ailments,
as likewise of losses and disappointments in life; but when,
by our rebellion and disobedience to that holy law of life and grace,
which God in mercy has placed in us, for our guide and conductor,
with respect to himself and towards one another, we wound not only our own consciences,
but crucify to ourselves the Son of God afresh, and wound his holy Spirit in us,
our anxiety must needs be incomparably greater in this case than the former.
Yet such is the unspeakable goodness of God to mankind,
and the efficacy of the virtue of that grace that flows from him,
that he not only shows us our transgressions and the evil of them;
not only the wounds and sores thereby produced; but as we are truly humbled in that view,
and willing to amend for time to come, he, most kind and beneficent,
sends forth his healing and restoring virtue, as emollient ointment,
taking away the anguish, and healing all our wounds.`"
This introduced a large field of discourse on such and the like subjects,
which held nearly three hours; and I believe, to mutual satisfaction,
and much upon the particular points following:

"`1. Faith in Christ, as come in the flesh, being the word, power,
and wisdom of God assuming our nature, in a person separate from all men,
as all others are.
2+++.+++ Faith in him as a quickening spirit, and divine light,
flowing from the Father into our minds,
affecting and influencing both body and mind at certain times and modes, and degrees,
as pleases him; being as a condemning law in us while we are in a state of unbelief,
sin and rebellion; but a law of divine and immortal life,
and true comforter in a penitent and faithful state;
to which he himself reduces us by his judgments and by his mercy,
inwardly revealed and applied: by the ministration of judgment, wasting,
as with divine fire and sword, the whole body of the sins of the flesh and carnal mind;
and at the same time, in and by the same Spirit,
manifesting and applying mercy and life eternal to the believing, humble,
and penitent soul;
and so completing that salvation declared by the coming of Jesus Christ,
his death and sufferings.

"`2. The kingdom of Christ in this world,
ruling and reigning in the minds of regenerate men, by his grace and spirit,
as King of Salem, Prince of righteousness and peace, in all them that believe and obey;
who are the children of this kingdom in divine communion.
The kingdoms of men,
established by the providence of God for the
government of the world in its natural state,
for the preservation of life, liberty, character, property; the better sort of men,
in a moral social state, being children of this kingdom.

"`3. The kingdom of antichrist, being a false show, counterfeit,
and pretense of Christianity, under which all cruelties and oppressions are,
and have been, acted, to the destruction of life, limb, liberty, property, and religion.
The children of this kingdom are priests, professing Christ, but living to themselves;
being called by hopes of honor, power and advantages in this world, and not of the Lord;
and the great men and small of this world confederating with them in worldly
views against the natural and common interests of the rest of mankind,
enslaving the conscience by force of human laws of their own devising,
according to that observation of Christ to his disciples,
'`Do not great men hale you out of the synagogues
before the judgment seats,`' and the like;
in all which they are influenced, and often out of their own sight,
by a devouring destroying spirit, contrary to the nature of Christ; who is most gentle,
wise, and beneficent, bringing forth in men his own fruits,
and making them like unto himself; as antichrist renders all his children like unto him,
proud, lofty angry, fierce, cruel, and unjust, bloodthirsty, arbitrary and tyrannical,
without compassion and mercy, implacable and unreasonable;
as is ever seen in all persecutors, whether under the pretense of national laws,
or despotic and absolute rule.`"
With some other important matters, not now to be fully collected.

Near the time of their dining came in the lady Irwin, one of his daughters, then a widow,
desiring to know what he would please to eat; to which he did not presently answer,
but bid her sit down in the room; which she did.
After a little pause, he said to her, "`I could have wished you had been present,
to hear what has passed between us on different subjects;`" and then
gave her to understand how great an esteem he had for Friends,
as an honest religious people:
and as we had been great sufferers on account of our principles,
he had ever helped and served us to the best of his power, and ever would.
All which he spoke with solid gravity,
as if he meant to impress in her mind a good opinion of us.
And when he had finished, desired her to take me with her to dinner,
for he could not go himself; which accordingly she did:
but before I went out of the room, he repeated his good opinion of Friends,
and his respect for myself in particular,
desiring me to call as often as my concerns lay that way.
I went to dinner accordingly, the company being only that lady, her maiden sister,
his son colonel Howard, an old gentlewoman, and the chaplain;
among whom I was civilly treated.

In the afternoon I returned to Malton, to an evening meeting I had appointed there.
The meeting was large, many of the town`'s people coming in;
and a very free and open time we had, the people being very sober and attentive,
and the truths of the gospel were opened among them.
The 12th, their monthly meeting at that place falling in course, I stayed and attended it,
having a very open time before we went upon the business of it.

On the 13th I went to York, and on first-day morning the meeting was not large,
there being but few Friends there for so large a city; but in the afternoon, much larger,
many of the town`'s people coming in, and very sober.

On the third-day evening we had another meeting in the great meeting-house;
which was well filled, many people, and some of note being there;
and things were open and well.
Fifth-day was their week-day meeting.
Some persons of note sent to know the time, and came; but did not behave well.
They were light, and whispered, and after a while, went out;
but on some consultation among themselves, came in again, were much soberer,
and stayed the meeting.
On sixth-day there happened a burial; and to the graveyard came many of the people,
one of the aldermen, and one of his sheriffs, and some others of distinction;
and I had an open time among them.

On the first-day following, the meeting in the morning was pretty large and open;
and notice being given beforehand of one that evening in the great meeting-house,
it was much crowded, many of the better sort being there,
and nothing rude or indecent appeared in so great a multitude; but a decent sobriety,
to the general satisfaction of Friends, as the meeting was also to the people.
After that meeting I was easy to leave the place.

On the 28th, being the first of the week,
we had a quiet meeting at Gainsborough in the forenoon, and another in the afternoon;
both small, and few besides Friends:
but not being easy to leave the place without seeing more of the people, the Friends,
at my request, appointed another meeting on the second-day evening;
and the people having notice, and many of the more noted sort, the house was filled,
and many in the yard; and a very open satisfactory time we had on that occasion.

On the 4th of tenth month we went to Stanford, to John Young`'s; and the day following,
being the first of the week, had two meetings in his house.
The first was very small; there being few Friends in town, or near it;
but as he had contrived to lay two front rooms into one,
and had given notice to the neighbors,
some of whom had also been at meeting in the forenoon,
we had in the evening a large meeting,
and an open time among the more reputable sort of both sexes, and some military officers.
The meeting was held and ended in sobriety.
On the 6th, in the evening, we had a meeting at Cliff;
which was pretty well filled with a low people, but not too mean for the grace of life;
for I had an open time among them; though but Sew Friends were there.

On the 10th I went to Cambridge to John Chapman`'s; and that day was at a meeting in town;
which was small: but several of the scholars being there,
were more sober than ever I observed them before.
I had a very open time among them; and one of the inhabitants, a light airy person,
coming to that meeting, with intent to make himself and others diversion,
was much disappointed; being so touched, as he confessed he never had been before;
and had no power to be rude, as he intended;
but was very sober and attentive all the time, and went off solid and serious.

On the 20th I went to London, and visited the meetings there;
Friends were generally glad to see me, and I also of them in the Lord; and many open,
comfortable, and confirming meetings we had to our great satisfaction.

After some time I returned to Carlisle and Justice-town,
visiting some neighboring meetings, and prosecuting some affairs of my own,
and did not take any journey out of the county
of Cumberland till the 25th of the second month,
1728, when I set forward towards the yearly meeting at Edinburgh.
On the 29th we went to the city of Edinburgh, where I lodged with William Miller, jun.,
and on the 30th we had a meeting of ministering Friends,
and after that their yearly meeting for business began;
where things were carried on with unanimity and satisfaction.

On the 1st of the third month, being the fourth of the week, we had a select meeting,
at the house of our friend William Miller, where I lodged, consisting of Friends only;
and that afternoon had another public meeting, at the meeting-house, at the West-Port;
where came many of the inhabitants of the city,
and were much more quiet and attentive than heretofore,
to whom several important truths of the gospel were clearly opened:
and having another meeting in the afternoon, our company increased;
and a good season the Lord gave us.

On the 2nd we had two meetings in the same place;
and our company and satisfaction still increasing,
it gave us encouragement to appoint another on the 3rd,
which was the largest and most satisfactory of all;
for Truth was over all in authority and brightness,
and the people departed under a grave sense of a degree of the virtue of it,
much beyond what I had observed in that city at any time before.

On the 6th, accompanied by Thomas Erskine, I went to Linlithgow,
and that evening had a meeting there; where came a wild looking sort,
there being but about half a dozen Friends remaining in that town:
but we sitting under some concern and sense of the grace of God towards them,
they grew more solid, and we had a good time among them,
and they went away very grave and sober.

On the 7th we went to Glasgow, and lodged at George Swan`'s; where we stayed till the 9th,
their usual meeting-day; and notice being given,
as many of the more reputable sort of people of
the city came to the room as it could contain,
and more; and the Lord gave us a very clear, open, and solid time among them.

On the 10th we had another meeting there, much larger; so that the next room, stairs,
and yard, or lane, were crowded; not with a rude rabble, as in times past,
but an intelligent people, reputable among men;
and as things opened in the wisdom and power of Truth,
they were received with sobriety and attention, to mutual and common satisfaction;
by which, and the open flowing of Truth,
I perceived the state of that people was much altered
for the better since I first knew that place,
and the old prejudices much worn away in many of them.

On the 11th we had another large and open meeting, at eleven in the morning,
at George Swan`'s; where all the room and yard, and some places adjacent, were filled;
and the Lord favored us with his good presence,
and gave us good matter and utterance among them.
The main points falling to my share therein, were the new covenant of light and life,
and the elect Seed; Christ as the mediator and messenger of it to all that believe:
of whom the sons of the first Adam, being born again,
became of that Seed which never fell,
and in whom also they stand and are established forever.
At this meeting were still more of the better sort, and one magistrate;
and for anything that appeared, generally satisfied.
After that meeting we returned in peace the same evening to Robert Gray`'s,
near Garthshore;
where we had a very peaceable open meeting next day with a few plain
and quiet people among the few Friends remaining in those parts.

On the 19th, being the first of the week, I was at Kelso both forenoon and afternoon;
where came several of the neighborhood: and as things opened clear and full,
the meetings were, for anything I could observe,
very acceptable both to Friends and strangers.

On the 20th I went to Berwick, where there had formerly been a meeting of Friends;
but they are all gone except one man and a woman:
so that at this time the meeting was quite lost, and the meeting-house being small,
and I willing to see as many of the people together as I could,
perceiving the grace of life to remain in my mind towards them,
the Friends with me applied to an acquaintance of theirs, a Presbyterian by profession,
who furnished us next day with a warehouse, and backyard,
wherein he ordered convenient seats of deal boards, etc., and we had a large auditory.

And as the Lord furnished my heart with much grace towards them, so out of that abundance.
I was enabled to say many things to them of importance;
and the necessary truths of the gospel were plentifully
and clearly opened that day among them,
and the solid weight of divine Truth reigned over all, to general satisfaction,
and the sole glory of Him, of whom is the power, and whose right it is to reign,
both now and forever.
Amen.

The meeting being thus well over, after some refreshment,
I set forward towards Alnwick Abbey,
my old friend Samuel Robertson and his son going with me.
That night we lodged at an inn about twelve miles from Berwick,
and the next day went to the Abbey with our friend John Doubleday, jun.,
where we were kindly received by him and his wife,
she being the eldest daughter of Robert Barclay, sen., of Ury,
and grand-daughter of the famous and honorable Robert Barclay of the same place.

In the afternoon John Doubleday ordered notice to be given through the town of Alnwick,
of a meeting at his father`'s house at the Abbey next day, where we lodged,
and where his father had provided a meeting-house, chiefly to suit such occasions,
and several of the more reputable sort of the inhabitants were there;
but the quarter sessions of the peace sitting in town,
occasioned the meeting to be thinner than otherwise it might;
though a comfortable and very open time was given us.

On the 26th, being the first of the week, I was at Newcastle meeting; which,
in the forenoon, was pretty open; but in the afternoon much shut up a long time,
and the heavens seemed like brass, and the gates thereof fastened as with bars of iron:
but waiting in patience and in sorrow, at length in his own time, which is ever the best,
the Lord came, who appeared of old, the doors being shut,
and who penetrates all things when he pleases,
and makes all opposition fly at the beckoning of his hand, though fortified by hell,
and secured with the chains and bars of death.
A little help from him altered the case,
and his presence gave life and ability to utter many good things out of his treasury,
to the general edification and consolation of the meeting,
and to his own praise who alone deserves it.

On the 1st of the fourth month I went to Durham, and the next day was at their meeting;
which was large and very open, many Friends being there from Sunderland.
Finding an inclination to see more of the town`'s people than were at that meeting,
I appointed another next day at two in the afternoon; where many of them came,
but were hard, dull, and drowsy; yet some of them more lively and attentive,
and some good and necessary things were opened to them.
But I had the least satisfaction in that meeting of any before,
and that afternoon was under some heaviness.

[.offset]
+++[+++Soon after, he returned to his lodgings at Carlisle,
and on the 30th of the second month, 1730,
again set out for the yearly meeting at Edinburgh--respecting which he says:]

On the 4th I went to Edinburgh, to William Miller`'s,
the yearly meeting there being on the first fourth-day of the month as usual.
It was held in the new meeting-house, which contained about six hundred,
and was every day full, and many in the yard.
They were not, for the greater part, a rude rabble, as formerly in that place,
but generally sober, reputable people;
and the truths of the gospel were plentifully opened, and with good authority.
The meeting held two days; and after it was over, I stayed until the first-day following,
in the mean time visiting the dean of Gild, a very sober religious person,
with whom I had some discourse, chiefly concerning the bread and wine, and the substance;
in which I had great satisfaction, and the rather,
that he also declared his in what passed among us on that subject.

On the second-day following, accompanied by Thomas Erskine, I went to Glasgow,
where we had a meeting the next day; which being in their new meeting-house,
was much larger, than heretofore, and very quiet and open,
many of the better sort being there.

On the 14th had two meetings, one in the forenoon, and the other in the after.
That in the forenoon was large, and in the main, quiet and open;
only as there came a great company of the collegians,
they were much ruder than any other of the baser sort;
which gave me some heavy reflections, that these seminaries of the members,
both of the national, or political, church and state,
should be more peculiarly depraved than the worst of the other rabble.
To see the good intentions of well-meaning
parents so cheated and eluded by the ignorance,
perfidiousness and idleness of those well-paid and over-paid teachers,
to whom the care of them and their education is committed, is lamentable.
For, alas! what but bitter and poisonous waters can be expected from such depraved fountains.

In the afternoon the meeting was large, with sober persons of the chief rank,
and the truths of the gospel in a good degree cleared among them;
and the meeting ended well, and in peace.
That which contributed not a little to our outward quiet,
was the care of the magistrates in sending civil officers to keep out the baser sort;
which we were favored with at every meeting; and was the first time,
so for as I have heard,
that ever any magistrates of that nation took any care
to preserve our meetings in peace that way.

On the 15th of the third month, being the sixth of the week, we returned to Edinburgh;
and the first-day following I was again at the meeting there;
which was the largest that had ever been in that place, and very open.
On the 18th I went for Kelso, accompanied by Joseph Miller;
and when we came to the inn at Channel-kirk,
we met with the marquis of Lothian and sir John Rutherford of Egerton.
They were very familiar and courteous, though strangers to us;
and as their company and attendants made a throng in the inn,
my companion and I could not be so well accommodated as otherwise we might;
which the marquis understanding,
he courteously sent us some of his own provisions which
his servants had brought for them.

I continued my progress to Justice-Town;
where I employed my time in my favorite amusement, of planting and improving my land,
and at the same time visiting meetings as they came of course,
and enjoying the conversation of my friends and neighbors, till the second month, 1731,
when I prepared for London.
On the 13th I went to the yearly meeting at Chesler;
which began about two in the afternoon for ministers and elders; and the next day,
the 14th, meetings for worship, both forenoon and after; which were very large and well,
we having the company of great part of the citizens, and many of the gentry round.
On the 10th, in the forenoon, was the meeting for conference,
and quarterly meeting for Cheshire, and in the afternoon, a meeting for worship;
where we had an audience of several thousands of people in a great tennis court,
many of them being of the more reputable sort, and among others,
seven ministers of the national church; who, as well as the people,
spoke well of the testimony of Truth which was delivered among them;
for which many Friends were thankful to the Lord our God,
who has wrought so great a change in the minds of the people, not only in this place,
but also in most places at this day throughout all Britain,
and the British dominions everywhere.

On the 19th we set forward for Shrewsbury, and on the 20th went to Ludlow,
where the yearly meeting for Wales was that year to be held,
and where there were no Friends, or any meeting for so long a time, if ever.
The first was held in the prince`'s palace, in a very large hall,
by the favor of captain Jones, the governor.
But the morning meeting being very much crowded,
the ministering Friends divided themselves in the afternoon,
and several held another meeting at the same time in a large room adjoining the hall;
and both were exceedingly crowded, and many could not set in at all.
The Lord was with us,
and the gospel was preached in his wisdom and power to general satisfaction.
Notwithstanding the great throng of people,
there was not any disturbance or disorder among them; for the magistrates,
to their just commendation, had taken great precaution, by making proclamation,
through the town beforehand, posting the same up in writing in the market,
or some public place, that if any should molest the meeting, or give any disturbance,
such should be severely punished.
Besides this encouragement, they appointed constables to attend the gates,
keep out children and rabble, and the meetings peaceable;
some of whom were very serviceable in the meetings,
in directing the people to convenient seats,
and placing them to the best advantage for general accommodation.
The meetings ended on the 22nd; and the next day I went with our friend Gabriel Smith,
to his house at Lempster, and we had a very open meeting with Friends,
and some others there, on the 24th.

On the 25th, being the first of the week, we returned with several Friends to Ludlow;
where notice had been given of two meetings that day; but the person who undertook it,
not doing it so certainly as it should have been, the morning meeting was not large;
but in the afternoon, the great hall was well filled with sober people,
to whom the gospel was yet more fully preached,
and was the most open meeting we had in the place; and so we left them in peace and love.
Returning that evening with Friends to Lempster, many of the people at Ludlow,
watching our departure out of the town, stood in companies on the sides of the streets,
to salute us with their civilities, as did many others in their doors and windows;
and we departed in peace, and in that humility wherewith the Truth adorns the mind,
being thankful to the Lord for his great favors;
his reducing magistracy to its proper use and end, a terror to evil-doers,
and praise and protection to them that do well, being none of the least,
considering how much our friends, and myself in some measure,
have suffered under magistrates of a persecuting spirit in former times.

On the 26th we went to Worcester, to the widow Pardoe`'s;
and the next day had a large and open meeting there;
many of those called gentry with military officers and others being present;
and the authority of Truth over all.
That evening we visited several families in town;
and next fourth-day had a meeting at Evesham; which was also open and well.
On the 29th we had a meeting at Cheltenham;
in which various important truths of the gospel were clearly, and with good authority,
opened and delivered.

On the 1st of the third month we went to Nailsworth,
and the day following had two meetings; which were very large and open:
that in the afternoon was the largest, some said, that ever had been known there,
many Presbyterians and Baptists being present; especially of the former,
and in the afternoon the matter of election and reprobation was fully handled and opened,
not knowing, till after the meeting, that so many of that sort were present.
The meeting was peaceable, and ended well.
On the 4th we had a small, but pretty open meeting at Tedbury; and next day at Dedmartin.
On the 6th we had a very open meeting at Bath; and we tarried till the 9th,
being the first of the week, and had two large meetings, and pretty open,
many strangers of account in the world being there.

On the 10th we went to Froom,
and the day following had two large and very open meetings among the general Baptists,
and others, in their meeting-house.
Having had a meeting in the same house many years ago,
as soon as they heard I was come to town, and desired such a meeting with them,
they readily granted us their house, and generally came to the meeting;
two of their teachers being there also.
On the 12th we went to Bradford, where we had a good meeting;
the truths of the gospel being clearly preached in the demonstration of the Spirit,
and power of Truth.
On the 14th went to the week-day meeting at Bristol;
where we stayed all the week following, it being the yearly meeting;
we had good times with both Friends and people, the meetings being very large and open,
and the kingdom of God fully preached.
On the 22nd I went back to Nailsworth, and was at their meeting next day;
which was large and open, but laborious,
by reason of the extreme heat and crowd of people.
The quarterly meeting being on the third-day following, I stayed;
where many things were opened, in the meeting for business,
concerning the discipline of the church, and the use and necessity of it;
against the payment of tithes;
and especially the hypocrisy and deceit of such as profess Truth,
in this present dispensation of it, and yet, by collusion and subtle practices,
evade the testimony, by dark, indirect, and underhand practices;
as if the Lord could not see,
though they may veil their own understandings by covetousness, or any other blind:
the faithful there had comfort and confirmation thereby.

On the 26th I went to the week-day meeting at Painswick, which was small;
but staying there next day, on occasion of a marriage,
the meeting-house was crowded with people;
and many important truths of the gospel were clearly, and with authority,
opened and preached among them, to the honor of Truth,
and comfort of those who desired the prosperity and spreading of it in the earth.
On the 29th I went to Warminster; and the day following, being the first of the week,
was at the meeting forenoon and afternoon.
The former was small, being few but Friends, and a little heavy at first,
but lively in the end.
That in the afternoon was filled with other people, and very open;
many truths of the gospel being published in
their audience with good authority and clearness;
and they departed in solidity, as if things had in some measure impressed them.

On the 31st I went to Sherburn, and the day after to Bridport,
and was at their meeting on fourth-day; which was small,
and something heavy in the beginning of it, but more open in the end.
On the 8th of the fourth month, accompanied by Samuel Bownas, then living at Bridport,
we had an appointed meeting in a barn at Kingham, belonging to William Smith,
about five miles from Bridport; where no meeting is settled,
and but one family of Friends there.
It was pretty large, though few Friends, and a good meeting.
The day following we had another appointed at Beaminster,
where there were but one Friend and his wife in town;
but a pretty large and open meeting.
On the 11th we went to Chard and had a small evening meeting there, and on the 13th,
being the first of the week, we were at Taunton, forenoon and afternoon;
the latter was large, and both well.

On the 14th, in the evening, we had a meeting at Creech.
It was very open; and a lawyer and his wife, and some others of the gentry, being there,
they stayed the evening with us, and were very sociable.
On the 15th we had a meeting at Bridgewater, which was very small;
for several of the Friends in that place,
who in time past had been in reputation as the chief among them, being trading men,
had fallen short in their business, and many had suffered loss by them;
so that the people were generally under offense by this means, and despised our meetings,
and neglected the Truth on that account; yet the meeting was open,
and the right-minded among them comforted.

On the 16th we went to Summerton,
and the day following were at the quarterly meeting there.
On the 20th, being the first of the week,
the meetings at Bridport were very large and open, especially in the afternoon;
which being put off till five o`'clock, was the largest, as some Friends supposed,
that ever had been in that place; and the important truths of the gospel were largely,
clearly, and with authority, opened among them; and Truth was over all.

On the 22nd, being the third of the week, was the yearly meeting at Pool;
and the next day the quarterly meeting; and that evening another meeting for worship;
when, the town`'s people coming in, it was the largest and most open.

On the 27th, being the first of the week, the meeting at Sarum being small in itself,
several of the neighborhood came in, and things opened well;
and the meeting being comfortable, we had much more company in the afternoon.
Some of the Baptists were so well satisfied, that two of them, of good understanding,
and honest, well-meaning men, came to John Moor`'s, where I lodged, after the meeting;
with whom I had conversation to edification.
They declared their satisfaction with the meeting;
but one of them still thought the bread and wine ought to be continued in the church;
but reasoned moderately:
and the other owned that I had given him more satisfaction
concerning the incarnation of the Word of God,
in some discourse I had had with him the day before,
than he ever had met with by word or writing.
We parted with good will on all-sides.

On the 4th of fifth month I went to Melksham meeting,
which was one of the most open I had in those parts;
the important truths of the gospel being opened in the wisdom and power of Truth,
to general satisfaction.
On the 6th I went to Bradford, where I had an evening meeting,
which was indifferently well, several of the neighbors being there, and very solid.
That night I lodged at John Ballard`'s; who went with me to Bath next day.
He was an attorney at law; and being convinced of Truth, made profession with us:
but the law being altered with respect to men of his practice,
and some new oaths required of them,
he had offered his affirmation according to the law made in our favor,
in matters of evidence; but judge Ayres, not being our friend, denied him that privilege;
which, it was generally held, the law and common right allowed him; since that practice,
being his way of livelihood and subsistence before that law was made, was no office,
or place of trust or profit in the government; which,
with serving on juries concerning life and death,
was all the exception in any of the Acts concerning the affirmation of Friends,
instead of oaths.

On the 9th I went to Bristol;
and on the first-day following had two full and open meetings;
though I never went to that city with less hope,
or more down in my mind than at that time; but on the third-day,
the meeting being larger than usual, was pretty generally reached,
and more of the young sort, of both sexes, tendered, than I have observed there,
or elsewhere, for a long time;
after which I was not so much laden in my spirit as before in that city;
where there is a great body of people under our profession;
who I hope will remain honorable in the Truth,
and increase in the power and virtue of it.
On the 14th I went to a monthly meeting for worship at Belton,
accompanied with Alexander Arscot, an honest and good warrior for Truth on earth,
against the anti-christian infidels of this present age.
We had the company of some Friends and others, to the number, in all,
of nearly forty persons; among whom I labored hard for some time;
but to what purpose I do not know: for,
though many important truths of the gospel were plainly opened,
I did not find any great impression made, nor was I very easy afterwards,
but rather under a kind of deadness; which, I fear,
is the state of too many people to whom we minister;
though several of them at that time seemed well satisfied with the meeting.

On the 21st I went to Frenchay, where we had a good open meeting;
the greatest part were young people,
there being several schools at that place for both sexes;
and that evening returned to Bristol; and the great fair approaching,
which is usually attended with a great concourse of people, I stayed till it was over.
There are, at this time, two great meetings of Friends at Bristol;
the greater part being young,
many of them are hardly distinguishable from the world by any outward appearance,
either in speech or habit;
but as people of all ranks and opinions now frequent our meetings everywhere,
they were very large and open on this occasion.
I stayed at that city till the 4th of the sixth month,
and then went to the week-day meeting at Sidbury,
accompanied by my old friend and acquaintance, Richard Champion, and his son; where,
though a small meeting, by reason of the prevalence of the small-pox in the place,
and harvest, yet a comfortable time the Lord gave us.

+++[+++After several other meetings, he says;]
On the 14th I went to Oxford; but soon after I arrived,
my mind became laden with that power of gross darkness, that may be felt,
constantly attending and prevailing in that seat of wisdom and subtlety, but not of God.

Next day, being the first of the week,
in the meeting it remained heavy and dark a considerable time,
till the never failing Truth arose and dispersed it; and then,
being over all evil spirits, I stood up, and many things were opened of great importance,
without any disturbance by the scholars, many of whom were there,
but not altogether so rude as at times heretofore,
or even the preceding first-day meeting; for, of all places wherever I have been,
these scholars of Oxford were the rudest, most giddy and unruly rabble,
and most mischievous.
But having got over them in the forenoon, the way was easier in the afternoon;
and having matter of importance to deliver, and with full authority,
several of them were affected, and all chained.

On the 29th I was at Nottingham meeting, which was not large in the forenoon;
but much fuller in the afternoon by the coming in of many of several sects, as Baptists,
Presbyterians, Episcopalians, etc.
But one Joshua Par, who had been denied by Friends, gave some disturbance to the meeting;
which was customary with him.
His father had been convinced, and was hopeful for a time, but declined at last; and,
as I remember, had been denied.
This Joshua was likewise hopeful, till he undertook to preach in our meetings,
which being in a confused manner, Friends could not receive him as a minister;
and continuing to impose himself, and becoming very turbulent and insolent,
they denied him as a member; on which he became an open enemy.
He began to accuse the meeting in a little time, calling them hypocrites,
and other ill names, after the manner of the Ranters.
William Thompson opposed him; and a constable appearing, he was daunted a little,
and became silent.
Then I had the time of the meeting; and things were pretty well.

In the afternoon he came again, and acted in like manner;
and pretending to pray in the meeting, the constable then came to take him away;
but he refused, pretending he had not broken any law; which was not true;
for disturbance of our meetings is against the Toleration Act.
William Thompson bid the constable let him alone, if he would be quiet,
and give no disturbance; which he did:
and a little after I began to speak on several important truths of the gospel.
The meeting was open and well:
but having said something concerning civil government
as an ordinance of God for the punishment of evil-doers,
etc., he took that as if intended against him;
and came to my lodging to wrangle about it.
I said not much to him; for the little I did say he could not bear,
being full of himself, and pouring out his resentments;
which gave me occasion to tell him, he was deaf and blind, he could not hear what I said,
or see the truth of it.
I told him he was a Ranter; that I had seen many such in America,
and some of late in Cumberland; that he was of the same spirit and practice,
speaking after the same foolish and blasphemous manner as they did;
and advised him to decline that way, and forbear to disturb our meetings any more.
He began to fleer, scoff, and giggle; for which, I reproving him,
he pretended that whenever he felt the comfortable presence of
the Lord to support him against his opposers,
he then could not forbear laughing.
This was a special note of the Ranters;
for they pretended that God had taken up their souls unto himself,
and possessed their bodies, and he being under no law but his own will, could do no evil;
therefore all those actions they did, they imputed to God,
though ever so foolish and wicked.

On the 30th I went to Mansfield, and on the 3rd had a meeting there; and when I went in,
found this Joshua Par in the gallery.
He was not long silent, but began to accuse Friends there as hypocrites; saying also,
"`Men gather not grapes of thorns, nor figs of thistles.`"
Then Richard Marriot, one of that meeting, replied, "`You are a thistle;
you bring forth ill fruits, by which you are known.`"
Another Friend went out quietly, and brought in a constable,
who was followed by some of the town`'s people; and as soon as Joshua Par saw them,
he sat silent; and the constable and neighbors staying,
we had an open comfortable meeting.
That afternoon I went on to Balberhall, to sir John Rhodes`', and there stayed two nights;
and on the 2nd of the seventh month, being the fifth of the week,
I went with him to the meeting at Chesterfield.

Next day I went to visit the widow Elizabeth Heathcoate and children at Cuthorp,
where I stayed two nights; and on the first-day following was at the same meeting.
It consisted for the greater part of Friends in the forenoon, and pretty open;
but having requested Friends in the place to invite the neighbors in the afternoon,
the meeting was much larger, and very open;
the important truths of the gospel being with good authority preached among them.

On the 9th I was at a monthly meeting at Burton; which was small, but very comfort, able;
and the next day at Woodhouse, the village adjacent, which consisted,
for the greatest part, of Friends, and pretty open; though it is observable,
in these days, that our meetings are generally brightest and most open,
and the necessary truths of the gospel most clearly and powerfully opened,
where the people are invited by Friends, and come freely in;
whereby Friends themselves become further informed and edified.

On the 15th I was at Halifax; where the meeting was small,
none but Friends being present, and few of them.
On the 16th I went to Bradford, and the day following had a meeting there;
which consisted mostly of Friends, and was large and open.
But having a mind to see the people,
Friends ordered their new meeting-house--not being fully finished --
to be tilted up as well as could be for that occasion;
and notice being given in town, and some adjacent parts of the country,
we had a large meeting the first-day following; and the people being sober and attentive,
the Lord opened things to them with authority and clearness;
and many of them seemed well affected with what they heard and felt.

On the 29th and 30th was the quarterly meeting at York;
where the envy and ill contrivance of some priests of
the national church fell under consideration.
The case was this: It had been falsely reported to some meeting of priests at London,
that Friends of the north, especially in Yorkshire,
had been very industrious in spreading and promoting
the blasphemous and anti-christian books,
published of late by Woolston;
and the bishop of Lichfield and Coventry having
written two volumes in answer to Woolston,
took occasion therein to vent his spleen against us; designing, but with no truth,
to put us on the same foundation with him, the Familists, and other heterodox persons,
as deniers of the outward coming of Christ, and despisers of the holy Scriptures,
the old, thread-bare, false charges of little credit at this day,
if at all believed even by these mercenary hirelings and scribblers themselves.
Yet, to obviate the hurt that some weak and credulous
persons might sustain by our silence to those charges,
the meeting extracted some paragraphs out of our yearly meeting epistles,
from the year 1706, to this year 1731,
containing earnest and repeated advice to
Friends everywhere to read the holy Scriptures,
and wait upon the Lord for his help in understanding them; and also not to read,
or allow to be read in their families, any books of deists, plays, romances, etc.,
tending to the discredit of the holy Scriptures, and contrary to the Christian religion.
These extracts the meeting committed to the care of several to be printed and published,
with a short introduction;
which resulting to the particular care of Roger Shackleton of York and myself,
it was accordingly printed at York,
and published there the 4th of the eighth month following.

At York I stayed till the 3rd of the eighth month, being the first-day of the week;
when the meeting was very large in the afternoon, chiefly with strangers,
for the meeting of itself is but small, and many truths of the gospel were freely opened;
and for anything I could observe, well received by the auditory;
which consisted in the main of reputable people.
The next day I stayed at York to see the printed extracts finished,
and on the 6th went toward Northallerton, and was at their meeting on the 7th,
which was very open and comfortable.

+++[+++After attending several other meetings he reached his home at Carlisle on the 25th.]
I stayed at and about Carlisle till the 30th of the sixth month, 1732;
when I went to York, and on the first of the week, was at the meetings there,
both forenoon and after; which were very open.

On the 5th of the seventh month I called at Castle-Howard,
and dined with the earl of Carlisle and his family;
the lord Cornbury being likewise there.
About the conclusion of our dinner, the earl, in a frank manner,
moved some discourse about the ceremonies of the national church,
and asked me if we would join with them,
in case they would lay aside the surplice and sign of the cross in baptism?

I answered, "`Lay these things aside, and then we will confer with you about the rest.`"
Then said the earl, "`These things are no way essential to religion,
and may well be spared; and we have no foundation in Scripture for them,
and some other things we use.`"
Then said his chaplain,
"`Things innocent in their own nature may be enjoined by the church and the legislature;
and from there arises a duty to obedience.`"
The earl replied, "`Whatever is invented and imposed by man, in matters of religion,
more than was ordained by Christ, and taught by him and his apostles, is vicious,
and ought not to be regarded;`" (a noble confession!)
and dismissed his chaplain with a frown,
while I was asking him this question,
"`When and where did the Lord Jesus ever give power to any temporal prince or state,
to add to, alter, or diminish, the religion he himself established on the earth?
Is not he all-sufficient in himself for that, without the direction, concurrence,
or aid of any other power, since all power in heaven and earth is given unto him?`"
The chaplain departing the room, I requested liberty of the earl for a few words further,
that since he had been pleased to mention their baptism, and object to an incident of it,
as now used by them, I hoped it would not be illy resented,
if I endeavored to inform him how we understood the Christian baptism;
and having his countenance therein, I proceeded.

+++[+++To the remarks made on the subject]
neither of the lords made any reply; but after a short pause,
entered into some discourse between themselves,
concerning the meaning of John the Baptist, when he sent two of his disciples to Christ,
to ask whether he was the Messiah,
after he had so fully before owned and declared him to be so.
They could not at first think the same way about his meaning;
one supposing he doubted under the temptation of persecution and imprisonment:
but that instance being advanced, where Christ, speaking to the Father, says, "`Father,
I knew that you hearest me always: but because of the people which stand by, I said it,
that they may believe that you have sent me;`" it was then concluded,
that the message from John was not for his own sake, or as doubting concerning Christ;
but for the sake of his disciples, and others,
for their further information and establishment in the faith of Christ:
and so the conversation ended.
Then I took leave; but the earl, though weak in his limbs, by a late fit of the gout,
went before me to the head of the stairs, and standing there a while,
professed his good liking to Friends, as a religious, useful people,
and good commonwealth`'s men; and wished his tenants were all of our way.

On the 7th I had an open comfortable meeting at Pickering;
and that afternoon went to Scarborough.
On the 8th I was at their weekday meeting; which,
though in the season for drinking the Spa water there,
and many strangers remaining in town, was small and select, consisting of Friends only;
but open and edifying.

The 10th, being the first of the week, the meeting was not large in the morning,
few strangers coming in, and my exercise a little heavy:
but in the afternoon many accompanied us,
and the truths of the gospel were preached among them with clearness and authority;
and then I was much easier and satisfied for that time:
for the whole meeting continued under a solid quietude a
considerable time after all outward exercise was over;
and they seemed rather unwilling to depart than hasty.

On the 14th I went to Whitby;
and had an open and solid meeting with Friends there the day after,
and came back to Scarborough, and on the first of the week, I was again at their meeting;
which was large and open, especially in the afternoon;
when we had the company of many strangers of the better sort.

On the 22nd I went to Newton, to Robert Milner`'s,
in whose house we had a meeting the next day in the evening;
and though no Friends were present, except his family, we had an open time,
the truths of the gospel being suitably opened to the state of the people.

On the 24th, being the first of the week, I went to Mallon; and the people having notice,
many came to the meeting; which was large, and the most important truths,
relating to the salvation both of Jews and Gentiles, plainly, and with full authority,
opened to them; which, by a close attention, many seemed to favor; and I hope,
some good was done among them that day.
On the 25th I went to York, in order for the quarterly meeting.
It was not large, but very comfortable:
but as few of the people came in during the time of worship, and I desiring to see them,
stayed there till the 1st of the eighth month; when, in the evening,
the great meeting-house was filled, so that several could not get in:
and the multitude being generally quiet and attentive, I had a free open time among them,
to the satisfaction of Friends, and I believe the people in general.
I went next day to Leeds, to my old friend Benjamin Horner`'s;
where I have ever been easy, finding the Son of peace there:
and the fourth-day following, being their week-day meeting,
I had a free and comfortable time with Friends.

On the 7th I returned to Leeds; and next day was at their meetings,
both forenoon and after.
The latter being attended with many of the neighborhood, was a good meeting,
as that in the forenoon also was, though not so large,
the gospel of the kingdom of God being fully preached unto them;
to which many seemed to assent by their sobriety and attention.
On the 10th I went to Bradford, and the next day,
had a very open and satisfactory meeting;
where several of the chief people of the town were present, and very attentive.
On the 13th we had an appointed meeting at Bridgehouse, which was not large,
being very wet weather and windy; but an open comfortable meeting.
On the 20th a meeting being appointed at Meadop, near Pennyston, I went there;
and the Lord gave us a good time in his holy presence.
That evening I went to Sheffield, and lodged at Thomas Buck`'s;
where I stayed till the 22nd, being the first of the week, and was at their meeting there;
and some of the most important truths of the gospel were opened with authority and
clearness, and I think, to general satisfaction.

On the 23rd I went to Dronefield, and the day after had a small, but open meeting there.
Next day I was at Woodhouse meeting; which was small,
and not so open as I could have desired; yet the Lord was with us, and owned us;
and that is sufficient at all times.
No notice having been given to the town`'s people,
and I having an inclination to see them, communicated it to the elders of the meeting;
who readily concurred with me to have another meeting, and notice given;
which accordingly was held on the 27th. Many of the people came,
and some from other villages; and the Lord gave us a free and open time,
and the people were generally satisfied;
only I heard of one who was not pleased to hear of any other baptism but sprinkling,
the baptism of the Holy Spirit being at that time recommended to their consideration.

On the 29th, being the first of the week, I was again at the meeting at Dronefieid,
that of Chesterfield likewise meeting with them that day of course;
and the Lord gave us an open, powerful, and comfortable meeting,
matters of the greatest importance being opened among us.

On the 31st I went to Chesterfield, to Joseph Storr`'s,
and that evening had the largest meeting ever known there;
for I had desired the Friends to give notice to the people,
that a stranger desired to see them; and though it was a mixed multitude,
the Lord was pleased to own us,
and open the doctrine and truths of the gospel with clearness and authority;
which seemed to affect many of the auditory, being generally still though much crowded,
and many without: the effects whereof must be left to the Lord,
of whom is the power and wisdom, and to whom be the glory of all his works.

On the 1st of the ninth month I went to Bather-Hall,
to see my worthy friend and old acquaintance, sir John Rhodes,
who had embraced the Truth early in his youth, under great self-denial;
in which he had continued, and holds his integrity unto this day,
and without doubt will to the end: and then an unspeakable overbalance,
to all the honor and pleasure he has, for the cross of Christ, sacrificed in this world,
will he meet with in that which is to come, never ending, and without change,
but from glory to glory forever.
Here I stayed in open friendship with him till the 4th;
which being the seventh of the week, and no meeting near, I went forward to Mansfield,
to Richard Marriot`'s, and was at their meeting next day; which,
though small in the forenoon, was open and comfortable; and in the afternoon,
many of the neighborhood coming, I had a full time,
and suitable matter given me among them:
and an ancient Friend departing this life while I was there,
I stayed to attend the service at his interment.
The meeting was the largest that had been known there,
with a mixed multitude of all sorts.
The Truth was preached to them in terms suitable to their states;
and they were much more sober and attentive than could
have been expected from their first appearance,
many of them looking wild and airy; which gave me occasion to think,
what good do their parents do them, and where is the care of parents to be seen?
But he that commands the winds, and stills the raging waves of the sea,
calms the most turbulent spirits, by his invisible word,
working effects visible and surprising.
The meeting ended in peace, and in all appearance, to general satisfaction.

On the 15th I was at a meeting appointed at Harborough; which was very small,
but very comfortable, the Lord delighting more to visit a few right-minded,
than many thousands of the rebellious and unfaithful.

+++[+++Attending a number of meetings by the way, he reached London the 7th of the tenth month,
1732, and says:]
At this time deism was much advanced in the city and nation,
and the former zeal of all sects nearly expired;
yet our meetings were much crowded on first-days:
and though the generality of Friends in the city were young people,
they delighted to hear the principles and doctrines of
Truth published with authority and demonstration;
of which the Lord was pleased to furnish me, in good measure, for his holy name`'s sake,
and the help of his people; though I boast not but of his mercy only.
I was frequently concerned to distinguish between a natural and spiritual state.
In the former, man has the use of his reason and understanding in natural things,
receiving all his ideas thereof from without by his senses within him,
and making a judgment according to the ability of his natural faculties,
deducing consequences from premises, by ratiocination:
by which he may rationally conclude the existence of the Almighty,
from his work of the creation, cognizable, in some measure, by the senses;
but cannot form any proper idea of the enjoyment of God, from the works of creation.

But in the spiritual state, whereinto man is brought,
not by any natural ability or effort, but by the word or Spirit of God;
by which he operates in and upon the natural man, as upon the dust of the earth,
and works in his spiritual senses, whereby he is capacitated to enjoy God,
as he is essential love, wisdom, truth, power, etc., through Christ;
who presents in the mind of the spiritual man every proper idea of God,
necessary to the complete happiness of man,
and admiration and adoration of the divine Majesty, now and forever.

The essential Truth, Christ Jesus, by the emanation of his own divine light,
exhibits these in the mind by divine intuition,
even as the sun in the firmament of heaven exhibits
himself to the natural man by his own light,
immediately, without any reasoning.

One day during my stay in the city, I, with some other Friends,
fell in company with a deist occasionally, at a Friend`'s house;
and something being moved relating to his principles,
he was furnished with various subtle arguments in opposition to the Christian religion;
which yet had no weight with us; and one of the company, to bring him, in some respect,
under the authority of the Holy Scriptures, asked him,
if he did believe what was written therein?
He answered equivocally, that he did believe many things therein, but not all.
However, he soon after urged the apostle Paul`'s doctrine in his epistle to the Romans,
in defense of their position,
"`That the reason of man is his only guide in the way to please God,
and the only principle by which man can apprehend there is a God; for,
says that Scripture, '`That which may be known of God is manifest in them (men);
for God has showed it unto them.
For the invisible things of him from the creation of the world are clearly seen,
being understood by the things that are made, even his eternal power and Godhead;
so that they are without excuse.`'
I replied, "`That man, taking in the idea of the outward creation by his senses,
and reasoning from the effect to the cause, may conclude, and cannot avoid it,
that there is an Almighty all-wise Agent, who has produced and supports all things;
and that he has all the divine and moral attributes commonly ascribed;
and that a great satisfaction may arise from a reasonable contemplation that way:
and yet all this is, in comparison, but a history or report of God, though forever true,
and gives not the enjoyment of his presence sensibly as
he is divine essential Truth and love,
wisdom, light and power; as which, he cannot be known but by his own light,
flowing from himself, through Christ; through which, as through a veil,
man sees the inaccessible glory of the Father, who dwells in the light,
which no man has seen, or can see by any other medium; and not by that,
till due qualifications be wrought in the mind by the power dwelling in that light,
which shines in the mind of the natural reasonable man, though he, as such only,
cannot comprehend it.`"

I added to this, "`That the divine light of Truth, or Spirit of Christ,
is another thing than human reason; and is superadded to the rational man,
after he is already rational; and is not a constituent of his being, as is his reason:
and instanced Cornelius, who was not only a rational man, but also a devout man,
and one that feared God, with all his house; who gave much alms,
and prayed to God always; and whose prayers and alms went up as a memorial before God.
Yet it was needful that an apostle of Christ should tell him what he ought to do further;
that is, to receive the word, anointing, or Holy Ghost; which believing,
he did accordingly receive it.
This is the Spirit of Truth, and leads into all truth relating to the spiritual world,
and the things thereof.
This human reason can never do, receiving all its ideas from without, concerning natural,
no even spiritual, things;
whereas the knowledge of things spiritual is conceived
in the mind from the Spirit of Truth within;
and those things exhibit their own ideas after their kind and nature, to the mind,
as outward things exhibit their ideas, after their sort, to the senses,
by sensible intuition, and not by reasoning.`"
These things seeming, at that time, to take some hold of the mind of this person,
I recommended them to his further consideration; and he said, he would examine them:
but I have not seen him since.

Having visited all the meetings at London, and one at Croydon, and being easy,
for the present, concerning them,
I set forward for the north on the 2nd day of the twelfth month;
but went no further than Tottenham; and the next day to Hartford.
On the 4th, being the first of the week, I was at the meeting there,
which was large and open, especially in the afternoon; and the next day, in the evening,
we had a pretty good meeting at Hitching.

On the 8th I had an open meeting at Sherington.
On the 9th, in the evening, at Bugbrook; many of the town`'s people,
and of a neighboring village being there, and on the 10th I went to Coventry,
and the day following was at their meeting; which was large and open,
especially in the afternoon.
That evening I had the satisfaction of the company of many Friends, and among others,
of Josiah Forster, author of a treatise lately printed, styled,
A Vindication of the Doctrine of Baptism; a worthy performance.

On 12th I went to Birmingham, and lodged at John Pemberton`'s,
and the day after had a meeting there; which was not large,
by reason of an epidemical distemper then in town, but a good meeting.
On the 15th I went forward to Leek, and the evening following had a meeting there,
the largest, as was reported, ever seen there:
for notice had been given in the daytime before, and the town`'s people came freely,
and were generally very sober and attentive;
and things opened freely with authority and demonstration.
On the 17th I went forward to Stockport,
where I met with our ancient and honorable friend Benjamin Bangs, who lived in that town.
It being the first of the week, I was at their meetings;
that in the afternoon being put off till the evening, was larger than the former;
and indifferently well and open.

On the 19th I went to Manchester; and the next day, in the evening,
had a meeting at a farm-house belonging to a Friend;
where we had the company of many country people, who were very sober;
and things opened well among them to general satisfaction.
That night returning to Manchester, we had a meeting next day there;
and the town`'s people having notice, many of the first rank came to it;
and the Lord favored us with suitable matter and an open time.
There being a burial on the 22nd, we had the company of many more; and things were well,
through that grace which tails not those who trust therein, and attend to its virtue.
Here I tarried till the 24th, and then went to Preston; where the meeting is small,
but was at it the next day, being the first of the week.

On the 1st of the first month, 1733, I went to Kendal, to Thomas Ellwood`'s,
and was at their monthly meeting the day after; which was large and open,
and the business thereof managed in the peaceable wisdom of Truth;
and a comfortable time the Lord gave us.
This being the sixth-day of the week, I stayed till the first of the next,
when the morning meeting was large, consisting for the most part of Friends;
and the truths of the gospel were opened clearly, and with tendering authority,
persuading the youth not to rest in the outside of things only,
in a formal exercise of those things left by example, by those who are gone before;
but to wait for the same word of wisdom and power in themselves,
as their conductor also in the same things in their day.
Several of them were tendered and broken;
and we were favored of the Lord with his presence, and comforted together in him.
The afternoon meeting was put off, at my request, till between four and five;
when came a multitude of all sorts, and several of the magistrates,
and generally sedate and attentive, and many things relating to the kingdom of God,
were opened among them with good authority and demonstration;
especially concerning regeneration, the difference between a natural and spiritual state,
and the necessity of a real and sensible change; and I believe, to general satisfaction.
I had thanks from one of the justices for my good instructions,
as he was pleased to call it: but that is a thing of course among themselves.
However, it was much better than being sent into a dungeon for it;
which was often the portion of those who made way in times past, by their sufferings,
for this liberty, and whose memory ought to be retained with great respect;
though some at this day, under the same profession, and enjoying that liberty,
despise and trample upon the most essential part of their testimony,
as also most of the incidents and exterior marks of distinction between us and the world:
for such incidents there are, besides a holy life and moral decorum among men.
Passing that evening in agreeable conversation with some select friends,
I went next to Penrith; and the day after that to my usual lodging at Carlisle.

Having settled some concerns I had in the country,
went to Kendal on the 9th of the second month, in order for the yearly meeting there;
which was very large, consisting for the most part, of young people;
as do our Society throughout the world at this day.
We were favored with the divine presence in some degree,
but not so gloriously as I have experienced:
for the state of the people could not bear it;
the generality of them being as the Samaritans of old.
They believed that Jesus Christ was the Messiah that was to come;
and so far they were right: but the Holy Spirit of Christ was not,
for some time after they had so believed, come upon any of them.
And so likewise these our younger sort of Friends,
having believed the same things concerning the coming of Christ in that administration,
as also the general doctrines published among us at this day, of his light, grace,
or Holy Spirit; yet the Spirit himself is not fallen upon many of them,
as a sensible and experimental dispensation of life and power;
which is properly the gospel; and the former is rather previous and introductory.
The meetings held three days; and the last being in the afternoon,
two large galleries were left open for people of the town, and other strangers;
and many of them were there.
The meeting concluded well, to edification and satisfaction,
to the praise of the Holy One, who never wearies or fails to do good to his people.

Here I stayed till the 14th; and that evening went to Richard Willan`'s near Sedbergh;
and next day, being the first of the week, was at their meeting;
which was very open and tender,
and several of the people there well satisfied concerning the way of Truth.

On the 18th I fell in with a general meeting of Friends at Raby;
where came also some few strangers; and the Lord gave us an open and comfortable time.

On the 19th we went to Durham, where I appointed a meeting next day; which,
though not large, was very open, several men of the law and other strangers being there;
and Robert Wardel and his wife being there from Auckland that morning,
we went together to Lancelot Wardel`'s, at Barns, that evening;
where we found him in a low condition of health,
and his house-keeper under the hands of physicians, but her death not feared;
yet about the second hour next morning, she departed this life;
which gave both surprise and great concern to the family.
Her distemper being a rash-fever,
they interred the corpse on the 22nd in the afternoon at Sunderland,
where we had the company of many of the neighborhood, and a good meeting;
many necessary truths of the gospel being opened to them.
It was the largest and most open meeting I ever was at there: but the day before,
being the seventh of the week, we had another meeting there,
on occasion of the interment of the corpse of another Friend,
where we had also the company of a good number of the neighbors;
whose report of this meeting had occasioned the crowd in that above mentioned.
The weather becoming very cold, with high winds and much rain, I rested at Sunderland,
and on the 25th went to Newcastle.

The next day their week-day meeting was very open, though small;
and being desirous to see Friends more generally together,
as also as many of the people as could be drawn, I stayed there till the 29th;
which being the first of the week, the meeting was not very large in the forenoon,
but comfortable,
through the divine presence of Him whose presence is
life to all that are favored with a sense of it in them;
but in the afternoon it was much larger by the company of other people, and very open;
the truths of the gospel being declared, the kingdom of Christ described,
and antichrist and his false church and priestcraft made manifest;
with some hints of his downfall and destruction,
by the brightness of the glory of the coming and manifestation of the Son of God,
Christ Jesus, the light of the world.

On the 30th I went to Haltwhistle, on my way towards Carlisle;
where I arrived the next day about noon,
and tarried there till the 4th of the third month following;
and then set forward for the yearly meeting at London.
It was, in the main, peaceable,
and the testimony of Truth further established against the payment of tithes;
which had been weakened by the unfaithfulness of several professors of Truth; who,
for the time, might have known better, and arrived at greater perfection.
And some members of the meeting offering subtle and
illusive apologies for delinquencies of this nature,
I put the meeting in mind,
that at a time of the greatest confusion and
distraction about matters of religion in this nation,
when all sects were imbruing their hands in one another`'s blood,
contrary both to the nature and end of the Christian religion, which they all professed,
but did not understand, the Lord, in infinite mercy,
stretched forth the arm of his power, by which he gathered to himself a royal priesthood,
a holy nation, a peculiar people; who, through the virtue and power of his grace,
bore a threefold testimony in the world.

1st; To the manifestation of the holy and powerful spirit of Christ,
as the only infallible and all-sufficient teacher of mankind,
in the things of God and eternal life.
2ndly; To a holy, innocent, righteous life,
as the natural and necessary consequence of such teaching.
3rdly; Against an anti-christian priestcraft and ministry,
set up and subsisting in the world, by tithes, and other oppressive means,
never appointed of God for a Christian ministry;
but invented and obtruded upon the world by the
subtletly and violence of an anti-christian power,
usurping authority, in the name of the Lord Jesus, whose kingdom is not of this world,
over all the kings and princes,
and moral establishments where Christ was named and owned.
In all which our primitives, in this dispensation, were true and faithful;
so that these three points were settled and held as essential
and indispensable to the dispensation of the Almighty
committed unto his people in this and all future ages.
So that none were from the beginning really accounted under that dispensation,
who came not up in the practice of them.
I therefore conclude that it is the same still, and ever will be;
and that the former yearly meetings, whose minutes on that behalf,
particularly about the payment of tithes, are now inspected and referred to,
did but their duty in distinguishing such as fall short
of the common testimony and dispensation,
from the faithful therein,
so far at least as to prohibit such from any share in the exercise of judgment,
or the application of the order and discipline of the church,
where themselves are subjects of just censure therein.
And it is written, "`The brother that is weak in the faith receive,
but not to doubtful disputations.`"
Many other remarks were made also by other Friends on the same account;
and the meeting concluded to have former minutes
against the payment of tithes transcribed,
and a written epistle prepared,
recommending faithfulness therein to the quarterly and monthly meetings;
which was done accordingly; and in which the meeting seemed generally unanimous.

I stayed in London some weeks after this, visiting the meetings there,
and at Croydon and Tottenham; and on the 3rd of the fifth month,
accompanied by my sure and esteemed friend Andrew Pitt, I went to Hartford;
and next day was at a yearly meeting there.
In the morning, till about the tenth hour,
we had a select meeting of ministers and elders;
where we were favored with the divine presence, in a good degree:
and then came on the other meeting, which was large and open;
and the Lord seasoned our minds together with the salt of the covenant of life.
The next day we went to Hitchin; where the week-day meeting was pretty large and open;
and went that evening to Baldock, and the day after were at their yearly meeting:
which was large, and indifferent well; and might have been better,
if a certain person had not entertained the auditory
too long with histories of the Old Testament writings,
reduced by her into songs, which she thought melodious; though others despised them,
as having no relation to the gospel of Christ; and canted in that manner.

On the 7th we went to Ware, and the next day, being the first of the week,
were at their meeting: which was one of the largest known there;
several strangers of account in town came in, and a door of utterance the Lord opened,
to general satisfaction, and gave us a comfortable time together.
On the 21st I went to Kingston, and the next day, being the first of the week,
was at the meeting there; which was large, by Friends from London, Croydon, Wandsworth,
Staines, and other places round, especially on occasion of a burial that day;
and we had an open and satisfactory meeting together; and the people,
many of whom were there, generally sober as Friends, and seemingly satisfied.
On the 23rd I went to Guildford, and had a meeting there; which was small,
but open and comfortable.
After the meeting I went to Alton, to Samuel Waring`'s;
and on the 25th was at their meeting: which was small,
the harvest in those parts being very throng about that time; but it was a good meeting.

On the 30th, accompanied by Samuel Waring, I went to Gosport,
and lodged at John Hooper`'s. He was not a Friend in profession, but a Presbyterian,
yet all his six children were Friends, and very honest; and he gave them liberty,
and entertained Friends freely at his house.
The day after we had a large open meeting at Portsmouth;
for though there are but few Friends, many others come to meetings,
and behave very decently; as they did that evening.
On the 1st of the sixth month we went to Southampton,
and that evening had a very open meeting; many of the neighbors being at it,
and the truths of the gospel clearly opened, and with good authority.

On the 2nd we had a small meeting at Rumsey with a few Friends;
which was very heavy a long time: but at last we were comforted together,
and the meeting ended well.
On the 3rd, in the evening, being the sixth of the week,
I had a pretty open meeting at Fordingbridge, and on the 5th,
being the first of the week, I was there again, where the meetings were large and open,
especially in the afternoon; many things were opened in the Truth,
and delivered to the people with good authority: for the testimony of Truth, at this day,
lies very much towards the people of this nation everywhere.

+++[+++After attending several other meetings he came
to Worcester on the 1st of the seventh month,
of which he says:]
There being several strangers in town,
the Friends appointed their meeting next day in the great meeting-house,
and gave notice to many of the inhabitants.
We had a largo open meeting in the forenoon, many of them being present;
and the time of the afternoon meeting being put off till three o`'clock,
we had a very great crowd of the more reputable part of the inhabitants,
and several of the aldermen and other magistrates;
some of our friends telling us afterwards, they had never known so full a meeting there,
but once at a yearly meeting.
That which fell to my share in this meeting was,
to open the nature of that called the Apostles`' Creed;
upon which I was enlarged and drawn out to expatiate with good authority and perspicuity.
Taking exceptions at that part, "`He descended into hell;`" I observed to them,
that Christ said to the thief upon the cross,
"`This day shall you be with me in paradise.`"
Upon which I put this question.
What was this you in the thief, and this me in the Lord Jesus,
to be that day in paradise, when the body of the thief was broken on the cross,
after the manner of criminals,
and the body of Christ laid dead in the sepulcher till the third day?
What then remained of Christ to go down into hell,
as he is already stated to be dead in the foregoing period, viz: "`Was crucified, dead,
and buried?`"
But since the persons composing that creed, long since the days of the apostles,
might bring it as near as they could to the tenor of the Scriptures;
and finding an expression in the psalms of David to this purpose,
"`You shall not leave my soul in hell,
nor allow your holy One to see corruption,`" they seem
to have misapplied it to Christ after his crucifixion.
Whereas it is properly applicable to him as stated in the time of prayer in the garden;
when, having the weight of his approaching sufferings,
and of the sins of all mankind upon him, being in an unspeakable agony,
grappling with death, hell, and the grave, in human nature,
the drops of sweat that came from his holy body, being, as it were,
like great drops of blood; and having overcome all these, he, the next day,
willingly laid down his life on the cross, in the will of the Father,
and from that time on triumphed over them all.

On the 3rd I went to Evesham, and on the 4th had a meeting appointed in the afternoon.
It consisted for the most part of Friends, few of the people of that place being there;
but very quiet and attentive;
and the Lord gave us an open and consolatory time of his goodness.
On the 5th I went to Tewksbury, and the day following was at their week-day meeting;
which was small, but open and edifying.

On the 7th I went to Cheltenham, where came people of various notions,
as of the national church, Presbyterians, Baptists, etc.,
and the Lord giving matter and utterance, as likewise consolation and ability;
we had an edifying meeting, well received by the people, and well spoken of after.
John Cadwalader, from Pennsylvania, was likewise there.
On the 8th I went to Nailsworth, and on the 9th, being the first of the week,
was at their meeting, which was large in the afternoon, but laborious.
Many of the people in those parts, and elsewhere, of various notions,
having been often at our meetings,
where the truths of the gospel have been clearly and powerfully declared,
and they secretly convinced, yet stumbling at the cross,
have not obeyed to an open confession of the Truth,
and therefore do not grow or come forward therein;
but become as seed buried under the clods of the earth, and in danger of perdition.
Yet Christ was clearly preached to them this day,
with respect as well to his inward as outward manifestation, and especially the former,
and with good authority;
and they were forewarned of the danger of neglecting the day of the offers of salvation,
and strivings of the Spirit of God in them; since his language, by the prophet of old,
to a rebellious, gainsaying, and negligent people, is thus, "`I called, says the Lord,
and you would not hear; you shall cry, and I will not answer:
I will laugh at your calamities, and mock when your fear comes.`"
Again, "`Today, if you will hear his voice, harden not your hearts,`" etc.

On the 14th I went to Marshfield, to the widow Wickham`'s, a good old matron,
and entertainer of Friends for many years, and that evening had a meeting there;
which was not large, but some of the sober neighbors coming in,
we were favored with an open and good time; and things were well and comfortable.

+++[+++After attending meetings at Bath, Bristol, Nailsworth, Calne, Devizes, etc., he says:]
On the 15th I went to visit my worthy and long acquainted friend, Alexander Kirton,
at Broughton-Mills; and the day following was at their week-day meeting,
about three miles from there; which was very small:
but a very comfortable time the Lord gave us together,
for our encouragement not to despise a few, but to remember and trust in the Lord,
who said, "`Wheresoever two or three of you are gathered together in my name,
there am I in the midst of you;`" of which we
were sensible witnesses in this little meeting.
On the 17th I went to Reading, and next day being the first of the week,
I was at the meeting there; which was large and open, especially in the afternoon:
for the meeting itself continuing large,
and the neighbors being informed by those who were at
the forenoon meeting what had passed there,
many more came in the afternoon, to our mutual satisfaction;
when the gospel was preached, and the poor heard it;
and who is rich but he whom the Lord endows.
On the 20th, being the third of the week, and one of their meeting days,
I was there again; and being more select to Friends,
the Lord gave us a memorable season of his good presence, to general satisfaction;
for which we were thankful to him, the Giver of every good and perfect gift.
On the 21st we had an evening meeting at Henley; which was very large,
many Presbyterians, and others of the neighborhood being there, and generally very sober;
and many truths of the gospel were proclaimed in their ears,
and some hearts touched with the virtue of it.
But the cross is still a stumbling block to many
professing the Christian name at this day;
mankind desiring heaven, when the report thereof seems beautiful,
but would part with nothing for it, and would still be heirs of two kingdoms; which,
in this sense, can never be.

On the 22nd I went to visit John Penn, son of William Penn, sen., at Fein,
about two miles from Maidenhead, where I met likewise with William Penn,
grandson of the said William Penn,
which I did not only for the personal respect I bore them,
as knowing them from their childhood, but in memory of so good an ancestor;
who took up the cross of Christ, and despised the shame, in his early days,
in view of high preferment in the world,
when the way of Truth was under the greatest contempt and persecution.
During my stay with them, we had a meeting on the 23rd in the evening at Maidenhead;
which was very small, but open and well.
On the 24th I went to Wickham, and on the 25th, being the first of the week,
I was at the meetings there, both forenoon and afternoon.
The latter was large and very open, many strangers being there;
and the goodness of the Lord was sensibly with us,
to the comfort and satisfaction of as many as were alive in the Lord;
and things opened well, and with power and clearness,
to the praise of him who works in all according to his good pleasure.

On the 27th had a meeting at Chesham; which was very open and comfortable,
the good presence of the Lord being sensibly with us.
That evening I went with Joseph Lovelace to his house, near Jordans;
and the next day had a very open meeting there; where the greatest part were Friends,
and divine love was not lacking to all the living.
On the 29th, being the fifth of the week, I went to the monthly meeting at Windsor,
which was very small; but some persons came out of the country,
who had not been at a meeting before, and others of the town coming in,
the Lord owned us, and gave us a good time together,
and many things were opened to edification and comfort.
In the evening went on to Batlersea, and so to London.

Having visited the meetings in London thoroughly,
I set forward for the north on the 23rd day of the first month, 1733-34;
was at two meetings next day at Albans, being the first of the week.
That in the afternoon being put off till four for the sake of the people, was very large,
and consisted of Friends, Episcopalians, Presbyterians and Baptists,
and perhaps some Papists;
and some truths of the gospel and kingdom of God were plainly opened among them;
during which there was a general quietude,
and several affected with the invisible word of Truth.

On the 27th we went forward to Dunchurch, and next day to Coventry,
and had a meeting there in the evening.
The assizes had been held there a day or two before,
and several malefactors capitally convicted; and among others, a priest,
for stealing a mare.
To whom, and to all in the court, the judge preached the doctrine of Truth,
and gave very good advice; more particularly to this poor condemned criminal;
to whom he said, That the sin was great in itself,
but much more aggravated and magnified in him; who,
pretending to be a minister of Christ,
ought to have been a good example and leader of
others in the way of righteousness and Truth;
but falling so greatly short himself of moral honesty,
he was become a reproach to his profession, and a stumbling block to the weak,
to whom he ought to have been a support.
That which was more particularly remarked in the judge was this,
that he told the criminal,
if he had taken due heed to the divine principle of grace and Truth in his own mind,
he would not have fallen into that sin,
which was now bringing him to so ignominious an end;
which had good effect on this and the other criminals, and also on the auditory;
some of whom said, the judge had preached a very good Quaker sermon.
Thus the Lord bears witness, by his divine Truth, against that which is evil,
by the temporal judges, through his divine light, when false teachers,
becoming criminals, are sentenced, as the reward of their evil deeds,
according to the laws of their native land; of which, as also of the sin against God,
and his neighbor, this poor unhappy priest could not be ignorant.

On the 1st of the second month we went to Stockport.
I had a comfortable time in that place in visiting the families of Friends;
and a marriage happening about five miles from there on the fifth-day following,
I was there.
The meeting was large;
and the Lord gave us a comfortable season in his blessed presence on that occasion.
There was justice Wright, with some other persons of distinction;
and he signed the marriage certificate as a witness, with many more.
On the 7th, being the first of the week, I had two open good meetings at Manchester,
to general satisfaction, so far as I could observe;
for some essential parts of the Christian faith, practice, hope, love and sufferings,
were laid open and made plain, in the light, virtue and power of the Son of God,
and many hearts tendered thereby.
Oa the 8th I went to Preston, and on the 9th to Lancaster, to R. Lawson`'s;
and that afternoon began the meeting of ministers and elders; which was well attended,
from various counties and places;
and we were favored with the good presence and counsel of the Lord.
The next day we had one meeting for worship in the forenoon, beginning about eight,
and another which began about the second hour afternoon; and both very large,
especially the latter, and consisted generally of Friends.
Many of the people there and thereaway resting
satisfied in their own national and dead forms,
lack nothing, being blind, naked, and dead to religion, or any need or inquiry after it;
though a few of them who did come in behaved very soberly,
and were attentive to what they heard; and a good meeting the Lord gave us,
through the revelation of the Father by the Son, who never fails nor forsakes his own,
whom in this age, as in times past, he has called and chosen, and fitted by his Word,
to bear the ensign of his great and awful name before the nations.
Things were carried on and ended well in this meeting.

On the 12th, being the sixth of the week, several Friends went here to Kendal;
where they had put off their week-day meeting till two in the afternoon,
expecting our company; and Thomas Erskine from Edinburgh being with us, and some others,
the Lord gave us a comfortable season of his life-giving presence together,
the public concern falling upon him and me; and the meeting was edified in love.

On the 14th, being the first of the week, we went to Sedberg meeting,
on the occasion of the burial of Richard Willan,
a Friend of good account and service in the country,
and his death generally lamented by all sorts and conditions of people who knew him.
There was a very great concourse of people;
to whom many truths of the gospel were opened,
the Lord favoring us with his good presence.

On the 19th I was at the monthly meeting at Carlisle,
where I gave Friends some short hints of my late journey;
and let them know I intended another soon after,
and to be at the approaching yearly meeting at London:
which the monthly meeting was pleased with,
since none had given up their names at the quarterly meeting, for the yearly meeting;
upon which the quarterly meeting had been adjourned,
in hope that some Friends would offer their service on that account.
After some further deliberations thereon,
seeing so general a backwardness in the quarterly meeting, they told me,
they hoped I would be at the adjourned quarterly meeting,
and agree to be one to represent them at the yearly meeting:
and as I intended to visit some other places after the yearly meeting was over,
the monthly meeting gave me another certificate; being a common order then among us,
to which all were alike subject, how well soever known in our Society,
to prevent disorderly persons and impostors.
On the 21st, being the first of the week, I was at the meeting at Carlisle;
which was very open and comfortable, several Friends from other meetings being there:
and on the 22nd I went to a farm I had in the country, to set some things in order there,
where I stayed till the 26th; and then returned to Carlisle,
and was at that meeting again on the 28th, being the first-day of the week;
which was likewise open and well, both forenoon and afternoon.

On the 2nd of the third month I was at the adjourned quarterly meeting held at Wigton;
where such business was finished as was before them;
but none offering for the service of the yearly meeting at London,
I acquainted the meeting of my intention of being there;
and then the meeting persuaded Jonathan Ostal
and David Hodgson to undertake the charge also.
That evening I returned to Carlisle.

+++[+++On his way to London he attended a meeting, of which he remarks:]
On the 16th I went to Macclesfield, to James Hobson`'s, and had a meeting with them;
which, though small, was very comfortable; where I remembered the promise,
"`Where two or three are gathered together in my name,
there am I in the midst of them:`" and some Presbyterians and Baptists being there,
they seemed surprised at the testimony of Truth,
which asserted the efficacy and spirituality of Christ`'s baptism,
and the insignificancy of water in this day of the gospel of life and power;
and the blasphemous falsehood of the Presbyterian predestination,
wherein the very being of the Most High is misrepresented, and all his attributes,
especially as he is full of love, and of infinite goodness and mercy:
and I was made to proclaim, with full authority,
that to charge the Lord with such an unmerciful decree as they talk of, is false,
and inconsistent with his divine nature and being.

The yearly meeting approaching, I attended the service incumbent;
and a peaceable time the Lord gave us,
though Satan was not lacking in his attempts to make division and mischief;
but through the wisdom and goodness of the Lord, was frustrated.
After-the meeting I stayed in the city, and near it,
visiting the meetings in their several turns, till the 14th of the sixth month: and then,
accompanied by my friend, John Fallowfield, we went that evening to Staines,
and next morning had a small meeting there, for they were then but few:
where the Lord favored us together with his good presence,
making good his ancient promise to his children and people.

+++[+++After being at Reading, Salisbury, Fordingbridge, etc., he says:]
On the 22nd we had a pretty large and open meeting at Ringwood, at Thomas Prichard`'s,
several of the Friends from Fordingbridge going with us.
Afterward we went to Pool, and the next day were at their weekday meeting.
There is at that place a good number of Friends, but for the most part young,
and not much experienced in the work of Truth; yet being in innocence,
and keeping to meetings, they are hopeful.
We labored among them, according to the ability given for the work of the day;
and the meeting was serviceable and comfortable.
Here we stayed till the 25th: and on the first-day of the week, were at their meeting;
which, in the morning, consisted generally of Friends;
and the Lord favored us with a good degree of his goodness together.
In the afternoon, the meeting being put off till four, and notice given,
we had a very great crowd, the house and all the galleries being filled,
and some could not get in.
The Lord furnished us with understanding and ability,
and the doctrine and virtue of the gospel reached many that day.
And though we were much drawn out to the people, in the labor of love and goodwill,
and much exhausted in the service, yet our reward was sure in the Lord,
and our satisfaction great in his divine presence; and the people were generally solid,
and not a light or airy countenance to be observed among them;
and for anything that appeared, generally satisfied.

On the 26th we went to Bridport, where we stayed till their week-day meeting.
It was small, consisting only of Friends; and we had the favor, in some degree,
of the sense of divine goodness among us.
Here we stayed till the 30th with our friend Samuel Bownas, an old fellow-laborer,
and able minister of the gospel,
in some desire of his company to the yearly meeting to be at Exeter the week following;
but he being taken ill, we were denied that satisfaction,
but were well refreshed there in their company and
families before we went forward towards Exeter,
which was on the 30th; and there, through the mercy of God, we arrived in the evening.

On the 1st of the seventh month began the circular yearly meeting for the west.
The Lord favored us with his good presence,
and many of the inhabitants of the city and neighboring places coming in,
and behaving very soberly,
the truths of the gospel were declared to them with
authority and demonstration by several of the ministry.
The meeting was peaceable and comfortable, and people generally satisfied,
for anything that appeared to the contrary.
The people throughout this nation, at this time,
are generally willing to give us a fair and peaceable hearing, and with good acceptance,
as to the truth of our doctrine; but the cross of Christ being yet too heavy for them,
as they weakly think, and finding ease and a false rest in death under their priests,
who soothe them in their sins, they yet rest short of the kingdom.
Nevertheless the spirit and power of persecution is greatly lessened
in this nation since the blessed Truth shined forth therein,
among our first Friends, in the dispensation thereof under the name of Quakers,
so called by the ignorant, dark, and blind world.

On the 4th, in the morning,
when I and my companion were ready to take horse for the west,
we had a message from Friends in the city, informing us,
that there was to be a marriage of two of our Friends there next day,
and that they expected many of the inhabitants would be present on the occasion,
and earnestly requested we might be there; which having duly considered,
we found freedom to stay, and we had the company of a good number of Friends,
and a great company of the inhabitants of the place.
The Lord was pleased to favor the occasion with his good presence,
and to furnish us with matter and strength suitable;
and we had a more satisfactory time than in the yearly meeting,
where sometimes we happen to be straitened by too many of the same order,
not all alike qualified for such services.

This stay altered our plans in point of time, which we had thought of for the west;
and being so near the first of the week,
and many of the inhabitants of the city being a little roused by the meetings aforesaid,
we tarried till then; when our meeting was more select in the morning:
but that in the afternoon being postponed till the third hour,
it was nearly as large as sometimes in the yearly meeting;
and the Lord furnishing us with understanding and authority,
some truths of the gospel and kingdom of God were declared with authority and clearness;
the auditory being very sober and attentive, and generally satisfied,
as we ourselves were in our service, having the reward of peace from the Lord;
not of debt, but of his mercy, goodness and bounty.

On the 9th we went to Totness, and Friends went to the mayor of the town,
and prevailed with him and the rest of the magistrates,
to let us have the town-hall for a meeting-place:
which accordingly was held there at the fourth hour afternoon next day.
A great crowd of the inhabitants came, and most of the more reputable sort,
several of the aldermen and their wives, and the like;
and a very full and comfortable time the Lord gave us among them,
exalting the testimony of his living Truth over all, to our very great satisfaction,
and general good liking of the auditory,
so far as we could collect from their sobriety and attention,
and what we were informed of as the sentiments of some of the more capable among them;
and we were favored with divine peace,
as a full recompense for the labor given us to perform by the word of the Lord,
in which we ministered.

On the 12th, being the fifth of the week, we went to Plymouth,
and had a pretty large open meeting there in the afternoon the day following;
and there rested till the first-day of the next week.
Contracting a very near acquaintance with several Friends here,
with whom I had not before been acquainted,
we spent the seventh-day in a very agreeable conversation among them;
and on the first-day had two meetings.
That in the morning was well furnished with Friends, and no small mixture of others;
and a good time the Lord gave us together:
but the meeting in the afternoon being put off till three, it was very large;
many of the more reputable part of the people of the town, of both sexes,
gave us their company to our mutual satisfaction.
The Lord favored his people with his living presence,
and opened the truths of his gospel, by us,
unto those who were not then come to the true faith of the Son of God,
according to the dispensation of it unto us, through the mercy of God, at this day;
and the multitude being very sober and attentive, and some of them apparently affected,
I hope there was some good wrought in them that day,
to the praise of him who works all in all.
That day I found myself under some indisposition of body; and in the night,
having been much exhausted in the meetings, it turned to an intermitting fever,
accompanied with a flux, whereby I could have no rest;
and the next morning I found myself extremely weakened in body,
and my natural spirits very low.
But trusting in the Lord, and using some means recommended, I recovered strength,
and about eleven next day set forward for Lowe; where we arrived that evening.

The distemper continuing, and aggravated by the journey, though not long,
I was very ill that night, and could not rest; by which I was more weakened than before:
yet my illness abating next morning, I went to the meeting;
where happened to be a marriage,
in which the Lord was pleased to favor us with his divine presence.
I was much comforted in silence, nothing being required of me further at that time,
the public concern falling on my companion John Fallowfield;
which he discharged to satisfaction.
I rested well that night, and found myself much stronger and better in the morning.
On the 18th we set forward for Foy, where we arrived about the middle of the day;
and about the first hour afternoon had a meeting there,
where there is no meeting of Friends: but we procured an unfinished large house,
which Friends who went with us, and some others who met us there,
got seated with planks for that particular service;
We had the company of a multitude of young people, especially of the female sex,
and some likewise of the other; but not many of the elder sort of either.
They were sober beyond expectation;
and I found myself concerned to lay before them the insignificancy
and invalidity of that which they call their baptism,
and the efficacy of the baptism of Christ,
and absolute necessity of it in order to their salvation;
with many other gospel truths then declared by me, my companion,
and also by our ancient friend Philip Deeble, who was then also with us from Foley.
We had no opposition; but I having told them they had no baptism at all,
but were deceived by their priests and teachers,
who told them they were already made members of Christ, children of God,
and inheritors of the kingdom of heaven, and no Truth in it,
it proved an amusement to several of them,
and gave occasion to much discourse and some debate among them.

On the 19th we were at the meeting at Austel, which was large and very open;
for of late many had been convinced of Truth in those parts, and very hopeful to stand;
to whom the doctrine of Truth, in the divine life of it, freely flowed that day;
and a comfortable time the Lord gave us together in his blessed presence.
On the 22nd, being the first of the week, we were at the meeting at Penryn;
which was select of Friends in the forenoon,
but more company of the neighborhood in the afternoon: and these meetings were peaceable,
and pretty open.

On the 24th we had an appointed meeting at Come-to-good, about five miles from Falmouth.
It was a small meeting; but there being several newly convinced persons there,
the Lord favored us with some degree of his blessed presence.

On the 25th we had a very open meeting at Falmouth; where,
having the company of a goad number of the more reputable sort of people, with Friends,
the Lord favored us together with his goodness:
and the truths of the glorious gospel were largely, clearly, and with divine authority,
published there; to the admiration of several, who were much affected,
and the general satisfaction of all; to the glory of God,
and the arm of his divine power, then made bare among us.
On the 26th we set forward for Marazion, and on the 27th we had a meeting there,
consisting of a few Friends and of those of Penzance, about sixteen or eighteen in all;
yet, though few, the Lord remembered his gracious promise of old,
and comforted us together in his good presence; for which we were thankful.

On the 29th, being the first of the week, we were at Landsend meeting; which was large,
many not being able to get in.
They are generally a people of low capacity;
yet matters suitable to their conditions opened freely:
but new wine is not put into old bottles.
Most of them had not yet believed in the Truth,
and therefore not sanctified through faith in him;
so that the efflux of the living water was not so plentiful,
nor the wine of the kingdom so strongly mingled therewith, as at some other places;
yet sufficient of both to give a clear evidence:
and in the main the Lord gave us a comfortable season of his good presence,
and magnified his own arm.

Returning next day to Falmouth, I stayed till the 2nd of the eighth month,
being the fourth of the week;
where we were favored with the company of some of the sober reputable neighbors;
and the Lord gave us a memorable time among them,
in the wisdom and authority of the divine Truth,
to the surprise and admiration of several persons,
who had been but little acquainted with our meetings.
For this I was fully thankful to him without whom we can do nothing.

On the 4th we had a meeting at Mevagissey; but being a very stormy time of wind and rain,
and the place a fisher-town, the people were employed in saving their vessels:
by which the meeting was small, yet very satisfactory,
through the presence of Him whose promise is ever good to the two or three,
in what time and place soever assembled in his holy name;
and we were much comforted here.

On the 6th were at the meeting at Dennis, among an innocent people,
many of them (about forty) lately convinced, being very tender,
as little children desiring the pure milk of the Word;
and the Lord dispensed it largely and freely among them,
to our solid and mutual satisfaction.
They were greatly tendered, as we had been when we were first convinced;
which gave me a grateful remembrance of those days of espousal,
and hopes that the renewing of such times in a more general way, is not far off;
such being now, in various parts of the world,
as a few first-ripe ears proclaiming the approaching harvest; as it is written,
"`Seed-time and harvest, summer and winter, day and night, shall not cease.`"
The dispensations of the Almighty unto mankind, though various, shall not cease,
from henceforward forever.
On the 8th, being the third of the week, had an appointed meeting at Cullom-major:
it was in the town-hall, where came a mixed multitude of people;
and being of high-church principles, if they may be called principles of religion,
many of them were very rude and foolish; yet,
there being some wheat among much straw and chaff, the Lord had regard to us and them,
in some degree, and gave us suitable things to minister to them.
I had to put them in mind, that what they call their baptism is no ordinance of God,
nor was it ever practiced in the church of Christ, but of antichrist;
nor is there any foundation in holy Writ for godfathers, the sign of the cross,
or such promises and vows as they have made to God, and have not kept them;
by which they are really and indeed miserable sinners, and under condemnation.
By their behavior and conduct they seemed only to make
a jest of things of the greatest importance,
and not at all to understand what they were about,
professing the sacred Christian religion,
to which their rudeness proclaimed they were yet strangers.
I directed them to the Spirit of God, and his divine light,
as the only sure teacher in their own minds;
and by which they could be enabled to keep and perform
those vows they had made before God and man.
They grew a little tamer before we had done, and we came away easy.

On the 9th we went to Port-Isaac, on the north-side; and the same evening had a small,
but open meeting, with the few Friends there, and two or three sober neighbors.

On the 10th we went to Liskard.
On the 11th had a meeting there;
where we had the company of our ancient friend Philip Deeble,
and some young people with him, from Lowe.

The meeting was not large, by reason of the exceeding great rain and storm of wind;
but whatever any suffered that way, being right-minded, was made up, I believe,
and overbalanced, by the goodness of the Lord,
which he was pleased to afford us together at that time.

On the 12th we returned to Plymouth, and on the first of the week were at their meetings,
both forenoon and after; where we had good service,
and were kindly entertained in the evening among our friends.
On the 15th we went to Exeter, and had a meeting appointed there;
which consisting for the most part of Friends, was open and comfortable.

On the 19th we went to Collumpton, and the next day being the first of the week,
were at their meetings both forenoon and after.
The first consisted for the most part of Friends, and the Lord comforted us together;
but in the afternoon we had a very large meeting of Friends,
and a pretty number of sober honest-like people
of both town and country for some miles round;
and the Lord gave us ability to preach the gospel,
in the authority and dominion of it that day:
and as a door of utterance was largely given us,
so a door of entrance was in a good degree;
for the people were as sober and solid as so many Friends,
and we were greatly satisfied to behold them,
and had comfort in our labor bestowed upon them in the Lord.
