== Chapter 18

While we were at the yearly meeting at Exeter,
some proposals had been made by our friend Thomas Finnimore, and some others,
of having a meeting at Tiverton, in our return from Cornwall.
There is not a meeting of Friends in that town at this time,
but the people are generally friendly; and we being willing to give them a meeting,
our friend Finnimore, and some others, being acquainted with the mayor,
and the chief magistrates of the town, they procured the town-hall for that service.
It is an oblong square, something resembling the Royal Exchange in London,
with a vacancy in the middle, and the buildings quite round, two stories high:
and as notice had been given some days before in the town and country about,
we had a very large congregation of people of all ranks in town and country on the 21st;
and the mayor and magistrates being present,
they appointed the constables to keep the baser sort in awe,
if any should offer any insult, or other disturbance.
We had a fair hearing;
and the people were as quiet as the exceeding great throng would allow,
till towards the conclusion of my testimony, which had held a considerable time,
a company of scholars under a Jacobite master in the place, came in a company,
and crowded into one end of the square,
and by that means disturbed the meeting for sometime,
but were soon borne down by the crowd; and after that the meeting was more quiet.
But it is observable, that the master of that school,
and others in different parts of the nation, being Jacobites,
and of the Schism Bill principles,
debauch the minds of the youth they pretend to instruct in useful learning,
by infusing into them rebellious principles and persecution.
We did not meet with any scoffing or affront in town, but from these scholars,
who could not forbear to deride us in the open streets;
which are the fruits of a depraved example and education, encouraging to such behavior.
But the Lord, who always countenances his own appointments, was not lacking,
but gave us strength and understanding sufficient for the work of that day;
wherein we had no small labor, but a good and comfortable time:
and all ended to the honor of God, and promotion of his Truth among the people;
who were generally satisfied with what they heard,
being many of the truths of the gospel,
and the Lord Christ preached truly by his own immediate power, and use of instruments.

After the meeting we made our acknowledgments to the mayor and
magistrates for their countenance and kind assistance;
and after dinner I went with Thomas Finnimore to
visit one of the most noted persons in town,
a man of learning, and a Presbyterian by profession, who had been at the meeting,
and very attentive.
He had been well satisfied with what he had heard in the meeting in general,
except some things I said upon the subject of baptism;
which I endeavored to make plain to his understanding,
that the baptism mentioned by the evangelist Matthew is not water baptism,
and that the few and uncertain instances of the
practice of water baptism by some of the apostles,
after the effusion of the Holy Ghost, were not from that text,
for they never used the terms of it,
but upon the same foot upon which they practiced it in John`'s time,
and that it was no other than his baptism with water.
But Christ`'s baptism in this text and others relating to the same time and subject,
is of a more excellent nature and efficacy, being by the Spirit of Christ,
the Word of God, the great baptizer of the soul in the laver of regeneration;
which being one of the great things of God, all natural men are ignorant of,
nor can they at all understand it, till they believe in the Spirit himself,
the condemner of the world; of whom it is written, "`Every son whom I receive,
I rebuke and chasten.`"
"`Turn at my reproof, and I will pour out my Spirit upon you.`"
I told him,
that I had often observed the great ascendency education and
custom have over mankind in outward things,
in which alone the religion of the natural man consists;
and how far remote they commonly are from the things they contended for:
and instanced the present case, where he was contending for water baptism,
and was not in the practice of any;
for sprinkling an infant in the face with water is no baptism nor ordinance of Christ,
nor ever practiced by any of his ministers;
but set up in the dark night of apostasy by anti-christian priests of the See of Rome;
and as they themselves had no baptism, but only rantism, no washing, or going into water,
as the true mode was in its first institution by John, but only sprinkling;
they could not, nor did they deliver any baptism to the other sectaries,
at the time commonly called the reformation.
So that none of you all have any baptism,
nor are you under any ordinance of Christ on that account,
but only of a vain tradition of ignorant and presumptuous men, an old popish relic,
which you cannot defend with any propriety or reason,
though you may and do perversely wrangle and contest for it.
And we know it is sufficient reason for us to decline all water baptism,
in that we can say with the great apostle of the Gentiles,
"`Christ has not sent us to baptize,
but to preach the gospel,`" according to the measure of the dispensation thereof,
in this age committed to us; which differs nothing from the same,
but in the degrees of wisdom and power,
but the same in the nature and the reason of the thing.
This he did not seem very well to relish,
but could make no further defense of a thing so plainly wrong:
and so we parted in friendship; I ever aiming at the understanding,
and as little as possible to raise the passions or blind resentments of men,
in treating on matters of religion;
by which alone they can be truly subdued and mortified.

On the 22nd we had a meeting at Wellington, at Thomas Ware`'s;
where the Lord favored us with his good presence,
and furnished us with authority to preach the gospel; and the Lord Jesus Christ,
the Word of God and light of the nations, was set forth with demonstration,
by his own power and grace.
There were some of the town`'s people there,
and several of them affected with the testimony of Truth.
On the 23rd we had a meeting appointed at Taunton, at the widow Elizabeth Giffords,
to which came many of the town`'s people; who behaved well, were very solid like Friends,
and well affected with the testimony of Truth, which was clear and convincing.
Next day being the fifth of the week, we were there again;
when the meeting was very large and open:
and another meeting being appointed in the afternoon, and notice given,
it was as full as any they had known there, with people of all ranks and notions in town,
who were very sober, and things were well.

On the 26th we arrived at Bristol, where we were kindly received by Friends.
We visited the meetings there on the usual days, for about two weeks;
and then John Fallowfield went to Bath,
intending for London upon the death of that able minister of the gospel,
and pillar of the house of God, Francis Davis, his brother by marriage,
and my sure friend, greatly lamented.
But I found it my place to continue longer there; where I had great satisfaction,
and where Friends were desirous I should take up my winter quarters:
but inclining for London, I departed from Bristol on 16th of the ninth month,
and was at Bath next day; which being the first-day of the week,
and the meeting more select in the morning, the Lord favored us with his good presence.
In the afternoon, the meeting being much larger, and some strangers there,
things opened to satisfaction; and we had a good meeting.
Here I stayed till the 21st, their usual meeting-day;
when we were favored with another open comfortable meeting.
On the 24th, and first of the week, large notice being given,
we had two large meetings at Calne, especially in the afternoon;
when the Lord favored us with his comfortable goodness,
and a good degree of openings of the general truths of the gospel,
with demonstration and authority.

On the 25th I went to Marlborough, and had a meeting there that evening;
where many sober neighbors sat down with us, and the Lord favored us together;
and the doctrine of Christ was full, plain, and clear, beyond my expectation:
but the times and seasons are in the hand of the Lord, as alone worthy, all-wise,
and only good; to whom be the glory of all now and forever.
On the 26th I went to Newbury, where I stayed that night,
in order for their week-day meeting, which fell of course next day.
The Lord gave us great countenance,
and opened unto us the Scriptures of the Old and the New Testament,
of the law and the gospel, written within and without, in tables of stone, in books,
and on the table of the heart.
The Lord was liberal to us that day.
On the 28th I went to visit my sure friend Alexander Kirton, at Broughton Mills;
where I stayed that right, and was favored with his agreeable company to Reading next day,
where we remained till the first-day of the week following,
and were at both their meetings: which were very open, especially the latter,
and to good satisfaction; for many of the sober neighbors being there,
and the testimony of Truth going much towards them, as in most places at this time,
many things of the last importance were opened
in the wisdom and authority of the divine Truth.
But as I had taken cold before, and my exercise was large in these two meetings,
I found more of the effects of it next day.
At Henley that evening we had a very large meeting;
I was drawn out very largely therein to the people, and to good satisfaction,
the truths of the gospel being made plain to low capacities.
On the 3rd of the tenth month I found my voice almost gone by the cold;
but a meeting having been appointed to be that evening,
I attended it with some difficulty; for it was some time before I could recover my voice,
so as to be able to speak: yet through divine goodness,
I got over the difficulty at that time; and the Lord being with us,
we had a good and open meeting.

The next day the meeting at Jordans falling of course, I went there; it was pretty large,
and the Lord was near in a time of long silence, and I had good matter before me;
but for a long time continued totally unable to speak; yet at length broke through,
so as to express the heads of some matters before me, namely:
That an ancient prophecy of the Lord is at this day fulfilled in the
greatest part of the professors of Christ throughout the world,
where it is said, "`That it should come to pass,
that seven women should lay hold on the skirts of him that is a Jew, and say.
We will eat our own meat and wear our own apparel, only let us be called by your name,
to take away our reproach.`"
That though many profess the name of the Lord Jesus,
yet they feed themselves with their own inventions,
of many and various forms of what they call their religion,
and clothe themselves with their own righteousness, neglecting the righteousness of God,
even the Lord our righteousness; and feeding the body to excess and luxury,
clothe the same with needless and airy, fantastical and costly garments, apparel,
and things not becoming the cross of Christ.
But the people of God are preserved clear from these things,
by waiting upon him day and night in his temple,
the second house more glorious than the former, for the consolation of Israel;
"`the light to enlighten the Gentiles,
and the glory of his true Israel;`" who is not
lacking to any of the faithful at this day,
more than to good old Simeon in his, who waited for the consolation of Israel,
and was not disappointed;
the present attendants of the Lord being rewarded by the same peace,
though the whole world, the faithless and stupid world,
lies in wickedness even unto this day.
After this I had great peace, and the like testimony as the poor woman,
who of old anointed Jesus; of whom it is written, "`she did what she could.`"
The Lord accepts the good-will for the deed, when we have dune all that we can.
On the 7th I went to London and stayed, visiting the meetings there,
till the 29th of the first month, 1735, and then went to Albans;
and was at their meeting next day forenoon and after, it being the first-day of the week;
and the Lord favored us with his good presence therein.

On the 1st I went to Hampstead, where I had a comfortable meeting with a few Friends,
and some others, that afternoon: and lodging at my friend John Owen`'s,
he went with me next day to Ailsbury,
where we fell in occasionally with a quarterly meeting, to general satisfaction;
for the Lord was with us, to our consolation.
At Bistor I had a small but open meeting;
and then went to Banbury to my friend Benjamin Kid`'s, where I was kindly welcomed;
and next day was at their meeting: which,
though a little hard and heavy in the beginning, was, in the main,
a good and serviceable meeting; and that night also I tarried there.
On the 6th was at Warwick meeting forenoon and after;
where the Lord was with us to general satisfaction,
many being much tendered in each meeting; to the praise of the only true God,
who works all in all his people throughout the whole world.

On the 7th I went to Birmingham, to John Pemberton`'s,
where I had a meeting appointed next day; which was laborious,
but in the main a good meeting,
many great and necessary truths of the gospel
being opened with authority and demonstration;
which excited the love of Friends very much.
One great point was to press them towards the perfection of
Christian morality and the dispensation of the gospel,
through the Word of eternal life and love revealed in them.

On the 9th I went to Wolverhampton,
where the marriage of a grand-daughter of that very honorable Friend, Charles Osborne,
deceased, and a grandson of that faithful and steady servant of the Lord, Thomas Aldam,
happening to be the day after, the meeting was much crowded with people,
especially of the more reputable sort, and many could not get in.
The Lord exalted his own name that day,
and honored his people and their offspring with his blessed presence and goodness,
to the surprise of many who had been ignorant of his power;
and the Truth was made evident to many, according to the testimony of Holy Writ.
While the certificate of the marriage was tilling up, I noted to the people,
that no clandestine marriages could ever pass among us,
since the stated rules of our Society required ample certificates,
and proof of the consent of parents or guardians,
and the clearness of the parties from all pre-contracts with others,
and not too nearly related.
But that the national priests, through covetousness, had not only eluded and made null,
in great measure, even their own primitive institutions and practice on that account,
but likewise the laws of the nation, provided to prevent so great mischief.
For as the law requires the priest not to marry any couple
till he has taken all necessary precautions in the premises,
on pain of a fine of one hundred pounds,
yet where any wicked person can prevail with a young woman,
of ever so good a family or fortune, to marry him, her price, by law,
is only one hundred pounds, paid out of her own fortune by her deceiver,
who has not a doit of his own, and a liberal fee and bond of indemnity to the priest;
and she is ruined, and her parents and friends grieved and disappointed without remedy.
The design of the priests is too often their own gain, honor,
and advancement over the people, by their own consent.
For, do not you observe the management of your priests, who say, in effect,
give me my fee, and I will make you a member of Christ, a child of God,
and an inheritor of the kingdom of heaven.
Many ages ago,
they cursed all who did not believe that the sin of Adam is imputed to little children,
and the priest, who himself is an actual sinner, must sprinkle it away.
Give me my fee, I will preach for your instruction in the Christian religion.
Give me my fee and I will marry you.
Give me my fee, and I will make a harangue at your funeral,
and according to the value of it you shall have praise.
And though the people were generally of the high party, the Truth being over them,
none made any reply; only some turned pale, perhaps with secret resentment,
others blushed, and some smiled: yet all continued quiet, and the meeting ended in peace,
to the praise of the God of peace and love, who is worthy over all now and forever.
Amen.

On the 11th I went towards the city of West-Chester, in order for the yearly meeting,
to be held there this year for four counties, namely: Cheshire, Lancashire,
Westmoreland and Cumberland, and the next day to Chester,
to my friend Peter Leadbeater`'s, where I was kindly received.
On the 13th, being the first of the week, we had two very open meetings there,
some of the inhabitants being with us; and the Lord favored us with his good presence,
and opened to us several deep mysteries of his kingdom,
to general edification and satisfaction, and to his own glory; to whom alone it is due,
now and at all times forever.

On the 15th, about two in the afternoon,
began the select meeting of ministers and elders, which was not large,
but comfortable and edifying; and the next day about nine in the morning,
began the yearly meeting.
It was in the old tennis court, which has been the usual place for many years;
where we had the company of many of the citizens, and a large open meeting.
In the afternoon there came a very great concourse of
people of all ranks in town and country;
and the good presence of the Lord was with us, and the divine power was over all;
the ministry being conducted in wisdom and strength,
the principles of Truth were opened to demonstration and general satisfaction.

On the 17th, in the morning,
was held a meeting for conference concerning the affairs of Truth,
how they prospered within the precincts of the meeting, and advice given where needful;
and then was held the quarterly meeting for that county.
At three in the afternoon began the public meeting for worship,
which was exceedingly large, consisting of some thousands;
for the Quarter Sessions of the peace happening at that same time,
all or most of the bench of justices came to the meeting, and many of the women,
under the distinction, among them, of ladies, and a very great crowd;
and the Lord was pleased to favor his people with his good presence,
and his ministers with wisdom and power, and to exalt his own glorious name over all;
that great multitude, during the service, being as still as a meeting of Friends.

In the close of this meeting several of the great ones asked if there would be any more,
and were answered, no; but that the place and seals would remain as they then were,
till after the next first-day, and that several of our ministers would slay the meeting:
which was held accordingly, and in the morning was large and open.
Joshua Toft, myself, and May Drummond, had the public concern upon us,
the rest having gone to other meetings in the country.
In the afternoon we had an exceeding great multitude,
rather more than at any time before; for being the first of the week,
and all free from business, they were at leisure; and beginning at three afternoon,
some came to our meeting after their own were over.
The Lord granted the desires of his people, affording us his blessed presence,
and exalting his own arm over all; so that among all that great multitude,
one could hardly see a light look.
The meeting ended well, to the honor of the Lord, the satisfaction of his people,
and of the auditory generally.

The young woman above named, May Drummond, is of a considerable family in North Britain,
convinced about four years ago at Edinburgh, at a yearly meeting,
at the time when her brother was lord provost; and she,
and about thirty of her acquaintances, being in the meeting,
I happened to speak some things among them which they took notice of,
and thought it was a contrived sermon in our way, so cunning, as they called it,
that they could find no fault in it; but were ready to conclude I was a Jesuit,
and that I had that sermon written in my pocket:
whereas I never prepared anything to say in any meeting in all my life time hitherto,
but have ever depended upon the heart-preparing power and Word of the Lord,
and immediate work and openings of it in my own mind.
From that time this young woman came nearer and nearer to Friends,
and came sometimes to our meetings,
till she found strength to own the Truth in a public manner;
to the great surprise of her acquaintances,
who are generally of the greater and more polite sort of both sexes,
and to the grief and trouble of her relations, who are all against her,
save only a younger brother.
But, for Truth`'s sake, she has left and withstood them all; and being of a ready wit,
and enlightened by the Truth, she is so furnished with understanding and fortitude,
that they have not been able to hurt her by all their subtleties and contrivances,
or frowns.
She being of late called into the ministry, it renewed their pain;
but as she is upon the right foundation, and well furnished for the work, for the time,
Friends regard her accordingly; and having good utterance and matter,
many people are taken with her.
Her character and circumstances drawing many to meetings where she conies,
I hope and pray to the Lord, she may stand firm in the divine Truth,
and be serviceable in his hand, without whom the best of all his servants can do nothing.

On the 23rd I went to Shrewsbury, where next day we had a very open meeting,
many of the people of account being there;
some of them remembering that great and glorious
yearly meeting there about seventeen years ago:
and the Lord was now also with us, to the exaltation of his own name and glory.
The meeting was solid, and the truths of the gospel were largely and clearly opened,
to the praise of the Lord, and comfort of his few people there;
who were filled with his good presence together.
On the 5th, in the evening, I had a meeting at Colebrookdale,
at the house of our friend Richard Ford, who looks after some iron works in that place:
it was very open, and some persons of account in those parts were there,
and all very sober and attentive.
On the 27th I was at the meeting at Bewdly, forenoon and after.
The first meeting was not large, but alarmed the people,
so that we had a very large and open meeting in the afternoon;
wherein many necessary doctrines of the gospel
were fully opened to the understandings of many,
the goodness of the Lord being with us, to his own praise,
who alone is worthy now and forever.

On the 28th I went to Worcester, and the day after being their meeting,
it was put off till three o`'clock in the afternoon, and notice given,
which occasioned the meeting to be considerably large.
The Lord favored us with his good presence,
and opened to us the Scriptures both of the Old and New Testament,
with brightness and authority, to general satisfaction, both to Friends and others;
for which we were thankful unto Him who has all wisdom and power,
and without whom we can do nothing.
Yet this meeting was so hard to me for some time in silence,
and the people so very heavy, that it put me in mind of a saying of the apostle,
"`If the dead arise not,
why are we baptized for the dead`'.`'`" But so
soon as a little help from the Lord appeared,
all weakness, and all the power of death, vanished as darkness before the day;
and then in him I arose and prevailed: and so let it be with all his ministers,
in all places, from henceforth throughout all generations.
Amen.

On the 30th I went to Eveshain, and the day after fell in with their week-day meeting;
where the Lord favored us with his good presence,
and gave us a comfortable time together.
On the 2nd of the third month I had an appointed meeting at Chipping-Norton;
which was very open, the goodness of the Lord accompanying us therein,
and the light of his countenance making manifest things of the greatest importance.

On the 3rd I went to Oxford, and lodged with our friend Thomas Nichols; who has,
for many years, borne a faithful testimony, in that old seat of the power of darkness,
and subtlety of the sensual and earthly wisdom of this world, against all the envy,
scoffs, flouts and jeers, and other immoralities of the scholars;
and against all the persecutions of the town; till, by patience in well-doing,
he has so overcome them, that he is now treated with general respect.
On the first of the week, I was at their meeting forenoon and after;
where now remain only four or five Friends; but in the morning,
sitting together in the usual meeting-house,
the Lord renewed to us the happy experience of the fulfilling of his promise,
while in silence, "`That where two or three are gathered together in his name,
there he is in the midst of them:`" but after some time came in a company of students,
most of them full of levity, with vice and folly sitting on their brows.
They scoffed and mocked at the great truths of the gospel;
especially when some proper texts of holy Scripture were
mentioned concerning the divine light and Word of God,
as if they meant to repel the force of divine Truth by a flood of laughter.
I had patience under all their foolish opposition and ill manners;
and laboring in the virtue of Truth, so overcame them,
that they were generally quiet before I had done,
and some of them sensibly touched with the invisible power of Truth;
which the alteration of their countenances, from all the signs of levity and wildness,
to great solidity, did plainly demonstrate: and in the main it was a good meeting,
and ended well.
I never had anything but good-will to these mismanaged and misguided young creatures;
whose great geniuses might, under a proper direction and conduct,
be improved to great services in this world, in useful arts,
and be preserved from the great depravity they learn there,
which sullies and overbalances all the good proposed by their education.
In the afternoon we sat so long silent, that we tired one set of them who came first;
but another sort coming, after the first were gone,
I had many things to say to them concerning their learning, manners, catechism, vows,
promises, creeds, and the martyrs from whom they pretend to derive their religion:
and then preached to them on the grace of God; by which, their teachers tell them,
in the latter end of their catechism,
they may be able to keep all the promises made for them,
at the time of what they call their baptism; but that none can make members of Christ,
children of God, and inheritors of the kingdom of heaven, but Christ himself,
who is the great baptizer of souls, and by one Spirit baptizes all into one body,
"`the church, which is his body, the fulness of him who fills all in all.`"
But if they were members of Christ, children of God,
and inheritors of the kingdom of heaven,
by what their priests had done to them in their infancy,
when altogether ignorant of good or evil, they are now in the state of fallen angels,
by their own confession;
for "`they have left undone those things which they ought to have done,
and done those things which they ought not to
have done,`" and are become miserable sinners,
"`full of wounds, bruises, and putrifying sores,
from the crown of the head to the sole of the foot;`" and certainly none, in this state,
can ever enter the kingdom of God.
I told them, I had heard that the two universities, Oxford and Cambridge,
are called the two eyes of the nation; it is therefore no wonder the inhabitants,
depending on them, are so ignorant:
for the blind have led the blind till they are all in the ditch.
Some of them were not easy under this, and much more of this kind,
intermixed with some of the most glorious truths of the gospel;
yet Truth being over them, they could not oppose otherwise than by laughter,
more forced than natural.
At these times I usually stood and looked upon them, and reproving them when over,
went on with what I had to say, till I had finished.
Being preserved clear over them,
I never had a better time among any of them in that place,
or came away with greater satisfaction;
and I observed that the sober people in the meeting were displeased with their behavior;
for they were like those of old, who neither would enter the kingdom themselves,
nor allow others.
Yet in the conclusion they were for the most part solid,
hardly a light countenance among them;
so that they are rather carried away with the vanity and airs of youth, than envious,
and might make good and useful men, if rightly governed in time of youth,
and well exampled; their behavior declaring they are destitute of both.

On the 6th, being the third of the week, I fell in with the monthly meeting at Northend;
where the Lord favored us with the consolation of his divine and living presence;
on the 7th with the week-day meeting at Henley,
and on the 8th I went to a meeting at Amersham;
where the goodness of the Lord accompanied us,
and the testimony of Truth was glorious and over all.

On the 9th I had a meeting at Chesham, which was not large, but very open and comfortable.
After the meeting, in the evening,
I had conversation with a considerable man in the world, inclinable to the Camissars,
or French prophets; by whom I perceived they expect such a dispensation from God,
as that all the gifts in the primitive times shall be restored, namely: working miracles,
prophecy, healing, raising the dead, etc.,
whereby their minds being carried off from the present dispensation,
they neglect that--in looking for greater things before
they are come to the lesser--as did the Jews;
who looking for the coming of the Messiah in another manner than he was promised,
that is, with outward and worldly power and pomp, despised him when he did come,
and so missed of salvation by him.
But I opened many things to him, and the Friends then present,
as at that time they were opened to me of the Lord; and we parted in friendship.

On the 11th I had a large open meeting at Jordans,
Friends being there from the meetings all round,
and the Lord favored us with his glorious presence, to our satisfaction.
On the 13th we had an appointed meeting at Uxbridge, at John Hull`'s;
which was not large of Friends, it being much declined from what it was heretofore;
but some of the neighbors and a great many troopers coming in,
many of the doctrines of the gospel were clearly, and with good authority opened:
so that the power in which they act, the spirit of this world was fully under,
and they behaved with sobriety and attention.
The next day I went to London, to my usual lodging;
where I was kindly received and entertained.

On the 23rd of the sixth month, I set out from London, accompanied by John Fallowfield;
and being the seventh of the week, we went that evening to Dunstable,
and lodged at our ancient friend John Chester`'s, where we were kindly entertained.
Next day we were favored of the Lord with a comfortable meeting in his good presence,
with Friends and some others there gathered,
and made by him instrumental to preach the gospel of his kingdom among them,
to our mutual and solid satisfaction.

On the 26th we had a large good meeting with Friends and others at Olney;
many of whom were much tendered and broken under the
testimony of Truth delivered among them that day.
On the 28th we fell in with their week-day meeting at Northampton.
They having had some notice of our coming, the meeting was pretty large;
and the Lord favored us with his life-giving presence, and opened matters suitable,
and with the power of an endless life, to the help and comfort of many;
and we were rewarded with divine peace.
On the 29th we had an evening meeting at Bugbrook,
at Joseph Adams`'. But most of the people having been laboring all day in their harvest,
and weary, the meeting was heavy at first; but the Lord had compassion on us,
and it ended well and living.

On the 30th we went forward to Rugby,
where the yearly meeting for worship and propagation of the
gospel was to be this year for the counties of Cornwall,
Devonshire, Somersetshire, Gloucestershire, Worcestershire, Herefordshire,
and Warwickshire.
There were few Friends near that town,
and the people in those parts generally ignorant of Truth, and we also unknown to them.
The meeting began on the 31st, being the first of the week,
and many Friends and ministers appearing from London, Norwich, Bristol,
and various other parts of the nation,
and the country all about having large previous notice,
we had a meeting so large as rarely to be seen:
for the place prepared was so capacious as to hold many hundreds;
which was very full in the forepart of the day,
but the people came so generally in the afternoon,
that scarcely half of them could get in:
so that some of the ministers went into a large court behind an inn,
near the meeting-place, but not within hearing of those within;
and so had two meetings at the same time.
We had the company of those called the quality and gentry all about,
and several national priests among them:
and the Lord honored his own name ill the midst of them, from meeting to meeting,
and owned his ministers and people with his living presence.
To him be honor and dominion, as alone worthy, now and forever.

The meeting held twice a day till the evening of the third of the week,
being the 2nd of the seventh month; during which time the glorious truths of the gospel,
in the authority and demonstration of it,
were set forth by our ministry beyond contradiction;
and the lies and calumnies of priests, and their votaries and supporters,
detected and turned backward; and the Truth and Friends cleared.
The people behaving with much sobriety and serious attention,
I hope the understandings of many of them were opened, so as, in some degree,
to perceive we had been formerly misrepresented to them, and our principles hid,
but now opened and cleared.

We made a collection of money among Friends at the inns,
for such poor persons and families, not of us, as might be most necessitous in the town,
and in the end of the last meeting gave away among the people near a thousand books,
suitable to their condition, for their information and help;
all which were kindly received: and as love and unity abounded among Friends,
so we left the town and people in mutual love and good-will between them and us,
to the praise of the living Lord, who works in us the good-will and the deed,
to his own glory.

On the 3rd Friends generally dispersed,
and I went with Benjamin Kid and his wife to their country house at Plympton;
where I stayed with satisfaction till the 6th, and then went with them to Banbury.
The next day, being the first of the week, I was at their meetings,
both forenoon and after; which were both small, by reason of the rain.
The beginning of each was heavy; but both ended well, especially the afternoon,
which was very open in the latter part of it.
On the 8th I went to Charlbury,
and that evening had a very open meeting with Friends and others;
where the truths of the gospel were opened freely, with good authority;
and a solid comfortable time the Lord gave us together.

On the 12th I had a meeting appointed at Cirencester, which was an open good time,
some of the sober neighbors being with us therein; and the Lord favored us together.

On the 13th I went to Nailsworth, and the day after, being the first of the week,
was at their meeting.
In the forenoon it was not large, but open; and in the afternoon was very full,
both of Friends and others, and the Lord favored us with his good presence,
and with many divine truths relating to his holy kingdom in this world,
and that which is to come.
He glorified his own powerful name to his lasting praise.
I remained there till the 16th, and then went to Bath;
where I agreeably met with Samuel Bownas from Bridport,
Andrew Pitt and May Drummond from London.
She has been public for about two years,
and her testimony relishes with people of all ranks, especially the greater sort;
by whom she is more followed and admired at present than anyone among us,
the notion of her being a lady of quality, which is yet a mistake of her degree,
raising a curiosity to hear her; which occasions crowds not always to her satisfaction.
But the children of this world will still gaze at the servants of God,
but neither believe nor practice what they preach,
though in the demonstration of the Spirit, and wisdom of the Truth.

We all stayed at Bath till the 18th; and then were at their week-day`'s meeting;
which was much crowded by all sorts, and many could not get in.
The concern fell first on Samuel Bownas, an able minister indeed,
whose ministry silenced and collected the minds of the auditory in good degree;
and after him May Drummond was likewise concerned in testimony,
and concluded the meeting in prayer: and several national priests being present,
all conformed on the occasion; and the meeting was, I believe, to general satisfaction.

Samuel Bownas retiring home to Bridport, Andrew Pitt, May Drummond and I,
stayed at Bath till the 21st; which being the first of the week,
we were again at the same meeting.
In the forenoon it was not very large, but open and comfortable;
but in the afternoon was much crowded with people of various ranks and notions;
who generally were still, and many of them attentive to what they heard,
and some affected: and upon the whole, the Lord exalted his own name and Truth,
and gave us the reward of his own good presence.

Andrew Pitt and May Drummond went to Bristol in the beginning of this week;
and on the fourth-day I went to Bradford, to their week-day meeting: which was small,
no timely notice having been given, but open;
and the Lord gave us a comfortable time together, being mostly Friends.
On the 25th I was at Bath again, and had another open time among the people;
to whom the gospel was preached with clearness,
and they behaved with sobriety and attention.

On the 28th I was there again; and being the first of the week, the meetings were large,
especially in the afternoon, many persons of note, of both sexes, being present:
and the goodness of the Lord was with us; and a solid comfortable time it was to many.

On the 2nd of the eighth month, being the fifth of the week,
and Bristol quarterly meeting, particularly for the edification of the youth,
I was there again, and May Drummond likewise.
The meeting was large, and the things of the kingdom of God, by his divine Truth,
and the wisdom and authority of it, clearly declared; and I think,
from the behavior of the audience, to general satisfaction:
and the next day I was there again, and with good satisfaction;
for though the meeting was not so large as the former,
the power of divine Truth was glorious therein.

Here I remained visiting and attending the meetings, first-days, third-days,
and sixth-days, as usual, till the 4th of the ninth month,
with peace and satisfaction to myself, and Friends in general.
But one first day I exposed the pernicious doctrine of transubstantiation,
wherein the Papists say, "`That upon uttering the words of consecration by the priest,
namely: Hoc est Corpus meum, the wafer which is so consecrated,
is immediately changed into the very body of Christ, born of the Virgin Mary,
which suffered on the cross at Jerusalem; that this wafer,
being now the true God and Christ, is to be worshipped as such: and yet,
though the priest does use the words of consecration,
if he does not intend to consecrate, which none can tell but himself,
there is no consecration or transubstantiation, but the wafer remains what it was;
and consequently the poor deceived people are led blindfold into idolatry,
and utter uncertainty, and to worship they know not what.`"

In this meeting there were people of various notions,
who did not at all relish this doctrine; neither did some pretenders among ourselves.
For at this day we have among us some traditionists,
the children of such faithful Friends of Truth, who did,
in the early part of this dispensation of God we are under, not only believe,
but suffer for the same.
These children have, for a time, taken up,
and continued in the doctrines and examples they have heard and seen among us;
but when they have come up into the state of men and women,
being only in their natural state, and looking out to the world,
have been taken by the lust of the eyes, with the vain and sinful fashions,
customs and notions of the world, and become, some deists, some free thinkers,
others profane libertines, and others atheists;
denying all revealed religion as contained in the holy Scriptures,
and asserting there never was, is not, nor shall be,
any other guide given unto man by God but his own reason,
either in matters of duty towards God or man, religion or worship;
denying all sense or knowledge of any divine Spirit.
Thus renouncing Christ, they shake off his cross and despise it, with all its discipline;
and yet come to our meetings as if they were Friends.
But though some such there be among us,
to the great grief of those who know and follow the Truth,
yet they are but few in comparison of the numbers among other professors:
but wherever they appear, they are enemies to the Christian faith,
though peradventure they do not mean it, but may be fallen into a wrong way of thinking,
from a reasonable view of the errors and designs of priests and priestcraft;
which they think unreasonable,
and many of their schemes and injunctions
inconsistent with the attributes of the all-wise,
almighty, and all-good Creator of the world, to dictate to, or impose upon mankind.

In another meeting in the city of Bristol, on a sixth-day,
when there were present several hireling teachers, of various notions,
though I did not know it, and many people of their several sorts, it became my concern,
from the Spirit of Truth, to stand up therein, with this prophecy of the apostle,
"`The days shall come wherein men shall not endure sound doctrine;
they shall heap to themselves teachers after their own hearts`' lusts,
having itching ears; they shall turn away their ears from the truth,
and give heed unto fables.`"
Having repeated the text of Scripture to this effect,
I proceeded to observe to the auditory,
"`That this prophecy is clearly fulfilled in this and other nations at this day;
all the several sects adopting to themselves certain notions, principles,
and systems of religion, or what they call so,
make choice of such teachers as will teach and propagate these notions, and no other,
and will pay such teachers.
These at the same time are rejecting and despising the free,
perfect and effectual teachings of the grace of God;
which have been publicly and freely preached, in this and some other nations,
now nearly a full century, and still are unto this day;
contrary to the kind and merciful invitation and expostulation of the Almighty,
where he says, by his evangelical prophet Isaiah, '`Ho, every one that thirsts,
come you to the waters; and he that has no money, come you, buy and eat: yes come,
buy wine and milk without money and without price.
Why do you spend money for that which is not bread?
and your labor for that which satisfies not?
Hearken diligently unto me, and eat you that which is good,
and let your soul delight itself in fatness.
Incline your ear, and come unto me; hear and your soul shall live;
and I will make an everlasting covenant with you, even the sure mercies of David.
Behold, I have given him for a witness to the people,
a leader and commander to the people.`'
It is to him, the Lord Jesus Christ alone, that we have ever directed mankind,
that they may be taught by his grace and Holy Spirit in their own hearts,
and redeemed from all the hireling teachers in the world, of every notion,
form and design; and that freely, without any mercenary or low views to ourselves,
but in that love to the souls of all men,
in which the Son of God laid down his life for all mankind,
tasting death for every man.`"

Though I did not observe any uneasiness in the people, for they were a mixed multitude,
either in the first-day`'s meeting, or that on the sixth-day, yet some days after,
a man rich and high in the world, professing the Truth with us,
but a secret supporter of the priests, by paying their demands,
contrary to the testimony of Truth in his faithful people, gathered of God,
and called and chosen of him, to bear witness for him against the hirelings of the times,
and anti-christian priestcraft in every shape; this man uttered several invectives,
and false accusations against me, concerning what I had said in those meetings, saying,
"`We (meaning himself, and such as he) are at peace with our neighbors of all religions:
we and they converse freely together,
and we do not meddle with mailers of religion among us;
but you have done a great deal of hurt in these meetings, by scolding at them,
and inveighing against their religion, with which we have no business.
I have heard some of them say,
you deserved to be pelted for meddling with their religion,
which did not concern you;`" with other matter of like import.

I replied, "`That neither himself, nor such other violent persons as he meant,
were proper judges of my concern on that account: for,
though he and they had a right to judge, so far as to receive or reject,
as to themselves, what I, or another, might utter in public concerning religion;
yet they had no judgment from what root, or commandment,
I uttered these matters in those meetings; nor did I regard him or them,
or any other adversaries to the Truth,
in whose wisdom and authority I uttered these things, with demonstration, clearness,
and authority, which I cannot now repeat;
with which all the living of God in those meetings, were well satisfied,
being sensible also from what power and root they came.
Therefore the language of these your honest neighbors, demonstrates their guilt,
and the just application of those Scriptures, as well to the hireling mercenary teachers,
as to their hearers then present, and to yourself too,
as of the same spirit and work with them.
And I may tell you, that it is my work and business,
as often as I have the same authority, in the life of the divine eternal Truth,
to expose all false teachers and hirelings, as also all hypocrites,
and covetous presumptuous worldlings among ourselves, who give their souls up,
in a manner insatiable, to the gains of this world, without any bounds,
and then intrude themselves into the affairs of the church of God among us.
Though professing the Truth, such have no right, or any calling thereto of God,
yet they take upon them to act according to the weight of their worldly gains,
and not of the balance of the sanctuary; in which they are lighter than vanity,
or the small dust that weighs nothing.
And such a one are you; '`for a man`'s enemies shall be those of his own household.`'
And so it is at this day in our Christian Society;
tor as great enemies and stumbling blocks in the way of Truth,
as any are this day in the world, are covered with a profession of Truth,
and the Christian faith and religion.`"
With more to the same effect; which was not pleasing, yet being his due,
I did not think proper to defraud him of it.

On the 4th of the ninth month I went to Bath,
where I had several meetings to satisfaction; and on the 11th to Chippingham,
where I fell in with their monthly meeting,
and appointed another for worship the next evening;
where we had the company of a Presbyterian minister, and some of his hearers.

He was a moderate friendly man, and behaved well, as did the people in general;
and it was a good meeting.
On the 13th I went to Calne, where we had a large open meeting,
and the majesty and wisdom of Truth was over all, to general comfort and satisfaction.
On the 14th I went to Devizes, and had an evening meeting there; which was small,
there being few Friends remaining in that place: yet the Lord owned us,
and a few neighbors with his good presence.
On the 15th I went to Marlborough, and the day after being the first of the week,
was at their meetings both forenoon and after;
where the Lord gave us comfortable times together in him,
and many truths of the gospel were clearly opened among us by his divine wisdom.

On the 17th I went to Newbury,
and having appointed an evening meeting there from Marlborough on the 18th,
it happened to be their monthly meeting day; which being held in the forenoon,
the evening meeting was held likewise according to appointment;
and the next day being their week-day meeting, I attended them all:
and the Lord favored us in all of them with his goodness.

On the 20th I went to Reading, and the next day being the sixth of the week,
I was at their meeting; where several of the younger sort were tendered,
and generally comforted in the good presence of the Lord.
And stay, ing there till the 23rd,
I found liberty in my mind to go directly In London the next day, in the Reading coach;
where we arrived safely.

At London, and thereabout, I remained several months, visiting the meetings,
and making what assistance I could in the solicitations then on foot,
before both houses of Parliament, for further ease concerning tithes;
many of the national priests continuing cruel, through envy,
notwithstanding the good intention of the government,
in moderating the laws on that account.
For though a more easy way of recovery of what they call their due,
had been provided by some former Parliaments; yet the old laws being still in force,
many of the priests continued to take the most severe
and destructive ways they could against us.
The bill passed the House of Commons by a very great majority, but was thrown out,
or not committed in the House of Lords, by no great majority,
notwithstanding the interest and number of the bishops;
and the many warm speeches made in both houses for us,
and against the bishops and clergy, discovered that the temper of the nation,
at that time, did not favor them.

The meeting for Sufferings,
under whose care that affair was conducted by order of the yearly meeting,
requesting some of our ministering Friends to solicit some of the bishops in our favor,
for some of them were moderate men, it fell to my lot,
with my cousin John Bell of Grace-church street, John Fallowfield, and Zaccheus Routh,
to speak with the bishops of Salisbury, Chichester, Rochester, Gloucester,
Litchfield and Coventry, Chester, and London, on that and some other subjects;
and they behaved themselves decently enough as men,
and generally gave up all pretensions to divine right of tithes,
and insisted on the laws of the land only;
but would not consent to abridge any of the pretenses of the clergy that way.
Only the bishop of London, with a differing air of height from any of the rest, told us,
"`That as he looked upon himself as guardian of the rights of the clergy,
which he thought were unjustly attacked, he intended to oppose us as much as he could.`"
To which John Fallowfield answered, "`You speaks like a man;
for it is best to be plain in all things.`"
Though this bishop`'s terms were general, inclusive of all the clergy in England,
yet I understood them as restricted to his own diocese;
because there are two metropolitans, in their way, before him in this point,
Canterbury and York; each of whom had a better title to such a priority,
the former especially: but when he appeared so legally positive and vindictive,
all I said to him was, "`That this case might be considered equitably and mercifully,
as well as legally, by any man under the notion of a Christian bishop.`"
Upon which he stept a little back, and looked seriously upon me,
the rest just passing off, but made no reply; and I also withdrew.

I continued at London till the yearly meeting; which was, in the main,
more peaceable than at some other times, there being but two appeals, as I remember;
one of which I thought uncommon and remarkable.
A certain person in Ireland, having been a preacher among Friends there,
and married our way, taking some offense by some ill usage, as he thought,
in an arbitration at London;
and letting in too deep resentments against some particulars,
and not meeting with such satisfaction, upon some complaints, as he thought was due,
by degrees he increased in his prejudices till they became general;
anti then he became an open and embittered enemy to the whole Society.
Falling in with the bishops in Ireland,
he became a strenuous opposer of our endeavors for an affirmation there,
as we had obtained in England; and sued some Friends in chancery for money,
where none was due, taking advantage of them,
because they could not put in their answers upon oath, and hindering,
as much as he could, their obtaining an affirmation instead of an oath,
in such courts and cases; and denying his wife, because married among Friends,
attempted to take another; with some other evil practices:
for which the monthly meeting he belonged to had denied him;
and he had appealed to the quarterly meeting, but had never appeared there,
nor anyone for him, to prosecute his appeal.
But after some time he had come over to London, and unknown to any meeting,
had prevailed with some ignorant and disorderly persons
professing Truth to give him a certificate,
but not in any meeting; with which he went into Pennsylvania.
But Friends there being apprized of his doings, from Ireland,
he was not received among them.
After some time he returned to England;
and insinuating himself into the opinions of some members of
the monthly meeting of Devonshire-house in London,
they so far espoused him, and his cause,
as to find means to bring it before the yearly meeting there; which grieved many Friends.
However, as it came by way of appeal from the quarterly meeting at London,
the yearly meeting appointed a committee to hear it; who,
after inquiring into the true state of the case,
of the Friends from Ireland then in the meeting, made their report.
That it was not regularly before the meeting; for that this appellant had appealed,
in the same case, to a quarterly meeting in Ireland,
where the offenses arose about sixteen years ago, as I remember;
which was so far regular: but never prosecuting his appeal, as above noted,
there it remains.

But notwithstanding this report,
certain arbitrary persons of the monthly meeting of Devonshire-house,
and of the quarterly meeting of London, who had, out of all order and rule,
espoused this offender and his cause,
would have eluded it by subtleties and sophistical reasonings;
but the wisdom and power of the meeting silenced them,
and the report was received and agreed to.

Seeing the ill tendency and consequences of such appeals from other
nations and places in the world to the yearly meeting at London,
I took this occasion to observe to the meeting,
That this being a matter of immoral conduct only, in the appellant, and not of faith,
doctrine or principle,
it was sufficiently cognizable and determinable in and by the monthly meeting in Ireland,
where the matters of complaint arose, or by appeal to the quarterly meeting there,
or finally in their yearly, or half-yearly meeting, usually held at Dublin.
And that no appeal at all ought, in such cases,
to be admitted from that meeting at Dublin,
or from any yearly meeting of business in any other country or island, to London;
nor ought that meeting at London to receive any such, or enter into judgment thereon:
for, if they should, the consequences thereof might be very pernicious and oppressive.
Such appeals from Pennsylvania, Rhode Island, Barbados, or other remote places,
or even from Ireland or Scotland,
would be attended with great charges and trouble many ways, and loss of time,
to persons necessary to attend appeals from such places,
and likewise to the members of the yearly meeting at London;
which would be thereby rendered as a stage of contention by every unruly spirit who
could make a party and wrong interest in and among such as himself;
and would render London as a kind of head of the churches.
But the proceedings of Rome remain in too glaring
characters for any men of knowledge and of truth,
and friends to the rights and privileges of mankind,
to submit to or promote any such thing in this Society, now,
or in the succession of ages.
So this appeal was rejected as irregular, and not lying there.
