== Chapter III

After this I remained at my father`'s house,
though under many inward loads and burdens in the family,
not one soul of them having any sense of truth; and keeping constantly to meetings,
and living near the divine truth,
I was thereby preserved from the attending evils and temptations,
till the Lord opened a way for another journey; which was as follows.

On the 19th day of the eleventh month, 1692, I went from my father`'s house in Cumberland,
and that night lodged at George Marshe`'s, at Healy Hall,
not far from Newcastle upon Tyne, where I met with John Bowstead, by appointment,
the next day; and in the 22nd we went to Shields,
and back the day following to Newcastle, and were, on the 24th, at Benfieldside;
and on the next day at Hexham; on the 26th again at Benfieldside,
and back to Newcastle on the 27th; having meetings at these several places;
and on the 30th we set forward from thence for Scotland, by way of Morpeth, Horsley,
Framlington, Whitiingham, and Wooler-Haugh; and next day we came to Kelso, in Scotland.

On the 2nd of the twelfth month we arrived at Edinburgh,
and were at the quarterly meeting there on the same day; which being ended,
we met with Thomas Rudd, who had some days before, come from England by way of Glasgow,
and had been several times through the city and colleges of Edinburgh, crying,
"`Woe to the sandy foundation,`" with some other words of the like import.
Next morning, being about to depart the city homewards,
John Bowstead and I went with him to take leave of William Miller, at the King`'s Gardens,
and his family; where we had been but a short time,
till the concern returned upon Thomas Rudd to go again through the city;
and after great exercise and travel in spirit, he became willing, and went.
The most of his message was in these words, "`Ho! all people; O all be warned this day,
to fear before the Lord, the mighty God of heaven and of earth;
and every one turn from the evil of your ways.`"
He had a voice suited to the measure of his words,
with an innocent boldness in his countenance,
frequently lifting his right-hand towards heaven as he passed along,
which was with a slow and grave pace.
John Bowstead and I, though we had a good will to the cause,
and personal love to our friend,
sufficient to have engaged us with him in any service
warranted by any degree of the like concern and call,
and to go with him through the city;
yet we were not willing to hazard our lives or liberty as intruders into his concerns,
not finding any thing from the Lord so to do.
We therefore went to our friend Bartholomew Gibson`'s, where we lodged,
to wait the issue of our friend`'s undertaking; where we had not sat down,
till it pleased the Lord to give us a more
evident fellow-feeling of our friend`'s concern,
in great brokenness of heart,
in which we were constrained to go up into the city after him,
where we found him delivering his message to a great multitude of people.
Some of them had thrust him down into a low shop in the high street; from whence,
as he attempted to move, the rabble pushed him back:
nevertheless the power of the Lord was over the multitude, both in him, and in us;
so that all fear of them was removed from us by the protecting arm of the Lord,
who is ever near to deliver such as act in his counsel, in the time of greatest danger.

In the mean time John Bowstead, being a bold, able-bodied man, pressed through the crowd,
and taking Thomas Rudd by the arm, advanced him into the street;
where some of the multitude pointed at a stone by the cross,
where he might stand a little above the people, which he did;
and John Bowstead and I stood between him and the people,
and they were then a little quiet, expecting, as we supposed by the rumors in the city,
to have heard some judgment denounced, or prophecy declared.
But Thomas having only some short warnings for them, some of them mocked,
others threw a pack of old cards among us, with some scoffing words;
yet others among them were put upon a more serious consideration,
what could engage us thus to appear in a place of so imminent danger.
Others whispering said, "`This is he who went through London with a message,
and shortly after there was an earthquake there.`"
By several circumstances,
we perceived it became a general amusement to the inhabitants of all ranks; and many,
as well of the greater as lesser quality,
would gladly have known the result of the matter.

From the cross we went down the high street and Canongate, till we came to the Tolbooth,
over against which stood several companies of soldiers, drawn up in order in the street;
to whom Thomas Rudd spake some words, by way of warning, as before;
and I did not observe that any of them offered the least opposition, either by word,
deed, or gesture.
But as we were passing by them, intending to go to our lodgings,
there came a certain civil officer from Charles Charteris,
chief bailie or alderman of the city, to summon Thomas Rudd before him.
This officer making known his message in a very civil manner,
Thomas went with him into the city.
I told the officer, that he did not need to lay hold on Thomas Rudd as a prisoner,
for he would go along without it; so John Bowstead, and the officer and I, went before,
and Thomas Rudd followed after, till we came before the bailie;
who examined Thomas about such things as he thought fit to object against him,
concerning his going through the city,
but would not suffer us to be present to hear his examination;
and in a short time he was committed to the Tolbooth of the city,
and put among such as they accounted traitors and rebels against the government.

John Bowstead and I stayed a little before the prison door,
the good presence of the Lord remaining with us, and bearing up our spirits over all,
in times of most apparent danger.
We called to the turnkey to admit us into the prison to see our friend,
and accompany him in his imprisonment; which he readily and courteously did.
No sooner were we entered, than a multitude of prisoners,
and their friends who were with them,
came to see us in the large common hall of the prison,
where they gazed upon us with seeming wonder;
for the Episcopal party at that time were under dissatisfaction,
because of the suppression of their clergy;
and others also were not satisfied with the government upon other scores;
which had excited several, of divers sorts, to offensive behavior; so that the prison,
which is large, was very full.

After a while the jailor took us into an apartment made of deal,
called the Quakers`' high room, made by Friends in time of greater persecution,
for their own convenience.
There we stayed till the evening, where several Friends came to us.
And Thomas Rudd being concerned in prayer at supper,
the people in the prison rushed towards the place, and were attentive;
some of them afterwards expressing their satisfaction to hear us crave a blessing,
as they phrase it, at our meat; by which I suppose they had been misinformed,
that we were such as would not call on the name of the Lord,
or crave his blessing on such occasions.

That night John Bowstead and I went to our lodgings, and in the morning returned;
and understanding that the bailie aforesaid was keeping a court near the prison,
being emboldened "`by the presence of the Lord, we went into the court to him,
with a Friend or two of the town with us, and there stayed till his business was over.
As he came to the foot of the stairs we began to expostulate the matter with him;
and John Bowstead told him,
it would be a great reflection upon the Presbyterians in Scotland,
who so lately themselves had been hardly used, as they said, by the Episcopalians,
so soon to begin to persecute us, for no other cause but discharging our duly to God,
in such manner as we were persuaded in our consciences the Lord required at our hands.

The bailie replied, that he had not imprisoned our friend maliciously,
but out of kindness to protect him from the rabble; "`which,`" said he,
"`when they are moved, are not easily suppressed,
but will commit outrages of dangerous consequence,
notwithstanding any power we have over them, when fully enraged.`"
And said he, "`I am willing to set your friend at liberty,
provided he will depart the city without any more disturbance.`"
Accordingly he went into a private office, whence he had committed Thomas Rudd,
and sent for him from the prison;
and after some fruitless endeavors to extort a promise from him to depart the city,
and come no more in the streets as before, he gave orders for his release.
Then we went again to the prison house,
to pay the victualler of the same for some bread
and drink which we had used in the prison:
and there we met with one John Kerr, an Episcopal priest,
who had been lately incumbent at Roburgh, and ousted at the revolution.
He had been, the night before, with Thomas Rudd alone; who having been in prayer,
this John Kerr had been so much affected thereby, that he promised, of his own accord,
that if he was released from his imprisonment,
he would come to our meeting the next time it should be held; yet he neglected it,
though he was released according to his own wish.
Thus the Lord is gracious in giving men their desires in times of distress;
yet they are apt to forget their duty, his mercies, and their own promises,
when they come where they think themselves less obnoxious to judgment,
or the cruelly of their adversaries.

As we were in the prison-house together in silence,
we were much broken in the good presence of the Lord;
and John Bowstead being concerned in prayer,
several of the prisoners and their visitants came up in a rude manner, to hear and gaze;
but the virtue of truth affecting them, they uncovered, kneeled down,
and reverenced that divine power and presence that was with us; though I think,
themselves did not know the cause of their subjection.

After this, a discourse happened between the said John Kerr and a Friend,
who was a citizen, concerning freedom from sin in this life;
which John Kerr asserted could not be;
and brought this passage out of the Epistle to the Romans, which he thought proved if,
namely: "`For the good that I would, I do not; but the evil which I would not,
that I do;`" and divers parts of the same chapter throughout.
I being at the other end of the table, and hearing them,
and observing where the priest erred, a concern came upon me to take up the argument,
and to endeavor to inform him better.
I said.
That the apostle, in that epistle, in the first place proved,
that both Jews and Gentiles were under sin, the former as well as the latter,
notwithstanding the law and ordinances of God delivered to them, which they had not kept.
That both had redemption through faith in the Lord Christ;
by whom they were made free from sin, even in this life, which the law could not effect,
as appears by these words: "`Knowing that Christ being raised from the dead,
dies no more; death has no more dominion over him.
For in that he died, he died unto sin once; but in that he liveth, he liveth unto God.
Likewise reckon you also yourselves to be dead indeed unto sin;
but alive unto God through Jesus Christ our Lord,`" etc.
The apostle here,
taking the comparison from the certainty of the death and resurrection of Christ,
infers likewise as great certainty of their being, in this life, through him,
raised unto newness of life; which he corroborates in the 18th verse of the same chapter,
saying, "`Being then made free from sin, you became the servants of righteousness.`"
And in the 22nd verse, confirms it further; "`But now, being made free from sin,
and become servants to God, you have your fruit unto holiness,
and the end everlasting life.`"
Where it is apparent, that the apostle makes the service of God and sin inconsistent,
and altogether incompatible: but, resuming the same doctrine, under another similitude,
in the seventh chapter, he there personates the state of the Jews, and of himself,
whilst only under the law, and without the knowledge of Christ,
and not that state that he, or the adult in the church, was in,
as an apostle and Christian, at the time of writing that epistle;
which states are so different,
that it is impossible the apostle could be in both in so short a time,
as between writing part of the seventh chapter and the beginning of the eighth,
which might be less than half an hour; for in the 24th verse of the seventh chapter,
summing up all the weaknesses under the law in a few words, he cries out,
"`O wretched man that I am, who shall deliver me from the body of this death!`"
And immediately answers his own question, "`I thank God,
through Jesus Christ our Lord;`" and then continues to assert the Christian freedom,
and saith, "`There is therefore now no condemnation to them which are in Christ Jesus,
who walk not after the flesh, but after the Spirit: for the law of the Spirit of life,
in Christ Jesus, has made me free from the law of sin and death,`" etc.

"`Thus it appears that the apostle Paul was not under the body
of sin and death at the time when he wrote that epistle;
but was only recounting the various states, both of himself and others,
under the law of Moses,
and after the law of life and liberty from sin was come by the Son of God,
and fulfilled by him in this apostle,
as also in the adult in the congregation of Christ.`"

Upon this the said John Kerr freely acknowledged before the company,
that he had all along mistaken that Scripture, and that we understood it right.

Having paid for our bread and drink,
and returned the bed and bedding to the Friend who had brought the same,
in expectation that Thomas Rudd`'s imprisonment would
have been longer than it was suffered to be,
through the good and well-ordering hand of the Lord, and departed out at the prison door,
no sooner were we in the street, than Thomas began again to speak to the people.
John Bowstead and I finding no concern that way for a short time,
at first were not forward to go with him, but went into a Friend`'s shop;
where we had not been long till the power of the Lord came upon us;
and then w-e went into the street, where we found Thomas Rudd preaching among the people;
who were more solid than before, concluding, no doubt,
that the magistrates had found no fault in him, having so soon released him:
but there was a secret power over them, which they knew not.

We went down the high street, near to the Canongate; and upon an out stair,
within the gate, Thomas Rudd stood up and preached to the people,
and after him John Bowstead;
upon which the multitude became so still as if we had been in a meeting of Friends;
and many persons of the greater rank, of both sexes, leaned out at the windows,
and heard the sound of the truth.
In the mean time I had been a while separated from the rest by a coach,
and disputing in Canongate with a young man who had asked me some questions,
which I answered; and we parted in friendship.

Thus the whole multitude being as it were chained by
the mighty and invisible power of truth,
and our spirits over them, and at liberty by the same,
to his glory and our great consolation, we went to our lodgings;
where we had been but a short time till a messenger came from the countess of Kincairn,
to invite Thomas Rudd to her lodgings,
in order to have some discourse with him concerning his message,
and to know whether he had denounced any judgment against the city; for the adversary,
by his emissaries, had invented and spread a rumor,
that Thomas Rudd had prophesied that in seven days the city should be destroyed.

In the afternoon we went to the countess, and Thomas Ballantyne with us,
a Friend who had been through the streets with Thomas Rudd before we came to town,
and continued with us during the whole time.
This countess was an ancient woman, and of a grave and serious deportment:
she was kind and courteous to us, entertained us with respect,
and acknowledged several doctrines of truth, so far as we had occasion to discourse her.
She also acknowledged a sense of the great provocations that
city had given the Lord to bring severe judgments upon it;
and told Thomas Rudd she heard he had spoken against the Presbyterian church,
of which she was: to which he answered, that he was concerned by the Lord to cry,
"`Woe against the sandy foundation;`" and if the Presbyterians were concerned there,
they would do well to look to it.

From thence we went to the lady Collington`'s lodgings, who,
in the time of Thomas Rudd`'s imprisonment,
had sent to him to know if he wanted any thing;
and had likewise sent her maid to invite him to her house after he was at liberty.
She entertained us respectfully, and discoursed matters that occurred seriously;
but in the mean time came in a priest and one Dr. Sibbald, a physician;
with whom we had some dispute: the matter in controversy with the doctor was baptism;
we made short work with him, but the particulars not being exactly remembered,
are omitted.

But the priest being a young man,
and a little too forward to engage in matters he did not understand,
and the controversy with him being concerning the ministry,
I cited a passage out of the first epistle of John, namely:
"`But the anointing which you have received of him abides in you:
and you need not that any man teach you:
but as the same anointing teaches you of all things, and is truth, and is no lie;
and even as it has taught you,
you shall abide in him;`" and asked the priest what this anointing was,
and how the same taught?
To which he was silent, not without blushing in the presence of the lady,
who was an ancient grave woman, and several younger, her kinswomen.

Then I questioned the priest further about his call to the ministry,
and by what authority he took upon him that office?
To which he answered, "`There is an external call, and an internal call.`"
The external I passed over, and asked him what his internal call was, and by what?
He replied, that it was by the light of God`'s grace, which was in him.

I returned, "`Take heed how thou ascribes so much power to the light within,
lest thou be reputed a Quaker.`"
Upon this he desisted to prosecute his argument any further,
and dropped the defense of his internal call; but betook himself to railing accusations;
and speaking to Thomas Rudd, said, "`We have ministers here already,
sufficient to instruct the people,
and need not you to make such disturbance in the city.`"
"`No,`" answered one of the young ladies, so she was styled among them,
"`it was not they that made the disturbance, it was your hearers;`" meaning,
that the unruly people were, for the most part, of the same profession with this priest.
A pause of silence coming over us, and truth over all,
Thomas Rudd said some few things to the old lady,
and John Bowstead to the priest and doctor, and then we departed in peace with the Lord,
and in favor and respect with most of our auditory,
which were many more than I have mentioned in particular.

Having finished our concerns at Edinburgh, we went into a ferry-boat at Leith,
on the 6th day of the same month, and arrived at Kinghorn, and next day to Couper;
through which Thomas Rudd went with the same message as at Edinburgh,
and John Bowstead and I went with him.
The people came forth as bees from a shaken hive; so that the streets were quickly filled.
We went through the town unmolested, and came back near the place where we began.
Then came two of the bailie`'s officers in red clothing,
and summoned Thomas Rudd to appear before him, which he did.
The bailie inquired by what authority or power he preached to that people?
Thomas answered, By the authority of the Word of God, nigh in his heart,
by which a necessity was laid upon him; as it is written,
"`Out of the abundance of the heart the mouth speaks,`" and "`a good man,
out of the good treasure of his heart, brings forth good things.`"

The bailie being a moderate man, and trembling a little whilst he examined Thomas Rudd,
though in the presence of many of the people, did not detain him long, but dismissed him,
without the least rebuke or scurrility; after which,
and a short exhortation to the people by John Bowstead,
and some few words to them by myself,
being the first I had ever uttered in a public manner, we departed thence.
The two officers and a multitude of the inhabitants,
very lovingly conducting us out of town to a green hill a little without,
directing us the way we inquired after, with great respect.
When we were about a quarter of a mile gone from them,
the tender love of truth being much manifested in us,
we were constrained thereby to look back,
when we saw the multitude still standing on the hill looking after us,
and that love flowed towards them as from an open fountain;
in the sense whereof we were tendered and broken, and yearned towards them,
as a young man towards his beloved, when he takes his journey from her for a season.
There will be a tender people there in time.

We went to Dundee the same day, where Thomas Rudd likewise preached through the streets,
John Bowstead and I going along with him.
No incivility was there offered to us,
save only that a soldier took Thomas Rudd by the arm and bid him be silent;
but Thomas not regarding him, he offered no further violence.
Being come quite through the town in that service, the Lord dropped his peace upon us,
and we went on in great joy and comfort in his good presence,
being lovingly directed on our way by one of the inhabitants.
The fields of Dundee are not yet fully ripe,
but in due time there may be a plentiful harvest.

The concern came upon us again in the way as we went from Dundee; and at Broughty,
a village along the river side, below the town, Thomas Rudd delivered his message,
the same as before, to a small people.
They opened not a mouth, as I remember,
but stood as if they had been amazed at the sound of truth,
which came with good authority and power.

A little further east, at a place called Moneyfeath,
near an old bridge and a water corn-mill, Thomas Rudd was concerned to cry aloud,
as we passed by two or three houses there,
to warn the inhabitants to turn from the evil of their ways;
and immediately came forth a company of idle people, who had been at a wedding,
with music and reveling; and they being in the height of their pleasure,
little was effected upon them;
but some of them seemed surprised with fear of some personal danger.

That evening we went to Aberbrothwick; where we felt a war in our spirits,
against a foul, dull, senseless spirit reigning there.
We laid, as it were, under it all night, and in the morning went through the town;
Thomas Rudd warning the people as at other places.
They offered us no violence, only some mocked, others gazed; and the whole,
being generally Episcopal, had little desire to know the truth.

On the 8th day of the same month we went to Montrose;
where we found ourselves engaged of the Lord to alarm that place also, and to make war,
against the spirit that ruled there.
Having on our armor of the love of truth to all souls, we went into the streets,
Thomas Rudd warning the people, as before.
There is much of the seed of Ishmael there, and some also of Isaac,
though oppressed and much under at present;
the Lord God of Israel hasten the time of his redemption.
By the time we were fully through the town and returned to the market-place,
there was a multitude of people gathered about us; who, in the main,
were indifferently sober, only some of the younger sort threw dirt on Thomas Rudd`'s hat,
as we went along the street; but he going into a Friend`'s house to wash himself,
John Bowstead preached to the people; who heard him with attention,
and departed peaceably.

A little after, on the same day, the Friends in that place being come together,
we had a meeting with them; and so departed in peace.
On the 9th day of the same month, as we were on the way to Kirktown-hill,
where David Falconer lived,
Thomas Rudd went to a house on the west side of the river from Kirktown-hill;
where lived a widow, who had several daughters then with her.
The message was as at other places;
and the fountain of eternal life was largely opened towards them;
and we found respect from them in a good degree,
according to their way of expressing it.

The same day we went to Urie, to the widow Barclay`'s; and the next morning,
were concerned to visit several villages in the neighborhood; as Fetteresso, Dunnotter,
and Stonehaven:
and after Thomas Rudd had delivered his message in the
streets of the Upper Kirktown of Fetteresso,
John Bowstead preached in the graveyard to a people buried in ignorance;
who seemed to have no sense of God at all,
but only what they dreamed in their public form.
We understood the priest of the place was, all the time,
looking out at a window towards us; but did not offer the least opposition,
though such as they account wolves in sheep`'s
clothing were even in the midst of his flock.

After we had gone through the streets of Stonehaven, we came into the market-place,
where John Bowstead had a very good time in preaching to the people;
and some soldiers at first attempting to pull him down, were hindered by others.
The people there, though in the main afar off,
yet some of them are drawing near the streams of the free fountain; which,
in '`the days of thirst, hastening upon that nation, may satisfy their fainting souls.

On the 11th day of that month we went to Aberdeen; and on the 12th,
being the first day of the week, we were concerned in the streets, as at other places;
and a military sergeant, with a file of musketeers,
came against us in the market-place in a furious manner,
clubbing their muskets over our heads, as if they would have knocked us down,
pretending orders from the officer-in-chief to put us out of the town.
But we standing in the power of the Lord, were not afraid, but demanded of the sergeant,
by what authority he, being a military officer, offered to hinder us from doing.
our duty; at which he, with his fellows, withdrew, as one conscious of his error.
Thomas Rudd then continuing his message through the market-place, John Bowstead was,
a little after,
concerned to proclaim the spring and dawning of the day of God`'s
glorious power to be near at hand upon the inhabitants of that place,
and the country adjacent:
and so after a good time in the streets we retired to our lodgings.

On the 14th day of the same month Thomas Rudd went back towards Kirktown-hill;
and in his way, as he told us, at a place called Benham-Kirklown, he met with a priest,
who had taken upon him to report to the people in those parts,
after we had passed through to Aberdeen, that we were Jesuits in disguise.
But when Thomas Rudd went among them, and to the place where the priest lived,
to deliver his message in public, the cowardly hireling,
like one ashamed of his slanders, shrunk into his house,
not having the least objection against what Thomas Rudd there delivered,
notwithstanding his backbiting insinuations aforesaid.

In the mean time, namely: on the 18th day,
John Bowstead and I went northward to Inverary,
where we had a good meeting among Friends; Robert Gerard, a sober young man,
a Friend of Aberdeen, then accompanying us.

On the 19th, being the first-day of the week, we went to the meeting at Kilmuck; where,
about the middle of the same, Thomas Rudd came again to us.
From thence we went to Lethenty, to our friend Robert Burnet`'s; towards Inverness,
which is about sixty miles north of Aberdeen; and no Friend there;
nor had any Friend travelled that way for about fourteen years before.

On the 21st of the month we went from Lethenty to Ligelsden, Strathbogie, Keith,
and Castle-Gordon, where we lodged; and the next day we went to Elgin in Murray.

As we came near Elgin, the word of the Lord began secretly to work in us;
and when we came to the town, we went to an inn to refresh ourselves;
where we had not drank till Thomas Rudd became concerned, as at other places,
to go through the streets with the same message as before; and John Bowstead and I,
having a fellow-feeling of our friend`'s concern, went into the streets with him.
Once we went through the whole town; and as we came by the guard,
in the middle of a street, where was part of a regiment of dragoons, the officers,
stirred up by the Presbyterian magistrates, slopped us, and asking us some questions,
called us Jesuits in disguise: adding,
that if we did not instantly retire to our quarters and refresh ourselves,
for so much liberty they would seem to allow us, and so depart the town,
a drum should be sent after us.
But John Bowstead being bold at that time, answered,
that he would hope for better evidence from them of that Christianity they professed,
than to offer to drown with the noise of drums, the voice of such as were sent of God,
to warn people to turn from evil; but some cried out,
"`They deserve to be hanged;`" and others had other hard speeches against us.
But in the mean time we went on with our concern by the guard again;
and at about forty yards distance from that place,
Thomas Rudd spake some words by way of testimony to the people, who were very numerous,
and more quiet than could have been expected,
considering the encouragement they had from the example of the soldiers and magistrates.

After Thomas Rudd had done, John Bowstead began to speak to the multitude,
and forthwith came several soldiers from the guard, by orders from their officers,
and took us all into custody, and imprisoned us in the guard-house among the soldiers;
where, for a short time, we were mocked and scoffed at by them.
But they seeing our patience and innocent behavior,
soon began to draw near us and excuse themselves, saying,
they did not imprison us of their own accord, as having any thing against us,
or what we were concerned in; but being commanded by their officers,
they could not but obey.
The corporal of the guard seemed much concerned at our imprisonment, and sorry for us;
for said he,
"`I have seen multitudes of your friends in Ireland at
their public meetings without interruption,
and never knew of any ill they did;
and why might not you have had liberty to do that which you think your duty here?
But our officers cannot help it;
for they are put upon it by the Presbyterian magistrates.`"
Some of the soldiers became so kind, that they sent for ale for us,
though we requested them to forbear it; yet, seeing the reality of their kindness,
in their way, we tasted a little of their drink, which pleased them.

In a short time after, the power of the Lord began to increase in us,
and we opened several truths of the gospel among the soldiers, as the Lord opened in us,
and gave us utterance.
And they standing with their backs towards the door,
in the mean time came the officers and some of the magistrates,
as also the laird of the town; who, when they heard what we were upon,
were more earnest to put us out of the guard, than before they were to imprison us there.
But we finding that the Lord had wrought our liberty,
and ourselves being above them in our spirits, and that power that wrought in them,
we were not hasty to go out; but remained discoursing those things which were upon us,
till the officers came behind us, and in a manner forced us out before them.

Then I called lieutenant Drummond aside, he being the chief officer present,
and gave him to understand that the civil magistrate had imposed upon him;
for it did not belong to the military officer, but to the civil,
to intermeddle with mailers of that import.
Howbeit, we parted with them in kindness;
but withal they commanded that we should depart the town,
and speak no more to the people; and would have had us promise so to do,
as the condition of our liberty, before they absolutely released us.
John Bowstead answered,
that if we could have gone through the town in peace with the Lord,
without doing his command to the people, we should not have been their prisoners;
and therefore could not make any bargain with them.
Nevertheless, through the secret overruling power of the Lord, they set us at liberty.
All praise and renown be given to the name of our God, who liveth forever.
Amen.

But we were not above fifty yards from the guard, till Thomas Rudd sounded again;
and so we went towards the east gate; and before we came to the market-place,
John Bowstead preached to the people.

From thence we went towards the west gate, Thomas Rudd proclaiming his message,
and in the way a Presbyterian priest fell in with us; and walking behind John Bowstead,
put a young man upon moving some dispute with him:
and Robert Gerard and I being a little behind them, observed the priest, and his design,
and went up to him to wait his proposal to John Bowstead;
but in a short time he asked me by what authority
Thomas Rudd went through the town with that message?
I answered, that his question was not proper to me, since the man himself was present;
but said I, "`Thou thyself seems to be a teacher, by what authority dost thou preach?`"

"`We,`" said the priest, "`have an external call, and an internal call.`"
"`Where there is a call,`" said I, "`there must be a voice to give that call:
this call thou sayest is within;
what therefore is this in thee which calls thee to that office?`"
Upon this the priest demurred a little, and began to tremble,
for the binding power of the Lord was coming over him, but at length said,
"`It is by the light of God`'s grace.`"
"`Why then,`" said I,
"`dost thou oppose us for preaching the power and virtue of that light, which,
by thy own assertion, is able to qualify for the gospel ministry?
But withal, do not thou belie the grace of God,
in saying it has called thee unto that office, when in truth, it has not.
And beware how thou pretends to preach the light as the foundation of thy ministry,
lest thou bring thyself under the denomination of a Quaker.`"
Thus, by virtue of that light, I extorted a testimony to the same,
from him who came to oppose it, and the work of it in us.

The priest being under this circumstance, John Bowstead cried aloud to the people,
saying,
"`Observe the confusion of your Babylonish teacher;`"
and then opened several of their errors.
But the priest`'s familiars, seeing him out of countenance and in confusion,
would gladly have had him out of the crowd in which we were environed;
and some were observed to weep.
Others, being affronted at their priest`'s confusion, threw dirt in my face,
which reflected back on his; upon which he seemed to smile, expecting, it is like,
to be rescued from the just hand of truth,
by the power and industry of the stoners and bedirters among his hearers,
from whom he alleged his outward call.
Then said John Bowstead, "`Art thou a minister,
pretending a call by the light of God`'s grace, which teaches to deny all ungodliness,
and yet canst laugh at wickedness;
and see also the fruits of thy teaching among thy hearers,
who thus offer violence to strangers?`"
Upon which a party from the outside of the crowd, in a body,
pressed into the middle of them, where we were,
and so drove the priest quite out to the other side, and away he ran.
Then John Bowstead cried aloud after him, "`The hireling runs,
because he is a hireling;`" and after some exhortation to the people,
we went towards our inn, Thomas Rudd proclaiming his message.

No more violence was offered to us,
save only that a soldier threw a piece of hard earth from the guard-house among us,
which fell upon Robert Gerard`'s shoulder, but did not hurt him much.
The rage of Satan being overruled by the blessed power of God,
to whom be praise and glory forevermore, the inhabitants of Elgin became very calm;
and we, finding the concern to cease in us, went to our quarters.
But the concern returning on Thomas Rudd, and reaching me likewise,
we went out together towards the west gate; where he delivered his message,
without any opposition from any person by word or deed.
So we returned to the inn to our companions;
and after refreshment we departed in the justifying presence and peace of the Lord,
and went forward that evening to Forress; the whole time spent in Elgin, as aforesaid,
being about three hours.

At Forress we lodged at an inn kept by bailie Scot; who,
together with his wife and family, entertained us with friendly respect.
The next morning, being the 24th, we went through this town,
Thomas Rudd doing his message, as at other times, but no violence was offered by any.
That day one William Falconer, a relation of David Falconer, came to see us.
He was an Episcopal priest, and had been displaced some time before by the Presbyterians.
He was a comely person, and of an affable temper;
and I asked him why they had turned him out?
He replied, that it was for the original sin of Episcopacy.
They objected nothing against his morals; and for the maintenance of his family,
he would have conformed: but his father having been a bishop, they would not trust him,
lest Episcopacy should have become hereditary in him: but more of him hereafter.

The same day we went forward to Old Nairn, where we were concerned;
and Thomas Rudd warning them to turn from their evil ways unto the Lord,
they gave us full demonstration there was need of it, by throwing dirt and trash at us,
and using bloody speeches.
But the Lord preserved us from their evil, by his blessed truth, the greatest good;
unto whom, for the riches of his power, be honor everlasting.
Amen.

From Old Nairn we went to Nairn, where part of a regiment of dragoons were quartered;
and Thomas Rudd delivering his message, as at other places,
many of them followed us through the streets very soberly; one of whom, a corporal,
as I remember, so soon as he had seriously observed us, and heard the message,
held up his hand, and stretching it towards the people,
gave strict orders that neither soldiers nor
others should in any ways molest or interrupt us
which accordingly was observed, for all were very peaceable toward us.
As soon as Thomas Rudd had done,
a multitude of soldiers and town`'s people followed us to the door of our inn;
and there being out-stairs ascending to an upper room, John Bowstead stood upon the same,
and preached a considerable time to them; they generally behaving with friendly gravity,
with tears gushing into several eyes;
and the testimony of truth went freely and openly towards them.
And though the Lord had not hitherto opened my mouth in testimony,
so as to be termed a minister, yet my heart was full of the Word of Life;
and the love thereof went towards the people, as it were, unrestrained;
as it had done towards many others of that nation in that visit.

After refreshment at the inn, we went that evening to Inverness;
where some of the people taking us for Dutchmen, came to inquire after news,
martial affairs being then much in agitation between the French and confederates;
but finding what we were, their expectation failed.

The next morning, being the seventh-day of the week,
Thomas Rudd walked through the streets alone, very early;
and afterwards we went all up together in the market-place,
where there were many Highlanders in their usual dress, and armed; who,
together with other people, flocking about us, John Bowstead preached to them;
and the testimony of truth had fluent passage.
They were respectful above expectation; and when any boys, or other particulars,
moved the least incivility or light behavior towards us,
others were forward to correct and reprehend them.
And whenever we went out of our inn into the streets on any occasion,
the people flocked after us.

On the same day, in the afternoon, divers young men, of the better rank,
as they are accounted, came to discourse us upon several points of religion; to whom,
in the main, through the truth, we gave satisfaction; only one John Stewart,
a Presbyterian,
abruptly darted in a question about the Almighty`'s
decreeing some men and angels to eternal damnation.
I being most concerned at that time in discourse, declined that subject,
till other matters, more suitable for the auditory, were fully discussed;
and then I told him,
That it was more proper and necessary for him to make his own calling and election sure,
than to be too curious about questions of so mysterious import: and withal,
that he ought not to wrest the Scriptures, which were, in the main,
designed to remove these conceits of the Jews, that they were the only chosen of God,
by covenant with Abram and the fathers,
and through the mediation of Moses at Mount Sinai; by which they slighted Christ,
the elect seed of God, and the gospel of salvation offered unto themselves,
and the work of the same, at that time taking place among the Gentiles.
Those Scriptures in the Epistle to the Romans, then adduced,
having no relation at all to the decree of any particular man, or order of men, as such,
or angel, or order of angels, to destruction from eternity;
for that could never comport with the unchangeable and
glorious attribute of divine goodness,
essential to the Almighty: with some other matter suiting that point.
And the young man being frustrated of his expectation, went away in a sullen rancor;
not like one on the right-hand, if such a decree had been;
but the Lord preserved us in the spirit of meekness and charity.
This gave me occasion to observe how hard it is for such as
are prepossessed with anti-christian notions and conceits,
to embrace the truth, or apply themselves to virtue;
and how the enemy of their souls rages in their own hearts,
when any thing appears to discover his deceit in any measure; how, through envy,
moving the same in them, docs he blind their eye, and keep them in the dark,
to their utter destruction:
for no sooner can one offer to resist that notion of predestination, as they hold it,
or form an argument against it, how clearly, calmly, rationally, and truly soever,
but they generally fly up like fiery serpents, ready, through rage,
if it were in their power, to set the very course of nature on fire,
kindling it with the fire of hell.

On the seventh-day, at night, we remained under some exercise of mind;
and the next morning, went into the market-place, in the crossings of several streets;
and there, first Thomas Rudd, and then John Bowstead,
preached a considerable time to the people,
who were generally to come that way to their several sorts of worship;
and many of them stayed and heard with grave attention;
and are a people of an English demeanor and aspect.
In convenient time we retired to our lodging,
and in an upper room had a meeting among ourselves and some few more.
Our landlady not having been able to move out of her chamber for many weeks before,
came up to us, and stayed during the meeting, to her great refreshment and satisfaction,
as she openly declared soon after.
Glory be to the Lord,
who is ever ready to do good to all who faithfully wait on him for his pure grace,
and the virtue of it; which is able to refresh both soul and body,
when it pleases him to move by the same in his poor creatures.
Our meeting being over, which happened before others came from their several worships,
we were concerned to go to the steeplehouse; but as we were going down the street,
one of the civil officers being at the door went in, but suddenly returned,
and placed a hand on each side of the same; and when Thomas Rudd, who was foremost,
attempted to enter, the officer hindered him.
Thomas Rudd offered some arguments to induce him to admit us, but could not prevail,
saying he could not dispute with us, but there we must not come;
but gave us no hard words, nor showed any passion in his gesture.
They were Episcopalians, Presbytery not having overspread all ! the north at that time.

We walked to and again in the street, and many people came to us,
and several would have had us go to the Presbyterian meeting,
which was a little below in the same street; but having no concern that way,
we look little notice of them.
But the Episcopalians, soon after, coming from their worship, and very numerous,
Thomas Rudd moved into the street before them, with his arms spread abroad,
as if to embrace them, and spake to this effect.
That some of the apostles of Christ, coming to a certain place,
where other worship than what they then preached was exercised, had the privilege,
after such worship was over, to preach to and exhort the people;
and why might not we have the same among professors of Christianity!
And then went on with other matter.
The people generally stayed,
though the priest used some ineffectual means to make them depart from us;
knowing that if the truth, and the blessed work of it, once affected their hearts,
his gain, power, and glory, would soon be lost.

The people were extremely quiet and attentive;
and the priest seeing their inclination and resolution to stay,
went away with some few attending him, without offering any discourse to us,
or objection against what was delivered.

By the time Thomas Rudd had done, the Presbyterians came from their meeting, and were,
for the most part, to pass along the same street;
and whether they were so inclined or not, they could not but stay;
for the whole street was blocked up by the crowd.
When Thomas Rudd had done, John Bowslead spake to them in good authority,
but not very long; and towards the end, exposed the priest,
and the design of his ministry to the people; which being as a trade for maintenance,
would never profit them: and having cleared their minds of their concern for that time,
we went to our inn without any molestation.

Having dined in a large upper room, several military officers, namely:
lieutenant Livingston, lieutenant Alexander Frazer, ensign Cunningham, etc.,
who kept garrison there, desiring a little of our company, came to see us.
At their entrance into the room they saluted us in their manner, uncovering and bowing,
saying, "`Your servants, gentlemen.`"
And the presence of the Lord being over us, Thomas Rudd answered, "`Not our servants,
but servants of God, and fellow servants one of another for the Lord`'s sake.`"
Then they made an apology, saying it was their way of expressing their respect;
which we perceiving to be without mocking, little more was said on either side,
but all drawn in an instant into profound silence, by the invisible power of God;
and in a short space the room was full of people, and all sober,
like a meeting of Friends; and Thomas Rudd spoke to them concerning true silence,
and the worship of God in spirit, in the silence of all flesh,
and the imaginations and desires thereof; with some other things of that import.

After Thomas Rudd had done, John Bowstead preached to them, and then Thomas Rudd prayed,
and after him, John Bowstead prayed: and so the meeting ended,
all departing in a grave and serious frame of mind.
The officers took leave of us in a friendly manner,
and the company departed without any objection to what was said.

The next morning, being the second-day of the week,
as were about to depart towards Chanery, on the other side of Murray Firth,
the said officers came again to discourse with us and take their leave;
and as matters of truth and religion were opened to us, which was not sparingly,
we opened to them, and they seemed troubled to part with us, and took us by the hands,
praying that the Lord might be with and prosper us.
About the first hour that afternoon we arrived at Chanery,
but found no further concern on that side; and after a little refreshment,
we crossed the river, and that night lodged at Nairn.

That night Thomas Rudd became concerned to return to Inverness, to speak to the priest;
and in the morning he and John Bowstead went to that place, where Thomas Rudd,
as they said, warned the priest not to deceive the people any longer;
with some other matters of religious import.
The priest was indifferently patient;
but his clerk used some light and indecent expressions,
pretending to argue several points with them.
Their business was not to dispute at that time, but to deliver a message;
which having done they were clear.
But the people flocked about them as before,
with expressions of gladness at their return.

In the mean time Robert Gerard and I went to Forress,
where we had appointed to stay till they should return to us;
and finding a concern come upon me, I went to the house of William Falconer,
the priest before mentioned, and Robert Gerard with me;
and there was one that was steward to a nobleman with him,
and some others besides his own family.
He seemed to receive us with respect;
nevertheless in a short time there appeared a cloud of darkness.
I sat quiet and inward, and the truth arose as a standard against it,
and the opposing darkness vanished, and truth reigned in me.
Then I began to speak concerning the many divisions in the pretended Christian world,
the Papacy, the Prelacy, and the Presbytery,
with their several subdivisions and confusions,
which being de parted from the Spirit of Christ, the prince of Peace,
into the spirit of envy and persecution, were warring and destroying each other,
contrary both to the nature and end of that religion they profess, which is love.
I was answered, that the bishop of Rome, under pretense of being the successor of Peter,
and as such, infallible,
has usurped a dictatorship over the Christian world in matters of religion,
and imposed a multitude of anti-christian errors, by unreasonable force upon mankind.
But God having committed his whole will unto writing in the holy Scriptures,
and in the course of his Providence preserved them unto us,
we have our whole duty declared therein, as our rule and guide in matters of religion;
so that we are not to expect the manifestations of the Spirit as in times past,
that dispensation being now ceased.

I replied, that what he said of the bishop of Rome was true,
and that the Scriptures are the most excellent books extant; which were given,
from time to time, by the Word of the Lord, which is the Spirit of Christ.
But men may read and speak the truths contained in the Scriptures one to another,
and the readers and speakers remain still ignorant of the Word of the Lord,
and of the things themselves intended to be signified by the words;
and not being sent of God, as the Scriptures send no man, cannot profit the hearers,
but are themselves transgressors in so doing, unless they were sent by the influence,
power,
and virtue of the same Word that did dictate the matter
of the Scriptures unto the holy penmen thereof;
as appears by the 23rd chapter of the prophecy of Jeremiah:
and then I called for a Bible and read, "`The prophet that hath a dream,
let him tell a dream; and he that hath my word, let him speak my word faithfully:
what is the chaff to the wheat, saith the Lord.`'
Is not my word like a fire, saith the Lord;
and like a hammer that breaketh the rock in pieces?
Therefore, behold, I am against the prophets, saith the Lord, that steal my words,
every one from his neighbor.
Behold I am against the prophets, saith the Lord, that use their tongues, and say,
He saith: Yet I sent them not, nor commanded them;
therefore they shall not profit this people at all, saith the Lord.`"
So that it is contrary to the declared mind of God,
that any should use his words to others as his ministers,
who are not sent by himself so to do; for though they have been his words unto others,
those who use them without his command, are charged by him as thieves;
especially such as make merchandize of them to the people.

As to the dispensation of the Spirit being now ceased, I am sorry to hear it is so;
for I can show thee to whom it is so ceased, but not to the church of Christ:
then I turned to the third chapter of the prophecy of Micah, and read, "`Hear,
I pray you, O heads of Jacob, and ye princes of the house of Israel,
is it not for you to know judgment?
Who hate the good and love the evil; who pluck off their skin from off them,
and their flesh from off their bones; who also eat the flesh of my people,
and flay their skin from off them; and they break their bones,
and chop them in pieces for the pot, and as flesh within the caldron.
Then shall they cry unto the Lord, but he will not hear them;
he will even hide his face from them at that time,
as they have behaved themselves ill in their doings.`"

Here it appears, that for the ignorance, cruelty,
and injustice of the princes or heads of the people,
the Lord would not hear or regard them.
Again, in the 9th verse, the Lord resumes his charge against the great men in that day;
"`They abhorred judgment, and perverted all equity: they built up Zion with blood,
and Jerusalem with iniquity: the heads of that people judged for reward,
their priests taught for hire, and their prophets divined for money;
yet they pretended to lean upon the Lord, and say.
Is not the Lord among us?
No evil can come upon us.`"
But the Lord was not to be mocked by such;
his just judgments were denounced against them; "`Therefore shall Zion, for your sakes,
be ploughed as a field, and Jerusalem shall become heaps; and the mountain of the house,
as the high places of the forest.`"
This was fulfilled upon them, and remains over them, as a monument of the justice of God,
unto this day.
The charge of the Lord, and his judgments against the prophets, I left to the last, viz:
"`They made the people err; they bit with their teeth, and (yet) cried peace;
and he that put not into their mouths, they even prepared war against him:
therefore night shall be unto you, that ye shall not have a vision;
and it shall be dark unto you, that ye shall not divine;
and the sun shall go down over the prophets, and the day shall be dark over them.
Then shall the seers be ashamed, and the diviners confounded; yea,
they shall all cover their lips, for there is no answer of God.`"

Now as to these Scriptures, said I, like sin, like judgment.
All these three divisions of the pretended Christian church,
failing into the sins of the old heathens, are become hateful, and hating one another;
and through that hatred,
have persecuted and destroyed each other when and wherever they have had power.
And all these in their turns, having deceived and subjected the temporal powers,
have persecuted and destroyed the church of Christ among them.
"`They have hated the good, and loved the evil.`"
They have exercised such cruelties upon the innocent
and just as are here figuratively termed,
plucking off their skin and their flesh, and the breaking of their bones, and the like.
The priests of every form have fleeced the people and the church of Christ,
which they have not fed; they have made laws by their own power, against them,
and thereby made war against such as would not gratify their covetousness;
they have worried them as with their teeth,
and yet cried up the peace of the gospel in words;
they have built and propagated their several sects and parties with the blood of others,
and of the saints of God; and have filled their sanctuaries with evil-doing and fraud.
Their heads, who lord over them, have exercised their offices for gain and pay,
their priests teach for hire, their prophets divine for money;
yet they pretend the Lord is with them in their various and opposite ways,
and that no evil can come upon them.
And yet, though the day of the gospel of Christ be dawned upon his church,
and the Sun of Righteousness arisen and shining in her, yet the night of apostasy,
and mist of thick darkness and ignorance is over these.
They have no vision of God; they cannot divine; the sun is set unto them,
and the day is dark over them.
For the light thereof they despise and hate, because they are evil-doers,
and to them there is no answer of God.

But the church of Christ here speaketh another language; she bears another,
a true testimony to the true God.
"`But truly I am full of power, by the Spirit of the Lord, and of judgment, and of might,
to declare unto Jacob his transgressions, and unto Israel his sin.`"
Here it is apparent from whom the Spirit of the Lord is departed,
and to whom he is not now revealed, and in whom he does not reside; that is,
Mystery-Babylon, with all her divisions, subdivisions and members, everywhere,
and under whatsoever name: but God is with his people still, as in former times,
according to the promise of the Son; "`If a man love me, he will keep my words;
and my Father will love him, and we will come unto him, and make our abode with him.`"

The auditory heard what was said with patience, and none made any answer but the priest;
and all that he said was, and that a little pleasantly, "`Such as you,
going about with such chapters, may do much mischief.`"
To whom I replied, that in as much as he was then silenced by the temporal powers,
he would do well never to look after that employment any more,
or think to enrich himself thereby; and the rather,
since he had a competent estate independent of it;
which the Lord would bless to him and his family,
if he disclaimed that ungodly practice of preaching for hire,
and was silent in the things of God till the Lord should send him,
if it might please him so to do.
The priest`'s wife seemed well pleased with what I said to him, and he made no reply:
and so a little after we departed in peace, and in friendship with them,
and went to our inn.

Soon after came Thomas Rudd and John Bowslead back to us from Inverness;
and the next morning being the 1st day of the first month, 1693, we went to Elgin;
and thence to Fochabers, or Castle-Gordon, and there we lodged;
and in the morning Thomas Rudd and John Bowstead went through the streets,
Thomas Rudd delivering his message, as at other places; and from thence we went to Keith,
where he did likewise.

On the 4th day of the first month we came back to Urie,
where we had a meeting among Friends, as in divers other places,
from whence Thomas Rudd went back to Aberdeen, and John Bowstead and I went to Edinburgh.
But as we were by the ferry, in order to our passage to Leith,
there came a concern upon us, and we observed several persons,
who were to be passengers with us in the same vessel.
As we were putting off from the shore,
some discourse was moved by way of opposition to us in matters of religion.
He that managed against us we found, by his way of reasoning, was a priest;
who finding us very sharp upon him,
and how little impression his reasonings and imaginations made upon us,
he fell into so great a rage, that he commanded us to be silent,
and the skipper to put us on shore, for we were not far from it.
"`Thou art under a mistake,`" said I;
"`thou art not now domineering over a few poor parish people,
who dare not speak the truth; we are not to be silenced by thee,
nor put out of the vessel by any, since we have agreed for our passage,
and are already in possession.`"
This being said with the authority of justice,
neither he nor any other said any more of turning us out;
but the contest was renewed in matters of religion.
After some observations on the several ways of worship in the world,
I fell upon some reflections on such as shifted from one form to another,
and would hang the cloak on either shoulder for advantage and honor among men.
This proved, though an arrow at adventure, to hit the mark;
after which the rude and boisterous spirit of the man became more humble,
and we came over him by the Truth;
who is always near to guide and strengthen such
as wait on Him for strength and direction:
to his glory be all things.

As there came a calm over this evil spirit, there came a calm likewise upon the water;
so that we were a considerable time upon it,
and had much discourse of religious consequence.
All in the boat were quiet and nearer us than at first,
and the priest himself began to commend love, and grew very kind to us;
and when we came on shore he took us by the hand very lovingly, wishing us well;
and we likewise parted with all the rest in friendship.

After this, as we were going up the high street of Edinburgh,
towards our meeting near the West-port, we saw the priest again;
and inquiring of a Friend who he was, he told us his name was James English,
who had once been a Presbyterian minister,
and had also showed some love for truth and Friends, and had read our books;
but persecution rising hot, in king Charles`'s reign,
by the Episcopalians against the Presbyterians,
he had thereupon transformed himself into the likeness of an Episcopalian; and now,
when Presbytery had again prevailed,
he had changed the cloak again to the other shoulder,
having a kirk without the West-port of Edinburgh, not far from the place of our meeting.
In those days change in government did not alter men`'s behavior towards us,
but we were rudely pelted with stones and dirt, and otherwise abused in our meetings,
and in our passage along the streets to and from the same,
by a miserable wretched rabble,
through the connivance of the magistrates of every notion and profession;
who perverted and misapplied, or willfully neglected their offices.

Observe then a twofold transforming:
a transformation of the adversary into the likeness of
an angel or messenger of light and truth inwardly;
and of his ministers into the likeness of the ministers of truth outwardly.

And as Satan will transform every way, to save his kingdom in man, till,
by the stroke of the judgment of the Almighty, he be destroyed in all who believe in God,
and in Jesus Christ the Son of God, and obey and keep his commandments;
so will those priests of antichrist, of every form and notion,
turn every way to save and support their worldly power, pomp, grandeur,
and unjust maintenance,
till the sword of the mouth of the Lord rescue his people and children from under them,
and by the breath of his mouth they be swept into the ditch.

"`For they, the blind shepherds of mount Esau, have troubled Jacob,
and led and drove the stranger out of the way;
therefore is the hand of the most high God against them,
and the day of mourning is near upon their dwellings.`"
Amen.

On the 13th we went to Linlithgow, and that evening had a meeting among Friends there.
On the 15th we went to Hamilton and had another; and on the 18th to Glasgow;
and on the 19th, being the first-day of the week, we had a meeting with Friends.
But the Presbyterian provost or mayor,
notwithstanding the establishment of liberty of conscience in matters of religion,
sent three of his under officers to disperse the meeting;
but the power of Lord being over them, they were overawed thereby for some time,
till one of them more hardened than the rest,
laid hold on one of the Friends belonging to the city,
and haled him out of the meeting-house; and then the other two,
by his example laid hands on other Friends, and look several more out.

At length, they laid hold on Hugh Wood, gardener to the duke of Hamilton,
a grave and religious man, whom they forced towards the door; but suddenly turning,
he twisted himself out of their hands, and sat down where he was before.
Then several other Friends came in again, and so the meeting continued;
and through the good presence of the Lord,
who never fails his people in the needful time,
we were much comforted and strengthened against all their disturbance.
When they saw they could not prevail that way, they used threats, saying,
"`It is upon the stroke of twelve, and the kirks are ready to break loose,
and if you be not gone before the rabble come, they will tear you in pieces,
and we shall not be able to hinder them.`"
Then said John Bowstead, "`Do your kirks consist of rabble,
that they will come with such violence so soon as the clock or dial assigns the hour.`"

But the Lord was pleased to afford his blessed presence to us,
and thereby to continue our meeting till their kirks were broken loose,
and their rabble came, but were chained by the invisible power of the glorious God.
They had no power to hurt us; for some were on our side, though others against us.

Then the meeting went to prayer along with John Bowstead,
and one of these disturbing officers attempted
to stop his mouth with his hand several times;
but being overawed by a power of which he was ignorant, he could not.
When the prayer was ended we went through a narrow lane filled with the rabble,
and then through a great multitude of people in the street, without any harm;
so good was the Lord to us,
in preserving us from the cruelty of that self-righteous and persecuting generation:
yet a better disposition appeared in many among them,
which was obvious by their countenances and behavior.
That afternoon we went back to Hamilton, where we found Thomas Rudd,
come after us from Aberdeen;
who had been through the streets with his usual message the same day;
and we were told by some we met in the way, who were not Friends,
the people had abused him very much.

A little after we came to town the concern returned upon him, and reaching us,
with several of the Friends there, we went all into the streets two by two,
each two at a little distance from the other,
and Thomas Rudd proclaimed the same warning as before;
upon which a multitude of people issued into the streets, and were indifferently sober,
till the town officer came in a barbarous and furious manner,
and laid hold on Thomas Rudd, commanding him to go to his quarters,
otherwise to the Tolbooth, their prison-house.
The rudeness of this man in the presence of the multitude so encouraged the baser sort,
that they fell upon us, and inhumanly abused us, but especially Thomas Rudd.
The most active in this shameful work were mostly of
that furious sect of Presbyterians called Cameronians;
and among others, there were a town officer,
and the sons of a deacon of the Presbyterian church at Hamilton.
Thomas Rudd not having fully delivered his message,
which he always continued everywhere till the people were quieted,
went again down the high street.
Upon which the officer put him in prison; and John Bowstead, Hugh Wood,
James Miller and I, went with him, with design to accompany him in his imprisonment;
but the rabble furiously pushed John Bowstead from the door down the stairs,
pulled off his hat, and trampled it under foot;
and some of them fixing their hands in his hair, dragged, beat, and abused him,
till several, touched with compassion, cried out murder;
and some young men of a more noble disposition, particularly one Thomas Kirkbarns,
rescued him from them.

They dragged James Miller, one of their neighbors, back from the prison door;
and throwing him upon the ground, beat, abused him, and brake his nose,
thereby shedding his blood: also they pushed, haled, tossed,
and abused Hugh Wood very much; which was the more inhuman, he being an ancient man,
a neighbor, and had not said any thing to provoke them,
unless to persuade them to moderation.
Some of them pushed me from the prison door to the foot of the stone stairs,
which were on the outside, with great fury, and bruised my left side against the stones,
though I had said nothing to them.

In the mean time John Bowstead called for the chief magistrate,
that if he had any thing to object against us, we were willing to answer him;
whereupon came David Marshall, eldest bailie, and desired us to go into his house,
which was over against the prison, till the rabble dispersed.
But he did not make any use of his authority as
a magistrate to disperse and appease them;
so far from it, he suffered one of his own servants to be active in this work.
The others, who threw dirt and stones at us, calling us dogs,
and other reproachful names, were generally the wives, sons, daughters,
and servants of the magistrates, merchants, and manufacturers.
Thus ended their sabbath day`'s work; though one of their pretenses for using us thus,
was, that we had broken the sabbath by going through the town in that manner.
Whether we, who were there on the Lord`'s account, to warn them to turn from evil,
or they who thus abused us on that day, which they call the sabbath,
did more break the sabbath, let their actions and ours demonstrate:
and whether magistrates countenancing evil, and taking part with the evil-doers,
be not false to the trust reposed in them,
preverters of the good end of their appointment,
and guilty of all the evil they might restrain, or punish,
we leave to the Lord to determine in his own time and way, by his unerring justice,
against that and such a magistracy.

The next morning Thomas Rudd and John Bowstead
were concerned to go through the same town again,
where they met with like entertainment; some of the rabble taking off Thomas Rudd`'s hat,
dashed his eyes, face, and head over with dirt taken out of the stinking kennels;
and having thus deformed him, they cried out, "`He looks like a devil!`"
Then Thomas Rudd, going to the house of a Friend, washed himself;
and going down the street again with the same message,
they renewed their cruelty as before;
particularly one Robert Hamilton and his two sisters, Anne and Rebecca,
gave threatening speeches, the latter saying,
she could find in her heart to kill Thomas Rudd with her own hands.
This Robert Hamilton, when I desired to reason with him, why he,
a professor of Christianity, which teaches love even to enemies,
would so much abuse us who were their friends, and come in Christian love to visit them,
and encourage others also in the same work, peevishly turned from me,
saying he would not converse with the devil.

Thomas Rudd going down another street, the rabble attempted to put him into an open well;
but being prevented by some more humane than the rest, they tore his hair from his head,
and beat him, and also the rest of our Friends accompanying him, with great severity,
and dragged them into the market-place; where they might have done more mischief,
but that Thomas Edgar, a young man of commendable deportment,
with some other sober and well-minded persons, of the Episcopal way, I suppose,
cried out, "`Shame on such actions;`" and used some endeavors to restrain them.
Thus we see the Lord, either immediately`' or instrumentally, or both,
is ready to deliver from cruelty, and to bear up the minds of his servants,
acting in his will under the same: to him be dominion and glory forever and ever.

The same day John Bowstead and I went to a meeting at Shatton-Hill,
which had been appointed before, leaving Thomas Rudd at Hamilton,
from whence he purposed to go for Ireland; but that day he went through the town again,
and the inhabitants became more sober;
and the next morning he visited them in the like manner, and they were all still,
and came not out any more to molest him.

And then finding his concern in that place to be at an end, he departed in pence.
But before I departed that town, I wrote a few lines to the above named Robert Hamilton,
in this manner:

[.embedded-content-document.letter]
--

[.salutation]
Robert Hamilton,

I understand thou art a person professing Christianity,
which is the highest excellency named among the children of men;
but how far thou art short of that life of love inseparable from every true Christian,
thy deportment to my friends, the servants of the Most High, and also to myself,
in the streets of Hamilton, does sufficiently demonstrate.

--

I also wrote to the inhabitants who had abused us as aforesaid, in these words,
from the mind of the Lord, viz:

[.embedded-content-document.epistle]
--

[.letter-heading]
To the Presbyterians of the Town of Hamilton.

How long will you do wickedly?
How long will you stone and abuse the servants of the Most High,
who are sent to you for peace and reconciliation?
How long will you trample under foot the blood of the everlasting covenant,
and adore your own inventions?
How long shall the wooings of the Highest be despised?
Shall eternal judgment terminate your wickedness?
Or will you escape by obedience to the gospel of peace?

Anger remains in the bosom of fools; and do your actions bespeak you wise?
Has the Lord left you to the counsel of your own will;
or is there yet hopes of redemption for you.

Surely the Lord is displeased with your doings,
because you hate the counsel of his love.
How far distant is persecution from the everlasting gospel of peace?
And how evident demonstration you gave last night and this morning,
that the prince of the power of the air, Apollyon the destroyer,
who reigns in the hearts of the children of disobedience,
also rules and rages in your hearts, I leave with you to consider;
that if yet there remains any place of repentance, you may lay hold of it,
and escape the unspeakable misery that is hastening upon all the workers of iniquity,
how well soever covered with a mask of profession.

I am, through Christ, a lover of the souls of all,
whose day of visitation is not already over,

[.signed-section-signature]
Thomas Story

[.signed-section-context-close]
20th of the First month, 1692.

--

On the 22nd of the first month,
John Bowstead and I had a meeting among a few Friends at Drumlanrig,
in the house of James Wood, gardener to the duke of Queensberry;
and on the 24th we went home to our several habitations,
John Bowstead to his family at Eglinby, in Cumberland,
and I to my father`'s house at Justice-town, in the same county,
being safely conducted and preserved through all dangers by the arm of Lord;
whose name is becoming dreadful among the nations.
Unto him be the honor and glory of all his great works and goodness, forevermore.
Amen.

About this time some of the parishioners of Scaleby, in Cumberland,
were convinced of the truth, and Nathaniel Bowey, being priest incumbent there,
wrote a letter to them, containing several invectives,
false accusations and reproaches against Friends and the divine light we profess,
as likewise heterodox opinions, and false doctrines; which I answered.
But neither the letter nor answer were printed.

The time of the county meeting for Cumberland being come, John Banks, that good, old,
and valiant soldier and warrior for truth on earth,
offered his service as a representative from the county to the yearly meeting at London,
then approaching; and the meeting thought fit to name me for the other,
though I did not deem myself qualified for that charge.

But the meeting insisting upon it, I yielded; and the rather,
since I was to go with a companion so experienced and able in that service.
We set forward on the 11th day of the third month, 1693;
and by several stages and meetings went to Waltham Abbey on the 23rd;
and on the 28th to the house of our friend George Barr, in Berry street, in Edmonton.
Here we had the satisfaction to meet with our eminent and honorable friend William Penn,
which was the first time I saw him; and with whom, at that time,
I contracted so near a friendship in the life of
truth and tendering love thereof in many tears,
as never wore out till his dying-day; and in which his memory still lives,
as a sweet fragrance in my mind, as a faithful servant of the Lord,
a man of God indeed in his time,
and of whom I shall have occasion to make further mention in the sequel.

On the 4th day of the fourth month we arrived at London;
and the Lord gave his church and people, there assembled from all parts of the nation,
and from Scotland, Ireland, etc.,
many comfortable seasons of his divine life-giving presence, to our great edification,
confirmation, and rejoicing;
where I became nearly acquainted with divers of the most eminent elders of that day,
both in the city and country, to my great satisfaction, and to theirs also;
for mutual love and esteem were not wanting, but adorned our conversation,
as in the primitive times.

In a particular manner I became nearly united in the divine love and life of truth,
with my much esteemed friend Thomas Wilson, then of Cumberland,
and afterwards of Ireland;
who was to me the most able and powerful minister of the Word of Life in the age;
and whom I had seen but thrice before; once in Cumberland,
before he went the first time to America in the service of the gospel;
the second time at a county meeting in Cumberland,
the same day he and James Dickinson came into that county,
in their return from America through part of Scotland,
a little before the said yearly meeting at London; and the third time at that meeting.
James Dickinson, his usual companion, being engaged another way,
he accepted of my company in visiting the west.
We set forward from London on the 24th day of the fourth month,
and that day had a meeting at Uxbridge; and on the 26th at Wickham; and so by Oxford,
where we had a comfortable, open meeting; for though many of the collegians were there,
who used to be rude in an extraordinary manner,
yet the invisible power of the Word of Life being over them at that time,
they were quiet under the testimony thereof,
in the authoritative ministry of Thomas Wilson;
whose voice was as thunder from the clouds, and with words penetrating as lightning,
saying, "`It is the pride, luxury, and whoredoms of the priests now,
as in the days of Eli the high priest, which deprive them of the open vision of heaven.`"
Upon this many of them were struck with amazement and surprise,
and their eyes were filled with tears; so that several of the elder sort retired,
but in a decent manner, as if to hide the effect of truth; which, if they had stayed,
could not have been concealed; but above all the rest, a very comely youth, who,
by his appearance and behavior, seemed to be the son of some noble person,
was most deeply affected.

On the 28th we went to Cownallius, to the house of our friend Giles Fettyplace,
a gentleman of a considerable estate, who had embraced the truth in early days;
whose company, together with his family, we had next day at a meeting at Cirencester;
and from thence, on the 30th, we went by Cuckerton, Tedbury, Didmartin and Sedbury,
to Bristol.

Here we stayed till the 2nd of the fifth month, where the Lord gave us glorious times,
in the sensible enjoyment of his divine and soul melting presence,
to our general and mutual consolation.
In those days Friends were near the Lord, and to one another in him;
and the canopy of his love was over us, and we rejoiced together therein,
but with holy fear, and with trembling; and had often occasion to say,
concerning the way of the Lord, as of old, and with respect to his noble servant,
that he "`maketh his angels spirits,
and his ministers a flame of fire;`" for so he was indeed, in an eminent manner,
to the churches where he came in this visit, as generally elsewhere at other times.

On the 2nd of the fifth month we had a meeting at Frenchay,
and that evening returned to Bristol; and on the 5th we had one at Posset,
in Somersetshire, and the same day returned to Bristol, where we remained till the 12th,
having other meetings there.
Thence we went to the meeting at Bolion,
and that night were at the house of our friend Richard Vickris, at Chew;
where we were kindly entertained.
He was a gentleman of a considerable estate, and had, at that time,
a numerous and hopeful family of children;
and they were a family of love indeed among themselves, and to Friends in general.
They loved, and were beloved.

The next day we returned to Bristol, to the meetings there,
and on the I.5th went to Bath, and were at their meeting; and from thence,
by Phillips-Norton to Warminster, where the Lord favored us with his divine presence,
and the gospel was preached by my companion,
in the demonstration of the wisdom and power of the Word of Life,
to the admiration of many who were not of our communion,
and to the consolation and edification of the gathered of the Father.

On the 17th we went by Bratlon, to Thomas Beaven`'s, at Melksham, and on the 18th to Cain;
where we had a large and glorious meeting with Friends.
Many strangers being there, they were much satisfied in a general way,
with what they heard; and one among them particularly,
thinking himself a competent judge of doctrine, and coming with a design to carp,
was disappointed; for he confessed he could not find fault with one word; but said he,
"`he exposed the errors of o u sect to the auditory.`"

The next day we went by Chippenham and Slattenford to Marshfield,
and on the 19th returned to Bristol where we stayed till the 24th,
and then had a meeting at Thornbury, in Gloucestershire; and on the 26th at Ross,
in Herefordshire, and on the 27th at Hereford on the 28th at Leominster,
and on the 29th at Bromyard.

On the 1st of the sixth month we were at the meeting at Worcester,
and next day we went by Bendley, Stourbridge, Newin, Newport, Nantwich, Middlewich,
Northwich, and Warrington, to Sanky, where we had a meeting;
and on the 6th to our ancient and honorable friend John Haddock`'s, at Coppull;
and so through Preston, Garstang, Lancaster, and Kendal, to Penrith;
from which my tender and fatherly companion went towards Hartly Hall,
and I returned to my father`'s house.

As to my own condition and circumstances in this journey;
before this time I was favored with the knowledge and enjoyment of the life of truth;
I had delighted therein above all things, and thereby was reduced to a state of silence;
not willing to interrupt the sweet and divine pleasure of his presence by
any needless and unprofitable talk upon mean and trifling subjects,
which I observed many were ensnared in.
I was still so preserved as in a state of childhood in the truth,
without the least apprehension of any censure.
For though I usually sat with my companion in the meetings,
and was constantly much broken and tendered from time to time, with many tears,
not of sorrow, which I had known long before, but of joy and satisfaction unspeakable;
I never considered what any might think concerning me, as to the cause of my weeping,
or of any expectation they might have of my appearance in a public ministry, often,
if not always, accompanied with such indications in the beginning of that concern.

Though I knew the Lord had called and begun such a work in me,
yet I had never met with any thing so great a cross to
my natural disposition as speaking in public;
and if I might have continued to enjoy the good presence of the Lord any other way,
or on any other terms, I had never submitted to it:
but those divine wages I could not live without;
the countenance of the Lord was become my all, and too dear to part with; and therefore,
at length I yielded, without any human considerations or views.

But it is not to be forgotten, that from the last time of our leaving Bristol,
every stage we journeyed northward my mind became darker and darker,
and the thoughts of returning to my father`'s house became loathsome and burdensome to me,
and even intolerable.
Before I got thither, I was greatly clouded,
as if a thick fog of darkness came over my mind; and then I mourned,
looking back to times past, recounting every step,
and the several views and openings of the things of God and his counsel,
which I had seen and enjoyed in the several meetings in this journey; and how the Lord,
who is a Spirit, exhibits the matters and things of his kingdom in the pure mind,
which is spiritual, and impresses it with a necessity of uttering them;
qualifying and assisting the instrument which he chooses,
to bring them forth in an apt and intelligible manner, for the information, help,
and consolation of those that hear and believe; whether in doctrine,
exposition of the holy Scriptures, reproof, instruction in morals,
or whatsoever tends to the convincement of unbelievers, confirmation of the unstable,
edification of the church and body of Christ, and perfecting the sanctified in him.

Being fully convinced I had fallen short of my duty,
by neglecting to utter the first sentences which had
been impressed upon my mind in several meetings,
not thinking them of sufficient weight and importance for public service;
and now plainly perceiving,
that through want of obedience in that which was first required,
I had been precluded from any further progress,
the whole depending upon the due order and connection of the parts;
and in consequence of my disobedience,
having been deprived of all sense of the divine presence for many days,
and destitute of all comfort, save a little secret hope,
that the Lord might mercifully return, I resolved that if it might so please him,
I would then obey.
I deeply mourned for some weeks, till all hope was near vanishing,
the heavens became as brass, and shut up as with bars of iron,
and nothing remained but a bare remembrance of former enjoyments and things,
where the true idea was wanting; which nothing can give, restore, or continue,
but the divine Truth himself, by his own presence and power.

But notwithstanding all this, when the Lord did again unexpectedly appear,
as divine love and light in my heart, and new matter presented in my understanding,
I found that state so comfortable and pleasing,
that I thought nothing could be added to my enjoyment by uttering it in words,
while in that condition; and so let the proper time of moving therein slip over.
The duty being anew neglected, I again fell short of a settlement in the divine presence;
and when that was withdrawn, condemnation only remained,
as due to my fresh disobedience and neglect;
and then I was surrounded again with horror and despair,
as if that had been the last call of the Lord,
and latest offer of terms of divine peace and salvation;
and my soul mourned again unspeakably.
Then I understood the language of the apostle Paul, when he said,
"`Woe is unto me if I preach not the Gospel.`"

While I was in this condition, my beloved and much esteemed friend Thomas Wilson,
imparted to me his intention of visiting the churches in Ireland, desiring my company;
but having so thick a cloud over my mind, and little love then appearing in me,
either to him or any other particular, or to mankind in general,
I did not think myself worthy, or in a condition for such an undertaking.
Besides, I was at that time unprovided with money and other necessaries for the voyage,
and for so long a journey; and the latter I made use of as an excuse for the former,
and so declined it.

But though this cloud remained over me for a time,
laying me under a necessity to stand still, to see what the Lord would please to do,
yet his never-failing goodness and mercy did not finally leave me,
but remained as withdrawn behind the thick veil, hid from me only for a season;
for in another meeting in Kirklinton, in Cumberland, on a first-day, some weeks after,
the Lord returned in peace and reconciliation,
and his divine countenance shined again upon me, whereby I was enabled to resolve,
that if the Lord moved any thing then, as in times past, I would obey.

Soon after that resolution was firmly settled in my mind, these words sprang therein,
"`It is a good day unto all those who obey the voice of
the Lord;`" and as they settled in my mind,
with the presence of the Lord remaining, I stood up and uttered them in his fear,
with a voice just so audible as that the meeting generally heard.
No sooner were the words uttered, than my soul was increased in joy unspeakable,
which was followed with a flood of tears;
and the meeting in general was immediately affected the same way,
as a seal of the work of the Lord thus brought forth in me;
and all were silent under the canopy of the divine presence for some time.
At length John Bowstead, having had a particular concern to come to that meeting,
about eight miles from his house at Eglinby,
stood up in testimony to the truth of what I had uttered,
making it the substance of what he said, to general edification;
as a father taking the weak by the hand,
and helping forward in that exercise in which I had been long waited for,
and expected by Friends in general in those parts.
The Lord favored us with the enjoyment of his divine presence that day.
