== Chapter VI

I now turned my face towards America, and think proper to go back in point of time,
in order to relate how my concern for that part of the world began in me and increased.
In the year 1693, towards the latter end of autumn,
as I was riding alone in an evening in Cumberland,
the power of divine truth moved upon my mind,
and my heart was greatly tendered before the Lord; and the Word of the Lord opened in me,
saying, "`Behold, my visitation cometh over the western parts of the world,
towards the sun-setting in the time of winter.`"
And I was greatly comforted in the words of his holiness.

From henceforth I was often tendered in spirit, in remembrance of the western world,
in a sense of the love and visitation of God to a people there, whom I had never seen;
which was more and more renewed and settled upon my mind,
and frequent tenderings and brokenness of heart,
under the holy influence of the divine presence, until the year 1695;
when at the house of our friend John Whiling, at Wrenton, in the county of Somerset,
upon a visit to Friends in those parts with Aaron Atkinson,
looking upon a map of the world, especially upon the south-westerly parts from England,
the power of the Lord suddenly seized my soul,
and his love melted me into a flood of tears.
But hitherto I knew not that the call of the Lord was to me to visit those parts; though,
from henceforth, I began to he afraid of it.

In the time of the yearly meeting at London, in the Bull and Mouth,
Aaron Atkinson being concerned in prayer, among other petitions to the Lord,
prayed for the western countries, and places beyond the seas,
that the Lord would please to send forth his ministers in the power of his Word,
to publish the day of glad tidings more and more among them.
Upon which the power of divine life moved sensibly in my heart, and the concern,
secretly begotten in my soul, now began to appear;
and after that great heaviness and fear came over me.

The same day, after the meeting,
several Cumberland Friends and others being together after dinner,
some of those countries being mentioned by one of the company,
the Word of Life moved powerfully in my soul,
with open assurance of the call of the Lord to
me to visit some of the American countries.
I was exceedingly broken, to the tendering also of most of the Friends there,
yet I was silent as to the particular matter,
being willing to conceal it as long as I could,
since no time was then fixed when I should move forward therein.
And being young and weak in the exercise of the ministry,
and having no opinion of my own abilities of any kind,
I urged it before the Lord as a reasonable plea, as I thought, against it at that time.

At London I remained for some time,
and entered into some writing business for necessary subsistence;
but before the year ended I suffered much in spirit, by reason of my confinement thereby.
But, though loath to leave all, for it was no less than life,
and all that was near and dear in the world, yet, finding my concern remain and increase,
I yielded at length, in the secret of my mind,
to answer the call of the Lord to that part of the world.

Here it may be regular to mention my companion, Roger Gill,
and how we came to be concerned together in this work and service of the gospel.
Sometime about the first month in this year, before I went into Ireland,
we being together at a meeting at the Park, in Southwark,
and each of us having had some service there,
I found my mind very free and open towards him,
and discovered something of my concern to him for America,
as we went together into the city;
and asked him if he knew of any ministering Friend concerned for those parts,
for I wanted a companion.
To which, being silent for some time, he replied,
"`It is now long since I was first concerned that way, and the last night, in my sleep,
was as if making all things ready for my voyage.`"
To which I replied, "`Is it no more but a dream yet?`"
And so we left it for that time.

Afterward, going to a meeting at Enfield, he overtook me in the way;
and we having some more discourse on that subject,
he told me it would be the seventh month at soonest before he could be ready;
for he had his wife and family to put in a way of living,
not knowing whether ever he might see them any more.
We had not much more discourse of it at that time,
and soon after I set forward for Ireland, as before related.

At my return to London from Ireland, Roger Gill was waiting at my lodging for me,
and said, he had made some progress for America: for the thing abiding with him,
he had acted in all things as though we had fixed the time before I went to Ireland.

After I had visited some meetings in London,
I became greatly laden and concerned in spirit,
and pressed to move forward on my intended voyage;
and hearing of a Friend that was to sail in a short time for Virginia, viz: William Cant,
commander of the Providence of London, my companion and I went together on board,
to view the ship and accommodations: at which time,
being retired in my mind as we sat in the round-house,
the divine love and life of the Lord Jesus moved gently in my soul,
and sweetly comforted my heart; whereby I was confirmed in my calling and undertaking:
so that for that time all the loads and weights were removed.

Having made our concern known to the brethren at the morning meeting, London,
they encouraged us; and provision being made,
both by the body of Friends and many particulars,
of everything needful for our voyage and journey, on the 10th day of the ninth month,
1698, in the evening, we went on board near Deptford, in the river Thames,
accompanied by several of our dear friends and brethren.

Being together in the great cabin,
the good presence of the Lord commanded deep and inward silence before him,
and the Comforter of the just brake in upon us by his irresistible power,
and greatly tendered us together in his heavenly love,
whereby we were melted into many tears.
Glorious was his appearance, to the humbling of us all,
and the admiration of some there who did not understand it.
In this condition we remained for a considerable season,
and then William Penn was concerned in prayer, for the good and preservation of all,
and more especially for us then about to leave them;
with thanksgiving also for all the favors of God,
and for that holy and precious enjoyment, as an addition to his many former blessings.
When he had finished,
the Lord repeated his own holy effusion of divine
soul-melting love upon the silent weeping assembly,
to the full confirmation of us more immediately concerned,
and further evidence to the brethren of the truth of our calling.
In this love unfeigned, and tender condition of soul,
we embraced each other to our mutual satisfaction;
for the same powerful love of truth that makes us loath to
depart from the friends and brethren of our native land,
drawing us to remote parts of the world, and remaining in our hearts,
gives courage and strength to leave all, and follow the Lord wheresoever he will.
We looked after them so long as we could see them; not with minds to go backwards,
or with any desire now to return, but in the comfort of divine love;
which neither distance of place, or number of years,
shall ever be able to obstruct or deface, as we keep true to the Lord in ourselves.

We did not arrive at Gravesend till the 12th of the month,
and next morning took coach for Rochester,
accompanied by the master of the ship and some other Friends,
and there we had a large and comfortable meeting.

Next day we went on board, but did not arrive in the Downs till the 18th;
and the wind being contrary, and very high, we remained on board till the 20th,
which being the first of the week, and we willing to have a meeting at Deal,
the master took the boat and hands, with a sail, to put us on shore.
We drove about a mile towards the Goodwin Sands, and then our mast broke;
but betaking us to our oars, through the mercy of God, we got safe on shore,
about two miles from the town, to which we walked, and had a meeting.
But having no opportunity of giving notice of our coming, the meeting was very small,
yet the Lord did not despise our little number, but was with us.

Next day we went to Dover, and the day after had a meeting there,
which was likewise small; yet several Episcopalians and Presbyterians being there,
spoke well of the meeting, as we were informed.

The wind remaining contrary, on the 27th, being the first of the week,
we went to Folkstone;
where we were favored of the Lord with a blessed meeting with Friends and some others;
and from thence returning to Dover, we had a meeting there,
which was larger than the former.

The wind coming fair on the 29th in the morning, we hasted to Deal,
and in the evening went on board our ship; and next day set sail from the Downs,
and proceeded on our voyage, in which we had various weather.
On the 18th of the tenth month, being the first-day of the week,
we had a very hard gale of wind at west, which increased to an exceeding great storm;
so that all the yards were brought down upon the gunnels,
and the helm lashed and made fast, and the ship let drive before the wind.
We being met together in the great cabin and steerage, to wait upon the Lord,
as at other times, he was pleased to appear in the needful time;
for the tempest increased, with thunder and lightning and rain, to that degree,
that few there, if any, had ever seen the like.

In waiting upon the Lord, I became concerned in prayer;
and wrestling in spirit with the Lord, I received hope that we should not perish;
and having concluded for that time, and my concern returning, I prayed again,
and then some stout hearts were broken, and the Lord`'s power was glorified,
and we greatly comforted.
I prayed unto the Lord, who is God of the seas as well as of the earth and of the winds,
the Creator of all things visible and invisible,
that he would be pleased to send forth his Word, and command the winds as of old;
and that if there was any opposing spirit that stood in our way, to hinder our progress,
the Lord would please to drive him away.
And then I was easy, having fully overcome;
and my companion and some others were greatly tendered.
As soon as I arose I took the Friends by the hands, and some others also,
and in full assurance, told them the worst was over for that time;
and the words were scarcely out of my mouth, and I set down in the cabin,
till the storm abated, and the weather became moderate for some time after.
Here we saw the effects of the mighty power of God; how he enrageth,
and again at his pleasure, stilleth, the seas; He that createth the winds,
and bindeth the ocean as in swaddling bands,
and holdeth the deeps as in the hollow of his hand, and worketh in the heavens above,
and in the earth beneath, and in the waters under the same, whatsoever he will;
the God of truth is his name forever.

From henceforth the succeeding storms, for we had many,
were made easy to what they had been before.
But at one time being ready to murmur,
that so very many of them should he suffered to rage upon us to such a degree,
the answer of God was on this wise:
"`Though the storms were as great as the seas were able to bear,
and the disturbance such as mortals, of themselves, could not endure,
yet since I the Lord am present with thee,
and proportion my power and strength in thee to the greatest hardships I suffer to come,
why should any complaints arise?
In the greatest extremity is the might of my power most seen;
and in the time of distress my mercy and truth
also appear in all those that call upon my name,
and obey my will.`"
Thus we see our own weakness as men, our strength in the Lord,
and the Lord`'s great condescension to his poor creatures.
And therefore, to the Lord of life, the God of everlasting truth and consolation,
be honor and dominion; for he is worthy forever and ever.

As to the wonders of the deep, what appears to sense is natural and usual;
but the depth of the power, wisdom, love, mercy, justice, and goodness of the great God,
the creator, upholder, and governor of all things, are truly wonderful,
and abundantly manifested both on the land and in the sea; and particularly the last,
as we fully experienced in this voyage, which, at land,
we could but have had an imperfect notion of.

Having sailed through many and great storms, variable and uncomfortable weather,
over most of the great western ocean, under the protection of divine Providence,
and all the ship`'s reckonings being out on the 7th day of the twelfth month,
the next day about four in the evening,
we struck ground with the lead at nineteen fathoms water.

This was glad tidings to us all;
and being in our latitude we stood in towards the land all night,
and the next morning we saw the capes on either side of the bay of Chesapeake,
and were standing right in, as we could have desired;
and that afternoon we came to an anchor in Mockjack bay, a little above Point Comfort.

On the 11th of the twelfth month we set sail in
the long boat for Queen`'s creek in York river,
but the wind coming contrary, we went on shore about two miles below Gloucester,
and went up thither on foot,
and soon after went on board our friend William Dowell`'s ship,
lying at anchor in that river, to write letters for England;
after which he sent some hands with us in his boat to Queen`'s creek,
being about twenty miles; and setting out about eleven in the night,
it was troublesome to find the entrance of the creek;
and often running upon oyster banks and other shoals, it proved fatiguing and dangerous.

But at length, about five in the morning,
we got to the house of our friend Edward Thomas, with some difficulty,
for our men not knowing the place,
we went to several other plantations in the woods before we found it.
When we came to the house and called, Edward arose and came to us,
concluding that we were Friends from England,
for he had had some apprehension that way in himself a little before,
and he and all his family made us kindly welcome; and having a good bed provided,
we rested comfortably till about nine in the morning.
Our friend Edward being zealous for truth and the good of his neighbors,
gave notice of a meeting to be there that day; where the Lord owned us,
and gave us a very comfortable season of his goodness
with the family and a few of the neighborhood,
several of whom, though not Friends, were much tendered;
which was the first fruits of our ministry in that country, and good encouragement.

On the 15th of the month we had a meeting about sixteen miles off, at Daniel Akehurst`'s,
at Warwick river, which was a good meeting, but small,
and next day one at Martin`'s Hundred, in the house of Robert Perkin in James city county,
and returned that evening with Edward Thomas.

On the 19th day of the twelfth month we had another meeting at Bangor house,
which was large, and many much tendered.
A blessed meeting it was, and the people generally satisfied,
and on the 21st had an appointed meeting at the house of John Bates,
at Skimino in York county, where no meeting had been before;
and though he was not a Friend by profession, yet very forward to provide seats, saying,
he feared his house would be too small for the meeting,
but had room sufficient in his heart.
The people were generally tendered and humbled,
and we comforted in a sense of the love and visitation of God towards them.
The concluding of the meeting falling upon me, it was upon my mind to say,
in the spirit of prayer,
that since such as should give a cup of cold water only to any of his,
in the name of a disciple, were not to lose their reward;
the Lord would be pleased to reward with the knowledge of his blessed Truth,
those who had so readily and openly received us
and a meeting of his people in their house;
and at that instant both John Bates and his wife were convinced of Truth,
and from that time professed the same with us.

Next day we had another meeting at the house of Daniel Akehurst, which was large,
and many were humbled and tendered by the word and power of Truth,
and departed in a solid frame of mind;
we having preached to them the free and universal grace of God through Christ,
for life and salvation; endeavoring to turn them thereunto,
that through faith therein they might come to know the full end of
the sacrifice of the blood of Christ shed at Jerusalem of old;
and that such as reject the grace and spirit of Christ in their own hearts at this day,
have not the benefit of that work and sacrifice of Christ then made manifest;
but crucify to themselves the Son of God afresh; with many other things of weight,
which the Lord opened in us and by us to the people, to our comfort, their edification,
and to his praise.

The next morning we went to Thomas Gary`'s, who had been lately convinced,
but he was not at home.
His wife had been likewise lately convinced,
and so soon as we entered the house the Lord`'s power tendered us,
and we were much comforted together; and his brother,
Miles Gary and his wife coming thither to see us,
were made partakers of the same visitation.

By the time this satisfactory visit was finished, three of our friends came,
and with some other assistance, set us over James river to Chuckatuck.
It was late in the night before we arrived at our desired port,
which was at the house of our ancient friend John Copeland,
where we were openly and cordially received and entertained.

Upon some discourse with our friend,
I found he was one of the first of those who had their
ears cut by the Presbyterians or Independents,
in New England, for the testimony of Truth,
in the first publishing thereof to that bloody and rebellious generation;
and at my request he showed us his right ear,
yet bearing the badge of their anti-christianity,
whose uncircumcised hearts and ears are, to this day hardened, it may be judicially,
against the testimony of Jesus, and his holy life,
then so much persecuted in his harmless messengers and members.

The wind coming contrary, and rainy weather, the Friends stayed with us next day,
and in the evening several other Friends coming to see us,
it pleased the Lord to visit us together, and we had a tender season of his love.

On the 26th, being the first of the week, we took boat to Chuckatuck meeting,
about six miles; but because of the great rain, the meeting was but small.
Returning that evening to John Copeland`'s, we had a meeting on the 28th at Derasconeck,
where came several neighbors who had not been at any meeting before,
and some of them were tendered; and that evening we returned to John Copeland`'s.

Next fourth-day, being the 1st day of the first month, 1699,
we went again by water to a monthly meeting at Chuckatuck,
where came our friend Elizabeth Webb, from Gloucestershire, in England,
who had been through all the English colonies on the continent of America,
and was now about to depart for England.
The meeting was large, and the sheriff of the county, a colonel,
and some others of note in that country, were there, and very sober and attentive.

Next day we had a meeting at Western Branch, which was pretty large and tender;
the people were solid, and several confessed that what they heard was the truth.
On the 3rd we had a meeting at Southern Branch, which was large,
considering the short notice, and Elizabeth Webb was also there;
the grace of God was plentifully with us, to our great and mutual consolation;
and the people were tendered, and the meeting ended in the dominion of Truth.

On the 5th, being the first of the week, we had a meeting at Barbican,
being the last meeting in Virginia towards Carolina: it was pretty large,
though exceedingly cold weather.
The people seemed wholly ignorant of the testimony of Truth,
and little acquainted with Holy Scripture;
and when the Truth was declared among them some were amazed, others surprised;
some afraid, and some a little affected with the invisible power of Truth.

That night we lodged at our friend Nathan Newby`'s and
had some discourse with him concerning the Indians,
and what sentiments they have about heaven and heavenly things.
He told us,
"`Many of them came frequently to his house to
employ him--being a smith -- to mend their guns,
and he had discoursed with them on such subjects:
they think there is one Divine Being who made all things,
and that he always beholds all the Indians as if they
were comprehended together in a small circle;
and that all bad Indians, who will lie, steal, cheat, and do other ill things,
when they die go to a cold country, where they are always hungry, cold,
and in all manner of distress they can imagine: but the good Indians,
who will not do such things, go to a warm country,
where they have fat pork and roasting ears of Indian corn all the year long;
these being the most excellent food they can imagine.`"
But though their notions be low and sensual, yet I do think,
that if many thousands who profess the true God and Christ,
were to give their sentiments concerning future rewards and punishments,
and wherein they do consist, they would not much exceed the Indians therein;
since many of them are so far from any sense or relish
of the holy and divine taste of the true bread of life,
which comes down daily from God out of heaven, and, as manna,
is daily rained about the tents and dwellings of the whole Israel of God,
that they do not believe it.
The Indians are just, loving and courteous in their way,
and harmless to all that are so to them; but if wronged or abused, revengeful:
but drunkenness, swearing, and the like, they have learned of our own countrymen,
who make greater pretenses to religion and knowledge, and yet are worse in practice.
The God of truth open the eyes of boasting and vain-glorious Christendom,
to see how far short she is of true Christianity;
and that till her inhabitants experience a change by
the workings of the divine nature in them,
they are yet but practical heathens, in the nature of the first and fallen Adam,
and so esteemed in the sight of the Lord; whose love is surely towards the Indians,
which shall be published in them in the fulness of his appointed time.

Next morning we went towards North Carolina through the wilderness,
and there being no house in all that way,
about the middle of it we made a great fire by the side of a brook,
and ate some bread and cheese which Nathan Newby carried in his wallet,
and drank of the brook, and were well refreshed and content.

Having given our horses some Indian corn, we went towards Gabriel Newby`'s,
at the head of Perquimon`'s creek, in Carolina, where we arrived that afternoon;
and he gave notice of a meeting to be on the fourth-day following;
and next day we went to the house of our friend Francis Toms, on the same creek.

Here we had the meeting proposed; which was large,
and several persons of note in those parts, of both sexes, were there:
but the noises and elevations of some professing Truth, were hurtful to them;
though they had, before that, been very solid and attentive to my companion`'s testimony,
who had the whole public concern in the meeting that day.

On the 9th we went forward, and being accompanied by Francis Toms,
who was one of the provincial council, and several other Friends from Virginia,
and other parts thereaway, we went with them to court,
where we were respectfully received and entertained by the Lieutenant-Governor,
and others of the council, I having brought letters to the Governor from England.

In the evening we went over Little river,
and lodged that night with our friend Thomas Simons;
and next day had a meeting over the creek, at our friend Henry White`'s, which was small,
by reason of the court, which usually holds several days, but well and tender:
the Lord was with us.

On the 13th we had a pretty large meeting, where several were tendered,
among whom were some negroes.
Thomas Simons having several negroes, one of them,
as also several belonging to Henry While, had of late come to meetings,
and having a sense of Truth, several others thereaway were likewise convinced,
and are likely to do well.
The morning that we came from Thomas Simons`'s,
my companion speaking some words of truth to his negro woman, she was tendered;
and as I passed on horseback by the place where she stood weeping, I gave her my hand;
and then she was much more broken.
Finding the day of the Lord`'s tender visitation and mercy upon her,
I spoke encouragingly to her,
and was glad to find the poor blacks so near the Truth and reachable.
She stood there looking after us and weeping, as long as we could see her.
I inquired of one of the black men how long they had come to meetings?
He said, "`They had always been kept in ignorance and disregarded,
as persons who were not to expect any thing from the Lord, till Jonathan Taylor,
who had been there the year before, discoursing with them,
had informed them that the grace of God, through Christ, was given also to them,
and that they ought to believe in and be led and taught by it,
and so might come to be good Friends, and saved as well as others;
of which they were glad.
The next occasion was when William Ellis and Aaron Atkinson were there,
they went to meetings and several of them were convinced.`"
Thus one planteth, and another watereth, but the Lord giveth the increase.

I called one of the negroes aside after the meeting,
and exhorted him to be inward with the Lord;
and that he and the rest should wait to know the work of the power of God in themselves,
to change their minds from a state of nature and sin to a heavenly condition.
To this he was attentive, and said,
he and those other negroes that were convinced had discoursed with others of them,
and had told them what they were come to understand and believe;
and that some were inquisitive after Truth,
but some others of them seemed to take little notice: but, said he,
every tub must stand on its own bottom; and the neglect of others, we hope,
will not discourage us to press forward in that which we are persuaded is the best.

On the 14th we had a good meeting, where many were tendered,
my companion especially being very powerful that day in his testimony;
to the praise of the Lord, of whom alone is the power, and to whom be all glory forever.
We passed the Great Sound next morning, and went to a meeting at the widow Anne Wilson`'s,
which consisted, for the most part, of Friends, and was a very tender and open meeting.

The morning following we set forward for Virginia;
and alighting at the same brook where we had been as we went into Carolina,
we again refreshed ourselves and horses,
and accomplished our journey to Dorothy Buskin`'s about sunset;
and next day had a meeting there.

We rested there the 18th; and on the 19th had a large good meeting at Chuckatuck,
both of Friends and others; and the next day we went to Benjamin Small`'s,
and there I had a good season in the meeting,
where Friends were comforted and divers of the people tendered,
and generally humbled under the testimony of the blessed Truth;
which that day reigned both in word and power,
to the glory of him that liveth and reigneth, and is worthy forever and ever.

On the 21st we had a good meeting at Alice Halloway`'s, near Elizabeth river, but small,
by occasion of a member of council to be elected that day in those parts.
Next day we had a pretty large meeting at Southern Branch,
at the house of Robert Burgess: he was not a Friend by profession,
but a justice of peace, and of good account in those parts.
There had never been a meeting thereaway before; yet the people were generally solid,
and several of them tendered.
After the meeting the justice and his wife were very respectful,
and would gladly have had us to eat with them and lodge in their house that night;
but being otherwise engaged in the course of our service, we departed in much kindness,
both on their part and ours.

We returned that evening to Alice Halloway`'s;
and next morning set forward for Elizabethtown,
about three miles by land and seven more by water.
We went by the house of Thomas Hodges, a justice of peace,
who lent us his boat and was very courteous; but the wind being contrary,
we did not arrive till about the middle of the day.
The first thing we did was to view the house where the meeting was to be;
and finding no seats in it, we were at a loss on that account:
but another Friend and I went to the high sheriff`'s to acquaint him of the meeting,
who being absent, we informed his wife and family; and applying for planks for seats,
we readily had them; and she, with several of their daughters, were at meeting,
and were civil and tender.
There is no meeting of Friends in that place, nor any dwelling there; but a very rude,
senseless people, devoid of all relish of truth, and of the fear of God in general;
yet many of them came to the meeting: some were civil, others tender;
but the bulk of them airy, wanton, and scoffers;
sometimes rushing into the meeting and leering under their hats,
and then again running out of the house, mocking at what they had heard,
to the great disturbance of the few who were sober,
and of us who went to visit them in the goodness of God.
Many things of great moment were declared unto them,
both of the mercy and judgments of God;
and the Lord gave us power to clear our consciences to them at that time;
and I am persuaded the Lord hath a seed among them.

From the meeting we went to the house of one who kept an ordinary,
and I took that opportunity, he having been light, airy, and a scoffer in the meeting,
to tell him, that though Ishmael was the first born of Abraham,
yet being of the bond woman, he was not to inherit; and scoffing at the birth of Isaac,
was excluded from the house of his father; which under that typical dispensation,
being a figure of the two seeds now inwardly revealed,
there is no scoffer can enter the kingdom of God,
unless he be first born of another spirit.
Upon which he was ashamed, and fell under;
and we left him to think further of what was said.
There we took boat and went back to Thomas Hodge`'s,
who entertained six of us that night with good accommodations.

Next morning we came back to Benjamin Small`'s, and stayed there some hours;
and being at the creek-side, accompanied by some Friends, and ready to take boat,
the good presence of the Lord came upon us and sweetly tendered us together,
and my companion first and then I, had some time in prayer;
where we parted with those Friends in tender love, and then went to John Copeland`'s;
and next day had a small but heavenly meeting about three miles off,
at our friend Daniel Sandborn`'s, and returned in the evening to John Copeland`'s.

The next day we had a meeting at Pagan creek, alias Levy-neck,
where we had a large assembly, most of whom were not Friends;
and the power of the Lord was gloriously with us,
and the truths of the gospel were opened to general satisfaction.

After this meeting my companion returned to John Copeland`'s,
and from thence over James`'s river, and went up the other side to alarm the people there,
and to meet us that day week further up.
Richard Gove and I went that night to Levy-neck,
and next day had another meeting at Lion`'s creek, at Robert Lacy`'s;
it was small by reason of the short notice, but otherwise pretty well.

Next morning very early, we went towards Burleigh, on the south side of James`'s river,
and being very hot, and no house of entertainment by the way, and but few others,
we alighted at a brook called Stony-run; and having ate some bread we brought with us,
and likewise fed our horses with some Indian corn,
we remounted and proceeded to James Johns`'; where we arrived at three in the afternoon,
having rode about thirty-eight miles.

We had not been long in the house till I perceived a concern in my mind in the truth;
and seeing two Indian men-servants and a negro woman about the house,
I found it was on their account, for the love of God was towards them.
Our host being deaf and very talkative, was troublesome in asking many questions,
and in commenting upon the Scriptures in his fashion; and interpreted them to us,
as he imagined: but as soon as I could,
I look an opportunity to retire into the woods for the
more free exercise of my mind in the gift of God alone,
and to see what might be the issue of my inward concern.

Finding no way for it that night, the next morning I sent for those servants,
and had the family and them together in the hall;
where I published to them the day of the visitation of God,
directing their minds to the light and grace of God in their own hearts;
that as it reproved sin in them, and in all men,
so it teacheth all that w`'ill receive it, "`to deny ungodliness and worldly lusts,
and to live soberly, righteously, and godly, in this present world.`"
Thereby men escaping the corruptions that are in this world through lust,
are received into everlasting joys in the world to come.
But such as are not led and governed by the grace of God here,
are to be condemned to everlasting fire,
in the great day of the judgment of Almighty God, which is coming upon all the world:
and that though men there should desire to die, they could not;
neither is there any end of their torments; with some other things,
importing both the judgments and mercies of God.
Perceiving them touched in some degree, I did my best,
according to that understanding the Lord gave me,
to set their minds upon the present truth, as an inward object.

I also exhorted them to wait upon the Lord in stillness; who, being a holy,
invisible Spirit, appears in the hearts of men;
and that whatsoever things are reproved in men`'s hearts here, in this world,
will be condemned in the day of judgment; but if they repent of their former evil deeds,
and for the time to come, join and unite with the Spirit of Christ,
which discovers and condemneth all evil in them,
the Lord will not only forgive and forget their former sins,
but be their exceeding great comforter in this life;
and in the world to come they shall sing everlasting
songs of joyful praises to the great God,
in the kingdom of his glory, in the sweet company of innumerable angels,
and the spirits of just and good men in a state of perfection;
where there is divine pleasure unutterable and everlasting.
After this I prayed, and Robert Gove having spoken something among them, we concluded,
and I had great peace in the Lord.

One of the Indians wept much;
and there being a meeting the same day at our friend Thomas Chappel`'s,
about two miles from this, they both came after us thither;
and though the meeting was small, it was tender and well.

Next day at our friend Peter Wyke`'s, we had a small but very comfortable meeting;
and the following day we had a like meeting, eight miles off,
at our friend James Benford`'s, in the precincts of Merchants Hope:
there were several of the people there, and things opened to their states,
and we had a comfortable time with them and Friends; these loving, and those respectful.

The first of the week we were at another meeting there; but it proving very rainy,
with a great gust of wind and lightning and thunder till mid-day, the meeting was small;
but several of the people seemed solid and tender.
On the 2nd of second month, crossing James`'s river we went to our friend Jane Pleasant`'s,
at Curies, where we were kindly received;
and there we met with my companion and several other Friends, to our mutual satisfaction.

On the 4th we had a meeting there, which was large and well.
My concern therein was, for the most part, about marriage,
and the displeasure of God against his own people in the old world and all ages of this,
against mixed marriages between them and the world;
for I had heard some hints that Jane Pleasant`'s
daughter had married one that was not a Friend,
and gone quite off from the very form of truth;
and that her son Joseph was then likewise about
to take a wife that did not profess the truth.
This concern I bore long in the meeting,
under fear lest it should arise from the hearing of the ear only;
but at length seeing my way clear, I discharged my conscience in that matter,
and the young man was for that time brought to a sense of his error.

On the 6th we had a meeting at our friend William Porter`'s, a comfortable time;
and that evening returning to Jane Pleasant`'s, we had another meeting there on the 7th;
and on the 8th, being the seventh of the week, we went to Black creek,
and next day had a large meeting at the meetinghouse;
and the power and goodness of the Lord were plentifully with us,
and many were tendered thereby.

On the 10th we set forward for our friend George Wilson`'s,
towards the upper part of Mattapany river, swimming our horses over Pamunky river,
two at a time, one on each side of a canoe,
and got safely thither about the fourth hour in the evening.
It is a wilderness place every way; no meeting settled there,
but the Friend and his wife, through the mercy of God, preserved alive in the truth;
yet their children are in danger of being lost from it,
one of their daughters being married by a priest,
neither she nor her husband making any profession now with us.
We had a meeting there next day, which was larger than could have been expected;
several were tendered, and generally sober.
The Friend`'s daughter and her husband were there; whom we admonished and exhorted,
and they were humble and pretty tender.
We lodged there that night also, and in the morning set forward for Pamunky-neck,
to the plantation of William Clayborn.
We had a good passage over the river by the ferry;
and on the other side went into a house, for much thunder and rain came on;
and there we heard of an Indian town about a mile off,
on the side of the river Mattapany, and we went to see the people.
They are the Chickahominy Indians; their town consisted of about eleven wigwams,
or houses made of the bark of trees, and contained so many families.
We were directed to their chief;
and when we went to his door he came out and invited us in; and we being set down,
several of his people came to look upon us, and among them,
one who could speak some English.

After a time of silence the company increased; we asked him if they were all there,
for we desired to see as many of them together as we could;
which being interpreted to the chief, who was a grave, serious, and wary old man,
he seemed to be under some suspicion of us,
and what we might mean by ai desiring to see them all together,
we being wholly strangers to them.
Being under some concern in my mind, and observing a fear in them,
I informed them by the interpreter,
that we did not come among them for any hurt to them or gain to ourselves;
but being lately arrived from England, had a desire to see them; for we loved Indians,
and had something to say to them concerning the great God who made the heavens, the sun,
moon, earth, and all that dwell therein.
Englishmen, Indians, and all nations; that he loves all good English and good Indians,
and other good people everywhere.

And then they seemed a little more calm and settled in their countenances,
and my companion spoke to them concerning the immortality of the soul;
and that God hath placed a witness in the heart of every man,
which approves that which is good, and reproves that which is evil.

The chief then pointed to his head, and said, that was treacherous, or fallacious;
but pointing to his breast, said it was true and sweet there.
Then he sent forth his breath as if he had poured out his soul unto death,
and signing up towards heaven with his hand, raised a bold, cheerful, and loud hey,
as if the soul ascended thither in a triumphant manner; and then pointing to his body,
put his hand towards the earth,
to demonstrate his opinion that the body remains
there when the soul is departed and ascended.
I believe we might have had a more satisfactory time with them,
but that there came in two young Englishmen who lived somewhere thereabout,
and understood the Indian tongue: they undertook to interpret for us,
but we found them not quite honest in it; for when my companion spoke further to them,
which was concerning the righteousness and impartiality of God;
and that he hateth drunkenness, whoredom, lying, cheating, and all evil,
as much in an Englishman as in an Indian, the Indians were set into a laughter.

I desired one of the Englishmen to tell the Indians they should not be light,
especially on such occasions; that the great God, maker and upholder of all things,
hath right to the obedience of all men, and hath placed a law in every heart,
and also appointed a time wherein he will bring all men
to account for their deeds done in this world;
and as he is all-seeing and omnipresent, he always beholds all men`'s thoughts, words,
and deeds, and at last will reward every man as his thoughts, words,
and actions have been; the good, whether English or Indians,
he will reward with everlasting happiness and unspeakably good things; and the bad,
whether Englishmen or Indians,
he will condemn to everlasting fire and torment undeclarable.
But instead of telling the Indians these things,
he said they had formerly told them some of them,
and others he himself did not understand,
nor could he find words in the Indian tongue to reach them.
They told us also that the Indians had been great idolaters,
but since the English inhabited those parts, they were much reformed.

But if the professors of Christ have done the poor Indians any good,
they have done them much harm also; for they have taught them, by example, to be drunk,
to lie, steal, swear, cheat, and dissemble;
and often defraud them in barter for their skins, which is their living.
And when an Indian becomes drunk, as some of them will, then swearing, ranting,
and blaspheming, he will cry aloud, "`I am now all one Englishman.`"
It is reported of this chief, that he was never seen to be drunk but once,
and that was when young;
which had proved so troublesome to his mind and virtuous inclination,
that he always thereafter shunned every occasion of the like evil.
We took them by the hands, one by one, beginning at the chief;
and they seemed well pleased with our visit.

As to the conversion of the Indians to the Truth,
I believe the Lord will call them after the power of antichrist is overthrown;
but it seems to me that learning, or the historical part of religion,
or their own language, which is very barren of pertinent words,
will not be much instrumental in it; but the Word of Life,
whose divine and life-giving intellectual speech is more certainly known in the mind,
will tender their hearts in a silent state and retirement,
by means of some instruments that the Lord will raise up and qualify for that purpose;
who shall not confound them with a long fruitless history of needless things.
But when the Lord shall send forth his Word,
"`the Light of the gentiles,`" the quickening Spirit of Jesus,
into and upon any of them in holy silence, or in prayer,
their minds shall be directed to the Spirit himself,
as the present object of their faith, obedience, and love,
and author of their present joy and salvation: and so, believing in the light,
shall become children of that light and day of God, and heirs of eternal life in him.
And then the histories in the Bible, the prophecies of the prophets of God,
and the fulfilling of them; the evangelical account of the conception, birth, life,
doctrine, miracles, death, resurrection, ascension, glorification, mediation,
intercession, and judgment of Him, who is the substance of all,
and that "`true light which enlightens every man that cometh into the
world,`" will be the more clearly received by the Indians,
when the Almighty shall think fit to acquaint them therewith.

That evening we arrived at Captain Clayborn`'s, and next day had a meeting,
which was small, but comfortable: and being weary with hard travel,
we determined to stay there till after first-day; and intending another meeting,
we gave notice of it to the country.
We had a meeting accordingly,
which was large and well;
the people being generally sober, and several tendered,
and after the meeting expressed their satisfaction; and some of note among them said,
that since we had such good things to publish they hoped we would not
finally leave those parts without more meetings thereaway;
several of them adding,
that we should be welcome to their houses and the best entertainment they had,
though we had laid open their priests to the lowest capacities,
and especially their pseudobaptism.

On the following day we set forward for Queen`'s creek,
but in our way had much thunder and rain;
and though it was very dark in the night in the woods,
through the good providence of God we got well to that journey`'s end.

Next day we rested there; and the day after went to Daniel Akehurst`'s, sixteen miles off,
where we had a small but good meeting,
and returned that evening with Edward Thomas and his wife to Queen`'s creek.

On the 21st had a meeting at a place called Hickory-neck,
at the house of one Edmund Brewer, not a Friend,
nor had ever a meeting been there before.
It was pretty large, and some of the people tendered;
and though some persons were a little airy, yet,
being rebuked by my companion in his testimony, they became more quiet and sedate.

On the 23rd, being the first of the week, we had a meeting at York City,
at the house of a preacher among the General Baptists;
and it was the first meeting of our Friends that had been there.
The people were very rude and senseless of all good,
and the testimony of truth was sharp accordingly; especially in my companion,
declaring the heavy stroke of the hand of the Lord upon them,
if they did not speedily repent and turn unto him;
and they were at last brought pretty well under.

On the 25th had a meeting at a place called Pocoson,
where there never had been a meeting before: it was large, though the people,
till my companion began to speak, did not generally come in, but then crowded much,
and a good meeting we had, some being tendered and generally humbled:
blessed be the Lord for his power and goodness to us.
We were entertained in much friendship and tender respect by Thomas Nichols and his wife,
but by her especially; who, though a mulatto by extraction,
yet not too tawny for the divine light of the Lord Jesus Christ,
"`the light of the gentiles and glory of the whole
Israel of God,`" through all ages of the world.
Of this true light and the power and virtue of it, is this poor soul truly begotten,
and to a good degree filled with the unfeigned
love which ever attends those that believe in,
love and obey that "`true Light which enlightens every
man that cometh into the world:`" the Lord is with her,
and hath made her instrumental, the furtherance of his own glory in those parts.

On the 26th we had a meeting at George Walker`'s, at Kickatan; it was small,
yet many things were opened of great moment, and the Lord gave us a good time together.
After this meeting I found myself under a particular concern for the restoration,
if possible, of the wife of George Walker the younger,
who was one of the daughters of that unhappy apostate George Keith.
I observed her to have a good natural understanding,
but much out of that innocent adorning, both of body and mind,
usual among our best Friends,
and I spoke to her alone on that subject in much tenderness;
and though she was of a quick temper and naturally high-minded,
yet I observed the love of truth was toward her, and a time of visitation;
and exhorted her therein to be humble and moderate in all things, fearing the Lord.
At first, as I thought, she was jealous I had done it reproachfully, or to affront her,
considering the circumstances of her father and mother,
and would have made excuses and evasions; but nothing appearing in me but true respect,
friendship, and tenderness, she began in a short time to change colors,
and that was followed with tears; under which I took leave of her,
being full of compassion in the love of Truth towards her;
and in which also I greatly desired the return
of all that had gone out from the truth that way.
As I had taken leave of her, came my companion Roger Gill and Daniel Akehurst;
and when Roger Gill took her by the hand, she broke out again into a flood of tears;
by all which we had some hope that the Lord might restore her from under
those prejudices begotten in her mind by the apostasy of her lapsed parents.

In the evening, about six, we took horse and went that night with Daniel Akehurst;
and on seventh-day morning toward Remuncock,
where we had appointed a meeting to be next day, being the first-day of the week,
and in our way called at the house of John Bates at Skimino, formerly mentioned, who,
with his wife, were become professors of truth since our arrival in that country.
Though one soweth and another reaps, yet we are all the servants of one Lord,
and therefore to him alone be the glory of his own work,
in which the best and strongest of the children of men
are only instrumental in him who worketh all in all.
One begetteth into the faith through the divine Word;
another nourishes through the virtue of the same;
and another confirms and establishes by the same wisdom.
The wisdom and power of God is one.

The next day we had a meeting according to appointment, which was large and open.
Many persons of note in those parts were there, and all were very sedate,
and some broken and generally satisfied;
the Lord favoring us with his divine presence and aiding us by his grace.
The most noted priests in those parts were one Bucker, and another, Monro, a Scotchman.
Bucker had formerly boasted that no Quaker was able to dispute with him;
he could run them down at pleasure.
And Major Palmer hearing of the meeting, had invited him thither,
but he evaded the matter, by telling him,
"`The Quakers were not worth his while to discourse with,
for they deny the resurrection:`" though we own the resurrection, but not in his sense.
And Monro, though priest of that place, had an errand to the governor at the same time.

That night we rested there, and next day set forward for our friend George Wilson`'s,
in our way to Maryland; and next day arrived at the place we intended,
and where we expected a meeting the day following;
but some mistake having happened in the notice that had been sent,
we could not have one till the 4th of the third month, and then it was a very small,
hard, dark, and dull meeting; the people were busy planting tobacco,
and those that came to the meeting left their minds behind them in that business;
yet the Lord was with us in some comfortable measure,
and we departed thence in peace the next morning.

About two in the afternoon we came to the Rappahanock river; and having a ready passage,
we called at a house on the other side belonging to a widow woman,
of whom we asked some corn for our horses, for which we offered to satisfy her.
She replied, corn she had, and we should have sufficient; but she would not sell us any,
though it was very scarce at that time;
and she likewise gave us such provision for ourselves as she had ready,
and would have provided better, if we could have stayed for it.

On the 7th a Friend borrowed a flat to set us over the river, for there, was not,
at that time, any ferry allowed, being between two governments;
and so we passed over the great river Potomac to Cedar-point, about three miles,
at that narrow place.

This being the seventh-day of the week,
and not knowing of any meeting we could reach the next day,
we called at the first plantation we came to,
where we inquired if there were any of the people called Quakers in
those parts. Being invited to alight and refresh ourselves,
we did so,
and were told one of our Friends had appointed a meeting at a house about two miles off,
who had had several meetings before, and many went to hear him.
We asked his name, and where he came from, thinking it might be some Friend from England,
and were told his name was William,
and that he came from Virginia. Then we apprehended him to be one William Morton,
who had been denied by Friends there, and went up and down, under the name of a Quaker.

We lodged there that night, and were kindly entertained;
and next day about the tenth hour, with our landlord and most of his family,
went to the meeting, where we found a considerable number of people;
and in a short time the man stood up and prayed standing:
the people pulled off their hats, but sat on their seats, and we sat with our hats on,
in testimony against him and his prayer;
in which he used a few imperfect scraps of the national common prayer,
and some nonsensical expressions, exposing his own gross ignorance.

When he had ended his prayer he began to preach;
but affirming that the Lord Jesus Christ is married to the whole world,
my companion said it was false, and bid him prove his assertion if he could,
before he said any more; but he went on with some more confused sentences,
and then said he would not take up all the time, but give way to these strangers.
Then my companion stood up, and had a very good time among the people;
several of whom were tendered, and all very sober: and when he had done,
the man stood up again,
and would have made some opposition to what my companion had said,
as if he favored self-righteousness and long prayers,
though he had said nothing that might give him ground for such a charge.

Finding my mind engaged by the truth and authority therein,
I stood up and bid him be silent; and he gave way.

I began with the universal free grace of God, through Christ, unto all men; and yet,
though Christ hath died for all mankind, and the grace of God by him is come upon all,
those only are saved who believe in the sufficiency of that grace;
and in that faith deny all ungodliness and worldly lusts,
and walk uprightly in this present world.
For after Christ had done and suffered all things which
are written of him in the holy Scriptures,
John, who had the visions of God, even to the last and great day of his judgment,
saw every man rewarded according to his works; and that,
notwithstanding the offering of our Lord once on the cross,
for the sins of the whole world, yet at last Christ will set the sheep on his right hand,
and the goats on his left; and will say to the former,
"`Come ye blessed,`" and to the latter, "`Go ye cursed.`"
But if his dying for the sins of the whole world were sufficient of itself,
without men`'s faith in, and obedience to, the grace come by him,
there could not be any room left for such a distinction at the last day;
but as all have received grace by him,
those who believe therein and obey the dictates thereof, come to be saved;
as it is written, "`By grace we are saved through faith; it is not of ourselves,
it is the gift of God.`"

Again; "`The grace of God which bringeth salvation, hath appeared unto all men,
teaching us that denying all ungodliness and worldly lusts, we should live soberly,
righteously,
and godly in this present world;`" but those who do not believe in this grace,
and the sufficiency of it, cannot be saved by it.
For though in words they confess the Lord Jesus Christ, yet in works they deny him;
and then that saying becomes true in them,
"`His servants ye are to whom ye yield yourselves servants to obey,
whether of sin unto death, or of obedience unto righteousness.`"
So that there is an absolute necessity still of
a holy life and due obedience to the law of God;
for Christ is not come to give liberty to sin, but to redeem men from sin,
and to give us power to do the commands of God;
that man being redeemed from the cause of eternal death, which is sin,
might also be saved from the effects thereof, that is, eternal condemnation.

Having finished my testimony to the truth,
I proceeded to lay that man open to the people as an impostor;
that he was not in unity with us, nor received as a minister among our people,
being guilty of some things utterly inconsistent with our profession.
Then my companion concluded the meeting in prayer, and the divine truth was over all,
and the people well satisfied.
We departed after good service for the Lord; of whom is the power,
and to whom be the glory forever.

After the meeting we returned with William Herbert to his house,
where came to us a trading person from London; and he sitting with us near the river,
it came into my mind that he came for dispute,
and he and William Herbert and his wife going into the house, we followed them.
As I passed the window I perceived he was reading a passage to them out of a book;
and when we went in, I found it was concerning the institution of circumcision;
asserting that baptism--he meant sprinkling of
infants--was now as necessary as that was then.
And he began to allege against my companion,
that he had uttered something in the meeting concerning baptism,
which he could not maintain by Scripture; that is,
"`That the baptism now used--he meant by the national church--was
never instituted of God by any evidence appearing in Scripture,
nor any precedent there for sprinkling infants;
nor any water baptism commanded since the baptism of John was at an end.`"

The first part we owned my companion had spoken,
which the stranger oppugning we put him upon his proof;
and after a short dispute my companion brought him to
confess that he could not defend it by Scripture:
and then he went to the second part, viz:
"`Nor any water baptism commanded since the baptism of John was put to an end.`"
This we denied to have been spoken by my companion as he stated it;
but since he had confessed himself a member of the national church,
my companion insisted that he had nothing to do with baptism with water,
till he should come into the practice of it.

He replied, "`You mentioned the thing in the meeting, and the question is not,
whether I or another be of the Baptists`' opinion and practice,
but whether any water baptism was instituted after John`'s baptism?`"
But my companion having put him to silence, as to sprinkling,
and denying his charge as to the other part, said little more then to him.

A concern remaining upon me lest this man should go away boasting,
I entered into the argument with him upon the subject at large;
and since he had asserted that Christ instituted another water baptism than that of John,
I put him upon the proof of it.

Then he cited that text in Matt. 28:19; Go teach all nations,
baptizing them in the name of the Father, and of the Son, and of the Holy Ghost, etc.

I replied that this text was not to his purpose,
for water was not so much as mentioned in it;
and if the Lord Christ had intended water as the instrument of this baptism,
he would have expressed it.

To this he alleged that the practice of the apostles, pursuant to this institution,
determined that it was water baptism;
for from this time they baptized with water in divers instances,
and particularly in that of Philip`'s baptizing the eunuch.

Answer; The practice of the apostles doth not determine it to be water baptism,
because they practiced circumcision, vows, shavings, purifications,
and other Jewish rites; which, in point of obligation,
were all ended by the coming of Christ in the flesh, and suffering for all mankind;
and so was water baptism by the coming of the Holy Ghost.
But for the better understanding of this command,
observe that John the Baptist was commanded by
the Word of God to preach repentance unto Israel,
and to baptize them in water, directing them to the true object of faith,
then about to be made manifest, that is, Christ the Lord, the true Messiah,
and sent of God, though not known to John himself at that time; of whom he said,
'`I indeed baptize (or have baptized) you with water,
but he shall baptize you with the Holy Ghost, and with fire.`'
This shows there was a baptism of a more excellent and efficacious nature then to come,
and by an administrator incomparably superior to John, that is, Christ, who,
when he appeared in the flesh to Israel his people,
preached to them the same doctrine of repentance as John did;
and his disciples also preached the same,
and baptized them with the same baptism as John did,
differing only in this circumstance of administration --John baptized them,
saying they should believe in Christ then to come;
whereas the disciples of Christ baptized in the name of the Lord Jesus,
declaring him to be the true Messiah that Moses and the prophets had prophesied of.

"`Now, here is water baptism transferred from John to the disciples of Jesus,
for Jesus himself baptized not with water, who made and baptized more than John did;
and John being soon after martyred,
water baptism remained under the administration of the disciples of Christ only;
and until the resurrection of Christ, we hear no more of the baptism of the Holy Ghost,
as I now remember, foretold by John as aforesaid.
Nor was the baptism of the Holy Ghost declared as a
dispensation to the believers and disciples of Christ,
till a little before his ascension; nor established as such,
till the coming of the Spirit of Christ upon them at Jerusalem.

"`As to the introduction and terms of this baptism and dispensation,
they lie thus in the holy Scriptures:
'`All power in heaven and earth is given unto me,`' saith the Son of God;
'`Repentance and remission of sins must be preached in my name unto all nations,
beginning at Jerusalem; and ye shall be witnesses unto me in Jerusalem, in Samaria,
in Judea, in all the regions round about, and to the uttermost parts of the earth:
Go ye therefore, teach all nations,
baptizing them in (or rather into) the name of the Father, and of the Son,
and of the Holy Ghost;
teaching them to observe all things whatsoever I have commanded you; and lo,
I am with you always, even unto the end of the world.`'

"`To obviate any misapprehension the disciples might be incident to, the Lord adds,
'`Go ye into all the earth, and preach the gospel unto every creature: he that believeth,
and is baptized, shall be saved; but he that believeth not shall be damned:
but tarry ye at Jerusalem till ye have received power from on high.
But ye shall receive power after the Holy Ghost is come upon you:
for John truly baptized with water,
but ye shall be baptized with the Holy Ghost not many days hence.`'

"`Here is water baptism plainly ascribed to John,
and the disciples of Christ already in the practice of it;
and the baptism of the Holy Ghost as clearly distinguished from it,
as being the permanent dispensation of God unto all who
should believe in Christ and the Holy Spirit,
to the end of the world, by the preaching of the gospel by his own power;
which accordingly began at the city of Jerusalem, at the time of Pentecost,
as by the testimony of Holy Writ.

"`But to show how little poor mortals understand of the things of God,
though ever so plainly told us by the hearing of the ear,
without the Spirit of Christ revealed in ourselves, the disciples,
who had been so long with him, and heard him speak as never man spake,
being yet unconverted, though convinced,
replied to all that he had then said on those divine subjects of the highest importance,
'`Wilt thou, at this time, restore again the kingdom unto Israel?`'

"`The words of Christ, though so plain as to the nature of this baptism, that is,
with the Holy Ghost; and as to the extent of it, that is, to all nations,
to all the earth, and to all mankind; yet the apostles did not understand as to either,
but still thought themselves confined to the Jews,
till Peter was sent to Cornelius and his household, who were Gentiles.

"`It is not to be admired therefore, that the apostles, or some of them,
might administer water baptism in some instances, though few plainly to be proved,
since it was about eight years after the institution
and commencement of the baptism of the Holy Ghost,
as a dispensation, before they understood the nature or extent of it;
and no man knows any more of the things of God by the Holy Ghost,
than he opens or manifests to him.

"`It is also observable, that what baptism any of the disciples administered with water,
after the coming of the Holy Ghost, was not from that command mentioned.
Matt. 28:19, but from their practice of John`'s baptism before, and in his time,
as appears by the manner of administration; for it never was in the name of the Father,
Son, and Holy Ghost, the terms of institution in that text,
but only in the name of Lord Jesus, or name of the Lord, being the same.

"`But when your priest saith to a child of eight days of age, or the like,
'`i baptize thee in the name of the Father, Son,
and Holy Ghost,`' he uttereth a false proposition; for he doth not baptize,
but rantise or sprinkle, and taketh the name of the Lord in vain,
using it where the Almighty hath not commanded it to be used or named.`"

After this my opponent said no more but only this,
"`That he could not but believe that some water baptism was still necessary.`"
And so this conference ended in a friendly manner, and I said to him as he departed,
"`May he whose word of wisdom alone can give understanding in the things of God,
and speak forth knowledge in the secret of the heart, answer that;
for it is not in the power of man.`"
And so he bowed in good manners, in his way, and departed.

The next morning we set forward, taking in our way the Cold Springs,
where we found many poor diseased people;
and several said they had received benefit by virtue of the waters,
by drinking and bathing,
(the water is chalybeate) and among these poor
people we had a meeting in an old tobacco house,
where many of them lodged.
My companion had a very open time among them;
the Lord favored us with his comfortable presence,
and one blind woman complaining for want of bread, we gave her money to buy some,
and departed in peace.

Passing the river Patuxent about a mile over, at Benedict town,
we came to the house of our friend Elizabeth Hutchins, and being weary, stayed that night.
Next morning went towards the Cliffs, and there remained till the 11th;
and thence to Patuxent meeting, where was a marriage, and we had some service.
On the 14th, being first-day, were at another meeting at Patuxent;
after which we returned to the Cliffs, where we remained till the 18th,
and in the mean time,
had a small but comfortable meeting there,--where came
to us our ancient and honorable friend in the truth,
Thomas Everndon, from the Eastern Shore.

On the 18th we went to the Ridge, where was a meeting on occasion of a marriage,
in which we had good satisfaction; and so to our friend Samuel Galloway`'s,
where we rested that night, and were very easy and well;
his wife Anne being the only ministering Friend at that time in all those parts;
a very honest, innocent, lively, and honorable Friend in the truth,
and everywhere acceptable in her services.
Next day being the first of the week, we had a large meeting there,
but the hardest and most shut up that we had been at in America.

The yearly meeting for the Western Shore approaching,
in the mean time we visited some families of Friends in those parts.
Meeting with our friends Dr. Griffith Owen, from Philadelphia and Aaron Atkinson,
from England, we all went to Samuel Galloway`'s,
near which place the yearly meeting was to begin, +++[+++the 27th of third month.]

On the first and second-days it was very full and peaceable,
and the good presence of the Lord was with us; but on the third-day, came one Henry Hall,
a priest of the church of England, and with others of his notions,
eavesdropped the meeting, but came not in; and after the forenoon meeting,
we being gone into an upper room, he was heard to mutter something among the people,
by way of exception to some part of what Aaron Atkinson
had said in the meeting concerning predestination.

Some of them sent word to us, that the priest desired to speak with him, or all of us,
about it, and we went down to him among the people.
At first he was a little surprised, and seemed to deny that he had any thing against us;
but regaining his courage a little,
owned he had something to object about predestination.
We invited him into the house and into the gallery with us,
that he might have like advantage of being heard;
and the house was quickly filled with people, many of whom were his own hearers.
The matter of his objection was,
that Aaron Atkinson had preached against the doctrine of election,
as held by the church of England; and he said he would defend that doctrine against us,
and show us to be erroneous in holding the contrary.
But the priest not being in the meetinghouse when Aaron Atkinson had spoken there,
had mistaken what he said, and so brought a wrong charge,
for Aaron Atkinson did not speak of election alone as held by the church of England,
but against election and reprobation,
as taught by the Independents and Presbyterians of New England,
where he had lately travelled, and that their doctrine touching that point,
was erroneous;
and rehearsed to the people the substance of what he
had said in the meeting upon that subject.
Upon which I observed to the people, "`That the priest`'s charge at first was,
that we deny predestination; which, by the common acceptation of the word,
includes both election and reprobation; though now shifting his terms,
he restricts it to election only.
And whoever accuseth us of error for opposing predestination,
doth himself thereby assert that doctrine,
and must prove it if he can;`" which he would not attempt.

The priest was then silent as to that point, and in an angry manner affirmed, that we,
as a people, deny Christ, and pretended he could prove it, being furnished,
as we perceived, with his pretended proof out of that lying, perverting, scandalous book,
called The Snake in the Grass; which, as we were informed,
he used to read often among his people.
His pretended proof amounting to no more than false accusation,
we rejected and exposed it as such.
Then his last shift was, to call upon us for a confession of our own faith,
and directed his demand to our friend Richard Johns in particular,
with whom he was acquainted.

We denied that he had any authority to make such a demand from us, nor should we,
on his own account, take any notice of him therein,
he appearing as an adversary and a perverter; but for the sake of the people,
were willing to say what might be sufficient to satisfy
such as were not prepossessed or prejudiced against us:
and then Richard Johns began, and proceeded after this manner;
"`We believe that the Lord Jesus Christ, who was born of the Virgin Mary,
being conceived by the power and influence of the Holy Ghost,
is the true Messiah and Savior--that he died upon the cross, at Jerusalem,
a propitiation and sacrifice for the sins of all
mankind--that he rose from the dead the third day,
ascended, and sitteth on the right hand of the Majesty on high,
making intercession for us; and in the fulness of time,
shall come to judge both the living and the dead,
and reward all according to their works.`"
All which being more fully spoken to by Roger Gill, we asked the people,
if they were satisfied with that confession?
and they generally, from all quarters, answered, "`Yea, yea, yea; it is full,
no man can deny it.`"

The priest being disappointed in his expectations,
and his wicked purpose of exposing us as no Christians frustrated,
the next day he came again, and brought one of his brethren with him;
and they again eavesdropped the meeting.
But my companion being in his testimony, and apprehending they were within hearing,
cried aloud to them to come forth out of their
holes and corners and appear openly like men,
and if they had any thing to say, after the meeting was over they should be heard;
and a little after, they came into the meetinghouse, one at one door,
and the other at the other, and many crowded in after them.

My companion having done, it fell to my lot to speak next;
and having opened several things concerning the coming of Christ in the flesh,
I said something also concerning water baptism, as used by John the Baptist; which,
though once a dispensation of God to the Jews, and then of use to them,
yet is long since abolished, in the conclusion whereof I informed the auditory,
that as for sprinkling infants, it is foreign to Scripture,
and I could look upon it to be no other than a Popish relic;
and since the national church had espoused it,
and asserted it as an ordinance of Christ by practice,
and some of her ministers were there present, I requested them to make it appear,
if they could, when the meeting was ended,
that Christ ever instituted or commanded that baptism, or pretended baptism,
which they now use.
Aaron Atkinson concluded the meeting by prayer;
and the blessed Truth was over all to general satisfaction, especially to Friends,
who were filled with divine consolation.

The meeting, as to Friends,
ending in peace that passeth the understanding of all priests who preach for hire;
one of them, viz., Henry Hall, stood up, and pretended to prove sprinkling of infants,
as used by the church of England, to be an ordinance of Christ.
Many justices of peace, and others of note of both sexes, were present,
and he began with a preamble, in which he so rambled from the matter proposed,
that he ended in a pretense to prove the right of the priests to tithes,
or some other legal maintenance; as if that were the sum of their religion,
and all they meant by their profession.
Which impertinence I noting to the people, the priest was justly interrupted,
and called back to make good his first proposition, which he evaded, saying,
he did not propose to do it then, but would another time.

We appealed to the people, many of them having come that day far and near,
and great part of them the hearers of those priests, concerning the state of the matter,
and whether the priest had proved what he had undertaken;
and they generally granting he had not, we held him to it,
as most reasonable and profitable to be done, if he could, in the same auditory.
But he utterly evading it, fell under the censure of the people, who,
seeing their weakness, generally contemned them.

When the invincible truth came thus over their lofty and self-confident heads,
and their spirits were fallen under their own party and hearers,
I put them to prove their call to the ministry; which they taking upon them to do,
only told us, that Christ called apostles, and they ordained others,
and they again others, in succession to that time.

Then I called for their proof, who they were that the apostles ordained, and who,
from age to age successively, were so ordained; wherein if they failed,
they were justly to be rejected as no ministers of Christ,
since they had rested the matter on such a succession and credentials.
One of them repeating the same assertion only as before,!
returned it upon him as his own proofless say-so only.

Many of that people then, seeing their ignorance, said, "`We`'ll pay you the tobacco,
being obliged thereto by law, (that is,
forty pounds of tobacco for every negro slave) but we will never hear you more.`"

While we were yet in the gallery, one of their hearers, who climbed up into a window,
cried out with a loud voice to Henry Hall, "`Sir, you have broken a canon of the church:
you have baptized several negroes, who being infidels,
baptism ought not to have been administered to them.`"

At this the priest was enraged, but made no answer to the charge, only frowned, fretted,
and threatened the man to trounce him.
Then I observed to the people, that if those negroes were made Christians in their sense,
and members of Christ, children of God, and inheritors of the kingdom of heaven,
received into the body of the church of Christ,
as their language is at the time of sprinkling,
how could they now detain them any longer as slaves?

Several of the justices of the peace being ashamed of their priests,
slid out of the meeting as unobservable as might be,
and the people in general openly contemned them as such,
who behind the backs of the Quakers had greatly reproached and belied them,
but face to face were utterly baffled and subdued by them.
That night several of the justices lodging with our friend Samuel Chew,
expressed their sentiments altogether in our favor,
and that their priests were really ignorant men in matters of religion.

The next day being the meeting for discipline and business, abundance of people came,
and finding no public meeting for worship, many remained till they saw no hopes of any:
the following day likewise came many,
the meeting continuing a day longer than was expected,
who remaining till the business was over,
we had a comfortable time together in the presence and love of God,
in which our meeting concluded, to our great satisfaction, and the praise of the Lord,
who alone is worthy.

We went that afternoon to the bay of Chesapeake,
and many Friends and some of the people with us, to see us embark.
We were all that night upon the water, viz: Griffith Owen, Aaron Atkinson,
my companion and myself, and went home about the break of day,
with our friend William Sharp, in whose vessel we had come over.
On the 4th day of fourth month, being the first of the week,
we had a large and good meeting near the place,
where we had the company of many people besides Friends;
and after the meeting went with a Friend, whose house was on our way.

We went on next morning, and the day proving wet it was a little uncomfortable;
but the rain ceasing about noon, we alighted in the woods near a rivulet,
and made a fire, and some of us having biscuit and neats tongue, we eat to satisfaction.
We went that evening to the house of a Friend, a widow, where finding the Son of Peace,
we were well entertained and refreshed next morning with her and the family,
in a comfortable season in the truth.

The following morning Griffith Owen,
my companion and I set forward for Newcastle upon Delaware;
but Aaron Atkinson remained in order to visit some meetings thereaway.

At Newcastle we met with our good friend Samuel
Carpenter and other Friends of Philadelphia,
and +++[+++proceeding to that city]
were kindly received to lodging with him.
The fifth of the week we had a large meeting there,
and were much comforted in the blessed Truth among Friends,
staying over the first-day meeting and the third-day following;
we had a meeting at Merion, with the Welsh Friends, on the 15th,
among whom I was much satisfied.
Several of them appeared in testimony in the British tongue, which I did not understand;
yet being from the word of Truth in them, as instruments moved thereby,
I was as much refreshed as if it had been in my own language.
This confirmed me in what I had thought before,
that where the Spirit is the same in the preacher and hearer, and is the truth,
the refreshment is chiefly thereby, rather than by the form of words or language,
to all that are in the same spirit at the same time.
This is the universal language of the Spirit,
known and understood in all tongues and nations to them that are born of him.
In order to the convincement of such as know not the truth--for the
begetting of faith in such as do not yet believe therein--for the
opening of the understanding by the form of doctrine,
and declaration of the necessary truths of the gospel and kingdom of God,
intelligible language, uttered under the immediate influence of the Spirit of Truth,
is indispensably necessary; as also for the edifying of the church, the body of Christ,
in general.

That evening we returned to Philadelphia, where we stayed till the 17th of the month,
and then went to Burlington, in West New Jersey, and lodged with our well known,
and very hospitable friend, and able minister of the gospel, Samuel Jennings,
and the next day being the first of the week, had a large and good meeting there.

On the 19th we had a meeting at Crosswicks, in Jersey,
about fifteen miles towards New York;
next day travelled through the woods about thirty miles, to an inn,
and next day in the afternoon we arrived at Elizabethtown, in East Jersey,
where we took boat about eleven at night,
and landed at New York about four in the morning.
The day following had a small meeting there, and on the 24th,
being the seventh of the week, we went thence by water to Long island.

Passing over the sound to West-Chester, upon the main,
we fell in opportunely with a yearly meeting, about twenty miles from New York,
and on the 26th set forward for Rhode Island, about two hundred miles.
At Stanford, in the colony of Connecticut, a considerable village,
we inclined to have a meeting, and acquainted our landlady with our intention,
and desired of her the liberty of her house for that purpose, which she readily granted,
so far as it was in her power; for their,
laws and magistrates were very strict and severe against Friends,
of whom there was not one in all that country.
To secure the good woman from any hurt by her good will toward us,
we went to a justice of the peace, and informed him of our intention.
He was an ancient man, and moderate in his natural temper, but worse for his religion.
He questioned the sufficiency of our calling to that service.
"`What call,`" said we,
"`dost thou think is necessary in that case!`" "`The call of the people,`" said he.
"`Our calling is of God,`" said we; "`and if the people hear us,
let the Truth in their hearts, to which we desire to be made manifest,
judge whether we be called of God; and any other calling we do not regard.`"
"`Then,`" said he, "`I will not tolerate you.`"
"`We do not come for thy toleration,`" said I,
"`but only to acquaint thee with our purpose, as thou art a magistrate,
and we being strangers, there might be no surprise by such a concourse of people.`"
Then he gave us a hint that he would use means to deter them from coming to hear us;
and so we returned to our inn.

When there, we met with some people come in as though to refresh themselves,
but rather to see us: for generally they are either afraid of us,
as if we were deluders and deceivers, or they are so much under their priests and laws,
that they dare not be seen with a Friend.
Their dead faith and religion depend so much upon their priests,
that they scarcely dare look toward the truth, or hear any but them.
That evening we had conversation with some of them concerning the occasion
of the coming of their ancestors out of England into that country,
then a wilderness, upon account of religion, for which they had been persecuted there;
which seemed a new thing to several of them.
And supper being ready, I had something in prayer before we ate,
and the people were still and attentive,
and seemed pleased to find the false accounts they had received, refuted, viz:
That Quakers receive the mercies of God as the brutes, never craving a blessing,
nor returning the Lord thanks.
And we informing them of our intention of having
a meeting there next morning at the ninth hour,
they departed friendly.

The time came, and many of the people; and whilst we sat in silence, came a constable,
and another to assist him, with a warrant from one John Sillick, the mayor of the town;
in which were several invectives and false charges against us, as heretics, blasphemers,
deniers of Christ, and the like; dictated, as we conjectured from some circumstances,
by their priest, who went out of the town and left his flock.

The warrant being read,
I stood up and acquainted the people with the law of toleration in England,
the moderation of the king, and temper of the government and people there towards us;
and that they of Connecticut ought not by their
charter to have any law there to the contrary.
But the constable and his rude assistant replied,
they did not depend upon the laws of England, but stood upon their own foundation,
and they had a law that no Quakers should have any meeting among them,
and none there should be, and then commanded us to be gone.

My companion being filled with zeal, stood up and spake to the people,
and the constable commanded him to be silent, of which he took no notice, but went on.
Then the constable came close up to his face in an angry manner, repeating his command;
but my companion in continuing his speech,
recounted to the people the wickedness of that anti-christian spirit in New England,
where they had whipped, and many ways abused and persecuted our friends,
cutting off the ears of some, and hanging others, because they were Quakers,
and came into their country, though they came in love,
as the peaceable messengers of God to them;
that the same spirit was yet alive among them in Connecticut,
and would be at the same cruel work still, but was overruled by a better power.

The constables not being able to effect their purpose upon us,
commanded the people to disperse, some of whom still remaining,
they at last commanded our hostess to forbid us her house; which she did with trembling,
and then we went into the streets, and through them,
my companion crying with a loud voice all along, "`Woe, woe, woe,
to the inhabitants of this place, who profess God and Christ,
without the knowledge of God, and void of his fear;`" with some such other words,
in a power and dread that amazed many of the people; and we going back towards the inn,
and standing before the door in the street, many came about us,
and there he had a pretty full and good time among them.

When this was over we went into the inn,
where several of their elders came to dispute with us.
The first matter pitched upon was the universal free grace of God to all men,
through our Lord Jesus Christ; which we asserted and fully maintained over them,
which being contrary to their beloved and false doctrine of personal predestination,
it occasioned a discourse on that subject; which they asserted, and we opposed.
An unlikely disputant came and placed himself at
the head of the table and espoused their cause;
and the proof being incumbent upon them, he, with great confidence, asserted,
that God said, "`before Jacob and Esau were born, that he loved Jacob and hated Esau;
and that it was the pleasure and decree of God from everlasting so to do,
without any cause in either of them, being before they had done good or evil.`"

Then I called for one of their Bibles, and told him,
"`He and they all were in a great mistake concerning that Scripture; for God did not say,
before the children were born, '`Jacob have I loved, and Esau have I hated;`' but said,
'`Two nations are in thy womb,
and two manner of people shall be separated from thy bowels;
and the one people shall be stronger than the other people,
and the elder shall serve the younger.
Here the answer of God being a prediction,
had no respect to the persons of Jacob and Esau;
nor was it ever fulfilled personally in them.
For Esau, who was the elder, never served Jacob in person; but on the contrary,
Jacob did obeisance to Esau, and called him his lord, Gen. 32:18,20,4.

"`This prediction then was written concerning the differing posterity of Esau and Jacob,
and not their persons, and was fulfilled in the Edomites of Mount Seir, who came of Esau;
and Israel, who came of Jacob:
and the displeasure of God against the Edomites was not
from any fore-hatred or decree of God from eternity,
as ye suppose; but the moral cause of his displeasure and their ruin was,
their great sins and wickedness, as declared by the prophets of God;
and first by Ezekiel, '`Behold, O Mount Seir, I am against thee,
because thou hast had a perpetual hatred,
and hast shed the blood of the children of Israel by the force of the sword,
in the time of their calamity,`' etc.
And likewise by Amos; '`Because he did pursue his brother with the sword,
and did cast off all pity, and his anger did tear perpetually,
and keep his wrath forever.`'
And also by Obadiah, against Esau, that is, Edom, '`For the pride of thine heart,
for thy violence against thy brother Jacob, shame shall cover thee,
and thou shalt be cut off forever.`'
And last of all by Malachi, who hath it thus, '`Was not Esau Jacob`'s brother,
saith the Lord; yet I loved Jacob, and hated Esau,
and laid his mountains and his heritage waste.`'
etc., which was for his pride, obstinacy, and opposition, persisting in final rebellion,
impenitence and contradiction.
All which is still concerning Edom and Israel, and not the persons of Jacob and Esau,
the last of those prophets having wrote about one thousand four
hundred and forty-one years after the prediction of God to Rebecca,
concerning their posterity.

"`The apostle in his epistle to the Romans, where he saith, '`as it is written,
Jacob have I loved, but Esau have I hated,`' refers to that of Malachi, as above,
about four hundred and fifty-seven years after Malachi wrote that prophecy.
In that chapter the apostle was laboring to convince the Jews,
that they are not the true seed, or elect of God, as they seem to have imagined,
because they were the descendants of Abraham, Isaac, and Jacob, after the flesh.
But Esau, being a rough, wild, hairy man,
was a figure of the first birth of man after the flesh,
as a son of the first Adam in the fall, who, in that state,
cannot inherit the kingdom of God; and Jacob, a figure of the second birth,
or regenerate state of man, in Christ the second Adam; who never fell, nor could fall.
For saith the apostle, '`they are not all Israel, who are of Israel; neither,
because they are of the seed of Abraham, are they all children;
but in Isaac shall thy seed be called: that is,
they who are the children of the flesh,`' are not the children of God;
'`but the children of the promise are counted for the seed.`'

"`The promise is Christ, the Messiah, the elect and promised seed of God;
of whom it is written,
'`I and the`' children which thou hast given me:`'
which children are all that believe in him,
as he is the man Christ Jesus, the Son and Word of God, and light of the Gentiles,
and are born of him, by the influence of his holy Spirit working in them.

"`And as the Edomites hated and persecuted Israel,
and took all occasions and advantages against them to do them hurt, till,
for so doing they were cut off, and for their other sins, when full;
so likewise the Jews, hated, rejected, and persecuted Christ, the elect of God,
for which they also were cut off, and remain infidels to this day.
Those also now, as in all ages, who are born only after the flesh,
and not after the Spirit, do hate, persecute, and as much as they can,
destroy them who are born of the elect seed of God, after the Spirit, for which,
if they repent not in time, they will likewise be cut off, and perish everlastingly.`"

This weakened one of our opponents, and his spirit fell,
and the better part came a little up; but another foolish disputant, in a precipitant,
ungovernable, furious zeal, said, "`I affirm that all the sins Esau ever committed,
were the effects of the eternal decree of God, and hatred against him,
before he was created, and not the cause of that wrath and fore-hatred.`"
And so, in a rage, would have run away, but I kept close to the table,
he being behind it, and hindered him; and looking him in the face, replied, "`I affirm!
Who art thou?`"
looking upon him till his lofty spirit fell under, and then repeating the assertion,
I demanded his proof from the Scriptures, but none could be had.

Then I returned it upon him as a false, blasphemous,
and unjust charge against the Almighty, under which he remained silent;
and the other asking me a question, to be informed concerning the light of Christ in man,
which he confessed he knew nothing of,
he slunk away in the mean time through the crowd
of people on the other side of the table,
and made off out of the house.
The Truth came over all,
and I believe several understandings were in some degree opened on that subject,
and some other points; for we had no further dispute,
but the other opponent and the people parted with us in a friendly manner,
the better part being sensibly reached and above.
We departed in the peace of our Lord Jesus Christ, to whom be the praise of all;
for of him is the understanding and power now and forever.

That evening we went forward to Fairfield, about twenty miles,
and lodged at the house of one Philip Lewis.
He told us there was to be a great meeting of their people, and a quarterly lecture,
in that place next day, to the inhabitants of seven townships and all their ministers.
We took notice of it, but said nothing;
in the morning my companion told me he thought he could not go clear from thence,
if he did not go to the lecture; at which I was well pleased,
for I had likewise a secret inclination to be at the meeting,
but not having seen clearly a sufficient warrant in myself for such an undertaking,
I was not forward to engage or speak of it.
Walking into a field, I sat down upon a stone on the top of a little hill,
and the word of Truth began to work in me more fully and clearly;
and then I received not only free will, but likewise power,
yet still kept the thing to myself.
Returning to my companion at the inn, thither came the priest of Stanford,
before mentioned,
to inquire privately of our landlord whether we intended to appear at their lecture;
which he not knowing, told him he would inquire of us,
and then we were free to tell him it might so fall out--which he told the priest,
who took it for granted, and returned to the rest.

We went to the meetinghouse, and they had begun their prayer,
which we perceiving as we approached the door, did not then enter,
lest we should offend them with our hats,
for we did not intend to interrupt them in their worship; but going aside,
we sat down upon the green, where we could hear the voice of him that prayed,
though not distinguish his words.
He made a very long prayer, which being ended, they sang a Psalm of David,
and we stayed till that was over,
and then entered as the preacher was giving out his text,
which was from the first three verses of the
fifty-fifth chapter of the prophecy of Isaiah,
in these words, "`Ho, every one that thirsteth, come ye to the waters;
and he that hath no money; come ye, buy and eat; yea, come,
buy wine and milk without money and without price.
Wherefore do ye spend money for that which is not bread;
and your labor for that which satisfieth not?
Hearken diligently unto me, and eat ye that which is good,
and let your soul delight itself in fatness.
Incline your ear and come unto me; hear and your soul shall live;
and I will make an everlasting covenant with you, even the sure mercies of David.`"
This text we were well pleased with,
for he could hardly have taken one more apt against himself, and all others,
whose ground of preaching is their own gain and livelihood, and for their own honor,
interest, and advancement in the world.
He divided his text into four heads, and then into several branches and subdivisions.
His sermon would be too tedious to recite, nor can I, verbatim;
but in the handling of the matter, he asserted,
the universal free grace of God in Jesus Christ, and that he is offered to all,
but many reject him for the trifles of this life,
and consequently their damnation is of themselves, etc.

The sermon being over, the minister went to prayer; which being finished,
the priests and people began to move away,
which was scarcely discernible till Roger Gill, my companion,
stood up on a form and began to speak, saying,
"`We have patiently heard what hath been declared, and having something likewise to say,
we expect the like moderation from you.`"
Upon which the people halted and would have heard; but in a moment,
five of the preachers who were in a gallery, descended from thence,
and the other two arose from their seats and called to the people to depart,
and some of them cried aloud for the powers.
He that had preached took Roger Gill by the hand as he stood on the form,
and prayed him to come down; and Roger urging the reasonableness of our liberty to speak,
since they had done, the priest of Stanford cried out, "`Sir, you are not qualified,
you have no call from the people as we have.`"
To which Roger replied, "`Have you your qualifications and call only from the people?
Our call is from God, and we recommend our testimony to the consciences of the people:
through the grace of God we call them to the faith and obedience of Christ,
and not they us.`"

Then the priest rejoined, that their qualifications to preach were of God,
but the call of the people was also necessary; and then cried out,
"`Where are the powers?`"
Upon which, Nathaniel Gould, their justice,
commanded the constables to take us into custody, one of whom arising from his seat,
his next neighbor pulled him down, many being desirous to hear us;
but soon after several of them came and haled us away.
Then I called to the people, and told them,
they wore not from thenceforth to pay any thing to their ministers for preaching,
since they had made open proclamation, that all was now to be without money or price;
at which many of them smiled.
I had not said any thing before.
The constables took us out from among them, to the further side of a large street;
and then I demanded a sight of their warrant,
and they confessed they had none but the justice`'s command.
Then I took their names in writing, and admonished them to beware of false imprisonment,
for they themselves knew that I had neither done nor said any thing against any law.
They replied, we were not in prison.
"`But,`" said I, "`custody is imprisonment by the law of England.`"
Then they were a little surprised, and my companion went from them back to the people,
most of whom were remaining about the meetinghouse,
and there he had a good opportunity to clear himself.

While he was speaking, a predestinarian, for he spake against that tenet,
came to interrupt him; but another of their own party pulled him away, and said,
"`The man spake truth.`"
I also kept several of them off by giving them soft words,
and desiring them to be patient till he had done,
and then to object if they had any thing against him;
but he met with no opposition in the end,
for after a while they were generally very sober, and some tender.

When he had finished, I did not find any thing upon me for the people,
but asked them where their ministers were, for I had a mind to see them;
and several were forward to show us they were
gone to the house of the minister of the town,
and we went thither.
When we came, we understood they were at dinner,
and the master of the house coming to us, I told him, we desired to speak with them,
but seeing it was then unseasonable, we would call after they had dined.
He kindly invited us to eat with them, and said we should be as welcome as any there;
but we returned to our inn, and after refreshment went back to them.

When we entered the room they generally arose
from their seats to tender their civilities,
only the preacher, being old, and weary with the work of the day, and lying upon the bed,
did not arise, but spake kindly to us.
Seats being set, I sat down upon the bed`'s foot, at the feet of the preacher,
and some of them urging me to take a chair, as a better seal,
I told them I took that seat for the better advantage of seeing them all at once.
Being a short time silent, I began to expostulate matters with them,
about their treatment of us in their meetinghouse,
reminding them of our behavior and patience, adding, that we came not to disturb them,
but in Christian love and good will to them and the people,
urging their duty to us as strangers, and the order of the gospel.
I recounted also to them the occasion of the coming of their ancestors,
if not of some of themselves, being ancient men, into those parts of the world,
then a desolate wilderness, viz: for conscience sake,
as dissenters from the national worship of England.
That it looked unaccountable, that they who had been hated, imprisoned, plundered,
and divers ways persecuted for that which was, or seemed to be,
matter of conscience to them, should now use the like practices,
against such as for conscience sake were appearing against
some things yet unreformed among them and their people,
both in doctrine and practice, among which,
a necessity of being called by the people to minister to them, is one.

This brought that point again into question, and John Davenport being, as we supposed,
the most learned and best orator among them, undertook it, and asserted,
that Christ called and ordained twelve apostles, and they ordained others,
and those again others successively unto this day.

That Christ ordained twelve apostles, we granted;
but denied that any at this day were in a lineal
succession from the apostles so ordained,
and put him upon his proof, and that they themselves were so ordained by such succession,
but he could make nothing of it.
All he could say for proof amounting to no more than his say-so,
or a repetition of the assertion.
And he also slunk from the question about the call of the people to their ministers.

Then said I, "`But if it were possible to prove such a succession, who are ye?
How like are you to the apostles?
How doth it appear that you are such?
How and what do you succeed them in?
You greatly err in your practice from the apostles of Christ.
For where do you find that ever they sat down in little corners of the world,
and received maintenance from the people for themselves and families?
And of such too as were not able or willing to pay them?
As your case is; (for some of them had, by a law,
taken the very wearing apparel of some poor people that could
not pay them) to take from them their goods and apparel?`"

Then their champion being in a rage, spluttered out a mouthful or two of Greek,
signifying, that Paul the apostle had robbed other churches,
taking wages of them to supply the wants of the Corinthians, to whom he then wrote; and,
"`thou shalt not muzzle the mouth of the ox that treadeth out the corn.`"

To which I replied, that their sect, as well as others,
had justly blamed the Papists for having their service in an unknown tongue;
and I suspected that the using of it then was for the like end,
that the auditory might not understand; (for there were many people,
and of the greater sort among them, present) so that they might have an opportunity,
after we were departed, to say they had overcome us.
I then bid him repeat those Scriptures in English,
that the people might hear they were nothing to his purpose; which,
after several evasions he did, first saying after a scoffing manner,
"`If you be a minister of Christ, inspired of the Holy Ghost,
surely you know the tongues.`"

I replied, "`It is not a sentence or two of Greek, or of any other language,
that renders a man knowing in those tongues;
nor is that an essential qualification to a minister of Christ.
The prophets of God, of old, spake to the people by the spirit of Christ,
but in their own language; and so did the apostles too,
notwithstanding the gift of tongues, which every minister had not;
and that gift was also to cease, and is ceased, though inspiration remains,
and no man is either a minister of Christ, or a Christian, without it.
'`He that hath not the spirit of Christ, is none of his.`'
And where a minister speaks in a language understood by the people to whom he is sent,
it answers the end of speech, to all intents,
though neither he nor they understand any other.
And I am of the mind of the apostle, who said,
'`I had rather speak five words with the spirit and understanding,
than five thousand in an unknown tongue;`' yet
thou dost not know what I understand of Greek,
or any other than that in which I now speak.
But, to invert thy own terms.
Art thou a minister of Christ?
And hast thou thy tongues by inspiration?
Or art thou a sootier at inspiration, and a minister of Christ, without it?`"
To which he was silent, and I went on to show to the people,
that the texts he had cited were nothing to his purpose,
and that he and his brethren had nothing to do with them.
For in the first place, they could not prove their succession as ministers of Christ,
as they had proposed; and failing in that,
they had no right to claim advantages due only to such.
In the second place, what the apostle there received,
was not for the maintenance of himself and family,
but for the service of the congregation in a time of general want.

And as to the treading out of the corn,
he had not yet proved that he or they were of those oxen,
or that they trod out that corn;
and therefore the Scriptures which might be applicable
to the apostles and ministers of Christ,
were but wrested, as applied to him and them, and their case:
for the apostles never had such maintenance as theirs,
but wrought with their hands for their support, and the help of others also,
which was not their practice.

He then betook himself to railing and abuse, and gave us scurrilous language and names,
calling us grasshoppers, schismatics, heretics, deceivers, and the like;
and pretended to prove his rude charge by a syllogism, which he formed thus:
"`What people soever deny the Lord Jesus Christ and his ordinances,
and set up the light of the devil in themselves for a Savior, are heretics.
But the Quakers,
ever since George Fox preached up that light in themselves for the Savior of the world,
have denied the true Christ and his ordinances,
therefore the Quakers are heretics and blasphemers.`"

Then I looked upon the people round about, and said,
"`Do you think that this man behaves like a minister of Christ?
Is this language becoming such a one?
What spirit do you think, is he of?
And from whom proceeds this behavior?`"
Upon which some smiled, and others blushed.
Then I proceeded to answer him, "`That we do not, nor ever did,
deny the Lord Jesus Christ, nor any of his ordinances,
in their various and proper dispensations and seasons; but say, God is light,
and so likewise is Jesus Christ the Son of God,
the eternal emanation of the Father`'s glory.
He is the Word, Wisdom, and Power of God; the Word that was made flesh,
born of the Virgin Mary, and dwelt among his people, the Jews,
under the name of Jesus Christ, which is also that true Light,
which enlightens every man that cometh into the world.
And neither George Fox, nor any other minister of Christ among us, nor we,
ever preached any other Christ or light but this,
which one of your ministers here calls the devil.
Let him therefore look at his own heresy and blasphemy, and repent.`"

I then observed to the people,
that their ministers were utterly unable to prove any call they had to a gospel ministry,
as they might plainly perceive by what had then passed between us.
And my companion was all this time keeping the rest in order,
that they should not break in upon us with other matter, till that was discussed,
as they often attempted.

"`As to the other pretended proof, that we are heretics, it is, he saith,
because we deny the ordinances of Christ, as he calls them;
and by the ordinances of Christ, he and they mean water baptism, and bread and wine,
and by baptism they mean the sprinkling of infants in the face with water,
in the name of the Father, Son, and Holy Ghost,
as by their frequent practice is evident to the world.`"
I told them they had deceived the people,
in administering that to them for an ordinance of Christ which he never commanded;
and that whoever set up and administer for
ordinances of Christ what he hath not commanded,
are liable to the curse.
For if God will add the plagues written in the book,
to such as shall add to or take away from the words of the book,
and if their part shall be taken out of the book of life,
how much more may not the Lord one day inflict his judgments
and condemnation upon such as presume to add any thing,
or take away from any of his ordinances, or any thing commanded by him?

"`You say, in your catechism, that baptism with water is an ordinance of Christ,
necessary to salvation; and what you mean thereby is plain as before.
I therefore demand your proof, that sprinkling infants is an ordinance of Christ,
necessary to salvation, and that they are heretics who decline the practice of it.`"
This gave all the priests very much disturbance, but the people were grave and silent,
and they earnestly pressed, first to prove water baptism an ordinance of Christ,
and then they pretended to prove the other:
but we insisted that they had nothing to do with baptism,
but to prove the sprinkling of infants, as they used it, to be an ordinance of Christ;
for this is a day wherein every man, and sect too,
must be judged according to their works, and not by the works of other men.
Then we observed to the people,
that their pretended proof of water baptism was only a
subtlety to alter the state of the question,
and introduce another thing, which they have no right to maintain till they practice it.
Let them first be baptized themselves, and then we may reason with them on that subject.
For when we talk with Baptists we know what to say, and to them too, if it were proper,
but sprinkling is their point to prove, or nothing.

Then John Davenport arising from his seat,
turned his back upon the people and pretended to
prove infant baptism an ordinance of Christ;
but we still insisted on sprinkling, not baptizing, of infants, as their proper task,
and at length he undertook it, and began thus: 1st; That Christ said,
"`Suffer little children to come unto me, and forbid them not.`"
2ndly; That the jailer`'s family, as we read in Scripture, were all baptized,
and there might be children among them.
3rdly; And that the commission was to baptize the whole world,
and surely there were children there.

To this I replied, that what he had advanced for a proof was altogether fallacious;
for first, the end the people had in bringing their children to Christ was,
not to sprinkle or baptize them, for he baptized none,
but that he might lay his hands upon them, and bless them;
in which he answered the faith and expectation of the people, saying,
"`Of such is the kingdom of heaven.`"
The Son of God therefore having thus blessed them, and declared their innocence,
being yet neither baptized nor sprinkled, let us leave them safe in his holy arms,
and under his care, protection, and blessing, where they are fully happy,
without any thing you can add to their condition.

2ndly; As there might be children in that jailer`'s family,
so likewise there might be none, and where the Scripture is silent as to facts,
we ought not to presume to speak, and from a bare possibility to assert a fact,
especially in a thing of this moment, is not good reasoning.
Besides, it is plain there were no children in the jailer`'s family,
for they all believed, which children cannot do; and to keep to the point,
those believers were baptized, not sprinkled.

And 3rdly; As to that text alluded to, with other concomitant Scriptures, they lie thus:
"`Repentance and remission of sins should be preached in his name among all nations,
beginning at Jerusalem:`" That "`all power is given unto him, "`in heaven and in earth.
Go ye therefore,`" said he, "`and teach all nations,
baptizing them in the name of the Father, Son, and Holy Ghost;
teaching them to observe all things whatsoever I have commanded you, etc.
Go into all the world, and preach the gospel to every creature;
he that believeth and is baptized shall be saved;
but he that believeth not shall be damned:`" and that they "`should
be witnesses unto him of these things;`" of his life,
doctrine, miracles, sufferings to death on the cross, resurrection and ascension,
"`both in Jerusalem, and in all Judea, and in Samaria,
and unto the uttermost parts of the earth.`"
The subjects of this baptism, not rantism, are such as have sinned,
and are capable of being taught or discipled--of believing--of
repentance--of observing all his commands to do them--of receiving
their testimony and doctrines of the gospel in all these particulars,
on pain of damnation; of which children are not capable,
and therefore not included in the intent and nature of this commission,
though living in the world.

The word bapto, of which comes baptizo, in the Greek language, signifies to drown,
or sink in water; to dip; to overwhelm; to plunge; to thrust in, or to go into water;
to steep, or infuse; to dye, or color; to tincture, or, as it were,
to impregnate one thing with the nature of another; as if the subject of baptism,
which is dipped, should be impregnated with the qualities of the instrument of baptism,
into which it is dipped, or washed.
But when the Greeks would express sprinkling,
which is a different act from washing or baptizing, they do it by the word rantizo;
which, in its various modes, is always used, as Heb. 9:19, where it is,
'`errantizo and Heb. 10:22--xii.
24, 1 Pet. 1:2, rantismon aimatos Iesu Cristo,
and sprinkling of the blood of Jesus Christ.
See Heb. 9:21. errantize he sprinkled, etc.
So that rantizing, or sprinkling of infants, is an ordinance of Christ,
and that they are heretics, schismatics, who decline it, are yet to be proved,
and is a false and unchristian charge.

He was loath to yield the point before the people,
being a matter of great importance to their function, and therefore rejoined thus;
"`The reason of things in this, as in all other matters,
ought to have some consideration and sway in this case:
the baptizing or dipping of children in cold countries, might hazard their lives;
and for that reason, may be indulged with sprinkling only,
as thereby rendering the ordinance more safe and commodious.`"

To this I replied,
"`That though this was sufficiently answered in what had passed before,
yet I would give it a more particular return:
that the greatest part of the habitable world lies in the torrid and two temperate zones.
In the first it is sufficiently warm at all times,
without any hazard of infants taking cold by baptism, or washing;
so that if they were the subjects of baptism, as they are not,
the mode need not be altered from washing to sprinkling on that pretense;
and in each temperate zone it is likewise sufficiently warm great part of the year,
and never so cold as to hazard the life or health of a child by dipping in cold water,
and they are not forbid to warm it;
for the common practice of the Indians upon their children,
in the coldest parts of the habitable world, proves it;
where they wash their children in cold water
immediately upon their being born into the world,
the better to harden them to the climate they are in, without any such effects:
on the contrary, it renders them more hardy and healthy.

"`And besides, the Lord Jesus knowing all objections, makes no exceptions;
which infinite goodness and wisdom would have done, if proper in his sight,
and wanted no assistance in the manner or extent of his ordinances, from the ignorant,
and weak, yet too bold and presumptuous reasonings of poor mortals, how high, lofty,
and conceited soever they may be in their own earthly wisdom and imaginations.
And thus erring from the truth, in mode, subject, and instrument of baptism,
you have none at all; but are deceived yourselves, and have deceived the people.`"
And thus, being tied down to their own practice, by the secret invisible power of Truth,
he was totally silent, and they did not offer any further argument upon it.

Then I addressed myself more particularly to the people, and told them again,
"`They had no baptism, but were only in the practice of a relic of Popery,
instead of an ordinance of Christ: for the anti-christian church of Rome,
imagining children to have original sin,
and that something should be done to clear them of it,
they thought upon water baptism as the effectual means;
which accordingly they administered.
But afterwards they declined baptism, and substituted rantism, or sprinkling,
first to sick or weakly children,
and afterwards extended their new invention to all children:
so that water baptism was wholly dropped, and John the Baptist`'s prediction fulfilled,
'`I must decrease,`' that is, his baptism, '`but he,`' that is, Christ,
and his baptism with the Holy Ghost, '`must increase.`'

"`To their new invention,
they added several superstitious and ridiculous actions and ceremonies:
they appointed god-fathers and god-mothers; the priest breathes in the child`'s face,
signs him on the breast and forehead with the sign of the cross,
but without any remaining mark; puts salt in his mouth,
and spittle upon his ears and nostrils, and asks him, though he understands nothing,
if he will renounce the devil and all his pomps; anoints him with oil on the head,
shoulders and breast, and gives him a white chrysom,
and puts a hallowed candle in his hand.

"`The effects they ascribe to all this are, 1st;
It makes the subjects thereof children of God, and remits both original and actual sin.
2ndly; It infuseth justifying grace into the soul, with habits of faith, hope,
and charity, and all supernatural gifts and virtues.
3rdly; It makes a spiritual mark or character in the soul, which shall remain forever,
either to their great joy in heaven, or confusion in hell.

"`But when the Lutherans and Episcopalians in England reformed a little from Rome,
they laid aside the superstitious part, except god-fathers, god-mothers,
and the sign of the cross on the forehead, which they still retain;
and ascribe the like effects to their act of sprinkling,
and the ceremonies and prayers they use on that occasion.
And when your predecessors, the Presbyterians and Independents in England,
reformed and dissented from them, they rejected the sign of the cross, godfathers,
god-mothers, and forms of prayer used by the church of England,
as Popery and superstition: but their eyes being but once touched, they saw men as trees;
not perceiving that sprinkling of infants is Popery,
an anti-christian invention as well as the other;
which remaining unreformed by your first reformers,
has passed to you of this present age by tradition, unexamined and unreformed.
And so ignorant, or willfully blind are your ministers,
that we are here branded before you as heretics, schismatics,
and deniers of the ordinances of Christ,
for testifying against Popish inventions and relics.`"

While I was upon this, several of the priests,
very willing to cover themselves from their people, started up;
and everyone had something else to offer.
But my companion, being a bold man in the cause, kept them back and told them,
their several somethings else being foreign to the present subject,
ought not to be admitted, till this should be settled; which concluding as above,
he then challenged all the seven ministers,
that if they would call a meeting of all the
people of their seven townships to that place,
we would stay, if it were some days, and discourse with them on what points they pleased,
openly before them; but they refused, and so their somethings else came to nothing.

In the mean time, while he was thus challenging them,
I sat down again on the bed`'s foot by the old minister, and the rest of them;
and the people being in motion, he arose and came to me, and took me by the hand,
and whispering, said, "`Pray sir, cannot you pass quietly along,
and let those things alone; for though there is little in them,
the people have a belief therein; they think well of them; they are innocent things,
and do them no harm.`"

To which I answered, "`That they and their forefathers said, and do say,
they were conscientious in discovering and rejecting the
errors and superstition of the Papists and Episcopalians,
in this and other points, and in exposing them to the people; so are we, in our time,
conscientiously concerned for the love of truth and souls,
without any other consideration,
to expose to the view of mankind such errors as yet remain among them,
as we are enabled by divine grace to do it.
This matter of sprinkling infants, though of little account in itself; yet,
as it is set up as an ordinance of Christ, which it is not, is no indifferent matter,
but hath been, and is of pernicious consequence to the Christian religion,
the people being taught to believe they have Christian baptism, when in truth,
they have none at all; and therefore sit down short and secure in a false rest,
and seek no further for the true baptism of Christ; which is only by the Holy Spirit,
and without the knowledge whereof no soul can be saved.`"
And so we concluded.

I exhorted them all not to be averse or ashamed to reform, though late,
from those things wherein they could not justly deny that they were amiss.
And finding my antagonist, Davenport, very calm,
and in a better mind than in the beginning, I took him by the hand,
and bid him beware for the future how he boasted beforehand over strangers,
for he had greatly vaunted, and insulted us before the people when we began this contest,
and how he would prove us heretics;
and I advised him not to boast till he had put off his armor, adding,
that I now found a better part in him, and was glad it was so.
The invisible power of the everlasting truth of God being over all,
we took them kindly by the hand, and they us, with mutual good wishes on both sides;
and so we parted with them in friendship, and in great peace in the Lord,
to whom be the honor now and forever.

As we went along the street from the house, there came aside of us a justice of peace;
who, smiling, said, "`Gentlemen,
you have had a whole body of divinity to encounter today.`"
I answered, "`That if we had met with more humanity,
it would have been more satisfactory to us.`"
And walking a little further, another justice on horseback overtook us; who,
saluting us with respect, said, he understood we were going his way,
and if we pleased to stay a little at our inn he would call upon us;
to which we assented.
At our inn we found some of the people, to whom we further improved the text, Isa.
Iv. I, 2, 3, to the advantage of Truth.

The justice came, and we went together several miles,
and had much discourse about points wherein they and we differ, viz: baptism, the supper,
the Word of God, etc., concerning the two first I took some pains with him;
but being under great prepossessions and prejudices,
and long accustomed to a carnal way of thinking on spiritual subjects,
he could not readily apprehend the force of my arguments;
though he was willing to be informed.
As to the latter, we acknowledged that the Holy Scriptures,
being given by divine inspiration, are of divine authority; yet not the prime,
but secondary rule, nor properly the Word of God.
In which my companion satisfied him after this manner:

"`'`In the beginning was the Word;`' but the Scriptures were not in the beginning:
'`and the Word was with God, and the Word was God;`' but the Scriptures are not God:
'`and the Word was made flesh;`' but the Scriptures were never made flesh.`"
And this he could see, and was satisfied.

He invited us to his house; and at our first entrance, his wife was shy of our company,
not being at all acquainted with our unmodish behavior;
but observing the respect of her husband towards us, she likewise altered her conduct,
became more social, and asked some questions about baptism, the light of Christ in man,
and that wild and foolish sect aptly called Ranters;
a meeting of them being at that time remaining in Long island; and some of them had,
from time to time, gone into Connecticut, under the name of Friends,
and by their wild and unaccountable behavior, had scandalized the Truth,
and brought reproach upon Friends; the people in that colony, till we went that way,
generally thinking all Friends were the same with those Ranters,
though they had a law of an old date, distinguishing them.

As to the light of Christ being in all men, I advanced several Scriptures, proving,
that God is light, and Christ is likewise light, the Word and manifester of the Father;
the same light that is the Word, is God manifested in the flesh,
and the true light that enlightens every man that cometh into the world;
with which she was satisfied.

As to baptism, I observed to her,
"`That when John the Baptist baptized the people with water,
he told them of another baptizer and baptism, more excellent than himself and his,
and that was Christ, whose baptism is not with water, but the Holy Spirit;
and that is the one only true baptism, by which men are inwardly washed,
purified and initiated into one body, and one mind; the church of Christ,
which is his body, the fulness of him who filleth all in all.`"
And informing her that sprinkling of infants is no baptism at all,
she was satisfied in this likewise.

Of the Ranters, I observed, "`That they held absurd and blasphemous opinions;
and frequently came into our meetings, and rant, sing, and dance, and act like madmen,
throwing dust in the faces of our ministers when preaching.
Though they are called Quakers, and have meetings of their own as we have,
yet they have no discipline or order among them, but deny all that as carnal and formal,
leaving every one to do as he pleases, without any reproof, restraint,
or account to the society in any thing, how inconsistent soever with civility, morality,
and religion; and are in mere anarchy.
And therefore we bear witness against them in word, writing, and practice;
we being settled under the most concise, regular,
and reasonable constitution of discipline that ever was established in the world.`"

This gave the justice and his wife full satisfaction as
to the great difference between the ranters and us,
as quite opposites in principle and practice;
though the world includes us both under one denomination.

We stayed as long as the time would allow,
having several miles to go to the inn to which we intended that night,
and departed in peace, and left them in love and respect to us.
