== Chapter VIII

Having a very great love and respect for the proprietor,
and his regard likewise so to me,
and not under any engagement in myself to return immediately to England,
and seeing I might probably be of some service in America,
I consented to remain so long as I might see it my place.

Being unengaged in any business, and a proper subsistence necessary,
the governor appointed me a member of the council of State and keeper of the Great Seal,
Master of the Rolls for recording patents, and for the enrolling of deeds,
and one of his commissioners of property, for inquiring into and confirming old rights,
and granting lands upon new purchases; with proviso in my patent for those offices,
to have deputies therein respectively,
when and so often as my calling in the truth and service thereof, might require it.
Under these circumstances I settled there for a time,
and fell also into much business in conveyancing, to which I had been inured in England.
Before the proprietor returned to England,
which was in about two years after his arrival in the country,
he granted a charter to the inhabitants of Philadelphia,
and thereby erected the town into a city, and appointed me the first Recorder;
but being averse to that station,
I resigned it as soon as the Corporation was
regularly settled and habituated to business.

These offices not obliging me to any close confinement to the various business of them,
I visited the meetings from time to time, in town and country, and also in the Jerseys,
as opportunities offered and need required.
On the 15th of the fifth month, 1702, I went from Philadelphia in order for Long Island,
and that night lodged at Burlington;
next day had a good meeting with a few Friends there, and on the 17th got to Shrewsbury.

On first-day had a large meeting at their meeting-house,
and the next morning set forward for Amboy, and lodged there at an inn,
and the next day went over the sound into Staten Island,
and through it to the next ferry.
We sailed up the entrance of the sound at Elizabeth-
town Point to gain the wind more fairly,
and while crossing over to Long Island there came on a very thick fog,
so that we lost sight of the shore on both sides, and had but a small breeze of wind;
but I encouraged the boatman, believing we should be safe;
and soon after there appeared an open sky, so that we saw both shores;
and though the wind had shifted whilst the fog was over us,
we were standing right for our intended landing place, and we got safely over,
but after night.
We landed near a small house of a poor man who had only one bed,
and he laid me down a coat on the floor, so that I lodged but very indifferently.
However, I was very well contented, the presence and goodness of the Lord being with me.
I got good water to drink, but little victuals; and in the morning set forward,
and missed my way several times,
they being generally Dutch people in that part of the island,
whose directions I could not well understand.
About mid-day I got well to Newtown, where I dined, and rested some hours,
and in the evening went to Thomas Stevenson`'s, where I lodged more comfortably.

The next morning we went by water to a meeting at Flushing;
and next day had another good meeting at Westchester on the Main.

The 26th, being the first-day of the week, we had a large meeting near Newtown,
where it is kept once a year; and on the 28th had a good meeting at Hempstead,
where I staid that night; next day a meeting at Jericho,
and that evening returned to Flushing, and was at their week-day meeting,
which was hard and shut up at first, but ended comfortably;
and on the 31st I visited several families,
and returned in the evening to Samuel Bowne`'s, where next day I wrote letters.

On the 2nd of the sixth month, being the first of the week,
I had a large meeting at Westchester upon the Main; from whence,
being accompanied by several Friends,
I set forward on second-day morning towards Fairfield, in order for a meeting there,
if a place could be had to meet in.
That night we arrived at Stanford, and endeavored for a meeting,
but could not obtain a place:
for though several of my company had relations there who would entertain them,
and be very kind in other respects, yet they durst not admit a meeting in their houses;
so miserably are they in bondage to their ministers.

The next day we went to Fairfield,
and that afternoon took considerable pains for a place to meet in, but in vain.
At length we agreed with our landlord for a large room for two days`' time,
to make what use of it we pleased.
He knew our design, yet he was willing to wink at it,
though he was brother-in-law to the town preacher.

The next morning calling for a reckoning, we paid our landlord for the room beforehand,
and that day went to Stratford, about eight miles further; where,
sending for William Bickley to the inn, he came readily to us,
and willingly let us have his house for a meeting place, and went himself,
and also sent his servant, about the town and invited the people; many of whom,
though busy about their harvest till near night, came to the meeting.

We sat in silence a pretty while;
and some of them who did not understand there could be
any worship performed to God in that condition,
went out again; but a little after finding some things begin to open upon my mind,
I stood up and began to speak;
and as soon as they heard my voice they came in
so fast that they quickly filled the place,
and were very quiet and orderly.
The meeting was very comfortable, the goodness of the Lord being with us;
and several necessary truths of the gospel were delivered among them,
and no offense taken at all, from anything that appeared.

The meeting being ended, I stood up again and signified to them,
"`That seeing I had no outward knowledge or acquaintance of any of them,
the love of God to their souls was the only motive I had to visit them;
and if any thing had been delivered which they did not understand,
or if they had anything to object in soberness, and not for contention,
I would do my best to satisfy them; but if they did not then,
while things were fresh in memory, but after I was gone, it would not be kind,
if just;`" but none answered a word.
They not being hasty to go away, I exhorted them,
if ever they came to any of our meetings again,
to stay with patience until the time of our speaking should come,
and to come to meetings as near the time appointed as they could;
since it is a disadvantage to one that is speaking, and to a meeting already settled,
to have fresh people coming in; who thereby incommode others,
and cannot readily perceive whereabout the preacher is in the matter he is handling,
or have the benefit of the whole, as those who come in proper time;
and that they would do well,
not presently after the meeting to run into much talk among themselves,
but weigh the matters in their minds, and compare them with the Scriptures.
And then desiring that the love of God might be with them, and preserve them,
many of them made a respectful bow, and so departed in silence and in peace.

We returned to Fairfield, where the report was arrived before us,
of the satisfaction of the people of Stratford with the meeting there;
which raised a general talk and desire in them of Fairfield of
coming to the meeting appointed that evening;
and their minister and Justice Gould said they would come also.
But they concealed their end therein, which was not for good, but evil;
for towards the evening,
when they and their accomplices saw that the
people were in earnest to come to the meeting,
they held a consultation how to disappoint both us and them;
and sent for our landlord and reprehended him for letting us the room.
He excused himself, alleging, that as he kept a house of entertainment,
and we were strangers, and so many of us as might well occupy that room,
and might desire to be by ourselves, as a quiet religious people,
differing from others in our manners and behavior, he let us have the room,
not at all questioning us what we intended to do with it.
But yet they so far discouraged him, that if we had not paid him beforehand,
we could not have had a meeting, by all appearance; for when he saw us making seats,
and other preparations for the meeting, he came to discourage us, saying,
"`Why should you trouble yourselves about such a thing,
since none dare come to hear you for fear of the minister, and others in authority?`"
But of this we took little notice.

None of the people came till near sun-set, and then but few in the room,
but many about the doors and in the court; and things beginning to open in my mind,
I waited for the fuller gathering of them, till they who were there began to be uneasy,
so that some of them went out: but standing up, and my voice being heard, many came in,
and the room was quickly full, and some hundreds about the doors and windows;
and their minister and the justice and constables among them: and things opening clear,
and my voice raised more than ordinary, I had a good time among them;
though I found there was war in the spirit of the
priest and his company against us and the truth.

The words which I began with were these: "`For the word of God is quick and powerful,
and sharper than any two-edged sword,
piercing even to the dividing asunder of soul and spirit, and of the joints and marrow;
and is a discerner of the thoughts and intents of the heart:
neither is there any creature that is not manifest in his sight;
but all things are naked,
and open unto the eyes of Him with whom we have to do:`" that this Word is Christ,
in his divine and spiritual appearance in the hearts of mankind;
of whom the evangelist bears testimony, that "`He was in the beginning with God,
and was God: that all things were made by him: that in him was life,
and the life was the light of men: that he is the true light,
which enlightens every man that cometh into the world: that he was in the world,
and the world was made by him, and the world knew him not:
and that this divine Word was made flesh (or assumed the proper nature of man,
a reasonable soul and human body) and dwelt among them, full of grace and truth:
and of his fulness have all we received, and grace for grace.`"
This is the only begotten Son of God, to whom all mankind are directed by the Father,
according to the prophet of old, where he saith, "`Behold my servant whom I uphold,
mine elect, in whom my soul delighteth: I have put my spirit upon him;
he shall bring forth judgment to the Gentiles.
Thus saith God the Lord, he that created the heavens, and stretched them out;
he that spread forth the earth, and that which cometh out of it;
he that giveth breath to the people upon it, and spirit to them that walk therein;
I the Lord have called thee in righteousness, and will hold thine hand,
and will keep thee, and give thee for a covenant of the people,
for a light of the Gentiles.`"
This is He, the same who was crucified in the flesh at Jerusalem,
according to the testimony of Holy Writ,
and as a propitiation for the sins of the whole world.
This is he, who being thus promised a light to the Gentiles,
and all directed unto him as such, as to the saving object of their faith,
and covenant of light and life with the Father, all must believe in him,
obey and follow him in the way of regeneration,
or else they cannot have salvation by him: as it is also written,
"`By grace ye are saved, through faith; and that not of yourselves,
it is the gift of God.`"
"`Not by works of righteousness which we have done,
but according to his mercy he saved us,
by the washing of regeneration and the renewing of the Holy Ghost;
which he shed on us abundantly, through Jesus Christ our Savior.`"
And this is the present dispensation of God unto us,
now scornfully and contemptuously called Quakers;
to whom this great salvation is come in our day, as well as to them in that day,
clear from all shadows, types, and figures;
without any representations or commemorations of Christ, as if absent,
but as sensibly present, as the divine light, love, and life from God the Father.

These were some heads of what I had to say among them;
and the rest was after this manner: that no name of distinction or contempt among men,
of their own inventing, through ignorance or envy,
would stand any of us in stead at the last day; nothing would do then but the name,
virtue, and power of the Lord of life, the Lord Jesus Christ, the quickening Spirit,
and to have life eternal by him:
that we shall not be asked in that day whether we had been named, or called Papists,
Episcopalians, Presbyterians, Independents, Baptists, Quakers,
or by any other name of that kind; but, What have been thy thoughts, words,
and deeds in life?
How hast thou lived?
Hast thou done unto all men as thou wouldst they should have done unto thee?
And the Son of God hath already told us, that "`A good man,
out of the good treasure of the heart, bringeth forth good things; and an evil man,
out of the evil treasure, bringeth forth evil things.
But I say unto you, that every idle word that men shall speak,
they shall give account thereof in the day of judgment:
for by thy words thou shall be justified, and by thy words thou shalt be condemned.`"
And all at last must be judged according to their works.
Let us therefore take the advice of the apostle, where he saith,
"`Let no corrupt communication proceed out of your mouth,
but that which is good to the use of edifying,
that it may minister grace unto the hearers;`" and do likewise
that which is good in the sight of God and good men.

The minister staid until he heard what subject I was upon, and had gone on some time,
and then retired, saying, "`He heard nothing that was hurtful.`"
Things going on well, and the people generally being very still and attentive,
in came the justice at one door, and two constables with a warrant, at the other.
The justice commanded the people to disperse,
asking them if they did not understand that the law was against such meetings;
and that they might be fined every man ten shillings, and the house five pounds;
and then he began to lake down some names, pretending to fine them.
Some of them were weak and cowardly, and retired, and some hid their faces;
but others were offended with their magistrates, saying,
"`If they were fined on that account, they would stand one by another,
and oppose any who should pretend to levy it.`"
Others cried out, "`We have not liberty of conscience.`"
The tumult increasing, and the people no longer in a condition of hearing to profit,
and the truth withdrawing as to that exercise, I was silent.

Then some of those opposers accused me of making a tumult; I replied,
it was themselves that had done it, contrary to the laws of England,
and the nature and end of the Christian religion; for I and the people were quiet,
as likewise my friends, until they disturbed us in our hired house,
where we were publicly and peaceably met in a Christian exercise,
in which we ought not to have been disturbed.
But if any of them had any thing to object against what was delivered in the meeting,
they should have been silent until it had been ended, and I would, by the grace of God,
have given them an answer, and reasonable and Christian satisfaction.

Then one of the constables took out a warrant, signed by justice Gould, purporting,
"`That whereas it is supposed one under the name of a Quaker is at such a house,
preaching, or pretending to preach; if any such be found there,
he is ordered to be apprehended, and taken to the constable of Norwalk,
about eight miles off, and from thence to be conducted from constable to constable,
out of the government.`"

Upon this I stood up upon a form, and told them openly,
I was the man who had said all that was said, by way of preaching, in that meeting;
and that I was ready to obey the warrant, if they thought proper to execute it,
for we are subject to government; only I desired a copy of it.
The constable refused to give me a copy, and said he did not believe that I was the man.
Then some of the people told him I was.
Then said the constable, "`I`'ll believe none of you;
nor do I see any body here that our law takes hold of;
these are not such Quakers as our law is against.`"
Then the other constable would have had the warrant, pretending he would execute it,
but the first would not give it him.
Then we perceived they did all this to hinder our meeting,
lest the people should receive the Truth;
and in reality they had no law to justify their proceedings.
I exhorted the people not to be cowardly, nor remain slaves to their minister,
who was of their own making, and I suspected he might be at the bottom of all this.
Then I and my companion went out into the street among the people,
the justice being slunk away in the dark.
They were very numerous, and I spoke what was further on my mind among them,
and found them generally dissatisfied with their magistrates for that disturbance.

Many of those people at that town of Fairfield,
ever since I had that dispute with the seven ministers there,
speak of the dispute in our favor, and against their ministers,
and their oppressions in taking away their arms and weapons of war; by which, they say,
they should defend themselves, families, and country, from enemies,
and also their very wearing apparel, for their maintenance.
But yet, when those people are tried, they are all so much overawed by their ministers,
that they dare do nothing to displease them,
not so much as to permit a meeting to be in their houses,
though in themselves they incline to it.

Next morning there came to us several of the people,
and again expressed their dissatisfaction with
the conduct of their magistrates in that action;
and after some further discourse with them, having refreshed ourselves,
we took horse for our journey, and called at justice Gould`'s door,
with intent to have reasoned the case with him
about his unchristian and illegal behavior to us,
both as strangers and subjects of the crown of England, but we could not see him.
And so, having set holy fire and sword from the Lord in the bowels of the town,
we left it; may it never cease,
till the Prince of peace be known to reconcile them unto himself and the Father,
and to govern in them: to him be dominion and praise, to whom alone it is due,
for ever and ever.

The same day, after some fruitless endeavors to obtain a meeting at Stanford,
we came back about forty miles, to Samuel Palmer`'s, where we lodged that night,
and on the 8th reached Long island; and the day following, being the first of the week,
was at the meeting at Flushing, which was not very open.
Having appointed a meeting at Oyster Bay on the 11th, John Richardson, from Yorkshire,
and James Bates, from Virginia, coming the day before from Rhode Island,
came to me at my lodging, and we went together to the meeting, which was small,
but comfortable, the good presence of the Lord being with us.

On the 12th we were at the week-day`'s meeting at Jericho, which was pretty large,
and an open good meeting the Lord gave us together in his presence.
That evening we went all to Flushing, and were at their meeting next day;
and on the 14th we had a large good meeting at Jamaica,
and a court for civil affairs being at the same place that day,
several lawyers and other company came to us, all very sober and attentive.

On the 16th we went to Great-Neck, in that island, to the house of William Mott,
a young man lately convinced by the ministry of Thomas Thompson,
where we had a large meeting, there being many of other people with us,
and all very sedate, and the truths of the gospel of Christ well opened.

On the 17th we went to Newtown, and next day had a meeting there,
which was very open and well.

On the l9th we went to New York, and had a small, dark, heavy meeting there;
and next morning crossed over Hudson`'s river to Staten Island,
and on the:21st had a meeting there, where none had been before.
The meeting was well, and the people very quiet; but after it was over,
there stood up one Captain Manning,
and objected to something John Richardson had said against water baptism,
and it fell to my lot to answer him; which having done,
so as to leave two Scriptures upon him unanswered, viz: "`For as the body is one,
and hath many members, and all the members of that one body, being many, are one body;
so also is Christ: for by one Spirit are we all baptized into one body,
whether we be Jews or Gentiles, whether we be bond or free;
and have all been made to drink into one Spirit.`"
And where Peter, speaking of the saving of Noah and his family by water,
or rather by the ark from water,
and the destruction made upon the rest of the world by it, saith,
"`The antitype of which figure, even baptism, doth also now save us,
(not the putting away the filth of the flesh,
but the answer of a good conscience towards God,) by the resurrection of Jesus Christ.`"

I demanded their authority for sprinkling infants: '`this pinched him so closely,
that he grew very angry, alleging that I laughed at him; which I never did, either then,
or on any other like serious occasion.
I told him it was only an old Popish remain,
set up by them under a false notion of an ordinance of Christ.
His anger then increasing into rage, he went away, and I went along by him,
confirming what I had said.
At length, getting out from among the people, he alleged that Scripture for sprinkling,
where Christ saith, "`Suffer little children to come unto me,`" etc., which I rejected,
as no way applicable to the case, there being nothing,
either expressed or implied in that text, either for sprinkling or baptizing.
Upon this he went into the house, and soon after his spirit fell,
and he became very calm,
and then began to tell what kindnesses he had formerly done to Friends at Salem,
in New England; and his wife, having been pretty tender in the meeting,
made an apology tor her husband`'s passion, and so all ended in love and friendship.

That evening we returned to New York, and remained there the next day,
and though thi re was a pestilential fever raging in the town,
so that seventeen persons lay dead there that day,
yet notice was given of the meeting to be on the 23rd, being the first of the week,
and was held accordingly; and though very thin,
it was the best and most comfortable I was ever at in that hard and dark place;
for the minds of the people were humbled with fear of the sickness,
and by so many instances of mortality, and so near,
by which they were more susceptible of Truth.

On the 24th visited a Friend that was sick, and then took boat for Flushing,
and on the 26th we had a meeting at West-Chesler, over the Sound.
On the 27th were at their weekday meeting at Flushing,
and that evening went home with John Rodman, where we staid till the 29th, and then,
accompanied by many Friends, we went to Westbury, to a quarterly meeting,
where we had good service; and the business of the meeting being all finished that day,
the next, being the first of the week, the Lord, in the riches of his goodness,
gave us a glorious meeting in his presence,
in a new meeting-house fitted up on that occasion; and many hundreds of Friends,
and abundance of other people were there, and generally satisfied.
Many things of importance in religion being clearly
opened by the wisdom and power of Truth that day,
to the praise of the holy name of the living Lord, who alone is worthy forever.

On the 1st of seventh month we were at the marriage of William Haige and Mary Masters,
at Flushing; on which occasion we were favored of the Lord with his good presence,
and an open, satisfactory meeting.

In the morning we went to the Narrows, and with difficulty,
procured a small boat that could carry one horse only at a time,
which made our passage very tedious as well as dangerous;
and my horse never having been in a boat before, leaped overboard,
and turned upon the boat with his feet, and might have overset or staved it;
but being just putting off from the shore, we returned to land, and taking down the sail,
quieted him, so that he kept in the boat the second time, but with much difficulty,
till we got over.

Being got well over, none of us knew the way to the Point,
nor could we have any guide but a maid we met
with on the side of the Sound where we landed.
One of our company took her on behind him,
and we got well along till we came to Captain Manning`'s,
where both he and his wife were very kind (o us.
We went forward, about a mile, to a Dutchman`'s house, who sent his two sons,
one with a canoe and some of the company and things, and the other with the rest of us,
through a boggy marsh to a point of land,
from which we swam our horses by the sides of the canoe.
This being about sunset, we had the other Friends`' horses, left there before,
to take up and pay for; which done, we went that night to Woodbridge.

On the 3rd we set forward for Shrewsbury, about five in the afternoon,
and next day had a meeting there, and the day following went to Crosswicks.
On the 6th, being the first of the week, had a very good meeting there,
and that evening went to Burlington, and on the 7th to Philadelphia.

Having further ordered my affairs at Philadelphia, visited some meetings in the country,
and attended the service of the yearly meeting, I went from thence to Burlington,
and back to the yearly meeting at Shrewsbury, in East Jersey,
to which came a message in writing, from that miserable apostate, George Keith,
who had applied to a bishop of the national church,
that he miglit be made a priest among them.
They thinking he might be of use to some purposes of theirs,
put him into their deacons`' orders,
not being willing to trust one so unstable with further orders,
till they had better proof of him.
And as a deacon in their way may preach, but not administer their sacraments,
they sent with him one John Talbot, a high church priest, of low consequence, to baptize,
as they miscall sprinkling,
and give bread and wine to such as George Keith should pervert.
They began in New England, and came along the coast in that work, (but to little purpose,
for they made but very few converts in all their journey,) to Shrewsbury,
at the time of our yearly meeting, to make disturbance, and as much as they could,
hinder the service of our meeting.
On the first day of it, being the 24th of the eighth month,
George Keith sent the priest with a paper, purporting:

[.numbered]
1st, an advertisement, that he purposed to have a meeting at the house of one in town,
to begin about the eleventh hour the next day, being in the middle of our meeting,
then and there to detect, out of the books of our approved authors, divers vile errors,
contrary to the Christian faith, and fimdamental principles of the Christian religion.

[.numbered]
2+++.+++ "`As also to be ready to vindicate the truth of any or all the
quotations out of the printed books of our approved authors,
contained in his several printed narratives.

[.numbered]
3+++.+++ "`To answer any objection we shall make against him;
in order to which he desired us to be then and there present.

[.numbered]
4+++.+++ "`That if we were not willing to meet him at the said time and place,
he would meet us at any time and place we should appoint him at Shrewsbury,
on timely advertisement, betwixt the 26th and 29th of that instant;

[.numbered]
5+++.+++ "`With a postscript, signifying, that if we did not come,
he would judge we acknowledged the quotations to be true,
and a demonstration to all intelligent persons that he had not wronged us in them;
but that our principal friends, with whom we joined,
have and do hold most gross and damnable errors, to the great hurt of our souls,
and scandal of the Christian religion.`"

This being directed to two of our ministers in particular, and to the rest in general,
I asked his messenger, Talbot,
whether George Keith sent this challenge as one
formerly cast off and rejected by us as a people,
for his misdemeanors, or as a minister of the church of England?
Which question being put into writing, and signed by me and two other ministers,
and sent to George Keith, he returned a long and ill-natured answer,
the substance whereof was thus, viz:

[.embedded-content-document.letter]
--

I positively answer, I sent you my challenge,
both as a person cast off and rejected by you most unjustly, for what ye call falsely,
as well as illegally, my misdemeanors,
and also as a minister of the church of England.

--

[.offset]
To this we replied thus:

[.embedded-content-document.letter]
--

George Keith,
we have received thy peevish and scoffing answer +++[+++for so it was]
to our questions.
And since thou givest thy advertisement and challenge,
both as a person cast off and rejected by us,
and also as a minister of the church of England, we let thee know,
that the latter alters not the case of the former with us: and therefore,
as an heathen man and a publican, we continue to reject thee,
despising all thy works of envy and revenge, to the blame of all which,
and the consequences thereof,
as well as of thy manifold disturbances of our meetings in America,
thou hast also entitled that ministry as partakers,
till they publicly disown thee therein.
But as thou hast begun in print, we shall, as hitherto, answer thee that way,
which we think is best for general information, and least liable to misunderstandings,
misrepresentations, and exceptions.

--

This implacable and restless adversary continued in his work of envy and falsehood there,
and afterwards at Burlington, and Philadelphia,
but we took no further notice of him in that way; but our friend Caleb Pusey,
who formerly answered him effectually out of his own books,
making George Keith the Quaker answer George Keith the apostate,
so that he could never make any reasonable reply, answered him in print soon after;
and all sorts of people becoming weary of him and his work, and slighting him,
he became as the salt which had lost its savor,
and returning by way of Virginia for England, he became a parish priest,
and died very poor and miserable.

After the meeting at Shrewsbury I returned to Philadelphia, and remained in my business,
and attended the meetings in Pennsylvania and West Jersey,
as I found concern and ability, until the 29th day of the twelfth month, 1703-4,
and then began a journey from Philadelphia for New England in the service of Truth.
Next day was at the nine weeks meeting at Burlington,
and the day after at a monthly meeting at Crosswicks;
and on the 3rd day went to Amboy ferry, where I was wind-bound two nights and one day,
and on the 5th day morning got over the river Raritan to Amboy, and thence to Woodbridge,
where, being the first of the week, we were favored with a good meeting.

The next morning I went to Elizabeth-town, where I hired a boat for York,
and got well thither that afternoon, and on the 8th had a small meeting.
That evening went into Long Island, and next day was at the meeting at Flushing,
and on the 12th, being the first of the week, I went over the plains to Westbury,
where the Friends of several meetings were together,
and there we had a large and open meeting.

This year our friend Samuel Bownas, a young man,
being come over from England to visit Friends in America,
in his testimony in that island had spoken against the error of sprinkling infants,
and something against the bread and wine of the priests, which they call sacraments;
of which the Lord Cornbury, being then governor of New York and Long Island,
having been informed,
he had arbitrarily put Samuel Bownas in prison at a place called Jamaica in that island,
where he was unjustly confined, without any law, about twelve months;
and at this place I had a meeting appointed and held on the 14th of this month,
which was large, very open and well.

On the 16th I was at Flushing week-day meeting, to which came some strangers.
The meeting was very open and bright,
and many truths of the gospel were declared in the authority of it,
to their satisfaction.
Next day had a meeting near Newtown, to which came several Presbyterians,
their ministers being arbitrarily silenced by the Lord Cornbury, and gone out of the way,
or absconded; and things were largely opened concerning the passover,
and bread and wine as being a part of it, etc.

After the meeting, as we rode along,
one of the justices of the peace that committed
Samuel Bownas to prison by the governor`'s order,
viz: Jonathan Whitehead, fell into conversation with me;
upon which I told him I had observed he had been at
most of the meetings where I had been in the island,
and asked him if he had any thing to object.
To which he answered, that he had not any thing, but was well satisfied,
and also expressed a considerable dissatisfaction in himself,
that he had signed the mittimus against Samuel Bownas.
He was loving and respectful, and under some more than ordinary concern of mind,
and went out of his way to accompany us along the road toward Flushing,
to which place we returned that evening.

On the 19th, being the first of the week, was at their meeting, which was large,
many people being there from several parts of the island where I had been before.
The blessed Truth was over all,
and many things were opened in the authority and dominion of it,
to the praise of the Lord, and general satisfaction of Friends and people.

The next day I visited Samuel Bownas in prison, and that evening returned to Flushing,
and next day had a meeting at West-Chester, which was more open than usual in that place;
after which I was very easy, and inwardly comforted in the divine Truth.

On the 22nd I set forward for Rhode Island, and that night lodged at Northwalk,
whore we had much discourse with our landlord and two strangers,
all of the Presbyterian or Independent way--who are often well
furnished with tongue and lip religion--about the principles of Truth,
and things were opened well and clear, so that all their objections were answered.

The next day we went on to Fairfield, and called at William Bickley`'s at Stratford,
where I had some discourse with one who began about bread and wine.
From thence we went forward to New Haven, and lodged at an inn.

In the morning we set forward and baited at Guilford,
where I had some discourse with three strangers about predestination,
and some other points.
One of them managed the discourse on their part, and the rest were silent;
and at length he was silenced, and soon after retired out of the room.
They were not bitter, but rather inquisitive,
and things opening clearly in a sense of divine grace, I hope they were profited;
we parted with them in a friendly manner.
We went forward to Killingsworth, where I once had a dispute with a Presbyterian teacher,
one Pearson, and I think, regent of a college there, and yet living.
The landlord quickly remembered me,
and began to speak of that dispute in the audience of several strangers;
which gave me an opportunity to reprove him for misrepresenting it to
several Friends who had travelled that way,
as well as to some others, which put him much to the blush.
I repeated, in his and their audience, the state of the question,
and also the regent`'s arguments and ours.
Neither our landlord, who heard the dispute, nor any of the company,
offered to gainsay or undertake to answer those Scriptures cited by me to
prove the possibility of a sinless perfection on this side the grave,
which was the subject the regent and I had been upon before.
The Scriptures are these, viz: "`If we walk in the light, as he is in the light,
we have fellowship one with another,
and the blood of Jesus Christ his Son cleanseth us from all sin.`"
"`If we say that we have no sin, +++[+++or have not sinned]
we deceive ourselves, and the Truth is not in us.
If we confess our sins,
he is faithful and just to forgive us our sins
and to cleanse us from all unrighteousness.`"
Again, "`For this purpose the Son of God was manifested,
that he might destroy the works of the devil.`"
"`Whosoever is born of God, doth not commit sin: for his seed remaineth in him,
and he cannot sin, because he is born of God.`"

Then a man broke in with his notions about predestination, affirming, that God,
from eternity, hath pre-ordained some men personally to destruction;
and that the number is so certain and definite, that not one can be added or diminished;
and that Christ did not die for them, but for the elect only.
To which I answered, That Christ himself is the elect Seed, and is the propitiation,
not for himself, for he had no sin, but for the sins of the whole world.
This he denied.
Then I told him he denied the testimony of the apostle John in that point,
where he saith, "`He is the propitiation for our sins; and not for ours only,
but also for the sins of the whole world.
For all have sinned and fallen short of the glory of God.`"
And if there had been such a decree, or personal fore-ordination,
it must be the will and desire of God that it should be so.
And seeing Christ suffered as a propitiation for the sins of the whole world,
he suffered for those who were determined to destruction, if such there had been,
as well as for those ordained unto life; but to no purpose as to the former,
and God doth nothing in vain.
But that God doth not will or desire the eternal death of any,
appears under the highest credentials, where the Lord saith,
"`Have I any pleasure at all that the wicked should die, saith the Lord God?
and not that he should return from his ways and Kve.
Say unto them.
As I live, saith the Lord God, I have no pleasure in the death of the wicked,
but that the wicked turn from his way and live: turn ye, turn ye from your evil ways;
for why will ye die, O house of Israel?
When the righteous turneth from his righteousness, and committeth iniquity,
he shall even die thereby.
But if the wicked turn from his wickedness, and do that which is lawful and right,
he shall live thereby.`"
Here, and in many other places in that prophecy,
the Lord places the destruction of man upon his own will,
and not upon any act or decree of God; where he likewise saith, "`O Israel,
thou hast destroyed thyself, but in me is thy help.`"
And again, it is testified by an apostle of Christ,
that "`God our Savior will have all men to be saved,
and come unto the knowledge of the truth;`" and
that "`Jesus gave himself a ransom for all,
to be testified in due time.`"
Therefore I believe God, and deny that predestination, as false doctrine,
assert it who will; as it is also written, "`Let God be true,
and every man be a liar,`" in this doctrine,
as in all other things wherein bold and ignorant men do contradict him.

Upon this the man was so enraged, that he abused us much with reproachful language,
without rebuke from the rest; which gave me occasion to reprove them all; him,
for his irreligious abuse, and them, being his superiors,
for suffering it in their presence, without expressing any dislike,
and so placed it upon them all; and yet some among them were more friendly.
We departed in peace, with an elderly sober man in company,
with whom I had some friendly discourse upon the subject of baptism,
in which he made no opposition: but confessed he had not heard such things before,
and said he would consider them further, and we parted in friendship.

That evening we passed over Connecticut river,
and lodged at an inn kept by an Independent, a sober man;
where some young people were singing, fiddling and dancing, when we went to the door,
but as soon as they saw us, they desisted, and departed,
which gave occasion for some discourse concerning the state of
that people when they first came into that country,
and the degeneracy of this generation,
which he very readily confessed was their unhappy state.

On the 25th of the first month, 1704, we set forward, and that night lodged at incton.
In the evening our landlord began some discourse about their sacraments,
asking our reasons tor the disuse of them; upon which I gave him several, viz:
"`The bread and cup being incidents of the Jewish passover,
and typical of Christ himself, who is the antitype,
and the true living bread which comes down from heaven,
as soon as men experience him to be so in their hearts,
all obligations cease as to our continuance any longer in the figure, as it is written,
'`As often as ye eat this bread and drink this cup,
ye show the Lord`'s death till he come.`'

"`Now the question arises.
What is meant by his coming?
We understand it of his second, inward, or spiritual coming, without sin unto salvation,
in all them who believe and wait for him in all ages: and this we,
through the goodness and mercy of God, do experience to be true,
that he is come in that blessed and saving manner in us,
and therefore the obligation of the use of the bread and cup,
in the sense in which ye now use it, being at an end to us, we disuse it.
Moreover, as it was the Jews`' passover, never incumbent on us the Gentiles,
and fulfilled by Christ, it is not obligatory upon us.
And besides, as the apostle saith, '`As often as ye eat this bread, and drink this cup,
ye do show the Lord`'s death till he come.`'
Seeing then all those who continue in these shadows are
only showing forth his death until he come,
they bear witness against themselves, that they are yet dead unto him,
and that he is not yet so come unto them; and being ignorant of his life,
they are not risen with him, but are yet in their sins, and in a state of death.

"`As it was the last passover, and fulfilled by him, when he gave them the cup, he said,
'`Take this and divide it among yourselves;`' but did not command them to give it,
or the bread, to others.
And further, as the apostle Paul was a true minister of Christ, to all necessary intents,
not one whit behind the chief of the apostles,
and yet was not sent by Christ to baptize with water, but to preach the gospel;
so likewise, though we, in our day, have a dispensation of the same gospel,
in some decree, committed unto us of the Lord, to preach his inward coming,
yet we have no commandment from him to administer either such bread or cup,
or water baptism in any form, nor do we believe that any others have it at this day;
and therefore we justly and reasonably decline either to administer or receive them.`"

In some further discourse I had occasion to speak of their ministers,
and how they were made and sent by one another, and not by Christ;
and though called by the people, not always by their inclinations,
but by the management of those ministers and their aiders;
and that their general aim was, to live upon them; and that when they had places,
they would exchange them for better, without any regard to the people,
though they commonly deceive the weak and ignorant with
an unreasonable pretense of a mission from Christ,
by the words in Matthew, where he said unto the eleven disciples,
"`Go ye therefore and teach all nations,
baptizing them in (or rather into) the name of the Father, Son, and Holy Ghost,`" etc.
And though it doth not appear that the Lord ever commanded those men-made ministers,
yet they run, and according to the extent of the words of Christ to his apostles,
pretend a call from him to preach to all nations, and to baptize them;
though they commonly take up at the next town that will entertain them for hire,
and baptize none, but only sprinkle little children.
So that they do not answer their pretended call in any respect.

This put our landlord to a stand, and made him silent, being a sober man;
and all ended in friendship.
We found afterwards that one of those ministers had married his daughter,
and was in the company when we began to discourse, but slunk away into another room,
not caring to say a word in his or their vindication.

On the 26th we rode twenty-five miles to a meeting,
at the house of our friend Rowland Robinson, on Narragansel, which concluded well,
though heavy in the beginning; and that evening we went five miles further,
and on the 28th we went over the Sound to the monthly meeting at Newport.

I think proper to observe here,
that this being in the time when Queen Anne was at war with Louis XIV.
king of France, the government of New England was preparing to invade Canada,
and there being many Friends at that time within that government,
who could not bear arms on any account,
as being contrary to our conscience and sentiments of
the end and nature of the Christian religion,
which teacheth not to destroy, but to love our enemies;
the people of New England made a law, "`That such of the inhabitants of that government,
as being qualified or able to bear arms, and regularly summoned, should refuse,
should be fined, and refusing to pay the fine, should be imprisoned and sold,
or bound to some of the queen`'s subjects within that colony,
for so long a time as by their work they might pay their fines and charges.`"

On the 29th of this month we went to an appointed meeting at Bristol, on the main,
where two of our young men, viz: John Smith and Thomas Macomber, were prisoners,
being impressed, by virtue of this law, to fight against the French and Indians.
The meeting was in the prison, and several of the people came in,
and some of them were a little tender.
After the meeting, having exhorted the young men to faithfulness,
we went back into Rhode Island, and next day to Newport, to their week-day meeting,
where I was much comforted in the divine Truth in my own mind,
but had no public exercise.

On the 31st I rested there, and going to see Benjamin Newbury,
a man in reputation for wisdom, and his wife a Friend,
I had some discourse with him on various subjects, and more particularly about war,
a topic on which the minds of the people were much exercised at that time;
he was silent at last.
I then took him by the hand, and advised him not to be too wise for the Truth,
and so left him and went away in great peace, to a Friend`'s house in town,
where came some Friends I had left there, who told me,
that Benjamin Newbury sat silent some time after I came from his house,
and then asked some of them, how a man could be too wise for the Truth?
To which the Friend answered, "`That the wisdom of this would being foolishness with God,
and the carnal mind enmity against him, men might be so full of it,
and consulting therewith, they might disobey the Truth,
thinking the ways thereof too mean and contemptible to be embraced and followed;
and thereby neglect the time of their visitation,
being too wise in the wisdom of this world, to embrace Truth in the simplicity of it;
and yet the Truth, in itself, is wiser and stronger than all, both men and angels.`"

That evening we had a meeting at Walter Clark`'s, the deputy governor, which was large;
for, being the time of a court, many people were in town from divers places,
and some truths of the gospel opened well, and in a good degree of the authority of it,
to general satisfaction.

On the 1st of the second month I went to visit Daniel Gould,
an ancient friend of the primitive sort, beaten gold, well refined,
having been persecuted in time past by the Presbyterians and Independents of New England,
and now confined by lameness and other infirmities of age.
Some of his family were likewise ill of a distemper then infesting that island,
which to many proved mortal.
In relating some passages of Truth,
his heart was so warmed with zeal for the prosperity of it,
that we had a comfortable time therein together,
he declaring several sound truths in the life of it among us.
From hence we went to visit his son`'s widow, who was under great exercise,
by the loss of a tender husband, a young man generally esteemed in those parts;
and there I had a good time in declaring some things for her help and consolation.

The next day the meeting there was large, and many strangers present.
The subject given me was baptism, which opened largely and clearly,
with some other matters and things, and I heard of none displeased,
but several well satisfied.
On the 3rd I visited some Friends near Newport; and on the 4th, in the evening,
had another meeting in town, at Waller Clark`'s, which was large,
and many strangers there, as well in the house as at the windows.
I heard of none being dissatisfied save one man, who, being a papist,
took offense at my saying, the cross of Christ is not a cross of gold, or silver,
or other metal, or of wood or stone, to be taken up in order to follow him;
but the wisdom and power of God,
reproving and crossing the wills and lusts of mankind in their own hearts;
and the way to take it up is, to believe in it, and follow it in its manifestations.
Those invented crosses, how neat soever, and prettily contrived,
or richly adorned they may be, are of no value in religion;
for the evil one will tempt men, and prevail over them too,
though they cross themselves with their fingers ever so much,
or wear such crosses ever so many.
He did not show any uneasiness in the meeting, but told a Friend afterwards,
"`that he liked all very well except that.`"
A Friend telling me of it next day, I sent him word,
that I knew nothing of him in the meeting, nor of his cross;
and therefore desired him to consider the thing further,
and not to blame me for doing my duty, seeing it might be for his information, reproof,
and reformation, rightly received and used.

On the 10th, being the first of the week, we had a large open meeting at Newport;
the people being generally satisfied with the doctrine
and testimony of truth delivered among them,
in the authority of it; and the governor of the island having been at this meeting,
I went to visit him the next morning, and found him very respectful;
and after some conversation on various subjects, I took leave,
and then visited several Friends, the place at that time being sickly; and that evening,
had a meeting at Thomas Cornwell`'s, Jr., about five miles from Newport,
where we were favored with a sense of the good presence of the Lord.

On the 11th, I went to Bristol again,
where the two young men aforementioned were prisoners,
having been notified to appear in arms, which they, for Truth`'s sake, refusing,
were fined five pounds; for nonpayment whereof they were imprisoned in that place,
where they had remained about nine weeks.

Being in the prison with them, and many other Friends present,
we were favored with a good time in the presence and love of God together;
and the same evening we had a large and good meeting in town.
Truth was over all, and the people generally satisfied.
I heard of no objection to what was delivered, but from the man of the house,
about baptism, some few things having been said on that subject;
upon which I had some discourse with him the next day,
and then he seemed pretty well satisfied; and also by a woman, who said,
"`she liked all well, both sermon and prayer,
only I did not pray for forgiveness of sins; and she had heard, she said, we never did.`"
She did not speak to me herself, but I answered the person that informed me of it,
that it might be remembered,
that I gave thanks unto God on behalf of my own community there present,
for his great mercy in sending his Son Christ for our redemption,
and for his great goodness in forgiving and passing by
many sins and transgressions in and through him;
and that it might please the Lord to preserve us in time to come,
by his grace and good spirit, that we might not trespass against him any more;
but that the rest of our lives might be pure and holy, to the honor of his great name.
For the Lord having forgiven all our sins past, for his name`'s sake,
and testified the same in us by his holy Spirit,
we ask not forgiveness any more for what he hath already pardoned,
but render unto the Lord the thanks and praises due for so great a work and mercy.

Thomas Cornwell and I went to the house of colonel Nathaniel Byfield next morning.
When we went in he was very boisterous,
reproaching Friends as a sort of people not worthy to live;
particularly those of Rhode Island and New England, who would not go out,
or pay their money to others,
to fight against a common enemy so barbarous as are the Indians;
wishing us all in the front of the battle until we had learned better;
charging us with many errors and heresies in religion;
instancing only our refusing to fight, and believing a sinless perfection in this life.

When he had a little vented his fury, being over him in the truth, I said,
"`I was sorry we should find him in that temper,
when we were come only to request a reasonable favor of him, he being judge of the court;
and that was,
to desire him to consider the case of our friends as a matter of conscience towards God,
and not of cowardice,
or of obstinacy against rulers or their laws:`" Upon which he flounced again,
with repeated charges, saying, "`that the apostle Paul, a better man than any of us,
cried out of a body of sin and death; and that when he would do good,
evil was present with him.`"

Upon this I called for his bible,
and offered to prove out of the same epistle he hinted at, "`that the apostle was,
at that time, preaching the doctrine of freedom from sin in this life;
for though he proves, in the same epistle, both Jews and Gentiles under sin,
yet he preaches freedom from sin through Christ, to both, even in this present world;
and also that war and fighting is contrary both to the doctrine of Christ,
the end of his coming, and nature of his kingdom,
and that it was upon his (this judge`'s) principles,
that the Jewish state crucified the Savior of the world.`"

Then he said, "`he could not stay, for there were a hundred men waiting for him,
and he must be going:`" Yet, soon after, growing a little calm,
he asked us if we had eaten any thing that morning?
And we confessing we had not, he called for victuals and drink,
and would have us eat with him; and said,
"`he could be content to see us another time at his house, to discourse things,
but could not then;`" yet ceased not to repeat and multiply his charges against us.
But we did not abate him any thing.

As we were sitting down to eat, he said, "`he would not offend us in using any ceremony,
meaning what they call grace before meat, knowing we did not like it.`"
I replied,
"`that though we did not rush into such exercises towards God in our own wills and time,
without due consideration and fear,
or any sense of the spirit of prayer and supplication upon us;
in which state we could not expect to be heard;
yet we never receive the mercies of God but with due
reverence and acknowledgement in our hearts unto him,
the great author and giver of them;
but that we dare not presume to pray unto the Almighty,
till we have a sense of the assistance of the Spirit of his Son, the Lord Jesus Christ,
the only Intercessor and Mediator between God and man;
since the most holy man that ever was, ought not to bow in his own name or power,
but in the name, virtue and power of Jesus.`"
And so we sat a little while in silence, and then ate and drank with him,
and he made us freely welcome.

When we had done, he walked to the town with us; and, notwithstanding his former passion,
being now much altered, he took us kindly by the hands in the street, before many people,
when we parted.

After this we went to the prison to see the young men, and acquainted them,
that we could find little ground to expect any favor;
at which they seemed altogether unconcerned,
being much resigned to the will of God at that time;
and we staid with them in the prison most of that day,
they not being called into court till the next afternoon.

The prisoners being brought into court, Thomas Cornwell and I, and many other friends,
went in with them; and though we had our hats on, the judge was so far indulgent,
as to order us seals,
but that our hats should be taken off in a civil manner by an officer.

I replied, "`we did not do that with any disrespect to him or the court,
but our hats being part of our clothing, we knew not any harm,
nor intended any affront to the court, by keeping them on.
And though religion be not in the hat, yet where it is fully in the heart,
the honor of the hat will not be demanded, or willingly given or received,
by the true disciples of him who said, "`I receive not honor from men.
But I know you, that ye have not the love of God in you.
How can ye believe, which receive honor one of another,
and seek not the honor that cometh from God only?`"

The prisoners being at the bar, the judge asked them the reason of their obstinacy,
as he called it, running again into several high charges against us as a people?
The young men modestly replied, it was not obstinacy, but duty to God,
according to their consciences and religious persuasions,
which prevailed with them to refuse to bear arms, or learn war.
But the judge would not, by any means, seem to admit there was any conscience in it,
but ignorance, and a perverse nature;
accounting it very irreligious in any who were personally able,
to refuse their help in time of war; with repeated false charges against us as a people,
saying, "`since we could pay public taxes,
which we knew were to be applied to the uses of war,
why could we not pay those which were by law required of us,
instead of our personal service.`"

I desired leave of the court to speak, which was granted, and said,
if the judge pleased to keep to the business of the court concerning the prisoners,
I would, with leave, speak to the point of law in the case;
but if he thought fit to continue to charge us
as a people with errors in matters of religion,
not properly before him, I should think it mine to answer him in the face of the court;
adding,
that I could give the court a full distinction and reason why we could pay the one tax,
and yet not the other.
Which the whole court, except the judge was desirous to hear, and he too was silent.

I began with the example of Christ himself, for the payment of a tax,
though applied by Caesar to the uses of war and other exigencies of his government,
and was going on to show a difference between a law that
directly and principally affects the person in war,
requiring personal service, and a law which only requires a general tax,
to be applied by rulers as they see cause, and affects not the person.

For though we, as a people, readily pay such taxes, impartially assessed; yet,
as the kingdom of Christ is not of this world, his servants will not fight,
though they may and ought to pay taxes, according to the example of Christ their head.

The judge interrupted me, saying, I would preach them a sermon two hours long,
if they had time to hear me.

Then Thomas Cornwell desired them to be careful what precedent they made upon this law,
since neither he, nor any of us knew what might be the effects of it,
or how soon it might be any of our cases;
and that it would be very hard upon us to be sold for servants.
He then demanded a precedent, where, at any time,
any of the queen`'s subjects ever sold others of them, for the payment of taxes,
where conscience and duty toward God, and Christ the Lord,
were the only cause of refusal?
Adding, that he could never pay any of those taxes,
though he should be sold for the payment of them.

Truth came gradually over them, and grew very heavy upon them,
though they still persisted in their own way; and John Smith, one of the prisoners,
said to judge Byfield, that he also must come one day to judgment,
before a greater judicature, and therefore desired him to be careful what he did.

Some time being spent in this manner, the court adjourned till towards the evening;
and at our departure,
I acknowledged the civilities we had met with from the judge and court,
and our hats being delivered us, we accompanied the young men back to the prison; where,
being set down together, the presence of the Lord was sensibly with us,
and I had some things to say concerning faithfulness unto God,
and the great reward of it here and hereafter; and one of the prisoners, and some others,
were tendered.
Having likewise prayed, and being about to depart, we found the prison door was locked,
by which we were detained a short time;
for the jailer having been reproved for suffering us to have meetings in the prison,
and had injunctions that no more should be allowed of, was fearful,
and therefore had locked the door and left us.
The prisoners were ordered to be confined until their fines were paid.

Parting with the prisoners in much love and divine peace,
I went the same evening to Joseph Wanton`'s, and had a meeting, which was small,
and not very lively, consisting for the most part, of laboring people,
newly come from their work; yet the Lord was good to us,
being present with us before we parted.

The next day we had a meeting at Seconet, which was very hard and dull,
little appearing in testimony but reproof and judgment;
and that evening we returned heavy to Joseph Wanton`'s,
where I remained as it were dead and comfortless till the next morning.
But sitting down a little with the family, and the Friends who were with me,
and waiting upon the Lord, his blessed presence overshadowed us, to our general comfort;
so that those Friends present went cheerfully home, and I departed in the like enjoyment,
to the praise of our living Lord, the Fountain of all our mercies.

That night we lodged with Peleg Slocum, where we were very easy and well; and next day,
being the first of the week, went to the meeting at Dartmouth, which was large,
and the blessed Truth was over all, to the glory of his great name, who liveth,
and reigneth, and is worthy for ever and ever.

Next morning we called at the house of Daniel Shepherd,
whose wife had been at some meetings, but neither of them professed Truth.
She was very ill of a fever, and made many promises,
that if it might please the Lord to restore her to health, she would be more faithful.
For though she had not been guilty of any great evil, as she said of her own accord,
yet she had not been so faithful and diligent in following the Lord as she ought,
according to what had been made known to her.
We sat down, and the divine Truth began to work, and after some time,
I was concerned in prayer, which being over, I took the woman by the hand,
and she was full of the love Truth, and said she never had been so comforted before,
giving me many thanks for it.
I bid her give the glory to God, and no thanks to me,
for it was his love and power which comforted her,
and I was only the instrument of it for her good;
and exhorting her to retire inward to the Lord,
to fee! more and more after his divine presence in herself, we departed.

That evening we went to Sippycan, otherwise called Rochester,
and next day had a meeting there.
It was small and hard, but ended well; and after it we went to Sandwich, and that night,
though late, came to us, Capt.
William Bassett, a man of good temper and understanding,
the greatest disputant in those parts for the Presbyterians,
and having often disputed with Friends concerning war and fighting.
He came to see a copy of the judgment against the young men before mentioned,
for not training or going to war, and I took occasion to say,
"`That Christians ought not to fight or learn war.
And that God hath said by his prophets, '`It shall come to pass in the last days,
that the mountain of the Lord`'s house shall be established in the top of the mountains,
and shall be exalted above the hills; and all nations shall flow unto it.
And many people shall go and say, Come ye, and let us go up to the mountain of the Lord,
to the house of the God of Jacob, and he will teach us of his ways,
and we will walk in his paths: for, out of Zion shall go forth the law,
and the Word of the Lord from Jerusalem.
And he shall judge among the nations, and shall rebuke many people:
and they shall beat their swords into plough-shares, and their spears into pruning-hooks:
nation shall not lift up sword against nation; neither shall they learn war any more.
O house of Jacob, come ye, and let us walk in the light of the Lord.`'

"`Now all this the law of the government of Boston contradicts,
where it saith in express words, '`All above sixteen, and under sixty years of age,
shall appear in arms, and be trained up in war.`'
And upon these Scriptures I observe, that the nations, or any of them,
so long as they continue to reject the Lord Jesus Christ, the true light,
which enlightens every man which cometh into the world, in which the house of Jacob,
the true church, walketh, and follow their own corruptions, lusts,
and laws made by themselves, to support them therein, they will from age to age,
go on in war and destruction one of another.
Yet the true disciples of Christ,
are those who speak the language of those prophecies in their actions,
as well as words and doctrine;
they will not fight now in defense of the religion
taught by Christ and his prophets and apostles,
more than his disciples in the days of his flesh would fight for his person; fighting,
in its root and nature, being opposite to Christ and the end of his coming,
who teacheth us to love enemies, and not to destroy them,
and '`came not to destroy the lives of men, but to save them.`'
The language of his followers, the saved of the Lord, is, '`Come ye,
and let us go up to the mountain of the Lord, to the house of the God of Jacob,
and he will teach us of his ways, and we will walk in his paths.
O, house of Jacob, come ye, and let us walk in the light of the Lord.
For all people will walk every one in the name of his God,
and we will walk in the name of the Lord our God, for ever and ever.
And the nations of them that are saved shall walk in the light of the Lamb.`'`"

We had some further conference about justification and sanctification,
and freedom from sin in this life; wherein I informed him,
that the Lord`'s way of sanctification and justification, is, to make men just,
who are not so, and holy, who were before defiled by sin.
As it is said, "`Either make the tree good, and his fruit good;
or else make the tree corrupt, and his fruit corrupt: for the tree is known by his fruit.
For we are his workmanship, created in Christ Jesus unto good works,
which God hath before ordained, that we I should walk in them;
and have put on the new man, which is renewed in knowledge,
after the image of Him who created him.`"
The Lord Jesus Christ came not to save men in their sins,
(that cannot be) but from them and all the dreadful effects of them,
and to bring them "`into the glorious liberty of the children of God.`"

The substance of these things the captain heard with good temper and solidity,
and seemed pretty well satisfied,
and I heard he spake afterward in commendation of that discourse.
But before we parted, I said to him,
"`That I should be glad to see some of the more
moderate sort of their magistrates and ministers,
and to discourse with them about religious matters;
for I suspect we are not rightly understood in
divers points of religion by them:`" which,
by the sequel, he bore in mind, though at that time he said not much to it.

The next day, being the fourth of the week, and their meeting-day, we staid at Sandwich,
and that evening went to Succoness.

The day following we had a small, hard, drowsy meeting there,
and the next day one at Yarmouth.

On the 22nd we rested at Sandwich, and next day, being the first of the week,
had a meeting there, which was large, and indifferently well.

Having had some conference with captain Basset,
one of justices of the peace of that place, as above hinted,
a Friend told him that I purposed to call at his house on the 24th,
which I accordingly did, where I found assembled a great many Friends and others;
for my intention of calling being known, they on both sides expected a dispute,
of which I had no apprehension.
Soon after we had entered the captain`'s house, he made a short speech to me,
in the audience of as many as could throng into the room, to this purpose, viz: "`Sir,
you told me upon our last conference,
that you would be glad to see some of the more
moderate sort of our magistrates and ministers,
and to discourse with them on religious subjects;
here are several of our magistrates present,`" pointing to them,
"`and this gentleman,`" pointing to one in the room, "`is our teacher.`"

To this I answered,
by giving them a relation upon what subjects the captain and I had been discoursing;
and that what I said concerning their magistrates and ministers,
was with respect to them at large in the province, and not in that place only,
my inclination being to persuade them to more moderation concerning our friends,
now in the time of war,
and to give them a more distinct knowledge of our
principles than I perceived they hitherto had.
However,
seeing so many people had heard already what subjects the captain and I had been upon,
I was willing we should resume them in their audience.
And upon my mentioning that point of freedom from sin in this life,
their minister answered, that "`it is the duty of every true Christian,
to aspire after freedom from sin in this life.`"

I replied, "`That seeing he acknowledged that to be a duty, he must, of consequence,
own it possible; and that therefore there was no need to say any more about it.`"

To this he replied, "`It is said, '`Ye shall be holy;
for I the Lord your God am holy:`' and yet who will presume to say he is as holy as God?`"
Then said I, "`The Scripture saith, '`Sanctify yourselves therefore, and be ye holy:
for I am the Lord your God.
And ye shall keep my statutes, and do them: I am the Lord which sanctify you.`'
Seeing therefore it is the Lord who sanctifies, his work is perfect, he doth it fully;
and what God hath sanctified, let no man call common or unclean.
And God`'s people, who are so indeed, are a holy people: as it is written,
'`For thou art a holy people unto the Lord thy God:
the Lord thy God hath chosen thee to be a special people unto himself,
above all people that are upon the face of the earth.
The Lord did not set his love upon you, nor choose you,
because ye were more in number than any people, for ye were the fewest of all people;
but because the Lord loved you,`'`" etc.

I added further, "`That we spake not of degrees of holiness,
as comparing man with God therein, otherwise than the Lord himself hath done.
But as God is absolutely perfect, and infinite in all essential attributes,
moral and divine, so there is a holiness applicable to man as a perfect creature of God:
'`For in the beginning God created man in his own image,
in righteousness and true holiness;`' and yet we
do not say that man was equal therein to God.
Even so, man may be truly restored by God, through Christ, to the same holiness, and may,
and ought to confess it, to the honor of God, without any presumption;
seeing that since the fall of man, and before the coming of Christ in the flesh,
God hath thus said to his people, '`Be ye holy,
for I am holy;`' which the Lord would not have said, if like holiness with his own,
had not, through his Word, been attainable by them.
And so likewise of God`'s righteousness, as well as his holiness, where it is said,
'`Little children, let no man deceive you: He that doth righteousness, is righteous,
even as he is righteous.`'`"

Upon this their minister was silent;
but the justices and people being desirous that
some other points should be moved and debated,
captain Basset, having great sway among them,
proposed that we should adjourn from his house to their meeting-house, where I might,
if I could, make out the matter more fully, with what else might occur,
before the people.
To this the minister was averse; but the captain,
being seconded by the rest of the justices, the minister was overruled,
and to the meeting-house we went, and the people followed us.
It was some time before their minister pitched upon a point upon which to oppose us;
but at last, notwithstanding what had passed before, he moved this question;
"`Whether there be a state of freedom from sin attainable in this life?`"
And I, being willing, as the Lord might enable me,
to make our doctrine in that point plain to the people, assumed the affirmative,
and my opponent assumed the negative.

The affirmative being mine, I was to prove it;
and accordingly began and proceeded after the manner of the apostles Paul and John:
first to prove, "`That all men commonly sin in this life in a state of nature,
or are liable thereto by temptation; and then,
that the offers of salvation are made by God the
Father unto all mankind in Christ the Son of God;
and that whosoever does accept of those offers in God`'s way and time,
may not only be saved at last, but freed from sin in this present world.

"`The apostle Paul, in his Epistle to the Romans, proves the Gentiles,
of whose lineage are all nations, the Jews excepted, to be sinners,
by breaking the law of God written in their hearts, whereby they became conscious of sin,
and guilty before God.
And the Jews likewise, according to the Psalms of David,
where it is written concerning them, '`There is none righteous, no not one:
there is none that doeth good, no not one.`'
And again, '`God hath concluded them all in unbelief, that he might have mercy upon all.`'
And again, '`The Scripture hath concluded all under sin,
that the promise by faith of Jesus Christ might be given to them that believe.`'

"`The apostle having thus proved all to be sinners, both Jews and Gentiles,
he proceeds to preach salvation to all by the Lord Jesus Christ, saying,
'`Being justified freely by his grace (which hath appeared unto
all men) through the redemption which is in Jesus Christ:
whom God hath set forth to be a propitiation, through faith in his blood,
to declare his righteousness for the remission of sins that are past,
through the forbearance of God.`'
Which faith must be obtained in this life, or never.

"`The same apostle, in another place,
proceeds to set forth freedom from sin in this life likewise by the same Savior, saying,
'`As by the offense of one, judgment came upon all men to condemnation; even so,
by the righteousness of one, the free gift came upon all men unto justification of life.`'
This free gift is '`the grace of God which bringeth salvation,
and hath appeared to all men; teaching us,
(especially all who believe therein) that denying ungodliness and worldly lusts,
we should live soberly, righteously, and godly in this present world.`'
That, '`where sin once abounded, grace might much more abound:
that as sin hath reigned unto death, even so might grace reign through righteousness,
unto eternal life, by Jesus Christ our Lord.
What shall we say then?
Shall we continue in sin, that grace may abound?
God forbid.
How shall we who are dead unto sin live any longer therein?
Knowing this, that our old man is crucified with him,
that the body of sin might be destroyed, that henceforth we should not serve sin.
Knowing that Christ being raised from the dead, dieth no more;
death hath no more dominion over him.
For in that he died, he died unto sin once: but in that he liveth, he liveth unto God.
Likewise reckon ye also yourselves to be dead indeed unto sin, but alive unto God,
through Jesus Christ our Lord.
Being then made free from sin, ye became the servants of righteousness;
for when ye were the servants of sin ye were free from righteousness: but now,
being made free from sin, and become servants to God, ye have your fruit unto holiness,
and the end everlasting life.`'
Again,
after this apostle had brought this doctrine of
freedom from sin in this life to a period,
under the similitude of the death and resurrection of Christ,
and thereby established the certainty of it,
he resumes the same doctrine in the beginning of the seventh chapter,
under another similitude, and brings it to the like conclusion;
'`For when we were in the flesh,
the motions of sins (or passions) which were (discovered) by the law,
did work in our members, to bring forth fruit unto death;
but now we are delivered from the law, that being dead,
(or being dead to that) wherein we were held,
that we should serve (God) in newness of spirit, and not in the oldness of the letter;
that ye should be married to another, even to him who is raised from the dead,
(who is without sin) that we should bring forth fruit unto God.`'
They being dead unto sin, and the carnal mind, which is enmity against God, in which,
(a state of nature) they had been held, they then became as pure virgins,
espoused unto him who had died for them in pure and matchless love,
who cannot be joined to any unclean thing, in the new covenant of everlasting love,
light, and life eternal, that they, by him, might bring forth fruit unto God;
which is holiness, righteousness, truth and peace, and not sin or evil.

"`And a third time the apostle proceeds, and insists upon the same doctrine,
and finally established it unalterably the same way: first,
setting forth the power of sin in the flesh,
notwithstanding the moral precepts of the law,
which prove insufficient until we come unto Christ,
or until his power be inwardly revealed,
by whom alone full freedom and deliverance from sin in this life,
and eternal salvation from the wages thereof in another world, are come.
The apostle, speaking concerning himself and the church of Christ at that time,
and the state they had been in before they believed in him, saith,
'`When we were in the flesh, the motions of sins did work in our members,`' as above.
The knowledge of sin comes by the law.
Sin brings spiritual death; and being discovered by the commandment,
becomes exceeding sinful.
The law is spiritual, but man, in his natural and fallen state, is carnal,
a slave to his own corruptions, lusts, and sins: for though the law, which is light,
and the commandment, which is as a burning lamp, discovers to man his duty,
what he ought to do, and leave undone; yet,
through the weakness of nature in its fallen state,
and the suggestions of the evil one in the imaginations and carnal mind,
(no good thing being in the flesh) the apostle and others under the law,
were held captive, and under a long and hard struggle for liberty and victory,
but could not obtain it by all the legal precepts, or rational assent unto them,
or by his own learning or natural powers.
He delighted in the law of God in his mind, yet seeing another law in his members,
to be understood as the temptations of the evil one,
working in the lusts and corruptions of the carnal mind,
warring against the law of his mind, and bringing him into captivity to the law of sin,
which was in his members; and seeing no way of deliverance from sin, by the law of Moses,
he cries out, as it were aloud, under a sense of the whole weight, force,
and body of sin, and saith, '`O wretched man that I am,
who shall deliver me from the body of this death!`'

"`Now, though the apostle, in all this, speaks as in the first person,
setting forth the state he had once been in,
or rather the state in which the Jews were who had not believed in Christ;
for this apostle had been, '`touching the righteousness of the law,
blameless,`' yet it is plain, that neither the apostle himself,
nor the true believers and followers of Christ in that day,
were in that state of sin at that time, but redeemed from it.
For instantly after the apostle had thus cried out,
'`Who shall deliver me from the body of this death!`' he
immediately and most comfortably answers,
'`I thank God, through Jesus Christ our Lord;`' and adds,
'`There is therefore now no condemnation to them which are in Christ Jesus,
who walk not after the flesh, but after the Spirit;
for the law of the Spirit of life in Christ Jesus,
hath made me free from the law of sin and death.`'

"`Seeing the apostle speaks of a state of captivity and
bondage under the law or power of sin and death in this life,
and of a state of redemption and freedom from that law also, in this present world,
by Christ, including the apostle himself, and every living member of the true church,
neither he nor any other of them as such,
could be in those two opposite states at the same time,
or in so short a time as he was in writing that part of his epistle; which,
in an ordinary way, might be in less than two hours:
but sin being reproved and condemned in them,
by the manifestation of the Holy Spirit of Christ,
and the righteousness of the law fulfilled in them,
and they become the sons of God thereby,
they were gradually led out of sin into all truth, according to the promise of Christ,
whose word is truth, and sure for ever unto all who believe, love, and obey him.

"`And also, in another place, this apostle confirms the same doctrine,
with respect to the present salvation and attainments
of the true disciples of Christ in that day,
where he saith, '`For we ourselves also were sometimes foolish, disobedient, deceived,
serving divers lusts and pleasures, living in malice and envy, hateful,
and hating one another;
but after that the kindness and love of God our Savior towards man appeared,
not by works of righteousness which we have done, but according to his mercy he saved us,
by the washing of regeneration, and renewing of the Holy Ghost,
which he shed on us abundantly,
through Jesus Christ our Savior;`' which must be done in this life,
or else there will be no entering the kingdom of God;
for no unclean thing can enter there.

"`The apostle Paul having thus, in this epistle,
fully preached the glorious doctrine of liberty from sin in this life,
through Jesus Christ, the Word, Son, Wisdom, and Power of the Father,
as he likewise preaches the same in divers others of his epistles,
not necessary to be mentioned at this time; I proceed to prove the same doctrine,
by the authority and testimony of the apostle John,
who preached it after the same manner,
that it may be established from the mouths of two so great and faithful witnesses.

"`1st; That all have sinned and wanted salvation.
2ndly; That Christ died for all mankind.
And 3rdly; That all who believe in the Lord Jesus Christ,
and follow him in the regeneration, are not only freed from all sin in this life,
but eternally saved in that which is to come.

"`In the first place the apostle reminds the church,
what was the testimony of the apostles unto them
from the beginning of their preaching the gospel,
and the certainty of it, as what they '`had heard, seen,
and handled of the Word of Life;`' so that they certainly knew,
and were witnesses of the truth they delivered to others, '`That God is light,
and in him is no darkness at all.`'

"`In the next place, that they had formerly, in their natural state, been sinners,
but having confessed their sins to the Holy One, who, in love and mercy,
convinceth and reproveth the world of sin,
then his faithfulness and justice were made manifest in them,
not only in the forgiveness of their sins against his law,
but likewise in cleansing them from all the inward pollution of sin and unrighteousness.

"`If they had said they had not sinned, they would then have given God the lie,
who sent his Son to save them from their sins; but though all have sinned,
yet God in infinite love, mercy, and goodness, hath sent his Son, the Lord Jesus Christ,
'`to be a propitiation for the sins of the whole world;`' thereby
declaring his mercy and goodness in him unto all mankind,
to be testified in due time.
And the sin and condemnation of the world stand in this;
That Christ is come into the world, not only as man and lifted up,
but also as he is the true light,
'`which enlightens every man that cometh into the
world;`' but the world neither knoweth him,
nor believeth in him, (as that light) nor loveth him, but men rather love themselves,
and darkness, wherein to act their own will,
and hide from themselves their own evil deeds.

"`And although this divine eternal light reproveth and
condemneth all sin and evil in mankind,
yet faith therein doth not only restore and preserve from final perdition,
but hath the promise of life eternal.
And on the contrary, he that believeth not is under present condemnation,
not for acts of sin and evil only,
but because '`he hath not believed in the name of the only begotten Son of God.`'
Thus is faith in the Lord Jesus Christ, the Son of God, as he is lifted up and crucified,
and likewise as he is the true and divine light,
and that faith accompanied and evidenced by good works,
necessary and effectual for the redemption, and present restoration of unbelieving,
sinful, polluted mankind, from under their present condemnation,
and for their preservation unto life eternal.

"`And God the Father, through Jesus Christ the Son,
hath given a saving gift of his divine Light, Spirit, Grace, and Truth,
which is one and the same, unto all mankind, to lead, direct, and guide them,
as an ever-living, infallible Teacher unto all, that whosoever shall believe therein,
and repent of their sins, and obey him in his manifestations in their hearts, minds,
and understandings, shall be surely led into all Truth,
and consequently out of all untruth and error, which must be in this life, where sin,
untruth and error only are.
The cause of such the Lord Jesus will advocate before the Father.

"`And as the knowledge of God and Christ is eternal life,
so the evidence of that knowledge is the keeping of his commandments,
and the love of the brethren.
Whoever pretendeth to that knowledge, and keepeth not his commandments, is a liar,
and Christ, who is the Truth, is not in him; he is a reprobate,
and his sins remain upon him,
notwithstanding the sufficiency of the propitiation in its own nature,
and to its general and proper end.

"`But whosoever keepeth his Word, in him is the love of God perfected;
whereby such sanctified souls know, not only that their sins are forgiven them,
but that they are in him that is true, in whom there is no sin;
and such walk in the way of faithfulness and obedience to the Father in all things,
even as Christ himself walked, who never sinned,
which sinless walking must refer to the Christian`'s conduct in this world,
in order to be settled at last in the kingdom of glory, where nothing sinful or unclean,
while so, can come.

"`And this apostle clearly distinguisheth three several states
and orders in the universal church of Christ at that time;
that is to say, '`Little children, young men,
and fathers:`' and it hath ever been the same, from that day unto this, and ever will be,
to the end of the world.
He writes first to little children in Christ, that they should not sin: for this apostle,
as all the rest, having once been such,
knew the danger they were in of being enticed by the evil one,
mysteriously working in their own natural propensities, affections, passions,
and desires, even after they had known something of the beginning of the work of Christ,
the Word of God in them; and yet, if such should sin, he,
to preserve them from despairing of the mercy of God, through a consciousness of sin,
and the accusations of the evil one,
remarks the provision which is made for their safety, saying, '`If any man sin,
we have an advocate with the Father, Jesus Christ the righteous.`'
Their sins were forgiven them, and they knew the Father.

2ndly; The apostle writes unto the young men in Christ, not that they should not sin,
they having attained a further degree of growth and establishment,
but because they were strong through the in-dwelling of Christ, the Word of God, in them,
and had thereby overcome the wicked one;
and there was nothing then to lead them into sin,
but they were preserved from the sins and evils of the
world through the prayer and intercession of Christ,
until they attained a further degree of knowledge of God, and in due time became fathers.

"`3rdly; He wrote unto the fathers of the church, not as to children,
that they should not sin, nor as to young men, who were not yet perfect in knowledge;
but because they had known him who is from the beginning.
They were come to the certain infallible knowledge of God and Christ, as sure as,
and more so than, they could know the certainty of any object, knowable by hearing,
seeing, or handling thereof.
They knew Christ, not only as the Messiah,
sent of the Father into the world in human nature, but as he is the Word of Life,
manifested to them, and in them:
and that was the message of the apostles to the church (the congregation of
God) from the beginning of the publication of the gospel,
in order to true church fellowship; that as Christ is the Word of life from the Father,
so God is light, and in him is no darkness at all.
And this message was thus declared by the apostles and
messengers of Christ to the universal church of God,
that they might have fellowship with them, whose fellowship was with the Father,
and with his Son Jesus Christ,
which plainly implies the presence of the Father and Son divinely and sensibly in them,
and in every true and living member of that holy and saved body, where no sin,
uncleanness or unrighteousness can remain or come.
For they who live in sin, live in darkness,
and are dead unto God while they live in the world;
and when they pretend to fellowship with God and Christ in his church, they lie,
and do not the truth, but continue in sin,
and have only a church and fellowship therein of their own inventing and composing,
and not of the Lord; for as the Father and Son are one, a divine and eternal light,
in whom there is no darkness, good works are the evidence of true faith in him;
and even so,
walking and having conversation in and through this present world of darkness,
in and by that light, is the true and only test of fellowship with God and Christ,
and the universal church of Christ, wherever hidden, dispersed, or visible in the world;
all the members of this holy Christian fellowship
having not only all their transgressions pardoned,
but are also cleansed by the blood and Spirit of Christ, from all sin.

"`Though I have been long upon this necessary and
important doctrine of the apostles of Christ,
let your patience bear a little longer,
till I add some more texts out of the same epistle of the latter,
in further confirmation of the same doctrine, where he saith,
'`Every man that hath this hope in him, (that is,
of seeing the Lord as he is) purifieth himself even as he is pure; and in him is no sin.
Whosoever abideth in him sinneth not; whosoever sins hath not seen him, neither known him.
Whosoever is born of God doth not commit sin; for his seed remaineth in him,
and he cannot sin, because he is born of God.`'
It is therefore evident, that as many as receive the Word of God,
by whom the world was made, '`to them he gives power to become the sons of God,
even to them that believe on his name: who are born not of blood,
nor of the will of the flesh, nor of the will of man, but of God.`'

"`Now, I would have the auditory to observe,
that this epistle of John was written chiefly to preserve the
church of God from being seduced from the teachings of Christ,
the Word of life, of which they were born,`' by the antichrists in those days,
who attempted to draw them therefrom, back into the rites of the law of Moses,
effectually ended by the coming and manifestation of Christ the Lord,
as appears by these parts of the epistle, where it is said; '`Little children,
it is the last time, (or dispensation) and as you have heard that antichrist shall come,
even now are there many antichrists; whereby we know it is the last time.
They went out from us, but they were not of us; for if they had been of us, they would,
no doubt, have continued with us: but they went out,
that they might be made manifest that they were not all of us:
but ye have an unction from the Holy One, and ye know all things.`'
'`These things have I written unto you concerning them that seduce you:
but the anointing which ye have received of him abideth in you,
and ye need not that any man teach you:
but as the same anointing teacheth you of all things, and is truth, and is no lie;
and even as it hath taught you, ye shall abide in him.`'

"`And the successors of those antichrists, and their supporters,
who have from age to age, even until now,
formed and composed unto themselves images and likenesses of religion and worship,
from mistaken, wrested, and misapplied texts and portions of the holy Scriptures,
intermixed with many inventions and imaginations of their own,
and imposed their forgeries, by violence of persecution,
upon the church of Christ and mankind, are still, under various names and forms,
the chief opposers that Christ and his true ministers and doctrine,
which in itself is the same now as then, do meet with in this generation.
Those antichrists had once been professors of Christ, and many of them then were,
as to his outward coming in the flesh, but had gone out,
and apostatized from the Spirit of Christ, the holy anointing and divine light of God,
and the fellowship of the faithful therein, denying thereby the Lord who bought them,
attempting to draw the church of God after themselves and their false teachings,
and to establish the rites and righteousness of the law of Moses,
in their own erroneous sense;
together with their own heterodox sentiments concerning the faith of Christ,
imposed by persecution and anti-christian violence.
So it is now, by the same spirit, in like mercenary members,
who come in their own names and wills, and not in the name, will, and power of the Lord,
and seek and propagate their own interest, honor, power, and glory only,
and not the Lord`'s, nor the good of mankind,
but to make a prey and advantage of them unto themselves.`"

These things having passed after this manner, I drew to a conclusion thus:
"`That though by nature, as we are the offspring of the first Adam,
we have a seed of evil or sin in us; which springing up,
and we acting according to its motions, being influenced by the evil one,
become guilty before God; yet, as we receive and believe in, and unite with Christ,
the Word of God, the second Adam, the Lord from heaven, the quickening Spirit,
and are witnesses of his work in our hearts, we become born of him, that Seed,
who never fell, or could fall, children of God, and heirs of his precious promises,
partakers of the divine nature,
and have present redemption from under the power of sin and satan.`"
During all this time, which held above an hour, the people were very still,
but their minister was fretful, and interrupted me often,
for he saw what I said took with them;
but several of the justices reprehended him openly divers times,
and he was much down and discouraged.

When I had done he answered,
"`That there is not a just man upon the earth that doth good
and sinneth not;`" and that "`if we say we have no sin we
deceive ourselves;`" with some such things in favor of sin,
very short, and so sat down.

I replied, "`That I had already repeated one of those texts of Scripture,
and some others to the same purpose;
(for I intended at first to anticipate him in what they
usually allege in favor of that pernicious doctrine,
of sin term of life,) and that whatsoever was written in the law,
was to them who were under it.
It is true, while men were under that law, which gave the knowledge of sin,
but did not redeem from it, all these things were true as to them.
For the law made nothing perfect; but the bringing in of a better hope doth;
which hope is '`Christ in us the hope of glory,`' the law of the Spirit of life by Christ,
which, received and believed in, worketh in us a conformity to the will of God,
which the law of Moses could not do, as I have already proved.`"

This opposer was very angry at all this,
and several times broke out into opprobrious language,
and false charges against us as a people; but several of the magistrates reproved him.
Captain Basset alleging still that the apostle was in that
sinful and wretched state when he wrote that epistle,
undertook the argument, but advanced nothing new,
only the weakness of nature since the fall, and how easily we are prevailed upon to sin.
Whereupon I took the Bible again, and showed him in the same chapter,
"`That the apostle speaks only of a state under the law,
but was not in that condition himself at that time, in these words,
'`For when we were in the flesh,
the motions of sins which were by the law did work in
our members to bring forth fruit unto death;
but now we are delivered from the law, that being dead wherein we were held,
that we should serve in newness of spirit, and not in the oldness of the letter.`'
Here it is evident that the apostle speaks of two very differing states; of sin,
in which they had once been whilst in the flesh, or carnal mind,
and of freedom from sin in the spirit;
and they could not be in those two opposite states at the same time.
By the law the power of sin is made manifest, reproved,
and condemned in the mind and understanding; but sin is not thereby,
nor can it by any outward law, be subdued and slain, until man believe, repent, receive,
follow, and obey the law of the Spirit of life,
which not only reproves and condemns for sin, but destroys it.

"`Now, that wherein we are captivated, and held in our first and natural state,
is our carnal mind; which being '`enmity against God,`' neither is nor can be, as such,
subject unto his law; but that enmity being slain and crucified by the cross of Christ,
the grace and Spirit of God, and the body of sin destroyed,
that henceforth we should not serve sin,
then the reproving and condemning power of the law ceaseth to work in the soul;
for they who are Christ`'s '`have crucified the flesh, with the affections and lusts.`'

"`And though they who are in the flesh cannot please God, yet the apostle, by the flesh,
doth not mean the natural body, but the carnal mind; for he saith,
'`But ye are not in the flesh, but in the Spirit,
if so be that the Spirit of God dwell in you.
Now, if any man have not the Spirit of Christ, he is none of his.`'`"

By this time the Truth being in some measure over the people,
they were generally calm and silent; and being asked if they were satisfied,
they made no reply, only one pettish justice said no; and captain Basset,
being desirous of further dispute, said,
he could not yet believe that mankind could be freed from sin in this life:
but neither of them assigned any foundation or cause for their unbelief.
Then their minister, taking fresh encouragement from them,
blustered out several harsh and false charges,
and railing accusations against us as a people, which I took in writing,
and put him upon his proof, viz:

"`1st; That the Quakers hold lying and damnable principles.

"`2ndly; That the Scriptures of the Old and New Testament are the ground of faith,
and rule of life.`"

Both which I denied, and put him upon his proof, which he undertook, and began thus, viz:
"`The words of the charge seem harsh, but I cannot help it;
the nature of the thing requires it, and it is not I that bring the charge, but God,
upon their own disobedience: '`For, as it is written, he that saith I know him,
and keepeth not his commandments, is a liar, and the truth is not in him.`'
Now our blessed Lord hath commanded,
as you will find it written in the 28th chapter of Matthew, at the 19th and 20th verses,
'`Go ye therefore and teach all nations, baptizing them in the name of the Father,
and of the Son, and of the Holy Ghost;
teaching them to observe all things whatsoever I have commanded you: and lo,
I am with you always, even unto the end of the world.`'
Now, these people living in the avowed neglect of this great commandment,
and yet pretending to know God and the way of God, they are liars,
and the truth is not in them:
therefore all sober Christian people ought to beware of them,
and shun them as deceivers.`"

To this I answered, "`That if by this Scripture he understood water baptism,
as I apprehended he did, he mistook it;
for every institution of Christ is plain and explicit,
and water not being mentioned there, he must prove it if he could, some other way.
But if it were water baptism, then he himself, and all of his communion,
living in neglect of this commandment, (as he imagines it to be,) are equally,
if not more guilty; not being in the practice of any baptism ever instituted by Christ,
or in use in his church in the days of his apostles, or for some hundreds of years after,
either as to the manner, instrument, or subjects of baptism.
For sprinkling is no baptism, nor are infants the subjects of it;
for the words of the text are, '`Teach all nations,
baptizing them in (or rather into) the name of the Father, and of the Son,
and of the Holy Ghost,
teaching them to observe all things whatsoever I have commanded you,`' etc.

"`The instrument of baptism here, according to your minister, is water,
and the manner of applying it, as is well known, and as the word itself signifies,
is by going into the water and washing, particularly the feet, therein.
The subjects were not infants, but such as were capable, not only of being taught,
or made disciples and believers,
but likewise of observing and doing all things which Christ had taught his disciples;
of which infants are not capable.
And if Christ had commanded his disciples to baptize with water,
and they had only sprinkled, they had not then obeyed him,
but acted another thing in their own wills, and made themselves transgressors.
And if Christ had sent his disciples with such a message, as it is plain he did not,
what is that to this man, or any such?
Who sent them to do so?`"

Then the priest replied and said, he did not sprinkle infants.
I answered, "`What dost thou then?
Dost thou pour water on their faces off thy hand?
Or dost thou wash their faces with it; for it seems thou dost not baptize them?
If not, thou dost not obey the commandment in thy own sense, if it were a command to thee.
But this is only a low equivocal evasion.`"

He replied, "`You have no baptism at all; and the question is not,
whether we are in the right mode of baptizing, but whether you do, or not,
break Christ`'s command in the neglect of it in any form?
And seeing you do neglect it, you are liars, and hold lying principles.`"

Then directing my answer to the people, I said,
"`The question on this head is equally applicable, Who is in the right,
or who is in the wrong?
and not only whether you be in the right mode of water baptism,
but whether you have any at all; and it appears, as above, you have not,
and whether that be water baptism in the text, where water is not mentioned,
as your minister hath suggested, but not proved, and only begged the question,
which I have not granted?
And whether they who neglect or omit water baptism, be liars, and hold lying principles?
As to us, whom he thus accuseth, we have, through the mercy of God,
the true baptism here commanded, which is that of the Spirit;
of which this man is no competent judge,
being ignorant of that great and saving work of the baptism of the Son of God.
I add one question more.
Who sent him, and such as him, either to baptize or sprinkle?
It doth not appear that they are sent of Christ: but if he hath sent them to baptize,
and they do not so, but only rantize, then they break his command by their own rule;
and when they say to a child, '`I baptize thee,`' or to others present,
'`I baptize this child in the name of the Father, Son,
and Holy Ghost,`' they then lie in and unto that great name of the Holy One,
and before the people,
who are yet so blind as not to see they are acting upon false and lying principles.

"`The Lord gave a command to his eleven apostles to preach unto,
and disciple or baptize all nations; but what is that to these men now,
who assume upon themselves a bare, imperfect, and mistaken imitation of it,
in which they send one another with carnal and corrupt views,
in both the senders and sent, without any command from God, but from men,
who know nothing of the mind of God, nor at all seek it therein,
nor have any power from him in what they do?
For a command of that nature to the apostles, is none to any one else,
unless he be likewise qualified, endued, and sent by the same power.
For if this was water baptism, as it is evident it was not,
then it would have been a command and sufficient mission to the apostle Paul, who,
though not behind the chief of the other apostles,
as to any gift or qualification necessary to a gospel minister,
and '`labored more than they all,`' assures us, that '`Christ sent him not to baptize,
but to preach the gospel.`'
And as he was in a particular manner the minister of the Gentiles,
and messenger of the promise of God unto them, to '`turn them from darkness unto light,
and from the power of Satan unto God,`' none can succeed him in
baptizing with water who had it not by command from Christ himself.
And as that great apostle could not justly be accused and stigmatized
as a neglecter and breaker of the command of Christ in that case,
or a liar and holder of lying principles,
when he thanked God he had not proceeded any further than he did,
in a practice for which he had no command or authority; neither can nor ought we.
But being in so good company therein,
and having no command from Christ to baptize or sprinkle, or pour on water,
or any way at all to use it herein, we cannot honestly be charged with any neglect of it,
nor be called liars therefor, nor holders of lying principles; but men of truth,
assuming nothing to ourselves but what we have freely received from the Lord,
the gift of his grace, in which we minister freely, without money and without price,
and therefore all sober Christians ought rather to
receive us and our Christian testimony for truth,
and to shun the mercenary hirelings of the times, of every form,
and beware of those as deceivers who falsely accuse and calumniate us: for it is written,
'`He that receiveth you, receiveth me; and he that receiveth me,
receiveth him that sent me.`'

"`Though it is not incumbent upon me to prove that
water baptism was not commanded in that text,
but upon your minister, +++[+++to prove that it was]
and he hath not done it, yet, for your sakes, and of my friends present,
I find my mind engaged to endeavor to make it manifest that it was not water baptism,
but the baptism of the Holy Ghost; the first being the baptism of John,
and the latter of Christ.

"`John the Baptist was sent of God to preach repentance to the Jews,
and to baptize them with water, saying that they should believe in one to come after him,
whom they did not then know, but that he was among the people, and ready to appear.
That he was a Baptizer superior to himself,
and should baptize them with a more excellent baptism, and that was Christ.
John was the servant, and his baptism was with water, and was to decrease,
and consequently come to an end; but Christ is the Son of God,
and his baptism is with the Holy Ghost and divine sanctifying fire,
and increaseth and remaineth unto the end of the world:
and as Christ fulfilled all the righteousness of the law of Moses in his own person,
so likewise as John`'s baptism, in point of time, came before his,
though he needed no repentance, not having sinned,
it was incumbent upon him to fulfill the righteousness of that dispensation likewise;
and therefore he was baptized of John as others were.
Thus concentering in himself all the righteousness of the
typical dispensations of God he became from thenceforth the
sole Dispenser of righteousness unto all nations and people,
throughout all generations unto the end of the world;
and he himself is that essential righteousness in his own nature.
And therefore, as soon as he had fulfilled all that righteousness,
he began to be made manifest, and to preach repentance to the Jews, as John did,
that being most necessary to their sinful state,
declaring the kingdom of God to be at hand to that people;
for he was not sent at that time, nor in that manner, to the Gentiles;
and calling disciples, he sent them forth among the Jews,
declaring him to be the Messiah, and preaching in his name the same doctrine,
and baptizing with the same baptism, as to the mode and instrument of it,
but with this distinction as to the application and end of it;
John with water unto repentance, not in any name declared,
but in him who was to come after; but the disciples of Christ preached the same doctrine,
and baptized with the same baptism, but in the name of the Lord Jesus,
as the true object of faith, declaring him to be the Messiah,
of whom Moses and the prophets wrote, now already come and made manifest,
not unto repentance only, but for the remission of sins repented of,
in llie name of him who was shortly to be offered up unto God,
a propitiation for the sins of the whole world.

"`And it is said, that Jesus made and baptized more disciples than John,
yet he did not baptize any in his own person;
that was below the dispensation John had ascribed unto him,
which is a dispensation of eternal substance of light, life, virtue and power,
and not of shadows or symbols.

"`The apostles and disciples of Christ being thus in the practice of water baptism,
and other services of that day, the Lord, when they were able to bear it,
plainly told them who he was, that is, the Way, the Truth, and the Life,
and foretold them of his suffering, a little before it came to pass;
of his departure from them; that he must go away as to his bodily presence,
but should come again in Spirit, by which he should be in them as their Comforter:
and this promise he made in the Father`'s name,
which was to come to pass as the effect of his own prayer and intercession.

"`And accordingly, after he had suffered, and finished his testimony on earth,
and was risen from the dead, he appeared to his disciples,
and gave them several infallible proofs of it.
And the apostles being present with him in a place
appointed a little before he ascended into heaven,
he said unto them, '`All power is given unto me in heaven and in earth,
and repentance and remission of sins must be preached in my name unto all nations,
beginning at Jerusalem; and ye shall be witnesses unto me,
both in Jerusalem and in all Judea, and in Samaria,
and unto the uttermost part of the earth.`'
'`Go ye therefore, teach all nations, baptizing them in the name of the Father,
and of the Son, and of the Holy Ghost;
teaching them to observe all things whatsoever I have commanded you.`'
'`And lo, I am with you always, even unto the end of the world.`'
'`Go ye into all the world, and preach the gospel to every creature; he that believeth,
and is baptized, shall be saved, but he that believeth not shall be damned.`'
'`And behold, I send the promise of my Father upon you.`'
But tarry ye in the city of Jerusalem until ye be endued with power from on high.`'
'`But ye shall receive power after that the Holy Ghost is come upon you.`'
'`For John truly baptized with water;
but ye shall be baptized with the Holy Ghost not many days hence.`'`"

"`Here their mission and work were greatly enlarged; before, they, as well as himself,
were confined to the Jews only, until he had finished his testimony unto them on earth,
but now they are sent to all nations under heaven.
They had been before baptized with John`'s water baptism,
and they had baptized many in the nan)e of the Lord,
without any other power from on high, with the same baptism:
but now they themselves were to be baptized with a more excellent baptism,
foretold by John; the baptism of Christ, which was with the Holy Ghost, a divine, holy,
soul-cleansing fire.
And then, and not before, they were to go out in that glorious, wonderful,
and powerful name.
For after the Lord had given them this command, '`to go and teach all nations,
baptizing them,`' etc.,
he restrained them by a subsequent order from going by virtue of that command only,
until they were actually endued with power from the Father, saying,
'`But ye shall receive power after that the Holy Ghost is come upon you;
for John truly baptized with water,
but ye shall be baptized with the Holy Ghost not many days hence.`'
It is clear that the Lord Christ spake all these things at the same time to his apostles,
with plain connection, very intelligible, to any unprejudiced understanding;
though they are dispersed in the Scriptures, and some part recorded by one Evangelist,
and some by another, and not entirely by anyone of them.
He distinguisheth between the baptism of John with water, then in practice,
and shortly to be superseded, and cease in point of obligation,
and the baptism of Christ himself by the Spirit, which,
as it is the gospel baptism and dispensation, was not then commenced, nor could be,
until Christ ascended,
and was glorified with the same glory that he
had with the Father before the world was made.
The Lord Christ doth not mention in all this, any other water baptism but that of John,
in distinction to the baptism of the Spirit; which he establisheth alone,
as his permanent, necessary, and saving baptism to the end of the world.
Nor is it at all probable that Christ would institute water baptism,
which they were already in the practice of, by his own authority and countenance,
that had its time and use already,
and not so much as name water in the words of the institution,
but by way of contradistinction and precaution, lest they should so far mistake,
in so great and necessary a point, as to think he instituted another water baptism.
And though they were apostles of Christ, and had received some degree of the Spirit,
and were thereby sanctified,
so far as to be fitted for the services to which they had been hitherto called,
yet they were not at this time so thoroughly converted,
or their understandings so far opened, as to know either the nature of this baptism,
or the extent of their commission therein.
For worldly views had prepossessed their minds,
and misguided their judgments for the present,
until the Holy Ghost came and was manifested in them,
by his own divine and powerful influence and work:
for to all that Christ said to them on that subject,
they answered like men deeply prepossessed with
views and sentiments of Christ and his kingdom,
quite contrary to the nature of it, and the Truth; after a carnal manner saying, '`Lord,
wilt thou at this time restore again the kingdom to Israel?`"

"`It is not to be admired therefore,
that none of them understood Christ either as to the nature or extent of their mission,
at that time, until Peter was sent to the house of Cornelius, who was a Gentile,
which was about eight years after this command.
Till then, notwithstanding the plain intelligible words of Christ,
they still thought salvation was confined unto themselves, the Jews only,
until Christ himself demonstrated the contrary by matter of fact,
in baptizing Cornelius and his household with the Holy Ghost, by the ministry of Peter;
and then his understanding was opened and enlarged, and the rest likewise,
who had yet remained ignorant, were,
by his relation of the circumstances of the whole matter, convinced,
both as to the nature and extent of their commission,
that it is a spiritual baptism and dispensation, wherein salvation is offered,
through Christ, unto all nations and ages, to the end of the world.

"`But though the spirit of Christ leadeth those
who believe and follow him into all Truth;
yet not all at once, but as we poor, low, weak mortals are made able to bear,
from one degree of convincement, illumination, sanctification, understanding, experience,
and knowledge, to another, under the conduct of the Spirit,
until we arrive at as great perfection as our nature is capable of in this present world,
which is no small degree, in order to be completely filled for a far greater glory,
and full establishment, in a more excellent world to come, in life everlasting.`"

The priest gave many unmannerly interruptions during this time,
but was sometimes reproved by the justices, especially by captain Basset,
who had great sway, though one of the youngest men among them,
but of good temper and understanding.
His reasons for interrupting me, he said, were these:
"`That if he did not answer things as they were moved,
he would forget great part of them, and so they might pass unanswered,
and take with the people.`"
However,
I came at length to inform the people how this error of
sprinkling came to take place in New England,
viz: "`By the coming over of some of the ancient Puritans, Independents,
and Presbyterians, into that country, not then, in that point,
fully reformed from the church of Rome, the original maintainer of that pernicious error,
by whom it was continued.
And seeing sprinkling is no baptism, you have none at all,
but an old invention and relic of the church of Rome.
Wherefore I exhort you to believe in the Lord Jesus Christ, the Son of God,
that you may be baptized of him, and saved, since he himself hath said,
as on holy record, '`He that believeth and is baptized, shall be saved;
but he that believeth not shall be damned.`'`"

The priest stormed much at this, saying to a Friend as I was speaking,
"`See how smooth he goes, and makes all look as even as he pleases; let him alone,
and the people will take all this for granted;`" and
then arose violently from his seat and interrupted me,
so that I could not finish that part as I intended.
And yet I thought much of what I had said remained with
the more intelligent sort of the people.

To all this my opponent made no reply,
but began to maintain his charge as well as he could,
"`That the Scriptures of the Old and New Testament are
the ground of faith and rule of life.`"
He attempted first to prove, that the Scriptures are the Word of God;
and that as such they are the ground of faith, and rule of life, thus:
"`Christ reproving the Scribes and Pharisees concerning their traditions, told them,
'`They had made the Word of God of none effect thereby;`' and
seeing he here expressly calls the Scriptures the Word of God,
consequently they must be the ground of faith and rule of life.`"

To which I answered,
"`That the particular subject there treated of is the fifth commandment,
not the Scriptures;
where the Lord Christ chargeth them with laying aside the commandment of God,
and giving contrary commandments of their own; rejecting the commandment of God,
that they might keep their own tradition.
So that what is called the word of God in the 13th verse of that chapter,
is the fifth commandment, and not the Scriptures.
And the evangelist Matthew, writing of the same passage,
calls it the commandment all along throughout the chapter,
and never calls it the word of God;
nor doth the Scripture any where call itself the Word of God,
but gives that title justly, and properly, to Christ, in his spiritual appearance,
both in the Old and New Testament: first in the old, where it is written,
'`For this commandment, which I command thee this day, it is not hidden from thee,
neither is it far off, etc., but the Word is very nigh unto thee, in thy mouth,
and in thy heart, that thou mayest do it.`'

"`This was not any of the ten commandments, written on tables of stone, though in.
deed the root of all the commandments of God,
nor was there much of the Scripture then written;
but this was the Spirit of Christ before his incarnation, of whom Peter testifies.
That he was in the prophets, and testified beforehand his sufferings, in the flesh,
and that many hundred years before his manifestation therein,
and the glory that should follow: of whom the apostle Paul likewise bears testimony,
in these words, '`The righteousness which is of faith, speaketh on this wise.
Say not in thine heart, who shall ascend into heaven, (that is,
to bring Christ down from above:) or who shall descend into the deep, (that is,
to bring up Christ again from the dead:) but what saith it?
The Word is nigh thee, even in thy mouth, and in thy heart:
that is the Word of faith which we preach.`'
And the word we, in this place, shows that it was not the testimony of that apostle only,
but likewise of all the rest of the apostles and ministers of Christ in that day,
that Christ himself is the only Word of the Father, and there is not another.

"`Again, the evangelist John testifies of Christ after this manner,
'`In the beginning was the Word, and the Word was with God, and Word was God.
All things were made by him, and without him was not any thing made that was made.
He was in the world, and the world was made by him, and the world knew him not.
And the Word was made flesh, and dwelt among us,`' etc.
Now these things cannot be truly, or with any sense, said of the Scriptures;
for the Spirit of Christ is not the Scriptures, though they testify of him.
The Scriptures never ascended into heaven,
neither did they descend into the deep and rise again;
neither are the Scriptures the word of faith; neither were they in the beginning;
nor are they God; nor was any thing at all made by them.
But all things were made some thousands of years
before there were any Scriptures in the world,
which was not (any now extant) until the days of Moses,
who wrote but a small part of them.
Nor does the world now know God, or the Word of God, by the Scriptures;
nor were they ever made flesh.
They are not therefore the Word of God, and consequently, not that rule,
by your minister`'s own way of reasoning; but, as the apostle Peter testifies,
'`That no prophecy of the Scripture is of any private interpretation:
for the prophecy came not in old time by the will of man;
but holy men of God spake as they were moved by the Holy Ghost.`'

"`And concerning those Scriptures which Peter speaks of,
the Scriptures of the New Testament not being then written,
the Lord Jesus said to the Jews, who had them, though they did not understand them,
or know him by them, '`Ye have not his (the Father`'s) word abiding in you;
for whom he hath sent, him ye believe not.
Search the Scriptures; for in them ye think ye have eternal life;
and they are they which testify of me; and ye will not come to me that ye may have life.`'
Here Christ, the Word of God, is again distinguished from the Scriptures;
they are not that Word, but bear testimony of him:
and so do the Scriptures of both Testaments still, and will, through ages to come.
But, I beseech you to beware, lest, while you seem to magnify the Scriptures,
as the Jews did, you likewise fall into the like errors,
and they become of none effect also unto you,
through your own vain inventions and traditions, and fall short of eternal life,
as they did, through a willful neglect of the manifestations, admonitions,
and operations of the Spirit of Christ, the Word of God, in your own hearts;
the grace of God given unto you, in you,
as a free and constant teacher in the way of truth and salvation;
and lest you be found of the number of those at last,
of whom it is prophesied in the holy Scriptures,
'`The time will come when they will not endure sound doctrine,
but after their own lusts shall they heap to themselves teachers, having itching ears:
and they shall turn away their ears from the truth, and shall be turned unto fables.`'`"

Then I said to the people,
"`I was willing to carry the subject and argument this length for your information,
because I fully desire the welfare and salvation of every one of you; but your teacher,
unaware, gave up his own cause in his own way of reasoning.
For, upon a wrong supposition that the Scripture is the Word of God,
he grounded his position, That it is the ground of faith, and rule of life;
whereas the Scripture itself saith, '`Faith is the gift of God,`' and consequently,
not acquired by reading or hearing the Scriptures, which the Jews had,
and highly esteemed, as much as you can do,
and yet did not believe in Christ the Savior of the world.

"`I shall now invert this assertion, and establish the point contrary to his doctrine,
in a few words, and say, that what, or whoever is the Word of God,
the same is the ground of faith, and rule of life.
But the Lord Jesus Christ, and not the Scriptures, is the Word of God,
in whom dwells all the fulness of the Godhead substantially.
He is the wisdom and power of the Father, and therefore is the ground of faith,
the faith of the operation of God by him, and the rule and ruler of that life,
of which himself is the author and giver.`"

Then I informed the people, "`That we ever had a great esteem for the Scriptures,
believing them to be given by divine inspiration, (the priest having, in our discourse,
urged that passage, where it is said,
'`The Scripture is able to make you wise unto salvation,`' leaving out,
'`through faith which is in Christ Jesus,`' which is the main point)
but they make wise unto salvation only through faith in Christ:
so that faith must go before;
and the apostles believed before their understandings
were opened to know the Scriptures.`"

My opponent gave me several interruptions during this time;
yet I am persuaded divers of the people understood and
received in their minds the truth of much I delivered.
The dispute held about seven hours, and by this time it was near sun-set;
so that we adjourned to captain Basset`'s house, to which we were invited;
where we had some more discourse about the call to the ministry, and their maintenance,
wherein the priest said, that Christ`'s ministers had a command from him,
in Matt. 28:19, to teach and baptize all nations.

I replied, "`That command was not to any others but the apostles in that day,
and the call to the ministry, and qualifications of the ministers of Christ,
are a new work of the Holy Spirit of Christ, in all ages of the world from that time,
and ever will be; and never can be by tradition or imitation,
how nicely soever counterfeited.
And if he had no other foundation for his ministry than that,
he had none at all in the gospel sense;
but seeing he had alleged that text for his ministry, and a command thereby from Christ,
to teach and baptize all nations,
he seemed to be greatly deficient in his obedience and performance,
since I perceived he had been long in that place, if not all the time of his ministry,
and had not travelled through, or in any one nation on that account,
and taught but a few, nor baptized any at all;
for sprinkling of infants is no baptism.`"

Then he turned the question upon me, and asked, if I had been in any nation but one,
on that account, in our way?
To which I answered, "`That question is not so proper to me on that subject,
seeing I do not pretend to have had my ministry from that command,
but by the immediate work and manifestation of the Spirit of Christ, in me, being opened,
directed, and governed thereby in the love of it, in my ministry, from time to time,
and place to place, as it pleaseth him, and not in my own time and will;
and yet not confined or limited to any.
Nevertheless, to answer thy question directly,
I have travelled through most parts of England, Scotland, Ireland,
and many colonies of America, in the service of the Lord Jesus Christ and the gospel,
and that freely, and without charge to any, save to eat and drink,
in the course of my travels, such things as were freely set before me,
by such as received my ministry in the same love of Christ in the gospel,
in which I have travelled and labored; which is the way of our ministers every where.
But I have not baptized any with water; for Christ sent me not to baptize that way,
but to preach the gospel according to the measure given me.`"
Adding, that a maintenance in a particular settled place, as I reasonably could suppose,
might be all he aimed at by his ministry.

He replied, he was, according to the advice of the apostle Paul,
to "`give attendance to reading, to exhortation, to doctrine;
to meditate upon these things, to give himself wholly up to them,
that his profiting might appear to all;`" which
he could not do without a reasonable subsistence.

To this I answered, "`These Scriptures and advice belong to a minister of Christ,
as Timothy was; but they are nothing to such as are not in Timothy`'s condition.
And thou hast omitted to mention the main point there exhorted to; that is,
'`Neglect not the gift that is in thee,`' etc.,
without which all thy ministry will be dead,
and thy reading of no value to the end of a gospel ministry.
For the apostle doth not there write of the studies of our modern masters of arts,
as they call themselves, as appears by these words, '`O Timothy,
keep that which is committed to thy trust, avoiding profane and vain babblings,
and oppositions of science, falsely so called;
which some professing have erred concerning the faith;`' for my opponent had,
in the meeting-house, talked of syllogisms, and such like learning;
but the particular things Timothy was to study, were these,
though he was but a young man, '`To be an example of the believers, in word,
in conversation, in charity, in spirit, in faith, in purity;`' to '`take heed unto himself,
and unto his doctrine, to continue in them,`' etc.
And that reading must relate most, if not only, to the Holy Scriptures,
since he excludes such science: and in his next epistle,
knowing that without the opening of the gift of the Spirit of Christ,
reading the Scriptures would not be rightly profitable or understood, he exhorts Timothy,
'`That he stir up the gift of God which was in him;`' and afterwards, further exhorts him,
'`to continue in the things which he had learned, and had been assured of,
knowing of whom he had learned them:
and that from a child he had known the holy Scriptures,
which were able to make him wise unto salvation, through faith which is in Christ Jesus;
which faith is the gift of God, and not acquired by reading.
All Scripture is given by inspiration of God, and is profitable for doctrine,
for reproof, for correction, for instruction in righteousness,
that the man of God may be perfect, thoroughly furnished unto all good works.`'
But all this is attained by believing in, and adhering to the gift of God,
and the work of it within, and not otherwise; and therefore I exhort thee,
and all these people, to believe in the grace of God in yourselves respectively,
that you may all be taught and perfected thereby, and finally saved;
which I heartily pray unto God for every one of you.

"`And, as the apostle Paul saith concerning himself and his ministry,
'`though I preach the gospel, I have nothing to glory of, for necessity is laid upon me;
yea, woe is unto me if I preach not the gospel.
For if I do this thing willingly, I have a reward;
but if against my will a dispensation of the gospel is committed unto me:
What is my reward then?
Verily, that when I preach the gospel, I may make the gospel of Christ without charge,
that I abuse not my power in the gospel.`'
And accordingly '`he dwelt two whole years in his own hired house,
and received all that came in unto him;`' and appealed to the church at Ephesus,
that he '`had coveted no man`'s silver or gold, or apparel; yea,
yourselves know that these hands have ministered to my necessities,
and to them that were with me.
I have showed you all things, how that, so laboring, ye ought to support the weak;
and to remember the words of the Lord Jesus, how he said.
It is more blessed to give than to receive.`'

"`Thus the apostle exercised his ministry in its full extent; and, no doubt,
had done all those things himself, to which he exhorted Timothy.
So that an honest employ to live by, that the gospel may not be chargeable,
is very consistent with it.
And as to the words, '`wholly to them,`' in his said Epistle to Timothy,
it can mean no more than that he should not neglect any
time to do these things in every opportunity;
the gift there spoken of being fully sufficient
of itself to every thing there exhorted unto,
save only reading; which might well be done,
without any hindrance to a necessary bodily labor, for his own maintenance, at least.
But in all this we do not find any thing of bargain and
sale of the mere dead letter of the book;
which, without the life of Him who first gave it forth, killeth;
or any human and false glosses thereon, in the will and natural abilities of man,
sold at a dear rate to the people for gospel, which it is not;
nor any mercenary preliminaries settled before-hand,
as conditions of preaching those fallacious medleys for gospel;
or of any security to be given for the performance of such blind bargains;
nor of procuring or making human laws, by the violence whereof to extort them,
and from such, too, as are neither par lies nor privy to such works;
nor is there any thing in those or other Scriptures,
of any contributions previously settled, and without which no preachment;
according to the pro verb.
No penny, no pater-noster; there is no thing of all this,
or of the nature and tendency of it in all the Holy Scriptures,
or gospel of the Lord Jesus.`"

This nettled my antagonist much, and at the conclusion of it, I took paper,
and gave him what I had affirmed, and maintained before, viz:
"`That a state of perfect freedom from sin is, through the grace of God,
attainable in this life.`"

And likewise of what he had asserted, viz:
"`That the Quakers held lying and damnable principles;
and that the Scriptures of the Old and New Testament are the ground of faith and
rule of life;`" telling him before the chiefs of the people still remaining with us,
"`that I had, in the meeting-house, sufficiently proved my position,
but he had failed in his; and therefore left them upon him as false assertions,
till he had, (if he could do it) proved them in writing,
since he had in conference given me so many rude interruptions;
and then he might expect an answer, either a refutation or acknowledgment:
for the latter whereof I see no cause, nor ever shall, I am well assured.`"
Thus this long contest ended for that time, but without any personal rancor, I believe,
on either side; for in all contests of this nature which I have hitherto been engaged in,
I have, in the first place, looked for the seasoning grace of God in my own heart,
to qualify me with a right temper of mind for such provocations as I might meet with,
and for understanding and fortitude,
so that the truth might not suffer by any weakness or passion of mine.
My aim hath ever been much more to gain upon the
understandings of my opponents and auditories,
than the vain glory of conquest;
and I have ever succeeded best when preserved in full charity, wherein the divine light,
which giveth understanding, dwelleth,
and have so behaved to the opposers of truth as not to provoke them into any passion,
but keep them calm as much as possible;
they having the measure of the same light in themselves,
(for he is in all mankind) and their own understandings as reasonable creatures,
on my side, against their errors, or mistakes.
My contest is not with men, but their errors, which hurt them, and passion and anger,
(and malice much more so) are darkness, and involve the mind therein;
and while that is uppermost in the heart of man, and he prepossessed against the truth,
he is not capable of information, but opposeth what he does not understand,
though the necessary truths of the gospel.
That is a true saying, "`the natural man receiveth not the things of the Spirit of God,
for they are foolishness unto him; neither can he know them,
because they are spiritually discerned; muchl ess is he capable in the time of anger,
when he is not reasonable;
nor is it prudent to discourse with him on such subjects at such times.
Yet when an opposer, though a little warm, keeps within reasonable bounds,
he may be convinced of his mistakes, and yet not publicly own it,
because of his imaginary honor; for, being in reputation for a man of understanding,
parts and ability, and perhaps a teacher, in his way,
he is ashamed to be overcome before an auditory,
or own the truth to be on the other side;
yet it may be reasonable to discourse with such a one, and profitable to the audience,
though himself may have the least share.
But this I have ever endeavored in such cases,
to part with every opposer in as much friendship as could be obtained, that, if possible,
no rancour might remain.

If I had not known that the invisible power of Truth was over the people at that time,
considering their former enmity against us and the truth,
I had run a great risk (humanly speaking) of personal injury by some of them; but,
through divine goodness both to them and me, I did not observe a frown on any brow,
or hard word from any, save only one before mentioned.
For which, unto the only true God and Savior, be dominion and praises now and for ever.
Amen.
