== Chapter XI

[.chapter-subtitle--blurb]
A Journal of My Voyage to Barbados and the Western Isles, in the Year 1708-9.

Having had a concern upon my mind for some years to visit Barbados, Jamaica,
and some other islands in the West Indies, in the service of Truth,
and the Lord having wrought a willingness in me, in the course of his providence,
made way through many difficulties:
on the 18th of the eleventh month I sailed from Philadelphia in the sloop Unity,
Henry Stephens master, and that evening, about seven, we arrived safe at Newcastle.
It having snowed most of the day, and a strong gale blowing,
with much rain in the evening, we anchored at Newcastle;
and the next morning about eight went on shore, and stayed there that day,
to see if the weather would settle.

On the 21st, being the sixth of the week, we set sail with a small breeze at north-east,
but the wind being slow, and continuing in that point,
the master did not think fit to descend into the bay, but came to anchor.

On the 23rd, being the first-day of the week, we weighed anchor about six in the morning,
the wind near north, and with a fresh gale entered the bay,
and by the good providence of God,
arrived safe and well at Barbados on the 9th of the twelfth month;
so that we had but about fifteen days passage from the capes to the island;
for which I was truly thankful to the Lord, the over-ruler of all things.

I was welcomed by my good friend Edward Singleton, who came on board to that end,
and invited to the house of our friend John Grove,
where I was openly and kindly received.
Two meetings falling of course that day in Bridgetown, where we landed, I was there,
to my great comfort and satisfaction in the Lord,
who was pleased to give me a full confirmation in myself concerning my call thither,
though he did not appear much by me then,
other than in greatly tendering my spirit before him in silence.

Being well refreshed every way, the next morning arrived our friend Samuel Wilkinson,
who had been at Pennsylvania from Ireland; and another meeting falling in course,
we had some service,
the Lord being pleased in some measure to concern us to minister among them,
and things were well and comfortable, though the meeting was but small,
and of them several were strangers.

On the 13th, being the first-day of the week, we had another meeting at Bridgetown,
which`' was larger than before, and a good meeting, many strangers being there,
and things well opened.

On the 15th we had another good meeting at the Bridge, and that evening,
accompanied by our friends John Grove, his wife, and some others,
we went into the country, where we lodged with our friend Joseph Gamble.

On the 16th we had a meeting at Spring meeting-house, where we had several strangers,
and generally satisfied.

On the 27th, being the first-day of the week, I went again to Spring meeting,
where I had some concern; after which I returned to Joseph Gamble`'s.

On the 17th of second month, being the first of the week, I went thence to Pumpkin Hill,
where we had a hard, laborious meeting; and that evening returned to William Derrie`'s,
at Spikes, in great heaviness,
under a sense of a spirit of apostasy and uncleanness in that part of the island,
more than I had felt in some other places.

At Spikes I stayed till the 19th, and had another meeting there;
which consisting for the most part of such as come to meetings,
the testimony for that day, after a long and heavy time in silence,
went against such as had professed Truth, and were not faithful;
but rather secretly encouraged their children in such things as the
testimony of Truth is gone forth against in this generation,
in mixed marriages with such as know not Truth, nor regard its ways,
in the glory of the world, and love of it, and in training to arms.
After the meeting I went, indifferently easy, to Joseph Gamble`'s,
where I lodged that night.

On the 22nd we went to Abigail Braithwaite`'s,
and that afternoon to see our friend Nathaniel Curtis, who at that time was very weak,
and not likely to recover; and after some time with him,
returned that evening to our friend Braithwaite`'s. On
the 23rd we repeated our visit to Nathaniel Curtis,
with whom we had some time in prayer; after which he expressed great satisfaction,
and said, "`It is in vain to make promises to the Lord,
considering the weakness and frailty of man;
but if it may please the Lord to restore my former health, I hope to be more circumspect,
and spend the remainder of my days more to his glory.
He is a merciful God,
and has been near to help in some times of great
extremity;`" with several such like expressions,
in a very weak and broken condition of body and spirit: and so,
after some expressions of respect on both sides, we parted.

[.offset]
+++[+++He attended the meetings in this island as they came in course,
besides appointing many others, until the 7th of third month, 1709,
when he embarked for Antigua,
and arrived there the 13th. Of his visit to this island he says:]

Our friend William Haige met me on the wharf, and from thence conducted me to his house,
where I stayed till the 15th, being the first-day of the week,
and then had a meeting in town, which was indifferently large and good,
the blessed Truth being in good dominion, and the people very sober.

On the 16th I went into the country to see our ancient friend Jonas Langford,
being now above eighty years of age, and without natural sight; but otherwise hearty.
He met me at -the door in the porch, and as I took him by the hand,
he looked upward and said, taking off his hat,
in reverence to that Name he was about to take in his mouth, "`Blessed be the Lord,
who gives unto the righteous the desire of his soul.`"
And so, without any more words between us for some time, keeping me by the hand,
we sat down together in the hall; and after some time in silence,
we discoursed of such things and affairs of truth as then occurred;
and being freely received, and openly entertained both by him and his wife,
there I remained till the fourth-day following,
being in the mean time visited by several Friends.

On the 18th, being the fourth of the week, I went to John`'s-town,
where the meeting fell in course.
It was not large, or very open, yet many things opened clearly,
and the meeting ended indifferently well; after which I returned to William Haige`'s;
and from thence that evening to Jonas Langford`'s, where I stayed till the 20th;
and the meeting falling there in course, was at it, which was very small,
but open and well.

Continuing here till the 22nd, being the first of the week,
and the meeting being there again in course, it was larger than before,
and the blessing of the Lord was plentifully among us, to the praise of his holy Name,
who is worthy forever.

On the 23rd I went to John`'s-town, and lodged that night at William Haige`'s,
and the next morning went to see General Park,
then governor in chief of the Caribbee islands,
who was very respectful and free with me on several heads.
The packet boat being then in, and being free in my mind,
I look my passage in her for Jamaica; but tarrying till the 25th,
about six in the evening, we set sail for Montserrat,
where we arrived next morning about seven,
having had a meeting with Friends at Antigua the day before we sailed thence.

At Montserrat we arrived well, and there tarried till the 28th, in the morning,
and thence set sail for Nevis; where, with a strong gale,
we arrived half an hour after eight the same morning.
Here I went ashore; and the next morning, being the first-day of the week,
we went into the country, about eight miles off,
the worst way for stones that ever I rode, to the house of Mary Wilson, an honest Friend;
where, in a meeting of about eight or nine persons,
the Lord was pleased to give us a comfortable season of his love together,
to our great refreshment.

On the 30th, in the morning,
we set sail and arrived safely at Jamaica about half an hour after four in the evening,
on the 8th of the fourth month.

Soon after our arrival came on board our friend John Ward, and with him I went on shore,
and lodged at his house that night, and the next morning, the 9th,
viewed the town and forts; where I saw great effects of the dreadful earthquake,
still remaining,
though the people were gradually filling up divers deep places with stones,
in order to raise new buildings,
most of the ground being already built upon that
was left by the earthquake in that point.
The earthquake here was such as has scarcely been paralleled in any age or country;
and was followed by a dreadful fire,
which hardly left a house in all the town unconsumed.
Such are their wicked expressions, their oaths, blasphemies,
profanations of the holy name of thje Almighty God, their curses,
and rude language in all their conversation, even amongst both sexes, that sober men,
who never heard them, would hardly believe, if it were told them,
that human nature was capable of so great degeneracy; insomuch that it looks as if,
when sunk into the earth, they had been baptized in hell,
into the very nature and language of it,
whose expressions I will not defile my pen to repeat;
and yet I believe the day of God`'s mercy is not quite over to some among them.
O that they might see it, in the remaining time of it, to their great redemption!

This view finished I went on board Charles Wager, rear-admiral of the blue,
of whom there have been accounts in the public prints,
and his great achievements in martial marine affairs.
My business was only a civil visit, where I was courteously received,
he being a person of a calm, sedate temper, naturally courteous, and no way elevated.
As he is a man of war, we discoursed on that subject; and as I am a man of peace,
we conversed religiously, and not martially;
he for the punishment of privateers and pirates, as breakers of the peace, and robbers;
but I was for saving life, that poor sinners might have time to repent and be saved;
though what passed between us, was with the greatest civility and temper,
the meekness of Christianity being more apparent
in his deportment than any martial harshness.
Having stayed so long as I thought suited our circumstances on both sides at that time,
and received invitations from him to further acquaintance, I returned on shore,
and that afternoon went by water up to Kingston;
and was entertained kindly there by our friend Stephen Web,
with whom I look up my quarters.

On the 10th we had a meeting at Stephen Web`'s house, which was very small and poor,
there being but three or four Friends in town.
On the 12th, being the first day of the week, we had another meeting at the same place,
which was a little larger and better;
though at that time I was under some indisposition of body.

On the 13th I went to Anne Pennock`'s, where I was that night,
and the next day had a meeting there, where were several people,
and most of the Friends of Kingston and those parts, and Truth came over all.

On the 22nd we had a meeting at the house of Captain Hewit, at Port-Royal; who,
though not of our communion, readily gave up his house, as he had written in his letter,
to the service of God.
Being at his plantation, a Friend wrote to him about it; and he ordered his cousin,
a Friend, who looked after the house, to make preparation for the meeting.
It was pretty large, and very well, the Lord opening things clear,
and people were generally satisfied, and some much pleased, as they signified afterwards.
The meeting being over, my company and I dined at the captain`'s house, by his request,
and that evening returned to Kingston.

On the 24th we had another meeting at Kingston, which was very small,
but indifferent well; none but such as make some profession of Truth being there,
it was harder than the other meeting.
On the 16th, being the first-day of the week,
we had another meeting at the same house at Port-Royal,
which was much larger than before, and many things clearly opened; and the people,
though one of the rudest and most wicked places I know of in America, very sober,
attentive, and affected, and some of them pretty much reached.
And leaving things to general satisfaction, and the honor of the Lord,
the Author of every good word and work, I returned with several Friends to Kingston,
where I lodged that night.

On the 28th I embarked for Pennsylvania on board the sloop the Happy Return,
Jonathan Dickinson owner, and James Wilkinson master; and the wind coming fresh,
a sea breeze.
we kept nearer the shore than the rest, and making better way,
the next morning we got up as far as the Yellows,
and in the afternoon reached Port-Morant, where we put in to water;
and the wind increasing, and weather turning bad, we tarried there for the rest,
two of which coming in with the port near night, put out to sea again, as we thought,
to look for the convoy and company, being all to leeward;
but saw no more of any of them whilst we remained in that port,
only we heard of some of them being seen off there on the 1st of the fifth month,
as we lay at anchor, by the inhabitants.

After they departed, we were becalmed in sight of Hispaniola,
and a small island to the westward;
but in the evening made a Mule way with a small breeze, and so proceeded on our voyage.

On the 12th, in the evening, with a fresh gale, we turned the eastern-most point of Cuba,
and stood our course all that night, and the next evening came near certain sands,
called the Hog-sties; and being among several islands, shortened our sail that night,
and in the morning, so soon as we could see about,
found ourselves on the south side of Long Island, and near the shore,
though we did not think it had been that, for we aimed at Crooked island,
further to the east; but by reason of the currents, were insensibly driven thither.

But this was not the worst; for soon after we spied a sail to the windward,
and after a short time perceived it came down upon us, and stood the same way.
We were a while in doubt and suspense what kind of vessel she was,
but in a few hours were convinced to our great exercise and damage;
for coming within gun-shot, we saw his French pendant,
and soon after he fired one of his guns to summon us.

Our captain being of fighting principles, and his men likewise,
hoisted the English ensign, and returned his salute, having two guns only mounted,
though ten on board in the hold, but no loss happened on either side.
They quickly perceived how the mailer stood with us,
that we were not capable of any great resistance;
and therefore advanced within reach of small arms, and gave us one volley;
and the master having only two small arms on board, and but about ten fighting men,
soon yielded to her, who was but a small sloop, with four small guns, about thirty men,
and commanded by Captain Lewey, a Frenchman, and filled out from Martinico.

We being, by God`'s permission, fallen into their hands,
the captain sent on board his lieutenant, one Capitain Cornelius, a Dane, as he said;
who speaking good English, told us not to fear, for we should fare no worse than he;
so that they did no personal harm to any of us,
but were very kind all along as we sailed to Port-a-pee, on the north side of Hispaniola,
where we arrived on the 17th in the evening, and came to an anchor.

Our captors, in the time we were sailing, sung several Ave Marias,
and were very devout and very merry,
and mighty importunate with us to discover what we had but little of, viz: money;
for I had but about two pence on board,
and there was not much more among the rest of the passengers.
However, having a chest of provisions, and a small box with some linen,
they still had a jealousy that I had more,
but were civil in their carriage all this time.

On the 19th the captain that took us went in a boat towards Cape Francois,
to speak with some of their owners concerning the prize;
but still having a jealousy that I had money, he ordered me to be searched,
but found only my silver spoon, my watch being gone before;
so that I saved only two shirts, and some small linen, and what clothes I had on,
which were but mean, being provided on purpose for my voyage.
However, they were otherwise kind; and the man that searched me desired my forgiveness,
since he did it by command, not inclination;
and some of them said they would not have done it on any account.

On the 19th we were sent for on shore by the officers aforesaid,
and very kindly treated by them;
but Jonathan Dickinson +++[+++one of the passengers and a Friend]
and I were under great exercise in spirit, not yet seeing the particular cause,
which afterwards appeared to be this:
It seems the laws of France require an oath of
the owners and masters of vessels in such cases,
the better to discover the value of vessels and things,
which they administer by holding up their hands,
then imprecating God to their loss of their part in him, in case of falsehood,
but true answer to make to every question.

The master being no Friend,
was sworn -- there being a man among themselves understanding English,
by whom they acted--and they examined him strictly; and when they had finished with him,
proposed it next to Jonathan Dickinson, but he refused;
which was a great surprise upon them,
and some of them began to be a little heated and zealous.

Then I told them in Latin,
That we were a people differing from all Protestants in several points of religion;
and that we never swore, either in judicature or conversation:
that we had suffered great hardships in former times in England, for refusing to swear;
and many of us had died in prison for that cause:
that King James had given us some more favor than any before him;
and that King William in his time had passed an Act of Parliament in our favor,
in the case of oaths; and that I believed King James, to whom we were well known,
had given the king of France an account of us in that particular, when in his court,
in the time of his exile.

They replied, it was a difficult case, their law being very express in the king`'s books;
and looked into a printed book often on this occasion.
My spirit being under great exercise all this time,
especially while they were thus striving with Jonathan Dickinson,
who stood firm against swearing; at last I found great ease and comfort in that holy,
blessed and overruling Truth,
whose testimony we were thus called on to bear against so great a power as the French,
then an enemy, and we their prisoners`'; and very soon after,
they look his testimony without swearing, or any other asseveration,
save only a bare and sober relation, by promise only to answer truly.

After they had began their examination of him, the comfort of our blessed Lord,
whose presence and shield was with us, so increased in my heart,
that my spirit was broken in a consideration of his goodness and faithfulness to us,
though I had a full recompense for all I had suffered.
And some tears running down as I sat by, one of them observed it,
and being in a surprise and admiration of it,
they inquired the reason by the interpreter; but I made them a sign of silence,
which they all took, and were still a short time,
and then proceeded in their examination.
Then I told them, when that was over, I would relate the cause of those tears.

The examination being over, which was done both with gentleness and strictness,
then they inquired the cause of my brokenness; to which I answered:
"`That though it had pleased God to permit us to fall into the hands of these men,
and bring us under so great a power, and many dangers,
yet perceiving he had been pleased to inspire them with
so much gentleness and favor towards us,
my spirit was so broken as they observed, in humble thankfulness to the Lord,
who was thus kind to us in a time so needful;
and for their favor we were likewise grateful.`"
All which they heard with great attention, and bowed themselves, when they understood it,
with a gravity, and a serene and gracious aspect.

Things being thus ended to our great ease and comfort in this point,
they took us with them to dinner in town, where they were kind beyond common friendship,
in all manner of freedom and kind expressions; so that, save the loss of goods and time,
our confinement did not seem so grievous as might well have been expected.
They often wished that peace might be proclaimed while we were with them;
and one of them, viz: Judge Danzell, had Jonathan Dickinson, his wife and family,
to his house, about three miles off, where they were kindly entertained.
We went on board again after this time, they giving us leave to be on shore,
or on board as we pleased, saying it should cost us nothing either way:
but the vessel unloading here, I went on board the 21st,
and the next morning coming on shore in the boat with some of the goods,
our captain`'s boy was coming along also;
but some of the privateer`'s men suspecting him of
taking some money belonging to some of our men,
left in the vessel, and could not be found, stopped him,
and in his going back over the waist of the sloop,
they saw the money tied up in his pocket.
This drew a suspicion on me also; so that as soon as I came on shore,
they ordered me to be searched in a room on shore, before the secretary;
but finding no money, nor any thing of theirs, nor any thing valuable,
they seemed a little ashamed of their treatment,
though a little of that goes far with them; but the officers seemed troubled.

On the 22d, in the afternoon, a papist priest, of the order of Jesuits,
being of the family of the Duke of Lorrain, came to the inn where I was.
This Jesuit and I had some discourse in Latin; in which,
though I had been long out of use of it, and his dialect and mine much differing,
we made a shift to understand one another pretty well;
and he being a master of the language, was a help to both.

Having a Latin Bible, Old and New Testament, by Beza, and an English concordance,
for I had my books and papers given me by the privateer`'s men,
I quoted several passages to him out of both;
showing Christ to be the true light that was promised as such,
as the object of faith in the first place, to the Gentiles,
and then as a sacrifice for their sins.

That though it was the same Christ offered to the Jews, yet under another administration,
viz: as born of the Virgin Mary, according to God`'s promise to them;
and that He is the "`true light which enlightens every man that cometh into the world.`"
All which he could not deny.

After this he began with their common notions about Peter, quoting Matt. 16:18,
where Christ says, Thou art Peter, and upon this rock will I build my church, etc.
That Peter, being the head of the church,
the popes of Rome had succeeded him until this day, and were in his place,
Christ`'s vicars here on earth, and ought to be regarded accordingly in all things.

To this I replied, "`It is true that our blessed Lord,
taking occasion to ask his disciples, '`Whom do men say that I the Son of Man am?`'
some said one thing, and some another, but Peter said,
'`Thou art Christ the Son of the living God;`' upon which Christ replied,
'`Blessed art thou Simon Bar-jona: for flesh and blood hath not revealed it unto thee,
but my Father which is in heaven.
And I say also unto thee, that thou art Peter;
(i.e. a rock) and upon this rock I will build my church;
and the gates of hell shall not prevail against it.`'
In all which I do not understand that Christ promised to build his church on Peter;
but on the Spirit, power and wisdom of the Father,
which opened and revealed that great and necessary truth to Peter.
For though his name signifies a stone, or rock, outwardly,
yet such a rock is too weak to bear so great a weight as the church of Christ;
but the power of the Father being almighty, his Spirit all-quickening,
and wisdom all-sufficient, the gates of hell, that is, the wisdom, council,
and power of hell--for here he alludes to the kings, elders, and people of the Jews,
who often held their political and warlike councils in
the gales of their cities -- shall not prevail;
but the counsel, wisdom, and power of God.
And Christ himself, being the wisdom, power, and Word of God,
the elect and precious stone, the head of the corner,
and binding-stone of all the building,
the apostle Paul does accordingly ascribe to him only the headship,
and calls him expressly the foundation, viz:
'`He is given to be head over all things to the church.`'
And, '`other foundation can no man lay than that which is already laid,
which is Jesus Christ.`'
But,`" continued I, "`if it had been true, that Peter had been that rock, head,
and foundation of the church, as we see he is not,
how did they prove that the popes of Rome had succeeded him in that station?
And who was Peter`'s successor, when there were two popes in Rome at one time,
both pretending to be Peter`'s successors?`"
This question I found was not grateful; and consisting of two parts,
he answered only to the latter, and that by another question, viz:
"`When king James and king William became competitors about the crown of England,
how did the people know which was in the right?`"
To this I replied, "`That though I understood his intent and drift by this question,
yet there was no parallel; for this was wholly a human affair, and men usually,
in such cases, follow the dictates of human understanding,
consulting chiefly their own safely and natural interest;
but in matters of religion and divine things, it is quite otherwise;
for good and truly religious men, following the example of Christ and his saints,
sacrifice all to the cause of religion, though contrary to human reasoning;
therein following the revelation, dictates, and openings of the Holy Spirit;
which is never wanting to the true and faithful in all such great cases,
as the head and foundation of the church of Christ, and his successors,
which are only they who follow Christ in a holy, innocent life.`"
All this the good old man, for so I thought he was, heard with great patience,
and without any show of anger; but made no reply to the matter,
only saying it was near mass-time, and he must attend,
and that we might have some further discourse another time; but I saw him no more,
though we tarried long enough there for it, if he had desired it.
For my part, as I had come off pretty safe after all this plainness,
for I had no fear of him, I had nothing in my mind to seek after him,
though I had several discourses with many others, who also knew a little Latin;
and all ended peaceably, these things being generally new to them.

In my discourse with the Jesuit, and frequently with others,
when I brought Scriptures home upon them, and against their sentiments, or for ours,
they told me, "`This Bible of yours is not truly rendered from the original languages;
there are many omissions and undue versions in it.`"
Then I desired one of theirs to compare them;
but could not get one among them all to do it.
For though they said that persons of any account among them might read the Scriptures,
being only prohibited to the ignorant and mean sort,
yet none of them could say they had any Scriptures,
but generally referred me to the father, viz: the Jesuit, for one; except once,
that one of them had a New Testament in Latin,
in which I could not observe any difference from mine,
though he was averse to compare them, having had it, as I suppose, from the Jesuit.

On the 23rd, being the seventh-day of the week, came Colonel Lawrens,
who was governor of the fort here, and of all the precincts; and at table,
taking notice of me, inquired more particularly after me and my circumstances,
and then gave me an invitation to his house, about two miles off, which I accepted.
He ordered me a horse next morning for that purpose when he came to town to mass.

That day, being the first of the week, as we were told by several of their own people,
both in Latin and English,
there being several that spoke English among the privateer`'s crew,
the above Jesuit made us, our principles and deportment, the whole subject of his sermon;
and said.
That we were an innocent, religious people, differing in many points,
both of doctrine and practice, from all other Protestants,
and seemed to have a right faith in Christ;
only we seemed too diffident concerning the saints, our duty to them, the church`'s power,
and the like.
But in the end, exhorted his people to keep firm in their own religion;
and as this people were thus cast among them,
to show their Christianity and respect to them.
And so they generally did, more than could have been expected; and several of them said,
though too lightly, the Quaker preacher had converted their minister.

In the evening I went with the governor to his house,
where I was very liberally and courteously entertained by him, and all his family,
who were free with me every way, behaving not as to a stranger, but a friend.
He was pleased with the relation I gave him of Pennsylvania, its settlement, name,
people, situation, and way of living, often wishing for peace,
that he might come and see it, hoping there might be trade between us.

His wishing there might be peace, occasioned a discourse between us about war,
and the cause of it; wherein I showed him,
that as Christ is the Prince of righteousness and peace,
so his kingdom differs from the kingdoms of men, being no worldly kingdom;
and as he had commanded his followers to love their enemies,
and thereby taken from them all cause of fighting, so he also said,
"`My kingdom is not of this world; for if my kingdom were of this world,
then would my servants fight; but my kingdom is not from hence.`"
And that the apostle also said, "`From whence come wars and fightings among you?
Come they not from hence,
even of your lusts that war in your members`'!`" To the truth of all this he assented,
but replied, "`That it was not they that desired the war,
for they were generally much hurt by it, but the king;
and that as God had set a king over them, they were bound in conscience to obey him,
who was answerable for all the evil, if any, and not they;
so that they ought to give active and passive obedience to all his commands,
whatever they were.`"
I then instanced Shadrach, Aleshach, and Abednego; who though in office under the king,
and loyal in their duty as officers in the civil state,
would not obey the king in any thing contrary to God.
Then he said.
That was a heathen king, and commanded idolatry; but theirs a Christian,
and gives only Christian commands, so ought to be obeyed.

I replied, "`That so far as his commands were Christian, they ought to be obeyed;
but we see he has commanded many things, which many of his subjects,
not thinking consistent with their duty to Christ, had disobeyed,
to the loss and sacrifice of many of their lives, and others had fled,
and many thousands of them in the Queen of Great Britain`'s dominions,
to the great depopulating and weakening of his kingdom.`"

All this he bore without any appearance of resentment;
and in the end owned that liberty of conscience is no unreasonable thing;
but seemed still to be tenacious of their way of passive obedience and non-resistance.

Here I tarried till the 28th, being the fifth-day of the week,
usually coming once a day to town will him;
and he several times told me I was not a prisoner, but a free man;
in the mean time lending me linen till my own small remnant--
for I had but two shirts and a little small linen--was washed;
which was done very neatly.
But the vessel intending to sail from hence to Port Francois on the 29th,
I went on board on the 28th, in the evening; and on the 29th,
being the sixth of the week, we set sail,
and turned up against the wind to the head of the Isle of Tortuga,
where we were almost run upon the great rocks with a fresh gale;
but escaping that danger, we soon after espied a sail right ahead, but far distant.
The privateer`'s crew being willing to hold what they had,
did not think fit to see what he was, but presently bore down right before the wind;
and so in a few hours arrived at anchor again at Port Paix,
and there we tarried three days: but they would not suffer us to go on shore again;
which I suppose was only to save charges, for they were so kind, that we lived as well,
or better than they;
and they and we were as friendly as if no ungrateful things had passed amongst us,
the only quarrel being our goods, of which having possessed themselves,
they had no enmity against us;
and we had so much grace from God as to be able to forgive them,
and power among them in the truth, as to reprove them for swearing and ill words,
and to argue with them even against their present ill employment.
Several of them would move their hats, and thank me for my admonitions;
and Augustine Cornelius, the lieutenant, who was by nation a Dane, as he said,
and spoke good English, having been formerly kidnapped when a boy, into Virginia,
would sometimes seriously say, that if he got safely home to Marlinico this time,
he would take up another way of living; but at other times he would talk wildly.
I had much discourse with him on various occasions,
and he seldom could resist the principles of truth when opened to him:
and many places of Scripture we examined on these occasions;
but sometimes when it came close, then he would say our Bible and theirs differed;
which notion, I perceive, is fatal to many of them, being all Roman Catholics.
However, I offered, as I had often done to the officers,
to write them a whole scheme of doctrine, according to our principles,
if they would procure me their own Bible; but could not have one:
and I found that what pains soever I might take that way,
it was all liable to this perversion, viz: It is not according to our Bible.
However, I drew up some heads about the light; that Christ is that light;
that he lightens all men, and is the same Word that was made, or assumed flesh, etc.,
which the Secretary, who understood Latin, casting his eye upon,
desired me to permit him to read it, promising to return it; but he did not,
and I saw it no more.

On the 1st of the sixth month we set sail again for Cape Francois, near night;
and the next morning were up with the head of Tortuga,
and so stood along till about three in the afternoon, when we espied another sail;
upon which we immediately tacked, and stood again for Port Paix.
But in about half an hour`'s time they perceiving it only to be a canoe, retacked,
and stood for the cape; where they arrived next morning, being in all fourteen leagues.
Soon after the sun appeared in the horizon we saw
another sail coming down upon us before the wind;
and though we were within half a league of the town, they were in much concern,
fearing it was an English privateer; and this place was more dangerous than all before,
the entrance into the haven being very critical, by reason of the shoals on each side;
so that their concern increased as the vessel approached, they having a sea breeze,
which brought them in, and we a land breeze, which kept us out.
We fired three guns for a pilot, but none came; at last the lieutenant of our vessel,
being bolder than the captain, ventured in:
and so we came safe to anchor before the town about nine in the morning.

At Cape Francois we found some difficulty in getting on shore;
which we did not till the next day, they still thinking I had gold about me;
and the lieutenant informing me of the people`'s conjectures, I told him very freely,
that it was unreasonable to keep us on board under that apprehension.
For as they had searched me twice before,
and I had been on shore so long at the other port,
it was not fair to trouble me any more; but that as I had told them the truth before,
rather than be detained on board, they might search me once more; but they did not;
and soon after let us go on shore.

The town is generally built of split cabbage trees, or palms;
it lies along the coast behind the cape; has a dry situation; is an oblong square;
the ends of the streets to the sea, and others running across,
after the manner of Philadelphia.
There were several Jesuits there, but I had no discourse with any of them.

The place is not healthy, by reason of their brackish water,
and in a few days I was taken ill of a violent fever; which, in one night`'s time,
caused a question in my mind, whether I might survive it?
But we finding out a widow`'s house, of Irish parents, called Margaret Connel,
she gave me the best entertainment she could;
and it pleased the Lord to restore me to my health very quickly:
but not having any means to clear myself of the effects of it in my blood,
it was of ill consequence to me after this.

Though we were not made prisoners at any time, but at liberty to go where we pleased,
their forts excepted,
yet we did not find the inhabitants of this port so courteous as the former:
for here we were left to shift for ourselves, our liberty excusing their allowance;
though some of them who had been prisoners with the English, were affable.

We found some Protestants, but incognito, among them;
and some who could speak a little English, would curse the Jesuits, saying,
"`We were free till these came among us;
but now we are taxed and spoiled to support them in idleness and luxury.`"
There is one great man there who has engrossed
all the meat and killing of cattle in town,
and none may do it besides; so that meat is scarce and very mean,
they not ordering it aright.
The governor and fathers--so they term their priests --must be first served,
then the other great ones, and the rest in order; and if any fast, it is the poor;
though in such forced fasts,
their prayers are anathemas against them that force their fast.
As with meat, so with fish on all their mock fast days, which are many;
the poor come last, and often fast in good earnest, not of choice, but necessity.

One day one of the Jesuits in his pontificals, with bells, cross, and such formalities,
passing along with many others, one of our company asking what they meant?
was answered, that there was a man in town very sick,
and the father was going to administer God unto him;--he meant the consecrated
bread they call the sacrament--and whilst the priest prayed within,
the people prayed, or seemed to pray, in the street, kneeling.

As we had occasion to pass the streets,
the people often viewed us with great seriousness, and seldom derided us.
I never saw any seem to do it but once, as I was passing along,
two young men coming out at a door, moved their hats;
and I not answering them in the like kind,
though I let them know I took notice of their intended civility,
some on the other side smiled, and told them I was a Quaker;
then they observed me more intently as I went along,
and some of them were not without a real respect.
I often had occasion to pass by the place of the Jesuits,
but they never seemed to take any notice.

We had little money, and fared but poorly; and yet had no want.
I often retired alone into a deep valley, a mile off the town,
where there were several springs and pools of water,
which I mixed with the juice of fresh times, there growing, and so drank it,
and eat some wild fruits I found there; and as often as I had occasion, washed my linen;
which necessity had taught me, though unused, to do indifferently well.
One day, buying a little loaf of bread, intending to eat it there, it proved very bad,
and though I ate but little of it, I was not so well as I had been before.

We stayed in this port about forty-five days, and were in a great strait what to do;
for it is rare to find any occasion of passage, or correspondence, to any other place,
save old France, or Martinico: the first was not our way; and besides,
it is rarely any occasion happens directly thither:
so that we were forced to solicit a passage in the same vessel we were taken in,
where we had already been fully weary of the very unsuitable conversation;
and it was not without some difficulty we obtained it for pay.

We sailed on the 17th of the seventh month; but they being all commanders,
and none to obey, when we were some way off at sea, on the 19th,
we returned near the same port for more fresh water, and next morning sailed again.
Reckoning their passage beforehand to be only about two weeks,
they proceeded accordingly; but when we were far from all land, and much time spent,
having had small winds, we were at last becalmed for about ten days together;
and our fresh provisions being nearly spent, and no prospect of proceeding on our voyage,
or of any relief, we came to allowance of water, being a quart in twenty-four hours;
which not being good at first, was now muddy and stinking,
and sometimes we found worms in it.

This was afflicting to all, especially to Mary Dickinson and me,
for she was delivered of a daughter at the Cape three days before we sailed,
and I was taken ill of a violent flux soon after I came on board; by which,
and want of suitable accommodations,
I was reduced to a weaker condition than at any time since I can remember.
But when they saw how ill I was, the captain, one Pickato, of Martinico, then commanding,
allowed me a sufficiency of claret and rusk, so long as he could spare it,
and what water I had occasion for, without limitation;
which I sometimes mixed with a little sour oat-meal, and sometimes infused orange-peel,
and drank it.

We had Cassava bread and Irish beef sufficient on board,
and had no want of such provision; but salt meat being against my distemper,
and too strong for my weak condition, my diet was mostly that bread and slinking water:
besides, my lying in the hold among the crew of blacks and whiles,
a mixed and nasty company of rude and blaspheming wretches,
where we could not sit upright, and close as a stove, in that hot climate,
was no small aggravation of my illness.
And besides,
I was forced by my distemper to rise five or six times commonly in the night,
and sometimes in the rain, and go upon the deck in the night air, out of that hot room;
so that at last I grew so weak I was not able to do it,
but lay upon the deck in the open air, and often wet with rain and the waves;
and at last my legs swelled so big, that the skin would scarcely hold,
with divers aggravating circumstances I forbear to add;
which had been far too hard for all my own strength,
if I had not been upheld and supported by the never-failing arm of the Lord;
who never left me wholly to myself in all my afflictions,
and in whose blessed visitations my soul rejoiced in
remembrance of some of my nearest and dearest friends,
who by this time had looked long for us, and were ready to give us over for lost;
and yet through the grace of God, I was fully resigned to his blessed will,
in dying or suffering, in death or life.

At length it pleased God to give us a fair wind, also a little to abate my distemper,
and we fell in between Antigua and Monlserrat,
with the French island Guada loupe right ahead;
and there they put in for fresh water and other refreshments.
On coming to an anchor, the governor of the island heard of us,
and sent us word that there was a flag of truce belonging to Antigua, then at Martinico,
which he expected at Guadaloupe in a few days,
and advised us to come on shore and stay for the flag; and so we did,
being extremely glad at this unexpected deliverance.

From the shore we went to an inn, I leaning on two of our men,
not being able to walk alone; and stayed about a week before the flag came,
and we were much refreshed, the people being kind.

The flag being come, commanded by Captain Birmingham, we made known our condition to him,
and he was very kind,
giving us considerable credit with the French for our passages and expenses;
and on the 26th of the eighth month we set sail for Antigua, by way of Montserrat,
and on the 29th, near night, arrived safe in the harbor.
That evening, being a little cheered in my spirits to meet with some Friends,
and again returned among our own nation, I went to Jonas Langford`'s,
where I was kindly and openly received and entertained,
and nothing omitted in order to my recovery,
being much overrun by this time with a scorbutic humor over my body, especially my legs;
from which both my good friend Jonas and his wife took great pains to recover me,
and with good success; though I got not fully clear for some time after.

+++[+++On the 8th of second month, 1710,
Thomas Story attended the first weekly meeting of the ministering Friends of
Philadelphia--it is therefore probable that he had arrived shortly before,
from this protracted, and in many respects, painful engagement.
The following minutes were made on the occasion, viz:

"`Our dear friend Thomas Story, being at this our meeting,
after his return from the West Indies,
reports that at Barbados the Friends that are left keep their integrity,
are living in the truth, and in pretty good unity.
Many flock to meetings and seem to be affected with the testimony of truth.
He had a pretty good time and service amongst them.

"`At Antigua there are but few Friends, and they are indifferently well for the present,
and many other people flock to the meetings and are quiet and seem affected.

"`At Jamaica there are but very few Friends, and truth at a very low ebb,
but there are some who keep their integrity.
Many other people came to the meetings at Port Royal,
and some were affected and tendered.`"

[.offset]
After his return home, there is a chasm of between four and five years in his journal,
of which time no account has been found among his papers.
In the year 1710 he buried his wife,
and was probably mostly employed in the duties
attached to the several public offices he filled,
until the year 1714, when he again found his mind religiously engaged to visit Barbados,
England, etc.; of which service he gives the following account, viz:]
