== Chapter XII

[.chapter-subtitle--blurb]
A Journal of a Second Visit to Barbados, etc. in the Year 1714.

On the 3rd of the second month, 1714,
under a suitable concern I set sail from Philadelphia in the Hope Galley, John Richmond,
commander, and that night arrived at Newcastle upon Delaware,
and next day being the first of the week, was at a meeting there;
where it pleased my great Lord and master to favor me
with his good presence and the consolation of it,
which I received as a testimony and confirmation
that he was pleased with that undertaking.

The winds standing southerly, and we being becalmed some days,
it was the 15th of the third month before we saw the island of Barbados,
and that evening landed at the Bridge,
where I met with a kind reception from my friends and some others of the inhabitants,
and took my lodgings at my dear friend John Grove`'s,
where I had been so kindly entertained in my former visit to that island.

On the 16th, being the first of the week, I was at the meeting in that town,
where divers sorts of people appeared, and some Jews, and all were generally sober;
and things well and comfortable.
On the 18th I was at another meeting there, where were many of the inhabitants,
and I found rather an increase of the testimony of truth; and things were plain and well,
truth being over the minds of the auditory in a general way,
and several broken and comforted.
On the 20th, being the fifth of the week, I was at the monthly meeting at the Bridge,
which was open and well, and my certificates were read there.

On the 23rd, the first of the week, I was again at the Bridge; the meeting was large,
and some Jews there, and things clear and well,
the Lord`'s power and presence being with us.

On the 29th we went with our friend Edward Harrison, to visit his mother, brother,
and sister, the two women being under some convincement; but his brother being a major,
and young, seemed not much apprehensive of the way of truth; but yet was courteous,
and made us very welcome.
My spirit was much comforted in a sense of the love and
visitation of God towards his mother and sister;
and my hearty desire and prayer to God was,
that they might embrace the merciful offers of the Lord,
whilst he was pleased to continue them; of which I was not without hopes,
considering how near they were to truth;
waiting at home in silence together for the Lord`'s teachings,
and in some measure then sensible of it.

On the 30th, in the evening, I went to Thomas Jackman`'s, and there rested that night;
and next day was at the meeting at that place, which was larger than before,
and pretty many strangers; the Lord affording his blessed presence,
and the testimony of truth coming pretty close home to several of them:
that evening I returned with John Grove to his house at the Bridge.

Next day was their six weeks`' meeting, where I was present;
but being rather a meeting of business,
and but few left in the island taking cognizance of the public affairs thereof,
it was very small.
The 1st of the fourth month was their week-day`'s meeting of course;
it was heavy in the forepart, but truth wrought through in some measure,
and I had comfort in it.

On the 4th I was at an appointed meeting about five miles from the town,
at the house of our friend Bridget Peirce;
which was for the most part made up of young people, and generally sober,
several being a little affected.

On the 6th, being the first of the week,
I was at another appointed meeting at Alice Thorpe`'s, which was larger than expected,
and things opened fully; and some were reached and touched with the power of truth.

On the 8th, being the third of the week, I went to the quarterly meeting at Spring,
which held till the filth of the week, inclusive:
it was very open and several of the gentry there, and generally satisfied.

On the 11th, being the sixth of the week, we went to our friend Mercy Evans`' house,
and thence to the Windward meeting on the first-day following; which, as usual,
was small and heavy, there being no constant meeting at that place;
Mercy Evans and Anne Gettings being the only Friends there;
whereas in time past there was a large meeting, and the house will hold some hundreds:
so great is the falling away there, as also in all parts of the island.

On the 30th we had an appointed meeting at James Clement`'s house, which was pretty full,
and a good meeting; things opening clear to general satisfaction.

[.offset]
+++[+++After attending several meetings as they came in course, he says:]

On the 2nd of the fifth month, being the sixth of the week,
we were at Speight`'s-town meeting,
where things came close upon such as despise the day of small things,
neglecting the plain language, plain apparel, etc.,
and such as basely equivocate about the priests`' dues,
and appear in arms on training days, and the like; which was of service,
as I heard since, some being guilty of all these things.

[.offset]
+++[+++Having been employed in attending meetings at the Bridge, Pumpkin-hill, the Thickets,
and at some private houses, he says:]

On the 6th +++[+++of the seventh month, 1714,]
I went up to the Thickets, accompanied with our friends Edward Harrison and John Oxley;
and on the 7th, 8th, and 9th, we were at the quarterly meeting there;
where were several great ones of the world, and truth was over most of them:
the meetings were well and comfortable,
though great heaviness usually attended in the beginning of them.

On the 9th, at night, I returned to the Bridge; where I stayed till the 22nd,
and had some private conference with one Acourt, an Episcopal priest,
who asserted that the church of England had power to work miracles;
and gave this instance, viz: "`That the Archbishop of Canterbury having this power,
as the rest of the bishops, and laying his hands upon the king or queen,
or anointing them, devolved that power on them.`"
This being an allegation I had never met with before,
my curiosity led me to ask some questions upon it.

1st; Which kind of miracles these were?

2nd; Whether that bishop and the rest of them,
could work the same miracles`'.`' But all I could find in this was curing;
of that distemper commonly called the king`'s evil;
which none of the king`'s bishops of England, I presume, will pretend to cure by miracle:
and then Nemo potest plus in alium transferre quam in sese habet, an rirtitaliter,
an formaliter: That is, What he hath not in himself he cannot transfer to another.
What mean shifts will men fly to in support of a bad cause!
For the question was, whether they were ministers of Christ?
He affirmed they were, and had their power by laying on of hands;
being the same power that the apostles had; and consequently, as he supposed,
were obliged to affirm working of miracles necessary to that calling.
He said also, "`That the church of Rome is a true church, though corrupt;
and that ministers made by the Pope and that clergy are true ministers:
that the church of Rome was calumniated, and not so bad as reported;
that they had excellent things among them;
and that our martyrs of the church of England had no need in
those days to insist so much on these points as they did;
but that many of them might have saved their lives by just
condescension;`" with more to this anti-protestant purpose.
To which I answered, that it was apparent which way they were driving;
but now God had been pleased to throw a block in their way,
which would stop their career: the news of the accession of King George I.,
having been come a little before this.

We touched also on baptism.
He alleged that the text in Mat.
xxviii., in the Greek, is most properly rendered, "`To baptize all nations,
teaching them,`" etc.
Putting baptism first, to answer their own usage of infant sprinkling, or rantism;
which being confuted by Edward Harrison,--being present at the
conference--I had no occasion to say any thing to the language,
but to note to my friend Acourt,
that such little shifts rather ruined than advanced their cause;
and that the due application of the element in the mode of baptism,
was to be regarded by all those who apprehend water to be meant,
as well as the proper subjects of baptism; in all which Christ was only sufficient,
and left nothing to be amended in any institution of his in his church,
by any successor or representative, or pretender of that kind.
I put him upon proving their practice, viz:
'`Whether Christ had at any time instituted sprinkling infants in the name of the Father,
Son, and Holy Ghost, signing them with the sign of the cross, with godfathers, etc.,
and obliging them to promise as they do;
and annex regeneration to this as a necessary consequence?`"
Which not being able to do by Scripture,
he fled to the power and tradition of the church in such cases;
which being only their own pretense, for what they please to impose in their way,
as the church of Rome in theirs, was justly rejected as unscriptural;
and so matters ended.

[.offset]
+++[+++He continued diligently engaged in the service of truth,
and near the close of his visit to the island, remarks:]

On the 24th I was at a meeting at Speights-town; it was small, but well in the end,
though heavy in the first part;
there being some unfaithful still in point of
sufferings on account of priests`' pay and training.
Here I stayed till the 26th, which being the first of the week,
the meeting was pretty large, in which were some Jews, to whose state things opened much,
and we had a good meeting; but the unfaithful were judged with great sharpness.
That evening I returned to the Bridge, where I stayed till the 17th of the eighth month,
which being the first of the week, and about to take leave of the island,
the meeting was large, open, and free,
and truth in full dominion to general satisfaction:
and as many of different persuasions had frequented the meetings during my abode there,
so divers expressed their concern at my departure;
and I parted with them all in peace and love,
leaving the end of all my labors among them to the Lord,
for whose sake I was so long there.

On the 20th, about four in the afternoon,
I took leave of the Friends there in lender and mutual love,
and immediately embarked on board the Bond frigate, Captain Peter Blackston commander,
for London.

After as good and comfortable a passage as could reasonably have been expected,
the time of year considered, the wind falling away,
we were becalmed about two in the morning, on the 25th of the ninth month;
and as soon as the day afforded a sufficiency of light,
we found ourselves to the north of the Landsend,
and between that and the isles of Scilly, and both in view;
and in the evening we got into the chops of the channel, but by reason of contrary winds,
landed not at London till the 6th of the tenth month.

The Lord having been with me to comfort me, and bear up my mind through divers exercises,
arising from weakness of body and the fatigues of my voyage through the great ocean,
his goodness continued with me, and tendered my heart after I arrived at this great city,
both in my retirements, and also in meetings; where I declined to appear in public,
as long as I could be still in peace, but suffered under the burden of the word of truth,
and a right concern in it, by reason of some forward spirits, who,
having accustomed themselves to talk of the things of God, in their own power and wills,
left me no room in some meetings to discharge my mind of those things incumbent upon me;
though Friends who had formerly known me were very kind,
and we were mutually comforted one in another, both in conversations and meetings;
the Lord`'s presence being gloriously with us in some meetings,
to the honor of his own holy name and our consolation.

As I returned to my native land in the drawings of the
love of God and the power of his holy commandment,
in the simplicity of the blessed truth,
I appeared as the Lord was pleased to make way for me,
being reconciled to God and to all men, and unengaged in their various feuds, strifes,
and emulations; which I found to be many.
On the 12th, being the first of the week, in the meeting at Grace-church-street,
in the morning, I prayed for the king, as my concern was at that season;
from which some made this remark, that I was no Jacobite,--a distinction now on foot,
it seems, among such as concern themselves in the states and kingdoms of men,
and are in emulation in their minds who shall rule, and who shall not--supposing me,
as I may collect from hence, to concern myself, as too many even among our ownselves,
unwisely do,
in the advancement of particular persons to the thrones and dignities of this world;
which I never look to be my business, but to leave it to God,
and pray for those he advances in the course of his providence,
that they may rule in righteousness and truth, and we be protected, relieved,
and defended by them, against all those who would oppress or injure us,
in things pertaining to this present world.

On the 15th, being the fourth-day of the week, accompanied by John Crouch,
with whom I lodged, I went to Ruscomb to visit William Penn and his family.
He was then under the effects of an apoplectic fit, which he had had some time before.
His memory was almost lost, and the use of his understanding suspended;
so that he was not so conversant as formerly, and yet as near the truth,
in the love of it, as before.
Herein appeared the great mercy and favor of God, who looks not as man looks: for though,
to some this accident might look like a judgment,
and no doubt his enemies so accounted it; yet it will bear quite another interpretation,
if it be considered how little time of rest he ever had
from the importunities and the affairs of others,
to the great hurt of his own, till this happened to him;
by which he was rendered incapable of all business,
and yet as sensible of the enjoyment of truth as at any time in his life.

When I went to the house I thought myself strong enough to see him in that condition,
but when I entered the room and perceived the great defect of his expressions,
for want of memory, it greatly bowed my spirit,
under a consideration of the uncertainly of all human qualifications,
and what the finest of men are soon reduced to.
Nevertheless, no insanity or lunacy at all appeared in his actions,
and his mind was in an innocent state,
as appeared by his very loving deportment to all that came near him:
and that he had still a good sense of truth was plain,
by some very clear sentences he spoke in the life and power of truth,
in an evening meeting we had there, wherein we were greatly comforted;
so that I was ready to think this was a sort of
sequestration of him from all the concerns of this life,
which so much oppressed him; not in judgment, but in mercy, that he might have rest,
and not be oppressed thereby to the end.

On the 18th, being the seventh of the week, I went to Reading,
and was at their meeting next day, which was a pretty good one.
That evening I returned to William Penn`'s, and on the third-day following to London;
where I stayed till the 6th of the first month, being the first of the week,
and was accompanied by several Friends to Winchmore-hill meeting,
which was large and well.
That night I went to Bush-hill, to Samuel Waldenfield`'s,
and tarried there for the advantage of the air, till the 9th,
and then went to the meeting at Hartford, which was not large, but comfortable and well.

On the 10th, being the fifth of the week, I went to Hitchin,
where I was at their weekday meeting, which was likewise small.
The occasion of my going into the north at this time was on account of my father,
who hearing of my being in Britain, had written earnestly for me to come to him,
he being then about the eighty-fourth year of his age,
had lost his sight and was ill of an asthma,
and very desirous to speak with me before he departed this life,
which he expected would be quickly; so that I took meetings as they fell in my way,
not appointing any: but here we had a fresh meeting,
and that of Baldock being the next day, I sent word thither of my intention to be there.

This meeting was a little larger, and was indifferently well;
only some were too much under a dull heavy spirit, of which I admonished them,
as greatly hindering the growth of all that give way to it.
I stayed the meeting on the first-day following, which was large and open,
and generally well satisfied, the love of Truth being with us, and things clear and well.

On the 16th, being the fourth of the week, I was at Hockslyme, near Aplegyse,
where the meeting was not large, and at least half not Friends;
but things opened pretty well, and we had a good meeting;
and that night I went on to Newport-Pagnal, and next day was at their meeting,
which was open, and some not of our communion were touched, and generally well satisfied,
the testimony being against covetousness, and a drowsy spirit.

That evening we had a large meeting at Sherrington, where most were strangers,
and many things being opened among them,
tending to convincement and faith in the divine light, all were very still,
attentive and solid, and I departed in peace.

On the 20th, being the first-day of the week, I was at Leicesier meeting, which was open,
large, and tender, and many strangers coming in,
several were pretty well affected with the testimony of Truth.

On the 22nd was at Nottingham meeting, which was attended in the forepart with a heavy,
drowsy spirit, which being overcome, the latter part was clear and free,
and some persons were broken and tendered, so that it was a good meeting.

On the 23rd I went to Mansfield meeting, which was small;
and though a drowsy spirit was too much over some,
yet it proved an open good meeting in the end,
and Friends were very loving and free after it.
I went that evening to Balber-Hall, to John Rhodes`'s,
where I was kindly received by him and his mother.
Here I stayed several days, and had good conversation with them,
being very open-minded and courteous, and of a good understanding in the things of God.
He was convinced when young, and held his integrity through many temptations;
but his circumstances differing from most among us in some respects, he lived unmarried,
having a great aversion to all that were wanton, light, or vain;
and though under some disadvantages in this world for the sake of Truth,
yet he stands steady and true, preferring the simplicity of Truth,
and the enjoyment of it, before all other things.

On the 27th, being the first of the week,
he went with me to the meeting at Hansworth Woodhouse, to which he belongs.
They are mostly young people, and some of them not much acquainted with Truth;
but though my exercise was a little laborious, yet we had a pretty good meeting,
and several were tendered.

On the 29th I went forward to Burton, and stayed that night there with Francis Harrison,
where I had great peace and comfort in the blessed Truth;
and where I had a secret opened to me by my dear Savior,
which my soul humbly desires of him may be recorded in me forevermore.
On the 31st attended Leeds meeting, which was very open and tender to many,
and a very good time.
Here I met with my old friend and companion Aaron Atkinson,
and we were glad one of another in the Truth; and Friends`' hearts being opened,
several came to see me after the meeting.

On the 3rd of second month, being the first of the week, I went on to Bentham meeting,
and on the 4th, in the morning, got to Kendal,
where I was at the yearly meeting of ministering Friends,
and had some time in public therein, which was acceptable, and I was easy and well.
The meeting was very large, but not so thoroughly seasoned as might have been,
by reason of the forwardness of some, which is too often the case of such meetings,
where those of least weight and service are often in the way,
obstructing the service of such as have the real concern,
and are better qualified for the work;
a distemper the church labors too much under in many places at this day,
and hath been of great hurt; but in the main we had a good meeting,
the Lord being near the faithful, and I having a little time therein one day,
was pretty easy.

The meeting ended on the 7th, being the fifth of the week,
and I went on to Penrith next day,
accompanied with my old friend and companion John Bowstead, who,
with many other Cumberland Friends of my acquaintance,
and others raised up since my departure, were come to the meeting;
and we were mutually glad of each other.

Next day had a meeting there, which was very small but lively;
and being refreshed in the Truth among them, on the 9th I went to Carlisle,
where I was kindly entertained,
and several of my old acquaintance came to see me with respect;
which they expressed as fully as I could receive in their way, and more.
Notice being had of my being at the meeting there the next day,
the curiosity of many drew them thither,
and things were indifferently well in the forenoon;
but there was a greater gathering in the afternoon, and greater openness,
and the Truth came over them in a good degree, and being much spent in the meeting,
I stayed there that night.

On the 11th I visited some old acquaintance,
and then went to Justice-town to visit my lather, who was very aged, and without sight,
but exceedingly glad of my arrival, and very kind.
Here I stayed till the 13th, and then went to the meeting at Solport,
which was not very large, being their seed-time, but indifferently well.
On the 14th I went to see my sister at Kingfield, and stayed one night there,
and then returned to Justice-town to my father,
and there stayed till the first-day morning, and then went to Kirklinton meeting,
which was large, but not so open as I could have desired,
the expectation of the people being too much outward.

On the 23rd I took leave of my father in great tenderness,
who was much troubled to part with me; but having overcome that difficulty,
I went that afternoon to Carlisle.

On the 24th, being the first-day of the week, I went to Wigton.
At this place lived William Robinson and his brother John, who,
with Job Pearson and his brother Lot, and some others, their wicked accomplices,
were the most violent opposers of us in our meetings that have ever yet appeared;
occasioned by their being denied for their ill behavior,
and contentious and imperious spirits,
as appears by the minutes of the monthly and quarterly meeting against them.

The meeting was large, there being Friends from divers parts, but not fully gathered,
when John Robinson and his wife began in the meeting, with hideous noises,
and false accusations against Friends in general, to make great disturbance;
accusing me also as a persecutor, like Bonner, before I said any thing in the meeting,
the woman being altogether a stranger to me,
and I had been but little acquainted with the man,
and not seen him for about twenty years;
but their implacable rage is against the divine Truth and all that dwell therein,
and I had only at this time a taste of what Friends there and elsewhere,
have endured from these wicked people.

Henry Atkinson stood up first to speak, and at the same time, close crowding by him,
stood this woman, the most hardened and impudent of any I ever saw.
As soon as he began, she set up her noise, which was very loud;
and in the same time he uttered every sentence, she also uttered these words,
Persecuting Quakers, with some others at some times,
containing reproaches against some of the magistrates by name;
so that much of what he said could not be heard.
When he had done I stood up, and though I had not given her the least provocation,
she served me the same way; but my voice being stronger than hers,
and finding out the time she kept in her words, I spoke in the intervals of hers,
and so disappointed her in some degree, being rather better heard than Henry.
For all their design was, to vex and grieve us in our meetings,
so as that our minds might not be exercised in the virtue of Truth,
and to drown our voices, that the people might not hear.
Thus she continued during the greatest part of the meeting; but when she ceased,
then her husband began to prate, pervert Scripture,
and utter many false accusations against us,
which usually he did in times of our silence, having but a low voice.

Richard Wait praying towards the conclusion of the meeting,
she roared out aloud all the time, in the same strain of wicked language as before;
but notwithstanding all the rage of Satan, in these his instruments,
the Lord`'s blessed presence was with us, and in the main we had a good meeting.

In the afternoon the meeting being gathered, was very large,
and more people of the world there,
and she acted the same part against Henry Atkinson and me; but my voice, and his also,
being above her, and Truth over the meeting, her voice was little minded,
so that in the main the Lord gave us a comfortable meeting,
and honored us with his holy presence, to the great rage and torment of these people.
After I had done I gave the people an account of them, and why they were thus enraged,
saying,
"`That all the various sects and professors of Christ in the
world had certain and respective rules of discipline,
and terms of communion, that all their several members were subject to,
whilst of that communion or sect; which rules, or terms, being transgressed by any,
whilst of the profession, such transgressor was dealt with,
and proceeded against according to their known and stated rules; but,
persisting in the offense, was denied communion until reformed.

"`That Christ had commanded, that if a brother offends,
tell him of it between him and thee; and if he hear thee, (that is,
leave off the thing offending) thou hast gained thy brother;`'
gaining him being the true end of dealing with him:
'`If he hear thee not, (if he persist in his offense) then take one or two more with thee,
that in the mouths of two or three witnesses every word may be established;
and if he will not hear them, tell the church; and if he will not hear the church,
then let him be unto thee as a heathen man, and a publican.`'
That is, to deny him Christian or religious communion, which, by some,
is called excommunication.

"`Now, we have our monthly, quarterly, and yearly meetings,
in which we negotiate all the affairs of our community, as touching the poor,
the discipline, the Christian rule and order of our society;
that all may be preserved in a due decorum and deportment,
in all things becoming our holy Christian profession: that nothing immoral, uncivil,
or unrighteous, or of evil report, or tendency, may lake place among us:
and these men maintaining practices which some were offended at,
have been proceeded against according to our said method;
and persisting in their offenses, we have seen cause to deny them communion,
as not being of the same spirit and practice with us.
This excommunication extends neither to life, limb, liberty, property, or good name,
other than as the matters of fact they have done are disreputable in their own nature;
yet the evil spirit that rules in them, is so enraged, and they by it, that they have,
from time to time ever since, behaved themselves in this violent and wicked manner,
as you have this day observed, and abundantly worse at many times and places.
All this was borne for some years with great patience,
till our peaceable meetings were not only by their
means turned into stages of contention and disturbance,
but great violence done by them to many of us, especially our ministers,
in the time of their ministry; by which their health hath been impaired,
and even their lives, by consequence, endangered,
till the civil magistrate taking cognizance of them,
exerted his just authority for their suppression,
and security of our persons from their violence,
to which we have right with all other subjects of the kingdom, as members of it;
upon which these aggressors bawl out Persecution, persecution, as you have now heard,
though they themselves are the only persecutors in all these things.

"`Now observe, if this were the case of the church of England, or Presbyterians,
or Papists, or Baptists, to be thus used by persons excommunicated by them respectively,
how would it relish to any of them?
Would they think themselves obliged to sit still under such violences,
without any regard to the civil peace of mankind,
thus invaded on the most solemn occasion?
I do not believe they would.
Why then should we, who are equally privileged to the protection of the civil magistrate,
who is ordained of God as a terror to evil doers, and a praise to them that do well?
I think no rational considerate person can blame us, if we have, or yet should,
excite the magistrates against all such,
notwithstanding any unjust clamor of persecution against them and us for so doing,
since these people`'s cessation from violence will release them,
whenever they think proper to be quiet.`"

That evening I went to Lawrence-Holm,
and lodged with my honorable friend Robert Atkinson,
a clear and faithful minister of the gospel of peace,
and a great sufferer on account of tithes, and accompanied by him the next day,
I went to Holm meeting, which was not large,
but a good open time the Lord gave us together.

On the 27th I was at the meeting at Allanby, which was small, but very fresh and open,
and on the 28th I was at Pardsay-Crag meeting, which was in the main, a good meeting.

That night I went with James Dickinson, who was lately returned from North America,
from a visit to Friends in those parts.
On the 29th we went together to Broughton, where the meeting was but small,
but enlarged in the enjoyment of life; for it was very open, and things clear and well.

On the 1st of the third month, being the first of the week, I was at Cockermouth,
where the meeting was large, and pretty well,
there being a great mixture and variety of spirits and states, but in the main,
well in the forenoon, and better in the afternoon.
On the 2nd I went to Whitehaven, and on the 3rd to the meeting at Westside,
about three miles from Whitehaven, where came John Gilpin, his wife,
their Presbyterian minister, (Thomas Dixon) Justice Gilpin`'s eldest son,
a very discreet youth, and several others of that sort,
and also of the church of England.
And though I had at that time a great cold upon me,
and my voice more affected thereby than in all my life before, yet things opened clear,
and I was intelligible to them, and much better as I proceeded in my exercise;
and it was a pretty good meeting.
We all returned that evening to Whitehaven; but I had a sense upon my mind,
that the Presbyterian minister was not pleased with some things,
though he had been very quiet in the meeting, and said nothing.
The points I had most in hand were freedom from sin in this life, the necessity of it,
and baptism; setting forth the general fall of man, and redemption by Christ,
offered to all in the grace of God come upon all through him;
and also the baptism of the Spirit, as the only true, permanent, and saving baptism;
and that since every apostle of Christ had every
qualification necessary to so great a work,
without any dependence on any other in any part of his ministry;
and as the great apostle Paul was not one whit behind the chief of them,
and sent in a more especial manner to our forefathers, the Gentiles,
and exercised his ministry where Christ had not once been named,
yet this great apostle confesseth Christ sent him not to that work of water baptism;
by which it appears it was not necessary, or any part of the gospel dispensation.
And since he, the first great minister, thus peculiarly sent to them,
had no authority from Christ to baptize with water,
no man could succeed him in what he had not himself.
And therefore all pretenses of that kind at this day are vain and groundless;
with many Scriptures to the same purpose.

On the 4th I appointed a meeting at John Nicholson`'s about a mile from Whitehaven,
where went John Gilpin, his wife and servants.
Justice Gilpin`'s daughter, and some of their servants, and many people from the town,
so that there was a large meeting, and most of them not of our communion;
and a good meeting it was, Truth being over them, and things largely and clearly opened;
so that I did not hear of any objection.

On the 6th arrived at Broughton-Tower, at the willow Anne Sawrey`'s,
sister to John Gilpin, and an old acquaintance; but being long absent,
she did not know me for some time, but was courteous, and when known, very respectful.
I stayed two nights, and had some discourse with the family on several points, as baptism,
the supper, inspiration, the maintenance of ministers, etc.
She was an ingenuous and wise woman, and her two sons, young men, very sober and hopeful,
and her daughter also.
I left them all with much affection and respect.

On the 8th, being the first of the week, I went to Swarthmore meeting,
which was pretty large and open; to Hawkside meeting on the 10th,
which was very open and well; and on the 11th to the meeting at Height,
which was also very open and tender.

[.offset]
+++[+++After several other meetings he says:]

On the 20th, being the sixth of the week, we had a large meeting at Wolverhampton;
notice being given privately, that there was a stranger from America,
and rumor magnifying me above what I was,
raised a curiosity in many both to see and hear me,
so that the place was crowded with persons of some rank not of our communion,
and the Lord was pleased to condescend to them, so as to open some great things,
in a degree of power and light, satisfactory to most,
which some of them were heard to declare as they passed the streets;
and Friends also were pleased and comforted.

The day following we went on to Birmingham, and lodged with John Pemberton,
where we were courteously entertained, and the next day had two meetings there:
that in the morning consisted mostly of Friends, and was pretty open,
but Truth appeared in majesty and dominion; and in the afternoon,
things were largely and clearly opened, in the wisdom and dominion of the power of Truth,
and many strangers being there, were generally brought under,
and the hearts of Friends very open.

On the 28th, being the seventh of the week,
we proceeded to Oxford and lodged with Thomas Nichols, jun.,
and that afternoon went to most of the colleges in the city,
and viewed the buildings and gardens, which, in their kinds, are pleasant and commodious;
but that very great load and power of darkness which I felt (not the like in all
South Britain) was so much an overbalance to any satisfaction I had therein,
that I think I shall never see them any more.
And this power soon after showed itself by its fruits;
for in the evening a great mob of the scholars and
others attacked the Presbyterian meetinghouse,
and broke all the windows, doors, benches, wainscots and seats, carrying them away,
and burning and destroying them, which made a great uproar in the city.

On the 29th I was there at the meeting, which, in the forenoon, was not large;
several scholars and others came, but did not make any great disturbance.
Friends having heard that they intended to use our
meetinghouse as they had done that of the Presbyterians,
an advertisement thereof in writing was drawn up, directed to the mayor,
and sent by a Friend; but the mayor being absent at the time,
it was left with his servant.

In the afternoon the meeting was large, and many of the scholars were there:
a few came at first, and some of them wearied in the time of silence, but others stayed.
After I had spoken a while, more came, and many things were opened to them,
which seemed to reach their understandings.
Other people of some fashion in the world came also,
and all were very civil and quiet to the end of the meeting,
the scholars taking off their caps in the time of prayer.
The meeting was very comfortable, and of good service.
After the service was over, they not being hasty to depart, I said,
"`That I had seen several colleges and scholars in divers parts of the world,
and much rudeness among some of them;
but as civility becomes all men of learning and wisdom,
so their deportment that day had engaged my good opinion of them.`"
But I knew the Truth was at that time over most of them, and kept them quiet.

After the meeting we returned to our quarters, and about nine in the evening,
hearing a great noise of the mob at a distance,
we soon had an account that they were using our meeting-house
as they had done that of the Presbyterians the night before.
They broke in by violence, and took away all the forms and seats that were loose,
and such as were fast round the house they broke and defaced.
They took the doors also off the hinges, and burnt them, with part of the wainscot,
in their bonfire.
They broke also all the windows and stanchers;
and the room next the meeting-house they also abused and defaced,
so that the whole was ruined and destroyed, except the walls and tiling.
Yet all this did not cool their rage;
for they broke into the dwelling house of our ancient friend Thomas Nichols`'s daughter,
then a widow, where Thomas also was, and broke the windows,
and threw in some hundred weight of stones and dirt, covering the beds therewith,
breaking several things in the rooms, and also shedding some blood.
From thence they went to the Baptists`' meeting-house, and gutted that also,
as their term is.
I lodging with young Thomas Nichols,
we expected the same usage as his sister had mot with; but as they came up to the house,
they let fly their volley and broke all the windows,
and so went along without doing us any further harm.
But this I observed, that as Satan raged in them,
Truth moved in our minds with divine love,
and filled us with heavenly consolation and life,
so that we were without any fear of what they could do further.

The next morning we went to see the ruins of our meeting-house,
and that of our friend Nichols`'; and as we were at the former,
I stood upon a small eminence, and looking over the place,
many scholars and people being there, said pretty loud, so that they might all hear,
"`Can these be the effects of religion and learning!`" upon
which several of the scholars hung down their heads,
but none answered.
Then young Thomas Nichols made a short speech, but very close,
putting them in mind of Sodom and Gomorrah;
and that this was the same evil spirit which wrought in that wicked generation,
upon whom came destruction; and that if they continued in such evils,
the same just God might bring like condign punishment upon them.
To which they made no reply, but that the mob had done it, and it was illy done,
so would have excused themselves; but some others said, they themselves were that mob,
and would be met with one day.
After some time we returned to our friend`'s house, and so departed that wicked place.
This is one of the blind eyes of this poor nation!
This is one of the filthy fountains of their religion and learning,
from whence the whole land is poisoned and undone.
Can sweet and bitter waters issue from the same place?
Or can religion flow from hence to the nation,
where the life of religion is so remote from these vain pretenders?
And what learning can they have, who are destitute of all principles of civil behavior?

That night we went to Richard Richardson`'s, near Uxbridge, and on the 31st to London,
being about a week before the yearly meeting, which, in the main,
was much more comfortable, through the great mercy of God, than many expected.
The affirmation, from the beginning of it, had occasioned much disturbance in the church,
some being for, and some against it;
and these divisions had ever been very oppressive to my spirit,
knowing nothing could hurt us more than they,
or give Satan or evil men more advantage against us.
But though I never liked the Act,
yet I ever kept true charity to those Friends who were for it,
believing they saw no hurt in it, though I thought I did;
and at my coming over to London, I labored among them,
to regain and keep a right temper one towards another;
and as they talked of a further solicitation concerning it,
the late Act being ready to expire,
I advised several leading men on both sides to
proceed in one joint interest as one people.
For though we could not all agree about the definition of an oath,
or in what relation the affirmation stood to an oath, yet we all were as one man still,
that an oath is not consistent with Christ`'s doctrine;
and accordingly they did both solicit for a plain affirmation,
without the sacred name at all.
But that could not be obtained; all that the Parliament would do,
was to perpetuate the former, adding some clauses for the levying of tithes.
When this came to be discoursed in the meeting,
the minds of some on both sides being healed, things were likely to run high;
but the Lord was near, and by his blessed wisdom and power, preserved us in unity.
Some few of those who were for the affirmation inclined to have it established overall,
as the testimony of Truth, by the yearly meeting; and some others on the other side,
were resolved to reject it, and testify against it, as short of the testimony of Truth.
But seeing the tendency of such a division, I and some others labored for peace;
and with much long-suffering, patience, and labor in the love and wisdom of Truth,
and as he opened and made way, things came at last to this good issue,
that such as could take the affirmation,
might have the benefit of it without censure of their brethren,
and such as could not take it, should not be reproached by them;
but that the meeting for Sufferings should continue their care and solicitations,
together with the dissatisfied, for further ease in that point, at a fit season.
With this conclusion both sides were at last easy,
and the meeting ended in more peace and brotherly kindness than for some years before,
and to more general satisfaction; for which my soul was truly thankful, with many more.

The meeting being thus well over,
on the 17th of the fourth month I went with some Friends from London to Braintree;
and on the 19th, being the first of the week, was at their meeting,
both forenoon and afternoon.
The meetings were large, and filled with strangers, who were generally satisfied.

On the 20th I went to Colchester, to the quarterly meeting,
and the third and fourth-days being their yearly meeting,
the Lord gave us a comfortable time,
setting his blessed Truth and its living testimony over all.

On the 22nd, being the fourth of the week, I went to Edmundsbury,
and on the 23rd was at their meeting, which was very dry and barren,
but yet had some service and comfort.

On the 27th we went together to the quarterly meeting at Norwich,
and on the two days following was their yearly meeting, which was very large,
especially the last day; when came abundance of people of all sorts,
and things were full and plain.
The more particular matters wherein I was concerned, being about the kingdom of Christ,
the kingdoms of men, and the kingdom of antichrist, with his priestcraft and fallacy,
which reached many understandings, and affected the people as well as Friends;
and Truth gained among them to our mutual comfort.

On the 3rd of the fifth month, being the first of the week,
I was at a general meeting at Titsil, which was large,
and many of the world`'s people there, and Truth shined over all.
In this meeting I had an opening concerning that
creed commonly called the Apostles`' Creed,
and took some exceptions to some terms of it, viz: Christ`'s descending into hell,
and the holy Catholic church, as they call it;
the former importing more than the state of the dead,
and the latter showing plainly what church, and not the apostles, was the author of it.

On the 4th I went back to Norwich, and on the day following, went by water, to Yarmouth,
expecting a vessel to sail next day for Holland, in which I intended to go;
but the wind proving contrary, we appointed a meeting at Yarmouth.
There came many of the people, and a loose, airy company generally they were,
though some sober persons were among them, and in the main things were well.

On the 11th, being the second-day of the week, I went back to Yarmouth;
but the wind proving contrary again, we had another meeting there on the 12th,
which was far larger than before, but some of the people more rude,
and yet in the main it was a good meeting, several being tender,
and many brought down under a sense of the weight of Truth.

I remained at Yarmouth till the 17th of the fifth month, being the first-day of the week,
and the people being generally at their own worship, and no notice of my being there,
the meeting was more select, and much quieter and more comfortable,
the Lord being with us, and a few sober people also well satisfied who sat with us.
The afternoon meeting being ended, the wind came fair,
and I went on board the vessel about six in the evening.
