== Chapter 14

On the 4th I went to their meeting at Monallen, which was open and free,
and several strangers reached by the power of Truth, and broken, and it was a good time.
On the 7th, being the first of the week, I was at the meeting at Grange, by Charlemount,
which was an open good meeting;
after which I was as easy and as much comforted as at any hitherto in Ireland.
I had a long time in it, and many things were fully and clearly opened.
One was concerning such teachers and priests as pretend
to have power by the text in Matthew 28:19,
to teach and baptize all nations,
and yet sit down at the first parish or town where they can have a presentation,
or make a bargain for so much a year, and never go into half,
or a thousandth part of their own nation, and baptize nobody,
for sprinkling is no baptism; it is neither dipping, washing, nor wading into water,
nor are infants subjects of baptism.
Besides, the apostles themselves, who had the immediate command of Christ,
who has all power in heaven and earth,
by whom these priests and teachers pretend to derive their authority
successively as they were not to proceed upon that command barely,
without actual power by the Spirit; so none else can have power but by the same Spirit.
Since then these have not the Spirit, by their own confession,
they have no power from God; but through covetousness,
and as mercenary hirelings for bread, run when they are not sent, and do not profit,
but deceive the people; who, nevertheless, loving to have it so, the buyers and sellers,
as in the parable of the ten virgins, are excluded together, etc.

On the 13th, the seventh of the week, was their province meeting,
being for worship in the forenoon, and business in the after.
It was large and open, and I had some time after the meeting for business,
which was very satisfactory to all,
being something of my own experience in my convincement,
and the satisfaction I had in secret in these meetings for business,
before I found myself at all qualified to meddle in them,
which was not till my peace began to lessen, by reason of my aversion and neglect.
For if I could always have had peace, and the enjoyment of the good presence of the Lord,
without either preaching,
or answering the concerns incumbent on me from him in
matters of discipline and affairs of the church,
I had much rather never have meddled in them,
observing the tempers of some men professing Truth,
and what spirits they are of that are for the most part to be dealt with in it.
Though the discipline now in use in the church is of God,
through the openings of his wisdom, and dictates of his Spirit;
yet it may be said now of discipline, as Paul, personating that state, said of the law;
the law is spiritual, holy, righteous, just, and good, "`but I am carnal,
sold under sin.`"
The discipline is settled to great and glorious ends;
but as Satan regards not what be the law, if he can be judge to pervert it,
so even in this age, the mystery of iniquity has so wrought,
as that ungodly men in some places have advanced themselves into the seat of judgment,
whose spirits and ways are for judgment and condemnation; who, by that means,
being unseen of some, and awing others, turn the edge of judgment backwards,
and pervert right, put truth for error, and error for Truth;
which being the highest abomination and indignity to the Lord, he will shortly arise,
to the discovery and overthrow of all such, with their evil work throughout the world.
Until that day come, as a few are easier brought to a settlement,
through debatable points, than a multitude; so,
when things are fully settled in the church that now is, whilst but few;
such as shall be added,
will sooner fall in with what is established before their coming in,
than if they were to be settled after.
And this is one great cause why the Lord delays
bringing in the great multitude yet to be gathered.

On the 14th the meeting was large, and I had a full time in the forenoon,
many things being opened to general satisfaction, though there were many strangers,
as well Episcopalians and Presbyterians, as Papists.
In the afternoon many more strangers appeared there,
so that the evening meeting was almost as large as that in the morning,
and the blessed Truth reigned over all, to the praise of his own name,
of whom is the power, and to him be the glory from every baptized soul, now and forever.

The province meeting at Lurgan being over, on the 15th I proceeded to Alexander Seton`'s,
and the day following had a meeting at Ballinahinch,
a village where there is no settled meeting,
but had it at an inn kept by an Episcopalian,
though the people are generally Presbyterians.
Having great peace and comfort in the Truth after this meeting,
we went that evening to Downpatrick, and lodged with our Friend John Beck,
he and his family being all the Friends that were in town.
Next day we had a meeting there, which was pretty large and open.

On the 18th we had a meeting at Rathfriland, and the people having notice,
seemed inclinable to come; but the Presbyterian priest, one Robert Gordon,
and Robert Little, one of his elders, went about to forbid their party,
and hindered them generally from coming to the meeting;
they two standing in the street to that end,
their sect not daring to go to meeting in their sight.
But their envy extended further than this; for after we were set down in the meeting,
there came a great company of boys and made a noise near the door;
but being discouraged by some Friends who went out to that end, then they threw dirt,
stones and turf, and disturbed the meeting that way,
several of that sect of envy looking on and abetting them.
Our peace nevertheless remained in us, and we were comforted in him +++[+++the Lord],
After a while John Turner, of Lurgan, with some other Friends, went out into the street,
there being many people in the shops and houses, as near the meeting as they could;
and I went after him, having the same thing also in my mind.
We stood by the end of a house which had a view several ways,
and there preached to them a pretty while;
and by the time he had done we had a far greater
auditory than the meeting place could have contained.
After him I stood up, and then the Friends came to us out of the meeting,
and I had a full time among them.
But all the time we spoke, the boys made a noise, and threw stones, dirt, and turfs;
and though sometimes some of the people would reprove them, and drive them off,
yet others gave countenance, and encouraged them; and some others, who,
by the distance they stood, must have been stronger than boys,
threw turf and some stones amongst us over a house, standing out of sight behind it,
most part of the time; one stone struck me on the right breast, but did little harm:
the Lord preserved us from their violence,
so as no great harm was sustained by any of us.

This being over, having had a full and open time among them, we retired to the meeting,
where some of the people came, and we had some time there.
But the work of that spirit of envy in these Presbyterians was not yet at an end;
for they renewed their disturbance, and one fellow came into the meeting with water,
and in a scoffing manner said, "`The preacher must needs be very dry by much speaking,
here is water for him;`" and seemed to intend to
throw it among us by some motion he made;
but a person in the meeting turned him out, and some boys also that were with him,
and at last things ended peaceably, and we were generally comforted.
One thing I think fit to mention here,
which was with me to say to the multitude in the street, viz:
"`That it could not be childish behavior only in
those children who scoffed at the prophet of old,
that provoked the great and merciful God to bring, or suffer,
that destruction upon them by a she-bear out of the woods; but as, without all doubt,
they had been taught and countenanced by their parents,
they were punished in their children.
So, in like manner, we impute not this to them only, but to those that set them on,
and abet them, being well apprized of the root of this evil treatment,
wherein those miserable parents and abettors are but laying in
their children a foundation of a more dreadful destruction;
for being thus debauched in their very infancy,
and improving therein as they increase in years, their end must needs be miserable.`"

The day`'s work being over, we went to the inn to refresh ourselves,
and then going out of the town, the rabble of boys followed, stoning us, and saying,
"`We will drive them out of the town like dogs.`"
I rode back till I met with some of the inhabitants,
and told them we understood the meaning of all that, and where to place it;
not only on those poor children, who were thus depraved,
and ruined by their wicked leaders and abettors,
but were certainly informed that their Presbyterian
priest and their elder had hired them,
by giving them money for that evil service,
and therefore they must answer for it in time.
The priest being at his door as we were riding that way,
I intended to speak with him on that subject, but seeing me,
he slunk away into the house,
and in a minute`'s time they in the house said he was not within,
though I was at the door by the time he got out of it.
I made this observation on these Presbyterian people in the north of Ireland,
that as their party in Scotland exercise their
church tyranny there over all not of their way,
many of the teachers of that sect in Ireland, either coming from Scotland,
or having their education there, through pride and a self-exalting, domineering spirit,
forget that they are in another nation where they
themselves are but dissenters as well as we,
and begin to exercise the same cruelties which they do at home,
and would do everywhere if they had power.
But as there is nothing wanting to the blind leaders of that unhappy people but power,
to make the nations once more swim in blood,
so I hope the merciful God has a more favorable aspect upon the poor
deceived inhabitants than to gratify their lusts therein,
or give power any more to such, who, when invested with it, used it so illy;
exercising the anti-christian cruelty of their religion and tempers,
upon such whom the grace of God had taught to fear him, and deny their wicked ways.

That night we went forward to Newry, and lodged at an inn;
and desiring to have a meeting, the landlord, who was also seneschal of the town,
readily accommodated us with a long malt-house, which being made ready in the morning,
some hundreds of people of several sorts came, many of them Presbyterians;
and we had a very open good meeting, the people being generally sober and satisfied,
which gives me occasion to remember that true saying,
"`The leaders of the people cause them to err.`"
For in the place above,
where they were under the eye and influence of their priest and leader,
they were full of fury and ill-nature; but here, where they had not such an abettor,
they behaved like other sober people.

That evening, the 19th, we passed the mountains, and came within night to Dundalk,
and lodged at an inn, William Sewel landlord.
A little after we were alighted, having a mind to have a meeting,
I inquired of him where a place might be had for that purpose,
and he immediately proffered his own house, which was a new building,
and not a small one.
Expecting a pretty large gathering,
no meeting having been there or at Newry for many years,
we tried to have had the courthouse; but one putting it off to another,
we found the magistrates were not willing, and so we prepared the inn next morning,
being the seventh of the week.
The meeting gathered about the tenth hour,
and was as large as several rooms together could accommodate, and many in entries,
stairs and other places, a great concourse of divers sects, and many Papists.
Things opened very suitably to them, and the meeting was to general satisfaction,
the tendency of what was delivered being mostly
to their convincement of the principles of Truth.

On the 21st, in the morning we went to Drogheda,
where there is a small meeting of Friends; but the notice being short, it was very small,
and but a dull time, till some people without, hearing me speak, came in,
and then things quickened a little, and the meeting ended pretty well.
We went that night to Dublin, where I remained till the 29th, and then went to Timaho,
and on the 30th had a meeting there.
The 31st being the meeting day at Edenderry, I went thither.
It was pretty large and open, and the next day, being the 1st of the ninth month,
Thomas Wilson, with some other Friends, went with me to a meeting at John Stephenson`'s,
which was an open, good season; for the Lord comforted us together.

On the 2nd we went to Ballytore, where we had a free open meeting.
On the 4th, being the first-day of the week,
I went to the province meeting at Castledermont, which held that day and the next.
It was a large good meeting; and thither came also George Gibson and Edmund Peckover,
from Norfolk.
On the second-day evening we went back to Ballytore.

On the 6th we had a meeting at Stephen Wilcox`'s, a Friend`'s house,
in three rooms opened together; and being mostly strangers, and the meeting pretty large,
things opened accordingly for convincement, and we had a pretty good time among them,
George Gibson and Edmund Peckover being also there.

On the 7th we returned to Dublin,
the half-year`'s national meeting beginning the day following.
The affairs of it were carried on with great ease and unity, and much sweetness,
which gave me, and some other strangers, occasion to remark, that it were happy,
and greatly to the benefit and growth of the church,
if the affairs of the yearly meeting at London could be so unanimous and peaceable;
which could not well be expected till some men are removed, and others regulated,
who have crept in unawares under the wings of others,
who were never true members of the living body,
or ever qualified for the stations they have assumed by the
connivance of such as ought to have been more vigilant,
and kept them at a due distance.

Finding an openness at Dublin, and many people of divers sorts frequenting our meetings,
especially in the afternoons, I stayed there till the 20th of the tenth month,
where I had services of several kinds.
And being fully recovered, for I was a little out of order of a cold,
I went to Ballytore, Amos Strettle and some other Friends being with me.

On the 21st we had a meeting there, which was not very large, but pretty open.
On the 22nd, being the seventh of the week, we went to the province meeting at Carlow,
which held that day and the following, and was a good open meeting,
and many strangers there on the first-day, and matters opened suitable to them,
and things ended to general satisfaction.

On the 24th I went to Samuel Watson`'s, at Kilconnermore,
and the next day had a meeting there, being the third of the week,
and that day supposed to be the nativity of Christ, commonly called Christmas.
There were pretty many strangers in the meeting, and the Lord was with us,
to the comfort of Friends.
In this meeting it was upon me to set forth the Word of God made flesh,
or appearing in flesh, born of the Virgin Mary, sent to the Jews in that manifestation,
according to the foreknowledge, purpose, and promise of God; but they,
save a remnant of them, rejected and crucified him,
and yet at the same time were magnifying Moses,
and garnishing the tombs and sepulchers of the prophets, and boasting themselves of them,
but refusing the Son of God himself, who is Lord of all the prophets.
Even so now the nominal Christians of several notions,
whilst they keep feastings and revelings, under pretense of honor to Christ,
in commemoration of his birth,
behave themselves so as rather to represent a triumph of sin and Satan,
rejecting his divine light and grace in themselves;
crucifying to themselves the Son of God afresh by wicked works,
in which they abounded especially at that time.
It was a solid meeting, and ended to satisfaction.

That evening I returned to James Lecky`'s, and the day following,
accompanied by him and Samuel Watson, I went through the mountains to William Eve`'s,
being late within night before we got there, and wet, cold weather.

On the 27th we had a meeting at Ballycane, which was not large, but an open meeting,
and Friends were refreshed together in the Truth, who was near to several.
After the meeting I went to William Errot`'s at Escontinna,
and on 25th had a meeting there, which, though small, was open,
several strangers being there; and a good time we had,
the Lord seasoning us together by his grace.

The 30th, being the first of the week, I went to the monthly meeting at Lambstown,
which was large, consisting of several neighboring meetings.
In the beginning it was heavy, the ears of the people being outward for words;
but the Lord condescending to us, was pleased to appear after some time,
and the way of life was opened clearly and fully, and many were reached,
and Truth over all; but it was a laborious meeting,
many things being thoroughly handled in the word of Truth.

On the third-day following, being the 1st of eleventh month,
commonly called New year`'s day, (1717) I went to a meeting at Wexford,
which was large and open, the Truth appearing in his divine majesty.
I had to declare to the people, the abomination of Ireland in her different parties,
covering her fields with the blood one of another;
the earth receiving the blood of professed Christians at the hands one of another,
mixed with the blood of the beasts and cattle of the earth;
the inconsistency of it with the nature of that love through which Christ died for all,
whilst yet enemies; the ingratitude of Ireland to the Lord for her many deliverances;
and the threatenings of the Lord of further punishments
yet to come in case of continuance in wickedness,
by the sword, plagues, pestilence, fire and famine.
In the delivery whereof all were bowed, and some amazed,
and the meeting concluded in a weighty frame.

On the 2nd I had a meeting at Ballancarring, which was pretty large,
and the Lord was good to us, especially in the latter end of it.

On the 3rd I went to New-Ross, and the day following, being the sixth of the week,
had a meeting at John Elly`'s about three in the evening;
and many of the inhabitants coming, it was a large gathering,
so that many could not crowd in.
The Lord seasoned my heart with his grace, and renewed his holy Spirit in me;
for I had been somewhat low in my mind that day.
Many things opening to their conditions, with somewhat also relating to the abomination,
aforesaid, they were generally weighed down under the testimony of Truth,
and Friends were comforted, some being there from several places.

On the 6th, being the first of the week, I was at the meeting at Waterford.
It was not large in the morning, though some strangers were there,
but very open and comfortable, many being bowed under the blessed Truth,
and some sweetly broken and melted; and a comfortable time the Lord gave us,
to his praise.
In the afternoon we had a large full meeting, many strangers being present,
and things opened fully and with good authority,
and the Lord exalted his own name and Truth over all,
the people generally settled and bowed down under the weight of it,
to the honor of the Lord, and the consolation of the faithful there.

On the 8th I was there again, and the meeting was pretty large and open,
many of the inhabitants of all sorts being there,
though but a few Friends belong to the meeting, and generally satisfied.
I stayed till the 10th, and had another meeting, which was larger than before,
the people being a little awakened by the former meetings.
Things opened clearly in the authority of Truth, which was over them.

On the 11th I had an appointed meeting at Thomas Barnes`'s,
about four miles out of the town, which was crowded, the place being but small.
Hither came several officers of the king`'s customs, who were civil,
and the meeting was well and open; and several of the Irish Papists, and others,
were well satisfied,
though things tended in some part to expose their priests and their deceit.
After the meeting we were invited by a Baptist and his wife, who were after meeting,
to their house near the place, where we were kindly entertained.
That night I returned to Waterford.

Here I stayed till the 13th, and being the first of the week, had two more meetings.
That in the forenoon was large, and an open meeting,
the people being reached and brought down; but that in the evening was much larger,
filled with people of all sorts, and Truth reigned over all in wisdom and power,
to his own lasting praise;
and I believe many will remember that day so long as they live.
I was concerned here to open to the people that called the Apostles`' Creed,
which came very clear in my understanding at that time, as at some other times:
but as to that article, "`He descended into hell,`" I took exceptions to it.
Another point also fell in my way, viz: Predestination; wherein the Presbyterians say,
"`That God, from all eternity, hath decreed some men and angels unto life and salvation,
and others unto damnation or destruction; and the number is so certain and definite,
that not one can be added or diminished;`" referring, for more certainly of words,
to the Greater Catechism of the Presbyterians made at Westminster.
Upon which I thus remarked, among other things,
"`That it is a contradiction in the terms in which they have laid it down:
for the act of the divine will, moving to a decree,
must have a beginning in order to effect that decree;
and therefore cannot be from all eternity, or without beginning, which is all one.
And if God had at all made such a decree, whether before or since the world began,
he had not then left any room for that saying, '`As I live, saith the Lord,
I desire not the death of a sinner,
(whether it might be man or angel) but rather
that he should turn from his wickedness and live.
But so the Lord hath said long since the world began,
and since the time of the supposed decree;
and therefore he had not made any such decree at all.
And again, when God, by his Son Jesus Christ, our Lord,
offered salvation to all the people of the Jews, especially at Jerusalem, and they,
most of them, refusing it upon the terms offered, he wept over them, saying,
'`O Jerusalem, etc., thou that killest the prophets, etc.,
how often would I have gathered thy children, as a hen gathers her chickens, etc.,
but thou wouldst not.
O that thou hadst known, in this thy day, the things that belong to thy peace,
but now they are hid from thine eyes.`'
Now, if God had decreed these to destruction, why did he then offer them salvation,
and charge it upon themselves as an act of their own wills to refuse it?
It cannot consist with any notion of justice that God should decree any to damnation,
without either foresight of faith, or condition of works,
and yet offer terms of salvation to the same persons, as in this case,
and seem to reject them for noncompliance,
when he that is almighty hath determined they shall
never comply:`" with much more to the same effect,
too long to be inserted here.

On the 14th I departed to Carrick, and next day had a large and open meeting there.
Truth came over them in some good degree, most of any note in town being there,
and generally well satisfied, and the Lord comforted us in his service.
On the 16th we had a meeting at Clonmel, about ten in the morning,
which was large and pretty open; and the greatest part being strangers,
things opened for convincement, and much concerning the true church, what it is,
and how constituted, and the people were generally satisfied.

On the 17th we went to Youghall, and on the 18th, in the evening, had a meeting there,
which was very large and open, though but few Friends,
and the people were well satisfied.
On the 19th I went to Cork, and the next day being the first of the week,
and their province meeting, it was pretty large and well, and held two days.
I stayed till the 25th, and was at their week-day meeting,
consisting for the most part of Friends,
where I had opportunity to speak to some things more
peculiar to their states than in those mixed meetings.

The first-day following, being the 27th, accompanied with many Friends from Cork,
I was at a meeting at Kinsale, which, in the morning was not very large, but pretty open.
In the evening it was greatly crowded by people of all ranks and sorts,
and many things were declared to general satisfaction, though errors,
both of Papists and Protestants were laid plainly open.
The crowd was so great that many went away, who coming late, could not get in,
and were not able to abide the cold, or stand so long without doors.
This was a good meeting, and Truth over all, and the people generally, both officers,
soldiers, and others, were very civil to us;
especially the next morning as we passed the streets, wishing us well.

On the 29th I was at their week-day meeting at Cork, and on the 3rd of twelfth month,
being the first-day, I was again there,
where the meeting in the afternoon being put off till towards the evening,
and the town`'s people having pretty general notice,
it was one of the largest that had been seen there, and very open,
being crowded with people of all ranks, and for any thing we could learn,
they were very well satisfied.
Truth being over all to his own glory.

There being a couple of Friends to be married the third-day following,
I stayed the occasion, and the meeting was greatly crowded,
the novelty of the thing drawing some, and many could not get in.
Matters opened fully and clearly to several points, the meeting was satisfactory,
and many spake well of the way of the Lord,
to whom only belongs the praise of all his own glorious works;
for of him is every good word and work.
Here I rested till the fifth-day following, and then went forward to Malo;
where we had a large meeting, the town`'s people being generally there,
and some out of the country adjacent.
Many things were opened to them,
but not in that degree of the power of Truth as at some other places,
they being greatly strangers to Truth,
and until for the streams of life till further sanctified.
Yet things were well, considering their state, and they were generally satisfied;
for I had the thanks of the town at the inn next morning, for the good sermon,
as it was called, by an attorney, who took upon him to be their mouth.
But I told him, if any good was done, they ought to thank God, the author of it.

On the 8th we had a meeting at Charleville; where many people came.
Some of them were a little raw, and whispering a while; but as Truth arose,
it came over them and we had a good meeting, the people being very solid in the end.

On the 9th, in the morning, we set forward, accompanied by several Friends,
and arrived at Limerick in the evening,
and having had letters of invitation from my brother George Story, then dean of Limerick,
and also from my sister, his wife, to lodge at their house, I accepted of it,
and was with them during the time I stayed in town.
They were very kind, and invited my company one day to dinner,
and entertained us freely and plentifully.

On the 18th I went to Tipperary, and the next day had a pretty large meeting there;
which was open.
On the 20th, being the fourth-day of the week, we had a meeting at Joseph Fennel`'s;
which was small but open, and my spirit more at liberty.
After the meeting we went to Clonmell,
and lodged at the house of our friend Joseph Collet.
On the 21st, being their meeting day, which usually is in the forenoon,
they appointed it in the evening, at the fourth hour, for the sake of the people;
whom we had a desire should be at the meeting.
It was very large, and many things of weight were opened to them,
and Truth prevailed over all.
The mayor of the town was there, with the badge of his office,
and some military officers, and all very sober and satisfied;
and things were well and comfortable.

On the 22nd we had a meeting at John Bowie`'s at Woodhouse; where most of the gentry,
so called, in those parts adjacent, and others were present,
and four of them justices of the peace.
The meeting was open, and Truth over them, and they were generally satisfied.
But one of the justices, an ingenious man, after the meeting,
in some free and pleasant discourse with John Bowles, said, "`The doctrine was good;
but that part against war, though according to the scripture, was too hard,
especially at this time, when an invasion is expected.
Would you have us lay down our arms, said he,
and suffer the pretender to take possession of us?`"
But he said nothing to me, nor any thing in displeasure.

I stayed there till the 24th; and being the first of the week, went to Cashel.
The meeting, both fore and afternoon, was very large, especially the last;
and the truths of the gospel were fully and largely opened to them;
many people of all ranks being there, and generally satisfied or silenced;
and a good time it was to many, who spoke well of the way of Truth.

On the 25th we had a meeting at the town of Thirles, in the courthouse;
where came together a great concourse of people, it being generally a popish town;
but the people were civil in the main, except some of the baser sort,
who were a little light; and many were reached by the wisdom and power of Truth,
and well satisfied.
But the curate of the town, one Thomas Sharp,
though he did not give us any interruption in the meeting, yet in the mean time,
put up a paper on the market cross, a copy whereof followeth, viz.

[.embedded-content-document.paper]
--

[.signed-section-context-open]
February 25th, 1716-17.

All religious assemblies which dissent from the established church in this kingdom,
etc., are schismatical, and contrary to law; therefore,
to go to a dissenting congregation for any other
end than to oppose and suppress such a meeting,
is sinful.

To go with a design to join in the worship of it is so;
because this is to have fellowship with that which is sin,
and partake in the iniquity of it.

Or for diversion, because it is not lawful to make a mock at sin; and they are fools,
i.e. profane and wicked, who do so.

Or for curiosity, because this is in order to know and be acquainted with sin.

Or for want of better employment, and out of amusement only;
because no one ought to be so idle, or so ill employed,
as to pay attendance to any thing which is sinful:
this is to show a respect and countenance to it.

[.signed-section-signature]
Thomas Sharp, Curate of Thirles.

--

After we went to the inn, I had began to write an answer to this paper; but,
in the mean time came the priest himself, and one Oliver Grace,
a gentleman in the country, and a lieutenant of horse, to our inn;
and seating themselves in a room, desired to see me.
I went accordingly to them, and two or three Friends with me; and after some civilities,
we began upon the said paper.
I observed to them,
that all these supposed sinful consequences
depended upon the proof of the first position,
viz: "`That all religious assemblies,
which dissent from the established church in Ireland, etc. are schismatical,
and contrary to law;`" which I denied, and put him upon his proof.
But first, fully to establish the terms of his proposition,
I desired him to explain the meaning of this etc.
For as there were once in England a sort of men
who swore with an etc. including pro or con,
to be explained as they might think most conducing to their interest,
or advantage afterwards;
so in this etc. might be included many sorts of national churches in other countries,
and some quite contrary to that now in Ireland.
He answered, "`I mean the church of England only.`"
Then I asked him, "`How is that church established more than any other in Ireland?`"
He said, "`The clergy of Ireland being in time past, met in convocation,
agreed upon certain articles of religion, thirty-nine in number,
which were afterwards confirmed by the king and the great seal of England.`"
I asked him, "`How does it appear that this is such a church,
as that all are schismatics and sinners that dissent from her?
For the true church is hid with Christ in God; is the ground and pillar of Truth,
the New Jerusalem, the church of the first-born, and mother of saints;
and built on Christ Jesus, the true foundation, rock of ages, and chief corner stone.
But a church established by human authority, is the creature of that authority,
which the church of Christ never wanted, or will want to establish her;
being settled already by his own power, to his glory.
And if schism and sin be marks of an irreligious assembly, pray then,
why are they in England and Ireland so divided among themselves,
as that one part is in rebellion against the government that established them,
and the whole miserable sinners, as by law established?
Can it be any schism or sin to dissent from, or meet together otherwise than among,
miserable sinners.`"
Some of his company being rude, and more subtle than himself, would have brought him off,
by giving ill language, and so making a confusion;
for they saw where it was like to land; but he could not take the hint.
"`For if it were schism to dissent from a national church, why did they,
in queen Mary`'s time, etc. dissent?
And if that was a schism, why do you continue it?
Is that the reason you are miserable sinners?`"

Then he recurred to the sacraments, and said,
"`They that deny the sacraments and ordinances of Christ are schismatics.`"
I asked him, "`What dost thou mean by these terms?`"
He said, "`Baptism and the Lord`'s supper.`"
I asked him, "`What baptism?`"
He said, "`Water baptism.`"
I replied, "`If all are schismatics that decline water baptism, you yourselves are so;
for sprinkling infants is no baptism.
It is an error both from mode and subject.`"
Then he recurred to the authority of the church;
which being a plain handle for turning the schism where it should be, the above officer,
one of his company, threw in a diversion,
by accusing me of being the leader of those bullocks, as he called the Friends there.
I told him, "`They and I have all one Leader,
and I am far from assuming any such character;
which is very injurious and scornful in thee to offer.`"
Then we proceeded upon the argument of baptism.
He alleged the text, "`Go teach all nations,
baptizing them,`" etc. and said it was water baptism.

I said, "`Water is not mentioned, but in another place, by way of distinction;
showing it was not water but the Holy Ghost, thus:
"`For John truly baptized with water,`" said our Lord Christ,
"`but ye shall be baptized with the Holy Ghost not many days hence.`"
He said,
"`The apostles did baptize those with water who had before received the Holy Ghost;
therefore it was water they understood by the text.`"
I replied, "`That is no fair deduction, or consequence;
for some were also circumcised after they had received the Holy Ghost,
which established the one as well as the other; but indeed neither.
Besides, if the apostles had baptized with water from that text,
they would have pursued the terms of it, viz: '`in the name of the Father,
Son and Holy Ghost;`' but they never baptized any so with water;
therefore not from that text.`"
Then he said, "`I can prove they did;`" alleging that text, "`Who can forbid water,`" etc.
I answered,
"`It does not appear by that text that these were baptized in the name of the Father,
etc., and in other places, it was in the name of Christ the Son only;
not upon this text in Matthew xxxviii.
but upon the same foot on which they baptized in John`'s time,
before the giving out of this text; where Jesus himself baptized not, but his disciples.
But that the apostle has put out of all question, where he says, '`there is one Lord,
one faith,
and one baptism;`' which one baptism must either be water baptism without the Spirit,
or the Spirit alone without water, or the Spirit and water must make up that one baptism.
It is not water alone; for Simon Magus was baptized with water,
and yet had neither part nor lot in the Holy Spirit.

Again, the Samaritans had been baptized with water in the name of the Lord,
but had not received the Spirit; and some were baptized that had not heard of it;
therefore, the Spirit and water not going together, they are not one baptism.
But the apostle is clear in the point, where he saith,
'`By one Spirit we are all baptized into one body;
for we have all been made to drink into one Spirit.`'
And this makes members of the church, which is his body,
'`the fulness of him who filleth all in all;`' which is not a body of miserable sinners,
but of saints and saved of the Lord.`"
They could not hear this but with divers interruptions;
and he would have evaded it by some poor flosses upon some texts, viz:
"`It was to be understood by the authority of one Spirit, etc.`" which I rejected.
Then this Oliver Grace,
(said to be a late convert from popery) began to be further abusive, and said,
"`You have no more religion than my horse.`"
I asked, "`What hast thou seen or heard in me to provoke thee to such an expression;
which thy horse, if he had like faculties as thyself, would hardly have used,
where no occasion was given.`"
I told them, "`I am now disappointed in you; I expected,
when desired and invited into your room and company,
at least a rational conference on the points proposed;
but to be thus treated is another thing;`" and so departed the room.
After I went to bed, I found my spirit much laden, which after some time went off,
and I fell asleep in much sweetness.
But they were drinking in a room at the other end of the house, the people,
being protestants and civil, having so contrived it, that they might not disturb us.
There they stayed the greatest part of the night, and the priest with them,
till they could hardly know which end was up.
But in the morning I was told,
that this Oliver Grace would needs come to me in the night, in that condition,
to dispute about religion, as he pretended.

The next morning, the 26th, we set forward for Kilkenny;
where we procured a place for a meeting; being a long malt house,
and had it well furnished with seats that evening and the next morning.
At that place, it is to be noted, was a very high and lording prelate;
having also a temporal title, called Sir Thomas Veazey.
This Haman-like man had shown a particular aversion to Friends;
and several of our meetings in that town had been disturbed and hindered by his register,
one Robert Connel, an alderman in that town,
and such others as he could procure to officiate in such evil work.
They exercised their violence and disturbance upon Elizabeth Jacobs once,
and another time upon Margaret Hoare and Abigail Craven, and hindered the meetings;
which Friends had borne for the sake of peace, without any complaint to the government.

But now they proceeded more violently; for as we were met according to appointment,
on the 27th, about the second hour in the afternoon,
and many of the town`'s people with us, some time after I had stood up,
two men came in and made disturbance, bidding me be silent, and the people disperse.
I did not mind them for some time, but went on, till they had so disturbed the meeting,
that the people were not in a condition to hear.
Then I stopped, and asked who they were, and by what authority they did that.
They answered they were the church wardens.
I replied, that the church wardens, as such, had no business with us,
or power to hinder us; and desired them to desist, and sit down quietly as others were.
They seeing that would not frighten us, as they had imagined,
began to speak to particulars of their own sort,
threatening them with the bishop`'s court, and excommunications, and such like things,
and began to take some names in writing; which some being afraid of, went out;
but the greater part stayed, and some were much troubled at the spoiling of the meeting,
for it had begun well.
But the envy of Satan, and pride of ungodly men rising higher,
whilst we were at this work,
in came one of the mayor`'s sergeants at mace and a constable with a warrant.
I being still standing,
and sometimes exhorting the people as well as I could in such disturbance,
they bid me come down and go with them,
for they had a warrant from a justice of the peace to apprehend me,
and disperse the meeting.
Then I said, we were well known to be an innocent people, readily subject to government,
either actively or passively;
but desired them to have a little patience till I had cleared myself among the people;
and they did not seem very forward to take me away,
till some of the superior persecutors towards the door cried out,
"`How well do you execute your warrant!`" and then they took me, Edward Cooper,
Henry Ridgeway and John Harris, away in custody up to the justice`'s house.
But he would not be seen, being much troubled that he had signed the warrant,
it being ready drawn by Robert Connel, the bishop`'s register,
and sent to the justice by the bishop, desiring him to sign it;
which he had done with great reluctance.
They then took us from place to place to find a justice; but none cared to see us,
till at last we were brought before the mayor and this Connel, who,
being one of the aldermen, is also a justice of the peace for the city ex-officio.
They were a little rough, and pretty high upon us; but the Lord,
for whose name and cause we were there, kept us over their spirit and power.
John Bowles, John Deckey, Samuel Watson, Thomas Prin, John Prin, junior,
and other Friends, continuing the meeting, and many of the people with them,
the officers also brought away those Friends
last named before the mayor at the same time.
They charged us with a riotous and unlawful assembly;
I told them they themselves did not believe it to be a riotous assembly;
and there were many witnesses that we were peaceable,
till the church wardens and their officers disturbed us.
Then Robert Connel himself confessed we were not making any disturbance,
but said it was an unlawful assembly,
the Act of toleration in England not extending to Ireland.
I answered, "`That act being for the liberty of the subject,
extended everywhere in Ireland,
and other countries where the subjects of
England are settled under the crown of England.`"
Then they demanded security for our appearance at the assizes,
and for our good behavior in the mean time.
We told them we were not of ill behavior, and therefore needed not to be bound;
but seeing their wicked design, we all refused.
Then they wrote a mittimus, pretending to send us to jail,
but at last they told us we might go where we pleased, only they charged us,
upon pain of what should follow, not to have any more meetings there; for if we did,
they would take more severe measures with us.
Having a full bottle of wine upon the table, they would have given us some,
but we all refused it, at which they were angry.
So we left them, and went down to Thomas Date`'s, at the Swan, where many of us lodged.
And pretty many Friends being together there after supper,
we concluded to have another meeting next morning,
and some Friends were appointed to give notice to the mayor, some to the justices,
some to the soldiers, and some to the people of the town.

On the 28th, about nine in the morning, we went to this second meeting,
where the people did not gather much till about ten;
and I had stood up about half an hour, when in came the same church wardens,
and made the like disturbance as before, taking names,
and threatening the people with the bishop`'s court and excommunication, frightening some;
but most did not seem to mind them, and I went on for some time over them,
till also came two of the mayor`'s sergeants at mace and constables,
and a great mob after them; and they commanded me to be silent,
and the meeting to disperse.
Some of the meaner sort went out of the house as fast as they could, being fearful,
but many stayed to see the issue; and they taking me into custody, I went with them,
but they took no other Friend.
The mayor, this alderman Connel, and some others, being together,
I was had before them without any warrant.
They were very angry, and gave me some threatening language.
I told them they were not to insult the king`'s peaceable subjects,
or to exercise their own passions upon them; but if I had broken any law,
I was subject to the law, either actively or passively; and if they acted without law,
they also were punishable by the law.
They were very angry still, and the mayor said, I had assembled myself with others,
contrary to law, and demanded security for my appearance at the next assizes,
the 16th of next month, at the city of Kilkenny,
and in the mean time to be of good behavior.
Then I said, "`What law have you here in Ireland against our meetings!`"
Said the mayor, "`There is no law for them here.`"
Then said I, "`There is none against them;
and where there is no law there is no transgression.
The Act of toleration in England gives us, as well as all others,
the king`'s Protestant dissenting subjects, liberty everywhere in his dominions.`"
Then they wrote a mittimus as followeth, viz:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
By John Birch, esq.. Mayor of the said city, and Robert Connel, esq.,
one of his majesty`'s Justices of the Peace of the said city.

City of Kilkenny, ss.
We herewith send you the body of Thomas Story,
he unlawfully assembling himself with several other persons,
and refusing to find sufficient security for his appearance next assizes,
and for his good behavior; and him in safe custody to keep,
till thence discharged by due course of law.
And for so doing this shall he your warrant.
Given under our hands and seals this 28th day of February, 1716.

[.signed-section-context-close]
To the keeper of his majesty`'s jail of the said city.

[.signed-section-signature]
John Birch, Mayor.

[.signed-section-signature]
Robert Connel.

--

I was sent to the common jail of the town, among thieves in irons,
where I stayed not long in the custody of the jailer till Anthony Blunt,
the sheriff of the city, a very civil young man, and loyal to king George, came to me,
and showed his resentment sufficiently at their doings;
for he not only called for the mittimus, that we might have a copy of it,
which the jailer had refused, being an Irish Papist,
but left it in my own hand till he returned, going immediately to some of the justices,
to have their opinions and concurrence in taking me to his house, which he readily had;
and accordingly took me with him, and provided me a very good room in his house,
and agreeable accommodations,
to the disappointment of that great Episcopal envy thus leveled against me.
All this I observed to be the Lord`'s doing,
for the furtherance of the gospel and his own glory;
and the Lord was with me in a good degree, to my great comfort, and as my only sure help.

On sixth and seventh-days came Friends from several parts to see me,
and many stayed in town till the first-day, being the 3rd of the first month;
and in the forenoon we had a meeting in the sheriff`'s house, where his wife,
a vey good-natured, sober woman, and family were present, and many of the neighborhood.
We had a good open time,
wherein I had an opportunity to expose antichrist and his ministers, which,
I am apt to think went to the bishop`'s ears, as it did quickly through the town,
the people wondering at our boldness, not knowing our foundation.

The next day, the 4th, I went to take the air in the late Duke of Ormond`'s gardens there,
and some Friends with me, and several people came to us, and among others,
some French Protestants and an Irish Papist.
He seemed friendly, and repealed some verses against such as seemed to be religious,
but aimed at nothing but promotion, and worldly honor and glory by it.
I told him some people`'s religion made them worse than their natural temper,
which could not be right; for the end of true religion is an improvement upon nature,
and restoration from the fall, even in this life,
and rendering men more sociable and safe; but that priestcraft of many kinds,
tending to an evil end, had, as to great part of mankind,
eluded all the means hitherto offered for the help of man, and made a prey of him,
instead of that aid designed.
For though there is nothing more plain than religion in its native simplicity,
yet the priests, the better to effect their own designs,
had invented abundance of lying mysteries, to confound and amuse the people,
and persuaded them, that offerings of many kinds were essentials of religion,
which offerings were ever at the priest`'s disposal, and for his gain and advantage;
which will ever continue till the people receive the Lord Jesus,
and turn to his light and grace as their true teacher.

In the meantime, as we were at this sort of conversation, in came justice Warren,
alderman Haddock, and Clarke, the collector of the king`'s customs, and some others,
and entering into conversation with us,
by degrees they fell to discourse upon my confinement,
which they all did with considerable resentment; and some of them observed,
that to make a show, now after the people had talked so broad in the streets, the mayor,
and that party, had shut up the mass-houses, which before had been connived at;
and also how angry they were with our meeting the day before,
but could not help themselves, since I being a prisoner,
could not be hindered from speaking to such as came to me; and very friendly they were.

In the mean time the mayor and alderman Connel came in, greatly chafed,
which was heightened to see these persons with me, conversing so friendly together.
Their business was to persuade justice Warren, alderman Haddock,
and whom they could besides, to join with them to send me out of the county,
from constable to constable; for I becoming very burdensome to them,
they had fallen upon this contrivance to get rid of me;
and their power extending no further than the town,
they could not send me out of the county, but out of the town only,
and then they feared I would come in again immediately; but if out of the county,
being some miles, it is likely they imagined I would not take the pains.

As they advanced towards us, I began to speak to those persons with me above mentioned,
concerning the grounds upon which my adversaries built, viz:
the supposition that the toleration Act extended not to Ireland.
But I told them, "`They were mistaken; for all men by nature are free,
till that freedom is taken away, either by policy or force.
Some penal laws then, made by an anti-christian policy, and applied by tyrannical force,
having obstructed the liberty of the subjects of England for a time,
yet that liberty was not destroyed; but that force being removed, liberty revived,
and turned into her natural channel.
For there are many statute laws in England,
in which there are several terms and clauses of enacting,
that in reality are not initiatory of new matter,
or new laws or privileges never before claimed, or enjoyed by the people, of right;
but declaratory only of rights and privileges in possession by them and their ancestors,
before endangered by evil counsellors to kings and princes, who,
for their own advancement in favor,
are too frequently the wicked instruments of tyrannical and enslaving counsels,
where they meet with any degree of propensity in the
tempers of their princes biassing them that way.
Of the like nature is this toleration Act in England:
which native rights and privileges all Englishmen carry along with them into all
regions of the world where they settle under the regimen of the crown of England,
now upon a very worthy head,
who declares for liberty to all his Protestant dissenting
subjects throughout his dominions the world over;
and that indulgence they enjoy everywhere but here.
The Act of toleration extends to Ireland, America, and all the king`'s dominions,
being declaratory in its own nature, not only of English, but also of gospel liberties;
and which we now insist upon against the unjust force of such as oppose themselves here.
And that this is, and ever hath been,
the mind of the king and his predecessors since that law was made, is plain,
by extending that liberty and indulgence here, as likewise to all his English dominions.
And not only thus, but the king has given us his royal word for his protection,
upon several addresses, and particularly upon one from our last yearly meeting at London,
the 26th day of the third month, 1716; and another since,
from our last national meeting at Dublin, here in Ireland,
to which he was pleased to answer in these words, viz:
'`I thank you for the assurance of duty and affection to my person and government,
contained in this address; and you may always depend upon my protection.`'
I myself was present, with many more,
when the king received us with this first address in his own bedchamber:
so great was his condescension and regard to his loving and peaceable subjects.
But it seems the mayor and magistrates here think it their
interest to insist upon an opinion quite of another nature,
at the hazard of what may follow;
for you may assure yourselves we are as jealous and tenacious,
both of our gospel and natural liberties as any
body here can be bent to deprive us of them.`"

This being finished, the mayor and his party showed a great deal of rancour,
but could not help themselves; and immediately after,
the mayor and Connel made application as aforesaid for assistance.
But the justice at once refused,
and told them he had done too much of this drudgery for them already,
and would do no more, but would leave them to their own measures.
This vexed them heartily, and occasioned some more words,
which were pretty warm on both sides,
till the justice and the rest that were for the king and indulgence, asked them,
"`How came you to connive at so many masses in view,
and be so furious upon the king`'s friends and peaceable subjects?
Pray, Mr. Mayor,`" said he,
"`what notice have you taken of the seditious sermon
you heard yesterday afternoon in the little church?
You can hear such with pleasure,
whilst you treat these loyal subjects with so much severe usage.
Did you, sir, demand that person`'s notes, and bring him to account for what he had done?`"
To which the mayor answered, "`That is my lord bishop`'s business, not mine.`"
Then they replied, "`If it was not your business, being a matter of religion,
pray how comes it to be so much your business to meddle with these people,
who have given you no other occasion but in respect of their religious opinions,
to which they have equal right and liberty with all
others his majesty`'s Protestant dissenting subjects,
and are much more useful to the government than some that you connive at?
And pray, from whom arises the common danger?`"

We heard them thus far, but things rising higher and higher,
thought best to withdraw and leave them, the dispute turning favorably on our side,
which we did: but in the evening the sheriff told me they ended in heat;
and that the mayor and alderman Connel,
finding they could not have any aid of the others, were resolved, as they pretended,
to send me out of the town next morning by the constables,
and that if I came again they would put me in the stocks.
I told him I did not fear them; let them run the length of their chain.
For though they thought to frighten me with their threats,
I knew the laws better than they imagined;
and that they could not do it but by illegal violence.

The next day, the 5th, the mayor was much cooler;
and intending to go out of the town the day following to meet the judges at Wexford,
being deputy clerk of the crown, he took up the mittimus,
and sent me word by the sheriff, that I was at liberty,
and might go when and where I pleased; and said also,
that he would not have done what he had done against us, but that the clergy, as one man,
greatly urged him to it, saying they had thought him a man for the church;
but to find him so remiss in suppressing the Quakers, looked quite otherwise.
And added, that for his own part he did not care what meetings we had;
but intended to get out of the way of it,
and leave alderman Connel in his place till he returned,
hoping all would he over in his absence.

Upon this message I told the sheriff,
That they had committed me publicly by a mittimus till the assizes,
as if I had done some heinous crime;
and as on the one hand I could not accept of a private discharge, so on the other,
this discharge was not legal,
which was an indication they were either ignorant or arbitrary;
for they ought to have returned their proceedings before the judges,
that the matter might be heard at the assizes.
But in case of a discharge before that,
it ought to have been by a liberate in writing under their hands and seals,
or of some other justices; and therefore I remained with the sheriff,
which displeased my adversaries worse than before, and heightened their rage.

Many Friends visited me from divers places on the 9th, being the seventh of the week;
and considering together of a meeting next day,
we spoke to the same person about the same place we had before,
and he readily granted it: so all was prepared, as seats, etc.,
and notice was given by some Friends to alderman Connel, now deputy mayor,
and the justices, of what we intended; but he said he would disperse us again,
and that we should not have any meeting there.
However, we went to meeting,
and though I had some things in my mind to say in the meeting,
before I found the proper time to stand up,
one of the church wardens came and began the disturbance;
and soon after came the mayor`'s sergeants at mace, commanding the people to disperse,
and the church wardens took down names,
and threatened the people with the bishop`'s court.
Then I reasoned the case a little with the constables and sergeants,
and they seemed troubled that they were put upon using us so; but could not help it,
being under authority.
After a while I went with them, having first made some remarks on things to the people,
and they put me in jail the second time, where I was hardly well entered,
till they brought William Brookfield of Dublin thither also.
For some Friends from thence coming to see me, and he among others,
and the meeting continuing after they had brought me away, William had stood up to speak,
and some of the constables took him down, and brought him to us.

We had been in prison but a small time till the
sheriff came and took us home to his house,
where the other Friends came to us after the meeting was over, which they held,
notwithstanding all the disturbance, till it regularly ended.

But the deputy mayor being come from his worship, sent for me before him,
and seemed very angry, and asked me how I came to appoint another meeting,
being in custody`'.`' Then said the sheriff, "`Sir, the gentleman was not in custody,
for Mr. Mayor took up the mittimus before he went out of town,
and told me he was at liberty;
only he would not go out of town till he himself thought fit, being free,
as he apprehends, to go or stay at his own election.`"
Then said I to the deputy mayor, "`These proceedings are very arbitrary:
what have I done now to deserve imprisonment?`"
"`Did not I tell you, sir,`" said he, "`that I would disperse you,
(for I had met him in the street as we went to the
meeting) and that you should have no meeting here?`"
"`It is true,`" said I; "`but since there is no law against our meeting,
thou hadst no right to say so, nor was I obliged to take notice of it, being without law;
but besides, the gospel must be preached,
and God must be worshipped according to his own appointment,
whoever will make laws to the contrary,
or apply an unjust and illegal force to restrain it.`"

Then said one of the sergeants to the deputy mayor, "`Sir,
this gentleman said nothing in the meeting; he was not preaching.`"
He immediately laid hold on that to get rid of us, for he wanted his dinner,
then staying for him, and said, "`I cry mercy, I thought you had;`" and so dismissed me.
But, before we parted I told him, "`That notwithstanding thou hast used us so illy,
I have a secret apology in my mind for it,
but cannot be positive whether thou deserves it; and that is,
I conjecture that thou dost not act altogether
from a native spring of dislike in thy own mind,
but as excited by some other person or persons,
for some other reasons than perhaps thou carest to express or own.`"
Upon this he said, "`I have no enmity against Friends, but have, upon occasion,
forgiven some of them lees (being register to the
bishop`'s court) to the value of seven pounds.`"
And so we were dismissed without any further conditions.

About three in the afternoon we went to meeting again in the same place,
and the bishop hearing of it, and walking in the Tolsel,
told one of the sergeants if we met again he would have
us put in the stocks till he came from church.
But being set, many people came to us, and the Lord,
who never tails nor forsakes his own, was with us, to our great comfort,
whilst envy and rage tormented our enemies.
I had something to say, and had gone on some time,
the people being greatly desirous to hear,
and many still and satisfied with what they heard,
till the constables and sergeants came in again; but so faintly, and with apologies,
that they could hardly touch me.
But after some time, one of the sergeants named the bishop to be concerned in it,
which I laid hold of,
and told the people we had not been without
apprehensions all this time who was at the bottom,
but now they heard plainly it was the bishop; and after some further remarks, viz:
"`That what our Lord said to his disciples,
'`Some of you shall Satan cast into prison,`' was now also fulfilled in us.
For though that evil one cannot cast any into prison by himself,
as he is a wicked destroying spirit; yet as ungodly and wicked persecutors are excited,
instigated, and hurried to that evil work by Satan, he, as the first mover,
is said to do it,
so that they might plainly see on what bottom they were who thus abused us.`"
The people, nay, even many of the Papists who came there to hear and see,
were generally displeased with them;
and the Truth reached them through our works and patience,
and exposed our enemies to the just censure of all.

The sergeants and constables took me away, many of the people followed,
calling out shame, and blaming the magistrates; but we desired them to avoid disturbance,
lest some advantage might be taken.
The officers became so troubled and ashamed,
that they entreated me to walk up to my lodging till the church was done:
but I told them I was in their custody, and could not go but where they took me;
and they went with me to the sheriff`'s house, where they expressed their great concern,
that they should be in offices that subjected them to
actions so much against their inclinations.
But the meeting continuing after I was brought away,
William Broomfield had a good time in a short testimony among them;
and though some constables were there, they stood without,
as if they had no mind to understand or hear any thing; and the meeting ended in order,
and Friends were generally comforted.

In the evening the deputy mayor sent me word by the sheriff,
that he would wait on me by and by at my lodging about that afternoon`'s meeting.
I replied, "`That was not so proper, but if he had any thing more to say,
that required my answer, I would wait on him where he pleased.`"
The sheriff told him what I said,
and he sent the sheriff to ask me if I intended to go out of town the next day,
and if I did, he had no more to say; but if I did not go out, he would put me out.

I replied,
"`That if the mayor had sent to ask me that question without any threats annexed,
I would have answered him freely and plainly as to my intent;
but was not to be frightened, being at my own liberty to stay or go as I pleased.`"

This the sheriff told him; and he then made the sheriff take it down in writing,
which he did.
The mayor then bid him set his hand to it, which he did;
but told the mayor he would keep it in his own custody, and accordingly showed it me.
I suppose the mayor thought to frighten me by this poor little shift.
Then I told the sheriff I intended to go out of the town in the morning,
to take some meetings in the country, and return there again at the assizes,
in the latter end of the week.

Then the sheriff told me the bishop was very angry with him,
and so were all his creatures, for letting me have liberty,
and had sent for him that morning; but that he would not go till we were out of the town.
I told him he had best go then, lest the bishop might take some advantage,
as if he did not regard him; but as for us, we did not fear any thing he could do to us.
However, he went not so long as we stayed, which was till about the eleventh hour,
I going to see several of the aldermen who had shown us countenance,
and also Colonel Warren, before we took horse;
and went openly through the greatest part of the town,
telling the people on every occasion, I intended to see them at the assizes.

On the 11th we set forward; and several Friends being in company, on comparing things,
we found we had all had a share of the burden;
but were very easy and comfortable in our spirits,
concluding that as we had come laden thither, and left our burden behind,
it was gone upon those who had opposed Truth, and would be heavier and heavier on them,
till they sunk under it, or yielded.
And so we saw the hand of the Lord in the whole, and rejoiced together in him.
That day I went home with Edward Cooper, who had been with us all this time.

On the 12th we had a meeting at Samuel Watson`'s, which was a large open meeting,
and the people, as well as Friends, were well satisfied.

On the 13th we had another meeting at Carlow,
which was also well filled with people of several sorts,
and they were also very quiet and sober in time of silence.
I had taken cold in the transactions at Kilkenny, which had weakened me;
but the Lord strengthened me so as to make me
instrumental to deliver many things to edification,
information and comfort; and it was a good meeting to some,
and the people were generally satisfied, and some much pleased.
That night I went home with John Leckey, about a mile from Carlow, back towards Kilkenny,
where I was well entertained.

On the 16th, in company with several Friends, I went to Kilkenny,
to see what they had to say to me at the assizes,
to which I had been committed by the mittimus aforesaid,
not thinking it honorable in the Truth to take liberty by word only, lest, being absent,
they might pretend I had given them the slip;
to which I never had any temptation from first to last.

On our way we fell in with some persons going to town;
and one of them offering some discourse about religion, I perceived after a while,
he was a Roman Catholic; and after some other points,
we came upon that of transubstantiation.
He urged the words of Christ, where he said, concerning the bread, "`Take,
eat ye all of it; this is my body which is broken for you.`"
And again, concerning the cup, "`This cup is the New Testament in my blood,
which is shed for you,`" etc.
"`This,`" said he, "`is so plain and distinct, that there can be no mistake in it:
'`This is my body; This cup is the New Testament,`'`" etc.

I answered, "`This is a figurative speech: this bread signifies my body,
which shall shortly hereafter be broken for you; and this cup, that is to say, the wine,
or liquor contained in it, signifies, or symbolizes, the New Testament in my blood.
For if it were a proper speech, without any figure, many absurdities would follow,
against both sense and reason;
whereas Christ and his apostles suit their doctrine and miracles to both.
And saith reason.
It is impossible that both the body of Christ
and the bread can occupy one and the same place,
at one and the same time; for when the body is present, the bread must be absent,
and when the bread is present, the body must be absent.

"`And again to the senses: the apostle John says,
'`That which we have heard with our ears, seen with our eyes,
and our hands have handled of the good Word of life;`' alluding
to the infallible certainty of sense in preaching the gospel;
'`for the life was made manifest, and we have seen it.`'
So that as certain as is sense in sensible subjects and objects, so certain,
and yet more,
are all the true ministers of Christ of those saving
and divine Truths they deliver from the Spirit,
or essential Truth and life manifested in them, in its own power and virtue;
and so certain also may the hearer be of the Truth of the ministry,
by the manifestation and answer of the same Spirit working in him.`"

I further urged that it was a figurative speech, for this reason; "`Because he saith,
'`This cup is the New Testament,`' were it of wood, stone, earth, or metal.
That cup, whatever it was, was the New Testament, according to thy and your notion.
Where then is that cup?
If the cup be lost, then also is the Testament, if the cup be the Testament.`"

This was a little pinching, and drove my antagonist to this reply, viz:
"`This speech of Christ hath two parts: the first is proper, concerning the body;
but the second is figurative, concerning the cup.`"
Then said I, "`Friend, pray give me thy reason for the difference.`"
"`Because,`" said he, "`it was impossible to drink the cup,
but only that which was in it.`"
"`It is a good reason,`" said I, "`friend, and holds as well the other way;
for if that must be figurative respecting the cup,
because of the impossibility of drinking the cup itself, to common reason; even so,
for the same reason, deduced from the impossibility of the thing,
I justly conclude there is no transubstantiation.

"`But if it had been so, then this, and many other like absurdities would have followed,
viz: Whilst Christ sat at the table, and said of the bread,
'`This is my body,`' the body which brake if, and called it his body,
must cease to be that body, and the other,
the bread must commence and begin to be his body, which it was not before,
and be really so, before he could properly and truly call it so,
or else there must be many, nay innumerable same bodies at the same time,
and yet all but that one body; which is absurd and unreasonable.

"`Again, if whilst Christ sat at the table with his disciples,
they all ate the whole entire Christ the evening before he was crucified; pray, then,
who was left uneaten to be crucified next day?
And if the first to whom he gave a piece of bread had all the whole Christ,
what remained for all the rest`'.`' I think nothing at all.`"

Then he said, "`Christ told the people, '`That except ye eat the flesh,
and drink the blood of the Son of Man, ye have no life in you.`'
There must then be some way of eating and drinking, to make good that saying;
which is also very plain in its own nature, the flesh and blood in a proper sense.`"

To this I answered, "`That Christ did say so, and the people took him to mean properly,
and without a figure, as ye now do, looking upon the impossibility of the thing,
as it really is, in the sense they and you take it;
but when they were all offended and gone, he turned to his disciples,
and explained it to them, for they seemed not rightly to understand him;
'`Will ye also leave me?
It is given to you to understand the mysteries; but to them (the world) in parables.
What then was the parable or mystery?
It is the Spirit that quickens, the flesh profits nothing.`'
And thus it is in your own Bible as well as ours.`"

I further added, "`That if therefore the bread were really transubstantiated,
after the words said, and were the true body and blood of Christ;
and if they ate and drank the same flesh and blood which then they beheld,
it would profit them nothing.`"

Then he said, "`It is true the flesh and blood by itself, without the Spirit,
does not profit; but when we eat the flesh and blood together, we eat the Spirit also,
and that quickens as we eat it.`"
This was a deep fetch, and the last shift, which I answered thus, viz:
"`This cannot be Christ`'s meaning; for he does not only distinguish,
but divide between the flesh and Spirit.
'`It is the Spirit that quickens:`' here is the
whole work of quickening ascribed to the Spirit;
and the same that quickens, also continues life in him who is quickened;
for from the Spirit came flesh, blood, bread, wine, and the whole universe,
and all that in it is; and are all continued by the same Spirit,
the substance of all things.
'`But the flesh profiteth nothing:`' here it is
set apart from the Spirit in the same sentence,
and profiteth nothing to be eaten.
And for further interpretation of this, observe 1st; The words of Christ to Satan,
'`Man shall not live by bread alone;
but by every word that proceedeth out of the mouth of God.`'
The words which proceed out of the mouth of God are spirit and life;
as said the Lord Christ, who is that Word, '`My words they are spirit,
and they are life;`' which words the apostles knew, by experience, to make them alive,
and preserve them; as appears,

"`2ndly; By the answer of Peter at the same time, '`Whither shall we go,
thou hast the words of eternal life?`'
So that this quickening is not by this so gross
and carnal eating and drinking here imagined;
but by receiving of the Spirit, through the Words of Christ,
abstracted and apart from that holy body, or any other body.
And for the further understanding of sayings of this nature, observe,
that when the disciples of Christ were showing him the temple at Jerusalem,
and the beauty of it, he said to them, '`Destroy this temple,
and I will raise it up in three days.`'
The temple at Jerusalem was the object of their eyes, and the subject of their discourse,
which gave them just occasion, as men, to suppose he meant that temple; which they said,
'`was forty years in building,
and could he raise it in three days`'!`' They admired at his saying; but yet,
in the sequel of things, they understood afterwards, though not at the time,
that he spoke of the temple of his body.

Again, in like manner, where he saith, '`I am the vine, ye are the branches,`' etc.,
this may well explain that other saying, '`I will drink no more of the fruit of the vine,
till I drink it new with you in my Father`'s kingdom;`' which can mean no other,
than as his coming in the flesh consecrated the way,
and was previous to the coming of the Spirit;
so his drinking new wine in the kingdom of God must signify the community of spirit,
intended in the words of the apostle afterwards, concerning the whole church;
'`We have all been made to drink into that one Spirit.`'`"

My opponent by this time being weary of the subject,
advanced a question concerning the Spirit itself, viz:
"`How do you know that Spirit from another spirit,
since Satan is transformed into an angel of light?
May it not be that evil one, and not the Spirit of Christ?`"

I replied, "`That the divine essential Truth is self-evidencing;
that the quickened soul is assured of him by his own nature,
and quickening power and virtue; as saith the apostle,
'`Hereby we know that he abideth in us, by the Spirit which he hath given us.`'
And he that is in a state of doubling is in a state of condemnation and reprobation,
and hath not yet known the Spirit, but is in death and darkness,
and ignorant of God and Christ; and in such Satan is transformed,
and not in those that are quickened or regenerated.
For such as wanted a proof of Christ`'s speaking in and by the apostles, were, by Paul,
referred back to themselves; '`Know ye not your ownselves,
how that Jesus Christ is in you, except ye be reprobates.`'
And again, '`The Spirit itself helpeth our infirmities,
with sighs and groanings which cannot be uttered; and searcheth all things,
even the deep things of God.`'`" By this time we drew near the town, and then he said,
"`No doubt but you have a good intent m what you do, in traveling so in the world;
but you must have some good considerations for it,
as our priests have gold and silver:`" and mentioned
about three hundred guineas for that time.
I told him, "`No; we whom God had raised up, and qualified in some degree, in this age,
to that service, were advanced above any such mean, base, and mercenary considerations,
as to take any thing from men for this labor, which we bestow freely in the love of God,
and by his commandment, for the common good of men.`"
"`Why,`" said he, "`the apostles were but poor men, and wanted necessaries,
and must have received of the people, or wanted.`"
"`True,`" said I; "`but then they say, '`Having food and raiment,
let us be therewith content.`'
And where that is really the case,
such as are poor among us we would not grudge them that;
but it is very seldom or never so among us, but rather, with Paul, we can generally say,
'`These hands have ministered to my necessities;`' having
no desire that any such thing should be done unto us;
and we generally have sufficient of our own.`"

Then, said he, "`But in case your friends, after some very good sermon,
that pleaseth a great congregation well and generally,
should offer you a purse of two or three hundred guineas, would not you accept it,
being freely given?`"

I replied, "`No; I hope it would be no temptation, if so it were,
which can never be as long as they and I abide in the Truth we profess,
either to give or receive that way.
I should rather be greatly troubled to see so great a degeneracy,
as to subject them to so great an evil.`"
"`Well,`" said he, "`I cannot tell; you say well, and I am apt to believe you;
but if you would not, there are many would be glad of the offer,
and receive it with both hands.`"
"`I believe it,`" said I;
"`for there are too many mercenary hirelings in the world in this age, who,
though they pretend a mission to '`go teach and baptize all nations,`' yet,
as unfaithful servants, if they were sent at all,
sit down where they can have the first maintenance,
and never move till the voice of a better, cry in their ears; and then,
and not till then, they run where God does not send them.`"
"`There is too much of it,`" said he: and so we parted in friendship,
with good wishes on all sides.

Coming to town, and many Friends from other parts, it was soon known,
and many were looking what would be the issue of things.
William Sandwith being there,
he and some others went to the judges and apprized them of matters, and the case,
and how Friends and I had been used by these high church persecutors,
especially the bishop, now here at Kilkenny.
Amos Strettie, and some Friends at Dublin,
procured a letter from one of the intended lords justices to one of the judges,
in his private capacity, not being yet sworn, to see that justice should be done us:
for the government favored us; but our enemies and theirs,
proceeding under a pretense of law, that was not to be overruled,
but inclined to do all they could in honor and safely, which was all we desired of them.

They sent for the sheriff to see the calendar; and not finding the mittimus returned,
they saw our adversaries had no mind to meddle against us, but were willing to drop it,
which they rather advised us to overlook for that time,
since we might in time have our meetings free, which was all we desired.
But that evening one of the judges said in open court, when he gave the charge,
"`That it was treason in any to pull down or deface any public
religious meetinghouse;`" which going quickly through the town,
many rejoiced on our account, it being a great stroke to our adversaries.
I made this construction of it;
as the house was a circumstance and accommodation to the meeting,
who were of more regard than the house, it being only regarded for their sakes,
if it were treason to deface the house,
how much more so thus to disturb and abuse those that met therein;
which some laying hold of, inculcated it among the people,
to our further advantage upon our enemies.

On the 17th, being the first of the week,
we appointed another meeting in the same place--for we were for the same cause still,
the liberty of the gospel, without fear of any -- and went accordingly,
and a full meeting it was, and very comfortable and quiet to all outward appearance.
But I had felt all the night before an inward load and sling from some corner or other,
and expected another bout; and so it happened.
For Patrick Henderson kneeling down to prayer,
in the mean time came in the mayor`'s sergeants; but as civilly as could be desired,
and made no disturbance during the time of prayer; and one of them went out soon after,
but the other stayed.
A little after prayer was ended I stood up and spoke a while,
but had not got well into the matter in my mind, till the other sergeant stood up,
and with great reluctancy, for we all believed it was much against his will,
and in a low voice, said, "`I am sent of the mayor to command you, in the king`'s name,
to disperse:`" but quickly added, "`But if you will not, I cannot compel you,
nor have any orders to force;`" and so went civilly away.
Then I proceeded in my testimony, many things opening to the state of the people,
particularly relating to the duty of a Christian, not to believe only,
but also to suffer when thereunto called.
After which I set forth the nature and ground of persecution, Satan the cause,
and wicked men his instruments in it, as Cain, Jezebel, the high priests, popes,
and prelates; as they might now see in this present case,
though but a shadow to what we had met with, not always by plain and open violence,
but more generally under the specious pretext of law and right:
and then I concluded the meeting in prayer.
After it was over, we heard that one of the church wardens had been there; and he,
and the sergeant who disturbed us--for the other said he had been troubled
in conscience since the first time -- were sent for by the bishop,
who, in the hearing of the judges, examined them about the meeting, what we were doing,
and what we said.
They told him,
"`A good-like man (meaning Patrick Henderson) was at prayer when they came in,
and prayed heartily and devoutly for the king and him (the bishop) too,
and all of them:`" for he prayed for all in authority under him.

Then the bishop asked them if I preached?
And the church warden said, I did.
Upon which the bishop tendered him his oath,
it being me his great spite and envy were bent chiefly against.
Then he had the Act of Uniformity, of the 14th of Charles II. in England,
but the 17th in Ireland, brought before him, and discoursed upon it with the judges;
he thinking it reached us, and would have pumped the judges, and had their opinion on it;
but they were wiser than he, and said nothing, but let him take his own way.
They were staunch friends to the king`'s interest, and were our friends,
as knowing our integrity to the king and his government.
The bishop`'s rage and envy blinding him--if he could at all understand the
Act--he first gave a warrant and mittimus in his own name,
directed to the sheriff of the town,
to arrest and commit me to the common jail for three months, without bail or mainprize,
where this anti-christian judge, for there are many now as of old in the world,
intended I should lie until the full time was expired, without any liberty as before,
if either by hardship or otherwise--for I was then but weak
and tender--he had not murdered me in the mean time.
For he had, before I went out of the town,
sent for the sheriff and reprimanded him sharply for
letting me go abroad in town upon my first commitment,
threatening to have him before the House of Lords the next session of Parliament.

Our afternoon meeting this day being over, which was very peaceable,
for now we had conquered him so far as that none disturbed us,
I found a secret sting as I went to the inn with the Friends from Dublin,
who lodged there; and we were there but a short time,
till I was told there was another warrant and mittimus out against me from the bishop.
I hasted to my quarters at the sheriff`'s house, where I expected it,
and found that such a warrant had been directed to the mayor,
and sent to the sheriff by him to be executed; but it not being directed to the sheriff,
he would not receive it, but sent it back to the mayor.
Then the bishop, mayor, and alderman Connel, and some more, consulted further,
and found their error, as to the bishop`'s giving a warrant himself.
For all the Act requires in the case for which it was made, is, that the bishop,
as ordinary, should certify the offense, only relating to those of his own sect,
to any two justices, or mayor, etc., and then they to grant a warrant and mittimus,
which now the mayor granted accordingly, a copy whereof followeth, viz:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
By John Birch, esq., Mayor of the city.

City of Kilkenny, ss.
Whereas, I received a certificate,
under the hand and seal of the right reverend father in God, Thomas,
lord bishop of Offery; in which he certifies, That Thomas Story, a Quaker,
did this day preach in the said city of Kilkenny, contrary to the Act of Uniformity,
made in the seventeenth year of the reign of King Charles II.

These are therefore, in pursuance of the said Act and certificate,
to will and require you, on sight hereof, to apprehend the body of the said Thomas Story,
and him so apprehended, to convey to the common jail of the said city,
there to remain for the space of three months, without bail or mainprize;
whereof fail not at your peril, and for so doing this shall be your warrant.
Given under my hand and seal this 17th day of March, 1716.

[.signed-section-context-close]
To the several constables and officers of the said city.

[.signed-section-signature]
John Birch, Mayor.

--

This warrant the same sergeant who came last in the forenoon to
disturb our meeting brought to the sheriff`'s house now in the evening,
but delayed its execution for an hour;
and in the mean time Friends advised with some counsellors of their acquaintance,
in town at the assizes; and some of them said it was in the nature of an execution,
so that it might be more dangerous for the sheriff to give liberty,
or to let me be in his house, than before; so that things looked a little harder.

I had not read the Act for a long time, and not remembering the tenor of it,
thought there must be something in it to justify their proceedings,
or else they would not have done it;
and so was resigned in my mind to submit to it for the Truth`'s sake, and was very easy,
being in more danger of too deep a resentment of their base and wicked usage of me,
than of repining at the loss of my liberty;
for I had a view of some things to employ my time in,
which would have made my confinement much more uneasy to the bishop than to me,
for the Lord was with me.
After some time the sergeant came into the room, for we let the door be open on purpose,
and served me with the warrant;
but the sheriff said I should not go out of his house that night, however,
come what would, and so I stayed there.
But the Truth arising in me, I observed the indignation thereof against the bishop,
but no enmity in me against him as a man; and after a little inward concern that way,
I sent for the Act, and read it carefully, and saw they were all quite mistaken;
for the Act had no relation to us, or our meetings or preaching, but to themselves,
the priests and bishops only.
For after the coming in of Charles II. there were many priests who, in Oliver`'s days,
had been in the benefices, the bone of contention they ever strive for,
and finding the sweets of them, would fain have held them,
and yet could not readily swallow the common prayer and services of the others,
which they had furiously opposed and rejected so lately before,
till this law forced them; which they generally complied with,
rather than lose their gains.
This law respected only their own priests,
to bring them all to a uniformity of prayers and worship, or the image of it,
but concerned no other.
Then after a while, I told the sheriff it was false imprisonment,
and desired him and others to take down in writing what time I was arrested,
because there might be occasion for their evidence.
The sheriff seemed a little surprised at it,
that the great bishop and his counsellors should miss it so far,
but took account of the time.

That night I had a strong exercise in my spirit,
and chiefly with the imperious spirit of this bishop; but in the night,
saw and felt him fully overthrown.
Then I was pretty easy and fell asleep.

The next morning before I arose, several Friends had been with the judges,
and they had given their thoughts freely how much this was
against the mind of the government to disturb our meetings,
and did not doubt but this would do us service in the end.
However, they advised, that seeing how times stood,
the talk of an invasion by the Swedes not being over,
and that town a dangerous place to be in prison in,
if the bishop would set me at liberty, they would have chosen that rather.
But I had heard nothing of this;
nor would Friends give any ear more than I to make any application to the bishop;
for that he wanted.

About nine in the morning, whilst I was at breakfast,
came the same sergeant that arrested me, with a message from the mayor,
that he had taken up the warrant and mittimus,
and I was at liberty to go where I pleased, if I would accept of it.
I told the sergeant, "`He ought to send me a liberate under his hand and seal,
and not think I was wholly at his disposal, to toss in and out of prison as he pleased,
but I had my remedy by law against him and them who had used me thus.`"

A little after this came the mayor himself to my lodging, to tell me I was at liberty,
for he had taken up the mittimus, and destroyed it.
I then told him, "`Since that violence, by which my just liberty had been obstructed,
was removed, it was now returned into its own natural course,
and if I could find it consisting with what I professed,
I should consider of ways and means how to do myself
justice against such violent and illegal proceedings;
but as it was a wrong done me for the sake of my religion,
I might probably bear it with patience for that reason,
being sensible enough of the advantages I had of my enemies.`"
He made very little reply, but civilly departed.

After this I went to several places in town,
to take leave of such of the magistrates as had been friendly;
for all the king`'s friends were so, and some Papists were troubled,
as working no good for them by these proceedings.
Truth was honored, and gained by all this;
and the eyes of many were opened to see the bishop, and his spirit and party,
and what many might expect if he and they should prevail,
and many tongues were let loose, after their several ways, to speak their sentiments;
by all which our persecutor and persecutors greatly lost ground,
and fell short of their wicked designs.

Before I departed the city I met with Robert Connel, the tool of this proud bishop,
and told him I was at liberty, which he pretended to be surprised at; but I told him,
"`If I had stayed longer, some of you might have had the more to pay;
for it was false imprisonment, the Act you went upon being about your own priests.`"
He desired me to go to his house, being near, and see the Act.
I told him I had seen it already.
Then said he, "`I have as good counsel as any in Ireland, that says it does affect you.`"
I replied, "`I will debate it with all the counsel in Ireland,
that it has no relation to us at all.`"
Then he wished me well, when he could do me no more hurt, and so I left him.

That afternoon I left the town, and went home with Joseph Firth to Ballinakill,
and the next day, the 10th, had a meeting there, which was not large,
but a good open time,
the Lord being near to comfort and refresh us after so much fatigue;
for many Friends from places round had come to visit me in my confinement,
and some were always with me, and several from this place.
The Earl of Donnegal was in this meeting,
and behaved more soberly than he had ever done before,
being apt to be restless and troublesome at some other times.
That afternoon I went home with John Harris, at Mountrath,
who had been several times with me at Kilkenny.
On the 21st was their meeting-day, the fifth of the week.
It was a large open meeting, many of the neighborhood, Papists and others, being there;
and a good time the Lord gave us together.

On the 23rd I went to Mountmellick, and next day had a meeting there in the forenoon,
which consisted mostly of Friends, and was not very open;
but in the afternoon some of the neighborhood came in,
which I generally observed freshens meetings,
and many things were opened in the authority of Truth, to edification,
confirmation and comfort.

Here I tarried till the 26th, and in the afternoon set forward for Dublin.
That night I reached Kildare, and the next day arrived safely in Dublin,
where I was kindly received, and was at the meeting on sixth-day following,
the 29th. It was a fresh and open meeting, and we were comforted together in the Truth,
which, as the heavens transcend the earth, exceedeth all other enjoyments.
Hearing of a vessel going for Chester,
and I intending for the yearly meeting at that place,
took timely care to secure my passage in it; but the wind not answering,
I stayed there till the first-day following.
The meetings were very large, especially at Sycamore Alley in the afternoon,
where came together a great concourse of people, hardly a greater meeting seen there;
and things were open and well, and the blessed Truth over all,
who is worthy above all forever.

The wind continuing contrary, I stayed still at Dublin,
and was at their third-day meeting, where I had some time,
things opening to many states very closely; and I came away easy,
leaving the better sort under good satisfaction.
Many came to see me before I went off, and among others,
Captain Smith.
He had been in military offices, but being under some convincement,
was at that time under great inward struggles;
for having a commission for being a captain of dragoons then offered him,
he would gladly have seen it lawful and consisting with Truth, to accept the commission,
and sell it, not intending to act by it; but upon some private discourse with him,
he was much straitened about it, and was very tender and humble;
we parted in love and friendship, he owning his satisfaction in that conference.

Having finished my visit in Ireland, on the 4th day of the second month, 1717,
being the fifth of the week, accompanied by several Friends,
I set off from Dublin bay about the second hour in the afternoon,
with a fair and fresh gale off the west, and the next day, about the same time,
arrived at Parkgate, on Chester river, but went not on shore till the evening,
the waves being high.

On the 7th, being the first of the week,
and the day before the yearly meeting for the north,
we had a meeting in the meetinghouse at Chester in the morning, which was not large,
but pretty good;
and notice being given therein of another meeting to be in the afternoon,
in a large place called the Tennis Court,
being the place provided for the yearly meeting, it was held accordingly,
and was much larger and more open than that in the forenoon,
and in a good measure made way for further service.

The day following we held our meeting of ministering Friends, which was pretty large,
there being some of both sexes from Ireland, Cumberland, Westmoreland, Lancashire,
Cheshire, Yorkshire, Hertfordshire, Wales, etc.

The next day the public yearly meeting began in the forenoon,
and was very large and open, that great spacious place being crowded,
with two galleries also erected, as likewise a large upper room,
with windows opening into the court, where were military officers and some others; who,
though willing to hear and see, did not think it safe or proper to be in the meeting,
with regard to some laws then in force, which might have affected some of them.
The Lord appeared with us, to the glory of his own name, and comfort of his people,
and to the general satisfaction of most people there;
for there were present of most sorts and sects in the nation.
In the afternoon it was crowded so that many could not get in,
though some constables who attended without,
kept out the baser sort of the rabble and children, who are apt to take up room,
and make disturbance in such cases.

The next morning some select Friends and elders had a
meeting of conference about the affairs of Truth,
inquiring of one another how it prospered in their several quarters,
where some comfortable and encouraging accounts were given.
That afternoon there was another public meeting,
where were supposed to be near four thousand people; and Truth was over all,
to general satisfaction, and the glory of our great Lord, whose honor,
and the good of his people, and of mankind in general,
are what we aim at in all these things.
That evening the meeting ended, we having increased from time to time,
both in number and openness, the people being more and more ready to hear,
and several were convinced, so as to come to meetings, and own Truth openly.

Intending to go through Wales, to the yearly meeting at Bristol, I went, next day,
the 11th, with Sarah Lloyd, wife of Charles Lloyd of Dolobran, and her son and daughter,
to Rixham, and on the 12th I had a meeting appointed there, which was not large,
for want of due notice; but many things opened fully, and the people were much satisfied.

On the 17th Charles Lloyd accompanied me to New-Town, in the county of Montgomery,
where we had a meeting appointed, which was small, but pretty open,
some of the people being reached and affected with Truth, things opening full and clear,
and the Lord vouchsafing to visit us together.
The yearly meeting of Wales has some time been here, but no settled meeting in the place.

On the 18th we had a meeting appointed in Laneedless, at an inn.
It was small, and in the beginning of it hard, but better in the end,
some persons of some account being there, and some of them much broken.

On the 20th I sent to appoint a meeting at Radnor,
where the yearly meeting was to be the week following, in the place intended for it,
which was in a barn belonging to the priest of the parish,
which he had granted to Friends for that service.
A rare instance of condescension in a man of his function!
But being a moderate, good-natured man, when they made their request, he said,
"`Since we preached Christ, and endeavored to reform the people,
and aimed at the honor of God, he could not refuse it,
though he expected censure for it from his own people.`"

The first meeting on the 21st was not large, but pretty open,
considering the state of the people, ignorant of the way of Truth,
and made way for larger gatherings; for things had opened plain and full,
and a liking was raised in several, who gave a good report to their neighbors.
That night we lodged there at an inn.

On the 22nd, being the second of the week,
we went about four miles to see the widow Price, an ancient Friend, and her family,
where we met with some other Friends, and stayed there that night.

On the 23rd we returned to Radnor;
for hearing that the country people had mistaken our yearly meeting-day,
expecting it to be on the third, which was also their market-day at Radnor,
lest any should be disappointed, we appointed a meeting in the afternoon,
on purpose to answer them; and it was very full and large, and of good service:
for the people being raw, and a little rude, especially the meaner sort,
they were a little cultivated and settled by it,
and the better prepared for the following meetings.
This meeting we held in the town hall;
for some of the magistrates hearing we had the barn,
and that it was too little and incommodious,
were so favorable as to give us some private hints that
we might have the hall for the service,
if applied for; and it was accordingly granted us.

On the 24th began our yearly meeting, which proved so large that the hall was too little,
there coming several people of note, and a great concourse from divers places;
and a good time the Lord gave us, for his blessed power was over all, and honored.
But in the afternoon there were two meetings, one at each place, and both full and well.

On the 25th the meeting for business was in the forenoon,
and at the same time a meeting for worship at the barn, which was large and full,
and serviceable, keeping the people together, and off from our other meetings;
and there were some magistrates in hearing, though they were not in the place,
the laws prohibiting them.
That afternoon being our last and parting meeting, it was in the hall, and very full,
and ended well.

After this meeting a certain widow lady, who, with divers others of superior rank,
had been in the meetings, and well satisfied in the main,
desired some conference with me, for further satisfaction, about the resurrection,
and what we held in that great point.
For I had gone through most points in that creed, commonly, though not justly,
ascribed to the apostles; but she only mentioned that of the resurrection,
owning the thing in general.

She was a grave elderly person, religious and apprehensive;
and being willing to inform her, I stated the matter thus, viz:
"`In order to open this mystery to thy satisfaction,
let me first state and settle the terms.
1st, Of death, as it is applicable to the laying down, putting off,
or departing out of these mortal bodies.
2ndly, As applicable to the mind or soul dwelling therein.
And 3rdly, Of the resurrection of both, and how applicable.

"`By the death of the body, I mean the cessation or departure of the soul out of it;
by which it is left in a state of corruption and dissolution,
as we see by common and daily experience.
And though the soul is of a spiritual nature, and immortal, as to her duration,
yet mortal, or corruptible, as to her true life and primitive state;
being capable of losing it by her own act,
and of departing from her first state of innocency and virtue,
and yet living in an animal and sensual mode.
And this last being of the highest consequence, and rightly understood and settled,
makes way for the understanding of what may be needful in the other,
I shall first proceed upon it.
For the better understanding of what I call the death of the soul,
I consider her first state of life, and what that was.
Man in his first state, as to his soul, or mind, was innocent, righteous, and truly holy,
in the image of God.
For as God is the holy, righteous, just, and true God, so Adam was a holy, righteous,
innocent, just, and true man; and as God is a spirit, so was Adam spiritually minded;
but as to his body, it was of the same mould and form of other men,
his posterity and offspring.
In this state the life of the divine Word, and Son of God,
was the light and law of the life of man, his guide and rule;
through which Word God gave unto man a law of abstinence from
the fruit of the tree of knowledge of good and evil,
annexing this threat and sure prophecy,
'`that in the day thou eatest thereof thou shalt surely die.`'
So long as man continued in the faith and belief of this Word,
he remained in his first state; but as he departed from his faith therein,
and believed another voice, viz: of the evil one, then he died.
But how?
Not a bodily death; for he continued in the mode of his being, as to that,
according to his first intention, living nine hundred and odd years,
and begat sons and daughters; but as to his soul,
though that is not so mortal as to be subject to
the dissolution of the mode of its being,
as the body is, yet departing from the law and life of the divine Word,
it remains in a state of separation from that life; which, after its kind,
is a death unto it, and exposes it to real and everlasting misery.
And this may be further collected from some other Scriptures; as,

"`1st; Where Christ, who is that Word, said unto Martha,
'`I am the resurrection and the life; he that believeth in me, though he were dead,
yet shall he live; and he that liveth and believeth in me, shall never die.`'

"`And 2ndly; where the apostle saith, '`Ye who were sometimes dead in trespasses and sins,
hath he quickened.`'
In the first part of this saying of Christ,
the word life is explanatory of the word resurrection,
that life being the cause and power of it,
and must intend a resurrection from the same death here intended,
which could not be of the body, but of the soul, or mind of man,
in a state of death in the body.
For these words, '`He that believeth in me, though he were dead,
yet shall he live,`' intend a capacity and possibility of faith in the interim,
and same time of this death; which a state of death and dissolution of body,
will not allow: for man is then gone past a state of faith,
or beginning to believe to salvation,
and concluded forever under the effects of his faith or unbelief whilst here below.
And not only so,
but the life here spoken of is intended as an immediate consequence of that faith,
as where he also saith, '`He that believeth on me,
out of his belly shall flow rivers of living water; and this spake he of the Spirit,
which they that believed on him should receive,`' signifying the abundance of
the life of the divine Word to be made manifest in all true believers.

And these words,
'`He that liveth and believeth shall never die,`' cannot be intended of a natural life,
or any life, to continue a believer forever here,
or give him a translation into glory without a natural death.
For the apostles and primitives were all then alive, and they all believed,
and yet all died a natural death; yea Lazarus,
though once raised from the dead by the power of the resurrection,
hath again paid the common debt appointed of God to all men.
Have the words and doctrines of Christ therefore failed`'.`' No, they are true forever;
but not in a natural sense.
For though the saints and just ones of God are departed this life, they are alive in God,
through the work and mediation of him whom God hath sent to quicken the dead,
having believed and obeyed, and obtained eternal life,
in and through the same divine Word, whom Adam disbelieving and disobeying, fell from,
into death, and all the miseries attending that unhappy condition.

"`And this resurrection, as I have observed,
is also expressed in these words of the apostle, as a thing already attained,
'`Ye who were sometimes dead in trespasses and sins, hath he quickened.
Awake to righteousness, and sin not.
As Jesus Christ was raised up by the glory (or power) of the Father,
so also are we raised to newness of life.
The life which I now live in the flesh, is by the faith of the Son of God.`'
The faith of the operation of God, which works by love, wrought by him the word of faith,
even the engrafted Word which createth anew unto good works,
and is able to save the soul.

"`Now, as to the resurrection of the body,
we have never found that so much our concern to inculcate,
it being generally received already by the professors of Christ in every nation:
but opposing some carnal notions of ignorant men about it,
and others being interested against us, as enemies to their filthy gain and ways,
have falsely accused us as deniers of the resurrection of the dead:
whereas we believe the resurrection of the dead, both of the just and unjust.
But as to that forward and foolish question, '`How are the dead raised,
and with what bodies do they come,`' as secret things belong to God,
so we do not presume to explain it, or answer other than the holy Scriptures have said;
but are satisfied in this, that '`God giveth it a body as pleaseth him,
and to every seed his own;`' and are rather in the first place
concerned how to attain the resurrection of the just,
and the right hand of the Father,
through the life of him who is the resurrection and the life,
than to gratify a lust of knowledge of divine mysteries,
rather pertaining to another state, than fully understood,
or to be at all known by the sons of Adam, as such only, here in this world.`"
To this effect I laid things before her; and she answered,
"`That whilst we are low and carnally minded,
we have ideas and apprehensions accordingly; and being used to these bodies,
and unacquainted with abstracted ideas of spiritual beings,
were tenacious of bodily appearances,
till these apprehensions were removed by more divine knowledge.
For if in the resurrection we are to be as the angels of God,
who are all ministering spirits,
we shall have a more excellent mode of being than we can easily conceive in this life,
or can consist with any corporeity of any material form.`"

She asked me, "`Have you read Mr. Locke on that subject, who I think has done it well?`"
I replied, "`I have seen some part of what he wrote against the Bishop of Worcester,
but never read it all.`"
What passed was to the mutual satisfaction of ourselves and some others in company:
but before she retired,
I understood she had been some times conversant with the bishops Burnet and Hoadley,
and having a little book with me of the latter in vindication of the revolution,
I presented her with it; and after some more converse on other subjects,
for she had a general understanding, she took leave and departed,
seeming to be well pleased,
and saying she believed we had been much misrepresented in many things.

Upon the whole it was a large open meeting, and of great service, as many thought;
for Truth was over the people, and many were broken and tendered,
and Friends comforted in the Truth, and in one another in him,
and the Lord had due praise from many humbled and watered souls,
who alone is worthy forever.
Amen.

On the 28th, being the first of the week, I was at the meeting at Haverford West,
which was not large, and also heavy.
The matters which concerned my mind in silence, were the leaven of the kingdom,
and of the Pharisees; their difference in nature, operation and end;
and the different states of souls at last finally centering in the one or the other.
I had comfort in the Lord, but not much in the meeting;
for some things were very sharp and plain to the states of several,
which I did not know how to apply to particular persons;
but had some hints afterwards that things suited well.
And supposing the people would come in more fully in the afternoon,
the meeting was put of till four, yet not large,
there being little concern in that place for the life of religion,
the generality being dead under dead forms.

On the 30th I had another meeting there at four in the afternoon,
being willing to try them further; that was also small, and very heavy in the beginning,
but ended a little more lively.
Also, by the exercise of my mind, I found things at a very low ebb among them,
as to the life and nature of Truth, but some alive.
That day and the next I stayed there, being a little weary with my journey,
but for the most part under an inward heaviness, and had little spiritual comfort.

On the 2nd of the third month, being the fifth of the week, I had a meeting at Jamestown,
which was small, but pretty well.
That evening I went to James Scoone`'s,
who next morning went with me to a village on the sea coast, called Laighren,
where we had a meeting that evening.
It was small, but more lively than any of the former in those parts.

On the 4th I went to Swangill, where I was kindly entertained by Sylvanus Bevan,
and next day, the first of the week, was at their meeting.
In the forenoon it was not large, nor very open,
but larger and more open in the afternoon, yet some heavy thing lay at bottom.
I stayed there the day following,
and had another meeting in the evening at his brother`'s house, which was much more open,
there being several people in hearing about the house.

On the 7th I came to a village called Bridgend,
and that evening had a meeting at the house of a Friend,
who lately settling there among a professing people, had sometimes little meetings,
and many came in.
Things opened much about the light of the Gentiles,
and against that pernicious doctrine of predestination;
by which their foundation was much shaken, and some convinced, who I hope will stand.
This made amends for some hard times in Wales before.
Truth came over the meeting in general;
and though several Presbyterian elders were there, no objection was made that I heard of.
This was a good meeting, to the praise and glory of God, and comfort of several.

On the 8th I went forward to Treverig, to my old friend John Bevan`'s house,
with whom I had been well acquainted in Pennsylvania.
He received me kindly, and the day following I was at their meeting, which was small,
but pretty open, and some people well satisfied in several points.

On the 10th he went with me, though above eighty years of age, to Pontypool,
about sixteen miles, and that evening we had a meeting among a few Friends there,
which was open and comfortable.
He spoke in Welsh, and though I understood not the language,
yet was much comforted in the Truth all the time;
by which I perceived his ministry was from that ground.
His speech flowed very free and smooth,
carrying a proportion and satisfaction to the ear, not easily expressed.
For though the languages of men differ very greatly, yet the language of Truth,
as to the comfort of it, is one in all nations.

I stayed here till the 12th, being the first of the week,
and the meeting being at Pontamoyle, I walked thither, about half a mile,
with my landlord Elisha Beadle.
In the forenoon the meeting was pretty large and open, some of the people coming in,
but in the afternoon was much larger, and clear both to Friends and people,
to pretty general satisfaction; and I was very easy,
the good presence of God seasoning our hearts together.

On the 13th I passed over the Severn,
and fell in that night at the house of Nathan Sturges, about four miles from Thornbury,
intending only to inquire the way of him, but he finding out who I was,
gave me a kind invitation to stay with him that night, which I did.
The next day he went with me to Thornbury meeting,
which was as large as could well be for the time, and very open,
and I was greatly comforted in the love of Truth.
That evening I went on towards Frenchay, to Abraham Lloyd`'s, where I lodged.

The 15th was their meeting-day,
and notice being given that John Everet and
Patrick Henderson would be there from Bristol,
it was a little larger on that account,
but shut up and heavy to us all from some unknown cause.

On the 17th I was at Bristol meeting, which was a little larger than usual,
because of several strangers come to the approaching yearly meeting,
which began the second-day after.
The 19th, being the first of the week, the meeting was very large,
both forenoon and afternoon; and the Lord was near,
and many reached by his blessed Truth.
On the 20th was the meeting of ministering Friends, where were some from divers parts,
and much counsel opened in the wisdom and power of Truth among us,
to our mutual edification and comfort.
On the 21st, in the forenoon, was the public meeting of worship,
which was very large and open.
In the afternoon the men and women`'s meeting were held apart,
for conference and inquiry into the affairs of Truth;
and things were in a good way in the main.

On the 22nd was the parting meeting, which was very full and open,
and the Lord`'s blessed power came over all, to general edification,
and great comfort of many souls; and the Lord, as is only due,
had praise in exalting his own name and glory.
Amen.
On the 24th I was at their week-day meeting again, which was also comfortable,
and I came away in great peace and love with all Friends.

On the 26th I was at the meeting at Bath, both forenoon and afternoon.
It was large both times, especially the latter;
for they said it had not been much larger at any time,
and hardly ever so quiet in that place; for being a resort of such a mixture of people,
they used often to be rude, but were now very still,
and a comfortable and a very good time we had, and ended very weighty and solid.

On the 27th I went to Nailsworth; and Patrick Henderson and some others meeting me there,
we went together the day following to the quarterly meeting at Cirencester.
The meeting was not large, considering the extent of it, nor very open,
yet in the main well and edifying.
One thing I observed which was very unusual, and not of good consequence:
in their meeting for business, some introduced a letter, directed to the meeting,
from a person who intended to stand candidate as a
member of Parliament for the county of Gloucester,
or to solicit for some friend of his that way.
It was read in the meeting, purporting as aforesaid, and in a friendly style,
well adapted to the intent.
I observed some of the younger sort to be much tickled and pleased with it;
but the wiser sort were not so.
Then finding a concern on my mind to caution the meeting, I told them,
"`That the apostle Paul, on a certain occasion, made use of a Roman privilege,
on account of religion; and I thought it was not unlawful for such among us,
who had native English privileges, to use them according to their true intent.
But as our meetings are altogether of another kind,
respecting religion and the worship of God only, and such things as relate thereunto,
and not matters of human policy or state,
it might be of ill and dangerous consequence many ways
to introduce such things in any of our meetings;
but rather let them be concerted by particulars concerned,
with such persons as they thought most proper for representatives in that station,
having regard to the integrity and abilities of the person, and the public good.`"
Several fell in with this, and the rest were silent, and all ended in peace.

On the 29th, at four in the afternoon, we had a meeting at Farrington,
which was small and heavy in the forepart, but ended pretty well.
On the 30th we had a meeting at Bishop`'s-Town, in a barn,
where some of the town`'s people came in;
but to me the meeting was very dull and dead a long time:
and after some Friends had spoken what was in their minds,
the meeting was silent a while, and then I stood up and told them,
"`That there had not been more mischief done among the children of men by any one thing,
in most ages of the world, than by men`'s running in the name of God, as his messengers,
when he did not send them; who not only did not profit the people at all,
as set forth in the 23rd chapter of Jeremiah, but did much hurt by misguiding them.
And though it might look strange to some, as a meeting had been appointed,
and the people invited, that I said nothing;
yet as no consideration of that kind ought to prevail with me to run in my own will,
to speak of the things of God among them; so it might be better, both for them and me,
if I were silent, than do it.
For though the apostle was come to so clear a distinction in himself,
as to be able to say, '`This say I, and not the Lord;`' and again, '`Thus saith the Lord,
and not I:`' this I, without the Lord, having in many others done so much hurt,
I would rather at that time hazard their censure, and what might follow from thence,
than be too busy with the things of God where he did not concern me.
And though the day before, and many other times,
I had been rightly concerned from the Lord;
yet it did not follow that I might employ myself that day when the Lord did not fit me,
and require it at my hand, lest instead of comfort, I should procure reproof from him;
and in seeking my own honor, dishonor the Lord, and so become a transgressor.`"
And so, recommending them to the teachings of the grace of God,
I sat down for a little time, and then stood up and said,
"`I would not have any think I have smote at any of my
brethren here who have been concerned in the meeting;
I have only spoken what was simply with me, as relating to my present state.`"
And being set down again, I was broken in spirit by the income of the love of Truth,
which reached several; and in some time I was concerned in prayer,
and the meeting ended well.

On the 31st we came to Newbury, and had a meeting, which was pretty large and open,
and things were comfortable.
After the meeting we went to the next village with the widow Jane Stainton,
where we tarried that night, and the next day, being the 1st of the fourth month,
went to Reading.

Those and their posterity, who had formerly separated themselves from Friends at Reading,
being, since I was here last year, returned and become one meeting,
I found it considerably larger, and in the morning I was much comforted in it,
and had an open time among them; yet afterward found a secret load,
which increasing till the afternoon meeting, remained for some time;
but at length Truth came up, and in some degree dispersed it.

After that I had some time in the meeting, much about predestination and baptism,
many people of different sorts being present, and generally quiet and brought under.
One particular passage concerning baptism came thus, viz:
"`That could not be water baptism mentioned in these words, '`Go teach all nations,
baptizing them,`' etc., for if that had been water baptism,
and if the apostles had had power thereby to baptize with water,
and that power and commission devolved on all succeeding
ministers and apostles to the end of the world,
then certainly upon those rather who were contemporary with the twelve apostles;
but the apostle Paul was an apostle contemporary with them,
and not one whit behind the chief of them, and yet Christ sent him '`not to baptize,
but to preach the gospel;`' which gospel was sufficient without baptism with water,
since repentance and remission of sins was to be
preached in Christ`'s name unto all nations.
If then it was no commission to Paul, it was none to any other;
and since he had no power thereby to baptize with water, none could succeed him in any.
So that all this pretense to succession is vain and false;
and a man may be a true minister of Christ, and thoroughly furnished, without it;
since the substance of the gospel, in a minister,
is to '`turn them from darkness to light,
and from the power of Satan unto God,`' who is light; and in the people,
it is to believe in that light, walk in it, and obey it, and so become children of it,
and heirs of eternal life, in him who is heir of all things,`" etc.
I became much easier, and was kindly received by Friends there of all degrees;
all old things being laid aside, and not once named among them,
as I had before advised them, in the mind and wisdom of Truth,
through which I had been opened to that end the year before.

On the 3rd I went to Ruscomb, to see our ancient and honorable friend William Penn,
still remaining under the effects of a fit of the apoplexy,
much hurt as to his memory and expressive faculty, but still living in the better part.
I stayed there that night, and next day returned to Reading to their week-day meeting,
which was pretty comfortable.
After dining with Robert Peacock, one of the returned Friends, and his family,
I went to Ruscomb, where I stayed till the 6th, in the morning,
and went from thence to London.

The yearly meeting coming on,
it was considerably larger and more peaceable than for many years past.
For those Friends who had so much struggled for the affirmation,
the common occasion of strife, having obtained their end, were now quiet on that side;
and those who could not for conscience receive it, continuing in Christian patience,
bore the yoke willingly, though alone, and more heavy than before,
upon that bottom were quiet: and besides, many satisfied Friends sympathizing with them,
and the intention of solicitation for further ease to the whole being kept on foot,
things were quiet.
It was a crowding time; and I rather being willing to be straitened,
than to straiten any, suffered much in my spirit,
for want of opportunity to clear myself, there not being, for the most part,
one minute`'s time between the end of one testimony and the beginning of another,
an indecency I have ever disliked; however, things in the main were pretty comfortable.
At the meeting for business, being requested by the meeting,
I gave them a relation of my travels since the last yearly meeting,
which I observed gave some satisfaction.

I stayed some short time in the city after the meeting,
and was at several of the city meetings,
where I found my spirit more and more at liberty.
But the summer time being fittest for travel, and having some other places before me,
I departed the city on the 2nd of the fifth month, 1717, and that night went to Hartford,
and on the 3rd was at a yearly meeting there, which was pretty large and open.
On the 4th I went Hitchin, and was at their meeting that day.
The beginning of it was very heavy and dull, a dead spirit being over several;
but in the end the Lord quickened us together, and the most were comforted and helped,
and the rest reproved.

On the 5th I was at a yearly meeting at Baldock, which was pretty large and open,
but attended with a spirit of heaviness in some,
though the doctrines of Truth were clearly published in the authority and wisdom of it,
by several brethren.

I stayed here till the 7th, and being the first of the week, had a meeting at Royston,
which was the largest that had been seen there, and the greatest part not Friends.
It was a very open good meeting,
and many things the Lord disclosed to general information and satisfaction;
and Friends were comforted together in our dear Savior,
and in a sense of his fresh visitation to many.

Next day went to Cambridge, where the meeting is small; but many of the scholars came,
and filled the house above stairs and below, and many crowded without.
They were generally wild and wanton, their countenances airy, talking,
whispering and laughing among themselves, and rude with the women; which,
observing soon after I went in, and finding my spirit over them, I said to them,
"`Ye look like gentlemen; and if ye are, then behave accordingly.
Be still, and if you hear any good thing, make the best use of it;
but if you do not like it, then let it pass for nothing with you; it is not imposed,
but offered.`"
They were much quieter for a time.
What I began upon was, some qualifications both in preacher and hearer,
necessary in preaching the gospel.
The teacher, as the oracle of God, being qualified by him with understanding and power,
not acquired by the creature, but given and inspired by the Creator;
and the hearer ought to be still, sedate, and unprejudiced, free from enmity and passion,
that taking things into his understanding, he might judge aright of what he heard.
I then proceeded to the nature, end and advantage of true silence,
as commanded of God by the prophet of old,
and consisting also with a state of glory in heaven;
with the difference between outward and inward silence; the former from words and noises,
and the latter from all evil thoughts, imaginations, and desires,
where sin has its beginning in the creature,
so as to be chargeable with it in the sight of God.
Then things opened clearly concerning the law, both as given by Moses to the Jews,
and also as written in the heart by Christ,
the mediator of the second and more excellent covenant;
and how both Jew and Gentile became guilty before God, by the breach of this law,
to whom one Savior Jesus Christ is sent--but under a two-fold administration; to the Jew,
as born of the Virgin, according to God`'s promise to them; and to the Gentile,
as a light and covenant to the people.
That the Jews who received him in that administration, knew him also in a greater,
by the work of regeneration, through which they became the children of God;
but they that rejected him, were also rejected of God,
as the main body of that people were.
And that so many of us Gentiles as reject Christ as he is light,
and so promised of God unto us for salvation, are also rejected of him,
and of the Father.
But as all have sinned, so the love and mercy of God are to all in Christ,
to give them grace by him;
that believing in him and obeying him and the teachings of his grace, they may be saved.
For as he said,
"`Repentance and remission of sins must be
preached in my name unto all nations;`" by which,
as it appears, all, at one time or other want repentance and remission,
through the breach of the law of God; so also it is plain by the holy Scriptures,
that there are two parts of sin, as well as a two-fold administration of Christ.
The one is the act, acted against the law and will of God;
and an act once done can never be undone, but remains forever:
the other is the effect of that act inwardly in the heart or soul of him that acts evil;
that is, the stain, pollution, or defilement, and the death it effects there.
As Christ said, "`It is not that which goeth into the man that defiles him,
but that which proceedeth from him; for out of the heart proceed murder,
fornication,`" etc.
But Christ being offered upon the cross,
is a propitiation for the sins of the whole world,
so far as they are acts against the law,
but applicable and effectual only as men believe in that light, and walk also in him;
that is, in obedience to the rule of his light and grace,
inwardly made known and revealed.
For, saith the apostle, "`If ye walk in the light, as he is in the light, then (that Is,
in that case) ye have fellowship one with another, and the blood of Jesus Christ,
his Son, cleanseth us from all unrighteousness.
And this also shows,
that the stain and pollution of sin is done away by the
inward appearance of Christ by his Holy Spirit.
And again, as saith the prophet Malachi,
"`He shall sit as a refiner and purifier of silver;
he shall be as fuller`'s soap:`" all which signify a perfect and thorough cleansing,
as well as pardon; and without which cleansing, men cannot enter God`'s kingdom,
for there is no unclean thing can enter there:--
with many other things of great importance,
too long to be recollected here.
And though at sometimes a fit of laughter would pass as through their whole company,
being a thing of course among them, yet I perceived some of them very solid,
and truly affected with Truth;
which silenced and quieted most of them before the meeting ended.
In the main I was well satisfied with the meeting, and so also were Friends,
who did not look too much at their behavior; which they rather do wantonly,
and as what some of them think they ought to do of course at a Quakers`' meeting,
than in malice or wickedness;
and I hope things will so stick with some of them as
that they will not be able to shake them easily off.

Next day, about six in the evening, had a large open meeting at Hadnam;
the people having finished their labor, came in fully,
and the Lord manifested himself to us, and opened the mysteries of his kingdom largely;
and Friends and people were satisfied.

On the 10th I went to Chatteris, where the meeting was pretty large and open;
and a person being present--which I knew nothing of till after
it was over--who was fitting himself to be a priest,
and some of his sort with him; things opened very clearly concerning antichrist,
and his ministers and kingdom: that he began to work in the days of the apostles,
and in some who were professed ministers of Christ, viz: Diotrephes, a high, proud,
insulting, domineering man, who threw men out of the church by his own authority;
and Demas, who having a ministry,
forsook it and the apostle for the love and lucre of this world.
And such as preached up the law, circumcision, and outward ordinances,
to glory in outward and fleshly things; who in time also, according to the apostle,
did not only make merchandize of the people for filthy lucre,
but exalted themselves over kings, emperors and princes, and also lorded it,
as at this day, over the heritage of God, and church of the Lord Jesus,
who had from that time hitherto suffered by them.
But that the time is now near wherein that evil spirit,
and all that shall in that day be found in him, as members of him,
whether as lording Diotrephes, covetous Demas, or legal and ceremonial formalists, who,
neglecting the substance, glory in shadows, and in their, own inventions,
together with all their company and employers among the people, shall be confounded.
For as the days are now come, spoken of formerly,
wherein men will not endure sound doctrine, but have heaped, and do heap to themselves,
teachers after their own hearts`' lusts, having itching ears;
that day shall cleanse the earth both of the buyer and seller,
of that teacher and his employer and hearer.
For as the Son of God said, "`All the blood that has been shed,
from the blood of righteous Abel, to the blood of Zacharias,
whom they slew between the altar and the wall,
shall be required of that generation;`" being of that evil one their father the devil,
who had done it all along; even so also are the days hastening upon apostate Christendom,
wherein all the blood which hath been shed,
from the holy blood of the blessed Son of God upon the cross at Jerusalem,
to all that shall be shed to the coming of that day,
shall be required of that wicked generation, who call themselves Christians, and are not,
but do lie; and are, and will be of that evil one, antichrist, their father,
whose works of murder and destruction they will do,
till that day of the Lord shall destroy them,
wherein Jesus Christ shall be revealed from heaven in
flames of fire against him and them all,
and shall leave them neither root nor branch;
for they shall be turned into hell together, and punished there forever and ever.
Many other particulars opened, which some Friends, after the meeting, said,
were so close to him and them as if done on purpose.
It was a good and open meeting.

On the 11th I went to Ramsay, and had an evening meeting there about six,
which some Friends thought the most proper time, it being their fair day,
and they expecting some of the people might come in after the fair was over;
but they were so taken up with the fair and business, and the vanity thereof,
which was great, and had so little desire after good, that we had few but Friends;
but the Lord was pleased to visit and comfort us together in his love,
and it was a good meeting.

On the 12th I went on to Huntington, John Everet being with me,
as at the two last meetings; and there the Lord gave us a very open and comfortable time,
there being few except Friends, but of these from several parts about where I had been,
and some from Royslon.
On the 14th, being the first of the week, I went to Ives, where we had a large, good,
open meeting, many Friends and professors of several denominations being there.

On the 15th I went to Wellingborough, and the day following had a meeting there,
about six in the evening.
It being the hay-harvest, people could not well attend sooner.
It was late gathering, but in the main, a good meeting,
the people being generally solid and sober, and a considerable number.
On the 17th I had an evening meeting at Northampton, which, though not large,
was an open good time.

On the 18th I was at their week-day meeting at Bugbrook, which was a good meeting,
and on the 19th at Kingstrop, which was a large open meeting,
and many reached by the Truth, and well satisfied.
There had been one or two meetings in that town before,
and at the last was John Fallowfield, which was held in the courthouse;
but the priest being filled with envy,
and pretending to be a freeholder by his gain in that parish,
and consequently interested in the house, used means to hinder us of it;
so that we had our meeting in a Friend`'s house, licensed for that purpose,
there being no other Friend in town.

On the 21st I was at a meeting appointed at Burton,
where there had lately been a dispute betwixt some Friends and Baptists,
which had not come to any great matter on either side.
The meeting was very large, being held in a great barn,
and considerable openness among the people.
The Lord opened my understanding upon several subjects, and gave me utterance;
particularly with respect to faith in the Lord Jesus, repentance from dead works,
the doctrine of baptisms, laying on of hands, the resurrection from the dead,
eternal judgment, and full perfection; what it is here,
and what also regards another world.
It was an open profitable meeting, and many were satisfied concerning the Truth;
and there being Friends and people from many places,
this gave a general alarm throughout the country, and was helpful on that account,
to the following meetings.
I was much spent in this meeting; but after some refreshment,
went back to Wellingborough that evening.

On the 22nd, in the evening, I had another meeting appointed at Isham,
where came several of the contending Baptists, as they had been at Burton;
but made no objection,
though some of the points they had contended with Friends were there spoken to,
as baptism, the Scriptures, etc.
It was a good meeting, and the people generally satisfied.

On the 23rd, in the evening, I had a meeting at Wilby.
There had been but one meeting held there before, by John Fallowfield.
This being after the people had done their day`'s work, they came pretty generally,
and were very quiet; so that we had a good open time.

On the 24th, about six in the evening, I had a meeting appointed at Moulton,
where came a few sober people, and sat down with some Friends,
and others stood behind the corners, and all about at a distance;
and finding something in my mind to say among them, as soon as my voice was heard,
they came in fully, as is frequent in new places; so that we had a large meeting.
The Lord was pleased to open many things for their edification and convincement,
and to the opening of the understandings of several in some degree;
and it was a good time to many.
I found my strength much spent, and my spirits very low afterwards,
the weather being hot, and my love much to the people in the Truth.
But the Lord, who never fails, soon repaired my wants, both spiritually and temporally;
for, after some refreshment, and a good night`'s rest,
I was very much comforted next morning.

A meeting being appointed to be on the 26th at Arthingborough in the evening,
it was pretty large and open.
There I was concerned about infants, their salvation,
and the ignorance and presumption of such as
affirmed there were thousands of them in hell;
and the wickedness of that pernicious doctrine
of personal predestination and reprobation.
Next morning I heard that a Presbyterian teacher had, not long before,
been preaching such hideous things among them;
from under whose heavy yoke some were that evening relieved.

On the 28th, being the first of the week, we had a large open meeting at Thingdon,
where several points opened to general edification and satisfaction.
On the 29th I had another appointed meeting at Ranee: it was not large,
and a little heavy.
Presbytery prevailing there, and the people dead; but some were a little awakened,
and it ended well.
On the 30th I was at an evening meeting at Bridgestock, which was not large,
but very open, and the people satisfied.

On the 31st went to the meeting at Kettering,
where it fell to my share to expose that destructive
doctrine of personal reprobation from eternity,
with sin term of life, and salvation in the end;
the insignificancy of religion where such tenets take place,
and the grievous error of such as reject the covenant of light,
and forge to themselves a covenant of works, which they never keep,
but are miserable sinners to the end of their days.
Things came with good authority, and an open meeting it was to many.

On the 2nd of the Sixth month I was again at Bugbrook,
where we had a large and good meeting.
Many things were opened to the people; as, 1st; A state of sin in all nations.
2nd; Repentance and remission still to be preached in every age, in the name, virtue,
and power of Christ; and all to be directed to him as the light,
and God`'s covenant to the Gentiles, and believing and walking in him who is that light,
may have holy fellowship one with another, and the blood of Christ, in that case,
to cleanse them from all unrighteousness.
3rd; Against the ministers of antichrist, their rising in the days of the apostles,
and among them; their going out, and who they were: John says,
"`They went out from us,`" etc., viz: Demas, the covetous; Diotrephes, the proud, lofty,
and imperious;
with such others as drew the people with feigned words to the ceremonies of the law,
and made merchandize of them; and whilst they promised them liberty,
themselves were the servants of sin.
But as the best security against such seducers, the apostle directs all to the anointing;
that is, to the Spirit of Christ in their own hearts.
4th; Against tithes, and all among ourselves who have not been true on that account,
or in other sufferings; that they are departed from the faith,
and are as the stony ground, fruitless and lifeless;
and though they may hang on in outward communion, as coming to meetings, etc.,
yet not of the same spirit with the faithful.
This was a solid meeting, and the people satisfied, though things came exceedingly close,
especially at last;
where I remarked that both the buyers and sellers of the oil in the parable
of the ten virgins were excluded whilst they were at that work.
On the 4th, being the first of the week, I was at Harborough,
where we had a large open meeting,
there being Friends from several other places where I had been,
and many of the town`'s people of several sects;
and the name of the Lord was exalted over all.

On the 5th we had an appointed meeting at Desborough, at the house of a farmer,
in a large hall; where came a considerable number of people,
and things opened full and clear to their states,
and we had an open good meeting to general satisfaction.
On the 6th I was at a meeting at Norton, which was small, by reason of the harvest,
consisting only of a few Friends; but the Lord was good to us, fulfilling that promise,
"`Where two or three are gathered together in my name, there am I in the midst of them.`"
On the 7th I went to Leicester, and was at their meeting.
It was small, consisting only of Friends, and heavy in the beginning,
some giving way to a drowsy spirit; but the faithful continuing in a true concern,
we were quickened by degrees, and the Lord gave us a good season together in the end.
There I stayed at my old friend John Brookes`'s house till the sixth-day,
when fell out their general meeting, which was small, and much as the other before;
but some of the town`'s people were there, and a little affected with Truth.

On the 11th, being the first of the week, I went to Cileby, to another general meeting,
that is, several meetings in the country,
usually meeting at certain interchangeable places, which was pretty large and well.
