== Chapter 16

[.offset]
+++[+++After being at some meetings he went to Bath, where he remained some time,
and attended the meeting on the 4th of eighth month, respecting which he remarks:]

On the 4th I was there again.
In the forenoon we had but few strangers,
but in the afternoon came a great company of the nobility and gentry,
so that the house could not hold them, and all the yard before the door was filled.
And though, in the beginning of the meeting, some of them,
as they are used in their own worship, were a little airy and pleasant among themselves,
expecting something to make them diversion, being wholly unacquainted with Truth,
and the way of it, and lying under the prejudices of false rumors;
yet in a short time many of them began to change countenance,
and look with another aspect; for God, who wills the good of all men,
favored the opportunity, and gave me several matters of moment to declare among them,
to the surprise of some, and general liking of most, if not all of them,
except some few Papists and their favorers,
whose principles and errors were a little exposed.
Finding Truth over all, and love towards them, after the service of the meeting was over,
I told the auditory,
that we were to have another meeting there on the fifth-day of the week,
which they call Thursday, and we should be glad of their company;
and they seemed generally pleased with it.
But for some reasons the meeting being put off a day longer, we gave notice accordingly,
and it had the desired effect; for there was so great a concourse,
especially of the quality, so called, that the house could not hold them,
and many were in the yard;
but as the ladies and women were generally preferred to the seats,
several of the nobility stood great part of the time with great patience and attention,
suitable things being opened to them, and the meeting held between two and three hours.
That day Truth gained ground considerably;
for as many of them had before odd notions of us and our way,
they now began to see we were a people greatly abused by rumors,
and the world imposed upon concerning us, our way and worship,
and were generally well satisfied.

On the 7th, being the fourth of the week, I had an evening meeting at Bradford,
which was pretty large and open.
That night I lodged at Dr. Clark`'s, and the next day was at a meeting at Cosham, which,
though not large, was a good meeting.

On the 11th I was at Bath again, and as many persons of rank, and others,
were by these several meetings generally alarmed, we had more than we had room for,
especially in the afternoon; and many went away out of the yard and lane,
who could not bear the weather, and to stand so long a time.
A good season the Lord gave us to general satisfaction;
for the blessed Truth was over all, and many of them reached,
and went away with solid countenances.

On the 12th I went with Caleb Dickinson to Chew-Magna, to the marriage of Martha Vickris,
youngest daughter of Richard Vickris, who, in his day, was an honest Friend,
and a man of good sense and reputation, and Robert Button of Taunton;
which was solemnized on the 15th, at the meeting-house there.
Many of their relations, and generally the neighborhood, were present; and among others,
sir William Cann of Bustleton,
whose sister had intermarried with Robert Vickris`'s eldest son,
and heir of the said Richard,
with whom I had much discourse afterwards on many points of religion, to satisfaction.
He and his lady, with some others of such sort,
having been well pleased with the meeting,
both with the manner of the celebration of our marriages, and what they heard;
he obliged me to call at his house, if I should come that way.
The day before the marriage I was at the meeting at Belton, two miles from Chew, which,
though small, was very open and comfortable.

On the 16th I returned to Bath, and on the 18th, being the first of the week,
we had the lord Carpenter, general of the forces in Scotland, and his son,
at meeting in the forenoon, and some other strangers.
The subject matter was concerning Christ the foundation, and that Peter could not be so.
I do not remember I was ever more clearly opened upon it than at that time;
nor did I ever observe any person more grave and attentive than he during the time of it,
and I thought, sometimes affected with the power of Truth, and what he heard.
It was a good time to Friends, and we were thankful to the Lord that gave it.

Some time before this, divers poor people came up to Bath,
in order for help by the waters against their several diseases,
who had not wherewithal to procure accommodations for
so long a time as was needful for their cure,
and were not permitted to beg in public,
the city being often oppressed by the resort of common beggars,
who rather make a trade of their real distempers than come there for cure,
and too often make false pretenses of ailments, to deceive, where there is nothing real.
Yet being willing to relieve the truly necessitous,
proper notice had been given the week before in our meeting of such an intention,
and Friends desired to come prepared for a contribution that way at this meeting;
the thing being distinctly stated, lest any should think it was for our own poor,
or for any other secret or particular purpose, of which some might be jealous.
The meeting was very large this afternoon, and several of the nobility of both sexes,
and others present.
Good part of what I had then to say was concerning that
creed commonly called the apostles`',
and the interpretation of it;
some things concerning the state of both Jews and Gentiles at the coming of Christ;
the gross idolatry of the latter, and apostasy of the former;
and that great part of the supposed Christian
world now at this day is under as great idolatry;
instancing, in the worship of a piece of bread or wafer in the Romish church,
and the inconsistency of transubstantiation both with sense and reason; both which are,
and ought to be, used in the Christian religion, and both helped and improved;
but falling in also against Deism, so much at this day prevailing, I said,
"`Reason is not to be the sole guide of man, but the light and Spirit of Christ;
which being above reason, and the true illuminator and rectifier thereof,
if the sure and unerring guide unto all that believe and truly follow him.
This was a great and glorious meeting,
where many of the nobility and gentry were present:
but that which was the crown and glory of all, was the presence of the King of kings,
and Lord of lords, among us,
whose Truth was over all in the demonstration of his wisdom and power, to his own glory;
and many were that day sensible of it.
This meeting was most generally satisfactory to all sorts,
and as it was our parting meeting,
a general solidity and awe were over the most of the audience of all ranks.
The meeting held near three hours, till it began to be dusk,
and I was concerned in testimony about two hours and a half;
and though many of the quality, as well as others, stood most of the time,
I did not observe any of them express any weariness or other dislike.

The meeting being ended, we proceeded to the collection; and before we began,
John Eccleston of London, who being there for his health,
had been very serviceable in procuring some great persons to come to our meetings,
and in answering questions among them, where any thing had not been well understood,
made a short speech to this effect:
"`That though this collection was intended wholly in our own communion,
yet being for poor people not of our own sort, we were not so narrow,
or tied up to ourselves on such accounts,
but that the charitable contributions of others would be acceptable to that end.`"
Upon which several did contribute liberally with us.
And lest any should, through malice or evil surmising, pervert our good intentions,
we desired that some one or more of their sort might be
concerned to see the distribution according to the intent,
which was accordingly done; but notwithstanding all our precautions,
this charitable action was perverted, as I afterwards heard,
by some who made an injurious and perverse remark upon what John Eccleston said,
that we had first drawn people to our meeting as if we had expected nothing from them,
and when there, obliged them to a contribution by another speech,
to the support of our own poor, or worse; all which I had an opportunity to clear.

I was there again on the 25th, being the first of the week,
where the meeting was not large,
great part of those who usually came to us being out of the town;
but some other strangers being there, we had a pretty good meeting:
and finding myself clear, I now began to think of some other places, and accordingly,
on the 27th I went to Bradford, where we had an evening meeting, pretty open and well.

On the 28th I went to Warminster; but happening to be their fair day,
the Friends there gave no encouragement for a meeting that evening,
saying the people would he attending the puppet-shows, etc., which usually came to fairs;
and as for themselves, there would be but two or three out of two families at meeting,
if we had one; but if I would have one the next day, they thought I might.
Finding things thus,
and notice of a meeting at Froom being already given to be the evening following,
I passed them by, though with some inward trouble.

On the 29th I went to Froom, and that evening had a full open meeting there,
in a large new meeting-house of the general Baptists,
which they readily lent us for that occasion,
our own place being too small to accommodate the number expected.
There was a pulpit finely carved and set off, which might have been free for me,
but I declined it, and took a seat with two or three Friends in a place under that,
enclosing their communion table; and when I found my time to begin to speak,
though the table was the most convenient place to stand upon, vet I declined that,
lest I might offend some of the weaker sort of their people, most of whom,
with many others, were present.
The subject was, God`'s universal free grace through Christ unto all people:
and I do not remember I was ever more fully or clearly opened upon it.
A good time the Lord gave us, not only to the satisfaction of Friends,
but of all in general.

The meeting being over, as I came out of the pew, an ancient grave woman,
a particular Baptist, as I suppose, asked me this question,
"`That if Christ died for all, why were not all saved,
since there could be no insufficiency in the
blood of Christ to answer the end proposed?`"
I answered her,
"`That if she had taken good heed to the whole of what was said in the meeting,
that point had been made very plain and clear to her understanding;
but since she had not, I further said,
that there is no insufficiency in the offering or offerer, but in mankind,
that do not believe and obey: '`For this is the condemnation of the world,
that they have not believed in the only begotten Son of God.`'
Again, '`I am the light of the world,`' said Christ the Lord,
'`whosoever followeth me shall not abide in darkness.`'
And again, '`This is the condemnation of the world, that light is come into the world,
but men loved darkness rather than light, because their deeds are evil.`'
And again, '`Whatsoever things are reproved are made manifest by the light;
for whatsoever makes manifest is light.`'
All this is said of Christ, who is that one propitiation for the sins,
not only of the apostles and those that had already believed,
but also for the sins of the whole world, who at that time bad not yet believed,
but were still in unbelief; which offering being on God`'s part,
in discharge of his promises before by his prophets,
the way that the promises become effectual unto us is, to believe in this light,
that we may be the children of God in him.
And first believing in this light, and walking in him, that is,
in obedience to his manifestation and discoveries,
then the blood of Christ cleanseth from all sin, and the promises are so applied;
but the unbelieving and disobedient are under condemnation still, rejecting him,
the light of the Gentiles, in whom the covenant is, and who is that covenant,
and is altogether sufficient and complete in himself,
though we may fail by our own neglect.`"
This answer she received and was silent, and went away with some signs of respect.

On the 31st I went to Bristol, and stayed there some time.
From thence I visited some ancient Friends in the country near,
and also several meetings, as Frenchay, Portshead, Claverham and Sidcot;
and having an invitation by sir William Cann to his house,
I went thither one day from Bristol; but he being from home,
his lady being a very civil good-tempered person, obliged us to stay dinner with her.
In the mean time came Cobb, esq., and his wife and a young maid, a cousin of hers,
and after some civilities on all hands,
we fell into discourse on various subjects and points of religion,
where I had an opportunity to clear several to them;
and also that aspersion mentioned before,
relating to our collection for the poor at Bath,
whereof I found some of them had received false notions,
and all ended in civility and good temper on all hands.
We returned that evening to Bristol.

There are at this time in that city a young people, the offspring of Friends,
a considerable body,
who love Truth when preached to them in the life
and demonstration of the wisdom and power of it;
but many of them, not yet much acquainted with the powerful work of Truth in themselves,
are not apt to relish the harsh and unsavory discourses of some among themselves,
who very unwarrantably and falsely apply to them, and even to the men`'s meeting there,
all the woes and judgments against old Israel in their most degenerate state,
of which these young people and others, knowing themselves not to be guilty,
though perhaps in some things they want amendment, are greatly offended and hurt,
judging the prating of such to arise from no other ground than their own ill-nature,
heightened by some private offenses taken at some particulars,
against whom they cannot have revenge in their own way.

I had some open and good times among them in the love of Truth, the visitation whereof,
I know, is towards them.
Many important Truths were opened among them,
and the way of Satan`'s temptations in the thoughts and imaginations of mankind,
exposed to the meanest capacities, and the necessity of regeneration,
by the holy convincing power and Spirit of the Lord Jesus, inculcated and enforced;
using all decent plainness with them concerning their present state.
And as it was in the love of Truth, they received it in the same ground:
and my ministry reaching their understandings, and not their affections only,
I hope it may be serviceable to many of them; observing that,
as I came in love among them,
they generally paid me a regard arising from the same ground;
though they despise the speeches of those who know not their own spirits,
or ground of their own ministry, which gives no testimony for Truth,
nor ascends higher than its own fountain, begetting harsh ideas like itself,
but nothing that is sweet or lovely.

On the 22nd of the tenth month I departed thence,
leaving them in mutual love and friendship,
and the next day in the evening I had a good time in a ministering Friends`' meeting,
mixed with elders, at Glastonbury, where the quarterly meeting being next day,
the Lord gave us a comfortable meeting.

On the 25th I was at an appointed meeting at Grinton.
Our friend Philip Watts, landlord of the parish, of a considerable estate,
was in Ivelchester prison for non-payment of church rates, so called,
by the malicious prosecution of an ill-natured person in the neighborhood,
and I suppose one of his own tenants,
who being instigated and supported by some of the
members of the ecclesiastical court at Wells,
and others of that sort, an old anti-christian engine of great oppression upon mankind,
had been thus very mischievous and wicked.
This our friend bore with Christian patience,
though separated from the comforts of his new married wife and family,
and necessary concerns of life.
I was concerned to take some notice of the circumstances that day in my testimony,
which was very open in the love of Truth to the faithful.
Many truths opened to the people for their information and help,
and we had a good season, to general satisfaction.

I stayed there that night, and on the 26th went to Longsutton.
The day following, being the first-day of the week,
I was at their meeting in a large new meeting-house,
where we had the company of some hundreds of people, and two very open meetings.
On the 30th I was again at their week-day meeting, which was fresh and well,
and that evening had a large good meeting at Summerton;
for though their meeting be small of itself, the people came in fully,
and we had a good time, things opening freely to the state of the meeting.

On the 1st of the eleventh month I was at a funeral at Ivil,
where we had a large meeting on the occasion, and I believe, to general satisfaction;
for the truths of the gospel were opened freely, with great authority and demonstration.
After some refreshment I returned that night with Samuel Bownas to Lymington,
where I stayed till the first-day following,
and then had a large open meeting in the town-hall at Ivelchester.

On the 4th I went to Grinton, upon the occasion of the death of the widow Powel,
mother of Philip Watts, who was then prisoner at Ivelchester for church rates,
and had leave to go home on that occasion.
We went together, and next day had a large open meeting at the funeral.

Two Friends being deceased at Glastonbury,
the Friends of that place desired my company at the funerals,
and I found freedom to answer their request.
The meeting was very large on that occasion, the town`'s people coming fully in,
and a very open and comfortable time the Lord gave us, to his own praise,
which I believe many will remember.
That evening Samuel Bownas and I went to Puddymoor,
and I lodged at James Salter`'s. On the 7th we had a meeting there,
and on the 8th at Weston Bamfield, which, though laborious, I believe was of service;
for there were several strangers there, not observed to have been at meetings before,
and things opened suitably and clear.
On the 9th I went to Sherbourn, and on first-day had a large open meeting there,
many of the people coming in, and Friends from the meetings round the country.

On the 11th I went to Bridport, and had two meetings there on the 13th,
one being more select among Friends, which was a very solid and comfortable time,
and the other in the evening, where the people came fully,
and things opened well in order to their convincement;
but they being as the stony ground, my time was something laborious,
though it was a good meeting.
Perceiving the people willing to hear, we appointed another meeting on the 15th,
which was larger and more open than the former; and staying over first-day,
we had two meetings more, one in the forenoon, of Friends for the greatest part,
and the other in the evening, which was very large, so that the house,
though lately enlarged, could not contain them; and they were very sober and attentive,
many things opening to them, both by Samuel Bownas and me, suiting their condition,
and so far as I could observe, to general edification and satisfaction.

On the 19th, leaving Samuel Bownas there, I went to Dorchester.
There are but a few Friends belonging to that meeting;
but notice being given in the town, there came some of the people, who looking in,
and seeing but a few mean-like persons, went away, but after a while came again,
and some others also.
I found a concern in my mind, but delayed, as long as I well could;
and perceiving some without, waiting till they could hear some speak,
I at length stood up and began to speak, which, when they heard, many more rushed in,
and in half an hour the place was crowded,
and we had a meeting much more open and large than I expected.
And though many of them being strangers to Truth and our way,
were at first airy and wanton, yet Truth coming over them,
most of them were very solid before the meeting was over, which, when done, some of them,
as their manner is, gave me thanks for my good sermon,
and gave me also their good wishes.

On the 20th we had a meeting at Weymouth; on the 22nd two appointed meetings at Corf,
which were not very full; and on the 24th, being the first of the week,
I was at the meeting at Pool, which was large and open in the forenoon;
but on occasion of a funeral, was much larger in the evening, and very open,
there being many strangers at the meeting of several notions.
Here I stayed till the 26th, and had another good meeting that evening,
many of the inhabitants being there, who did not usually come.
On the 28th I was at Ringwood meeting, which was small and heavy in some part,
the life of Truth not having for some time a free passage,
and some terms of correction and reproof were uttered in my testimony;
but at length Truth making its own way, we had a good meeting.

On the 29th we had a meeting at Fordingbridge, to which many of the inhabitants coming,
and the truths of the gospel opening freely,
in the demonstration of the wisdom and power of the Lord, we had a very open good time.

On the 30th I went to Salisbury, and the day following, being the first of the week,
was at their meeting, where, in the forenoon, came several Friends from Fordingbridge,
and the Lord gave us a good time together.
There were also some of the town`'s people with us.
I was greatly comforted in this meeting in silence, and had an open time in testimony;
but in the afternoon the place was crowded with all sorts,
the controversy being then warm about the Trinity,
and some being willing to hear what might be said on that head.
But I rather set forth Christ the light of the Gentiles and object of faith;
exhorting all to a holy life, and to keep the commandments of God,
Christ setting himself forth as an example that way, saying,
"`If ye keep my commandments, ye shall abide in my love;
even as I have kept my Father`'s commandments, and abide in his love.`"
That keeping Christ`'s commandments is a necessary consequence of loving him;
and without keeping his commandments, all profession of discipleship is vain.
"`If any man love me he will keep my commandments, and my Father will love him,
and we will come and make our abode with him.`"
Again, "`In that day ye shall know that I am in my Father, and you in me, and I in you.`"
Again, "`He that saith he loves God, and keepeth not his commandments, is a liar,
and the Truth is not in him.`"
And since it is eternal life "`to know the only true God,
and Jesus Christ whom he hath sent,`" and that knowledge is
not to be acquired but as God pleases to make himself known,
it was better to wait humbly upon God for this knowledge,
to be experimental witnesses of his presence in the Son of his love,
than to have any notions of him other than what he gives,
since no man can form any true idea of him, or is he any thing to any man,
but what he himself pleases.
But as he is declared to be love to all the humble, faithful, and obedient,
and a consuming fire to the ungodly,
it is better we all labor so to demean ourselves to him, and one to another,
as to escape his wrath, and abide in his love, than by unwarrantable curiosities,
and neglect of our duty, to provoke his displeasure,
since this is the sum of all his requirings, "`To love God with all the soul,
and with all the strength,
and one another in him;`" without which all speculations are vain;
with many other truths of the gospel, which freely, and with good authority,
opened in that meeting, to general satisfaction.

On the 1st of the twelfth month I went to Romsey,
where we had a very small meeting the day following,
they having given little or no notice to the neighborhood;
and as they were sparing that way, so the Lord was also sparing to them,
for we had a poor time, though some were alive.
On the 3rd I came away with a load upon my mind on that account,
and at Southampton had another like meeting.
I everywhere observe,
that where the pretenders to Truth are cold and indifferent that way, they are asleep;
and God is also sparing of his living mercies unto all such, and justly.
After this meeting, which was a little better than that at Romsey,
I stayed at Thomas Curtis`'s house till about four next morning,
and then embarked in a Cowes hoy for that place, in the Isle of Wight:
where we arrived next morning about eight, being a very clear and pleasant morning,
and that evening had a small meeting there, at the house of Jonathan Ely.

On the 5th, at six in the evening, I had another meeting on the east side,
at Daniel Hollis`'s, which being very small, by the same neglect as at Romsey,
we fared accordingly, though not quite without the presence of the Lord.

On the 7th I went to Newport, where the meeting was small in the forenoon,
there being but few in the island, and most of them there at that time;
but we had a very comfortable season.
And putting off the afternoon meeting till five in the evening,
there came a mixed multitude, some of the age of discretion, but had none,
and others too young to have much of themselves,
nor were there any signs of instruction at all upon them;
yet I had an open full time among them.
And though many of them kept talking, and making noise most of the time,
yet not regarding them, and my voice being over them,
the sober sort were informed and satisfied, and I came away easy.
But after the meeting was ended, I stood up and reproved them.
First,
I put them in mind of what the apostle Paul said
of the trouble he had with the baser sort,
who were like themselves; and then told them they were a reproach to government,
a shame to their parents, a scandal to their teachers, if they had any,
and a grief to the honest-hearted.
I added, that the teachers among the first reforming Protestants,
used to catechize the youth of their profession every first-day,
by which some impressions of religion were made early in their minds.
But as most of those now in this nation, of all sorts,
mind little else than to seek their gain from their quarters,
their hearers were too generally gone so far from religion,
that they were below a moral education.
And having been so guilty, this they bore without reply, and went away quiet,
only some of the soberer sort said, there was too much in it to be denied,
and they blamed one another as they passed in the streets.

On the 8th, accompanied by Jonathan Ely of West-Cowes, I passed over to Portsmouth,
where we had a meeting the same evening, which, though small, was very open.
Here I met with Robert Roberts of Maryland, waiting for a wind for Barbados;
being an old acquaintance, the occasion was acceptable.
That night we lodged at Mary Graysden`'s together.

On the 9th we crossed the harbor to Gosport,
and had an evening meeting in the Baptist meeting-house there,
which was exceedingly thronged, being a new thing among them,
but with a yet ruder company than at Newport; though, to do them justice,
the noises were rather occasioned by the great press and crowd, than intentionally,
and were most in the door and passage.
But notwithstanding the inconveniences and disadvantages we labored under that way,
many things of great moment opened, with clearness and authority,
of which many sober people among them had the advantage, who spoke well of the meeting,
though grieved with the noises and ill-behavior of others;
for which I also reproved the offenders in the end of the meeting.

The 10th being very cold, and a high wind, we crossed over again to Portsmouth,
to accompany the corpse of a deceased Friend up to Port Chester,
where it was to be interred; and the deceased being the commander of a ship,
many of the same faculty went to the meeting on that occasion.
We rowed against the wind and tide,
and arrived not there till near the second hour afternoon; but having a large, sober,
and open meeting, to general satisfaction,
we w-ere sufficiently rewarded for all our fatigue and labor.
Here I parted with my friend Robert Roberts, who went back with the company to the town.
That night I stayed at Port Chester, lodging with Thomas Whiting,
an ancient Friend of that old village, reported to be first settled,
and the old castle there built, by Julius Caesar.

On the 11th I went to Alsford, where I met with James Simpson, of Yorkshire,
who had that day appointed an evening meeting there, to which I also went.
We had some sober people, there being but few Friends;
but a company of boys belonging to a free school taught by a priest in town,
were very rude and troublesome, whom both James and I reproved.
He had the concern of the meeting, only I concluded it;
and being desirous to have a time with the people,
gave them notice of another meeting at the same place the next evening,
which accordingly was held.
But being a wet evening, we were not troubled with the rude boys,
nor with such as were more dainty than desirous, but a sober solid people,
among whom I had an open time, wherein Friends were comforted in the Truth,
and others satisfied in what was opened.

On the 13th I went to Alton, to James Hawkins`'s, and the day following,
being the first of the week, was at their meeting, being a monthly day for worship,
and many Friends from the places adjacent,
and the Lord gave us a comfortable time together,
there being also some strangers among us.
The afternoon meeting, at my request, was put off till the fifth hour in the evening,
and notice given in the close of the first meeting.
We had a large gathering, and many of the inhabitants of different notions came,
who were generally very sober and attentive to what the Lord gave me to say among them,
which was not little, for I was largely opened, both in spirit and doctrine,
which had a free and open passage.
I had comfort concerning this memorable meeting,
in which my natural strength being much exhausted,
and the family where I lodged agreeable, and also desirous of my company,
I stayed there the next day, and visited some families and a Friend who lay ill,
with whom I was comforted in prayer.
And being well refreshed and recruited, both temporally and spiritually,
and pleased with the conversation of Friends, as they with mine,
on the 16th I proceeded to Godalming,
having a particular desire to see and converse with Joseph Taylor,
who had been teacher of a congregation of Baptists at London,
and visited of the Lord with his day-spring from on high,
had believed and obeyed the divine light,
and thereby become a minister of it in a good degree,
according to the dispensation that now is in the church of Christ,
gathered thereinto throughout the world.
I stayed at his house, two nights, and we had much conference about divine things,
and I found him a man of good understanding.
As I desired to see not only the few Friends belonging to the meeting,
but as many of the inhabitants as might be,
he and they took some pains to give large notice, and on the 17th in the evening,
we had a very full and open meeting, more than their meeting-house could hold,
and the people generally behaving very soberly, as Friends,
went away solid and satisfied.

On the 18th I had an evening meeting at Guildford, where were Joseph Taylor, John Smith,
and others, from Godalming;
but there happening a burial of the corpse of one of the magistrates,
where a sermon was expected, and general invitation given to the inhabitants,
and also a Baptist meeting at the same time,
our meeting was not so large as otherwise it might,
and yet a pretty large gathering both of Friends and others.
We had an open meeting, which Joseph Taylor concluded in prayer,
after I had been largely opened in it, in matters doctrinal,
which seemed to have a good reach upon the people, and Friends were comforted,
especially those who travail in spirit for the prosperity and spreading of Truth,
both in themselves and others.

On the 19th I went to Dorking, where we had a large meeting,
though there are but few Friends.
The people were generally sober, and the time satisfactory to most, if not to all,
many things of moment being opened among them, and with good authority;
coming close upon such as secretly are convinced of the way of Truth,
but for reasons relating to this world, will not own it; especially in these texts,
and some short comments upon them, viz; "`He that denieth me before men,
him will I also deny before my Father and the holy angels;
and he that confesseth me before men,
him will I also confess before my Father and the holy angels.
He that receiveth you, receiveth me; and he that receiveth me,
receiveth him that sent me: and he that rejecteth you, rejecteth me;
and he that rejecteth me, rejecteth him that sent me,`" etc.
And "`with the heart man believes unto righteousness;
but with the mouth confession is made to salvation.`"
It is not therefore sufficient that a man be
inwardly and secretly convinced of the Truth,
and way of it, or to know who are the people of God, and yet not own it openly;
but as the unbelieving are excluded, so also the fearful.
Neither father, mother, wife nor children, houses nor lands, oxen nor farms,
liberty nor life, is to be preferred to the calling of God,
since Christ has told his disciples from the beginning,
what they must expect in this world for his name`'s sake, if they believe in him,
and follow him fully.
And as ignorance will be no excuse in the day of the Lord,
and the unbelieving are condemned already, so it will be no plea in the day of the Lord,
for any to say, I did not believe these were thy ministers,
or these the truths of thy gospel, which I heard them declare;
or that thy light and grace they witnessed unto or declared;
since this is the condemnation of the world,
"`that they have not believed in the only begotten Son of God,`" who
hath declared himself to be the light of the world;
and his servants have witnessed that he is that true light "`that
enlightens every man that cometh into the world,`" that all men,
through him, might believe.
The 21st being the first of the week, I went to a meeting at Street Cobham,
which was not large, yet a comfortable time the Lord gave us.
That evening I went with Samuel Streeter, to his sister`'s house at Kingston upon Thames,
and the next day to London.

On the 18th of the first month, 1719-20,
I was committed to the Fleet Prison for not taking the oath of affirmation;
in which suffering I had great peace and acceptance with the Lord,
who hath forbidden swearing to his disciples.
On the 18th of the sixth month, 1721, I was released by order of the lord chancellor.

On the 25th of the third month, 1722, I went from London,
accompanied by honest Benjamin Holme,
and that night we lodged at our Friend Thomas Wyat`'s, at Chelmsford.
On the 27th we were at a meeting at Coggeshall,
and appointing another about five in the evening, it was very large and open,
many of the town`'s people being there, and very sober.
On the 28th we went to Colchester quarterly meeting, and were, on the 29th and 30th,
at the yearly meeting there, which was large and open.
On the 30th, in the afternoon, we returned to Coggeshall, to the burial of a Friend;
where we had the largest meeting that could be remembered there, and very open,
the people being very sober and attentive.
The things of God were largely and clearly
opened and demonstrated to general satisfaction.

On the 31st we went to Witham to a marriage,
which was attended by many Friends and others,
and the Lord gave us an open and comfortable time on that occasion.
On the 3rd of fourth month, being the first of the week,
we had a meeting at Aughton Hall, which was small,
by reason of thunder and much rain that fell that day.
On the 4th we went to the quarterly meeting at Woodbridge,
where I found it upon my mind to exhort Friends to
faithfulness against anti-christian priests and priestcraft;
as the successors, not of the apostles,
but of those antichrists the apostles witnessed against in their day; "`who,
with feigned words,`" according to the apostle`'s prophecy,
"`make merchandize of the people.`"
On the 5th we were at their yearly meeting in that place, which was large and open,
many of the town`'s people being there.
On the 6th, being the fourth of the week,
we had a large open meeting by appointment at Ipswich,
where came many people of note of the town, and were generally satisfied.
On the 8th I had a good meeting at Needham,
where some people of account in the town came, and were very quiet and attentive,
though it was not so open as at Ipswich.

On the 9th I went to Edmundsbury, Benjamin Holme having gone thither before from Needham,
and the day following was at their meeting in the morning, which was pretty open,
but small; but in the afternoon Friends from divers parts,
and a multitude of the town`'s people, coming in, it was the largest known there;
the house, galleries, and greatest part of the court-yard being filled.
Some persons of note in the world were there, among whom was sir John Holland`'s lady,
daughter of the earl of Yarmouth,
and granddaughter of king Charles II a mild affable person.
She came to the widow Dikes`'s, where I lodged, and drank tea with some of her sisters,
with whom she was acquainted.
We had some solid discourse concerning the meeting, which was open, though laborious,
both by reason of its largeness, and the heat of the season.

On the 11th, parting with Samuel Alexander, his wife, sister and niece,
who came from Needham on that occasion, I went to Midner,
where I lodged with Simon Burgess, and the day following had an appointed meeting,
which was large, considering it was the time of hay harvest;
and a very open season the Lord was pleased to give us, in showers of heavenly rain,
and some pruning and digging, in order to more fruit.

On the 13th I went to Cambridge, and that afternoon had an appointed meeting,
which the scholars of the university hearing of, many of them came,
and I had good suitable matter for them.
But, alas! they were so wild, so airy, wanton, and foolish,
many of them could not be touched; and yet several of them, in some time,
grew much more solid and attentive, till some, to scare the rest and divert themselves,
suddenly reported that the proctor was coming;
upon which they all flounced away like wild colts that had never been haltered.
However I did not mind that,
but went on with what was in my mind to the people that stayed;
and the alarm proving false, many of them came back, and would have stayed quietly,
but others still renewed their fears by fresh alarms.
I compared them to wild fowls, which are not to be taken, but shot flying.
And I do believe the arrows of the Almighty did not miss them all.
O that they had been still but one hour,
for the advantage which might have accrued to
them by the excellent openings I had that day,
through the grace of God, which flowed towards them in me from the Lord!
But this sort, of all men, are most miserably stated; professing themselves wise,
(the leaders of them I mean) they are the greatest fools.
And if that saving be true, that the two universities, Oxford and Cambridge,
be the two eyes of the nation, or national church,
how blind are they in the things of God!
And in whom more than in them, and those led by them, is that saying fulfilled,
"`If the blind lead the blind,
they shall both fall in the ditch;`" as at this day is
too much the sad case of this professing nation,
through the fogs of the pit, rather than any light of the gospel of Christ,
issuing from these rude and benighted dungeons;
the stink of which poisoneth and stifleth the people,
that they draw little or no breath from the Lord and Giver of life, though near them,
even in their own bosoms; but unknown, by the force of the power of death,
still reigning by means of those children of darkness, those learned fools.
These young men are lamentably circumstanced; they have not a sober education,
and seem utter strangers to all piety and virtue.
What then can be expected from the baser sort,
if any thing can be baser than such behavior as is too common among them.

The 14th being their meeting-day, I stayed, which consisting only of a very few Friends,
who live there, and two or three of the neighborhood who came in,
was sober and comfortable.
After I had visited a young person who was lying ill near the town,
I went that evening to Zachariah Wyat`'s, at Saffron-Walden.
On the 17th, being the first of the week, I was at their meeting at Walden,
which was not large in the morning, yet living; but in the afternoon very large,
so that several went away, not being able to endure the heat of the sun without.
Some of the aldermen of the town were there,
and a very free open time the Lord gave us to general satisfaction.

On the 18th I went to Royston, to Robert Izard`'s,
and had a meeting there the day following, which was small, but a good one.
On the 20th was at Bishop-StrafFord, where the meeting was small, and many drowsy,
but pretty well awake before the meeting ended.
On the 21st I went with Joseph Dockwray to his house at Ware,
where we had a meeting next day.
It was heavy and drowsy in the forepart, but more open in the end.

On the 25th, in the morning, I visited a daughter of John Stout,
who lay very ill of a lingering distemper,
and had a very open and comfortable time in prayer with her and some other Friends,
to our mutual refreshment.
After that I went to Baldock, to John Izard`'s, where I stayed writing letters,
and putting some things in order till the 27th, and then had a meeting, which was small,
heavy, and drowsy for some time, but ended well.

On the 28th I went to Hitchin week-day meeting, which was very heavy and sleepy a while,
but afterwards very open and tender,
and ended in a living sense of the goodness of the Lord.
On the 29th we had a small meeting at Albans: it was flat and dull awhile,
but ended fresh and living.

On the 1st of the fifth month, being the first of the week, the meeting at Woodend,
about two miles from Hampstead, was an open living time.
In the evening, about the sixth hour, we had another meeting at Hampstead,
where many of the town`'s people came in; and we had a large open time,
and many were tendered, and generally satisfied.

On the 6th I went to Wickham, and that evening had a meeting there,
which was pretty large, and very open,
the power of the blessed Truth reigning triumphantly,
and the meeting generally broken and comforted.
I left an exhortation with them to keep up their testimony faithfully,
against the payment of tithes, that great support of anti-christian priestcraft.
There are at this time very few Friends belonging to the meeting at Oxford, and few,
if any, in town, but Thomas Nichols and his family;
but the scholars come much more to meetings of late than for many years past,
and generally are not so rude as heretofore;
though some of them now and then very waggish and arch, but few malicious.
Some of them frequently come to week-day meetings,
and sit silently with the two or three Friends, sometimes the whole time,
and go away silent and sober; which Friends observing,
make no complaint against the ruder sort,
lest the better sort should be hindered from coming, and lose that advantage,
which some time or other, they might reap in our meetings.

It being the first-day of the week,
many of them and others came to the meeting in the morning.
Some of them looked wild and airy, but others more solid; some sat down and were quiet,
others were restless and floating, full of tricks, whisperings, and smirkings,
and sometimes fleerings; and one young man, not of them, but of the same temper,
and countenanced by some of them, played tricks with a spaniel dog in the meeting:
all which we bore as if it had not been.
I had a great work of Truth in my spirit; and when I found a fit time,
I stepped up into the gallery, for none sat in it at that time,
being but few Friends there, and delivered what was in my mind;
during which some of them went out, and some of them and others came in again;
but most stayed the meeting,
and were generally more sober and attentive than I have seen them, and went away quietly.

In the afternoon the meeting was very full,
both of the scholars and other people of both sexes.
Most of the scholars were very solid and attentive, and stayed the meeting,
there being little smiling at all among them;
but such as attempted that way to draw out the minds of others, were disappointed,
finding but little countenance, so that we had a very large, open, comfortable meeting;
and by the exercise of my own mind, the doctrines I had to deliver,
and the love of Truth attending, and by what went out among them,
I hope there was some good done that day.
To the Lord be the praise,
whose work alone it is to save--whether immediately or instrumentally, it is the Lord`'s.

On the 10th I went to Witney, going round by Woodstock,
where I took a turn in the duke of Marlborough`'s gardens,
and view-ed some part of the house, with the famous bridge before it; all very noble.
On the 11th the meeting there was large, many Friends belonging to it,
and very open in the main; but there was a drowsy heavy sort here also,
as there is at this day in most places of the world, though others are fresh and living.

On the 12th I had a meeting appointed at Burford, which was pretty large and open,
some strangers being there; but we had also some sleepers,
who are always a dead weight wherever they are in any meeting, or in any society.
At this meeting another was appointed to be next day at Milton,
about three miles from thence, which was held about the sixth hour in the evening,
and was as large as could be expected in that time of hay-harvest,
where pretty many of the country people came in, and things were open and well.
It is near that parish, if not in part of it,
the tithe whereof was given to John Fox and his heirs,
for his great care and pains in compiling his large and useful history, entitled,
"`Acts and Monuments of the Church,`" etc.

On the 14th I went to Cirencester,
and the day following was at their meeting forenoon and afternoon.
It was small, by reason of the weather, and a very drowsy, sleepy sort among them;
and yet a remnant alive, who were tender, and some of the younger sort broken and melted.
On the 16th I went to Tedbury, and the day following had a meeting there,
which was small, there being few Friends in that place, but the Lord was with us,
and gave us a comfortable time; and some neighbors who came in were well satisfied.

The week-day meeting at Painswick being on the 18th, I went thither.
It was small and heavy in the beginning, but ended fresh and lively.
The hindrance was drowsiness, a great evil,
hindering the living worship of the living God; and in which hidden temptation,
Satan has greatly prevailed in some places, to the dishonor of God,
and hurt of many souls.
For if Satan can transform himself into an angel of light,
and in that way deceive the simple, and such as know not the true light,
how much more may lie transform himself into the image
of death and darkness in a dead and drowsy soul;
through which, as a veil he puts on in a meeting,
he also loads and grieves the upright and living;
and where this prevails there can be no worship of God,
but rather a yielding and bowing to the enemy,
whereby all worship of God is much more effectually suppressed,
than by all the powers of the earth in times of their open opposition and persecution.

On the 20th I returned to their week-day`'s meeting at Nailsworth, which being large,
was laborious; and the more so, because most of them were young people, hardly convinced,
and of little knowledge of Truth as it is in Christ Jesus, and yet sober as men,
and hopeful.

On the 21st I had a meeting at Sedbury, which was not large.
Some sleepers were well awakened by the word of reproof, which flowed plentifully;
and though a rebuke upon the careless, it was health to the diligent and living.

On the 22nd I went to the city of Bristol, and meeting with Alexander Arscot,
went with him to see his wife, who lay dangerously ill of a fever,
and having some time in free prayer, was much comforted with them; and from that time,
it pleased the Lord she began to recover.
It was near the time of the fair in that place, which usually holding about two weeks,
I fell in there on purpose to attend the meetings on that occasion,
being usually larger than at other times;
and yet was much hindered and disappointed for a time, by some other forward persons,
who had come there only about their trades, and buying and selling.
But when once I had an opportunity, under the weight of one of their great meetings,
consisting of many hundreds of Friends and others, I was easier,
as also were the meetings; and after some few times I had very open service for the Lord,
his Truth and people, and continued therein from time to time,
till the 8th of the sixth month, and then was at the week-day meeting at Frenchay,
which was a good, open, comfortable time.
I lodged at Abraham Lloyd`'s, on my way to Thornbury,
to the burial of our ancient and honest friend, John Thurston.
It was on a first-day of the week, and as he was a man well beloved,
and much esteemed of Friends and neighbors in his life time,
so many came to our meeting on that occasion, and the Lord gave us a good time,
and many were reached and satisfied; things opening very plainly to most understandings,
who had any love for Truth, or concern for religion.
That evening I went again towards Bristol, and next day to the city,
where I had a very open time on the third-day following, and another on the sixth,
to the help and comfort of many, though to the rebuke of some states;
and some other ministering Friends coming to town,
I departed thence on the 25th of the month, for Glaverham,
on my journey to the yearly meeting at Exeter.
On the 26th I was at their first-day`'s meeting, which was pretty large,
consisting mostly of young people, not yet much baptized into the nature of Truth,
which made my exercise for them a little harder.
On the 27th I went to Chew-Magna, on a visit to my ancient and much esteemed Friend,
the widow Elizabeth Vickris, I having been, in my early time,
well acquainted in that then honorable family.

On the 29th I went to Sidcot week-day meeting,
where the Lord was pleased to favor us with his presence to a good degree.
On the 1st of the seventh month I went to Taunton Dean,
and the next day was at their meeting, both forenoon and after,
which were large and open, especially the latter.
Their monthly meeting falling of course the next day, I tarried with them,
and the day following had an evening meeting appointed, for the most part,
for the sake of the neighboring people, who,
though they are willing to come to our meetings, yet would not be seen there.
This meeting was large, and the Truths of the gospel flowed plentifully among them,
to general satisfaction;
so that I am not without hopes some good might be effected in some of them,
through the grace of our Lord Jesus Christ, which mercifully attended the meeting.
I went away very easy, and Friends rejoiced and were comforted.

The week-day meeting at Wellington falling in course on the 5th, I went thither,
it being the road to Exon; and though but small, yet was comfortable,
some reputable neighbors also being there.
The 6th, being the usual day of the meeting at Spiceland, I fell in with them there,
and we had a good season together in Christ Jesus our Lord,
though some sharp things were uttered in the authority of Truth to some states,
especially to the drowsy, sleepy, lukewarm and indolent,
who take up a false rest in that unhappy state, to the danger of their utter ruin,
after many years fruitless profession of the living and life giving Truth of God.

On the 7th, being the sixth of the week, and the usual week-day meeting at Collumpton,
I took that also in my way.
It was pretty largo; but there were some young people,
little acquainted with the work of Truth, and some older who had set down short,
and at ease; in which unhappiness they are not alone.
Yet the Lord was mercifully with us, notwithstanding the word of reproof was not wanting,
nor consolation withheld, from the several subjects.
That night I lodged at Thomas Fennimore`'s, where, in the evening, came Thomas Beavan,
from Melksham, and several Friends with him;
and he favored us with the reading of his manuscript, proving that reason in man,
and divine Truth, are distinct things.
On this subject he and I had discoursed before,
as very necessary to be fully and plainly treated on.
At that time many of the more ingenious sort of people, of divers denominations,
some among ourselves not excepted, were ready to mistake one for the other,
and establish their own reason instead of divine Truth; the spirit of man,
with his uncertain and fallacious reasonings, in which are endless wranglings,
uncertainty and confusion, instead of the Spirit of the Lord Jesus Christ,
which is self-evident and certain Truth,
and leadeth the rational man into all righteousness and truth in spiritual things,
with demonstrative certainty, and undoubted assurance; which his own reason,
without the light of Truth, can never do,
any more than the eye can see without the medium of light, though its faculty of seeing,
in itself, be ever so perfect.

On the 8th, being the seventh of the week, we went to Exeter yearly meeting,
appointed by consent of the yearly meeting at London,
and intended for the more effectual promulgation of Truth in
those several counties to which it was confined,
and moveable at its own discretion, the better to answer the end;
and like those in the north, not meddling with matters of business or discipline,
but only worship, doctrine, and occasional communication of holy things.

The meeting began on first-day morning, the 9th of the month,
and ended the third-day following, and was a good time throughout;
but as generally such meetings are observed to be, was brighter and brighter,
and brightest in the end.
For as they consist of a mixed multitude of all sorts and notions,
the understandings of the uncouth and ignorant are darkest at first coming;
but as they begin to be illuminated by the testimony of Truth,
and their senses a little awakened to relish something of the sweetness and virtue of it,
Truth then flows more freely to them, with a greater facility in the minister,
and reception in the hearer.
The sensible and living, who, in the life of the Son,
and as they stand related to him who beareth the
infirmities of all from the foundation of the world,
in the beginning of such meetings, are often deeply and mysteriously laden,
but being eased of their burden and travail, now laid upon those in the auditory,
where it rightly belongs, things then proceed, and conclude to mutual comfort and ease.
This was much the case in this meeting,
the most part consisting of a young uncultivated sort of our own natural offspring,
and others, strangers to the verbal testimony of Truth;
but some were a living people and ministry among us;
and as the true and worthy crown of all, the living presence of the everlasting Lord God,
in some good degree, blessed our assembly.
The meeting of ministers, on the second-day morning was eminently favored with it,
to our general and mutual help and encouragement.
This meeting ending in peace and gravity, I stayed in town that night,
and the next morning, being the 12th, returned towards Taunton.

On the 13th, the quarterly meeting for the county of Somerset was held there,
and well filled with good Friends, and those with divine truths;
in which the Lord gave me an open utterance at that time, and a free reception,
to my satisfaction, and the hearts of Friends were freely opened in the same;
for he who openeth and no man shutteth, and shulteth and no man openeth,
and who had and hath the key of David, was there, and blessed us together in one name,
unto which we bowed, and in which we worshipped and adored him, who liveth and reigneth,
and is worthy forevermore.
Our spirits being thus refreshed in the presence of the Lord,
the concerns of the meeting for business were
carried on and finished with unity and comfort.

Next morning, accompanied by a Friend belonging to Sidcot meeting,
I set forward for Bridgewater.
About three miles from Taunton we met three companies of foot soldiers,
newly come over from Ireland in the king`'s service, marching to Exeter.
Having acquaintance in Ireland, and being a well-wisher to the country,
I asked several questions, of health, whence they came, and the like,
and was answered civilly.
But having passed the whole three companies, and riding near the hedge,
we suddenly met a running footman in white, leading a dog, which so scared my horse,
that he flounced round, and jumped to the other side of the lane,
by which he threw me out of the stirrups, and upon the pummel of the saddle.
Finding himself loose, he run back towards Taunton,
so that I could by no means turn or stop him, or recover the stirrups or saddle.
Coming up with the rear of the soldiers, I called to them to stop him if they could,
for I was not able, which several of them attempted with their muskets and staffs,
but in vain.
However, it broke his career, and I had an opportunity to be willingly thrown off.
In the fall he happened to set one foot upon my head, a little above my temple,
and another upon my breast; but so it was ordered that he laid not his weight upon me,
but in dragging his foot off, wounded me a little with his shoe behind the ear.

My strength being gone, and quite out of breath, I lay a while,
till some of the soldiers came, and kindly took me up in their arms,
lamenting my misfortune, thinking I had been crushed and slain.
But though I was bruised, and my strength gone, my understanding remained,
and they were gladly convinced of their mistake as soon as I could speak to them,
though I staggered, which gave one of them occasion to say,
"`The gentleman is in drink;`" which I perceiving,
took care to assure him of his mistake, and that I was never so in my life,
but it was only the effects of my weakness and fall,
having drank nothing that day but a little tea and milk,
and a wine glass of middling ale.

The officers were very kind, and offered to send for the doctor of the companies,
gone before; but not apprehending myself to be so ill as I was,
I acknowledged the kind offer, and declined the trouble of sending.

Finding myself, as I thought, able to walk,
and not willing to remount my horse till his fright was more over,
I leaned on the arm of my friend, and went a short way.
But my strength failing, and my breath shortening,
I was forced at last to sit down upon the ground on the side of the way.
I was then more sensible of my hurt; and putting up my hand to the side of my head,
found it wounded and bloody, which the Friend perceiving, shook his head,
and turned pale, supposing it worse than it was.
My strength however gradually returned, and I grew very easy,
as if nothing had befallen me.
In about half an hour`'s time we mounted again, the Friend upon my horse and I upon his,
in order for Bridgewater; but the weather being cold, and riding slowly,
I became very sensible of other bruises, and I felt myself much weakened in my journey.
But though I rested better that night than could have been expected,
yet the next day I found myself stiff all over, so that I could scarcely walk;
upon which I became thoughtful for the meetings appointed before this accident fell out,
one being the day following in the evening, at that place, desiring,
if it pleased the Lord, I might be enabled to the service of them, since,
on the one hand, some persons might be disappointed and hurt that way,
and others might reproach the Truth and ministry by that accident.
The Lord heard and granted my desire;
for though in the morning there were few but Friends in a small chamber,
yet in the evening we had a large meeting of the town`'s people in a warehouse,
and the whole service of it, as to outward ministry, falling upon me,
I was not in the least sensible of any deficiency or weakness from my bruises;
but the Lord was pleased to work in and by me in a good degree,
affording healing virtue by the same power, and I was, from that time,
little sensible of any danger, but recovered far beyond my own expectation,
or that of others.

Here I stayed till the 18th, and then went to Marks,
where a meeting had been appointed before the accident happened.
It was an open comfortable time, consisting of a tender people,
but few of them yet professing the Truth; and that evening I returned to Sidcot,
to William Jenkins`'s.

On the 19th I went to the general meeting at Claverham,
which was more open than the time before; and lodging at Arthur Thomas`'s that night,
I went next day to Bristol,
where Friends were glad of my return and escape from so great danger,
and I was also glad to find them in peace and love.
I tarried in the city till the 26th,
having some as open times as ever I knew in that place, to general satisfaction,
as well as to my own great consolation,
my testimony tending in the main to a visitation
of the love of Truth to the young generation;
many of them being much touched with a sense of the goodness of the Lord therein.

In my way to Bath I made a visit to sir William Cann and his lady,
who had borne me respect ever since the marriage
of Robert Button and Martha Vickris at Chew,
some years since, where they were present.
We had more discourse concerning some points of religion on this occasion,
which gave me no uneasiness; for they both treated me with civility and good nature.
The season of the Bath not being over,
and many of the nobility and gentry frequenting our meetings,
I attended the service of Truth there for some time,
and in the mean time drank the waters,
till the cold weather setting in a little sooner than usual, I took cold,
and upon that an intermitting fever, which weakened me much for the time;
but as it pleased the Lord, it was fully over in about two weeks.

During this time we had many strangers at the meetings, and some clear and open seasons,
according to the manner and degrees of the working of the grace of our Lord Jesus Christ;
in which some of them were sensibly touched and affected with that which is good.
And the season being nearly over before I removed from thence, and less of such company,
the Lord was pleased to give us some more select times and enjoyments
of his good presence in our own less mixed assemblies,
and we were greatly comforted together.

On the 18th of ninth month, being the first of the week,
I was at the meeting at Bradford, forenoon and afternoon,
the latter being large and open.
I had likewise been thero one lirst-day before during my stay at Bath.
That evening returning to Joseph Hull`'s with some Friends from Bath,
I stayed there that night also.

On the 20th I was at the week-day meeting at Melksham,
and the Lord gave us a comfortable time in his good presence.
That night I lodged with Thomas Beavan, junior; and his father,
my long acquainted friend, being then living in that place,
we had good agreeable conversation together.

I went to Calne on the 22nd, where was appointed an evening meeting,
to which came several professors in the Presbyterian and Baptist ways;
and as things opened very fully in some points relating to them, they were very still,
giving no signs of dislike, and we had a good time.

On the 24th I went to Marlborough, and the day after was at two meetings there;
that in the evening was large, many of the neighbors of various distinctions being there,
and many important truths of the gospel were plainly opened,
through the grace of God among them; and by their peaceable and quiet deportment,
they seemed generally pleased, and some pretty well affected.

On the 26th I went to Newbury, where we had a meeting that evening,
to which came some professors, and among others, a Baptist teacher.
I was fully and clearly opened upon the universal love
of God in Jesus Christ unto all men,
and the subject of predestination, as clearly as I have known for some time.
They were all calm, and for any thing that appeared, well satisfied,
there being a good degree of that holy love among us, in the virtue of it,
as well as words upon the subject, which affected Friends as well as other people,
and seasoned us together as one lump.

On the 28th I went to Henley meeting, but no notice being given, it was small;
yet we were favored with the experience of the fulfilling of that good promise of old,
that "`where two or three are gathered together in my name,
there am I in the midst of you;`" though among these
few some never were at any of our meetings before,
and things opened larger than reason could have expected in so small a gathering.

On the 30th was the meeting day at Reading, but a burial happening on the same day,
the meeting was put off till the afternoon, when came many of the neighbors of all sorts,
and among others, several military officers.
The Lord gave me a door of utterance,
and a considerable entrance also with Friends and people,
the gospel of the kingdom of Christ being plainly laid open to them,
and many well affected among them.
A lieutenant afterwards said, that he had never been at any of our meetings before,
oral any other with like satisfaction, nor had he ever heard such things in any assembly;
and that we were a people much misrepresented and abused: which he also hinted to myself,
I accidentally seeing him in a shop in town next day.
On the 2nd of the tenth month I was there again,
and the meetings were both large and open;
so that I had never been there with the like satisfaction before,
and hope there was some good done among both Friends and others.

On the 3rd I had a meeting appointed at the house of John Fellows, at Maidenhead.
The house was small, and notice only given to a few: but when the meeting was set,
and my voice heard, the place was quickly crowded,
and many in the street who could not get in,
and some military officers and soldiers were there;
and as the Lord was pleased to open in me several gospel truths for their sakes,
I found a very ready passage for them among the people,
so that I concluded some good was done to them also.

On the 4th I went to Windsor and had an evening meeting, which was large,
a great many of the town`'s people coming in.
As we were often concerned to declare the universal love of God to mankind,
so about this time, as often before, I felt much of it, even a dispensation of it,
to the people in most places;
and many great and necessary truths were declared as the Lord opened, on that occasion,
with good authority, and many clear proofs out of the Holy Scriptures,
both of the prophets, and also of the apostles of Christ.
Truth was over and upon the people, and they departed from the place,
when the meeting was over, under a grave and solid concern.
The Lord gave me great peace, as a full reward in that work,
blessing me as a co-worker with himself, the great Master workman, therein.

On the 5th I went to Jordan week-day meeting, which was but small, most of the ancients,
who were once numerous there, being deceased, and their reward sure forever,
and of late many died of the small pox;
but the Lord made up all by the comfort of his life-giving presence, which,
through his mercy, was not wanting.

The next being week-day meeting at Windsor, consisting, mostly of Friends,
we were refreshed together in the presence of the Lord.
The meeting ending about mid-day, I went that afternoon to Stains,
where I fell in with their meeting, which is usually in the evening;
and as they had heard of my intentions,
so they had given notice to some of the neighbors, and the meeting was larger than usual,
and very open, much beyond my expectation.
The goodness of the Lord is boundless,
and the treasures of his divine wisdom not to be searched out, or exhausted,
which he freely dispenses and opens, when and where,
and in what manner and degree he pleases,
and to the purposes of his own glory and good of souls;
and here he was pleased to give some renewed instances of it,
affecting many with his divine goodness, to his own praise,
who is worthy of all dominion, praise and thanks forevermore.

On the 7th I went to London, where I met with a kind reception from Friends in general,
and great openness in several meetings among them,
where the Lord gave evidence of his presence and power with me in his service,
as at many other times it had so pleased him.
I stayed at London till the 15th,
and then went to the burial of the corpse of my very good friend, Anne How,
a woman generally beloved of all who knew her; for she was a loyal and affectionate wife,
an indulgent mother, a kind relation, a good neighbor, and very charitable to the poor,
doing good to all as opportunity offered;
and as precious to the Lord is the death of his saints,
so he was pleased both to honor and comfort us
with his solacing presence on that occasion,
where we had the company of many neighbors, and some of quality, and generally satisfied.

After this I continued at London some time,
visiting the meetings there and in some adjacent places, and had some very open times,
on first-days especially, many people usually attending our meetings,
and also at marriages and funerals,
till the moveable yearly meeting for worship for the northern counties drew near;
and then, on the 4th of the second month, 1723, being the fifth of the week,
I set forward from London for Chester,
where the meeting had been appointed for that year,
and arrived there on the 8th in the evening, and lodged at the Talbot inn,
there being few Friends in town, and I little acquainted with any of them.

On the 10th began the first meeting for public worship;
and to prevent any disorder by too great a concourse of the baser sort,
several constables were placed in a narrow lane leading to the town`'s court,
where the meeting was held, in order to intercept and stop them.
The meeting was very large, and great openness to the people as well as Friends;
for the universal love of God, through Jesus Christ our Lord, to mankind,
was not only preached, but in some measure enjoyed among us; and the people,
as well as Friends, were generally satisfied.

On the 11th, from eight to ten,
we held a meeting of conference among the ministers and elders of the several counties,
as is usual, concerning the affairs of Truth, and how they prosper in those parts,
and also the quarterly meeting for business in the county of Chester;
and that afternoon had another, and the last, public meeting, which was very large,
to the number of about three thousand, and by the goodness of the Lord,
preserved in good order.
Many of the gentry, both in the city and country, were there; and among others,
the mother of the duke of Argyle`'s lady, and two of her daughters,
who were very solid and attentive; and sir Thomas Brooks, Baronet,
was at all the meetings for worship, and some said, eight priests in common habits,
and some of them well pleased with the meetings,
as also were the people in a general way.
The meeting ended that evening to our mutual edification and general satisfaction,
to the praise of the Lord alone, of whom is the power,
and to whom it doth of right belong, now and forever.

On the 12th I went to Rixham, in company with John Thompson, of Crook,
an able and experienced minister, and some other Friends; and there we had a small,
but open meeting, some of the town`'s people coming in and sitting with us.
On the 13th we went together for Shrewsbury; and next day being the first of the week,
we had two pretty open meetings there.
Here John Thompson and I parted;
and I went that evening to Prestane on the borders of Wales,
in order to that yearly meeting; which began the day following.
People came from many places, and it was a very large meeting,
and many gospel Truths were opened, by the grace of God, therein, and the Truth,
in some good degree, was in dominion over the people, full as much as could be expected,
considering great part of them had not been at any meeting before;
and the meeting throughout being preserved in a good decorum, it ended well,
to general satisfaction, on the 18th.

On the 19th I went to Lempster,
where we had a large and very open meeting in the evening,
and many of the town`'s people came in, and were very sober.
Truth was much in dominion, and the testimony thereof full and clear,
and we came away in peace.
The day following I went to Worcester,
and on the 21st was at their meeting forenoon and afternoon;
the latter was very large and open,
and the gospel preached in the demonstration and authority of it.
On the 24th I went to Evesham, where a meeting was appointed.
In the beginning, and time of silence, it was very heavy and hard;
but soon after I got through all that load of darkness and death,
under which I was baptized for the sake of the dead and drowsy,
and a spring of life opened in me, so that we had an open time and a good meeting.
Friends being very earnest with me to stay there till the 25th,
being their week-day meeting, I did accordingly.
The meeting was pretty open, especially in prayer at the conclusion.
That night I tarried there,
and on the 26th went to their week-day meeting at Chipping-Norton, which was very small,
but the Lord was in some measure with us.

On the 27th I went to Oxford,
and the day following was at their first-day meeting in the morning, which,
though still small of Friends, was pretty well filled with scholars,
who were very quiet and attentive, things opening with authority,
upon the promises and covenant of life and light, and that afternoon I went to Wickam,
and next day to London.

Being detained at London about divers negotiations relating to my own concerns,
as also those of others, I visited the meetings there till the 7th of the ninth month,
1723, and then set forward for Cumberland, and took Tottenham week-day meeting in my way.

+++[+++After attending several meetings, he proceeds:]
On the 5th I went to John Moor`'s, at Gaile,
and next day was at a monthly meeting for worship at Kendal;
where I met with many friends and acquaintances, to our mutual satisfaction,
the Lord giving us a comfortable time together.
I stayed there till first-day, where the meeting was large and open in the forenoon;
but being put off in the afternoon till five in the evening,
some hundreds of the town`'s people came in, and we had a large meeting,
where the Lord opened several things to information, edification, and consolation.
I lodged that time at Thomas Ellwood`'s, and on the 9th went to my friend James Wilson`'s,
about three miles from Kendal, where several Friends being in company,
we were freely and agreeably entertained.

On the 10th, though very stormy, we were at a monthly meeting for worship at Grayrig,
about a mile distant,
where the Lord gave us an open and comfortable time in his good presence;
and that afternoon I returned with some other Friends to James Wilson`'s. On the 11th,
in the forenoon, we set forward for Penrith, but the wind was so very high,
we could scarcely sit our horses; and finding it dangerous to proceed,
we returned till afternoon, and the wind being much abated, we went that night to Shap.

On the 12th went on to Penrith, and had an evening meeting there, which was not large,
nor very open, though some of the neighbors came in, and things were clear and safe,
but not much capacity in the people to receive the flowing cup of the Lord,
being too much like the old bottles, not fit for the new wine,
which yet was not altogether wanting to us.

I went to Wigton, to a ministering Friend`'s meeting,
and was next day at the quarterly meeting, which was large,
and the glory of Truth over all, to general satisfaction.
It was a blessed meeting, where the Lord met freely with his people,
and the light shined clear, to the edifying and settling of many.

In this country I remained,
and was at the yearly meeting for the northern counties at Carlisle;
and with John Irwin and some other Friends,
had some meetings in fresh places in the summer following;
and in the winter I resided for the most part at my friend Isaac Huntington`'s,
in Carlisle, attending the meetings as they fell in course in the county, and was,
the spring following, at the yearly meeting this year, 1725, held at Kendal,
which was the largest I ever saw there, and very open.
The mayor of the town, and many of the chief of the people were there,
and were generally well satisfied, and afterwards loving and respectful.

From this meeting I returned into Cumberland, by the way of Hawkside,
where we had an open meeting, and so by Whitehaven; where on the day they call Easter,
I had a large meeting, the first in our new meetinghouse, and open to my satisfaction,
and of all there, so far as I could learn.
Some Glasgow merchants, of the Presbyterian way, who were occasionally in the town,
were at the meeting, and spoke well of it.

During the time of my abode in this country, having some concerns with the lord Lonsdale,
I went to Lowther-hall, where he then resided, to attend him therein,
where he gave me more respect than I desired or expected;
and after I had finished my business with him,
he moved some discourse concerning some points of religion,
there being none else in the company but counsellor Blencoe, a young lawyer.
The point chiefly discussed, was the knowledge of God,
and by what means mankind may arrive at it; in which I was drawn out to this purpose,
"`That many wise and ingenious men apply themselves, with success,
to the knowledge of things in this life, and relating thereto,
and yet keep not within the strict rules of virtue;
whereby their knowledge vanishes in the end,
as not subservient to the purposes of another world.
Wherefore I recommended them to a real inquiry after the knowledge of God,
as the most noble and most profitable subject a rational being could be concerned about,
and altogether necessary in order to our happiness, as well in this,
as in a future state;
which man can never arrive at by the utmost efforts of human reason.
For though a rational being cannot deny, but conclude there is a God,
by the works of the creation, which produced not themselves,
but were produced by another; and though reason must conclude the Creator to be eternal,
without beginning or end, all-wise, all-knowing, all-powerful, omnipresent, holy,
righteous, just and good, in all divine perfections unchangeable;
and though in all these attributes we read of him in the Holy Scriptures,
and hear clear discourses of him frequently made by such as say they know him,
and perhaps, in some measure may; yet all this is but an image of knowledge, as to us,
until, by the agency of his own power and will,
he is pleased to work in us such qualifications whereby we may perceive him, and say,
'`This is he,`' through that holy and blessed medium which he himself hath,
in good-will to mankind, provided to that end; that we may believe in him, hope for him,
know him, have communion with him in a degree in this life,
and be forever blessed in the enjoyment of him in a future condition.

Of this knowledge no man can rightly conceive,
by any thing another can say who hath that knowledge,
unless he to whom it is said or declared, be in himself, in some degree,
under the same qualifications, by which the things declared or spoken of,
present in the mind and understanding, by a kind of divine sensation or intuition,
are self-evidencing by their own nature and energy.
As for example, to a man born blind,
another can find no terms whereby to give him a proper and distinct idea of colors,
of light, and the manner of the discovery of objects by that medium unto those that see;
whereas everyone that doth see,
concludes the same thing by a kind of sensitive intuition, at first view,
without the expense of ratiocination, or deducing conclusions from stated premises.
Nor, if we can suppose any one has never in his life been
touched with any sense of that natural affection,
or principle we call love, can any, by any terms he can use,
inculcate in such a person any idea of the thing.
Whereas all the experienced are affected in the same manner,
though perhaps not to the same degree,
and need no other terms but itself to inculcate the thing.
Since then, in natural things,
it is impossible to exhibit proper ideas to the apprehensions of those who
are deprived of natural qualifications and capacities to receive them,
how much more so in spirituals;
for we cannot find out proper terms by which to exhibit them to the view, understanding,
or apprehension of others; but as we borrow them from natural things,
which can never reach them as they are.
When it is said, God is a spirit, a man must first have a distinct idea of a spirit,
before he can fix any notion of God by that term; and by the word God,
we intend to express an awful and ineffable being:
but none of these terms exhibit that being to our sense, either in fear or love.

I come then to some positive expressions of Christ, viz:
'`No man hath known the Father but the Son, and he to whomsoever the Son will reveal him.`'
'`This is life eternal, to know thee the only true God,
and Jesus Christ whom thou hast sent.`'
'`No man can come unto me, except the Father which has sent me draw him.`'
'`No man hath seen God at any time; the only begotten (or first begotten) Son of God,
who dwelleth in the bosom of the Father, he hath manifested (or revealed) him.`'`"

"`By this it appears,

1st; That God may be known, though not immediately, but by a proper medium.

"`2nd; That this medium is Christ, the Word of God; who having a reasonable soul,
and clothed therewith as a veil, is homogeneal to mankind,
and thereby proportions the splendour of his glory, as God, to the state of every soul;
gradually revealing or manifesting the Father therein,
according to the degrees of purification, capacity, and qualification he worketh in it.

"`3rd; That this knowledge is an experience,
and gives the soul a certain evidence and assurance of eternal life;
and God himself is that eternal life.

"`4th; That as the knowledge of the Son makes way for the knowledge of the Father,
so the drawings of the Father excite to the knowledge of the Son.

"`It is not therefore the knowledge of the things of God, or of all his attributes,
or of any, or all formal truths, but of God himself, who is the essential Truth,
in which our happiness stands, and forever shall remain.
For there are essential truths, and there are formal truths.
Jesus Christ the wisdom of God, and power of God, is that essential Truth;
and that he is the Son of God, was incarnate, lived as a man here on earth,
was crucified as a propitiation for the sins of the whole world, died, rose again,
ascended, is glorified in heaven, etc., are all formal and unalterable truths;
and yet the knowledge of all these does not give life eternal,
until the soul comes to experience the in-dwelling of the essential Truth,
in its nature and being, through that holy and blessed medium, homogeneal unto all;
which cannot be until we be reduced unto a state of holiness and purity of mind.

And therefore, to illustrate all I have said in a practical way,
give me leave to add a little further.
Whilst I was yet in a natural and unconverted state, I believed the being of God,
and all his attributes; but I did not actually know God to be righteous or holy,
till he reproved unrighteousness or unholiness in me; or merciful and good, until,
through condemnation of evil, convincing me of evil in myself,
he also pardoned the acts of sin, and destroyed the effects thereof,
by the agency of his own power, working that change that is meet,
according to his own will, through which I experience both his goodness and mercy;
nor had I known him as a consuming fire, unless by the refining operation of his Spirit,
he had consumed my corruptions, or begun that work; or that he is love,
divine and unspeakable love, unless, by his own power, he had fitted me, in some measure,
to enjoy the influences of his grace in a state of holiness;
in which he rules as a Monarch in the soul, according to that saying,
'`The kingdom of heaven stands not in meats and drinks;
(no outward or natural enjoyments) but in righteousness and peace,
and joy in the Holy Ghost:`' which I know, through grace, infinitely transcends,
even in this life, all that can be named besides.

"`And though formal truths are commonly clouded and confounded by the
perverse and ignorant reasonings of the learned of this world,
and numerous opinions and sects are produced and engendered thereby;
yet the essential Truth is self-evidencing,
and whenever it appears in the soul she cannot deny or doubt,
but by the cogency of his power and virtue,
certainly and infallibly concludes in herself,
that this is He. For as there is no way or medium,
by which we discover or perceive the body of the sun in the firmament of heaven outward,
but by the light which proceeded from it;
so there is not any medium by which we can know God, but by his own light and Truth,
which is Jesus (Christ, the efflux and emanation of his own glory and being,
and through that holy and homogeneal mind wherewith he is veiled.

"`And as the light of the sun carries along with it the power and virtue of the sun,
wherever it shineth in its unclouded rays, and by its influence,
nourishes and makes fertile the animal and vegetable worlds; even so, and much more also,
doth the heavenly Sun of righteousness, Jesus Christ,
the essential Truth and light of the rational and intellectual world, arise, make known,
and manifest himself in the soul; into whom, by the rays of his divine light,
he introduceth and dispenseth the influence of divine heavenly virtue.
Into them, I mean, who believe and obey in the day of small things;
according to that doctrine of an experienced holy man, '`Whatsoever things are reproved,
are made manifest by the light; for whatsoever makes manifest, is light.`'
And again, according to that saying of the Truth himself, '`I am the light of the world;
whosoever followeth me, shall not abide in darkness, but have the light of life.`'
We must therefore begin at the word of reproof, in order to the sure knowledge of God,
and enjoyment of him, as he is love, and an ocean of unspeakable pleasure,
and renounce the low and sordid pleasures of the animal life,
which disqualify for divine enjoyments here and hereafter.
But love God, love his judgments and reproofs in your hearts, which are all in love,
in order to the manifestation of himself, according to that saying,
'`Every son whom I love, I rebuke and chasten, saith the Lord.`'
And I can assure you, if you can believe me,
that as I have tasted of the pleasures of this world, and through the goodness of God,
known condemnation therein; so, through his great mercy,
I am favored of him with this certain experience in some measure;
that the enjoyment of God, in a state of reconciliation,
is undeclarably more excellent and eligible than all other things,
to the experience whereof i would recommend and excite you.`"
This was the substance of what then passed among us, the lord Lonsdale,
being a very ingenious person, of strong natural parts and penetration, asked me,
"`Since you had, before you came to the knowledge of God, in the way you have spoken of,
believed the being of God, and all his attributes,
did that knowledge make any alteration in your way of thinking on that subject,
or give you any contrary sentiments that way?`"

I replied, "`No; for as reason, a constituent property of man, is still the same,
and its proper objects the same also;
so the knowledge of God makes no alteration there.`"
Then he was pleased to say, "`Some things you have hinted at are new to me;
which I have never read of in any book, or heard before.`"
By the time all this was finished,
and some intervening questions and objections answered, it was about one in the morning,
and then we went to rest; and the next day after dinner, I departed in peace.

One thing previous to this I have omitted, viz: that a little before night,
some airy young persons threw in some reflections upon Friends about going naked,
as they said, which could not be consisting with God to command.

To which I replied, "`That about the time that Friends first appeared,
there were a sort of people called Ranters, who frequented our meetings,
and mixing themselves among them, acted some unaccountable things,
which were imputed unto us by such as could not, or would not, distinguish them from us;
for which we were not accountable, they not being of us.
And yet going naked is not inconsistent with God, in some cases,
since he commanded one of the greatest of all his
prophets to go so for the space of three years,
as a sign to Egypt and Ethiopia; and what hath been, may be,
since God is still the same.`"
This abated their ridicule, so that they did not proceed any further upon the subject.

Since that time, upon another like occasion,
I had some further discourse with the same lord Lonsdale upon another subject,
that of tithes and maintenance.

He was pleased to allege, though perhaps not seriously, "`That kings and great men,
being possessed of countries, and large quantities of land,
gave the tenths to the support of ministers;
and the same laws which gave nine parts to the laity, gave the tenth to the clergy.`"

To this I replied, "`That the law gives no property,
but protects the possessor in it against violence.`"
And then I deduced property from its original thus: "`The first properly a man hath,
is his person, life and liberty; and as these are from God, and the right of all men,
so he has provided means for the support of them unto all.
The means of the support of person and life, are food and raiment,
arising either naturally from the fruits of the earth, spontaneously growing,
animal creatures, or by the personal labor or industry of man.

"`Cain, it is said, was a tiller of the ground, and Abel a keeper of sheep.
When Cain had cleared and cultivated a piece of ground,
and propagated useful things thereon,
that and those became the property of Cain by his personal labor;
in which the law of natural reason will protect
him against any thing but personal violence.
And Abel,
taking under his care and management some of the
creatures he found most proper for his use and purpose,
they became his properly, by his care, labor and pains;
in which also he was protected by the same law:
and all just laws are no other than right reason,
declared by way of compact upon that principle of reason constituent of our being.
But when the earth was filled with violence, God destroyed the world,
save Noah and his family, by whom he replenished it.

"`In process of time, '`Nimrod became a mighty hunter before the Lord;`' that is,
his hunting was of that nature and tendency, as that God took notice of him therein;
for he, with his company, first hunting wild beasts, became wild also themselves,
and then hunted after the liberties and properties of other men,
invading them by force and numbers; till the rest of mankind, in their own just defense,
entered into reasonable compacts against unreasonable invasions,
repelling an unjust violence by a just and equitable force or power.

"`Having essayed to fix a proper idea of the rise of property,
I next observe how men may forfeit it, in all these respects, in the sight of God;
and that is, by extreme wickedness, as may be instanced in a malefactor, who,
by his evil deeds, forfeits his liberty, or properly, or all;
but then no private person can take cognizance of such offenses,
incurring such forfeitures, other than to bear witness against the offender,
in order to conviction and adequate punishment before a proper stated judicature,
of which no nation is destitute, though varying in circumstances.
Since then property in lands, etc.,
cannot be justly taken away from any one--not forfeiting-- without consent,
what is that consent necessary to that end?
It must be either in a public or private capacity.
Private, as by his own particular act to give such lands to such a minister or priest,
on condition of certain services, or saying so many masses or prayers,
either for the living or the dead, or the like;
or for the service of religion in general, according to the notion the donor had of it.
Or public, as where the legislature of any country, for politic views and interests,
makes laws for alienating the property of the subjects,
with or without their private or particular consent; where,
though property is truly invaded, the major directing the minor,
the compulsion to obedience is held lawful and just,
whatever it may be in the nature of the thing;
and particulars sit under the burden where they have no redress.
But all this binds not the conscience, though properly is forced.

"`All which I apply as followeth:
This nation was once free from tithes and other impositions of that set of men,
enslaving the world on pretense of the liberty of the gospel,
till anti-christian priestcraft, more subtle than that of the heathen,
so far seduced the minds of weak and ignorant men, prone to superstition and idolatry,
that they often gave away to the priests even their whole substance,
at least on their dying beds, for pretended services, merely imaginary;
for praying the departed souls of themselves or friends,
out of a supposititious purgatory, with such and such masses on such and such days.
This so far prevailed in this nation, that the legislature,
fearing the whole lands would, in time, fall into the hands of the priests,
made a law called the Statute of Mortmain, as a means to prevent it; which,
in some degree, answered the end, and clogged heir proceedings.
But I do not remember any law, made by the legislature of this kingdom,
for imposing tithes, or for the recovery of them, or any thing to the priests,
under the notion of dues, until the reign of king Henry VIII.,
when men`'s eyes began to be so far opened,
that many throughout the nation refused to pay them,
as may appear by the preamble of the statutes for that end made in his reign.
This law establishes the customs on foot in favor of the priests, and no doubt,
originally of their own beginning and imposing, for forty years before;
which statutes being detective,
they were corroborated by the second statute of Edward VI., still in force.
By all which it appears,
that this set of men never came fairly and equitably to
the large and unreasonable share they demand,
and receive out of the property of others; especially of those who do not, nay cannot,
receive them, and their pretended services, as gospel ministers, and means of salvation;
since the Author of religion himself hath commanded hi.s ministers,
that '`as freely they have received, they shall freely give.`'

"`The laws of the land therefore, upon the whole,
though they bind the property by a sort of national violence,
yet they can never bind the conscience; for which, and the Lord of conscience,
we suffer with patience, as witnesses on earth, for him who reigneth in heaven; until,
in the course of his providence, he appears for our relief,
who is the King of kings and Lord of lords,
and doth what he will in and with the kingdoms of men.`"

My noble antagonist replied, and not without a little pleasantness,
that he would not yet yield me the argument;
though he was pleased to propose another subject, of a different tenor.
