== Chapter 19

At London I remained, attending the meetings there, and some in neighboring places,
till the 12th of the sixth month, 1736; and then went with my friend Thomas Jackson,
to his country house at Bush-hill; and the next day to Albans,
and that evening had a pretty full and open meeting there.
On the 13th we were at the meeting at Sherington; which was large and open,
partly occasioned by the company of some Friends from Northampton:
and the Lord favored us together with his good presence;
and divers doctrines were opened by the Truth among us, to satisfaction,
on several subjects.
That afternoon we returned to Newport;
and on the 16th we had a meeting at Wellingborough, considerably large and open,
which consisted, for the most part, of the younger sort of Friends;
and things opened well to their state, and were comfortable.

On the 17th we went forward to Leicester,
and fell in with their week-day meeting next day.
It was small and low, things being much declined there;
yet a few honest Friends still remaining,
the Lord favored us with a degree of his divine goodness together.
On the 19th we were at the week-day meeting at Nottingham, which was large,
by the coming in of some strangers; and the Lord favored us and them with his goodness,
and the openings of some important truths of the gospel with authority and demonstration:
it was a good meeting.
On the 20th we went to Chesterfield,
where we were kindly received and entertained by our steady friends,
Joseph Storr and his wife.
They have been both able ministers of the gospel many years, and have many children,
young men and women, and all preserved from the immoralities of the world, and hopeful.
We had no inclination for a meeting there; but next day went forward to Sheffield,
and on the 22nd were at their meetings both forenoon and after.
That meeting is much enlarged in some years, and was very full,
by the addition of many of the inhabitants of other professions;
mind the Lord favored us together with his divine, melting, solacing goodness,
and suitable mailers of doctrine, to convincement and edification.

On the 23rd we went to Bewdley,
where we called to see our ancient friend William Francis,
then above eighty years of age.
In his latter time he had been much in the highlands of Scotland,
about some business in which he had been entrusted,
and which he had discharged honorably;
and on that occasion had preached the Truth in word and doctrine,
as also in life and conversation among them,
and had obtained near acquaintance and friendship with
some of the nobility as well as the lower rank.
And though he was so weak with age and labor of divers kinds,
that he could scarcely get on horseback, yet he went with us several miles towards Leeds.
On the 25th the week-day meeting at Leeds was large, and consists, for the greatest part,
of young people; sober, but few of them, yet baptized of the Lord,
by his sanctifying baptism:
which is much the case and state of our young people at this day throughout the world;
being in danger, as others have done, of sitting down under the profession of Truth,
in a traditional way, as to the doctrine and form of the discipline of it,
and yet short and ignorant of the life, light,
virtue and power of Truth essentially in themselves;
by which an apostasy from the very form may enter and
proceed gradually till the whole be lost,
as to them, and some other thing take place under the same name: which the Lord prevent,
by his kind and merciful visitation, in his own time and way; for nothing else can do it,
or carry on that great and glorious work,
which his own arm hath begun in the earth in and by his people.

On the 29th we went to the meeting at Bradford, which was large, and more so,
by pretty many of the neighborhood who came there.
The Lord was with us, and gave me a full and open time among them,
to our mutual and general satisfaction; to the praise of the Lord alone,
who only is worthy now and forever.
On the 31st I went to Skipton, to David Hall`'s; and next day had a meeting there,
consisting for the greatest part of strangers.
It was large and peaceable,
and the saving truths of the gospel of our Lord and
Savior Jesus Christ were freely and plainly opened;
with which several were affected, some tendered, and generally solid,
through the weight of Truth then over the auditory.

That night also I lodged there, and the next day went to Settle, to William Birbeck`'s;
and though it was near four in the afternoon before I arrived,
yet by the diligence of that family, we had a large meeting beginning at six;
where the Lord`'s good presence accompanied us, and in his love and light,
the Truth was preached with authority and demonstration;
and though many of the auditory were of the priest`'s people, mixed with dissenters,
yet the wisdom and virtue of Truth came over them,
reduced them to quietness and solidity during the meeting,
and they generally retired after the meeting in a sober and grave manner,
a sign that they were weighed down by the invisible power of Truth.
After this meeting I found my strength much exhausted;
and having taken some cold before, the weather being wet,
its effects appeared more fully then, so that I could not rest as usual that night: yet,
by the good providence of the Almighty, and care of the family,
I was able to go on the next morning, and in the evening reached Kendal.
I stayed there till the first-day, and was at their meetings both forenoon and after.
It was pretty large in the morning, consisting for the most part of Friends;
but being put off in the afternoon till the fourth hour,
and notice given to the inhabitants, we had a large and peaceable meeting.
The hand of the Lord is open to mankind in general,
but meets not with due acceptance and gratitude in many
to whom his goodness is extended in this generation;
yet his arm is stretched out still.

I stayed there till the 9th of the seventh month;
and there happening to be a burial that day,
we were labored with the divine presence in our meeting on that occasion;
and many of the town`'s people being there,
the Lord opened the mysteries of his kingdom freely and plainly to them,
in which Friends were satisfied and comforted.

On the 20th I went to my farm called Justice-town,
where I had a large nursery of forest-tree plants, both British and American;
from which having been absent some years, they were in that time grown much out of order,
and many of them lost, being overgrown and suppressed by others.
Here I stayed, preparing for a further progress in that concern;
but the quarterly meeting for the county happening to fall at Pardsay, below Cockermouth,
I went thither on the 23rd; and attending the service of the meeting,
which was to the satisfaction both of myself and Friends, for the Lord was with us.
I returned to Wigton, and it being the seventh of the week,
I was at their meeting next day;
where the divine Truth shone over all in majesty and glory,
to the praise of the Father through him forever.

On the 27th I went to Justice-town, where, with many hands,
I began to plant out several sorts of young trees, as oaks, elms, ashes, acermajors,
poplars of several kinds, firs, English walnuts, black walnuts, tulip trees,
locust trees, cedars of America, occidental planes, lindens, chestnuts, horse-chestnuts,
divers sorts of willows, beeches, hornbeams, scarlet oaks, etc.,
which I had raised from seeds and cuttings,
at that farm to furnish that part of the country, in time, with timber,
which is now scarce;
and that I might be an example to others in that useful kind of improvement;
which several since have begun to follow.
In the mean time I visited some meetings in those parts; as, Kirklinton, Solport,
Carlisle, Scotsby, and Moorhouse, and the monthly meeting, consisting of these five.

Here I stayed till the 17th of the ninth month, and that day set forward from Carlisle,
and on the 18th, being the fifth of the week, I went to Kendal, to Thomas Ellwood`'s,
and was at their week-day`'s meeting the day following;
where we were mercifully favored with the good presence of the Lord.
On the 21st I was at that meeting again; which,
in the forenoon consisted for the most part of Friends; and the Lord was with us,
to our mutual consolation.
And as I was known to many of the inhabitants, who had been often at our meetings,
and some times when I had been there.
Friends thought proper to put off the afternoon meeting
till between four and five in the evening;
when we had a great number of the inhabitants with us,
by computation about one thousand in all; and being very quiet and orderly,
some necessary and important truths of the gospel were
clearly opened among us with divine authority.
On the 22nd I went to Gale, on the 23rd to Settle, on the 24th to Slupton,
to David Hall`'s, and on the 25th to Bradford,
where I was kindly received by my friend Benjamin Bartlet.

Here I stayed till the 28th, being the first of the week, and was at their meeting;
which consisted generally of Friends,
and for the most part of young persons of both sexes:
and the Lord was pleased to open their states to them in a good degree,
and many were much tendered and broken in a sense of
his fresh visitation and goodness that day,
to the comfort likewise of the elders in general, and to the praise of his own arm,
who alone is worthy now and forever.

On the 30th I went to William Hird`'s, where I stayed two nights,
his company and conversation being very agreeable;
and on 2nd of the tenth month we went together to Leeds;
where I was kindly received by my long acquainted friend Benjamin Horner,
to our mutual satisfaction; and next day was at their week-day meeting.
On the 5th, being the first of the week, I was at their meeting again;
which being postponed till three in the afternoon, pretty many of the neighbors came in,
and were sober and attentive to the things that were opened, so far as I could observe;
and the meeting was well in general.

On the 6th the corpse of an ancient Friend was buried there,
and we had another meeting on that occasion: and many neighbors being there,
some truths of the gospel were opened to them with clearness;
and it was a comfortable meeting.
But what use they make of the kind visitations of the Lord, time must show: but it seems,
that delaying to own their convictions, and join with Truth and Friends,
they return and sit down under the gloomy shadow of their dark priests,
spending their money for that which is not bread,
and their labor for that which profiteth not; buying of them who sell,
till buyers and sellers are shut out together.
On the 7th I went to Pontefract, and next day had a meeting there;
which was open and comfortable,
some of the neighbors being there of various notions of religion, and all quiet.

On the 10th I went to Sheflield, where I stayed till the first-day following,
and was at their meeting; which consists, for most part, of young people;
and the Lord favored us with his good presence,
and a fresh visitation of kindness to them;
which I believe many of both sexes were sensible of.
That evening I went to Woodhouse, and next day went to Blythe,
to attend the burial of an ancient and honorable Friend:
on which occasion many Friends and people were at the meeting;
and the Lord gave us a comfortable time together,
opening many important truths of the gospel unto us, and things were well.

The first of the week I was at the meeting at Albans; which was small in the forenoon,
but open and comfortable, and not large in the afternoon, little,
if any notice having been given to the neighbors; yet a few sober people being there,
we were favored with a good meeting; and the Lord`'s good presence was among us.

On the 21st I went to London; where I was kindly received by my friend Joseph Green.
In this journey I had suffered very much by the badness of the weather and roads;
which affected my constitution so, that I remained at London,
visiting the meetings there, and in the country near, till the 13th of the fourth month,
1738, and then went to Hartford;
where the next day we were favored with a comfortable meeting;
for which I was thankful to the Lord, who is the fountain of all our mercies.

On the 15th I was at another meeting in the afternoon at Hitchin;
and on the first of the week, was at the meetings at Northampton, forenoon and afternoon;
which were large, especially that in the afternoon, and very open and comfortable:
and the truths of the gospel opened clearly and plentifully,
with demonstration and authority,
to the sole praise of the great and gracious Giver of every good and perfect gift.
On the 19th, accompanied by Thomas Binyon, jun., I went forward to Leicester,
where I rested that night.
A meeting being appointed at Nottingham on the 21st,
the Lord favored us with a degree of his good presence;
and though we were in silence a considerable time, the things of God opened well,
and were delivered with good authority, there being some of the town`'s people there;
and all was very quiet and well.

On the 23rd I was at the week-day meeting at Blythe; which was small,
few Friends remaining there, but very open and comfortable.
On the 25th, being the first of the week, I was at a general meeting for worship,
falling of course at Warnsworth yearly about that time.
It was large and comfortable, the goodness of the Lord being sensibly with us.

On the 27th, accompanied by several Friends, we set forward for York,
by way of Tadcaster; where, falling in with other Friends from Leeds and places adjacent,
we all dined together at an inn; and before we arose from the table,
the divine Truth tendered me very much, and reached the Friends in general,
with a merciful visitation of his kindness, as in our early times;
and we were at that time as little children before him,
and satiated with the breast of living consolation in his presence, not to be forgotten,
but sealed on every heart, to the ever-living praises of the God of mercy,
and of our salvation.
We were reduced to silence.
From Tadcaster we went that evening to York, to an evening meeting there;
and the next day began the quarterly meeting for the county; that meeting,
at that time of the year, being commonly called their yearly meeting.
It held the 28th and 29th, was very large, especially in times of worship,
when many of other communions came in, and generally behaved well.
The Lord was with us; and things, both as to worship and discipline,
were conducted in the meekness of his wisdom, to his own glory,
and consolation of his people, without schism or jar.

And I,
desiring once more to see as many of the inhabitants of
the city at our meeting as could be,
upon full notice given them, stayed till the 2nd of the fifth month; where,
in the forenoon, the meeting was more select: but in the afternoon,
being put off till five in the evening, it was very large,
the greater meetinghouse being well filled; and I had,
through the infinite mercy of God, the everlasting gospel,
and universal salvation of God through Christ our Lord,
to preach to them in some good measure and authority;
and observed many sober and attentive persons of both sexes among them,
but others too airy and unconcerned, yet generally of decent behavior.

On the 4th of the fifth month I went to a meeting appointed at Huby,
about seven miles from York; which was small, but open and comfortable,
the goodness of the Lord being sensibly with us.

On the fifth I was at an appointed meeting at Thornton; which, in the beginning,
was hard and exercising, but through the mercy of God, was very open afterwards,
and ended well, to the praise of his own holy name, who alone is worthy.
On the 6th I was at Malton, where the Lord was with us,
and opened the mysteries of the gospel clearly;
and a good time the Lord gave us together, there being few besides Friends there.
On the 7th I had a meeting appointed at Pickering;
where Friends came from divers places round.
In this meeting we had a considerable time in silence,
and something in it very hard to be wrought through, a spirit of heaviness, carelessness,
and darkness; yet the arm of the Lord arose,
and the brightness of his living presence prevailed over death and darkness,
and the righteous rejoiced before him, in a sense of his never-failing goodness.
It was a comfortable time indeed to Friends in general,
raising praises to the Almighty author of all good, and he himself is that good.
That evening I went with Robert Milner and his wife to their house, about seven miles;
where I was kindly entertained.

On the 8th I went to Scarborough, and the next day being the first of the week,
we were favored with two good meetings,
the good presence of the Lord being with us to our great refreshment,
and the truths of the gospel were opened clearly, and with good authority.
We had two very comfortable meetings more that week; one on the fourth-day,
and the other on the sixth, as usual.
And staying till the 16th, the Lord favored us with his good presence,
and gave us two comfortable meetings;
wherein divers important truths of the gospel were
amply set forth in the authority and wisdom of it,
to its own praise and glory.
On the 18th I went to Whitby; and the next day, being their usual meeting day,
we were favored with a very open comfortable meeting,
the Lord being with us to our general satisfaction.
I lodged there at Thomas Birkit`'s; where I was kindly received and entertained.
I stayed till the 21st, and was at their sixth-day meeting, for they have two in the week,
which was very open and comfortable.
Friends being generally tendered by the influence of divine love,
the sweetness whereof seasoned our conversation afterwards.

On the 22nd I returned to Scarborough;
and on first-day the forenoon meeting was very heavy for some time,
many being very drowsy and unconcerned;
but the Lord favoring us with a glimpse of his enlivening countenance,
we were thereby refreshed, and the meeting ended well.
In the afternoon many strangers being in town, came to the meeting;
and the Lord favored us with his good presence,
and opened the important truths of the gospel with authority and demonstration; as,
the fall of man in the first Adam,
his restoration by the second Adam to the knowledge of divine life lost in the first;
the necessity of regeneration by faith in Christ,
and through the work of his power in us, as he is the quickening Spirit;
by which we are born of the elect Seed, which never fell,
and made partakers of the divine nature in him, to our everlasting establishment,
as that great and truly wonderful work is completed by Christ,
out of the reach of all temptation and possibility of any future fall,
resting in the unspeakable joy of the salvation of God forever and ever.
The meeting was very solid in general, some of the quality,
as they are distinguished among men, being there; and yet some of the baser sort,
though in gay clothing, could not hide their levity and extreme ignorance,
in some part of the time of the delivery of truths so
needful to be known and received of all mankind:
but they being only some private sneerers, there was no open disturbance,
and the meeting concluded in great solidity and decency, as usual in these days,
to the honor of the divine Truth, who alone is worthy.
On the 26th, being the fourth of the week, I was again at their weekday meeting,
and also on the 28th; where we had our meetings more select with Friends,
and we were comforted together in the Truth.

On the 30th, being the first of the week, in the afternoon especially,
came many strangers to the meeting: the truth of the gospel was,
in the divine power of it, preached among them;
under which they were generally sober and attentive,
several of the quality being present.
On the 2nd of the sixth month the meeting was again more select,
though some strangers of both sexes were there,
where the one true and saving baptism of the Holy Spirit was clearly preached;
when several of the auditory seemed surprised to hear
the absolute necessity of it set forth so plainly,
according to the holy Scriptures, and with an authority which carried the matter home,
in some good measure, to the hearts and understandings of several of the auditors.
It was a glorious and satisfactory meeting, through divine goodness, though not numerous.

My concern for that place continuing, I was at all their meetings,
both on first-days and week-days, until the 20th, and then went to Anthony Langley`'s,
a Friend`'s house, two miles beyond Bridlington, where I lodged that night;
and the next day had two open and satisfactory meetings with Friends and others.
That night I lodged at John Atweek`'s, where I was kindly entertained;
and at the same place had another meeting on the 29th in the evening,
which was very solid, and the doctrines of the Truth were set forth with clearness,
by the grace of God, and the virtue and authority of it,
to the praise of the only true and living God, who is worthy and blessed forever.
On the 31st we had another meeting there, which was very comfortable,
the goodness of the Lord being much over us,
and the kingdom of God was declared in the authority of it,
and the kingdom and power of antichrist thereby laid open;
being founded inwardly in the darkness of this world,
in the imaginations and corruptions of men,
supported by that wisdom which is from beneath, and the power of it,
under the conduct of false and degenerate priests,
who run for rewards in this world where God never sent them;
who have profited themselves by the spoils of the blind people,
but have not profited the people at all.

On the 1st of the seventh month I went back to Scarborough; and on the 3rd,
being the first of the week, I was again at the meeting there; where, in the forenoon,
the Lord gave us a plentiful season of his goodness,
and the meeting being for the most part of Friends, the testimony of Truth was,
in the openings of life, more adapted to them, for their confirmation and encouragement;
and a glorious, comfortable, and confirming time it was to many.
In the afternoon the strangers who attended the Spa coming in pretty fully,
many truths of the gospel and kingdom of God were opened to them,
in the love and goodness of God;
under a sense whereof the meeting was held throughout the time, to general satisfaction,
so far as I could gather from the attentive, serious and solid behavior of the people.
So that it seemed as if they were all reconciled in one, even in the divine Truth,
under the powerful baptizing virtue and influence of it;
and that evening the Lord gave me great consolation therein.

On the 5th the monthly meeting with Friends of Whitby falling of course,
I was there to my satisfaction; for the good presence of the Lord was with us,
and the discipline of the meeting was managed in the peaceable wisdom of Truth,
and in brotherly condescension and love,
to the praise of the great Author of every good and wholesome establishment,
and every good word and work brought forth thereby and therein;
being as the Tree of Life, bearing its fruit ripe, comfortable, delicious,
and strengthening.
On the 6th I took leave of the place,
having first acquainted Friends therewith in the last meeting,
and left them in love and peace.
That evening I went to Newton, and lodged at Robert Milner`'s;
and the next day in the evening had a meeting in his house with his family,
and a few poor, simple people of the national way,
to whom the Lord opened many helpful instructing things by my ministry;
but to the praise of himself only.

On the 8th I went to a monthly meeting at Malton;
where the Lord gave us a comfortable time,
and opened several things relating to the discipline of the church,
and moral virtue and conduct, in the wisdom and authority of the gospel.
A case of a reproachful nature being presented,
and having been debated in some former meetings,
several of the meeting appeared to defend the transgressor,
though the facts had been proved, and also confessed by him.
But the power of Truth being over the meeting,
and finding myself engaged therein against the spirit of contention,
I reproved its members, convicted them of the errors of their evil work,
and silenced them for that time;
which greatly encouraged the righteous servants of the Lord there,
who were concerned for the honor of the Lord and our Society;
and then the testimony of Truth went out against the transgressor with unanimity,
and the meeting ended in peace, to the satisfaction of the just.
On the 9th I went to York, to Roger Shackleton`'s,
and on the 10th was at their meetings both forenoon and afternoon.
It was the first-day of the week, and being very rainy,
the meetings were more select to Friends, though there were some strangers;
and a very comfortable day the Lord gave us in his ever-blessed presence,
and many good things were opened in his divine light and power,
to edification and confirmation.

On the 11th I went to Leeds, to my old and dear friend Benjamin Horner`'s,
and was at their meeting on the fourth of the week.
The forepart of this meeting was heavy, dark, and uncomfortable; but, by degrees,
light shined out of darkness, and dispelled its power in good measure,
to the comforting of the sincere-hearted, and the reproof of the idle, lukewarm,
and unconcerned among us.
On the 15th I was at another meeting there,
in a small meetinghouse in town erected for more select meetings of Friends,
especially the aged and infirm;
where the Lord was with us to our general comfort and edification:
for our hearts were made glad by the wine of his kingdom plentifully dispensed among us.
On the 16th I went to Bradford, to my friend Benjamin Bartlet`'s; where I was received,
as usual, with kindness and respect, which hath ever been mutual since first acquainted.
The day after, being the first of the week, I was at the meeting there;
which was very large,
many of the more reputable sort of people of
various professions of religion being present;
and the Lord opened many of the doctrines of the gospel among us,
during which there was general quietude and attention; and the meeting seemed satisfied,
departing in a solid condition.

On the 19th I went to my friend William Hird`'s, where I stayed that night;
and the next day was at a meeting about a mile from thence;
where the Lord favored us plentifully with his good presence.
It was a glorious meeting, to his own praise, of whom alone is the power.
On the 21st, in the evening, I returned to Bradford;
where the monthly meeting happening next day,
I had some service both in discipline and ministry.

On the 23rd I departed in peace for Leeds; and next day being the first of the week,
I was at the meetings there, which were very large, especially in the afternoon,
the meeting being put off till the third hour,
and many of the chief of the people of the town attended, and a very great crowd.
The Lord had regard unto us,
and was pleased to furnish me with understanding and strength, both of body and mind,
to deliver many things to them touching the knowledge of God,
and eternal life in and by Christ the Lord: the Truth was over the multitude,
and reigned; so that there was not a light countenance to be seen among them.
These are the works of God, by Jesus Christ the Lord,
through whom be the acknowledgment to the Father, now and forever.

On the 26th I returned to York with Friends from Leeds, and those parts,
in order for the quarterly meeting of the county, which began the next day;
the business whereof, as well as worship,
was conducted in the peaceable wisdom of the Son of God,
whose divine goodness and presence presided there.
Many great and important truths were delivered in the meetings by several brethren,
in the demonstration and authority of the Holy Spirit.
Here a person took down something I said in short-hand,
as he had done at some other times, as also of some others in other places;
which is seldom truly done: for though the form of speech may be, by that means,
and help of the memory of the writer and others, nearly recovered;
yet the missing or altering of a word in some
sentences may greatly alter and wrong the sense.
And it is certain that no letters, words, or speech, can represent the divine virtue,
power, and energy,
in which the doctrines of Truth are delivered by those who are sent of God:
for they speak with wisdom and authority in and from him,
and not as the artists and hirelings of this world and of antichrist,
whose speeches are often cunning and deceivable; whereby they ensnare the people,
rule over them, and make a trade and gain of them to themselves,
and live in the pomp and grandeur of this world;
though they promise and vow before God and man, to renounce these,
and make the people do so likewise,
and yet break those vows also as often as they make them; not once only,
but to the end of their days, if their daily confessions be really true.

Nevertheless, where testimonies are truly set down in writing, so far as they are sound,
with respect to faith in God and Christ the Lord,
or any other point of doctrine in religion,
they may be of use to help forward the work of the Lord,
in the redemption and salvation of mankind.
The meetings ended in the peaceable spirit and love of the Holy One,
in which they began and were held.
Divers departed the city that evening with satisfaction and consolation,
towards their several habitations; and yet, as pillars in the house of God,
depart no more therefrom, but remain therein forever.
But having no certain dwelling place on earth, though something therein I call mine,
and have just power over while in this body; and not being in haste for any other place,
I stayed to attend the service of the Lord in the next first-day`'s meetings in that city,
where we were favored with the divine presence,
and many important truths of the gospel were delivered in the authority of truth.

On the 2nd of the eighth month I went to Pontefract,
and had a satisfactory meeting there on the 3rd. On the 4th I went to Warnsworth,
to Thomas Aldam`'s, and the next day was at their monthly meeting,
where a case happened which admitted of some different ways of thinking;
yet Friends condescending one to another,
and the testimony of Truth going out against all
partiality of judgment in the things of God,
and against all sides and parties on any account whatever, there being no side or party,
save truth or error only,
things were carried on and finished in the peaceable wisdom of Truth,
to satisfaction and comfort.
On the 6th, in the evening, I was at an appointed meeting at Woodhouse;
whither came a good number of the neighborhood,
who were very sober and attentive to the testimony of Truth;
which was largely and demonstratively delivered among them:
and the Lord gave us a good meeting.

On the 7th I went to Sheffield, and the day after was at their meeting,
both forenoon and after; where the Lord was sensibly and powerfully with us,
to the glory of his own eternal name.
It was a day of satisfaction indeed to be lastingly remembered.
On the 9th I returned to Woodhouse, and the next day to Balber-Hall;
where I was kindly received by my long acquainted friend sir John Rhodes, Baronet,
a man of truth and understanding, who neglecting all the honor of the world,
had lived rather too reclusely;
by which the brightness of his talents had not
been made so conspicuous as otherwise they might.
Here I stayed till the 13th, and then went to Mansfield, to Richard Mariot`'s;
where I was kindly received by him and his family.
There I abode till the 15th with satisfaction, and it being the first of the week,
was at their meeting both forenoon and after;
where we were favored with the good and comfortable presence of the Lord,
and many things were opened in his wisdom and power, to the establishment of some,
and edification of the generality.

On the 16th I went to Nottingham, and the next day had a meeting there;
where the eternal Truth triumphed gloriously,
and the truths of the gospel were delivered with majesty,
bringing a holy dread over the assembly, mixed with consolation:
and many were tendered and comforted.
On the 20th had a meeting appointed at Leicester;
which consisted of Friends for the greatest part,
and we were favored with a fresh experience of
the merciful truth of that saying of the Lord,
"`Where two or three are gathered together in my name, there am I in the midst of them.`"
The comfort of his Holy Spirit was our enjoyment at that time.

The weather being very rainy, I stayed there till the 22nd,
and was at their meeting both forenoon and after.
The former was more select, consisting for the most part of Friends;
and the goodness of the Lord was sensibly with us, and things opened to satisfaction.
In the afternoon we had the company of many of the people of divers notions in religion,
and the Lord opened a door of utterance of many
truths of the gospel in the authority of it;
where divers false doctrines of the mercenary, deceitful letter-mongers were exposed:
under which the people were very still and serious, not a light countenance among them;
for the dread of the Lord was over them, and Friends were comforted in the Truth,
and in the preaching of it in its own life and virtue.

On the 24th I had a meeting at Northampton, where the goodness of the Lord was with us,
and gave us a comfortable season together in him, to the glory of his own name.
On the 25th I went to Newport-Pagnal, to Thomas Cooper`'s; where I stayed that night,
and the day after went to Amptel, to the widow Barber`'s;
where we had an evening meeting with a few Friends and some of the sober neighborhood,
to good satisfaction: for the countenance of the Lord was towards us,
and many things were opened in the Truth to the understandings of the people,
and helping forward of the work of God, through the word of his grace,
without which no minister can do any thing to convincement or edification.

On the sixth of the week I fell in with the week-day meeting at Baldock; which was small,
but comfortable, through divine goodness.
On the 28th I went from thence to Hartford, to John Prior`'s; and the day after,
being the first of the week, was at their meeting forenoon and after.
The former was small, but very tender and comfortable,
through the influence of the divine presence; by which divers,
even the greatest part were tendered and melted as wax before the sun,
and had the holy image of the Son of God, in some good measure, impressed upon them;
to his own glory, and magnifying of his own holy name,
to whom it is due now and forever more.

The meeting in the afternoon was much larger, many being there from Ware,
and of the town`'s people, who had heard of the first meeting;
and the goodness of the Lord was with us.
But my exercise in public was more laborious,
by reason of the various states of the auditory;
many things being delivered of general and particular importance:
and all were very still, attentive, and by all appearance comforted and satisfied.
To the latter meeting came my landlord Joseph Green, and Dr. William Clark, from London,
to meet me; and we stayed that night at Hartford,
and had an easy journey next day to London.

At London I remained until the 17th of the fourth month, 1739;
and on the 22nd got to the meeting at Leeds,
where I was much refreshed and restored in the good presence of the Lord,
after the most fatiguing and painful journey I had known in the time.
On the first of the week I was at the meeting there,
which was very large and comfortable;
the people being solid and attentive to the testimony of Truth,
and well satisfied with it.
On the 25th their monthly meeting was a good time;
the Lord mercifully favoring us with his good presence.
The next day, accompanied by Benjamin Horner and his wife, and others of his family,
etc., I went to York to the quarterly meeting; which was large,
and very peaceable and comfortable both in worship and discipline:
and the business of the meeting being fully over, to general satisfaction,
I returned to Leeds.

On the 1st of the fifth month, I went to a yearly meeting for worship at Bingley;
which was very large, consisting of many hundreds of people:
and the truths of the gospel being largely opened to them,
and no public minister there besides myself,
I was very much spent as to my natural strength, and now of great age;
but the Lord being pleased to restore the strength of my mind,
and being kindly entertained, in company with many Friends, by our friend William Lister,
at his house there, my strength, through the goodness of God, was soon recovered;
for the Lord sanctifies every blessing to the ends proposed in it.
On the 2nd I went to Carleton, and made a visit to William Slater, and Mary his wife,
both ministers; where I was kindly received, and plentifully entertained:
for though they were not rich in the world, they were rich in love and right friendship;
which is abundantly better,
and more acceptable than a great deal of fine dainties without it.

On the 3rd, accompanied by William Slater, I went forward to Settle; and next day,
being their monthly meeting,
the Lord gave us a very comfortable time of his good presence:
for our hearts were freely opened by him and unto him, who openeth and no man shutteth,
and when he shutteth, none can open.
After the meeting I went forward to Gale; and the next day to Kendal,
to a meeting of ministers, which was beginning when I alighted;
where the divine presence was likewise with us.
The next day I stayed there, to attend the service of their quarterly meeting;
which was large and edifying, both in worship and discipline,
and conducted in the peaceable wisdom of our Lord and Savior Jesus Christ; through whom,
to the Father of all our mercies, be dominion and glory, now and forever.
On the first of the week, I was at their meeting, forenoon and after, being both large,
especially the latter, which was put off until the fourth hour.
The Lord was with us, and brought many good things of his kingdom to remembrance,
with authority and clearness, to general satisfaction.

On the 11th I went to a general meeting at Preston; which was large,
and for the most part composed of young people.
The Lord blessed us together in his presence;
and many of the young ones were baptized of him by the purifying flame of divine love,
to their great consolation; entering thereby into a covenant of light and life with him,
according to his sure promise of old.
The meeting ended in the gravity of Truth.
I returned that evening to Kendal.

On the 13th there was a general meeting at Carlisle which was small,
but fully as open as I expected: for some in that place are far from the Truth,
though they have professed it long; and strangers commonly find little consolation there,
though some are very worthy.

On the 15th I was at the meeting at Carlisle; which, being the first of the week,
was pretty large, but hard, by reason of some evil and hardened spirits among them:
yet Truth was in some degree over the meeting.
On the 20th I was at the monthly meeting, which was pretty large,
the country Friends coming well in; and very open,
the Lord favoring us with his divine presence, and exalted his own name over all,
to the satisfaction of all the living among us.
On the 22nd I was at the meeting at Kirklinton, which was very large and open,
consisting for the greatest part of young people; who,
having heard of my intention for that place at that time, came for some miles round;
and being desirous in the Lord to do them good through his grace, I spared not myself,
but was much spent that day among them, leaving the effects to the Lord;
to whom be praise, for of him is the power and understanding.
Amen.

On the 29th I was at the meeting at Scotby; and though it was the first of the week,
it was not large, but very open and comfortable; for the Lord was with us,
to our solid and mutual satisfaction in him.
On the 5th of the sixth month I was at the meeting at Moorhouse,
which was large and very open; many truths being delivered with divine authority,
and thereby sent home on the consciences of several; who, professing the gospel,
were yet ignorant of the law of moral righteousness:
great tenderness came over the hearts of many, especially of the younger sort,
most of the meeting being of such.
For this day`'s refreshment in the Lord the living were
thankful unto him who alone is worthy.

On the 12th I went to Wigton; where the Lord favored us with his life-giving presence,
and opened the truths of his gospel, and the mysteries of it,
with demonstration and power, to the comforting of the living, and satisfaction of all,
for any thing that appeared:
and the hearts of Friends were open and free one toward another in the Truth,
especially in the afternoon meeting;
and in divers visits to particular Friends which
I made in company with others that evening;
and then I returned to Carlisle.

Having finished what was incumbent upon me in the country at this time,
I set forwards for London on the 15th of the sixth month,
in company with John Wilson of Kendal, a true friend of mine in the Truth,
and of great service in and to the Society of Friends in general,
both in the country and in the yearly meetings at London.
That night we lodged at Penrith; and next morning called at Lowtherhall,
to pay our regard to lord Lonsdale; who, as usual,
received us in a friendly and familiar manner;
and as he is a person of good understanding and temper,
we had agreeable conversation on divers subjects;
and a people of late appearing in this nation, to whom the name of Methodists is given,
and now the common subject of conversation, we had some discourse concerning them,
and the points of religion and doctrine which they hold and profess.

Their teachers are ministers of the national church of England,
for the most part regularly ordained according to that constitution;
but profess to have received the Holy Ghost, not in notion only,
but in reality and in deed;
and by whose qualifications and immediate assistance they profess to preach.
They insist much upon the doctrine and necessity of regeneration;
but deny that this work can be effected by the ministration of water in any form,
or by whomsoever administered; but by the Spirit of Christ only,
as inwardly made manifest in the heart.
They preach freely, as is commonly reported; and the national priests,
fearing some ill consequences may arise from this
people to themselves and their power and maintenance,
some of them have taken the hint early; and as their manner is,
have begun to hate and persecute them, both as to their profession of the Spirit,
and characters as men; calling, both in their pulpits and print,
upon the powers of church and state to suppress them, as a sect, which may, in time,
be dangerous to both:
though I hear nothing of any kind of immorality countenanced among them,
but on the contrary much brokenness of heart, and reformation of manners in many of them.
"`The tree is known by its fruits; and they that are born only after the flesh,
always persecute them that are born after the Spirit:`" but the Lord of life,
in his own time, will determine all points, and declare who is in the right.
But this is certain, that no persecutor, on any pretense, can be a Christian,
while in that state and practice, nor any national persecuting church a church of Christ,
the Lamb of God and Prince of peace; for all such are synagogues of Satan,
and not congregations of the Highest,
as all are who are gathered of the Father of spirits into the life, name, nature,
and power of his ever blessed Son, the Lord Jesus Christ.

Being invited to dinner,
we stayed and were entertained in a plentiful and friendly manner;
after which we took leave, and that evening got well to Kendal,
and on the 17th attended a week-day meeting there,
where the goodness of the Lord was with us;
and that afternoon was a meeting for Sufferings, and other business of discipline,
and concerns of our Society, managed in a prudent manner--the peace of God ruling all.
Here I rested till the 19th, and then was at the meeting, which was large,
and very open and comfortable; the divine Truth appearing gloriously, shined over all.
The afternoon meeting being put off till four o`'clock,
was neither so full nor open as expected, being deferred for the sake of the people,
who did not come as at some other times, yet the Lord was with us,
though my exercise was harder and more laborious than before.

On the 20th I went to Lancaster, and the next day, being the third of the week,
I had an open and comfortable meeting with Friends;
and that afternoon visited a Friend in prison, and the criminals there.
On the 22nd I went to Preston,
and on the 23rd had a good meeting with the few Friends there;
where we were favored with a renewed sense of the truth of that gracious promise of God,
that "`where two or three (of you) are gathered together in my name,
there am I in the midst of you.`"

On the 24th I went to Manchester,
and on the first of the week I was at the meetings both forenoon and after:
but some unskillful travellers being there at the same time, and but novices in the work,
they took up all the time in both meetings--for some can preach, such as it is,
when they will, and what they will, so that I was exceedingly laden,
and sensible Friends grieved, and others were disappointed.
Another meeting being appointed on the 28th, it was full and very open,
many of the town`'s people being there, and very solid;
for the Lord was near and with his own.
The next day I was at their week-day meeting; which being more select to Friends,
the Lord was with us, and we were much comforted together in him.

On the 30th I went to Stockport, and that evening had a large open meeting there,
many of the inhabitants being present; and many important truths of the gospel,
through the divine eternal Truth, in the openings thereof, were declared unto them;
and they were generally solid, attentive, and behaved well,
the invisible power of the Word of life being over them in general.
On the 31st I had a meeting appointed at Macclesfield; where there are but few Friends,
and but a small number of people came to the meeting,
that place being much bigoted to the national worship, and very high;
yet they were sober under the many things I declared among them.

On the 1st of the seventh month I went to Leek, and next day was at their meeting,
which is large, and some strangers of other professions were there;
and the Lord favored us with his good presence, to our consolation together in him.
The next day I stayed there, being wet weather, and the day after dined at Bargate,
at John and Joshua Toft`'s, they being brothers and living together,
and able ministers of the gospel.
On the 5th, accompanied by Joshua and another Friend, I went to Stafford;
where we lodged that night at an inn, few Friends being then remaining in that place:
and next morning I went forward to Wolverhampton;
where I was kindly received and entertained by my long acquainted friend John Fowler.
On the 7th we had a meeting there, though there are only four or five Friends remaining;
but some of the neighbors and strangers happening to be in town, and coming in,
we had an open lively meeting;
and some important truths were delivered among them in the life and power of the gospel:
and all of them were very solid, and some well affected in the time.

On the 8th I went to Birmingham, to the widow Pemberton`'s;
where I was well accommodated after a fatiguing journey: and the next day,
being the first of the week, was at their meeting forenoon and after.
The first was considerably large, many Friends belonging to it at that time,
and others came in also; but the latter was much crowded with all sorts,
so that many could not get in.
The important truths of the gospel and kingdom of Christ were
clearly opened to them in the wisdom and authority of it,
and they were generally still and attentive.
Truth was over all, and Friends and others seemed at that time all united in one power;
so that I hope some good was done among them.

On the 11th I went, through a furious storm of wind and rain, to Coventry,
and next day was at their week-day meeting; which consisted, for the most part,
of Friends, and generally very young.
I said many things to them, pertinent, as I thought, to their conditions;
but many being as the old bottles,
and some others not then capable to understand the doctrines of Truth,
the flowings of the divine life were not so plentiful as at some other times and places;
yet the good presence of the Lord was sensibly with us; and that is the substance of all,
and ever sufficient for all who love and fear him.
On the 13th I had an appointed meeting at Warwick, at Joseph Allan`'s,
where came in some few strangers, and sat with us in a sober manner a considerable time;
and divers were under a sense of divine goodness;
in which I had many things to say to them, which seemed to take good place,
and we were comforted and edified together in the Lord.

On the 14th I went to Banbury, to my particular friend Benjamin Kid`'s,
an able minister of the gospel, and growing and increasing therein.
I was made kindly welcome by him and his wife.
There I rested the next day; and the 16th, being the first of the week,
was at their meeting forenoon and after;
where the Lord gave us a comfortable day together in him,
and the testimony of Truth was over all; to the praise of him alone,
who worketh every good work in his servants,
and furnisheth them with every good word in season,
for the furthering and carrying on of his own work in the earth.
On the 19th I was at a meeting at Adderbury, which was small,
and heavy in the beginning of it; but the Sun of Righteousness arising,
the darkness with its powers were driven away;
and we rejoiced together as in the daytime, and had an open and comfortable meeting.
On the 20th I fell in with the week-day meeting at Bistor, which was very small;
yet the Lord favored us so far as to gather us into his own holy name,
where we were greatly comforted together in him: so that we know, it is not a multitude,
but the real sense of the divine goodness in our minds, which renders it a good meeting.

On the 21st I went about twenty miles to High-Wickham, to Thomas Olive`'s,
and on the 23rd, being the first of the week, was at their meeting in the forenoon;
which consisted, for the most part, of such as profess the Truth.
It was much shut up in the beginning,
many of them being such as have come into the profession by education,
and know little of the work of Truth in their hearts;
yet the Lord mercifully favored us with his goodness,
and the testimony of Truth came over all.
The afternoon meeting being put off till the third hour, and notice being given,
it was very large; and he that opens and no man shuts, and when he shuts,
no man nor angel can open the mystery of life,
opened freely and largely the things of his kingdom, with authority and clearness,
as in the brightness of the day of his power, to general satisfaction and consolation,
to the solid praise and glory of his own eternal name, who is worthy forever.

On the 24th I went to Chesham, and the day after, in the evening, had a meeting there,
to which came many of the town`'s people,
who were generally very sober and attentive to the testimony of Truth,
which was plentifully opened unto them; and the Lord`'s presence made it a good meeting.
On the 26th I fell in with the week-day meeting at Jordans;
and notice having been given beforehand, it was larger than usual:
and though heavy in the beginning, through the drowsiness of some,
the soul-reviving presence and goodness of the Lord gave us new life,
and we fared well in the end.
On the 27th I went to John Gurnel`'s, at Ealing; where I was kindly received.
I lodged there that night, and the next day went to London, to my usual quarters,
at my dear friend Joseph Green`'s; where I was received with kindness and respect,
as in all former times.
And having been preserved in health,
and still in a good degree of strength of body and mind,
through so long a journey and much bad weather, I was thankful to the Lord,
who leadeth out, preserveth through every event, and returneth in safety;
and yet in the course of divine Providence, though I have sufficient in the world,
and some possessions therein, I have no certain dwelling in the earth unto this day.

At London I remained, attending the meetings, until the 26th of the second month, 1740,
and that day went to Alban`'s,
accompanied by my friends Joseph Green and Thomas Whitehead;
and staying there that night, we were at the meeting next day in the forenoon;
where the Lord favored us with his blessed presence in a good degree.
That afternoon they went back towards London, and I proceeded to Dunstable,
and lodged with John Chester, an ancient and honorable Friend; who, and his ancestors,
had freely entertained Friends from the most early times of our Society.

On the 29th I went to Northampton, and appointed a meeting for the next day;
which was favored with divine goodness, and we were comforted together therein:
and the testimony of Truth was clear, and the authority of it was over all,
to the praise of Him who alone is worthy forevermore.

On the 2nd of third month I went to Nottingham, and there lodged at Francis Hart`'s;
where I met with hearty entertainment in the love of Truth,
in which they do it freely to Friends, many being entertained by them,
though they are not very rich in the world.
There I rested one day, and the next being the first of the week,
was at their meetings both forenoon and after; where the testimony of Truth was over all,
and things opening clearly in the divine light, were, through the aid of divine grace,
delivered with authority and demonstration.
Several strangers being there, all were quiet and solid, and generally satisfied.

On the 5th I went to Blythe, about twenty miles; and from thence, the day after,
to Warnsworth, to Thomas Aldam`'s, where I stayed that night;
and went the next day to Leeds, to my old and long acquainted friend Benjamin Horner`'s;
where I stayed two nights, being at their meeting on the sixth-day.

On the 10th I went to Bradford, and next day I was at their meeting;
where the Lord gave me an open door,
and it was a comfortable time in his divine presence and goodness;
and the testimony of Truth was over all in the wisdom and authority of it,
to general satisfaction.

On the 12th I went to William Slater`'s, who with his wife kindly received me.
They are not rich in the world, having a large family of children, a little house,
with many small rooms for entertainment, two cows and a horse,
and a little close of land to support them; and all laboring with their hands,
they live plentifully in a decent way,
and entertain Friends freely with the best they have:
which must needs be very acceptable to every honest mind,
and much more so than from the high and lofty rich of this world among us,
who entertain here and there one for their own name and honor, and not for the Truth,
or love of it; which is ever burdened among them, in the minds of all who dwell therein,
and travel not for entertainment in the things of the world,
but for the honor and exaltation, the publishing and declaring of the divine Truth,
in the power and love of it, for the salvation of the children of men.

On the 16th I was at Kendal week-day`'s meeting; which was very comfortable,
both in time of silence and testimony; in which the divine Truth triumphed gloriously.
On the first of the week I was there again,
and the Lord also favored us with his divine presence and goodness,
to the satisfaction of all the living, and to the praise of his own name;
and Friends were generally very loving and cheerful after these meetings.

On the 19th I went to Carlisle, accompanied by my friend Thomas Ellwood,
and lodged with our honorable friend the widow Mary Jackson.
Soon after my arrival there, came on a monthly meeting;
where Truth was glorious in the power and virtue of it, to the stirring up of the drowsy,
idle, and careless among us,
and the just reproof and rebuke of busy-bodies in other mens`' matters,
neglecting what is properly their own;
and inventors of false accusations and evils against others--by surmises of
the evil one in their own depraved minds--of whom they know no evil,
or ever saw any thing like it in those they accuse in the dark among themselves,
in their evil communications.
Thus they defile and deprave each other, to the hurt of many, breach of charity,
and hinderance of the progress of Truth in the love of it among brethren,
to their own utter ruin and overthrow in the end;
persisting in that great sin manifested, judged and condemned of God,
and his true servants from the beginning.
Some of the principal things insisted upon were as follows: "`' Report,
and we will report;`' that old corruption is too
much rampant and in fashion among you this day.
Know ye not the state of those,
and what and who they are on the left hand of the judgment seat of Christ,
to whom it is said, '`Go ye cursed into everlasting fire,
prepared for the devil and his angels?
Do you really know who this devil and his angels are,
against whom this dreadful sentence is denounced by the Judge,
the all-wise and all-knowing Judge of the world, of the living and the dead?
If you do not, I will endeavor to inform you,
that your conversation may not be with them;
but in innocence and holiness to communicate with the just, to edification and comfort,
and escape the destructive effects of the vile and evil communication of drunkards,
liars, and the unrighteous of every denomination.
Too many of such being crept into the profession of Truth at this day,
have brought reproach upon the Lord, his Truth and people,
to the stumbling of many souls who have been seeking the Lord in secret,
and pointed in themselves towards his people; of whom having had good sentiments,
and yet seeing such things too visibly prevail, by the transformation of Satan,
and false pretenses of those his children, they have stumbled, gone backward,
and fallen from the beginning of that work of salvation they once knew;
and so may be utterly lost, save for the application of infinite goodness and mercy.

Now as to these terms which I was but now about to explain unto you, the word Satan,
in the language in which that part of the Scripture was written, signifieth an adversary;
being properly applicable to that evil thing in mankind,
which worketh in their imaginations every evil thought, and brings them forth,
as man closeth with them, into evil words and actions;
and as the destruction of souls is thereby effected, he is an adversary unto them,
even the greatest they have, though under the false pretenses of our friend,
to gratify all those evil desires himself is the father of in our deceived hearts.

"`And as to that word which is translated devil into our language,
it properly signifies a calumniator and false accuser.
He is the inventor of evil and evil things: he is the liar, and the father thereof;
and when he speaketh a lie, he speaketh of himself.
He hath no foundation for what he saith, and all liars are his children: for though,
by nature, they are the children of the first Adam in the flesh, yet, as to their minds,
they are so depraved and debauched, by hearkening to, and obeying this evil one,
and so united and incorporated with him, that they are one with him,
and the propagators of his works and kingdom in and among the rest of mortals;
not always by human design,
but under the delusions and deceptions of him who subtly worketh in them,
even often out of their own view.

"`And as to the angels of this devil,
the calumniator of God and man from the beginning of the world,
this word angel signifies a messenger sent by another;
then he who inventeth calumnies and false reports against others,
and they who receive them, spread and carry them about,
to the dishonor of God and hurt of mankind, as they are become one with that evil one,
and one with him in his work of evil, he and they have one and the same sentence,
'`Go ye cursed into everlasting fire prepared for
the devil and his angels:`' as much as to say.
Go ye workers of iniquity into that exquisite and everlasting punishment due unto you,
as the necessary effect of your own apostasy from all good, and of living in evil.

"`And I further observe to you,
that the word fire in the text imports the most
tormenting and painful properly to flesh and blood,
and the most dreadful too, known to mankind.
And also what the apostle James hath written to this effect,
'`Let not him who is tempted say, he is tempted of God, for God tempteth no man,
neither is he himself tempted of evil;
but he who is tempted is led aside of his own lusts, and enticed.`'
And as this apostle maketh no mention of any other devil in this text, but our own lusts,
let us all be so aware of them, every one in himself, as not to think, or speak,
or act according to them, and that evil one, who worketh in them and by them;
but through the divine eternal Truth, the Holy Spirit of Truth,
revealed in us through Christ our Lord, in whom we have believed,
mortify the deeds of the body; and then shall we conquer all evil,
and subdue every temptation towards it in due time,
and live in and unto him who died for us; and in the end of all, see evil no more,
nor any devil: to which I fervently exhort this day.

"`Now as to some of the evil fruits and consequences of evil surmising,
and the bad and pernicious effects of it to Christian consolation, society and love,
this being an evil work, and child of the darkness of this world,
it is conceived in darkness; in darkness it is brought forth;
in darkness it wandereth about from house to house, corner to corner, place to place,
till many are corrupted thereby,
so as to entertain evil thoughts and form false sentiments of others,
by means of those lying surmises,
of whom they never saw or heard evil in all the time of
their acquaintance and frequent conversation with them.
You may easily conceive, that if any entertain thoughts of another,
as if guilty of any particular evil,
such can never have real unity with such a one as he at the same time judges,
or censures as if guilty.
-For though false, it hath the same consequence, in that respect, as if true;
and the evil surmiser, by that means, becoming distant, shy,
and averse to the person censured, it hath the like effect upon him likewise:
so that there is no unity in the ground between them, but a bare outward show,
and no truth or sincerity among them, but they become hypocrites one to another.
I do verily think this secret evil hath done more hurt to Christian society in general,
and to us as a people in a more particular manner,
than all the open and flagrant sins which any
among us have ever fallen into unto this day;
for open evil is seen of all,
and judged and condemned of all persons and all denominations,
and therefore the failings of particulars are no way justly imputable to generals;
but secret evils reign and rage in the dark, as with toleration and authority.
Yet such is the common consent and joint sentiment of a mankind,
that to be convicted of a lie, or called a liar, false accuser, or calumniator,
is highly offensive to mankind, even to be supposed to be guilty of it;
and of which all are ashamed when duly convicted by proper evidence;
such as have heard with their own ears, seen with their own eyes,
and thereby known and understood the Truth, and not with the eyes and ears of others,
who say and report things which they have not seen or heard,
and consequently have never understood, or can;
there never having been such things at all.`"
Friends were exhorted to beware of all those great evils,
and to do or say nothing inconsistent with true and Christian love,
which is the law of divine and endless life in all the faithful and obedient,
and of all their conversation and dealings one with another, and with all men:
take the counsel of the apostle on that subject, "`Let love be without dissimulation;
love not in word, nor in tongue only,
but in deed and in truth:`" with much more on the same subjects.

I was some time after likewise at a quarterly meeting at the same place, (Carlisle);
where the subject matter brought to remembrance in the sense of Truth,
was concerning judging one another, and judgment;
in which I observed to the auditory the great error of mankind
in advancing themselves into the seat of judgment over another,
and most commonly in things wherein they have no evidence or power,
contrary to the doctrine of Christ, and his practice and example;
whereby in consequence and the nature of things, they detrude him from his office,
and usurp his throne, who said, "`Judge not, that ye be not judged;
for with what judgment ye judge ye shall be judged, and with what measure ye mete,
it shall be measured unto you again.`"
Even where there may be some seeming appearance of evil upon others,
we are cautioned against judging without knowledge or moral certainty.
"`Judge not according to the appearance, but judge righteous judgment.`"
We ought therefore to be very tender and cautious in this point,
lest whilst we rashly censure others without adequate evidence,
we bring upon ourselves the heavy stroke of the righteous judgment of
God for our false judgment and censure of the innocent,
whom the Lord hath made and preserved of his own good will and pleasure.
For, as all have been sinners, though not in the same manner,
as such they have no right or authority to judge one another.
God only, who knows all men, and our various motives to every thought, word and deed,
can judge rightly among us, and of those things between the Lord and the soul,
and award wages unto all, adequate to every state.
Nevertheless, where any are so unhappy as to commit evil of any kind,
and are justly accused of it in a regular manner before proper judges,
then they ought not to deny their faults, but freely to confess them to others,
that the offenses thereby given to particulars and the general, may be passed by,
and the penitent kindly restored: for conviction is by judgment,
that repentance and amendment may engage the
healing application of forgiveness and mercy.

I also observed the conduct of Christ in the
case of the poor woman taken in the act of sin.
Her accusers were all sinners, though perhaps not in the like thing,
and therefore had no power or right to censure her;
and besides they had an evil design in it against the
Lord himself with respect to the law of Moses,
by which, though in a tumultuous manner, they pretended to judge:
but the Lord who knew them well, and their evil design,
put them all to silence by bringing their own sins into remembrance to themselves,
and over them; and then they slunk away, ashamed in themselves as guilty sinners,
though so lately before they had triumphed over her whose sin was open,
and while their own was secret unto other men,
but known unto him by whom God created the worlds, and judgeth the thoughts, words,
and actions of men.
This great and notable example was not to encourage evil;
for though he did not condemn her,
not being judge according to the constitution of their law,
yet as the Messiah of God unto that people,
he gave her a merciful deliverance and exhortation, saying, "`Go thy way, sin no more.`"

And these are not the only instances whereby +++[+++we are taught that]
we ought to be very cautious how we censure one another without one another,
and that in a gospel way; for Christ saith of himself as man, "`I judge no man;
but the word which I have spoken, the same shall judge him at the last day.`"
Again, saith the apostle, "`I judge no man, no not even my own self.`"
Seeing therefore that Christ himself, as man, though the Son of God too, as such,
judgeth not without the Father;
and that apostle who referred himself also to the judgment of God,
as only righteous and good, did not assume judgment, and the seat of it, over mankind,
till given of the Father in his own proper time; who then art thou, O bold, arrogant,
hardened and presumptuous sinner, who exaltest thyself into that dignity and office,
which none hath right to, but whomsoever the Lord himself will call, qualify and advance?
These are not Pharisees, self-promoters, the proud, high-minded and unrighteous;
but such as being redeemed, through grace, from all iniquity,
he hath appointed them judges in truth over such
as sin against the righteous rules of Society,
and moral truth, and are justly convicted by moral evidence:
but secret things belong unto God only,
who knows the secrets of all hearts to perfection, and none else ever had, or can have,
and therefore the Lord alone hath that prerogative and right.
Many other matters and things were then delivered, not to be recounted at this time.

I was also at another monthly meeting there, and at some other meetings,
especially on first-days, at Scotby, Carlisle, the Moorhouse, the Border, and Wigton;
in all which the Truth triumphed gloriously, and especially at the last place;
where that day, and the testimony of Truth, will not be soon forgotten among them;
and many strangers of the town were also there, whom Friends had invited,
who behaved in a very decent manner.

I was likewise in the country occasionally: for as that estate,
which had been my father`'s inheritance, was providentially fallen into my hands,
and the small buildings much decayed,
especially by the severity of the extraordinary frost during the last winter,
by which many of the walls were rent, and nearly overthrown,
I thought it not equal to receive rents for the
premises without proper habitations for the tenants,
and therefore was willing to repair them, and erect others where necessary;
and in order to make some preparation for such a work,
I stayed in the country till the 15th of the sixth month;
and that day accompanied by my friend Thomas Ellwood, whom I met with at Carlisle,
we went that evening together to his house at Kendal.

On the 16th I rested there; and the day after, being the first of the week,
was at the meeting fore and afternoon.
The first was very open and comfortable,
and the Lord blessed us with a good degree of his confirming presence:
but that we might sensibly experience, that in the Lord alone are all our fresh springs,
as from an endless ocean of all fulness, and that it is not that which hath been,
but that which is present, on which we must depend,
in humble submission to his will and time,
the meeting was heavy and lifeless a long time in the afternoon;
yet the Lord showed mercy toward the end,
and brought that wholesome request and exhortation of the apostle into my remembrance,
and I believe in some degree of the same life in which it was written,
"`I beseech you brethren, that ye present your bodies a living sacrifice,
holy and acceptable unto God, which is your reasonable service.`"
The body being of the earth, is of itself dead and inactive;
but as it is in vital union with the mind -- which is of a very different nature,
being more subtile and moving--it moveth the body and acteth thereby as it pleaseth,
in things within the reach of its power, in its present state and mode of being;
and yet can act nothing acceptable unto God, but as quickened,
strengthened and moved by the influence of the Holy Spirit of Christ,
the mediator in all acts of worship.
Therefore we must wait for him at all times, in passive silence of mind,
to be rightly fitted under an exercise of faith and hope toward God;
and the Lord appeareth in his own time, when the creature seeth its own want,
and that there is no help but in the Lord alone;
then he ariseth as the brightness of the morning,
and thereby disperseth all the fogs of the night.
And since "`the last enemy that is to be destroyed is
death,`" how can that enemy be overcome by such,
who, in times of worship, continue to be overcome, by his image?
"`I speak as unto wise men, judge ye what I say;`" and be sincere and vigilant,
that the Lord may bless you in all your meetings with his living presence,
and preserve you all alive unto himself to his own glory.
And the Lord gave us the victory in the end.

On the 18th I went forward to Settle, to William Birkbeck`'s junior,
where I stayed that night; and next day to Bradford, to my friend Benjamin Bartlet`'s;
rested there that night, and next day being the fourth of the week,
and their meeting-day of course, I was at the meeting,
where the Lord comforted us together;
and most of the young people were tendered and broken,
under the influence of the testimony and ministry of Truth delivered among them.

On the 21st I went forward to Newel Grange, and on the 24th, being the first of the week,
I was at the meeting at Nottingham,
where the Lord comforted many in a sense of his goodness;
and there being many of the town`'s people,
the Lord opened divers important truths of the gospel instrumentally among us,
with authority and demonstration, to the praise of his own divine wisdom and power;
who is worthy forever.
The people were sober; and I believe many of them departed in a sense of divine peace.

On the 25th I went forward to Leicester, the day after to Northampton, and the next day,
being earnest for London, I went to Joshua Wheeler`'s at Cranfield,
and from thence to my old friend John Turner`'s at Hitchin, where, being wearied,
I rested till the 30th; and then, accompanied by him, to Hartford, to John Pryor`'s,
where I lodged that night; and next day was at the meeting in that town,
where the Lord favored many with the sense of the divine presence;
and divers truths of the gospel were published in the authority and dominion of it.

That night I remained there; and on the 1st of the seventh month,
accompanied by several Friends from Hartford, and others also from London,
who met us half way, I went thither in the evening to my usual lodgings;
where I was as well received as ever,
though at that time it was truly a house of mourning; for my kind and good landlord,
Joseph Green, a man of sincerity and truth, and his eldest son,
a hopeful youth of about nineteen years of age, had been lately buried,
dying within a few hours one of another,
and left one of the most mournful widows and mothers I have ever observed.
They loved each other most tenderly, after having been married about twenty years;
and having three other younger children, the whole care of them fell upon her,
with the weight of all their affairs and business in the world,
which was very considerable; and the concern which fell upon me, in Cumberland,
when I heard of this stroke of Providence, for the widow and children,
if peradventure I might be helpful or serviceable to them in any kind,
had hastened me thither much sooner than otherwise I intended.

The author`'s account breaks off here, which seems somewhat abrupt;
and as the editors have not been able to discover any
further prosecution of the work amongst his papers,
they apprehend it may not be amiss to add, that he continued in London,
sympathizing with, and assisting this afflicted family, part of the ensuing winter;
where he was seized with a paralytic disorder, which affected him to such a degree,
as deprived him very much of his speech,
and confined him within doors till the return of the spring.
He then regained a little strength, and got out to meetings;
but was still not so far recovered as to be able to hold a discourse long,
his memory being greatly impaired by the disorder.
Nevertheless he continued sweet in spirit, and pleasant and cheerful among his friends,
whom he was always glad to see, and to be in company with.
He diligently attended the yearly meeting at London this season, A. D. 1741,
though he spoke not much in it.
Before the end of summer he grew so much better, that he travelled to Carlisle,
to look after his affairs in the north, which required his attendance.

Having a design to build a house at Justice-town, he provided materials,
and frequently overlooked the workmen;
and indeed his health and faculties were so well restored,
that he many times appeared in public in the meetings,
greatly to the satisfaction of Friends.

Thus he continued without much alteration, till the 23rd of the fourth month, 1742,
being the first -of the week; when, in the evening, he had a new attack of his distemper,
which seized him with great violence; and the next morning,
between two and three o`'clock, he departed this life, in perfect peace,
we have great reason to believe, with God and mankind.

Two days afterwards, on the 26th of the said month,
his corpse was interred in the burying ground at Carlisle,
being attended by a great number of Friends from several parts of the country,
and also by divers people in the neighborhood;
who seemed deeply affected with the loss of a man so valuable
and useful to his country in several stations of life.
