== An Appendix.

[.chapter-subtitle--blurb]
Containing several conferences,
which Thomas Story and others had with the Duke of Somerset,
the Earls of Carlisle and Sunderland, the Archbishops of Canterbury and York,
and the Bishop of Carlisle, in relation to soliciting a bill in Parliament,
to remove the inconveniences which many of the people called Quakers did then lie under,
by reason of difficulties relating to the forms of the solemn affirmation,
as prescribed by former Acts of Parliament.

=== With the Earls of Carlisle and Sunderland.

Some Friends in London, of whom I was one,
being in a particular manner concerned in mind,
that the king and Parliament might be addressed for an
affirmation Act more generally satisfactory,
according to the agreement of our yearly meeting on that behalf;
I wrote a letter to the Earl of Carlisle,
ever a sure friend to our Society on all occasions,
entreating his advice to which of the ministry we had
best make our first application on that account.
He was pleased to send me an answer by one of his servants,
wherein he invited me to his house in Dover street, London, to confer on the subject;
and when there, being together in a parlor, his eldest son, the lord Morpeth came in,
to whom he said, "`They (meaning Friends) are an honest good people,
serviceable and helpful in the nation, and true friends to the government,
on the principles on which it now stands;
but because of some opinions they hold in matters of religion,
the laws are against them in divers respects, and particularly in cases of oaths,
which they think not lawful for them,
as apprehending they are forbidden by Christ under the gospel.
Be that as it will, I think they deserve relief,
and I have ever contributed as much towards it in all cases as I could; and I know,
from the many applications made to me on that account,
that they have suffered for not taking the oaths,
and do suffer very much in their families and business,
by refusing to take an affirmation, which was intended for their ease,
but does not prove generally consistent with their sentiments on that point:
and as they may have occasion, ere long,
to solicit the favor of the house of commons for further redress,
(of which the lord Morpeth was then a member) I expect you will favor them,
and use your interest on their account;`" which the young lord promised he would.
By which I observed that this great man was willing to
transmit his own good-will toward us as a people,
to his son and heir-apparent, and render it, in a manner, hereditary in his family;
for his grandfather had ever been our friend from the beginning,
and kept off the stroke of persecution in the worst of times, wherever he had any power,
especially in the north of England; where, in those days, he was much conversant.

Upon this occasion the earl informed me, that the Earl of Sunderland,
being secretary of state, in great favor with the king and sway at court,
as well as friendly to us,
was the most proper person to make our first application to in that point,
to know the mind of the king, of which we were not altogether ignorant before,
and on what we might depend from the rest of the ministry.
"`But,`" said he, "`the Earl of Sunderland, considering the duty of his office,
the great business of it, and assiduous application necessary therein,
cannot be spoken with but at some uncertain times.
But, to make it the easier, as he comes some times occasionally to my house,
I will give you notice of the first opportunity that happens,
where you may speak with him more freely than you can among a
throng of people constantly attending him at home.`"
He then advised me to have in readiness a copy of the affirmation as it then stood,
and also of the form of words agreed to in our yearly meeting.

Some days after this he sent me a letter by a servant, wherein he gave me notice,
that the Earl of Sunderland was then at his house,
and might be spoken with before he went thence.
I went immediately to him; but when I came there, the low rooms were crowded with people,
some with applications to one of these great men, and some to the other;
but notifying the Earl of Carlisle, by one of his servants, that I was come,
he came down himself among the crowd; and taking me by the hand,
invited me to an upper room,
next to where the Earl of Sunderland was with some persons of distinction,
and bid me stay there till he came to me, which he did in a short time,
and then introduced me to the Earl of Sunderland;
who received me in a very friendly manner.
I then made known to him my business, and said, "`That though the king, his ministry,
and the Parliament, had lately intended us a great favor,
in perpetuating the affirmation Act as it then stood,
yet it did not answer the end proposed;
for a great part of our people could not comply with it, the terms,
in their apprehension, importing a difference from the doctrine of Christ.`"
Then I produced the form in the Act, and that also which our meeting had agreed to;
which, when he had read, he said, "`You might have had the latter as soon as the former,
if you had applied for it;
for what we did in it was with intent to serve you in your own way:
and you yourselves soliciting for it, we thought we had fully gratified you;
and were informed, that but a few of you were dissatisfied with that form,
and those a sect among you, misled by Mr. Penn, in disloyalty to the government,
and in favor of the Pretender,
and who did not desire that favor from the present government,
hoping for it by another in time;
and those who were satisfied with that form were Mr. Mead`'s friends,
and principled for the revolution, and present government in the house of Hanover;
and the one sort called Pennites, and the other Meadiles.`"
I replied, "`This is only a calumny, artfully invented to defame our Society,
and render the more distressed part of us odious to the king and government,
that we might have no relief; and it is a great cruelty and hardship.
And I have hoard that Aislaby, then chancellor of the exchequer,
and a member of the house of commons, was so far imposed upon by that suggestion,
as to report it in the house, when the matter was in debate there,
whether the Act should be perpetuated or not.
I added, That I did not know, or ever heard of any such sect, party, or parties among us,
so attached to William Penn or William Mead, or to any other person;
for we are not a people subject to be led by sect-masters,
if any such should appear among us,
but to follow God and Christ only in matters of religion; and as such,
denying of all oaths we believe to be a part of our duty.
I was long and intimately acquainted with William Penn,
and knew his sentiments with respect to the government and Pretender;
and though he ever retained a great respect for all that family,
I believe he did it in point of gratitude for
the protection he had from the Duke of York,
afterwards king James, in a time of great persecution,
and not from any principle of disloyalty to the present king or his government:
but as to those among us, who cannot comply with the present form of the affirmation,
I know they are generally as loyal to king George, and true to his government,
as any of his subjects in all his dominions;
for I have lately been among them in a general way.
And the Earl of Carlisle himself likewise knows, that many of our friends,
whom he hath relieved by his interest,
who had suffered much for noncompliance with the affirmation,
were as loyal as any others.`"
The Earl of Sunderland, being himself a very good friend of William Penn,
spoke respectfully of him, and said, "`That gentleman (meaning,
Aislaby) was not your friend at that time,
but you will find him otherwise now:`" and then added with a smile,
"`He shall be your friend.`"
To which I returned, "`It is enough!`"
Then he said, "`It is not so easy a. matter as you may think,
to bring a thing of this nature through both houses; yet we can do it,
and you need not go to the king about it; for you are in his favor,
and therefore he will not oppose what we (meaning the
ministry) may think proper to advise him.

And I can tell you more, the greatest part of the bishops will be for you:
we have seventeen of them secure already,
and there may be more by the time that it may be proper logo upon it.
But then,`" said he,
"`will this please you if done`'? Will you make no further scruple about it?`"
To which I replied, "`If you will be pleased to enact this form,
or something of like import of no higher nature,
I dare venture to say our Society will not give you any further trouble about it.`"
And I told him, "`I do not come at this time by any direction of our Society,
but only with the privity of a few, who are of the dissatisfied,
to learn the mind of the ministry,
and to be instructed what measures to take in this affair;
since we are determined not to move, but by their privity and assistance;
though both the satisfied and dissatisfied are one in this solicitation.
For as the one side hath been willing the other should have their liberty to use it,
when they could freely do it, for relief of their families,
without any breach of union among us;
so the other are willing to join with them in one interest,
to solicit for such a form as may be easier to all.`"

All this being ended, I made him acknowledgments for his favor,
and returned with satisfaction and peace,
not doubling from thence forward but that we should succeed;
though my confidence was not from what this great minister had said,
but from the evidence I had from the divine Truth,
that it was my business and duty in his service,
and for the help and preservation of his people, to go about it at that time,
according to what our Society had agreed to among ourselves in the yearly meeting:
and that saying is worthy of everlasting remembrance,
"`That whatsoever ye shall agree to ask in my name, it shall be granted.`"
And in this name alone do we confide, and did so in that affair.

This passage I related to some Friends concerned fur a new affirmation,
which gave them considerable satisfaction,
and then made it known to some of the other side; who,
though they had used the affirmation as it then stood,
yet were heartily concerned for the other Friends, and for universal liberty;
and particularly Andrew Pitt and Joseph Wyeth, with whom I was very intimate,
and knew them to be true friends to mankind and just liberty.
I moved the matter first to Andrew, and told him what I had done,
and the encouragement we had from the Earl of Sunderland.
He answered, "`The stations such great men are in,
oblige them to give soft and obliging answers in a general way,
but the alteration of circumstances often altered their measures;
so that they cannot always do as they intend.`"
I told him I did not doubt his veracity, but had a better foundation yet to trust to,
and did believe, that if he and Joseph Wyeth,
and some others of the Friends on that side,
who were rightly concerned for general liberty,
would set freely about it with the other Friends, we should obtain what we all desired.
Then he said, "`If I was to be governed by just resentments I was once ready to yield to,
by some ill usage I met with from persons amongst us, against the present affirmation,
who misrepresented me as untrue in the former solicitations,
and even a counter solicitor, I would not set one loot forward in their assistance;
but I give thanks to the Almighty, by whose grace I am furnished with a better mind,
and by whose providence we are furnished with an opportunity,
to evince to mankind how ready we are to give that liberty,
and to procure it one for another, which we have desired of our superiors.`"
And then kindly added, "`I will go with thee to any man in England thou wilt desire,
and thou shalt be witness thyself of the sincerity of
my endeavors and solicitations that way,
and will assist to the utmost of my power with all my heart.`"

I replied, "`I am gad to hear it; and since thou hast said it,
no doubt can remain with me of thy sincerity,
and thou mayst do it in thy own way and time;
for such an inspection does not become the friendship I owe thee,
nor the just confidence I place in thee.`"
So we parted at that time.

I mentioned likewise the same matter to my very sure friend Joseph Wyeth;
who instantly declared his readiness to fall in with any
proper measures for the effecting so good an end as an
affirmation which would make our whole community easy:
and he had before had it so much at heart, that he had written to the king about it,
of which I was not then apprized.

Joseph Wyeth being in a particular manner in favor with the king,
no doubt but his letter had good influence;
for the good king George very much favored our applications,
and passed the Act for our relief in that case with all readiness,
from a real favor to our Society, and a settled design and purpose to do us good.
And yet the whole is to be attributed to the goodness and mercy of God to his people,
to preserve us as one in him, who turneth the hearts of kings as the streams of water,
and doth in the kingdoms of men whatsoever he pleaseth.
And it was very obvious that the divine Truth was over
the legislature in a general way at that time,
though some of the lords, who were anti-courtiers,
and opposers of all the king`'s measures, did not assent;
yet not in dislike to our liberty, etc.

=== With the Duke of Somerset.

The day whereon the Act passed, in the morning, along with some others,
I waited on the Duke of Somerset, at Northumberland House, by Charing-Cross,
to solicit his favor.

I acquainted him, that I had heard, as I came,
that both universities intended to petition against us,
as the clergy in and about London had already done,
which might give us much trouble and delay, if not bring our bill in danger;
and therefore I entreated that he would please to use
his interest for the passing it into a law that day.
Upon this he said, "`Perhaps Oxford may attempt something that way,
being influenced by the bishops of York, Chester, Rochester, and the rest of that sort;
but if they should, they are obnoxious, and will not be heard: and as to Cambridge,
they have done nothing, and I being their head,
(He was Chancellor to the University) they can do nothing without me;
and to make you easy, they shall not do any thing against you in this concern.`"
And then he said, "`There are a company of fellows, calling themselves the clergy,
in and about the city of London, who have sent in a petition,
wherein they pretend to blame both houses of Parliament for encouraging a sect,
which they rank with Jews, Turks, and other infidels;
as if we were to be imposed upon by them, and receive their dictates,
or knew not what we had to do without their directions.
And besides, we do not know who they are;
for there are above five hundred of the clergy in and about London,
and we find only forty-one names to their petition, and these very obscure.
Where is their Sherlock, their Waterland, or any of note amongst them?
Do these fellows see any corn growing in the streets of London,
that they should meddle in this case!`"

Then I informed the duke, that I had also heard that morning,
that many of the petitioners were three-penny curates, and unbeneficed.

The duke asked, "`What are they?`"
I replied.
That I had been informed they were poor clergymen, without benefices,
and had but few friends, and perhaps some of them Non-jurors, who hang on about the town,
looking for preferment; and being very indigent,
say prayers for the richer sort for three pence a time, which is paid,
two pence in farthings, and a dish of coffee.

This first occasioned the duke to smile,
and afterward drew from him some warm expressions of resentment,
that the poorer sort should live so abjectly, whilst the rich were so high;
but most of all,
that the rich should set so low a price upon the services of their poor brethren,
who did the work: and then he added,
"`We (meaning the legislature) know how to apply a remedy, and relieve them;
it is but to take off the pluralities, and make more equal distribution,
and then these poor fellows may be better provided for, and live.`"
Finding the duke in a temper to bear it at that time, for he was a great man,
and naturally of a very high spirit, but good sense, I replied.
That the pluralities had, for many ages,
been complained of as a very unreasonable thing in the church of Rome,
where it first began,
long before the time of the reformation of the national church of England;
and I have read a sermon of a good old reformer on that subject, one Bernard Gilpin,
who composed it in Edward VI.`'s time, with design to have preached it before that prince;
but his opponents contrived some means to procure the king`'s absence at the time;
yet the sermon was preached, inveighing heavily against pluralities as a great abuse.
Where then can the obstruction lie, that it is not reformed at this day?
To this he made no reply, but said, "`I am ready to go to the House,
where I would not have gone this day, but only to serve you.`"
That day, before noon, the Act was passed as now it is; for which we were thankful,
first to the Lord for his great goodness, in inclining the heart of the king,
and those of both Houses, so much to favor us; and next to them likewise,
as instruments in his hand of so good a work, and so great an ease and help to us.

=== With the bishops of Canterbury, York, and Carlisle, separately.

John Fallowfield, myself, and one more, going to Lambeth,
to solicit the concurrence of William Wake, then archbishop of Canterbury, with us,
in our endeavours with the king and Parliament
to procure an affirmation instead of an oath,
in terms less exceptionable than that then in force,
the bishop gave us a courteous and friendly reception;
and when we had told him our business, and exhibited our request, he, in a solemn manner,
expressed himself thus: "`Because of oaths the land mourns;
and it is shocking to observe with what levity and insensibility oaths are
administered and taken in this nation I i am for liberty of conscience,
where that is truly the case,
and could wish there were not any form of words
of any higher nature than you now solicit for,
to be used in this land in any case whatever; but if we should grant it to you only,
I fear the people would resent it, and blame us.`"
To this I answered,
"`That if he and the clergy would heartily concur in soliciting for
the establishment of such a form as we now desired,
I did believe our people would readily exert their utmost endeavors that way.`"

Then said the bishop, "`Put the case,
that any controversy should arise between any of the clergy and any of your people,
concerning what we call our dues, do not you think it were reasonable,
that we and our evidences should be admitted in the
controversy to the same form of words as you?`"

John Fallowfield answered, "`That he thought that could not be reasonable,
unless they had the same way of thinking as we,
and did believe themselves under the same obligation to
speak truth in evidence without an oath,
as with one, as we do; for lying and false witness are breaches of the commands of God,
and mortal sins as well as perjury.
And if your people, or such of them as might be called to witness,
should happen to think otherwise,
or that they were not so strictly lied up by such a form of words as by an oath,
they might equivocate, or venture to falsify; so that we could not have equal security.`"
The bishop very moderately took this answer, and made no reply.

Then I took the occasion to say to the bishop,
"`That notwithstanding the lenity of the government,
and the provision the legislature had made,
for the more easy and less destructive way of
recovery of what the clergy called their dues,
yet many of the inferior sort still continue to
take the most chargeable and ruinous methods,
in the courts of exchequer and chancery;
whereby many families were greatly distressed and reduced, if not ruined:
which did not only greatly oppress our friends,
but fixed an ill character and odium upon the clergy themselves in general.
For there is not a man so poor, if he is honest and a good man,
but that he is loved and respected by his neighbors;
and when such are oppressed by any of the clergy, though by a law, mankind,
who observe it,
are not always so just as to place the odium upon the single and immediate oppressor,
but rather to apply it to the whole body, and say.
See the clergy, who pretend to teach religion, how uncharitable, how covetous,
how cruel they are: here is a poor honest man and his family ruined for a trifle.
Now, considering the station and authority thou bears in the national church,
if thou would be pleased to advise them to greater moderation,
it might be helpful to many,
and prevent the odium which really militates against themselves,
as well as oppresses us.`"

The bishop being a mild tempered man, did not at all take this freedom amiss,
but replied,
"`That he had not that authority over the inferior clergy that we might think; for,
said he, they have the law on their side, and they know it,
and their highest regard is to their own interest;
and you have more authority among your people,
by your excommunications in your monthly and quarterly meetings, etc.,
than I have in the church by all the laws of the nation, ecclesiastical and civil.
I call it excommunication, you will not take that word amiss,
that is our way of expressing it.`"

I answered, "`That we did not lake any exceptions at the word; it was very significant,
and expressive of the thing;
only we think excommunication ought not to reach so far as they extended it;
it should not extend to men`'s liberty, property, or persons.
What we mean by excommunication is this:
when any one among us goes into any immoral practices or acts,
and after due admonition persists in any thing
contrary to the Christian faith and religion,
as we understand it, we deny such a one Christian communion,
or to be a member of our Society, until he repent, and by better conduct,
give ample proof of his reformation and sincerity.
And when such a delinquent is become a true penitent,
and desires to be reconciled to the body,
we apprehend it is as much the duty of the Society to receive him when so stated,
as before to bear witness against him, and deny, or excommunicate him.`"
The bishop made no reply to this; but only said, "`It is immoral in any one,
of any society, to break or reject the rules and orders of the society he belongs to,
or makes profession with; I say, such persons are in)moral,
and are not fit for any communion.`"

Speaking of the maintenance of the clergy, and their insisting on the law only for it,
he said, "`As to the right of our maintenance as ministers, whether of divine right,
or by the laws only, we are divided in our sentiments on that point.
There are about fourteen thousand of the clergy in this nation,
(as I remember he said) and I do not know on
which side of the question the majority may be.
But for my own part, for me to think I have this house,
(lifting up his hand towards the ceiling) or my bishopric, by divine right,
there is nothing in it; only,
as these are advantages annexed to an office by the laws of the land,
which office I enjoy by the favor of the prince, so I receive and hold it,
and no otherwise.`"
This I deemed a frank and honest confession, and could not but respect him for it.

Again,
upon my mentioning the severity and envy of some of the inferior clergy against us,
he granted, "`That these things brought an odium upon themselves,
and wrought against them; and added,
that he was against persecution in any degree or form;
and that if he was incumbent in any parish,
he would never sue any of our friends for his dues.`"
And then related to us the following passage: "`That a clergyman of his acquaintance,
having a presentation offered him to a church in London,
a friend of his would have dissuaded him from accepting it, because, said he,
there are many Quakers in the parish,
and you must either loose a great part of your dues,
or be perpetually at law and trouble about them,
which is not agreeable to your temper and quietude.
But, said the bishop, the gentleman replied,
that notwithstanding the number of Quakers in the parish, I will accept it,
and accordingly did; and being gentle and neighborly among them,
and never suing any of them, they took it so well,
that they generally made up his dues some other way,
and they lived very peaceably together.`"

To this I replied,
"`That it being matter of conscience in all of us that are true to our principles,
we could not justify any of our friends in taking any bye-ways
or equivocal methods to elude our profession in that case;
for whatsoever any man professeth as any part or incident of the Christian religion,
he ought to be sincere therein;
and it were more manly and Christian to act openly as one is inwardly persuaded,
than to profess one thing openly, and act another contrary in secret;
for that is hypocrisy, and we would not have one such among us.

Then I related to the bishop how far we think any society of Christians may
and ought to contribute to the necessary charge of a gospel ministry,
and how that matter stands among us at this day.
"`That we believe the true gospel ministry and Christian religion comes not by tradition,
imitation, or succession, as from the apostles and primitives,
but immediately from Christ himself; who, according to his promise,
hath ever been with his church, and ever will be, to the end of the world,
as a fountain of life and salvation unto her.
That he only hath right and power to call, sanctify, and qualify,
whomsoever he pleaseth as ministers and officers in his congregation,
or amongst his people; which is of his own seeking, congregating, baptizing, and saving,
by the revelation, operation, and agency of his Holy Spirit.
And we observe that now, as in times past,
he taketh the weak things of this world whereby to overpower the strong,
and foolish whereby to confound the wisdom of the wise,
that no flesh may boast before him.
And when at any time we are sitting together in silence, as we usually do,
waiting upon the Almighty for the influence of his Holy Spirit, that we may be comforted,
refreshed, and edified thereby,
if any one hath his understanding enlightened thereby into any edifying matter,
and moved and enabled to speak, the rest have proper qualifications, by the same Spirit,
to discern and judge, both of the soundness of his speech and mailer,
and also of the spirit and fountain from which his ministry doth arise;
and if from the Holy Spirit of Christ, who is Truth,
it hath acceptance with the congregation, and though but in a few words,
it is comfortable and edifying; for as the palate tasteth meats, so the ear,
or discerning faculties, of an illuminated, sanctified mind, distinguisheth words,
and the fountain from which they spring.
And such a person thus appearing, may so appear at another time,
and be enlarged in word and in power, and so on gradually,
till he hath given proof of his ministry to his friends and brethren, among whom,
in the neighborhood, he hath been exercised therein,
until he becomes a workman in the gospel, in some good degree fitted for the service;
and then it may so happen, as often it doth,
that this person is moved or called by the Word of God,
to travel in this service in some other places remote from his habitation,
which will take him off from his business whereby he maintains himself,
his wife and family; suppose him to be a cobbler of old shoes, a patcher of old clothes,
or the meanest mechanic that can be named, poor,
and not able to fit himself with common necessaries for his journey, he wanteth a horse,
though some only walk, clothing and the like;
in such a case the Friends of the meeting to which he belongs provide all such things,
and furnish him.
And if in that service he is so long from home, as that his horse fails,
and his clothes wear out, and necessaries are wanting unto him,
then the Friends where he travels, where his service is acceptable,
take care to furnish him till he returns to his family and business.
And in the time of his absence from them,
some Friend or Friends of the neighborhood visit his family, advise in his business,
and charitably promote it till he return.
But as to any other temporal advantages, or selfish motive of reward for such service,
there is no such thing among us.
For if our ministers should have the least view that way, and insisted upon it,
or our people were willing to gratify that desire,
we should then conclude we were gone off from
the true foundation of Christ and his apostles,
and become apostates.
But though our principles allow such assistance to our ministers as I have related;
yet I have not known any instance, save one, of any such help: for,
by the good providence of God,
our ministers have generally sufficient of their own to
support the charge of their travels in that service,
and are unwilling that the gospel should be chargeable to any;
only as their ministry makes way where they come,
their company is acceptable to their friends,
who afford them to eat and drink and lodge with them for a night or two, more or less,
as there may be occasion; which being freely given, and freely received,
w-e think is like unto the primitives, under the immediate conduct of the same Lord,
our Savior and director.`"

The bishop heard all these things with patience and candor,
not showing the least dislike to any part of what passed among us; and being ended,
he said, a little pleasantly, "`Then you are like Paul and Barnabas,
and we are like Silas and Timothy; you travel abroad to propagate the faith of Christ,
and we remain at home, taking care of things there.`"
And though it was on the second-day, when usually visited by his clergy,
he stayed with us alone till about the middle of the day, and at our departure said,
"`Gentlemen, let us, in our several stations, endeavor to promote universal love,
good-will and charity amongst mankind;
and I pray God bless you and prosper you in your undertakings;
for we ought to pray for one another, and desire the best things one for another.`"
And so we departed in peace and satisfaction.

=== With the Bishop of York, sir William Dawes, Baronet

Going to the Bishop of York to solicit his favor and concurrence in the House of Lords,
for altering the terms of our solemn affirmation,
as they then stood in the Acts of Parliament relating thereto,
being such as the body of our friends disliked, and could not comply with,
the bishop upon that occasion said,
"`I am for liberty of conscience where that is truly the case.
But there is a sort of people in this nation,
who dissent from the church on the pretense of conscience,
and yet can occasionally seek for offices and places of profit in the government;
(meaning the Presbyterians and their other sectaries) I cannot call this conscience,
but humor.`"
I replied, "`I am of the same mind: but that is not our case;
for we want no places or offices in the government,
but an exemption from such laws as tend to obstruct us
in our duty and service to the Almighty,
in such manner as we are in truth and sincerity
persuaded in our consciences we ought to worship,
fear, serve, and obey him, without any view to any other interest.`"

Then said the bishop, "`The words of the affirmation as it now is, are a solemn oath,
and so we (meaning the clergy) always, from the beginning, have understood them.`"
I replied, "`I know you have: for Dr. Tillotson, when dean of Paul`'s,
being required to preach a sermon before the
judges of the assize at Kingston upon Thames,
took his text in these words, '`Men verily swear by the greater, and an oath is, to them,
an end of all strife;`' from which he raised a discourse, intending therein to prove,
that oaths in judicature were not only lawful, but necessary under the gospel,
as well as under the law.
In which discourse he defines an oath in these words, or to this effect:
'`An oath is a solemn appeal to God, as a witness of the truth of what we say.`'
Which sermon being printed before we applied to the legislature for relief against oaths,
and '`the reasoning therein supposed to be strong in support of judicial swearing,
that Parliament would not grant us any relief in any other
terms but in the words of the doctor`'s definition of an oath,
a little improved.
For whereas he saith in his sermon.
An oath is a solemn appeal to God as a witness of the truth, etc.,
the Parliament added the word Almighty to the word God,
setting forth the Supreme Being in his highest attribute as a witness
in the most trivial cases occurring among the children of men,
whilst a mortal sitteth as judge in the cause.
And whereas,
the particle _a_ might denote the most High as a
witness only on the level with other witnesses,
the Parliament wisely and more reverently changed the
particle _a_ to the more proper words _the witness,_
by way of super-eminence, as justly due.
For where the God of Truth is witness, there needeth no other; and to suppose there doth,
is derogatory to his divine majesty, and blasphemous:
of which many of our people were aware, and therefore shunned it, and could not comply;
though some others not so well apprized of the nature of an oath, did use it:
but we as a body of people, never agreed to it; for our yearly meeting,
which represents us and our principles in the most collective and general manner,
hath always agreed to solicit the government for a more proper form,
when it might please God to incline their hearts to so much goodness;
and we hoping this is the time, have proposed the form now before the House.`"
The bishop replied, "`That he was not our enemy,
but could not stay at that time to see or hear any more on that subject,
being under an appointment about some business;`" and so we parted.

Some days after this I went to him again, accompanied only by John Irwin.
The bishop was alone, and received us very courteously,
and we renewed our applications to him on the same account;
and then the bishop was more plain with us, and said,
"`That he could not be for us on that account:
for though he did believe that the words of the affirmation, as they then stood,
were as solemn an oath as could be invented by the wit of man,
he understood our friends had generally complied
with them on every pinching or needful occasion,
as he had been informed by persons of unquestionable credit,
who had been exercised in the court of chancery.
He added,
That if there were any considerable number of us who conscientiously scrupled the words,
it ought to be duly considered by the House, and relief granted;
but to alter the laws for a very few, could hardly comport with prudence,
since the Parliament would greatly incur the censure of
the people of the nation if they should do it:
and added,
that he could not see any reason why such of us as took the
affirmation should be exempted from the common oaths of the nation.`"
By which I perceived he and they would have divided us if they could.

To this I replied,
"`That since the bishop himself understood the
words in the present Act to be a solemn oath,
I hoped he could not blame us, since it was a matter of conscience,
to which he was a professed friend, if sincere to our principles, though but a few,
that we made application for a form of a milder nature,
in which nothing like an oath was contained.
But as to the numbers on either side of the question among us the petitioners,
the proceedings against us in chancery, or any other courts, could not determine;
for few, in comparison of the body of our people, are prosecuted there:
and as there may be some who comply,
as not believing the words in the law to amount to an oath,
there are others also who have been prosecuted therein, who have so far scrupled them,
as rather to suffer the hard measures of the law than comply with that form.`"

Then said John Irwin, "`The bishop is misinformed in this point;
for I live in the north of England,
and know that there are very few of our friends in all these parts
who comply with the terms of the present affirmation on any account,
but generally suffer the force of the laws rather than
yield to a thing contrary to conscience.
And I have likewise, not long ago,
travelled through most parts of the west and south of this nation;
and upon a general observation, find,
that the greatest part of our friends everywhere are averse to the present affirmation,
and decline to use it as much as they can.`"

This I confirmed by adding, "`That I also had, for some years past,
travelled through most parts of the world where our people are, and observed,
that they are generally principled against the form of the present affirmation;
and this endeavor for further ease and liberty of conscience in the case,
is by consent and direction of our whole body,
represented in our yearly meeting here in London,
and not by any particular party or side only: so that I hope thy objection, as to a few,
is fully answered.
And if there were but a few in a nation under that circumstance,
charity ought not to be withheld for that reason,
since the '`eyes of the Lord are upon the righteous,
and his ears are open to their cry.`'`"

And as the bishop had asserted,
"`That the words of the former affirmation were a solemn oath,
and wished that all the judicial oaths of the nation
were in that form,`" and that party seemed to intend it,
and thereby elude our testimony against swearing,
it gradually drew the question into our discourse.
Whether Christ, in his doctrine, had prohibited all swearing;
they commonly alleging he only forbade profane swearing in conversation,
but not swearing in evidence?
I assumed the affirmative,
"`That the Lord Christ hath abolished all oaths out of his church;
and alleged for proof the fifth chapter of Matthew, where he saith,
'`Except your righteousness shall exceed the righteousness of the scribes and pharisees,
you shall in no case enter the kingdom of heaven.`'
And then, in several points, he sets forth what their righteousness did amount to, viz:
'`You have heard it was said by them of old time.
Thou shall not commit adultery; but I say unto you,
that whosoever looketh on a woman to lust after her,
hath committed adultery with her already in his heart.`'
Here, by taking away the cause, which is an unlawful desire in the heart,
he prevents the act, and makes it impossible, where there is no conception of desire;
for there begins the sin.
Again, '`You have heard it hath been said by them of old time.
Thou shalt love thy neighbor, (or friend) and hate thine enemy; but I say unto you,
love your enemies,`' etc.
Now where the heart is filled with the love of God,
in which Christ laid down his life for mankind, whilst yet enemies,
in which we can have love and compassion even for enemies, the cause of fighting,
and destroying one another as enemies, is taken away;
men are reconciled unto God through Christ, and one unto another in him; and so abiding,
cannot fight or destroy any more; as it is written,
'`They shall not hurt nor destroy in all iny holy mountain, saith the Lord.`'
Thus far in parables to introduce and illustrate the point in question;
and now home to that, '`You have heard it hath been said by them of old time,
Thou shalt not forswear thyself, but perform unto the Lord thine oaths;
but I say unto you, swear not at all.`'
Here the Lord begins with oaths of the highest nature,
used under the law on the most solemn occasions; which, whosoever falsified,
were perjured: and where there is swearing there may be perjury;
but where there is no swearing, there can be no perjury; where the cause is taken away,
the effect will cease.
And as he all along advanceth the morality of the gospel above that of the law,
in all other instances, so in this also: for if he had only forbid profane swearing,
he had done no more than Moses had done in the point; where it is said,
'`Thou shalt not take the name of the Lord thy God in vain;`'
which command every one breaks in a most impious sense,
who swears in conversation.
The Lord having thus prohibited the once lawful oaths,
he proceeds to explain the tendency of their invented oaths,
which they used in conversation, and on small occasions,
the breach whereof they did not seem to think was perjury,
'`Neither shalt thou swear by heaven; for it is God`'s throne,
and he who sweareth by the throne of God, sweareth by him that sitteth thereon:
neither shalt thou swear by the earth;
for it is his footstool:`' and by parity of consequence,
he that sweareth by the footstool of God, sweareth by him whose footstool it is.
'`Neither shalt thou swear by Jerusalem; for it is the city of the great King:
nor by thy head;
because thou canst not make one hair white or black:`'
both which result and terminate the same way;
such swear by the Lord, the King of kings,
whose name and temple were placed in Jerusalem in the time of the law; and the head,
as all the parts of man, being formed of the Lord, to swear thereby,
is to swear by his Maker.
Thus swearing by heaven, earth, Jerusalem, the altar, the gold thereon, the head,
or any creature, every oath, is forbidden in conversation, as well as judicial swearing;
'`but let your conversation (and communication) be yea, yea, nay, nay;
for whatsoever is more than these cometh of evil;`' of the evil one, which is the devil.
'`Leave off lying, and every man speak truth to his neighbor;
and use no higher asseveration in your speech,
than redoubling your yea on solemn occasions; as by example of your Lord, '`verily,
verily.`'`"

The bishop heard me with patience; and which gave me some surprise,
he made no other reply than this, "`Your interpretation of that Scripture is just.`"
Then he said, "`I read your books: I have read Barclay: he is no contemptible author;
yet I think he might be answered in some points.`"

I replied, '`That any ingenious person reading the works of another,
with design to find fault, may find something, especially in a large performance,
that he may think amiss, or wrest to such an appearance as he would have it.
But every work should be examined with an impartial view,
by a mind not prejudiced or prepossessed, comparing one part with another,
till the true mind, intent, and meaning of the writer be discovered; and then,
if any real error appear, to confute it by obvious truth; which needeth no gloss,
or color of sophistry:
but when an opponent subtly and willfully wrests the words of his antagonist,
and imposeth a meaning thereon which the author did not intend,
this opponent is a forger, combating his own invention, militates against himself,
and is felo de se in argument.`"
Upon this the bishop generously acknowledged,
"`That no man ought to oppose the works of another,
till he was fully master of the author`'s real sense,
and did at least believe it to be wrong or heterodox.`"

Then I said, "`That we had met with very hard usage in the House of Lords,
and particularly by the Bishop of Rochester (the same
that afterwards was banished for treasonable practices);
that at the same time when we, as a Christian people,
were addressing the legislature of our native country for liberty of conscience,
to serve God and our Lord Jesus Christ in the way we judge the most acceptable to him,
to be branded and accused in such a place and time, and on such an occasion,
as not being Christians, but compared, by him, with Jews, pagans,
and Mahometans! is very uncharitable, to say the least.`"

The bishop replied, "`I do not approve that usage of you;
but he explained himself to mean no more, than that you are not perfect Christians;
that is, in the way we initiate people into religion.`"

I answered, "`Then it remains for you to prove, that none can be perfect Christians,
unless initialed, at least, by you, or after your manner.`"
It being then near twelve o`'clock,
the bishop did not think proper to enter upon that subject.
And, as he had said in the sequel of this discourse, he had read our books,
I asked him "`if he had seen one styled, A Treatise of Oaths, written by William Penn?`"
he said "`he had not.`"
Then I said, "`We had abundance of votes collected there,
out of the writings of those you call fathers, on our side,
against swearing in any case or way.`"
To which he replied, "`That we ought not to depend upon numbers only,
but consider the weight also.`"
"`Granted,`" said I; "`but you have neither weight nor number, that ever I have heard of,
on your side; for all who wrote on that subject in the primitive church,
wrote against swearing, and not one in support of it under the gospel;
but that crept in gradually, with other errors,
as the church more and more degenerated into Jewish and
anti-christian practices in many instances.`"

Then this good tempered and affable bishop requested,
"`That if we had any books we valued more than others,
I would oblige him with a sight of them,
which I gave him some expectation of;`" and at parting, he took me by the hand,
as we passed out of the room in which we were, into another towards the door, and said,
"`I desire your prayers for me, as I also pray for you;
we ought all to pray one for another.`"
And so we parted in peace and good-will,
not the least word of warmth or a scornful look having appeared in all this conference.

I made inquiry after such of our books as I thought proper for him;
but he going soon after into his diocese of York, and I into Suffolk,
and across the country into the west in the service of Truth,
which look about seven months time,
I had no opportunity to see him till I returned to London,
and then went to his house in the Strand for that purpose;
but he not happening to be within,
and my concerns not allowing me another opportunity for some weeks,
in the mean time he was taken ill of the distemper whereof he died,
so that I did not see him any more: though his death,
through the respect I had conceived for his good qualities,
affected me with a friendly concern;
for he had as much of the gentleman as bishop in him,
and the former seemed rather predominant.

=== With Dr. Bradford, Bishop of Carlisle.

Peter Fearon, an ancient minister, and John Irwin aforesaid, being Cumberland men,
went to solicit Dr. Bradford, then Bishop of Carlisle, in our favor,
concerning the affirmation aforesaid, and altering the terms;
on occasion whereof he entered into an argument
with them on the point of oaths under the gospel,
asserting as usual, That Christ did only forbid swearing in communication;
but how they managed the point I know not, because not present,
and do not remember they related to me the particulars:
but as they intended to make him another visit on the same account,
they desired my company on that occasion,
and provided the Treatise of Oaths aforesaid as a present to him.
And we went to him together, finding none with him but Sykes, a moderate clergyman,
the same that printed a sermon on these words of Christ,
'`My kingdom is not of this world,`' before Benjamin Hoadley, then Bishop of Bangor,
preached his on the same text, which made so much noise among themselves and the nation.
The bishop received us mildly and courteously,
ordering seats to be set for us near himself;
and having heard our application for his favor
concerning further ease by a new affirmation,
and returned us a moderate and favorable answer,
he began again upon the subject of oaths, endeavoring to persuade us to think,
that Christ only prohibited oaths in common conversation or communication:
in which Sykes likewise concurred.
But they grounding their opinion only upon the
word communication in our English translation,
and the other two Friends leaving the matter to me, I answered,
"`That if Christ did not prohibit all oaths in that doctrine,
he did not advance the morality and righteousness of
the gospel above that of the law in that point,
as in every other particular there mentioned, he certainly did;
and added, That there is not a word in that text, which by any tolerable construction,
or by any propriety, can be rendered communication from the Greek original.
For the word is Aogou, the same used in the first of John, signifying word or speech;
which word is truth, signifying that the righteousness of the gospel,
abolishing oaths of all kinds,
requires mankind to speak the truth one to another in honesty and sincerity,
in all cases, as surely and certainly as they could upon oath.`"
And then desired the bishop to inspect his Greek Testament on that occasion,
which he readily did; and returning from his library,
confessed that the word there translated communication, was Aogou in the Greek,
and did not offer any further argument upon the subject.
Then I gave him the book, which the Friends had put into my hands,
telling him it was written on that subject, and desired him to peruse it at his leisure;
and so we left him in friendship and peace.

Some time after this, being at London, Walter Newbury and I went to the bishop again,
to request his favor in the House of Lords concerning the affirmation;
and he was come down to his hall, ready to take the air in his coach in the park,
but stopped when he saw us come in, and received us kindly, and presently said,
"`I have read your book, and will fetch it you.`"
I answered "`It was given him as a present, and desired it might be acceptable.`"
He thanked me, and immediately said,
"`That he believed that Christ and his apostles had forbid all oaths and swearing,
and that the time would come when there would
not be any such thing in the Christian world;
but added,
That the present state and circumstances of mankind could not bear such an exemption;
and said, you will own that some even among yourselves, in whom some immoralities appear,
are not fit for the liberty and exemption you request for your people.`"

I answered, "`That as mankind come into this world only in a natural state,
our children are as others in that respect;
and where not subject to the example and instructions given them, may,
and some of them do, degenerate into immoral practices of some sorts;
though our Society takes all practicable care to prevent it,
according to the stated rules among us, and by all Christian ways and means.
We pray for them, we example them, admonish, advise, exhort, reprove,
and rebuke them as need may require; and after all, if any one among us persist in evil,
we proceed against such according to the rules of our Society,
finally to deny them as not of our communion; and that is all we do,
or think we ought to do, in such cases.
And though some particular persons among us may not, in their younger times,
come fully up in all things into the perfection of our profession;
yet we hope in the main, as a Christian Society, we do.
And though some among us do fall into things disagreeable to our profession;
yet bearing false witness being so great an evil, and so easily discovered,
we hope none among us would be guilty of it; but if any should,
let the penalty of perjury be fully inflicted upon him:
and therefore we are encouraged to make this application.
And since thou art pleased to acknowledge thy sentiments,
that Christ and his apostles by their doctrine have
prohibited all oaths and swearing of every kind,
there must be a time wherein it must be begun to
be put in practice by some certain person,
persons, or community.
A nation is not born in a day;
nor did the Lord Jesus himself call and convert all his disciples at once;
it was a gradual work, though in the hand of him by whom the worlds were made.
And as the Christian world, so called,
hath suffered an exceeding great lapse and degeneracy from the doctrines, morality,
sanctity, and practice of Christ and his apostles, and the other early primitives;
so in the main they are more anti-christians than Christians.

The Almighty, who makes choice of the foolish things of this world,
whereby to confound the wisdom of the wise, the weak whereby to overcome the mighty,
and even things that are not, to bring to naught the things that are,
'`that no flesh may glory before him,`' hath raised up and chosen us as a people,
in and by whom to begin this reformation in religion, in doctrine and practice;
not by human power, for that is against us, nor by the wisdom of this world,
of which we have little, or the learn, ing or acquirements thereof,
which we do not pursue;
but by the same grace through which our Lord Jesus Christ laid
down his life upon the cross for the redemption of mankind;
wherewith being mercifully favored of God,
and having believed through the operation thereof in our hearts,
we have hitherto suffered all things for his name`'s sake,
which hath been permitted to be inflicted upon us by this and other nations,
where we have been raised up, or have come.
And we hope we have given Christian proof of our sincerity,
to the minds of all sober and thinking people,
that our religion is not some select notions of certain gospel truths,
but a real and practical thing;
wherein we are supported by the wisdom and power of God alone,
as witnesses for him on earth,
and to the redemption and salvation brought to pass for
us and in us through Jesus Christ our Lord.
And since ye profess yourselves to be Christian bishops,
(for we applied to them all) and we apply to you for
relief where our consciences are yet oppressed by laws,
and where you, by your offices in the national church, have a share for the time being,
in the legislature, who, under the Almighty alone, can relieve us; if you will not,
in your stations, contribute what you may towards that relief,
at whose door will the oppression lie?`"
The bishop heard me with Christian patience, and said,
"`We (meaning the bishops and former Parliament)
did not grant the affirmation that now is,
under any other view, on our part, than as a solemn oath; for so we always understood it,
and we thought your people had acquiesced under it: but seeing it does not suit you,
I am for liberty for tender consciences, where that is the case.
I am your friend herein.`"
Then we returned him our hearty acknowledgments; upon which he took us by the hands,
and gave us his good wishes, and we departed in peace and satisfaction.
He was, after the banishment of Atterbury, Bishop of Rochester,
before mentioned in my conference with the Bishop of York, translated, as their term is,
into the See of Rochester.
